### ISSUE TITLE
User Permission problem (can't choose user )

### ISSUE THREAD

**Issue by slob14** [danmunn/redmine_dmsf#1001]
Hi, thanks for the greate plugin! But  I have problem with user permission.
When tried to set permission on folder the button "Search for user to add" doesn't work (nothing to happend)

This is log:
F, [2019-04-25T17:18:40.354473 #1] FATAL -- : plugins/redmine_dmsf/app/controllers/dmsf_folder_permissions_controller.rb:52:in `users_for_new_users'
plugins/redmine_dmsf/app/controllers/dmsf_folder_permissions_controller.rb:34:in `new'
I, [2019-04-25T17:18:40.985785 #1]  INFO -- :   Parameters: {"project_id"=>"test"}
I, [2019-04-25T17:18:41.009578 #1]  INFO -- :   Current user: alex.coockoo (id=21)
I, [2019-04-25T17:18:41.063851 #1]  INFO -- : Completed 500 Internal Server Error in 78ms (ActiveRecord: 9.3ms)
F, [2019-04-25T17:18:41.070123 #1] FATAL -- :
F, [2019-04-25T17:18:41.070358 #1] FATAL -- : NoMethodError (undefined method `permissions_users' for nil:NilClass):

And this is my specification 
Environment:
  Redmine version                4.0.2.stable
  Ruby version                   2.6.2-p47 (2019-03-13) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.5
  Mercurial                      4.0
  Bazaar                         2.8.0
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_2chat                  0.3.1
  redmine_agile                  1.4.9
  redmine_base_deface            0.0.1
  redmine_base_stimulusjs        1.0.1
  redmine_bots                   0.3.1
  redmine_checklists             3.1.15
  redmine_contacts               4.2.4
  redmine_contacts_helpdesk      4.0.2
  redmine_contacts_invoices      4.1.8
  redmine_crm_mailchimp          1.0.3
  redmine_dmsf                   2.0.0
  redmine_finance                2.1.5
  redmine_impersonate            2.0.0
  redmine_intouch                1.4.0
  redmine_issue_field_visibility 1.0.1
  redmine_multiprojects_issue    4.0.0
  redmine_people                 1.4.0
  redmine_products               2.1.0
  redmine_questions              1.0.0
  redmine_recurring_tasks        0.3.1
  redmine_reporter               1.0.1
  redmine_resources              1.0.0
  redmine_sidekiq                2.1.0
  redmine_theme_changer          0.4.0
  redmine_wysiwyg_editor         0.3.4
  redmine_xapian                 2.0.0
  redmine_zenedit                1.0.2

Thank you in advance
Andrey

**Comment by picman** [comment]
Yes, it's a bug. It's related to new folder form only. As a work around you can create a folder and set permissions by editing the already existing folder.

**Comment by picman** [comment]
Fixed.

**Comment by slob14** [comment]
In my case it doesn't matter it is new folder or already existing. I even try to create folder under WebDav and after set permissions in but it doesn't work
