### ISSUE TITLE
Wrong file structure on migrate

### ISSUE THREAD

**Issue by skrech** [danmunn/redmine_dmsf#1003]
Hello,

I'm trying to migrate Redmine from version 1.1.1 to 4.0.3. Everything with the base Redmine migration went well but after I try to migrate the DMSF database there are some strange problems. 
The version of DMSF plugin is latest 2.0.1-devel branch as of today.

Watching the migration output I see that in file 07_dmsf_1_4_4.rb all my files are moved from flat structure under dmsf directory to dmsf/YYYY/MM file structure. If I understand correctly, this is supposed to be the latest file structure for this plugin. However, when the script reach 20170422104901_migrate_documents.rb it's trying to copy the same files but from dmsf/p_%project% directory to dmsf/YYYY/MM directory which fails with "Origin %file% doesn't exist" error.

Moreover, looking at the file structure after migration there are:

- directories starting with YYYY names, which have files in them; 
- p_%project% directories that are empty; 
- several files that are not moved (I guess this is because of "DmsfFileRevision.visible.find_each do |rev|" part in 07_dmsf_1_4_4.rb; more accurately the "visible" part ).

**Comment by picman** [comment]
Hm, quite a big step for migration. Not everything from your description is clear for me. However at least:
1) 07_dmsf_1_4_4.rb - visible. This is really wrong, I think. `visible` removed.
2) Empty p_%project% directories. This shouldn't happen but it is not actually a problem.
3) Expected file structure is YYYY/MM/file1, file2,...., so no files in the YYYY folder

**Comment by skrech** [comment]
Thanks for the fast reaction, picman!

Yes, big version jump. However, everything seems to be fine with the base installation, which is quite good. :)

I've updated to the newest commit (with `visible` removed) and now there are no leftover files in the dmsf directory after `rake redmine:plugins:migrate`! Good!

Now to clarify:
On `rake redmine:plugins:migrate` there is an error of type "Origin %file% doesn't exist" for every file in DMSF, because 20170422104901_migrate_documents.rb is searching for them in p_%project% directory, while all the files were copied from flat structure to YYYY/MM/file1..fileN by 07_dmsf_1_4_4.rb.

You are right that leftover p_%project% directories are harmless and Redmine+DMSF is working as expected after the migration (DMSF is searching for files in the correct YYYY/MM/ dir). However, it's good these directoris to be removed because they'll pollute the dmsf dir for years to come if the administrator is not aware that they are old-school file structure for this plugin. Moreover, the errors in the migration log are quite frightening, although they appear to be false alarms.

**Comment by picman** [comment]
Yes, if the origin file is not found also the part deleting the empty parent folder is skipped. Rather than change the migration, I'd leave it as it is. The fix might bring even more bugs. The case of a migration from Redmine 1 to Redmine 4 is quite rare, I think.
