### ISSUE TITLE
Wrong revision order after upgrading to DMSF 1.6.2

### ISSUE THREAD

**Issue by dinya** [danmunn/redmine_dmsf#1004]
I upgraded my environment to DMSF v1.6.2 from v1.5.9 and got wrong files revision order since v1.6.2 for some files. I can't understand why only for some files

Correct revisions order (newer first)

![dmsf_v1 6 2-correct_rev](https://user-images.githubusercontent.com/2182222/57094736-abce7880-6d2a-11e9-9f1e-540ee2cc303f.png)

Wrong revisions order (older first)

![dmsf_v1 6 2-wrong_rev](https://user-images.githubusercontent.com/2182222/57094737-ac670f00-6d2a-11e9-8fdd-681113b384ef.png)

I tried step-by-step upgrade 1.5.9 -> 1.6.0 -> 1.6.1 -> 1.6.2. The DMSF v1.6.2 has problem only.

My environment

```
Environment:
  Redmine version                3.4.10.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.11.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.5.3
  computed_custom_field          1.0.7
  custom_menu                    1.8.6
  easy_gantt                     1.12
  easy_mindmup                   1.4
  easy_wbs                       1.9
  redmine_agile                  1.4.6
  redmine_checklists             3.1.14
  redmine_default_custom_query   1.3.0
  redmine_dmsf                   1.6.2
  redmine_drawio                 0.8.3
  redmine_issue_tabs             1.3.2
  redmine_latex_mathjax_macro    0.3.0
  redmine_lightbox2              0.4.4
  redmine_mentions               0.0.1
  redmine_my_page                0.1.13
  redmine_presentation           0.2
  redmine_pygments               0.0.1
  redmine_sublime_markdown_codemirror 0.0.1
  redmine_tags                   3.2.2
  redmine_wiki_extensions        0.8.2
  redmine_wiki_issue_fields      0.5.9
  redmine_wiki_lists             0.0.9
  sidebar_hide                   0.0.8
  view_customize                 2.1.0
  wiki_graphviz_plugin           0.7.0
```

**Comment by PedroTeixido** [comment]
I had a similar problem and I wrote a patch to show issues order by major version minor version and revision in this order. So, versions are displayed the newer to older no matter in witch order they are uploaded.

[redmine_dmfs_fix_revision_history_order.patch.txt](https://github.com/danmunn/redmine_dmsf/files/3165673/redmine_dmfs_fix_revision_history_order.patch.txt)

**Comment by dinya** [comment]
Dear @PedroTeixido 

Unfortunely your patch is fixing the view only. But see at DMSF tree with wrong files revisions or at result of ``{{dmsf()}}`` or ``{{dmsftn()}}`` macros: it still links to wrong revisions. The constroller (?) should be fixed too.

**Comment by picman** [comment]
Revisions are sorted by `created_at` attribute. Because the revision number is assigned by the database engine and it's not guaranteed what will be the next ID. Can you check in your database whether `r7447.created_at < r7446.created_at`?

**Comment by dinya** [comment]
@picman 

> Can you check in your database whether r7447.created_at < r7446.created_at?

``SELECT id, dmsf_file_id, created_at FROM dmsf_file_revisions WHERE (id = 7447 OR id = 7446)``

id | dmsf_file_id | created_at
---|--------------|-----------
7446 | 3940 | 2019-04-19 09:55:**17**
7447 | 3940 | 2019-04-19 09:55:**18**

So ``r7447.created_at > r7446.created_at`` and it works as expected:

> Correct revisions order (newer first)
> 
> ![dmsf_v1 6 2-correct_rev](https://user-images.githubusercontent.com/2182222/57094736-abce7880-6d2a-11e9-9f1e-540ee2cc303f.png)

**But!**

``SELECT id, dmsf_file_id, created_at FROM dmsf_file_revisions WHERE (id = 7478 OR id = 7479)``

id | dmsf_file_id | created_at
---|--------------|-----------
7478 | 3956 | 2019-04-19 09:58:**38**
7479 | 3956 | 2019-04-19 09:58:**38**

So ``r7448.created_at == r7449.created_at`` and it correlates with

> Wrong revisions order (older first)
> 
> ![dmsf_v1 6 2-wrong_rev](https://user-images.githubusercontent.com/2182222/57094737-ac670f00-6d2a-11e9-8fdd-681113b384ef.png)

May be it is the problem --- my current storage engine hasn't the timestamp resolution less than seconds? Is it is the "hard" or the customizable parameter?

**Comment by picman** [comment]
Fixed by adding another order condition by _id_ if _created_at_ columns are equal.

**Comment by dinya** [comment]
@picman 

Is it possible to make the [backport](https://github.com/danmunn/redmine_dmsf/commit/1b6b9c4628957866ae9ba2c8b91a5c4ebeb5f5dc) to Redmine 3.4, say redmine_dmsf v1.6.3 :) (I tried, it works)?

**Comment by picman** [comment]
1. To have two revisions created in the same second is rare, I think.
2. The last release is 2.0.0; 1.6.3 is pretty old.
3. You can fix it manually in your installation according to 1b6b9c4.

**Comment by dinya** [comment]
Ok. Close.
