### ISSUE TITLE
'No Xapian search engine' Issue.

### ISSUE THREAD

**Issue by luckygg** [danmunn/redmine_dmsf#1005]
Hi all.

I have a question about installing the DMSF plugin.

OS: Windows 7
Redmine version : 4.0.3-2
DMSF version : 2.0.0

The last log is as below:

> No Xapian search engine interface for Ruby installed => Full-text search won't be available.
>                       Install a ruby-xapian package or an alternative Xapian binding (https://xapian.org).
> cannot load such file -- xapian

And I referred below link, but it can't resolve.
link1: http://www.redmine.org/boards/3/topics/17306
link2: https://github.com/xelkano/redmine_xapian/issues/84

Have you any idea how to resolve this issue?

Thank you :)

**Comment by picman** [comment]
See https://xapian.org/download and install Xapian binding as recommended.

**Comment by JohnArcher** [comment]
@luckygg Is that your only problem (then do what @picman suggested) or do you have trouble to run redmine after you installed the DMSF plugin? 
If the latter one: Do you use bitnami and the thin services stop running? Try to check out the latest devel-2.0.1 branch of DMSF and use this. This worked for us.

**Comment by luckygg** [comment]
@JohnArcher 
Oh, Thank you.
This issue is resolved!
