### ISSUE TITLE
office 2016 can not open word.

### ISSUE THREAD

**Issue by flyliu39** [danmunn/redmine_dmsf#1006]
I am using docker redmine 3.4, mysql 5.7, dmsf 1.6.2, office 2016. When I editting a word file, I found the office can not open it.Some tips like that, "opening http://localhost:3000/dmsf/webdav/fly/test-fly.docx" and then "Unable to download the information you requested".The port 3000 is my docker inner port, and access port is 38083.
Supplementary instruction, my office can open online file on [https://www.webdavserver.com/Usera16ea42/Sales/Australia/](url).So, I think my computer environment is normal.And I can open the url [http://localhost:38083/dmsf/webdav/](url), and can see all files I uploaded.
I have checked product.log, but can not find any error log.here is part of the logs.Perfectly configuring dmsf have took me 4 weeks, and I'm going crazy.Thx.

> F, [2019-05-08T10:24:00.258806 #1] FATAL -- : 
> ActionController::RoutingError (No route matches [OPTIONS] "/"):
>   actionpack (4.2.11.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
>   actionpack (4.2.11.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
>   railties (4.2.11.1) lib/rails/rack/logger.rb:38:in `call_app'
>   railties (4.2.11.1) lib/rails/rack/logger.rb:22:in `call'
>   actionpack (4.2.11.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
>   rack (1.6.11) lib/rack/methodoverride.rb:22:in `call'
>   rack (1.6.11) lib/rack/runtime.rb:18:in `call'
>   activesupport (4.2.11.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
>   actionpack (4.2.11.1) lib/action_dispatch/middleware/static.rb:120:in `call'
>   rack (1.6.11) lib/rack/content_length.rb:15:in `call'
>   rack (1.6.11) lib/rack/sendfile.rb:113:in `call'
>   railties (4.2.11.1) lib/rails/engine.rb:518:in `call'
>   railties (4.2.11.1) lib/rails/application.rb:165:in `call'
>   rack (1.6.11) lib/rack/lock.rb:17:in `call'
>   rack (1.6.11) lib/rack/content_length.rb:15:in `call'
>   rack (1.6.11) lib/rack/handler/webrick.rb:88:in `service'
>   /usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
>   /usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
>   /usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
> 
> 
> I, [2019-05-08T10:30:29.111730 #1]  INFO -- : Started GET "/projects/fly/dmsf" for 172.21.0.1 at 2019-05-08 10:30:29 +0000
> I, [2019-05-08T10:30:29.114675 #1]  INFO -- : Processing by DmsfController#show as HTML
> I, [2019-05-08T10:30:29.115169 #1]  INFO -- :   Parameters: {"id"=>"fly"}
> I, [2019-05-08T10:30:29.184899 #1]  INFO -- :   Current user: admin (id=1)
> I, [2019-05-08T10:30:29.209907 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.4ms)
> I, [2019-05-08T10:30:29.243995 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.3ms)
> I, [2019-05-08T10:30:29.245055 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (15.5ms)
> I, [2019-05-08T10:30:29.272236 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.1ms)
> I, [2019-05-08T10:30:29.273268 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (9.5ms)
> I, [2019-05-08T10:30:29.290770 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.2ms)
> I, [2019-05-08T10:30:29.292124 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (15.6ms)
> I, [2019-05-08T10:30:29.307028 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.1ms)
> I, [2019-05-08T10:30:29.307647 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (12.1ms)
> I, [2019-05-08T10:30:29.310650 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (96.8ms)
> I, [2019-05-08T10:30:29.327634 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.7ms)
> W, [2019-05-08T10:30:29.329435 #1]  WARN -- : /usr/src/redmine/public/plugin_assets/redmine_dmsf/javascripts/plupload/js/i18n/zh.js not found
> I, [2019-05-08T10:30:29.330478 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (5.5ms)
> I, [2019-05-08T10:30:29.335292 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (2.7ms)
> I, [2019-05-08T10:30:29.336640 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (129.2ms)
> I, [2019-05-08T10:30:29.389299 #1]  INFO -- : Completed 200 OK in 274ms (Views: 152.7ms | ActiveRecord: 101.1ms)
> I, [2019-05-09T01:57:25.762113 #1]  INFO -- : Started GET "/projects/fly/dmsf" for 172.21.0.1 at 2019-05-09 01:57:25 +0000
> I, [2019-05-09T01:57:25.768377 #1]  INFO -- : Processing by DmsfController#show as HTML
> I, [2019-05-09T01:57:25.769445 #1]  INFO -- :   Parameters: {"id"=>"fly"}
> I, [2019-05-09T01:57:25.851534 #1]  INFO -- :   Current user: admin (id=1)
> I, [2019-05-09T01:57:25.875894 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.2ms)
> I, [2019-05-09T01:57:25.892570 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.1ms)
> I, [2019-05-09T01:57:25.893679 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (9.3ms)
> I, [2019-05-09T01:57:25.902868 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.1ms)
> I, [2019-05-09T01:57:25.903546 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (6.8ms)
> I, [2019-05-09T01:57:25.912921 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.1ms)
> I, [2019-05-09T01:57:25.913561 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (7.1ms)
> I, [2019-05-09T01:57:25.923627 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.1ms)
> I, [2019-05-09T01:57:25.924557 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (8.0ms)
> I, [2019-05-09T01:57:25.926764 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (48.7ms)
> I, [2019-05-09T01:57:25.940932 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.0ms)
> W, [2019-05-09T01:57:25.942550 #1]  WARN -- : /usr/src/redmine/public/plugin_assets/redmine_dmsf/javascripts/plupload/js/i18n/zh.js not found
> I, [2019-05-09T01:57:25.943825 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (4.1ms)
> I, [2019-05-09T01:57:25.946502 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (0.9ms)
> I, [2019-05-09T01:57:25.948000 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (73.4ms)
> I, [2019-05-09T01:57:25.991945 #1]  INFO -- : Completed 200 OK in 222ms (Views: 99.9ms | ActiveRecord: 102.2ms)
> I, [2019-05-09T01:57:28.745372 #1]  INFO -- : Started GET "/projects/fly/dmsf/context_menu?utf8=%E2%9C%93&authenticity_token=iXH5PalsKLTsRg%2Bmx5178gGFp%2Bi4tpsVH6%2FwDPdkSTGovY%2BdtDa4%2BRB4ZEJBHRg1qw7SRSNvQrjop7r%2FxqmdLA%3D%3D&action=&ids%5B%5D=file-3" for 172.21.0.1 at 2019-05-09 01:57:28 +0000
> I, [2019-05-09T01:57:28.748907 #1]  INFO -- : Processing by DmsfContextMenusController#dmsf as */*
> I, [2019-05-09T01:57:28.749457 #1]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"iXH5PalsKLTsRg+mx5178gGFp+i4tpsVH6/wDPdkSTGovY+dtDa4+RB4ZEJBHRg1qw7SRSNvQrjop7r/xqmdLA==", "ids"=>["file-3"], "id"=>"fly"}
> I, [2019-05-09T01:57:28.832890 #1]  INFO -- :   Current user: admin (id=1)
> I, [2019-05-09T01:57:28.845516 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/dmsf.html.erb (8.1ms)
> I, [2019-05-09T01:57:28.846638 #1]  INFO -- : Completed 200 OK in 96ms (Views: 8.6ms | ActiveRecord: 82.1ms)
> I, [2019-05-09T02:14:42.346090 #1]  INFO -- : Started GET "/projects/fly/dmsf/context_menu?utf8=%E2%9C%93&authenticity_token=iXH5PalsKLTsRg%2Bmx5178gGFp%2Bi4tpsVH6%2FwDPdkSTGovY%2BdtDa4%2BRB4ZEJBHRg1qw7SRSNvQrjop7r%2FxqmdLA%3D%3D&action=&ids%5B%5D=file-3" for 172.21.0.1 at 2019-05-09 02:14:42 +0000
> I, [2019-05-09T02:14:42.351976 #1]  INFO -- : Processing by DmsfContextMenusController#dmsf as */*
> I, [2019-05-09T02:14:42.352676 #1]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"iXH5PalsKLTsRg+mx5178gGFp+i4tpsVH6/wDPdkSTGovY+dtDa4+RB4ZEJBHRg1qw7SRSNvQrjop7r/xqmdLA==", "ids"=>["file-3"], "id"=>"fly"}
> I, [2019-05-09T02:14:42.396249 #1]  INFO -- :   Current user: admin (id=1)
> I, [2019-05-09T02:14:42.406942 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/dmsf.html.erb (7.1ms)
> I, [2019-05-09T02:14:42.408188 #1]  INFO -- : Completed 200 OK in 55ms (Views: 7.1ms | ActiveRecord: 42.1ms)

**Comment by picman** [comment]
1) Are you able to write to the destination folder via WebDAV?
2) Do you open files from MS Office directly or you use the Edit command from the context menu in DMS UI?
3) Are you able to edit common TXT files using a text editor via WebDAV?
4) How about upgrade to DMSF 2.0?

**Comment by flyliu39** [comment]
1. Yes, I can
2. Directly
3. Yes, I can
4. Sorry, no try, not available recently

**Comment by picman** [comment]
I'm not sure nor, but HTTP X HTTPS might be a problem too. MS Office refuses to edit a document via HTTP, I think. And try to post just the log part related to the opening phase.
