### ISSUE TITLE
Description field trunkates on blank line.

### ISSUE THREAD

**Issue by skrech** [danmunn/redmine_dmsf#1008]
Hello,

After switching to Redmine 4.0.3 and DMSF 2.0.1dev we notice that if there is a blank line in the description field of an uploaded file, the description is truncated to include only the text before the blank line.

Example:
Type in the desc field the following text:
```
aaa
bbb

ccc
```
After uploading the file the desc field contains only:
```
aaa
bbb
```

Note, when pressing on Preview button before upload of the file everything is shown as intended.

**Comment by PedroTeixido** [comment]
I have the same issue with Redmine 3.4.2.stable and DMSF 1.6.0 

Any help is appreciated :-)

**Comment by PedroTeixido** [comment]
Excellent!!! :-)

Same thing needs to be done for the comment field (around 30 lines bellow). Do you want me to create another issue to associate the commit or you can recycle this one?

Thank you!!!

**Comment by picman** [comment]
Fixed in comments too.
