### ISSUE TITLE
Installing Redmine in a sub URI

### ISSUE THREAD

**Issue by n0nel** [danmunn/redmine_dmsf#1010]
If Redmine is running with sub URI, the upload area of the DMSF page will default to English.
And the following error is recorded in production.log:

`(REDMINE_ROOT)/public/(sub_uri)/plugin_assets/redmine_dmsf/javascripts/jquery.dataTables/locales/xx.json not found`
`(REDMINE_ROOT)/public/(sub_uri)/plugin_assets/redmine_dmsf/javascripts/plupload/js/i18n/xx.js not found`

How can I fix it?

To avoid this problem, I create temporary a "sub_uri" symbolic link under (REDMINE_ROOT)/public.

The following line is added to (REDMINE_ROOT)/config/environment.rb to run Redmine with sub URI.
`Redmine::Utils::relative_url_root = "/sub_uri"`

**Comment by picman** [comment]
Fixed.

**Comment by n0nel** [comment]
This patch is working good!
Thanks.
