### ISSUE TITLE
Error: FUNCTION redmine_companyname.mroonga_command does not exist

### ISSUE THREAD

**Issue by federicocandiago** [danmunn/redmine_dmsf#1014]
Hello, 

I just installed redmine_dmsf 1.6.2 on Windows 10, installed the gems, run the migrations and restarted the server.
After restart, Redmine works well but if I try to enter the plugin settings the server gives a 500 error with the following output in production.log:

`{ActiveRecord::StatementInvalid=>"Mysql2::Error: FUNCTION companyname.mroonga_command does not exist: select mroonga_command(\n         'select',\n         'table', 'issue_contents',\n         'output_columns', 'issue_id, _score',\n         'filter', CONCAT('(contents *S \"', mroonga_escape('richiesta di prova\\n\\n\\n\\n\\n\\n'), '\") && issue_id != 3267', ' && ((is_private == false && in_values(project_id, 7, [...] 1294)))'),\n         'limit', '5',\n         'sort_keys', '-_score'\n       )\n"}`

I tried to google the error but I can't find any information related to this error. What could it be?
Any help would be greatly appreciated.

Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.4.4-p296 (2018-03-28) [x64-mingw32]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

**Comment by picman** [comment]
`mroonga_command` has nothing to do with the plugin. Any other plugins installed?

**Comment by federicocandiago** [comment]
Yes, I can confirm the issue was not caused by redmine_dmsf, as after rolling back all other plugins, uninstalling and re-installing them it works correctly. 

Thanks for your response!
