### ISSUE TITLE
WebDAV client error

### ISSUE THREAD

**Issue by s-tkt** [danmunn/redmine_dmsf#1015]
Accessing from WebDAV client with bitnami redmine 4.0.3 occours:

Started PROPFIND "/redmine/dmsf/webdav/" for 203.138.115.155 at 2019-06-21 14:48:22 +0900
Processing WebDAV request: /redmine/dmsf/webdav/ (for 203.138.115.155 at 2019-06-21 05:48:22 UTC) [PROPFIND]
Scoped order is ignored, it's forced to be batch order.
WebDAV Error: undefined method `basename' for DAV4Rack::File:Class
undefined method `basename' for DAV4Rack::File:Class

(from production.log)

WebDAV client i used could access through dmsf before bmsf v2.0.0.

Thanks for your any information.

**Comment by picman** [comment]
Please post a bigger chunk of the log file. I believe there is more information related to the error.

**Comment by s-tkt** [comment]
That's all. Again I put messages from log file.(I tried 2times.)

`Started PROPFIND "/redmine/dmsf/webdav" for 203.138.115.155 at 2019-06-25 07:52:36 +0900
Processing WebDAV request: /redmine/dmsf/webdav/ (for 203.138.115.155 at 2019-06-24 22:52:36 UTC) [PROPFIND]
Scoped order is ignored, it's forced to be batch order.
WebDAV Error: undefined method `basename' for DAV4Rack::File:Class
undefined method `basename' for DAV4Rack::File:Class
Started PROPFIND "/redmine/dmsf/webdav" for 203.138.115.155 at 2019-06-25 07:54:36 +0900
Processing WebDAV request: /redmine/dmsf/webdav/ (for 203.138.115.155 at 2019-06-24 22:54:36 UTC) [PROPFIND]
Scoped order is ignored, it's forced to be batch order.
WebDAV Error: undefined method `basename' for DAV4Rack::File:Class
undefined method `basename' for DAV4Rack::File:Class`

I also put error log of Apche
`App 4439 stderr: [ 2019-06-25 08:02:20.9716 4491/0x000055b6b7fb3a60(Worker 1) utils.rb:87 ]: *** Exception NoMethodError in Rack application object (undefined method `to_i' for #<NoMethodError:0x000055b6bb16d178>
App 4439 stderr: Did you mean?  to_s) (process 4491, thread 0x000055b6b7fb3a60(Worker 1)):
App 4439 stderr:        from /opt/redmine/ruby/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/content_length.rb:18:in `call'
App 4439 stderr:        from /opt/redmine/ruby/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
App 4439 stderr:        from /opt/redmine/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
App 4439 stderr:        from /opt/redmine/ruby/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/urlmap.rb:68:in `block in call'
App 4439 stderr:        from /opt/redmine/ruby/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `each'
App 4439 stderr:        from /opt/redmine/ruby/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `call'
App 4439 stderr:        from /opt/redmine/ruby/lib/ruby/gems/2.5.0/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
App 4439 stderr:        from /opt/redmine/ruby/lib/ruby/gems/2.5.0/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
App 4439 stderr:        from /opt/redmine/ruby/lib/ruby/gems/2.5.0/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
App 4439 stderr:        from /opt/redmine/ruby/lib/ruby/gems/2.5.0/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
App 4439 stderr:        from /opt/redmine/ruby/lib/ruby/gems/2.5.0/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
[ 2019-06-25 08:02:20.9719 4392/7f9fafdcc700 age/Cor/Con/InternalUtils.cpp:112 ]: [Client 1-42] Sending 502 response: application did not send a complete response`

**Comment by picman** [comment]
Fixed.
