### ISSUE TITLE
Add ability to "link to" repositories via redmine source

### ISSUE THREAD

**Issue by mfrankk1973** [danmunn/redmine_dmsf#1016]
On occasion, files are loaded into the redmine repository; it would be convenient to be able to link to those files via "source:some/file" for portability.  (URL linking requires FQDN; this can be a problem if there is a need to rehost Redmine)

**Comment by picman** [comment]
FQDN is not necessary. You can use a relative path.
![image](https://user-images.githubusercontent.com/779003/228820542-8339ba00-dc8c-4f16-89e4-0494a4bad979.png)
