### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by Drexlin** [danmunn/redmine_dmsf#1018]
Any help would be much appreciated!

I installed dmsf on my Redmine 3.4.4 instance and it works (mostly), except for the fact that I can't upload files!

(see attached screenshots)
When I press the [Choose Files] button, it brings up the Browse File dialog, I select my file and click OK. Then if I choose [Upload], I get a blank screen and the only button is [Commit]. When I click [Commit], it goes back to the Documents page and no upload occurs.

I've checked all my permissions and everything appears to be in order. Any suggestions on where to check next?

** As an additional note, why are there 6 extra columns after the Author field (circled in red)?

![dmsf issue](https://user-images.githubusercontent.com/12022669/60371334-f127c300-99c6-11e9-909a-eabb42b44f6b.png)
![dmsf upload](https://user-images.githubusercontent.com/12022669/60371532-7f9c4480-99c7-11e9-8259-cec7e6d98956.png)

**Comment by picman** [comment]
Check log/production.log file for any errors.

**Comment by Drexlin** [comment]
I think I figured it out. Thanks for the tip!

I copied redmine/plugins/redmine_dmsf/assets/* to redmine/public/plugin_assets/redmine_dmsf. Is there an installation step I missed to copy these files? Sorry, I'm new to Redmine and installing plugins. Thanks.

**Comment by picman** [comment]
No, the installation procedure consist just from copying of _redmine_dmsf_ folder into the plugin sub-folder and launching the database migration. The assets should be copied by Redmine itself during the application start.
