### ISSUE TITLE
Conflict with other plugins

### ISSUE THREAD

**Issue by iq2luc** [danmunn/redmine_dmsf#1020]
In the release notes for 1.6.1 is mentioned:
> alias_method_chain has been replaced with prepend. Not directly but using RedmineExtensions::PatchManager. Consequently, there might occur conficts with plugins which overwrite the same methods.

...and indeed there are a conflicts with other plugins, for example: https://github.com/hidakatsuya/redmine_default_custom_query/issues/37#issuecomment-504361915

Is it possible to do something about it so DMSF may be used alongside other plugins?

Thank you.

**Comment by picman** [comment]
Yes, use the latest release of this plugin.
