### ISSUE TITLE
Installation Problem with redmine 4.0.4

### ISSUE THREAD

**Issue by Bilderbuch007** [danmunn/redmine_dmsf#1021]
I´ve got Problems with installing the plugin on debian stretch with ruby 5.2.3 and rails 2.3.3p222.
I got the following Errormessage:

[ 2019-07-10 11:39:48.8057 15637/7faad56eb700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /opt/redmine-4.0.4: An error occurred while starting up the preloader.
  Error ID: ce0bd1d5
  Error details saved to: /tmp/passenger-error-RlTW9N.html
  Message from application: No such file to load -- mime/types.rb (LoadError)
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
  /opt/redmine-4.0.4/plugins/redmine_dmsf/lib/dav4rack/resources/mongo_resource.rb:4:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:378:in `block in require_or_load'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in `load_interlock'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:356:in `require_or_load'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:334:in `depend_on'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:246:in `require_dependency'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in `each'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in `block in eager_load!'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in `each'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in `eager_load!'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:356:in `eager_load!'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in `each'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
  /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
  /opt/redmine-4.0.4/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

[ 2019-07-10 11:39:48.8107 15637/7faad6ff0700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is ce0bd1d5. Please see earlier logs for details about the error.

Can someone give me an advise what to do?

**Comment by picman** [comment]
Duplicates  #992.
