### ISSUE TITLE
project menu is not displayed in Redmine 4.0.3

### ISSUE THREAD

**Issue by hyama99** [danmunn/redmine_dmsf#1023]
Hi, I installed Redmine 4.0.3 and DMSF plugin.
When I logged in as admin or a user with system administration right, dmsf menu is displayed in project_menu, if I checked dmsf in its project configuration. However, if I logged in as another user without system administration right, dmsf menu is not displayed in project menu.

Thank you in advance.
Best regards,
Hideki.

**Comment by tainewoo** [comment]
Hi,
I think you should need to enable permissions for different kinds of roles for DMSF, before they can have the rights to browse/view them, by "Administration -> Roles and permissions".

**Comment by hyama99** [comment]
Dear Tainewoo,

Thank you very much. I resolved my problem. For the biginners like me, would you add the above reply to clause 7 in Setting in Git page?
Thank you in advance.

Best regards,
Hideki

**Comment by tainewoo** [comment]
Hi hyama99,
It's good that your problem is resolved. But i'm user of this plugin too.  pciman maintains this plugin, maybe he will help on it.

**Comment by picman** [comment]
Added.
