### ISSUE TITLE
"Edit" can't transfer the file content to office

### ISSUE THREAD

**Issue by tainewoo** [danmunn/redmine_dmsf#1024]
DMSF settings:
WebDAV: Activated.
WebDAV strategy: read-only.

Steps:
right click on a document from DMS, such as a word documents.
click on the "Edit" button.
Word application of office will be call, and after loading, no document is opened.
And check the log, "Processing WebDAV request: xxxx" completed with no error.

===============================================

DMSF settings:
WebDAV: Deactivated.
WebDAV strategy: read-only.

Steps:
right click on a document from DMS, such as a word documents.
the "Edit" button is also available, click on the "Edit" button.
Word application of office will be call, and after loading, no document is opened.
And check the log, "Processing WebDAV request: xxxx" completed with no error.

==================================
Redmine version: 4.0.2 and 4.0.3
dmsf version: master, tip.

**Comment by picman** [comment]
M$ Office version? DMSF version? And post a chunk of the log related to the document opening, please.

**Comment by picman** [comment]
It might be related to  #1006.

**Comment by tainewoo** [comment]
Hi Picman,
Office: Office2016
Site protocal: HTTP
hosting site under sub url: /redmine

Log:

Started GET "/redmine/projects/xxxxxxxxx/dmsf/context_menu?utf8=%E2%9C%93&authenticity_token=woEItUME%2FPqwzT96KITy8gbp5HXLnpYDXi3tyl2DDahei1LgZ56stJNnqomPYvM8%2B5jOEnpne9Cs3MpxzrIg0g%3D%3D&action=&dmsf_folder%5Bcustom_field_values%5D%5B28%5D%5B%5D=&ids%5B%5D=file-1" for 10.28.24.76 at 2019-07-19 18:04:08 +0800
Processing by DmsfContextMenusController#dmsf as */*
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"woEItUME/PqwzT96KITy8gbp5HXLnpYDXi3tyl2DDahei1LgZ56stJNnqomPYvM8+5jOEnpne9Cs3MpxzrIg0g==", "dmsf_folder"=>{"custom_field_values"=>{"28"=>[""]}}, "ids"=>["file-1"], "id"=>"xxxxxxxxx"}
  Current user: admin (id=1)
  Rendering plugins/redmine_dmsf/app/views/dmsf_context_menus/dmsf.html.erb
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/dmsf.html.erb (3.6ms)
Completed 200 OK in 55ms (Views: 3.2ms | ActiveRecord: 48.6ms)
Started OPTIONS "/redmine/dmsf/webdav/xxxxxxxxx/Guide/" for 10.28.24.76 at 2019-07-19 18:04:10 +0800
Processing WebDAV request: /redmine/dmsf/webdav/xxxxxxxxx/Guide/ (for 10.28.24.76 at 2019-07-19 10:04:10 UTC) [OPTIONS]
Completed in: 1 ms | 401 [http://yyyyyyy.zzzzzz.com/redmine/dmsf/webdav/xxxxxxxxx/Guide/]

**Comment by tainewoo** [comment]
Seems there is 401 authentication error in the last line of log?

**Comment by tainewoo** [comment]
Another log, use normal user, include both open/close office:

Started GET "/redmine/projects/xxxxxxx/dmsf/context_menu?utf8=%E2%9C%93&authenticity_token=lvXJhMAULwirq341%2BoFUmbOzWPrTBn39oDLYhzghj8AK%2F5PR5I5%2FRogB68ZdZ1VXTsJynWL%2FkC5Sw%2F88qxCiug%3D%3D&action=&dmsf_folder%5Bcustom_field_values%5D%5B28%5D%5B%5D=&ids%5B%5D=file-1" for 10.28.24.76 at 2019-07-19 18:10:05 +0800
Processing by DmsfContextMenusController#dmsf as */*
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"lvXJhMAULwirq341+oFUmbOzWPrTBn39oDLYhzghj8AK/5PR5I5/RogB68ZdZ1VXTsJynWL/kC5Sw/88qxCiug==", "dmsf_folder"=>{"custom_field_values"=>{"28"=>[""]}}, "ids"=>["file-1"], "id"=>"xxxxxxx"}
  Current user: TaineWoo (id=5)
  Rendering plugins/redmine_dmsf/app/views/dmsf_context_menus/dmsf.html.erb
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/dmsf.html.erb (3.6ms)
Completed 200 OK in 265ms (Views: 3.2ms | ActiveRecord: 258.0ms)
Started OPTIONS "/redmine/dmsf/webdav/xxxxxxx/Guide/" for 10.28.24.76 at 2019-07-19 18:10:06 +0800
Processing WebDAV request: /redmine/dmsf/webdav/xxxxxxx/Guide/ (for 10.28.24.76 at 2019-07-19 10:10:06 UTC) [OPTIONS]
Completed in: 1 ms | 401 [http://yyyyyy.zzzzzzz.com/redmine/dmsf/webdav/xxxxxxx/Guide/]
Started POST "/redmine/pretend/restore" for 10.28.24.76 at 2019-07-19 18:10:20 +0800
Processing by PretendController#restore as HTML
  Parameters: {"authenticity_token"=>"lvXJhMAULwirq341+oFUmbOzWPrTBn39oDLYhzghj8AK/5PR5I5/RogB68ZdZ1VXTsJynWL/kC5Sw/88qxCiug=="}
  Current user: TaineWoo (id=5)
1 stop pretend
Redirected to http://yyyyyy.zzzzzzz.com/redmine/projects/xxxxxxx/dmsf?folder_id=1
Completed 302 Found in 81ms (ActiveRecord: 74.8ms)

**Comment by picman** [comment]
It duplicates #1006. M$ Office refuses authentication over HTTP. You must host your Redmine over HTTPS.
