### ISSUE TITLE
In some occasions activity tab freezes the whole server

### ISSUE THREAD

**Issue by nikosfrangakis** [danmunn/redmine_dmsf#1025]
I am running a redmine installation with about 30 projects and around 1500 users. All projects use dmsf.

In some projects (1-2) when i go to the activity tab, the servers tops its cpu usage indefinitely, till i manually kill the process.

This behavior is observed since i upgrade to ruby 2.6.2, redmine 4 and dmsf 2.0.0

I was unsuccessful in gathering any meaningful logs, but my knowledge of ruby and how to gather logs is limited.

The problem occurs only if the checkboxes of " Document accesses" and "Document revisions" are checked.

Some logs from production.log
Started GET "/projects/xxx-xx/activity?utf8=%E2%9C%93&show_issues=1&show_wiki_edits=1&show_dmsf_file_revision_accesses=1&submit=Apply" for 147.102.5.155 at 2019-07-18 12:43:07 +0300
Processing by ActivitiesController#index as HTML
  Parameters: {"utf8"=>"✓", "show_issues"=>"1", "show_wiki_edits"=>"1", "show_dmsf_file_revision_accesses"=>"1", "submit"=>"Apply", "id"=>"xxx-xx"}
  Current user: nikos (id=3)
  Rendering activities/index.html.erb within layouts/base

This will never return.

Thanks for any support

**Comment by yzzy** [comment]
What database do you use?
I've heard that MySQL/MariaDB has numerous problem with big Redmine installations and at first it appears on activity page. People removed all the plugins but this problem persisted.

**Comment by nikosfrangakis** [comment]
mariadb  Ver 15.1 Distrib 10.1.38-MariaDB

**Comment by yzzy** [comment]
I think you should migrate to Postgres...

**Comment by picman** [comment]
It's very probably related to #1019. Check with v2.0.1. If the problem persists, we will reopen this issue.

BTW, MySQL/MariDB is capable of managing really big Redmine installation. Believe me. A DB dump of one of my Redmine has 2GB at the moment and I haven't observed any problems related to the database engine.
