### ISSUE TITLE
Feature request: replace Files module or import from Files to DMSF

### ISSUE THREAD

**Issue by gen555** [danmunn/redmine_dmsf#1031]
It would be useful to have a feature to totally replace File module and move all Files uploads to DMSF so users can collaborate by WebDav and use versioning for uploaded files.
As a "quick wins" and "proof of usefulness" I think it's possible to make "import job" based on dmsf_convert_documents.rake to move files from Files module to DMSF to according Issue folder by periodic job. If file already exists, the import job should import it as a new revision.
So if someone needs the feature, it would be as easy as to schedule the job.

**Comment by tainewoo** [comment]
+1 also to replace the Document module

**Comment by gen555** [comment]
It's possible to replace Document module now - disable the module and convert by dmsf_convert_documents.rake

**Comment by picman** [comment]
You've answered your own question. So we can close it, right?

**Comment by gen555** [comment]
No, my request was to replace Files module too.

пт, 23 авг. 2019 г. в 11:13, Karel Picman <notifications@github.com>:
