### ISSUE TITLE
Deprecate silverlight support?

### ISSUE THREAD

**Issue by vadave** [danmunn/redmine_dmsf#1032]
Is there any interest/willingness to deprecate silverlight support? We've experienced an issue where the silverlight bits in the javascript triggers a rule in our security appliances, causing DMSF to break.  We've had to modify the code locally to take out the silverlight bits. 

Microsoft has officially [announced end of support for silverlight](https://support.microsoft.com/en-us/help/4511036/silverlight-end-of-support), and neither Chrome, Firefox, nor Edge currently support Silverlight.

**Comment by picman** [comment]
It makes sense. Silverlight is no more supported.
How about Flash and HTML4. Shouldn't we keep just HTML5?

**Comment by vadave** [comment]
I'm no fan of flash, but browsers are still supporting it at the moment (although it's disabled by default). So I can go either way as far as deprecating flash. I'd be fine keeping HTML4 support...I still occasionally stumble across folks stuck with IE as their default browser, and its HTML5 support is very much lacking.

**Comment by picman** [comment]
Okay. Let's keep the other frameworks.
