### ISSUE TITLE
dmsf install on Redmine 4.0.4-5

### ISSUE THREAD

**Issue by brackovic** [danmunn/redmine_dmsf#1036]
Hallo, i am trying to install dmsf plugin to Redmine 4.0.4-5 Windows 10. I dont have any errors but afther installation when i try to restart Thin Servers, both thin Server goes to red after few sec.. I try to google for problem  but without success. Any idea? ( I have two more plugins installed contacts from RedmineUp and Pushover )
Thanks in Advance

**Comment by picman** [comment]
Duplicates #1033.
