### ISSUE TITLE
webdav not open file

### ISSUE THREAD

**Issue by nsasov** [danmunn/redmine_dmsf#1038]
When load file from webdav foolder, dowonload is begin, but not finish. All time 0,2 kb and not progress.
![Daw1](https://user-images.githubusercontent.com/48205689/65012511-c9028d00-d941-11e9-9e8f-4a2205015c87.png)
![Daw2](https://user-images.githubusercontent.com/48205689/65012521-ce5fd780-d941-11e9-8dd5-2f471e230251.png)

**Comment by nsasov** [comment]
![info](https://user-images.githubusercontent.com/48205689/65012537-dd468a00-d941-11e9-8d82-10e402545c9e.png)

**Comment by picman** [comment]
What is in the production.log regarding to the download?
Have you tried a different browser?

**Comment by nsasov** [comment]
Log:

**Comment by nsasov** [comment]
Started GET "/redmine/dmsf/webdav/test/Excel.xlsx" for 127.0.0.1 at 2019-09-17 14:05:48 +0700
Processing WebDAV request: /redmine/dmsf/webdav/test/Excel.xlsx (for 127.0.0.1 at 2019-09-17 07:05:48 UTC) [GET]
Completed in: 112 ms | 200 [https://127.0.0.1/redmine/dmsf/webdav/test/Excel.xlsx]

**Comment by nsasov** [comment]
> Have you tried a different browser?

Yes

**Comment by picman** [comment]
The return value 200 means that the request was successfully processed by the web server. Can't it be a firewall related issue? Do you test it on your localhost or on a server behind a firewall?

**Comment by nsasov** [comment]
This test in localhost, but on server same result
![127](https://user-images.githubusercontent.com/48205689/65024310-c95d5100-d95e-11e9-8c99-04759159deee.png)

**Comment by nsasov** [comment]
problem found on this installer:
https://bitnami.com/redirect/to/684621/bitnami-redmine-4.0.4-5-windows-x64-installer.exe

**Comment by picman** [comment]
Try Linux. I can't help you with Windows, sorry.

**Comment by nsasov** [comment]
ok, thanks

**Comment by picman** [comment]
It's very probably related to the fact that your Redmine is in a sub-uri. I've made a fix concerning this problem. Could you test the branch devel-2.4.2 in your environment whether the fix solves your problem?

Related to #1052

**Comment by nsasov** [comment]
Afte update and restart i see "Page not found" . And no authentication dialog is displayed
![image](https://user-images.githubusercontent.com/48205689/67221338-7e4ec600-f455-11e9-87a7-ef4035c50c5a.png)

**Comment by picman** [comment]
@nsasov: Your information are very short...
1. Which URL did you open?
2. Which file did you try to edit?
3. What is log/production.log?
Without detailed information you can't expect any progress.

**Comment by nsasov** [comment]
> @nsasov: Your information are very short...
> 
> 1. Which URL did you open?
http://127.0.0.1/redmine/dmsf/webdav
> 2. Which file did you try to edit?
Excel.xlsx
> 3. Do you test v2.4.2?
I load the plugin from the devel-2.4.2 branch, but in the settings it shows:

![image](https://user-images.githubusercontent.com/48205689/67357502-9aeb1b00-f587-11e9-95df-bcdb652764d6.png)

> 4. What is log/production.log?
![image](https://user-images.githubusercontent.com/48205689/67357614-fae1c180-f587-11e9-9249-9d7bb411619c.png)

>    Without detailed information you can't expect any progress.

**Comment by picman** [comment]
Add the following configuration into your _additional_environment.rb.
```ruby
config.relative_url_root = '/redmine'
```

**Comment by nsasov** [comment]
![image](https://user-images.githubusercontent.com/48205689/67405517-12986480-f5df-11e9-9dff-7b766a7d50e9.png)
Added, restart. But there is no effect (

**Comment by nsasov** [comment]
Any more ideas?

**Comment by picman** [comment]
http://127.0.0.1/redmine/dmsf/webdav

The page must by accessed via HTTP**S** otherwise Windows refuses basic authentication.
