### ISSUE TITLE
Download button gets disabled after first download

### ISSUE THREAD

**Issue by nikosfrangakis** [danmunn/redmine_dmsf#1041]
Hi,

when selecting a file and then pressing the Download button, the file gets downloaded and the Download button get disabled.
The Download button then remains disabled until you refresh the page.
<img width="408" alt="Screenshot 2019-09-26 at 11 54 08 " src="https://user-images.githubusercontent.com/15833029/65674012-8e40d900-e054-11e9-847c-b1750c59acac.png">
<img width="331" alt="Screenshot 2019-09-26 at 11 54 18 " src="https://user-images.githubusercontent.com/15833029/65674021-90a33300-e054-11e9-9446-56211c4c38e3.png">

Environment:
  Redmine version                4.0.4.stable.18320
  Ruby version                   2.6.2-p47 (2019-03-13) [x86_64-linux]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
SCM:
  Subversion                     1.10.4
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  redmine_ckeditor               1.2.2
  redmine_dmsf                   2.4.1

**Comment by picman** [comment]
Related to Rails 5. Fixed.
