### ISSUE TITLE
Conflict with "Default custom query" plugin on Redmine4.0.4

### ISSUE THREAD

**Issue by ryoji-takeuchi** [danmunn/redmine_dmsf#1043]
Condition; Redmine 4.0.4
DMSF 2.4.1
Default custom query 1.4.0
With this configuration, can't open project setting tab of redmine.

**Comment by picman** [comment]
Any screen-shot? production.log?

**Comment by picman** [comment]
https://github.com/hidakatsuya/redmine_default_custom_query/pull/43
