### ISSUE TITLE
Some folders with "special" symbols are unavailible via WebDAV

### ISSUE THREAD

**Issue by dinya** [danmunn/redmine_dmsf#1045]
After upgrade to DMSF 1.6.2 from 1.5.9 some folders are unavailible.

What does it mean?

For example, I have folder ``Тест №1`` (N.B. ``№`` presence) and I have access via:

1. Web client: http://SITE/projects/PROJECT_ID/dmsf
2. WebDAV http://SITE/dmsf/webdav with Firefox and plugin for Double Commander (http://ghisler.fileburst.com/fsplugins/webdav.zip, originally for Total Commander)

DMSF |  Web client (Firefox) | WebDAV (Firefox) | WebDAV (plugin)
-----|-----------------------|------------------|----------------
v1.5.9 | Folder is named as ``Тест №1``, all content is available. | Folder is named as ``Тест №1``, all content is available | Folder is named as ``Тест №1``, all contain is accessible.
v1.6.2 | Folder is named as ``Тест №1``, all content is available | Folder is named as ``Тест №1``, but **content is unavailible (empty page)** | **Folder is named as ``Тест No1``** and **content is unavailible (empty folder with "Error 404" in logs)**.

It looks like WebDAV mode normalizes (sanitizes) unicode.

Maybe DMSF 2.4.1 has the same problem.

**Comment by picman** [comment]
It works in v2.4.1. Firefox:
![image](https://user-images.githubusercontent.com/779003/67206692-728de000-f412-11e9-84ae-bd37cbc7dcc7.png)

**Comment by dinya** [comment]
@picman 

What about webdav clients for Linux (say, Nautilus or Dolphin)?:

1. Are names are the same as in Redmine (``Тест №1 -> Тест №1``)?
2. If ``Тест №1 -> Тест No1`` then how to rename the name (I mean ``No`` is two symbols)?

----------

Screenshots for the history.

* Server under Linux, Redmine 3.4.11 and dmsf 1.6.2
* Web client under Windows for the latest stable version of web browsers:

Browser | Screentshot
---------|---------------
Firefox | ![firefox](https://user-images.githubusercontent.com/2182222/67261425-0e265b80-f4ba-11e9-9724-c1e4611a288e.png)
Chrome | ![chrome](https://user-images.githubusercontent.com/2182222/67261426-0ebef200-f4ba-11e9-946a-a76460fa52bf.png)

**Comment by picman** [comment]
Cadaver client in Linux CLI; renaming Тест №1 to xxxx and back to Тест №1:

```
$ cadaver httpp://localhost:3000/dmsf/webdav/c1
Authentication required for Locked content on server `localhost':
Username: ***
Password: 
dav:/dmsf/webdav/c1/> ls
Listing collection `/dmsf/webdav/c1/': succeeded.
Coll:   Тест No1                        4096  říj 21 14:47
dav:/dmsf/webdav/c1/> mv 'Тест No1' xxxx
Moving `/dmsf/webdav/c1/%d0%a2%d0%b5%d1%81%d1%82%20No1' to `/dmsf/webdav/c1/xxxx':  succeeded.
dav:/dmsf/webdav/c1/> ls
Listing collection `/dmsf/webdav/c1/': succeeded.
Coll:   xxxx                                4096  říj 22 08:42
dav:/dmsf/webdav/c1/> mv xxxx 'Тест №1'
Moving `/dmsf/webdav/c1/xxxx' to `/dmsf/webdav/c1/%d0%a2%d0%b5%d1%81%d1%82%20%e2%84%961':  succeeded.
dav:/dmsf/webdav/c1/> ls
Listing collection `/dmsf/webdav/c1/': succeeded.
Coll:   Тест No1                        4096  říj 22 08:42
dav:/dmsf/webdav/c1/> 
```

Provide more details. Eg. Do you test the latest version 2.4.1? What is in log/production.log?

**Comment by dinya** [comment]
It seem the problem is only in v1.6.2.
I will test v2.4.1 later and provide the information.
And until then the issue can be closed.

Thanks.
