### ISSUE TITLE
Redirect to parent folder after folder edit

### ISSUE THREAD

**Issue by dinya** [danmunn/redmine_dmsf#1046]
In DMSF v1.5.9 after updating the folder params with http://SITE/projects/PROJECT_ID/dmsf/edit?folder_id=FOLDER_ID there is no any redirect: we still are in http://SITE/projects/PROJECT_ID/dmsf?folder_id=FOLDER_ID.

Since upgrading to DMSF v1.6.2 after editing the folder, we are redirected to the parent folder. I think this is unpredictable behavior because normally the user works with the contained files after editing the folder parameters and with the new behavior the user is forced to find the folder in the parent folder and go into.

Was this new behavior made in line with the planned design?

**Comment by dinya** [comment]
Dear @picman 

Is my question is incorrect? Is it possible to add the old behavior as the plugin option?

**Comment by picman** [comment]
It is not so easy. I'll come back to this issue later.

**Comment by picman** [comment]
Fixed.
