### ISSUE TITLE
Can't uninstall DMSF by migration error

### ISSUE THREAD

**Issue by ryoji-takeuchi** [danmunn/redmine_dmsf#1048]
I tried to uninstall DMSF to evaluate other plugins which are conflicted with DMSF. But when uninstall DMSF, uninstall didn't succeed due to migration error. 
After drop the table which is related with DMSF and DMSF related data from migration historical table, Redmine can rebooted without DMSF. 
Uninstall can't work automatically. 
Please advice what was happened.

Attached data is log file of migration for your reference.
[dmsf_migrate.txt](https://github.com/danmunn/redmine_dmsf/files/3717029/dmsf_migrate.txt)

**Comment by picman** [comment]
`raise_validation_error` - Your file names(s) contain invalid characters.

```ruby
INVALID_CHARACTERS = '\[\]\/\\\?":<>#%\*'.freeze
```
You must fix the filenames before the migration.
