### ISSUE TITLE
Accessible even if WebDAV is disabled.

### ISSUE THREAD

**Issue by n0nel** [danmunn/redmine_dmsf#1052]
WebDAV URL can be accessible even if "Disable" is set in the plug-in settings.
The current WebDAV does not work properly in our environment, so I need to disallow WebDAV access.

Confirmed problems in our environment(Windows+Apache+Thin):
- File reading via WebDAV doesn't work in sub URI.
- File display via WebDAV is too slow (over 30 to 60 second). (also WEBrick)
- WebDAV file/folder URL encoding(UTF-8 3 byte char) fail. (also WEBrick)

DMSF is 2.4.1

**Comment by picman** [comment]
Fixed. Thank you for pointing that out.

**Comment by picman** [comment]
Concerning sub-uri, I've modified the code in order to fix it. Do you think that you can test the branch devel-2.4.2 in your environment?
Also please port a folder/file name causing problems.

**Comment by n0nel** [comment]
Thank you for your quick response.
The WebDAV page is no longer displayed, but now it looks like this.
Is this correct?
```
HTTP/1.1 DAV4Rack::HTTPStatus::NotFound Not FoundX-Request-Id: ***
X-Runtime: 0.001371
Connection: close
Server: thin
```

And production.log is:
```
Started GET "/sub_uri/dmsf/webdav/some_project" for 127.0.0.1 at DATE TIME
Processing WebDAV request: /sub_uri/dmsf/webdav/some_project (for IP at DATE TIME) [GET]
WebDAV Error: DAV4Rack::HTTPStatus::NotFound
DAV4Rack::HTTPStatus::NotFound

```
Via Apache, I expected a status code 403 or 404, but the Apache log records 200.
`IP - - [DATE:TIME] "GET /sub_uri/dmsf/webdav/some_project HTTP/1.1" 200`

**Comment by n0nel** [comment]
Any file (or folder) cannot be opened with the sub URI as before.
A list of TOP page (/sub_uri/dmsf/webdav/some_project) is displayed, but all URL of the file (or folder) included in the list is /dmsf/webdav/some_project/*.* (without /sub_uri).

**Comment by picman** [comment]
1. Disabled WebDAV
In my case it behaves as expected:
```
kpicman@plzn020b:~/Downloads$ curl -I  http://localhost:3000/dmsf/webdav/c1
HTTP/1.1 404 Not Found 
X-Request-Id: 47ea6ae7-4380-4e79-98f9-a105bca5f662
X-Runtime: 0.001257
Server: WEBrick/1.4.2 (Ruby/2.5.1/2018-03-29)
Date: Wed, 23 Oct 2019 11:29:04 GMT
Content-Length: 0
Connection: Keep-Alive
```
2. Sub-uri
I'll investigate it further.

**Comment by picman** [comment]
Modify your _additional_environment.rb_ as follows:
```ruby
config.relative_url_root = '/redmine'
```
That does the trick.

**Comment by n0nel** [comment]
Thank you for your various research.
This issue can be closed because when WebDAV is disabled the file list is no longer displayed no matter what the status code is.
And I understood that it is difficult to run WebDAV function normally with a sub URI.
