### ISSUE TITLE
New revision: disable submit button less file as been uploaded

### ISSUE THREAD

**Issue by dnyamy** [danmunn/redmine_dmsf#1053]
Hello,

On the New Revision form, it is possible to click the submit button event if no file has been uploaded.

For our corporate needs, I have added some code to trigger another operation: a jenkins build that performs further checks, transforms and deliver to downstream systems.
We are annoyed when the user forget to attach the file. The process get trigered anyway, and deliver the last revision, which is then delivered twice, thrice... as long as the user forget.

Please, I as am not a rails master, can someone give me a tip on how to disable that submit button as long as no file has been uploaded ?

Thanks 

dn

**Comment by picman** [comment]
A new revision might be used not only in case of a new file upload needed. A new revision might serve also for a description change, comment or a new custom field. Therefore, for sure, such a change won't be a part of this plugin but it might be a part of your customization.
I'd focus on jQuery. E.g. the following patch do something you need. The button is disabled as default and enabled after a file is uploaded.

[disabled_button_patch.txt](https://github.com/danmunn/redmine_dmsf/files/3738968/disabled_button_patch.txt)

**Comment by picman** [comment]
Be careful. The same form is used during common upload too and in this case the button must remain enabled as default. So more coding is needed than is provided in the patch.

**Comment by dnyamy** [comment]
Thanks a lot for your reply.
I started with the proposal.
Button is disabled and enabled as needed.

Just noticing a strange effect: When I upload the file, there is an" OK box" that appears and remains there. See attached capture. What can be the reason ?

Thanks

![Capture d’écran 2019-10-18 à 01 11 25](https://user-images.githubusercontent.com/43039376/67054751-d6c84f80-f145-11e9-8c60-1b1dc29e7e48.png)

**Comment by picman** [comment]
Using prop method it works fine. See the updated patch.

[disabled_button_patch.txt](https://github.com/danmunn/redmine_dmsf/files/3742472/disabled_button_patch.txt)

**Comment by dnyamy** [comment]
Indeed !
Thanks a lot
dn
