### ISSUE TITLE
Autofill of folder link name

### ISSUE THREAD

**Issue by dinya** [danmunn/redmine_dmsf#1055]
While link creation in DMSF v1.5.9  on the "Source folder" selection the "Name" was auto filled with the "Source folder" value (folder link) and was changed on "Source file" selection (file link).

This was very useful because the folder links are often used and the link name matches the source 99% of the time.

Now in v1.6.2 the "Name" is auto filled on the "Source file" selection only.

Is it is possible to return v1.5.9 behaviour?

**Comment by picman** [comment]
It was changed 'cause the original behaviour was odd. It was handy in case of folder links but contra-productive in case of file links.
I've modified it as follows:
1. If the target folder is changed and the link's name is empty, the link's name is set to the folder's name.
2. If the target file is changed and the link's name is empty or it's the same as the selected folder, the link's name is set to the file's name.
I hope that this solution fits your requirements and my objection too. All in all you will have to upgrade to v2.4.2.

**Comment by dinya** [comment]
@picman 

Thank you, your solution (on the description) does exactly what I thought.

But I still need v1.6.2 and an upgrade to Redmine 4.x is in the plans.

Will this be the correct way if I replace ``app/views/dmsf_links/_form.html.erb`` from [``v1.6.2``](https://github.com/danmunn/redmine_dmsf/blob/v1.6.2/app/views/dmsf_links/_form.html.erb) with 
your commit from [``devel-2.4.2``](https://github.com/danmunn/redmine_dmsf/blob/devel-2.4.2/app/views/dmsf_links/_form.html.erb)? Or does your patch use incompatible features?

**Comment by picman** [comment]
It would be safer if you just replace the Javascript methods as follows.

```ruby
-- <%# Suggest a link name when a file is selected %>
--   $('#dmsf_link_target_file_id').change(function () {
--     var linkName = $('#dmsf_link_name');
--     var name = linkName.val();
--     if(name == '') {
--       linkName.val($('#dmsf_link_target_file_id option:selected').text().replace(/\./g, ''));
--     }
--   });
```
```ruby
++ <%# Suggest a link's name when a file is selected %>
++   $('#dmsf_link_target_file_id').change(function () {
++    var linkName = $('#dmsf_link_name');
++    var name = linkName.val();
++    var dirName = $('#dmsf_link_target_folder_id option:selected').text().replace(/\./g, '')
++    var fileName = $('#dmsf_link_target_file_id option:selected').text().replace(/\./g, '')
++    if((name == '') || name == dirName) {
++      linkName.val(fileName);
++    }
++  });
++  <%# Suggest a link's name when a folder is selected %>
++  $('#dmsf_link_target_folder_id').change(function () {
++    var linkName = $('#dmsf_link_name');
++    var name = linkName.val();
++    var dirName = $('#dmsf_link_target_folder_id option:selected').text().replace(/\./g, '')
++    if(name == '') {
++      linkName.val(dirName);
++    }
++  });
```

**Comment by dinya** [comment]
Some notes about the logic in the link edit form on changes:

1. If I select ``Folder == folder1`` and ``File == file1`` then ``Name == file1`` (It's ok). And when I wanna change the path (either ``Folder`` or ``File``) the field `Name == file1` still.
2. The same situation if select ``Folder == folder1`` (``Name == folder``), and then wanna ``Folder == folder2``, but ``Name == folder1`` still.
3. I think in both cases the old ``Name`` should be replaced. What do you think about that?

I tested with your patch from the previous message. Maybe for v2.4.x there is no problem.

**Comment by picman** [comment]
The reason is that I don't want the application be as a modern text editor; overwriting whatever you enter. I wouldn't add more logic there. I believe that there exist users which enter the name manually first and then selecting folder and file. In that case we would overwrite their input.

**Comment by dinya** [comment]
Justifiably. My bad
