### ISSUE TITLE
Permission denied @ rb_sysopen - /Mydrive/Redmine_Docs/dmsf/2019/10/my_file

### ISSUE THREAD

**Issue by BagginsHasIt** [danmunn/redmine_dmsf#1056]
Currently running Redmine 3.4 and DMSF 1.5.9.
When I upgrade DMSF straight to 1.6.2 I get the following error in the webapp:

Permission denied @ rb_sysopen - /Mydrive/Redmine_Docs/dmsf/2019/10/my_file

If I run the rake command ( bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf RAILS_ENV="production" )as my user I get multiple permission denied during migration to the new file structure, so I run as root and it completes but the new 2016 - 2019 folders it creates i.e. /Mydrive/Redmine_Docs/dmsf/2019   are all owned by root,

Assuming permissions were wrong since it was run as root I issued the following command:
chown -R www-data:www-data  /Mydrive/Redmine_Docs/dmsf/2019 ------ on 2018,2017 and 2016 folders.

Restared nginx and recieve the same error.
I checked your reference to #799 and downloaded the current .zip file from
https://github.com/danmunn/redmine_dmsf/releases/tag/v1.6.2
So it shouldn't be a master issue unless that link doesn't contain the master and I need a different one.

Ideas? Thanks for any help.

**Comment by picman** [comment]
It seems to be a permission issue. Check the permission of the file which can't be opened. Eg.

```ls -l /Mydrive/Redmine_Docs/dmsf/2019/10/my_file```

Your ```chown -R www-data:www-data /Mydrive/Redmine_Docs/dmsf``` is correct and should fix the problem, I believe.

**Comment by BagginsHasIt** [comment]
I think I've solved the permission error but now I"m getting - "No such file or directory @ rb_file_s_rename"
I found a resolution to the issue here  -> #774 and #786 
Seems I need to pull a master update? From your info I ran
cd redmine/plugins/redmine_dmsf
git pull
I'm getting fatal: Not a git repository (or any of the parent directories): .git
I downloaded version the 1.6.2 tar and upgraded directly from 1.5.9.
Doesn't it already contain a master with that fix specific for version 1.6.2?

**Comment by picman** [comment]
You have to use `git clone` to get the git repository and to be able to update it using `git pull` later. if you download the zip version,l you have to update it manually by downloading and replacing files.

**Comment by BagginsHasIt** [comment]
I just moved over the .tar file for specifically 1.6.2 and renamed it too redmine_dmsf before running bundle install.
If I try  - git clone git://github.com:danmunn/redmine_dmsf.git
I get that 'redmine_dmsf' already exists and is not empty.
What if run git clone initially and not move over the 1.6.2 tar will that then wouldn't that download the most current dmsf? If so that wouldn't work be cause I need specifically 1.6.2 or is there a way to just pull a clone repo of a specific version?

**Comment by picman** [comment]
1. Delelete/backup redmine_dmsf folder
2.
``` 
cd plugins
git clone --branch v1.6.2 --single-branch https://github.com/danmunn/redmine_dmsf.git
```

**Comment by BagginsHasIt** [comment]
That did it, thank you so much!

**Comment by picman** [comment]
1. Check the destination path in the plugin's settings.
2. Try to manually copy/move the file with the web user.

**Comment by BagginsHasIt** [comment]
Destination path is correct and I am able to create directories and files with the www-data user.

**Comment by BagginsHasIt** [comment]
If I do a tmp chmod 777 on the file system on my cloned test machine it looks like it clears the error. Are there any other internal users or services that need access other than www-data?

**Comment by picman** [comment]
Yes.
