### ISSUE TITLE
DMS form flickering on page reload

### ISSUE THREAD

**Issue by jurijstoks** [danmunn/redmine_dmsf#1058]
Hi!

Is there any solution to get rid of form flickering on page reload? 

There is [video](https://drive.google.com/file/d/1iYK6F3T5NVGxsT4cP25odjyqQAhNfgdS/view?usp=sharing) with example

We use redmine theme: A1, but i tried to use redmine default theme, still the same.

I have tested this moment in different browsers: chrome, centbrowser, opera, mozilla firefox, internet explorer, microsoft edge, brave, still the same.

Our config info:
>Environment:
  Redmine version-------------4.0.4.stable
  Ruby version-----------------2.5.1-p57 (2018-03-29) [x86_64-linux]
  Rails version------------------5.2.3
  Environment------------------production
  Database adapter-------------Mysql2
  Mailer queue------------------ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery----------------smtp
SCM:
  Git-----------------------------1.9.1
  Filesystem                     
Redmine plugins:
  redmine_contacts-------------4.2.5
  redmine_contacts_helpdesk--4.1.3
  redmine_dmsf-----------------2.4.1

Otherwise it works well. Thanks a lot for useful plugin!!!

**Comment by picman** [comment]
Fixed. The rendering of the table is postponed to the time when the initialization is done.
