### ISSUE TITLE
Xapian not working

### ISSUE THREAD

**Issue by itadminatitgroup** [danmunn/redmine_dmsf#1059]
Hello,

i'm having trouble getting xapian to work maybe you can help?
I installed xapian-core, xapian-bindings and xapian-omega.
Also when i run omindex it executes successfully and indexes all files.

Thank you in advance for any help.

![config](https://user-images.githubusercontent.com/32698930/68180242-48e8c300-ff93-11e9-87ee-c052b2387b6c.png)
![productionlog](https://user-images.githubusercontent.com/32698930/68180244-48e8c300-ff93-11e9-8d0c-0a65907f810e.png)
![RedmineDMSF](https://user-images.githubusercontent.com/32698930/68180245-48e8c300-ff93-11e9-8b44-f5db7b6416b9.png)

**Comment by picman** [comment]
Duplicates #769.
