### ISSUE TITLE
Folder content inheritance for custom fields

### ISSUE THREAD

**Issue by phqsh** [danmunn/redmine_dmsf#1062]
RM provides custom fields for DMSF as well and I can't understand if it is I who do it wrong.
I create a boolean value field and set it to "inheritable" and set the whole folder a value - but its content is not affected at all.
If the file was already in folder earlier than I created the field itself - it still has no value at all
If the file was in folder and had the value - it is unchanged
If I try to upload the file it has default value in custom field even if it doesn't match the folder value.
Is it correct behaviour?

>Redmine version 4.0.5.stable
>DMSF version 2.4.1
>Thank you for your attention

**Comment by picman** [comment]
The property **Not inheritable** is applied for document's revisions only. So if you have unchecked it and creating a new revision of an existing document, the custom field value is inherited from the previous revision.
