### ISSUE TITLE
Empty Folders (no Files shown) after Upgrade

### ISSUE THREAD

**Issue by skorpionking** [danmunn/redmine_dmsf#1063]
Hello together,

I've upgraded a redmine with dmsf plugin. But after upgrade the old dmf files are not in their folders.

Old system:

  Redmine version                2.5.2.stable.13421
  Ruby version                   2.1.9-p490 (2016-03-30) [x86_64-linux-gnu]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               SQLite
  redmine_dmsf                   1.4.8 stable

New system:
Redmine version                4.0.5.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               SQLite
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  redmine_dmsf                   2.4.1

I tried to upload a demo file in one of the old (empty) folders.
The uploaded file works. It can be downloaded.
A look in the database shows the difference to the old files:
In some tables exists the columns "deleted" and "notification" which have the values 0 or 1.
But the old file entries doesn't contains 0 or 1. The values in this lines were f or t.
A manual database update only is able to make in works.

Following updates were necessary:
update dmsf_files set notification = 0 where notification = 'f';
update dmsf_files set notification = 1 where notification = 't';
update dmsf_files set deleted = 0 where deleted = 'f';
update dmsf_files set deleted = 1 where deleted = 't';
update dmsf_file_revisions set deleted = 0 where deleted = 'f';
update dmsf_file_revisions set deleted = 1 where deleted = 't';
update dmsf_links set deleted = 0 where deleted = 'f';
update dmsf_links set deleted = 1 where deleted = 't';

I guess this may be a bug by upgrading.
Strange or what?

Best regards
skorpionking

**Comment by ahorek** [comment]
there was a change in rails 5.2

Change sqlite3 boolean serialization to use 1 and 0.

SQLite natively recognizes 1 and 0 as true and false, but does not natively recognize 't' and 'f' as was previously serialized.

This change in serialization requires a migration of stored boolean data for SQLite databases, so it's implemented behind a configuration flag whose default false value is deprecated.

https://github.com/rails/rails/blob/v5.2.0/activerecord/CHANGELOG.md

this config might help you as a temporarly workaround
```config.active_record.sqlite3.represent_boolean_as_integer = true```
for Rails 6, the new config will be mandatory, so you should migrate your db
