### ISSUE TITLE
installation error version 2.4.1

### ISSUE THREAD

**Issue by fracarfzx** [danmunn/redmine_dmsf#1065]
Hi there,
I'm new to Redmine and have an error in the DMSF plugin setup.
I did an installation from scratch of Redmine 4.1 following the guide http://www.redmine.org/projects/redmine/wiki/RedmineInstall and everything went well, however, I can't install the DMSF plugin.
I followed the guide http://www.redmine.org/plugins/dmsf and https://github.com/danmunn/redmine_dmsf, but when try to execute bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf RAILS_ENV="production" I get the error:

$ bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
(in /opt/redmine-4.1.0)
rake aborted!
NoMethodError: undefined method `assets' for #<Rails::Engine::Configuration:0x0000000003f404e0>
/usr/local/rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/railtie/configuration.rb:97:in `method_missing'
/usr/local/rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:20:in `<class:Engine>'
/usr/local/rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:9:in `<module:RedmineExtensions>'
/usr/local/rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `require_relative'
/usr/local/rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.2/lib/bundler/runtime.rb:74:in `require'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.2/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.2/lib/bundler/runtime.rb:69:in `each'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.2/lib/bundler/runtime.rb:69:in `block in require'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.2/lib/bundler/runtime.rb:58:in `each'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.2/lib/bundler/runtime.rb:58:in `require'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.2/lib/bundler.rb:174:in `require'
/opt/redmine-4.1.0/config/application.rb:18:in `<top (required)>'
/opt/redmine-4.1.0/Rakefile:5:in `require'
/opt/redmine-4.1.0/Rakefile:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)

Can anyone help me? Thank you!

**Comment by fracarfzx** [comment]
This are my step and versions:
- CentOS 7 minimal with update
- ruby 2.6.3 using RVM
- MySQL 8
- Redmine 4.1.0 with bundle
- DMFS plugin 2.4.1

**Comment by kvlahrogut** [comment]
We stumpled upon exactly the same issue here. But apart from that and up to Redmine v4.0.6 the DMSF plug-in always worked like a charm for us – wonderful software. Many thanks to @picman and all the other contributors!

**Comment by aviatorm** [comment]
I have this error too. Debian10, Redmine 4.1.0, Ruby2.6, Rails 5.2. this error is present both 2.4.1 and 2.4.2 plugin version.

**Comment by picman** [comment]
The error is caused by the dependency on RedmineExtensions gem.
http://www.redmine.org/issues/32223

**Comment by aviatorm** [comment]
picman, thanks. It worked after changing sprockets version > 3.7.2 in Gemfile (and installing it for replace 4.0, of course) and uncommenting string "require 'sprockets/railtie'" in the config/application.rb
Solved for me.

**Comment by fracarfzx** [comment]
ok, it works for me too. Thanks picman and aviatorm!

**Comment by acosonic** [comment]
I have solved this by

uncommenting `require 'sprockets/railtie'` 
from `config/application.rb `

and running after that:

`mkdir -p app/assets/config && echo '{}' > app/assets/config/manifest.js`
