### ISSUE TITLE
Minor version is limited to 99 max - I recommend to change the limit to 999

### ISSUE THREAD

**Issue by NGeb1** [danmunn/redmine_dmsf#1069]
Hello,

When working on fixing issue #793 , a limit was added to the minor revision number - 99 upper limit. We already have a project where we are at minor revision 350. I recommend / ask to change this limit to 999. Attached is an updated dmsf_upload_helper.rb which already supports 999 as the upper limit. Please review and see if this can be changed in the next release,
[dmsf_upload_helper.zip](https://github.com/danmunn/redmine_dmsf/files/4015760/dmsf_upload_helper.zip)

Thanks,

NGeb1

**Comment by picman** [comment]
Yes. Done. Next time a pull request instead of a zipped file, please.
