### ISSUE TITLE
Change xapian bindings

### ISSUE THREAD

**Issue by acosonic** [danmunn/redmine_dmsf#1073]
How about switching to this:

[https://www.rubydoc.info/github/johnl/xapian-fu](https://www.rubydoc.info/github/johnl/xapian-fu)

**Comment by picman** [comment]
Why? What will be advantages of usage of this library?

**Comment by acosonic** [comment]
Perhaps installation of required libraries and gems would be easier?
Not sure about other benefits, though. 

From their info:

> _provides an interface more in-line with “The Ruby Way”(tm) and is considerably easier to use._
>  
> _For example, you can work almost entirely with Hash objects - XapianFu will handle converting the_ _Hash keys into Xapian term prefixes when indexing and when parsing queries._
>  
> _It also handles storing and retrieving hash entries as Xapian::Document values. XapianFu basically_ _gives you a persistent Hash with full text indexing (and ACID transactions)._ 

It should work just with xapian-ruby and itself, though xapian-fu gem,

**Comment by picman** [comment]
The present solution requires just _xapian-ruby_ without any further gems. I think that the _xapian-fu_ might be handy if you use the library also for storing texts. But, in our case we use _xapian-omega_ for indexing and the _xapian-ruby_ for reading. I see no added value in usage of _xapian-fu_.
