### ISSUE TITLE
Xapian not available message

### ISSUE THREAD

**Issue by acosonic** [danmunn/redmine_dmsf#1076]
Xapian not available message removed only 
when I manually added

`gem 'xapian-ruby'`

to Gemfile

**Comment by picman** [comment]
And the package ruby-xapian was installed?

```apt-get install ruby-xapian```

**Comment by acosonic** [comment]
Yes it was installed. Ubuntu 16.04 server.

**Comment by picman** [comment]
Ubuntu 18.04 works fine without the gem. Debian 10 as well. BTW today Ubuntu 20.04 should be released. Isn't time for an upgrade?
