### ISSUE TITLE
Can't assign user to folder

### ISSUE THREAD

**Issue by kulik** [danmunn/redmine_dmsf#1078]
Preconditions:
redmine 4.1.0
dmsf 5d3c669a82facf07d31cee9e66f15a33c1d4eb30
 have project with enabled dms module
have manager role all dms permitions checked
login from admin user which is manager on this project, or just admin.

1) create folder
2) in folder creation form click on the "Search for user to add" link
3) dialog to pick users from the project opened. check one or few
4) finish creating the folder
result: there is no place to check who added to this folder
if i try to edit created folder, there is also no place where to see allowed roles and users.
when i click the link in edit form "Search for user to add" next exception appeared in the logs, but dialog not opened

Started GET "/dmsf_folder_permissions/new?dmsf_folder_id=2&project_id=some_api" for 172.17.0.1 at 2020-01-26 21:29:57 +0000
Processing by DmsfFolderPermissionsController#new as JS
  Parameters: {"dmsf_folder_id"=>"2", "project_id"=>"some_api"}
  Token Update All (4.3ms)  UPDATE "tokens" SET "updated_on" = '2020-01-26 21:29:57.408166' WHERE "tokens"."user_id" = $1 AND "tokens"."value" = $2 AND "tokens"."action" = $3 AND (created_on > '2019-12-27 21:29:57.374769')  [["user_id", 6], ["value", "1f93e5cf4a095d0bbc7c8781eb50b9cac153672f"], ["action", "session"]]
   (1.4ms)  SELECT MAX("settings"."updated_on") FROM "settings"
  User Load (2.8ms)  SELECT  "users".* FROM "users" WHERE "users"."type" IN ('User', 'AnonymousUser') AND "users"."status" = $1 AND "users"."id" = $2 LIMIT $3  [["status", 1], ["id", 6], ["LIMIT", 1]]
  Current user: kulik (id=6)
  DmsfFolder Load (6.3ms)  SELECT  DISTINCT "dmsf_folders".* FROM "dmsf_folders" INNER JOIN "projects" ON "projects"."id" = "dmsf_folders"."project_id" LEFT JOIN dmsf_folder_permissions ON dmsf_folders.id = dmsf_folder_permissions.dmsf_folder_id WHERE "dmsf_folders"."deleted" = $1 AND (projects.status <> 9 AND EXISTS (SELECT 1 AS one FROM enabled_modules em WHERE em.project_id = projects.id AND em.name='dmsf')) AND "dmsf_folders"."id" = $2 LIMIT $3  [["deleted", 0], ["id", 2], ["LIMIT", 1]]
  Project Load (1.3ms)  SELECT  "projects".* FROM "projects" WHERE (projects.status <> 9) AND "projects"."identifier" = $1 LIMIT $2  [["identifier", "some_api"], ["LIMIT", 1]]
   (0.8ms)  SELECT "enabled_modules"."name" FROM "enabled_modules" WHERE "enabled_modules"."project_id" = $1  [["project_id", 171]]
  DmsfFolderPermission Load (0.7ms)  SELECT "dmsf_folder_permissions".* FROM "dmsf_folder_permissions" WHERE "dmsf_folder_permissions"."dmsf_folder_id" = $1 AND "dmsf_folder_permissions"."object_type" = $2  [["dmsf_folder_id", 2], ["object_type", "User"]]
  Principal Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."status" = $1 AND 1=0  [["status", 1]]
  Principal Load (1.7ms)  SELECT "users".* FROM "users" WHERE "users"."status" = $1 AND "users"."status" IN ($2, $3) AND (users.id IN (SELECT DISTINCT user_id FROM members WHERE project_id IN (171))) AND (id NOT IN ('')) ORDER BY "users"."type" ASC, "users"."lastname" ASC  [["status", 1], ["status", 3], ["status", 1]]
Completed 500 Internal Server Error in 80ms (ActiveRecord: 32.6ms)
  
ActiveRecord::StatementInvalid (PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: ""
LINE 1: ...mbers WHERE project_id IN (171))) AND (id NOT IN ('')) ORDER...
                                                             ^
: SELECT "users".* FROM "users" WHERE "users"."status" = $1 AND "users"."status" IN ($2, $3) AND (users.id IN (SELECT DISTINCT user_id FROM members WHERE project_id IN (171))) AND (id NOT IN ('')) ORDER BY "users"."type" ASC, "users"."lastname" ASC):
  
plugins/redmine_dmsf/app/controllers/dmsf_folder_permissions_controller.rb:59:in `users_for_new_users'
plugins/redmine_dmsf/app/controllers/dmsf_folder_permissions_controller.rb:35:in `new'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:72:in `call'

**Comment by kulik** [comment]
UPD - probably it's an issue connected to Postgres vs IN set operator with an empty list of int it adds'' - empty string which is not supported by PG

**Comment by picman** [comment]
Fixed. Thank you for reporting that!

**Comment by kulik** [comment]
Thank you. Checked. Fixed
