### ISSUE TITLE
More than one ID in image rendering macros

### ISSUE THREAD

**Issue by dinya** [danmunn/redmine_dmsf#1082]
I and my team are researchers, not programmers, so the images with the plots and photos are the main objects to present.

Frequently we presents our images with the series of plots to show the evolution of object. So the macros like ``{{dmsftn()}}`` and ``{{dmsf_image()}}``  are the most used.

But notation ``{{dmsftn(ID1)}} {{dmsftn(ID2)}} ... {{dmsftn(IDN)}}`` is the long code (as least in the markdown/textile code).

Is it possible to enhance macros rendering the images so that they will render the series of the images (``{{dmsftn(ID1)}} {{dmsftn(ID2)}} ... {{dmsftn(IDN)}}`` <-> ``{{dmsftn(ID1, ID2, ..., IDN)}}`` saving the behavour).

I think it's possible without change the current behaviour, because all extra params are named, like:

```
{{dmsftn(ID1, ID2, ID3, width=200)}} 
{{dmsf_image(ID1, ID2, ID3, width=200)}}
```

**Comment by picman** [comment]
`dmsftn` and `dmsf_image` macros support multiple images' ids now.
