### ISSUE TITLE
Document Tagging

### ISSUE THREAD

**Issue by redfox1993** [danmunn/redmine_dmsf#1083]
Hi there,

We are testing your plugin and it is really cool. 
But i wonder where i can find the tagging function. I have created a New custom field Tag and added it to the dms plugin. But in the dms overview i can see only the filter box.

By the way, is it then possible to create more filterable custom fields?

**Comment by picman** [comment]
1) The custom field must be format of List.
2) No, just the first one is used.

**Comment by redfox1993** [comment]
I have created already a custom field and deleted it later. Could this be the reason that i cant get the new custom field to show?

**Comment by picman** [comment]
I don't think so. It simple takes the first DMSF custom field which is format of _List_. Order the custom field to the first position.

**Comment by redfox1993** [comment]
Yes, that worked. But if I choose one in the Tag, I get an error:

> Started POST "/projects/test-2/dmsf/tag_changed" for notebook9 at 2020-02-05 11:29:05 +0000
> Processing by DmsfController#tag_changed as HTML
>   Parameters: {"utf8"=>"✓", "authenticity_token"=>"ILAH5zTdrIGsybjdd7aD297PxiTTkVEZVCfG340j++Ykrn5lszxL4pCPDqNu6hvcG2izKm1yZM6UQPBNG6SGhg==", "dmsf_folder"=>{"custom_field_values"=>{"4"=>["Test", ""]}}, "id"=>"test-2"}
>   Current user: admin (id=1)
> Redirected to http://testserver/projects/test-2/dmsf?custom_field_id=4&custom_value%5B%5D=PFIT&custom_value%5B%5D=
> Completed 302 Found in 17ms (ActiveRecord: 5.2ms)
> Started GET "/projects/test-2/dmsf?custom_field_id=4&custom_value%5B%5D=PFIT&custom_value%5B%5D=" for 192.168.50.182 at 2020-02-05 11:29:05 +0000
> Processing by DmsfController#show as HTML
>   Parameters: {"custom_field_id"=>"4", "custom_value"=>["PFIT", ""], "id"=>"test-2"}
>   Current user: admin (id=1)
> Completed 500 Internal Server Error in 18ms (ActiveRecord: 4.5ms)
> 
> NoMethodError (undefined method `empty?' for nil:NilClass):
> 
> plugins/redmine_dmsf/app/models/dmsf_file_revision_custom_field.rb:32:in `block in compare_values?'
> plugins/redmine_dmsf/app/models/dmsf_file_revision_custom_field.rb:32:in `reject!'
> plugins/redmine_dmsf/app/models/dmsf_file_revision_custom_field.rb:32:in `compare_values?'
> plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:599:in `block (2 levels) in get_display_params'
> plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:597:in `each'
> plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:597:in `block in get_display_params'
> plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:596:in `get_display_params'
> plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:57:in `show'
> lib/redmine/sudo_mode.rb:65:in `sudo_mode'
> plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'

**Comment by picman** [comment]
Check the custom field settings. I think that **Required** and **Default value** must be set too.

**Comment by redfox1993** [comment]
I have filled that custom field for all documents and then I can click on the items. And it worked as purposed. Seems that an empty tag throws an error.

Are there any plans to get more custom fields to work? 
For example, I have got 2 custom fields:

- customers (customer 1 and customer 2)
- doctypes (invoice and documentation) 

now I would like to filter customer 2's invoices. I don't know how I get this result to the view

The features in #236 sounds very handy, too

**Comment by picman** [comment]
v.2.4.3 probably

**Comment by redfox1993** [comment]
I am looking forward to that. Thank you very much.

**Comment by picman** [comment]
Implemented in scope of #1080. There are filters and options now.
