### ISSUE TITLE
Version # no longer increments beyond 100

### ISSUE THREAD

**Issue by MichaelTJWard** [danmunn/redmine_dmsf#1086]
Since upgrading Redmine to 4.0 and this plug-in to 2.4.1 we have found a few documents that have been updated many times over the years.  The old version of the plug-in would increment the minor version beyond 100, but the new plug-in does not.  There appears to be no other versioning issues as the plug-in still recognizes that their are different versions of the file, and each one can be accessed individually.

**Comment by picman** [comment]
Duplicates #1069.
