### ISSUE TITLE
I can't upload files by sliding file between windows

### ISSUE THREAD

**Issue by jlsblasco** [danmunn/redmine_dmsf#1087]
My enviroment:
Environment:
  Redmine version                3.4.9.stable
  Ruby version                   2.5.0-p0 (2017-12-25) [x86_64-linux]
  Rails version                  4.2.11
  Environment                    production
  Database adapter               Mysql2
DMSF 1.6.1

We have two Windows explorer , one with a issue with documents and other with the DMS. I move a file with the mouse from the issue  document to the other Windows with  DMS and automatic créate in DMS a URL file. 
This is perfect for me.
In the last days, I repeat this task and now the exporer say me the option to open or save the file in my PC, but never the url its create in DMS.   What's happen? For me its a good idea to have url in DMS and not the phisical file.

Regards

The mechanism was running ok and now

**Comment by picman** [comment]
The only drag&drop feature supported is to drag& drop a file from your file system into the upload area of DMS. URL links must be created manually by creating DMS link and entering URL.
Drag&drop of URL links is not supported.

**Comment by jlsblasco** [comment]
Thank you picman for you quick response, but I remember that the last week this procedure was ok, are you sure that never this procedure should have worked succesfully?
the source was a document from issue and target the área of dms (drag&drop)
