### ISSUE TITLE
Can't modify frozen String error using DMSF internal links

### ISSUE THREAD

**Issue by chhobu** [danmunn/redmine_dmsf#1091]
Using Redmine 4.1.0 and DMSF2.4.2, I have created an internal link (project A) to another DMSF directory project (project B). DMSF main page in project A now throws the following error : 

ActionView::Template::Error (can't modify frozen String)
[...]/plugins/redmine_dmsf/app/models/dmsf_link.rb:110:in `insert'

**Comment by picman** [comment]
Already fixed here: https://github.com/danmunn/redmine_dmsf/commit/08d0898a6a01540636006d95141facda0a6a87f2#diff-c5e72af7afc225755505a5f7812fa337. Update the master branch using git pull or download the latest released zip file again.
