### ISSUE TITLE
Delete project after redmine_dmsf plugin installation

### ISSUE THREAD

**Issue by caesarfive** [danmunn/redmine_dmsf#1092]
After the installation of redmine_dmsf on a fresh redmine installed 
using:
- ruby 2.5.5p157 
- redmine 4.1.0
- postgresql 12
- nginx and passenger
any new  test project created with or without DMSF plugin enabled cannot be deleted anymore throwing an internal error on web interface and reporting in the following message on error.log
-------------------------------------------------------------------------------------------------------------------------------

> App 3439 output: Completed 200 OK in 134ms (Views: 31.3ms | ActiveRecord: 86.6ms)
> App 3439 output: Started DELETE "/projects/pippone" for 192.168.122.1 at 2020-02-17 23:11:09 +0000
> App 3439 output: Processing by ProjectsController#destroy as HTML
> App 3439 output:   Parameters: {"authenticity_token"=>"GYgqlStsvnodQ/PCkJzPcRYHzTJ83ihA3Hn8sVu9Wdd36msBvewh9gS8GeepFerkhTX9MSF65REduxKriWJevQ==", "id"=>"pippone"}
> App 3439 output:   Current user: admin (id=1)
> App 3439 output:   Rendering projects/destroy.html.erb within layouts/base
> App 3439 output:   Rendered projects/destroy.html.erb within layouts/base (3.7ms)
> App 3439 output: Completed 200 OK in 97ms (Views: 35.9ms | ActiveRecord: 51.8ms)
> App 3439 output: Started DELETE "/projects/pippone" for 192.168.122.1 at 2020-02-17 23:11:12 +0000
> App 3439 output: Processing by ProjectsController#destroy as HTML
> App 3439 output:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"mh/qVJJCUoUYX9SXY/O6H2HFJG6oNB+4HP+PjdS/1ZP0favABMLNCQGgPrJaep+K8vcUbfWQ0undPWGXBmDS+Q==", "confirm"=>"1", "commit"=>"Delete", "id"=>"pippone"}
> App 3439 output:   Current user: admin (id=1)
> App 3439 output: Completed 500 Internal Server Error in 631ms (ActiveRecord: 592.1ms)
> App 3439 output:   
> App 3439 output: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "easy_settings" does not exist
> App 3439 output: LINE 8:                WHERE a.attrelid = '"easy_settings"'::regclas...
> App 3439 output:                                           ^
> App 3439 output: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
> App 3439 output:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
> App 3439 output:                      c.collname, col_description(a.attrelid, a.attnum) AS comment
> App 3439 output:                 FROM pg_attribute a
> App 3439 output:                 LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
> App 3439 output:                 LEFT JOIN pg_type t ON a.atttypid = t.oid
> App 3439 output:                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
> App 3439 output:                WHERE a.attrelid = '"easy_settings"'::regclass
> App 3439 output:                  AND a.attnum > 0 AND NOT a.attisdropped
> App 3439 output:                ORDER BY a.attnum
> App 3439 output: ):
> App 3439 output:   
> App 3439 output: app/controllers/projects_controller.rb:264:in `destroy'
> App 3439 output: lib/redmine/sudo_mode.rb:65:in `sudo_mode'
> App 3439 output: plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:72:in `call'
> 

------------------------------------------------------------------------------------------------------------------------

**Comment by shemgp** [comment]
Run: `bundle exec rake db:migrate RAILS_ENV=production` discovered via: https://github.com/sameersbn/docker-redmine/issues/267#issuecomment-332290859
