### ISSUE TITLE
Public URL date cannot be set in Chromium based browsers

### ISSUE THREAD

**Issue by kyotocanuck** [danmunn/redmine_dmsf#1095]
I am currently using 2.4.2 devel but this issue has been present in earlier versions as well. The public URL feature has a read only expiration date field and, in ie / Safari, a calendar button to set the date. In Chrome and now Microsoft Edge, the field is read only and no calendar widget appears in order to allow changing it.

If we cannot get a fix for the calendar, can you explain how to at least allow the field to be editable?

Thank you for this invaluable plugin.

**Comment by picman** [comment]
You can modify your application according to the commit above.

**Comment by kyotocanuck** [comment]
Done. Worked like a charm. Thank you
