### ISSUE TITLE
Permission issue for approval workflow

### ISSUE THREAD

**Issue by aviatorm** [danmunn/redmine_dmsf#1097]
I have permission error with workflow process.
I needed workflow manage for one user and only file approval for other user. And this permissions set up for users in roles.
If document uploaded to DMS, but workflow not yet assigned, user without manage workflow function can select already present approval workflow with workflow select list. Yes, it cant create new approval workflow, but ability for assigning some other workflow is not right, In my opinion.
Debian 10
Redmine 4.1.0
DMSF 2.4.2 devel
Ruby 2.5.5
Rails 5.2.4.1
![IMG_20200305_212236](https://user-images.githubusercontent.com/59228982/76012589-96684300-5f27-11ea-8633-d1f76c00ed79.jpg)
![IMG_20200305_212452](https://user-images.githubusercontent.com/59228982/76012726-d62f2a80-5f27-11ea-92b6-d3a41f8309d8.jpg)

**Comment by picman** [comment]
**manage_workflows** - create, edit and delete workflows
**file_approval** - assign, start and approval

**Comment by aviatorm** [comment]
picman, thanks for comment. However I have my opinion, assign and start is management too.
You are maintainer, and decision by you too.
