### ISSUE TITLE
Issue with accessing a file with multiple revisions

### ISSUE THREAD

**Issue by floriankol** [danmunn/redmine_dmsf#1098]
I've got a strange problem with our dmfs, when users try to access files that have more than one revision the SQl request fails with the following error:
TinyTds::Error: A column has been specified more than once in the order by list. Columns in the order by list must be unique.: EXEC sp_executesql N'SELECT [dmsf_file_revisions].* FROM [dmsf_file_revisions] WHERE [dmsf_file_revisions].[dmsf_file_id] = @0 AND (id < 2052)  ORDER BY dmsf_file_revisions.id DESC, [dmsf_file_revisions].[id] DESC', N'@0 int', @0 = 1363
Redmine version is 3.4.8 and the SQL Server is Version SQL 2012

Thanks

**Comment by picman** [comment]
Upgrade your DMSF plugin. Revisions are sorted by _created_at_ now. It must be an old bug.
