### ISSUE TITLE
SystemStackError (stack level too deep) when click on the "move/copy" button

### ISSUE THREAD

**Issue by ithwsw** [danmunn/redmine_dmsf#1099]
Please help, thanks...

Operation steps:
Edit a folder/file and then click on the Copy/Move button, "Internal Server Error" occurred, and the operation stopped working.

The environment is as follows:
Redmine 3.4.9.stable
DMSF      1.6.2
Ruby       2.4.5-p335
Rails        4.2.11
Below is the production.log when that operation was performed.

```
2020-03-24 09:44:51 +0800 (13054) Started GET "/dmsf/files/20068/copy" for 10.62.35.49 at 2020-03-24 09:44:51 +0800
2020-03-24 09:44:51 +0800 (13054) Processing by DmsfFilesCopyController#new as HTML
2020-03-24 09:44:51 +0800 (13054)   Parameters: {"id"=>"20068"}
2020-03-24 09:44:51 +0800 (13054)   Current user: 16289 (id=11)
2020-03-24 09:45:14 +0800 (13054) Completed 500 Internal Server Error in 22412ms (ActiveRecord: 781.5ms)
2020-03-24 09:45:14 +0800 (13054)
SystemStackError (stack level too deep):
  plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:41:in `lock'
  plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:41:in `lock'
  plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:41:in `lock'
  ~
  hundred lines of "plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:41:in `lock'"
  ~
  plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:41:in `lock'
  plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:41:in `lock'
  plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:41:in `lock'
  plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:41:in `lock'
  
  plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:27:in `locked?'
  plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:89:in `locked_for_user?'
  plugins/redmine_dmsf/app/models/dmsf_folder.rb:207:in `block in directory_tree'
  plugins/redmine_dmsf/app/models/dmsf_folder.rb:207:in `delete_if'
  plugins/redmine_dmsf/app/models/dmsf_folder.rb:207:in `directory_tree'
  plugins/redmine_dmsf/app/controllers/dmsf_files_copy_controller.rb:31:in `new'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'
```

**Comment by picman** [comment]
There seems to be a loop. Didn't you try to copy a folder under the same folder? There used to be such a bug. Upgrade DMSF.

**Comment by ithwsw** [comment]
Hi Picman, 
   When I click on the Copy/Move button, then the "Internal Server Error" page shows up,
no chance to select project or folder.
We have lots of projects in redmine, all with DMSF running, 
only one project has this issue which got lots of folders and files more than other projects,
is it possible that too many folders and files might cause this problem?
thank you...

**Comment by picman** [comment]
There seems to be a loop in folders' hierarchy. I mean that a folder might be in itself. Try to go through the whole hierarchy. Open each folder in GUI until you find the odd one.
If you click the Copy/Move another form is opened with a field with destination folder. The loop occurs very probably when creating the folder tree for destination folder.

**Comment by ithwsw** [comment]
Yes, table dmsf_folders got a loop in folders' hierarchy. 
Thanks for your help and your **great plugin!**   :-)
