### ISSUE TITLE
DMSF Document Upload Issue on Redmine V4.1

### ISSUE THREAD

**Issue by JuanceV20** [danmunn/redmine_dmsf#1102]
When I try to upload a document (not a PDF) I get an error saying "Some files were not committed due to validation errors"

Please assist

**Comment by picman** [comment]
Check the production.log for any errors related to the upload.

**Comment by JuanceV20** [comment]
Hi, 

Thank you. We looked at it and the issue is fixed now. (we had underscores in our naming, we added a plugin and it is fixed)
