### ISSUE TITLE
Permissions for deleting files from the trash

### ISSUE THREAD

**Issue by dinya** [danmunn/redmine_dmsf#1105]
The current behavior of the plugin is to move a file to the trash when it is deleted. After deleting the file from the trash, the file will be completely deleted (?) or it will still be available in the file system if the "Physical file delete" option is disabled in the plugin settings (?).

Is there a way to set permissions for the trash cleaning?

**Comment by picman** [comment]
1) Yes, it's as you describe.
2) No, "delete" and "trash" use the same permission "file delete".

**Comment by dinya** [comment]
> No, "delete" and "trash" use the same permission "file delete".

Is it possible to split these permissions?

Use case:

The Project Admin is the only user can clean the trash.
He/she will not disturb the Redmine Admin with a request to restore files from the file system on every user's fails (only for his/her own :-)).
At the moment, this is probably a hard work that requires direct editing of the database (?). It's good that the file name has an ID.

**Comment by picman** [comment]
No more support for Russians.
