### ISSUE TITLE
Webdav soft compability.

### ISSUE THREAD

**Issue by vodkatruck** [danmunn/redmine_dmsf#1107]
Hello my comrade!
I've installed 2.4.1 version for redmine 4.0.7, but i've got one issue.
Webdav sending error messages "405 Method not allowed" for all the webdav soft.
However, firefox's webdav exploring and dms in redmine work perfectly.

From Russia with love, vodkathuck.

**Comment by picman** [comment]
What is "webdav soft"?

**Comment by vodkatruck** [comment]
Cyberduck, SmartFTP

**Comment by picman** [comment]
Both clients are available for Windows only. So, I can't help you here, sorry.
I'd recommend checking _log/production.log_ for any errors/warnings after a WebDAV request returning 405 Method not allowed.

**Comment by vodkatruck** [comment]
Okai comrad.
Nevertheless, I found that WinSCP is working.
Thank you for your work and support.
Motherland will never forgot you.
