### ISSUE TITLE
Is it possible to change row height?

### ISSUE THREAD

**Issue by j-avdeev** [danmunn/redmine_dmsf#1108]
Hi.
I am upgraded to DMSF 2.4.1

Is it possible to decrease row height?

In older DMSF 1.x rows were more compact.
![DMSF row height](https://user-images.githubusercontent.com/985802/80085278-0e86d880-8569-11ea-8e50-fce545cd1d10.PNG)

**Comment by picman** [comment]
I think you can modify Redmine's theme and modify rows using CSS.
