### ISSUE TITLE
No email notification for author approval workflow, when it was rejected (or approved)

### ISSUE THREAD

**Issue by yurmala** [danmunn/redmine_dmsf#1109]
subject.
dmsf 2.4.2.
redmine 4.1.1.

**Comment by picman** [comment]
Notifications are sent to all project's members unless they have blocked notifications in their user's profile. Please check it.

**Comment by yurmala** [comment]
Don't work for my project:
All recipient - my project member.
There are "Only for things I watch or I'm involved in" mail option for all my project member.

**Comment by picman** [comment]
The rule is that you are involved if you are the author of the last revision of the document. If you are not the author and just started the approval workflow, you won't be notified.
