### ISSUE TITLE
Cyrillyc named document upload error

### ISSUE THREAD

**Issue by etoosamoe** [danmunn/redmine_dmsf#1116]
Hello

Redmine 4.1.0
DMFS devel-2.4.3 (master branch was failed to install, i think it was a conflict with other plugins)

Now I can't upload file with cyrillic symbols in filename.

Log:
```
I, [2020-05-08T13:05:50.956681 #8881]  INFO -- : Completed 500 Internal Server Error in 45ms (ActiveRecord: 35.1ms)
F, [2020-05-08T13:05:50.957852 #8881] FATAL -- :
F, [2020-05-08T13:05:50.957942 #8881] FATAL -- : ActiveRecord::StatementInvalid (Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=': SELECT  `dmsf_files`.* FROM `dmsf_files` WHERE `dmsf_files`.`project_id` = 4 AND `dmsf_files`.`dmsf_folder_id` IS NULL AND `dmsf_files`.`name` = 'Элтекс - Дефектная ведомость.doc' AND `dmsf_files`.`deleted` = 0 ORDER BY `dmsf_files`.`id` ASC LIMIT 1):
F, [2020-05-08T13:05:50.958013 #8881] FATAL -- :
F, [2020-05-08T13:05:50.958195 #8881] FATAL -- : plugins/redmine_dmsf/app/models/dmsf_file.rb:113:in `findn_file_by_name'
plugins/redmine_dmsf/app/models/dmsf_file.rb:106:in `find_file_by_name'
plugins/redmine_dmsf/app/models/dmsf_upload.rb:63:in `initialize'
plugins/redmine_dmsf/app/models/dmsf_upload.rb:53:in `new'
plugins/redmine_dmsf/app/models/dmsf_upload.rb:53:in `create_from_uploaded_attachment'
plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:51:in `block in upload_files'
plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:50:in `upload_files'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'
``` 

I have searched in other issues and found one that point to incorrect collation on tables.
I looked in tables:

built-in redmine tables have utf8:

![image](https://user-images.githubusercontent.com/38806450/81396303-d4ebcb00-912d-11ea-9cf9-bad75ca70184.png)

but dmfs tables installed by migrating (**default manual**):

![image](https://user-images.githubusercontent.com/38806450/81396355-f5b42080-912d-11ea-91bc-68356a32cf52.png)

Is it bug, or smth? What is the right way to fix this for me? I want to install it on production instance with RM 4.0

Actually, it is not only with uploading. I can't add cyrillyc text.

**Comment by ahorek** [comment]
It's not a bug, but a configuration problem on your server, I would recommend you to use utf8mb4

setup config/database.yml
```
production:
  adapter: mysql2
 ....
  encoding: utf8mb4
```

convert existing tables
```
for TABLE in `mysql -e "use ${DB}; show tables;" --batch --skip-column-names | xargs`; do
    echo "Converting ${DB}.${TABLE}"
    mysql -e "alter table ${DB}.${TABLE} CONVERT TO character set utf8mb4 collate utf8mb4_unicode_ci;"
done
```

see https://www.redmine.org/issues/31921 for more details
