### ISSUE TITLE
How can I add 'Comment' column in the file list view?

### ISSUE THREAD

**Issue by nikosfrangakis** [danmunn/redmine_dmsf#1118]
I would like to add a column showing the "Comment" field on the file list view. 
Could you please point me in the right direction to accomplish this?
thanks

**Comment by picman** [comment]
Column **_Comment_** is not available in the main view.

**Comment by mmundi72** [comment]
It would be great to have the possibility to add the "comment" and "description" fields to the main view (configurable in custom queries).

**Comment by picman** [comment]
Description and Comment columns added.
