### ISSUE TITLE
Button "New folder" maybe must be replaced nearly button "New file" (UI better solution)

### ISSUE THREAD

**Issue by yurmala** [danmunn/redmine_dmsf#1119]
subj

**Comment by picman** [comment]
Try to explain your idea better. Ideally with a screen-shot.

**Comment by yurmala** [comment]
![image](https://user-images.githubusercontent.com/9638475/82316292-43a21180-99d5-11ea-8af1-ca01275ad35f.png)

**Comment by picman** [comment]
Done.

**Comment by yurmala** [comment]
Thanks. It's worked.
