### ISSUE TITLE
New UI: Values of custom fields not visible

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1120]
2 custom dmsf fields available: Kategorie / Besitzer

Meta data of a document:
![image](https://user-images.githubusercontent.com/7224922/82543342-af11ed80-9b53-11ea-937c-aa63ad022e46.png)

List view does not show the content:
![image](https://user-images.githubusercontent.com/7224922/82543493-e8e2f400-9b53-11ea-8640-ade5888951b5.png)

**Comment by picman** [comment]
What is the type of the custom fields?

**Comment by mmundi72** [comment]
Kategorie: List   (possible values: Protokoll, Projektauftrag, PMP, Konzept)
Besitzer: Text  (plain text; no additional parameters activated)
