### ISSUE TITLE
New UI: Saving Query -> Internal Server Error

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1121]
When saving a new query I get an 500 internal error message.

(maybe not yet implemented?)

Log content:

Started GET "/projects/projekt-1/queries/new?utf8=%E2%9C%93&set_filter=1&type=DmsfQuery&sort=title&f%5B%5D=&c%5B%5D=id&c%5B%5D=size&c%5B%5D=modified&c%5B%5D=version&c%5B%5D=cf_1&c%5B%5D=cf_2&c%5B%5D=author" for 127.0.0.1 at 2020-05-21 02:13:19 -0700
Processing by QueriesController#new as HTML
  Parameters: {"utf8"=>"✓", "set_filter"=>"1", "type"=>"DmsfQuery", "sort"=>"title", "f"=>[""], "c"=>["id", "size", "modified", "version", "cf_1", "cf_2", "author"], "project_id"=>"projekt-1"}
  Current user: mischa (id=1)
  Rendering queries/new.html.erb within layouts/base
  Rendered queries/_filters.html.erb (421.9ms)
  Rendered queries/_columns.html.erb (14.7ms)
  Rendered queries/_form.html.erb (1396.9ms)
  Rendered queries/new.html.erb within layouts/base (3172.7ms)
  Rendering plugins/redmine_agile/doc/LICENSE
  Rendered plugins/redmine_agile/doc/LICENSE (0.1ms)
  Rendered plugins/redmine_agile/app/views/bitnami/_license_popup.html.erb (46.0ms)
Completed 200 OK in 14660ms (Views: 5596.1ms | ActiveRecord: 408.8ms)
Started POST "/projects/projekt-1/queries" for 127.0.0.1 at 2020-05-21 02:14:03 -0700
Processing by QueriesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"bh904JSMLHiRqLeegs1Aku9OFYSsVk8S+N9/WOkd0n19akPbo4RehrWfDqRLp8cHU+ZKEAtRWZnWA1g4W/ea1Q==", "type"=>"DmsfQuery", "query"=>{"name"=>"DMS Abfrage 1", "visibility"=>"0", "role_ids"=>[""], "group_by"=>"", "sort_criteria"=>{"0"=>["title", "asc"], "1"=>["", ""], "2"=>["", ""]}}, "f"=>[""], "c"=>["id", "size", "modified", "version", "cf_1", "cf_2", "author"], "commit"=>"Save", "project_id"=>"projekt-1"}
  Current user: mischa (id=1)
Completed 500 Internal Server Error in 5292ms (ActiveRecord: 88.2ms)
  
NoMethodError (undefined method `redirect_to_dmsf_query' for #<QueriesController:0x000000000c003f50>
Did you mean?  redirect_to_issue_query):

**Comment by picman** [comment]
Fixed.
