### ISSUE TITLE
New UI: List view improvements

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1123]
For usability reasons I suggest the following improvements to the new list view:

1. Show "lock" for locked documents. It should be instantly visible if a document is locked or not (the function to lock/unlock can still be placed within the action menu)

2. Place "#" to the left most position (same as with issues; the same schema do other plugins follow)

**Comment by mmundi72** [comment]
As we are now working with version 2.4.4 it's getting more obvious that it is difficult for users to instantly see which documents are locked or not. It would be great to have an additional column "Locked by" similiar to the "Author" column. This way a user can activate/deactivate it, a user can sort this column and it could be used as a filter (#1124). This is quite an important enhancement which makes DMSF even more useful.

**Comment by xandre31** [comment]
+1 please. Really usefull feature which disapeared
