### ISSUE TITLE
New UI: Add additional filter "Locked documents"

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1124]
I suggest the following enhancement to the new filter options:

Additional filter called "Locked documents" with the following options:

- Locked by me   
- All locked documents

German translations:
Locked document => Gesperrte Dokumente
Locked by me => Von mir gesperrt
All locked documents => Alle gesperrte Dokumente

**Comment by xandre31** [comment]
Within new version 2.4.4, users can't see anymore directly from list which documents are locked (or not). Previous display with actions and lock status in the list is user friendy than being obliged to click on each "..." button.

Regards,

**Comment by picman** [comment]
v2.4.5 has returned the lock icon to the main view

**Comment by picman** [comment]
Such a view is in **My Page**.

![image](https://user-images.githubusercontent.com/779003/194308002-8d0f1e03-c52b-405d-b1bc-aa4929639835.png)

**Comment by mmundi72** [comment]
Not really - under My Page there is only visible which documents the current user has locked.
My use case is: As a project manager I would like to get a list of all documents which have been locked by any user. I want to make sure that documents are not locked forever.

By the way: what is the meaning of  (0/4) in you screenshot?

**Comment by picman** [comment]
0 folders / 4 documents

**Comment by picman** [comment]
- My locked documents => **My Page**
- All locked documents => a new filter **Locked**
