### ISSUE TITLE
New UI: Question concerning the new filtering options

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1125]
The new DMSF UI looks promising and the new filtering options gives a lot of additional power to the plugin. But I am not sure how the filtering is intended to work...

Does it need Xapian to be installed? I have setup a blank Redmine copy and installed the current devel of DMSF. Here my observation:

Content in DMSF - highlighted in yellow all objects containing the term "konzept":

![image](https://user-images.githubusercontent.com/7224922/82674547-c3cdae80-9c43-11ea-9568-f504b722d3ac.png)

Now I'm filtering by the title "konzept" and I get the following result:
![image](https://user-images.githubusercontent.com/7224922/82674620-e2cc4080-9c43-11ea-9e10-4126b06e2693.png)

Instead of getting 5 Objects in the result, only the one document in the root folder is being shown.

Is that correct? Should it work in this way?
I would have expected to get the 5 objects as shown in screenshot 1.

**Comment by picman** [comment]
The problem is, that filter is applied on the current folder only, so you will see filtered documents from the current folder and not from sub-folders.

**Comment by picman** [comment]
Fixed.
