### ISSUE TITLE
NameError: uninitialized constant RedmineExtensions::Migration

### ISSUE THREAD

**Issue by kaitaku** [danmunn/redmine_dmsf#1126]
The error below occurs when upgrading from redmine 3.4 to 4.1
ruby 2.5.7
OS: mac

rake db:migrate RAILS_ENV=production 

NameError: uninitialized constant RedmineExtensions::Migration
/Users/xxxx/.rvm/gems/ruby-2.5.7/gems/redmine_extensions-0.3.11/db/migrate/20190206121100_remove_foreign_key_from_easy_settings.rb:1:in `<top (required)>'

**Comment by picman** [comment]
As you can see the error is in Redmine Extension plugin.
