### ISSUE TITLE
Help integrating new feature - Auto-update word files with dmsf revision

### ISSUE THREAD

**Issue by PedroTeixido** [danmunn/redmine_dmsf#1127]
Hello,

I have written a small ruby program to modify word files (only docx) so that the word **_revnum_** field is updated.

My plan is to run this code in the upload process. So that, when a docx file is committed, redmine will automatically update the content of the document to match the dmsf file and revision IDs.
This ensures information within the word file is always synchronised with redmine information.

I'm not a ruby programmer, so I'm struggling to find where to call my code from. Can you point me to any part for the upload process where the file has already been committed so that file and revision IDs are accessible? The interface of my code is something like this:

   update_word_docx_references(file_path_and_name, dmsf_file_id, dmsf_revision_id)

I would really appreciate if you could help me with this. And I would be happy to do a pull request once working if you are interested.

Thank you very much!

  Pedro

**Comment by picman** [comment]
I think that the right way is to add a hook which you can implement in your plugin. As you ca see in the related revision above I've added a helper hook `:dmsf_helper_upload_after_commit` to the place where a new file is committed.
How to implement such a hook, you can see in _lib/redmine_dmsf/hooks/helpers/issue_hepler_hooks.rb_.

**Comment by picman** [comment]
I've added the hook calling into the new revision method tool. test it, please.

**Comment by PedroTeixido** [comment]
Thanks, it works!! :-)

Not sure about the name of the hook referring to the dmsf_upload_helper module now that it is also called from dmsf_files_controller module. If you decide to change it I'll adapt on my side.

I have tried to attach the patch file I did for our system in case some else wanted to use it, but I said it's not a supported file. What's the correct way of doing so?

See attached work with a list of the custom properties dmsf will update through this hook

Thanks,
  Pedro

[redmine_dmsf_word_template.docx](https://github.com/danmunn/redmine_dmsf/files/4770486/redmine_dmsf_word_template.docx)

**Comment by picman** [comment]
What's type is the patch? See the rules [here](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests).

**Comment by PedroTeixido** [comment]
it is a plain text file with .patch extension created with a git diff command

**Comment by picman** [comment]
So simply zip the patch. .zip files are allowed.

**Comment by PedroTeixido** [comment]
OK, 

There we go. This  is the patch I have done for DMSF 1.6.0 but the hook can be used with any version. 

Thanks for your support!

[redmine_dmsf_word_update.zip](https://github.com/danmunn/redmine_dmsf/files/4791772/redmine_dmsf_word_update.zip)
