### ISSUE TITLE
New UI: Optimize Actions Menu

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1129]
I suggest to optimize the Actions Menu and to make sure that actions for documents and folders are available to both object types:

![image](https://user-images.githubusercontent.com/7224922/83146506-b35f7d00-a0f6-11ea-8f2c-47c3a6391045.png)

**Comment by picman** [comment]
I agree with the most of changes. However, I wouldn't move "Edit content" as it's not available for all documents and on all systems and put it just above "Delete". I grues that it's gray/unavailable in the most cases.

**Comment by Km-swp** [comment]
I'm sorry for suddenly interrupting you.
How can I make this "gray / unavailable" work?

I'm sorry, but I'm Japanese, so I'm not good at English.

**Comment by picman** [comment]
Be more specifics. An item can be gray/disabled due to missing permissions or that the file is not editable(Edit content)

**Comment by picman** [comment]
Create a new issue with a screen-shot and an exact description.
