### ISSUE TITLE
Documents not found after plugin update

### ISSUE THREAD

**Issue by sseide** [danmunn/redmine_dmsf#1130]
Hello,
currently we have updated the dmsf plugin together with redmine from a older version.
After update a list of all files/folders can be seen through the Web-UI and via WebDav but the files itself cannot be accessed anymore - the request to view/download them returns a HTTP 404. 

The plugin settings do not show any errors - the "File storage directory" is correct and redmine can access it (no error message there). Uploading new documents via DMSF is working and they can be viewed/downloaded afterwards.

BUT:
the directory structure seems to have changed between the old version of the plugin and the new version and documents where not migrated to the new directory structure.

All document files from our old installation are saved below the directory
`/var/lib/redmine/default/files/dmsf/p_<project_identifer>/` but newly uploaded documents are stored below `/var/lib/redmine/default/files/dmsf/2020/06/`.

Is this new folder structure the reason for documents not accessible anymore? Can the folder structure be configured somewhere? Or does some rake task exist to migrate files to the new structure?

Running `$ rake redmine:dmsf_maintenance dry_run=1 RAILS_ENV="production"`
list some old and lots of corrupt files.

```
Files...
       ....
Documents...
	/var/lib/redmine/default/files/dmsf/2014/04/140430000141_1_Aufgabenstellung_131101.pdf
       ...

14 files haven't got a coresponding revision and can be deleted.
244 KB can be released.

0 links can be deleted.

156 corrupted documents.
```

Using:
* Debian 10
* Ruby 2.5.5 (from deb package)
* Redmine 4.0.7-1~bpo10+1 (from deb backports)
* Redmine_DMSF 2.4.1 (installed via git)

As i understand the changelog we cannot switch to v2.4.2 as it does not support Redmine 4.0 any longer.

Thanks,
Stefan Seide

**Comment by picman** [comment]
There were very probably errors during the migration which you ignored. Please see #799 and #767 for a solution.

**Comment by sseide** [comment]
thanks - the unix script from 767 moved all files and they are accessible now.

regarding the errors - maybe there were some, but these messages did not look like errors at all (how should i now nil is not valid here?). Therefor went unnoticed between all these hundreds of other lines. For future updates it helps to clearly mark such things with "ERROR" or similar.

and just for information - we went directly from version 1.4.8 to 2.4.1 without trying to install the broken 1.6.0 in between.
