### ISSUE TITLE
Feature Request: Please support all current Redmine-Versions (e.g. 4.0)

### ISSUE THREAD

**Issue by sseide** [danmunn/redmine_dmsf#1131]
On the README of latest version of your Plugin (2.6.2) its statet that minimum Redmine version is 4.1. and therefore the 2.6.1 is the latest version usable with Redmine 4.0.x

For current Redmine development booth 4.0 and 4.1 are supported and get security fixes. Therefore it would be really helpful to have booth redmine versions supported with the plugin.

Is it possible to add suport for 4.0.x again? Why was it dropped?

Thanks in Advance,
Stefan Seide

**Comment by picman** [comment]
I don't remember but there had to be a reason ;-)
You can simply try it with Redmine 4.0. Just comment out or modify Redmine's dependency in init.rb file.

```ruby
38 -- requires_redmine version_or_higher: '4.1.0'
38 ++ requires_redmine version_or_higher: '4.0.0'
```

**Comment by sseide** [comment]
Ok - found some time to play around with it. First i setup Redmine 4.0.7 and redmine_dmsf 2.4.1 (latest for 4.0) to check everything is working.

Now updated to 2.4.2 and later to 2.4.3 and changed the `requires_redmine version_or_higher` as you said.
Tested different things like up-/download / move / edit / delete /access via webdav and everything worked like a charme with booth plugin version (2.4.2 and 2.4.3)
Only found one deprecation warning inside the logfile during tests, but no errors.

Looks like you just changed the wrong number - this change was commited together with the "v2.4.2 release" commit instead of changing the plugins version number above (commit 89df08f85667853dbf661a744ef0fa6b0dff5429).

Your Travis worked well too for 4.0 until this commit. And this commit only added docs/changelog and changed the min_req version and nothing else.
After updating the min req number travis has to fail as your 4.0 tests pulled redmine 4.0.6 and this does not match...
https://travis-ci.org/github/danmunn/redmine_dmsf/jobs/639958090#L571

I suggest lowering the redmine min version, re-adding travis for redmine 4.0 and everything will be green again...

**Comment by sseide** [comment]
oh - and i forgot:

README.md line 227 - is not the task named `redmine:plugins:migrate` instead of `plugins:migrate`?

**Comment by picman** [comment]
You're right. Fixed.

**Comment by sseide** [comment]
Thanks!
