### ISSUE TITLE
Migration 2.4.2 -> 2.4.3 with Redmine 4.1.1: Error 500 when attempting to display DMSF pages

### ISSUE THREAD

**Issue by sunnyphone** [danmunn/redmine_dmsf#1134]
Hello
Here is what I get when I attempt to display de DMSF page after having updated it from version 2.4.2 to 2.4.3:
![firefox_bPINXVCBrY](https://user-images.githubusercontent.com/42149156/84584946-80153180-ae0a-11ea-8433-b22862f128f4.png)

In the log files, the following message:
```
Started GET "/projects/xxxxxxxx/dmsf" for xxx.xxx.xxx.xxx at 2020-06-14 06:17:56 +0200
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"xxxxxxxxxxxxxx"}
  Current user: pbreau (id=5)
Completed 500 Internal Server Error in 6ms (ActiveRecord: 1.8ms)
  
ArgumentError (wrong number of arguments (given 2, expected 1)):
  
plugins/redmine_dmsf/app/models/dmsf_query.rb:41:in `initialize'
app/helpers/queries_helper.rb:313:in `retrieve_query'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:633:in `get_query'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'
```

Here is my config:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [amd64-freebsd12]
  Rails version                  5.2.4.2

Direct links to documents still work.

Thank you for your help

Kind regards

**Comment by picman** [comment]
Could you update your master branch (git pull) and test it again, please?

**Comment by sunnyphone** [comment]
The issue is fixed!

Thank you very much for your development and your assistance.

Best regards
