### ISSUE TITLE
 Move or copy files to a directory different than the root

### ISSUE THREAD

**Issue by jlg29387** [danmunn/redmine_dmsf#1135]
Hello,

I need help with this.

I can only move or copy files to another directory only with the administrator profile. I have enabled all checks in the profiles but when I go to move them only the project's Documents root path is shown. 

This is my DMSF directory of the project.
![image](https://user-images.githubusercontent.com/21282197/84752708-63b9f600-afbe-11ea-8d9a-29df0a45ff06.png)

I want move the file but only show directory root Documents with other profile different that administrator system.
![image](https://user-images.githubusercontent.com/21282197/84753047-cf03c800-afbe-11ea-829f-99e34a2779f1.png)

Like administrator system you can watch this.
![image](https://user-images.githubusercontent.com/21282197/84753335-29048d80-afbf-11ea-960b-77adfdf64da5.png)

My redmine version es 4.0.3.stable

Thanks.

**Comment by picman** [comment]
I've just tested it, and it seems to be working properly. Does the user have corresponding rights to the destination project? Haven't you set permissions in folders of the destination projects, which prevent the non-admin user from accessing them?

**Comment by jlg29387** [comment]
This is my actual configuration.

The user "Tecnico de Explotacion - ODP" have the profile "Coordinador" in the project
![image](https://user-images.githubusercontent.com/21282197/84769964-07af9b80-afd7-11ea-80ea-34a8f3b74c50.png)

This profile have this configuration of DMSF
![image](https://user-images.githubusercontent.com/21282197/84770062-362d7680-afd7-11ea-995c-cb9897a6eb5e.png)

I am trying to move a daughter folder in the same project, the user has visibility and can access the folders, but in the drop-down it is not only shown the root when he wants to move or copy the file.

**Comment by picman** [comment]
I really don't know.
1) Check that the destination folders are not locked.
2) Check that the destination folders are not protected by permissions (**Allow access only to**).
3) Check the _production.log_ for any related errors.

You can also add some logging into the application, restart the application  and check the _production.log_ then.

_app/models/dmsf_folder.rb_

```ruby
def self.directory_tree(project, current_folder = nil)
    tree = [[l(:link_documents), nil]]
    project_id = (project.is_a?(Project)) ? project.id : project
    folders = DmsfFolder.where(project_id: project_id, dmsf_folder_id: nil).visible(false).to_a
Rails.logger.info ">>> invisible removed #{folders.count}"
    # TODO: This prevents copying folders into its sub-folders too. It should be allowed.
    folders.delete(current_folder)
Rails.logger.info ">>> current folder removed #{folders.count}"
    #
    folders = folders.delete_if{ |f| f.locked_for_user? }
Rails.logger.info ">>> locked removed #{folders.count}"
    folders.each do |folder|
      tree.push(["...#{folder.title}", folder.id])
      DmsfFolder.directory_subtree(tree, folder, 2, current_folder)
    end
    return tree
  end
```

**Comment by jlg29387** [comment]
This is what the log paints:

Started GET "/redmine/dmsf/files/15528/copy" for 10.118.135.30 at 2020-06-17 12:46:40 +0200
Processing by DmsfFilesCopyController#new as HTML
  Parameters: {"id"=>"15528"}
  Current user: tecnicoexplotacion.odp.cul (id=484)
>>> invisible removed 0
>>> current folder removed 0
>>> locked removed 0
  Rendering plugins/redmine_dmsf/app/views/dmsf_files_copy/new.html.erb within layouts/base
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_folders_copy/_form.html.erb (23.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files_copy/new.html.erb within layouts/base (26.6ms)
  Rendered plugins/redmine_status_report/app/views/issues_status_report/_additional_assets.html.erb (0.3ms)
  Rendered plugins/redmine_wiki_extensions/app/views/wiki_extensions/_html_header.html.erb (4.4ms)
  Rendered plugins/redmine_hide_sidebar/app/views/sidebar/_hideButton_partial.html.erb (0.0ms)
  Rendered plugins/redmine_wiki_extensions/app/views/wiki_extensions/_body_bottom.html.erb (0.1ms)
Completed 200 OK in 1360ms (Views: 123.2ms | ActiveRecord: 160.4ms)

**Comment by picman** [comment]
Add one more log line


```ruby
def self.directory_tree(project, current_folder = nil)
    tree = [[l(:link_documents), nil]]
    project_id = (project.is_a?(Project)) ? project.id : project
Rails.logger.info ">>> all folders #{DmsfFolder.where(project_id: project_id, dmsf_folder_id: nil).count}"
    folders = DmsfFolder.where(project_id: project_id, dmsf_folder_id: nil).visible(false).to_a
Rails.logger.info ">>> invisible removed #{folders.count}"
    # TODO: This prevents copying folders into its sub-folders too. It should be allowed.
    folders.delete(current_folder)
Rails.logger.info ">>> current folder removed #{folders.count}"
    #
    folders = folders.delete_if{ |f| f.locked_for_user? }
Rails.logger.info ">>> locked removed #{folders.count}"
    folders.each do |folder|
      tree.push(["...#{folder.title}", folder.id])
      DmsfFolder.directory_subtree(tree, folder, 2, current_folder)
    end
    return tree
  end
```

**Comment by jlg29387** [comment]
In this case paint:

Started GET "/redmine/dmsf/files/15528/copy" for 10.118.135.30 at 2020-06-17 13:33:17 +0200
Processing by DmsfFilesCopyController#new as HTML
  Parameters: {"id"=>"15528"}
  Current user: tecnicoexplotacion.odp.cul (id=484)
>>> all folders 6
>>> invisible removed 0
>>> current folder removed 0
>>> locked removed 0
  Rendering plugins/redmine_dmsf/app/views/dmsf_files_copy/new.html.erb within layouts/base
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_folders_copy/_form.html.erb (52.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files_copy/new.html.erb within layouts/base (68.2ms)
  Rendered plugins/redmine_status_report/app/views/issues_status_report/_additional_assets.html.erb (1.5ms)
  Rendered plugins/redmine_wiki_extensions/app/views/wiki_extensions/_html_header.html.erb (4.6ms)
  Rendered plugins/redmine_hide_sidebar/app/views/sidebar/_hideButton_partial.html.erb (0.0ms)
  Rendered plugins/redmine_wiki_extensions/app/views/wiki_extensions/_body_bottom.html.erb (0.1ms)
Completed 200 OK in 1937ms (Views: 217.5ms | ActiveRecord: 437.9ms)

**Comment by jlg29387** [comment]
I tried to drag it to the folder but it gives me a 500 error. This paints the log.

Started PUT "/redmine/projects/pro283/dmsf" for 10.118.135.30 at 2020-06-18 10:43:44 +0200
Processing by DmsfController#drop as JS
  Parameters: {"dmsf_folder"=>{"drag_id"=>"file-15528", "drop_id"=>"folder-4732"}, "id"=>"pro283"}
  Current user: tecnicoexplotacion.odp.cul (id=484)
Completed 500 Internal Server Error in 191ms (ActiveRecord: 6.8ms)
  
NoMethodError (undefined method `dmsf_workflow_assigned_by_user_id=' for #<DmsfFileRevision:0x00005585571911d0>
Did you mean?  dmsf_workflow_assigned_by_user=
               dmsf_workflow_assigned_by_user
               dmsf_workflow_assigned_by=
               dmsf_workflow_assigned_by
               dmsf_workflow_assigned_by_was
               dmsf_workflow_assigned_by?
               dmsf_workflow_assigned_by_changed?
               dmsf_workflow_assigned_by_change
               dmsf_workflow_started_by_user=
               dmsf_workflow_started_by_user
               dmsf_workflow_assigned_at_changed?):
  
plugins/redmine_dmsf/app/models/dmsf_file.rb:245:in `move_to'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:387:in `drop'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'

**Comment by picman** [comment]
It seems that you haven't run database migration
```ruby
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```
have you?

**Comment by jlg29387** [comment]
Correct, when executing this, even though the fields were already created, it seems that it has been correctly reconfigured.

Thank you so much for everything.
