### ISSUE TITLE
Title shows up in 'order by' clause multiple times 

### ISSUE THREAD

**Issue by ChadJPetersen** [danmunn/redmine_dmsf#1138]
The error from the logs is:
`Processing by DmsfController#show as HTML
  Parameters: {"id"=>"XXXXXX"}
  Current user: XXXX (id=XXX)
  Rendering plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_main.html.erb (1.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.3ms)
  Rendered queries/_filters.html.erb (5.1ms)
  Rendered queries/_columns.html.erb (1.8ms)
  Rendered queries/_query_form.html.erb (15.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb (174.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb (181.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (215.3ms)
Completed 500 Internal Server Error in 511ms (ActiveRecord: 261.0ms)
  
ActionView::Template::Error (TinyTds::Error: A column has been specified more than once in the order by list. Columns in the order by list must be unique.: EXEC sp_executesql N'SELECT  [dmsf_folders].* FROM ( (SELECT [dmsf_folders].* FROM ( (SELECT [dmsf_folders].* FROM ( (SELECT [dmsf_folders].* FROM ( (SELECT DISTINCT 
          dmsf_folders.id AS id,
          dmsf_folders.project_id AS project_id,
          CAST(NULL AS decimal) AS revision_id,
          dmsf_folders.title AS title,
          NULL AS filename,
          CAST(NULL AS decimal) AS size,
          dmsf_folders.updated_at AS updated,
          CAST(NULL AS decimal) AS major_version,
          CAST(NULL AS decimal) AS minor_version,
          CAST(NULL AS decimal) AS workflow,
          CAST(NULL AS decimal) AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          ''folder'' AS type,
          dmsf_folders.deleted AS deleted,
          0 AS sort  FROM [dmsf_folders] INNER JOIN [projects] ON [projects].[id] = [dmsf_folders].[project_id] LEFT JOIN users ON dmsf_folders.user_id = users.id LEFT JOIN dmsf_folder_permissions ON dmsf_folders.id = dmsf_folder_permissions.dmsf_folder_id WHERE [dmsf_folders].[deleted] = @0 AND (projects.status <> 9 AND EXISTS (SELECT 1 AS one FROM enabled_modules em WHERE em.project_id = projects.id AND em.name=''dmsf'')) AND [dmsf_folders].[project_id] = @1 AND [dmsf_folders].[dmsf_folder_id] IS NULL AND [dmsf_folders].[deleted] = @2) UNION ALL (SELECT 
          dmsf_links.id AS id,
          COALESCE(dmsf_folders.project_id, dmsf_links.project_id) AS project_id,
          dmsf_links.target_id AS revision_id,
          dmsf_links.name AS title,
          dmsf_folders.title AS filename,
          CAST(NULL AS decimal) AS size,
          COALESCE(dmsf_folders.updated_at, dmsf_links.updated_at) AS updated,
          CAST(NULL AS decimal) AS major_version,
          CAST(NULL AS decimal) AS minor_version,
          CAST(NULL AS decimal) AS workflow,
          CAST(NULL AS decimal) AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          ''folder-link'' AS type,
          dmsf_links.deleted AS deleted,
          0 AS sort  FROM [dmsf_links] LEFT JOIN dmsf_folders ON dmsf_links.target_id = dmsf_folders.id LEFT JOIN users ON users.id = COALESCE(dmsf_folders.user_id, dmsf_links.user_id) WHERE [dmsf_links].[target_type] = @3 AND [dmsf_links].[project_id] = @4 AND [dmsf_links].[dmsf_folder_id] IS NULL AND [dmsf_links].[deleted] = @5) ) [dmsf_folders]) UNION ALL (SELECT 
          dmsf_files.id AS id,
          dmsf_files.project_id AS project_id,
          dmsf_file_revisions.id AS revision_id,
          dmsf_file_revisions.title AS title,
          dmsf_file_revisions.name AS filename,
          dmsf_file_revisions.size AS size,
          dmsf_file_revisions.updated_at AS updated,
          dmsf_file_revisions.major_version AS major_version,
	        dmsf_file_revisions.minor_version AS minor_version,
          dmsf_file_revisions.workflow AS workflow,
          dmsf_file_revisions.dmsf_workflow_id AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          ''file'' AS type,
          dmsf_files.deleted AS deleted,
          1 AS sort  FROM [dmsf_files] INNER JOIN [dmsf_file_revisions] ON [dmsf_file_revisions].[dmsf_file_id] = [dmsf_files].[id] LEFT JOIN users ON dmsf_file_revisions.user_id = users.id WHERE (dmsf_file_revisions.created_at = (SELECT MAX(r.created_at) FROM dmsf_file_revisions r WHERE r.dmsf_file_id = dmsf_file_revisions.dmsf_file_id)) AND [dmsf_files].[project_id] = @6 AND [dmsf_files].[dmsf_folder_id] IS NULL AND [dmsf_files].[deleted] = @7) ) [dmsf_folders]) UNION ALL (SELECT 
          dmsf_links.id AS id,
          dmsf_files.project_id AS project_id,
          dmsf_files.id AS revision_id,
          dmsf_links.name AS title,
          dmsf_file_revisions.name AS filename,
          dmsf_file_revisions.size AS size,
          dmsf_file_revisions.updated_at AS updated,
          dmsf_file_revisions.major_version AS major_version,
	        dmsf_file_revisions.minor_version AS minor_version,
          dmsf_file_revisions.workflow AS workflow,
          dmsf_file_revisions.dmsf_workflow_id AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          ''file-link'' AS type,
          dmsf_links.deleted AS deleted,
          1 AS sort  FROM [dmsf_links] JOIN dmsf_files ON dmsf_files.id = dmsf_links.target_id JOIN dmsf_file_revisions ON dmsf_file_revisions.dmsf_file_id = dmsf_files.id LEFT JOIN users ON dmsf_file_revisions.user_id = users.id WHERE (dmsf_file_revisions.created_at = (SELECT MAX(r.created_at) FROM dmsf_file_revisions r WHERE r.dmsf_file_id = dmsf_file_revisions.dmsf_file_id)) AND [dmsf_links].[project_id] = @8 AND [dmsf_links].[dmsf_folder_id] IS NULL AND [dmsf_links].[deleted] = @9) ) [dmsf_folders]) UNION ALL (SELECT 
          dmsf_links.id AS id,
          dmsf_links.project_id AS project_id,
          CAST(NULL AS decimal) AS revision_id,
          dmsf_links.name AS title,
          dmsf_links.external_url AS filename,
          CAST(NULL AS decimal) AS size,
          dmsf_links.updated_at AS updated,
	        CAST(NULL AS decimal) AS major_version,
          CAST(NULL AS decimal) AS minor_version,
          CAST(NULL AS decimal) AS workflow,
          CAST(NULL AS decimal) AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          ''url-link'' AS type,
          dmsf_links.deleted AS deleted,
           1 AS sort  FROM [dmsf_links] LEFT JOIN users ON dmsf_links.user_id = users.id WHERE [dmsf_links].[target_type] = @10 AND [dmsf_links].[project_id] = @11 AND [dmsf_links].[dmsf_folder_id] IS NULL AND [dmsf_links].[deleted] = @12) ) [dmsf_folders]  ORDER BY sort, title ASC, title OFFSET @13 ROWS FETCH NEXT @14 ROWS ONLY', N'@0 int, @1 int, @2 int, @3 nvarchar(10), @4 int, @5 int, @6 int, @7 int, @8 int, @9 int, @10 nvarchar(10), @11 int, @12 int, @13 int, @14 int', @0 = 0, @1 = 16, @2 = 0, @3 = N'DmsfFolder', @4 = 16, @5 = 0, @6 = 16, @7 = 0, @8 = 16, @9 = 0, @10 = N'DmsfUrl', @11 = 16, @12 = 0, @13 = 0, @14 = 250):
    25:   <% options[:offset] = dmsf_pages.offset %>
    26:   <% options[:limit] = dmsf_pages.per_page %>
    27: <% end %>
    28: <% query.dmsf_nodes(options).each do |node| %>
    29:   <% system = node.title =~ /^\./ %>
    30:   <% id = (node.type == 'folder') ? "#{node.id}span" : "#{node.id}item" %>
    31:   <% @idnt ||= 0 %>
  
plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb:28:in `_plugins_redmine_dmsf_app_views_dmsf__query_rows_erb__88081436_174367560'
plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb:49:in `block in _plugins_redmine_dmsf_app_views_dmsf__query_list_html_erb__485134658_174724280'
plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb:26:in `_plugins_redmine_dmsf_app_views_dmsf__query_list_html_erb__485134658_174724280'
plugins/redmine_dmsf/app/views/dmsf/show.html.erb:77:in `_plugins_redmine_dmsf_app_views_dmsf_show_html_erb__103761317_175646600'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:76:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:72:in `show'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :having_mail. Overwriting existing method User.having_mail.
Creating scope :system. Overwriting existing method Enumeration.system.
`

I have found that changing line 135 of <redmine>\plugins\redmine_dmsf\app\models\dmsf_query.rb

From: 
`order_option = ['sort', group_by_sort_order, (options[:order] || sort_clause[0]), 'title'].flatten.reject(&:blank?)`

To: 
`order_option = ['sort', group_by_sort_order, (options[:order] || sort_clause[0])].flatten.reject(&:blank?)`

just removing 'title' from the end of the array fixed the issue. And from my testing has not had any negative side effects. Would someone with a  little better grasp on the whole system check if this breaks something else?

This is running on windows server 2016 and Microsoft SQL Server 2016.
Redmine version 4.1.1

Thanks for an awesome plugin!

**Comment by picman** [comment]
The bug is related to MS SQL and therefore didn't found earlier. Thank you for reporting. Also your suggested solution is perfect! Fixed.
