### ISSUE TITLE
Folder can not be deleted if the folder contains files or folders

### ISSUE THREAD

**Issue by s-tkt** [danmunn/redmine_dmsf#1145]
When deleting folder that has files or folders under the folder with WebDAV client, DMSF returns  HTTP 409. The folder must be deleted after all child files and folders.
I tried with many WebDAV clients including WinSCP, it got the same result.

**Comment by picman** [comment]
This is a feature. Also from web interface just empty folders can be deleted.

**Comment by s-tkt** [comment]
Thanks for your rapid reply. I have respect for that specification, however, I hope you sometimes remember of RFC2518:

8.6.2 DELETE for Collections

   The DELETE method on a collection MUST act as if a "Depth: infinity"
   header was used on it.  A client MUST NOT submit a Depth header with
   a DELETE on a collection with any value but infinity.

**Comment by picman** [comment]
Done. Delete and restore functions allowed for non-empty folders in GUI and WebDAV as well.

**Comment by s-tkt** [comment]
I made sure it works actually.
Thank you so much.
