### ISSUE TITLE
Files not attached to Issues any more after update

### ISSUE THREAD

**Issue by mdecker** [danmunn/redmine_dmsf#1147]
I'm currently in the process of upgrading from Redmine 3.3.1 with DMSF 1.5.9 (Debian 9) to Redmine 4.0.7 with the current DMSF 2.4.3 (Debian 10) using the Debian Redmine package. While testing I ran into several migration issues with incompletely migrated DMSF files that I managed to solve with the help of both #767 and #843.

Files were not moved to the new structure for unclear reasons. I have studied the migration output for some time but could not find any particular pattern explaining why most files were migrated and some were not. Some were also migrated to new directories, but with the wrong date stamp.  Roughly 10% of files were not migrated at all and a few ended up in directories that did not match their prefixed timestamp. The files in question look perfectly fine to me on the old system and I cannot see any inconsistencies there. The script from #767  fixed that for me. The files in the `.Issues` directories only became accessible once I also applied the database patch from #843. Before I got error 403 when trying to access them.

What I'm still struggling with is the fact that files belonging to issues are now accessible via `DMS/.Issues/<Issue ID>` which was not the case before but are not attached to the issue itself any more. I still see the history about how the file was uploaded (and never deleted according to that history) but it is just not attached any more and thus cannot be accessed through the issue itself. Uploading new files to an Issue works as expected, though. Any ideas or hints what could be wrong there? I cannot find any documentation what the `.Issues` directory is about, either. Is that supposed to be visible now or is it a side effect of something else being broken? I also understand that I skipped a lot of intermediate Redmine and DMSF versions. Maybe there's a problem in this huge migration step somewhere? The upgraded version runs on a new server, so I still have both installations to compare in case that helps with diagnostics.

**Comment by mdecker** [comment]
I just found that `Act as attachable` is a new option that was not enabled on the migrated system. This makes the attachment visible in the Issues again. My bad for missing that part in #843. It was certainly a surprising change of functionality for me.

**Comment by mdecker** [comment]
I also finally located the `Display System Folders` permission as well and can confirm that the folder is only visible to an Admin. Sorry for the confusion. Something is still broken in the automatic migration, though. Closing.

**Comment by picman** [comment]
You're right. The migration of documents to the new folder structure is painful. Especially in case of such a big step from 1.5.9 to 2.4.3. I'm glad that you've managed to fix all the problems.
