### ISSUE TITLE
New permission: Activate/deactivate notifications

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1148]
Please provide an additional permission which can be assigned to used roles. This permission can be used to specify which users are allowed to turn on notifications.

Reason: Feature #557 has not been implemented yet and I get complaints that there are too many notifications sent from DMSF. Unfortunately the permission to activate notifications is not yet separated.

As as starter it would help to have that separated as long this is not working in the same way as Redmine does it with issues and wiki pages.

Thanks.

**Comment by picman** [comment]
In scope of #557 has been implemented Watch/Unwatch functionality the same way as for other modules in Redmine including permissions to add/delete/view watchers.
The original DMS notifications are off by default now and it wouldn't make sense to add the permissions for them too.
