### ISSUE TITLE
Add document revision.patch_version

### ISSUE THREAD

**Issue by philvy** [danmunn/redmine_dmsf#1151]
Current versioning for documents allows for major and minor (revision.major_version and revision.minor_version):
![image](https://user-images.githubusercontent.com/15813637/87687155-ed531400-c774-11ea-92c0-23fe2f2e5587.png)

Versioning of the plugin itself utilises the common standard of three numbers for major, minor and patch version:
![image](https://user-images.githubusercontent.com/15813637/87687212-fe9c2080-c774-11ea-92ad-0e9c1537bca0.png)

This is also a common standard, for example through https://semver.org/spec/v2.0.0.html.
Proposing to allow document versions to allow for three numbers: revision.major_version, revision.minor_version and revision.patch_version.

**Comment by magic-k** [comment]
This is also important for us especially when we want to track external documents. Major.Minor.Patch notation is standard for a very long time.

**Comment by picman** [comment]
![image](https://user-images.githubusercontent.com/779003/159280762-745af0f3-1282-4540-9c62-1a2f12ea9c3d.png)
