### ISSUE TITLE
Documentation workflow - Assignee tracking not working

### ISSUE THREAD

**Issue by JuanceV20** [danmunn/redmine_dmsf#1152]
We have experienced an issue whereby you cannot see where or to whom documents have been assigned to once uploaded to DMS on Redmine and a workflow has been assigned.

Any advise on what could cause only the administrator to see where the document is and or assigned to?

**Comment by picman** [comment]
Check the DMSF's roles and permissions in **Administration**. Then also add a detailed description of the problem. What is not visible. Ideally with some screen-shots.
