### ISSUE TITLE
Where is bar for fast file upload dropping in v.2.4.4 ?

### ISSUE THREAD

**Issue by j-avdeev** [danmunn/redmine_dmsf#1153]
Hello.

I updated to redmine 4.1.1 + DMSF v. 2.4.4 and found that my favorite bar for fast file uplodating threw drag&drop is dissapeared (see attached image). This bar was in DMSF v. 2.4.1.
Now I have to press "New File" before eacht time I want to upload new file.

The situation with an additional click seem less convenient to me.
Or am I doing something wrong?

![DMSF-FastDrop](https://user-images.githubusercontent.com/985802/88560027-a3a0de00-d03e-11ea-928b-511010b7e996.PNG)

**Comment by picman** [comment]
No, the upload control has really been moved into **New File**. I want to keep the same appearance as other Redmine's modules.
