### ISSUE TITLE
How to update (not upgrade)

### ISSUE THREAD

**Issue by teatower** [danmunn/redmine_dmsf#1154]
Hi to all,

thank you for this great plugin.
I have read the install/upgrade session and it worked well for me.
Nevertheless I am not on the most up-to-date version of redmine_dmsf and want to update.
What is the correct way to do so?

Although it is not a bug of this plugin, are you arware of white bubbles appearing on mouse over on the lock- /pen- / workflow-sign, but only showing a white-filled bubble instead of an explaining hint, as one would expect?

Thank you very much.
Kind regards,
teatower

**Comment by picman** [comment]
1 Update
1.1 Replace plugins/redmine_dmsf sub-folder with a more up to date version. Either using `git pull` or manually.
1.2 Run `bundle install`, `bundle exec rake redmine:plugins:migrate RAILS_ENV=production`.
1.3 Restart the web server.
2. These icons have been replaced with context menu.
