### ISSUE TITLE
Editing a document also changes its title

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1156]
Please have a look at this behavior. It's quite odd, that the title is beeing changed when a document is directly opened in editing mode in MS Word:

![grafik](https://user-images.githubusercontent.com/7224922/89021320-a2163500-d320-11ea-97fc-58ac7eebd091.png)

I expect that the title is not beeing changed by just editing its content. 
Alternative: DMSF is using the proper title tag from the Word Document as such - but that is also not the case.

**Comment by picman** [comment]
Fixed.
