### ISSUE TITLE
EXIF info lost when file uploaded.

### ISSUE THREAD

**Issue by dexterdeng** [danmunn/redmine_dmsf#1157]
Hi，  it seems each time when I upload a file, the dmsf will create a new file. and EXIF lost . so I can't know when my photo was taken.  anyone know how to fix this? thanks.

**Comment by picman** [comment]
That's right. Each uploaded file is copied from it's temporary location after the upload to its final destination in a dmsf sub-folder. However, its content should be equal. Please add a better description of your problem and also samples of your files; before and after upload.

**Comment by dexterdeng** [comment]
@picman  scenario to reproduce the issue:
1. find an old photo, like taken long time ago. and make sure you can read EXIF info. like when you took that picture.
2. upload that file to dmsf
3. you'll see you can't find the date time when you took that picture any more. instead of the original time when you took that picture, you got the time when you uploaded instead. 

thanks.

**Comment by picman** [comment]
How does it behave when you upload such an old photo into **_Files_** module?

**Comment by picman** [comment]
I've just tested it using Gimp. _Exif.Image.DateTime_ metadata remains unchanged after uploading to DMS and downloading it back to PC.
![image](https://user-images.githubusercontent.com/779003/90641859-fb8fc680-e231-11ea-8042-c035b35e600f.png)

**Comment by picman** [comment]
No feedback => closing
