### ISSUE TITLE
Error: "An attachment not found by its token:" when uploading large file

### ISSUE THREAD

**Issue by donghphan** [danmunn/redmine_dmsf#1161]
Hi, I started using this plugin a few days ago and I need some help. I try to up the file upload limit from 50MB to 1GB. I can upload files 200MB with no problem, but larger files (500MB in this case) takes a long time to upload, then gives an invalid file error.

The production.log file says 

> "An attachment not found by its token:" 

with no token number.

I am using nginx version 1.19.1
What I've tried so far:
nginx.conf: 
set client_max_body_size 1000m
set client_body_buffer_size 16k
set fastcgi_read_timeout 3600s

Please tell me if more info is needed and thank you in advance for your time!

**Comment by picman** [comment]
Very probably duplicates #1150.
