### ISSUE TITLE
Folder visible via webdav but not via UI

### ISSUE THREAD

**Issue by acosonic** [danmunn/redmine_dmsf#1163]
I have created two issues and made user in a role which can only see his own or assigned to him issues.

And that works fine in web interface, user only sees issue 14062

but if I login via webdav, I can see other issues as well (from other users).

Expected behavior is that user sees files in a same way via web dav.

![image](https://user-images.githubusercontent.com/862015/89538886-66390f00-d7fb-11ea-8b6c-97236e2d7152.png)

**Comment by acosonic** [comment]
My redmine and plugin information:

> Environment:
>   Redmine version                4.1.0.stable.19444
>   Ruby version                   2.6.5-p114 (2019-10-01) [x86_64-linux]
>   Rails version                  5.2.4.1
>   Environment                    production
>   Database adapter               Mysql2
>   Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
>   Mailer delivery                smtp
> SCM:
>   Subversion                     1.9.3
>   Git                            2.7.4
>   Filesystem                     
> Redmine plugins:
>   additionals                    2.0.23
>   redmine_contacts               4.3.0
>   redmine_contacts_helpdesk      4.1.8
>   redmine_dmsf                   2.4.2
>   redmine_hidden_user_profile    0.2.0
>   redmine_lightbox2              0.5.1
>   redmine_mentions               0.1.1
>   redmine_xapian                 2.0.1
>   spectator                      0.0.2
>   vault                          0.4.1

**Comment by picman** [comment]
Understood, however DMSF uses different permission model. I'd recommend to revoke the permission **_Display system folders_** for all roles. Why should have users access to those folders?

**Comment by acosonic** [comment]
User should have access to a folder of issue, because there is Redmine permission that user can see only his own issue. Thus he should be able to see his own issue folder.

They can then map drive or open via office document via webdav, work on it, and changes can be tracked.

But its important that users don't see other user's documents.

**Comment by picman** [comment]
Fixed.
