### ISSUE TITLE
Embed video into wiki

### ISSUE THREAD

**Issue by enzote84** [danmunn/redmine_dmsf#1164]
Hi! Thanks for this amazing plugin.
I want to know if it is possible to embed a video from DMSF into a wiki page. Is there a macro for this?

Kind regards
David

**Comment by picman** [comment]
If you have an animated git for example, you can use the following macro.
```{{dmsf_image(file_id)}}```
![cat](https://user-images.githubusercontent.com/779003/90723028-3e967c00-e2bc-11ea-8064-064ed5bce125.gif)

**Comment by enzote84** [comment]
Yes, I knew that functionality, but I need to embed a 5 minute video into a wiki. I know that there is a plugin for youtube videos but I would like the video is located in dmsf.
Thanks for your response!
Kind regards

**Comment by picman** [comment]
Attach here a video sample.

**Comment by enzote84** [comment]
I can't attach here an mp4 video. But I provided a link here to one that I need to use: https://redmine.bbr.cl/redmine/dmsf_public_urls?token=d0d62f0e4cbbecbd66746bd871b48fea

Kind regards

**Comment by picman** [comment]
`{{dmsf_video(file_id)}}`
