### ISSUE TITLE
Version column in documents table can't display letters

### ISSUE THREAD

**Issue by pskillen** [danmunn/redmine_dmsf#1166]
# Bug
When creating a document revision with a letter in the version number (e.g. A.2), the version is displayed as a number in the documents table. The number displayed is actually ASCII code of the letter negated (i.e. A = -65)

**Update** The version number is also appearing as a 4 component version. It looks like major.minor is being printed in decimal format (i.e. 1.2 would become 1.0.2.0)

# Screenshot
![image](https://user-images.githubusercontent.com/1828517/91457749-9ca6fe80-e87c-11ea-8f19-edb53963bc46.png)

![image](https://user-images.githubusercontent.com/1828517/91457972-e7287b00-e87c-11ea-98f8-254b34578c10.png)

# Steps to reproduce
1. Create a DMS document with any file
2. Set the version number to be anything alpha-numeric (e.g. A.2) and save
3. Observe documents table in DMS

# Environment
* Redmine 4.1 (from official Docker image)
* DMSF 2.4.4

**Comment by pskillen** [comment]
Sorry, my Ruby is terrible or I'd offer a patch for this

**Comment by picman** [comment]
Fixed. Also sorting by version didn't work properly.

**Comment by pskillen** [comment]
Thanks!
