### ISSUE TITLE
After installing the DMSF plugin, project settings are not opened/ no project is created.

### ISSUE THREAD

**Issue by Nikita-az** [danmunn/redmine_dmsf#1169]
production.log:
![image](https://user-images.githubusercontent.com/70567642/91818754-152c0780-ec4f-11ea-89c6-72894a671975.png)
What is my problem?
Thank you .

**Comment by picman** [comment]
I see no relation to DMSF.
Redmine version?
DMSF version?
Have you run migrations?

**Comment by Nikita-az** [comment]
Redmine version                4.1.1.stable.19984
DMSF                                 2.4.4
"Have you run migrations?"  Do you mean it? RAILS_ENV=production bundle exec rake db:migrate RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf
Yes

**Comment by picman** [comment]
`description` is an attribute of tracker in Redmine 4.1:

```
mysql> desc trackers;
+-------------------+--------------+------+-----+---------+----------------+
| Field             | Type         | Null | Key | Default | Extra          |
+-------------------+--------------+------+-----+---------+----------------+
| id                | int          | NO   | PRI | NULL    | auto_increment |
| name              | varchar(30)  | NO   |     |         |                |
| description       | varchar(255) | YES  |     | NULL    |                |
| is_in_chlog       | tinyint(1)   | NO   |     | 0       |                |
| position          | int          | YES  |     | NULL    |                |
| is_in_roadmap     | tinyint(1)   | NO   |     | 1       |                |
| fields_bits       | int          | YES  |     | 0       |                |
| default_status_id | int          | YES  |     | NULL    |                |
+-------------------+--------------+------+-----+---------+----------------+
```

**Comment by Nikita-az** [comment]
Performed it again RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf:
![image](https://user-images.githubusercontent.com/70567642/91829986-938ea680-ec5b-11ea-9607-2e29443e2b9c.png)

mysql> desc trackers;
![image](https://user-images.githubusercontent.com/70567642/91830119-c5077200-ec5b-11ea-8400-520ec992d34d.png)

**Comment by Nikita-az** [comment]
![image](https://user-images.githubusercontent.com/70567642/91830868-c4bba680-ec5c-11ea-8fa0-4eefecdf80ad.png)

**Comment by Nikita-az** [comment]
Database migration was from a server where DMCF was not installed.

**Comment by picman** [comment]
1. As you can see the migration has fails with a MySQL error dmsf_folders table already exists. Fix the errors and re-run the migration task until it succeeds.
2. `No database selected`. `use your_database;` prior `desc` command.

**Comment by Nikita-az** [comment]
2.
![image](https://user-images.githubusercontent.com/70567642/91836919-e28d0980-ec64-11ea-8fc1-f5dad74effab.png)

**Comment by Nikita-az** [comment]
1. Could you help correct the errors? I'm new, I first installed redmine and dmcf

**Comment by picman** [comment]
If it's a new installation without any data in DMSF, you can simply delete all dmsf_ tables and re-run the migration.
```
mysql> drop tables like 'dmsf_%';
RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf
```
Or go, step by step:
```
mysql> drop table dmsf_folders;
RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf
```

**Comment by Nikita-az** [comment]
Great! Manually deleted all tables associated with DMCF. The repeated migration was successful! Thank you very much!
