### ISSUE TITLE
max size of upload-able file

### ISSUE THREAD

**Issue by s-tkt** [danmunn/redmine_dmsf#1170]
I remember previous DMSF plugin ( like version 2.4.1 ) has a setting of maximum size of uploading file in plugin's settings page. Now I can not look up that setting (version 2.4.4 ). However I made sure file of which size is over 100MB can be uploaded via WebDAV interface. Is limitation of upload-able file size removed?

On the other hand, max size of uploading file is limited to 5MB via Web-UI. How can I change this limitation?

**Comment by picman** [comment]
**_Settings/Files_** -> **Maxim attachment size** is used. It's not checked in WebDAV module. I will fix it.

**Comment by picman** [comment]
Fixed.
