### ISSUE TITLE
Manually locking document disables "Edit content"

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1172]
If a user manually locks a document the menu entry "Edit content" gets disabled. This was not the case in older version:

Behavior in version 2.0.0:
![grafik](https://user-images.githubusercontent.com/7224922/92687507-f5c26800-f33b-11ea-8ff7-f92ab63c492b.png)

Behavior in version 2.4.4
![grafik](https://user-images.githubusercontent.com/7224922/92687559-0e328280-f33c-11ea-9dbb-6596f7c8b6e1.png)

Expected: the same behavior as in version 2.0.0

**Comment by picman** [comment]
I consider it as logical. The document is locked for me, therefore I'm not allowed to edit it.

**Comment by mmundi72** [comment]
I disagree. Look at it this way: there are 2 users: User A und User B.
User A locks the document, because he wants to work on it. User B gets the info that User A has it locked. User B cannot work on the document (Edit content is disabled for User B).

Well, but how can User A now edit the document without downloading/uploading it? Direct editing of such a document should still be possible for User A (and only for User A).

**Comment by picman** [comment]
Fixed.

**Comment by mmundi72** [comment]
Perfect, thank you very much!
