### ISSUE TITLE
Time out occurs by accessing to deep folder

### ISSUE THREAD

**Issue by s-tkt** [danmunn/redmine_dmsf#1173]
Accessing to deep folder like ```/f1/f2/f3/f4/f5/f6/f7/f8/f9/f10```  via WebDAV takes a really much long time even if the folders are empty. The time exponentially increases more as folder become deeper.
Access time via Web-UI keeps very short though depth of folders.

**Comment by picman** [comment]
Which DMSF version do you use?

**Comment by s-tkt** [comment]
Thanks for rapid reply, and very sorry.
For some reasons, I use many versions of DMSF, but this issue occurred with DMSF version 2.4.1. 
Using version 2.4.5-devel, the response time is very short against very deep folder.
Anyway, I should decide very soon to use version 2.4.5-devel casually.
Thank you again.
