### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by alcama1** [danmunn/redmine_dmsf#1174]
after update to version 2.2.4 and Redmine 4.1 D&D is not longer possible in Browser.

**Comment by picman** [comment]
The up to date version is 2.4.4. Please use it.

**Comment by alcama1** [comment]
Sorry typo, I`m using version 2.4.4

**Comment by picman** [comment]
So please provide more detailed description of the problem including screen-shots.

**Comment by alcama1** [comment]
The description is rather simple: after the upgrade the drag&drop field is not available anymore. no other changes were made to the system.
![Redmine 4 0 with DMSF 2 4 2](https://user-images.githubusercontent.com/33027487/93362721-fe8ccf80-f84e-11ea-96c5-5ed3510a012e.PNG)
![Redmine 4 1 with DMSF 2 4 4](https://user-images.githubusercontent.com/33027487/93362726-ffbdfc80-f84e-11ea-9ce8-5cabfea7fc4a.PNG)

**Comment by picman** [comment]
Duplicates #1153.
