### ISSUE TITLE
Failed to PUT files which includes some characters via WebDAV

### ISSUE THREAD

**Issue by s-tkt** [danmunn/redmine_dmsf#1178]
With dmsf-2.4.5-devel and bitnami-redmine-4.1.1,
I tried upload a file of which name is '[].txt' via WebDAV, but it returns 502.

production.log:
```
Started PUT "/new/redmine/dmsf/webdav/dmsf-test/[].txt" for 124.84.42.104 at 202
0-09-28 20:30:29 +0900
Processing WebDAV request: /new/redmine/dmsf/webdav/dmsf-test/%5B%5D.txt (for 12
4.84.42.104 at 2020-09-28 11:30:29 UTC) [PUT]
WebDAV Error: File id is not set
File id is not set
```

I have not found other characters which occurs such an error.

**Comment by picman** [comment]
Square brackets removed from not allowed characters.
