### ISSUE TITLE
Update issue by API

### ISSUE THREAD

**Issue by tknrng** [danmunn/redmine_dmsf#1180]
When i trying update issue by API using pentaho i get this error
F, [2020-10-08T15:41:34.554953 #1] FATAL -- : ActionDispatch::Http::Parameters::ParseError (416: unexpected token at '{"id":11, "value":"2020-12-"'):
F, [2020-10-08T15:41:34.555023 #1] FATAL -- :   
F, [2020-10-08T15:41:34.555088 #1] FATAL -- : plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'
but i create normal json
when i run my integration without dmsf all work fine
it's look like dmsf is shrink my json

**Comment by picman** [comment]
Please attach the json file and command you use.

**Comment by tknrng** [comment]
Closed.
Bug found on windows core drivers. 
1 - when changing server from windows to linux and using curl (not Invoke-RestMethod) PUT working
2 - Changing version of Pentaho from 9.0+ to 8.2 - all working, because rest not using Invoke-RestMethod
