### ISSUE TITLE
Document Migration

### ISSUE THREAD

**Issue by t-lk** [danmunn/redmine_dmsf#1182]
Looking to move approx. 1600 docs from another doc repo into Redmine DMSF. Is there documentation or has someone batch loaded documents that can offer some guidance. Thank you

**Comment by picman** [comment]
1) To mount both DMSF instances as network folders via WebDAV and then copy files and folders.
2) Write a script an copy files and folders using [REST API](https://github.com/danmunn/redmine_dmsf/wiki/REST-API)

**Comment by t-lk** [comment]
Thank you for direction.  The one system is not DMSF and does not have WebDAV support but I think I make something work using the REST API path.
