### ISSUE TITLE
Suggest to show Approval option in list view instead hiding it in second layer menu being folded

### ISSUE THREAD

**Issue by linkcn** [danmunn/redmine_dmsf#1192]
If lots of files waiting for approval, user have to click "..." to unfold menu to select "Approval" button one by one document.
This is inconvenient if lots of approved and unapproved files are in the same list.

**Comment by picman** [comment]
I see no reason why to do that. Simply, use the context menu as for all other commands.

**Comment by linkcn** [comment]
The context menu 

> I see no reason why to do that. Simply, use the context menu as for all other commands.

If I have tens of files in the list mixing with approved and unapproved files, I must click each "context menu" to see if I need approve it.
If possible to put some flag in file list view, user can directly see those files need approving?

**Comment by picman** [comment]
There is a column **Workflow** indicating the status.

**Comment by mmundi72** [comment]
May I suggest to enhance this feature as filter option? Provide a "Workflow" filter which could show all relevant documents in a specific workflow step or documents waiting for action of the current user. This way a user could easily identify the relevant documents.
I think the filtering options is a very powerful tool and should be extended in DMSF (see also #1124).

**Comment by linkcn** [comment]
> May I suggest to enhance this feature as filter option? Provide a "Workflow" filter which could show all relevant documents in a specific workflow step or documents waiting for action of the current user. This way a user could easily identify the relevant documents.
> I think the filtering options is a very powerful tool and should be extended in DMSF (see also #1124).

Great idea!

**Comment by magic-k** [comment]
Unfortunately this issue is quite old. Can we at least put the Step into the list, so i can see in which stage every document currently is?
