### ISSUE TITLE
Restore files deleted by someone by time range.

### ISSUE THREAD

**Issue by Henry586** [danmunn/redmine_dmsf#1197]
Somebody delete all the project files mounted on webdav drive by mistake.
So I have to manually restore them, but since some folders was deleted and re-created with same name, it may report 'The parent folder doesn't exist' error message.

If there is a feature to restore files deleted by someone by time range, then life will be better.

dmsf version: 1.5.9, if there is already such feature, please let me know.
dmsf is very helpful for our project, hope it can be better.

**Comment by picman** [comment]
No, there is no such functionality. If a deleted folder is replaced with a new one of the same name, restore is not possible due to the same name.
