### ISSUE TITLE
500 Internal error when press the DMS Modules

### ISSUE THREAD

**Issue by hiyagou** [danmunn/redmine_dmsf#1198]
Bitnami Redmine 4.1.1-6 & redmine_dmsf 2.4.5
After Installed and xapian binding, the settings looks normal. 
![image](https://user-images.githubusercontent.com/25784765/103336915-989e1e00-4ab4-11eb-8760-e2f5f97e0038.png)
![image](https://user-images.githubusercontent.com/25784765/103336977-cb481680-4ab4-11eb-86ee-a42611140ed1.png)

But when I press the DMS tag，I got a 500 error page
![image](https://user-images.githubusercontent.com/25784765/103337990-ea947300-4ab7-11eb-9c7f-01f2516bd91c.png)
![image](https://user-images.githubusercontent.com/25784765/103338043-144d9a00-4ab8-11eb-801a-c8811b07f9d4.png)

The production.log is shown below, how can I fix this error ? Thanks

Started GET "/redmine/projects/ekm/files" for ip at 2020-12-30 07:56:02 +0000
Processing by FilesController#index as HTML
  Parameters: {"project_id"=>"ekm"}
  Current user: name (id=7)
  Rendering files/index.html.erb within layouts/base
  Rendered files/index.html.erb within layouts/base (8.7ms)
Completed 200 OK in 91ms (Views: 36.5ms | ActiveRecord: 39.8ms)
Started GET "/redmine/projects/ekm/dmsf" for 10.129.130.114 at 2020-12-30 07:59:07 +0000
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"ekm"}
  Current user: 03252 (id=7)
Completed 500 Internal Server Error in 41ms (ActiveRecord: 26.8ms)
  
Query::StatementInvalid (TinyTds::Error: Incorrect syntax near 'LIMIT'.: EXEC sp_executesql N'SELECT COUNT(*) FROM ( (SELECT [dmsf_folders].* FROM ( (SELECT [dmsf_folders].* FROM ( (SELECT [dmsf_folders].* FROM ( (SELECT DISTINCT 
          dmsf_folders.id AS id,
          dmsf_folders.project_id AS project_id,
          CAST(NULL AS decimal) AS revision_id,
          dmsf_folders.title AS title,
          NULL AS filename,
          CAST(NULL AS decimal) AS size,
          dmsf_folders.updated_at AS updated,
          CAST(NULL AS decimal) AS major_version,
          CAST(NULL AS decimal) AS minor_version,
          CAST(NULL AS decimal) AS workflow,
          CAST(NULL AS decimal) AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          ''folder'' AS type,
          dmsf_folders.deleted AS deleted,
          0 AS sort  FROM [dmsf_folders] INNER JOIN [projects] ON [projects].[id] = [dmsf_folders].[project_id] LEFT JOIN users ON dmsf_folders.user_id = users.id LEFT JOIN dmsf_folder_permissions ON dmsf_folders.id = dmsf_folder_permissions.dmsf_folder_id WHERE [dmsf_folders].[deleted] = @0 AND (projects.status <> 9 AND EXISTS (SELECT 1 AS one FROM enabled_modules em WHERE em.project_id = projects.id AND em.name=''dmsf'')) AND [dmsf_folders].[project_id] = @1 AND [dmsf_folders].[dmsf_folder_id] IS NULL AND [dmsf_folders].[deleted] = @2) UNION ALL (SELECT 
          dmsf_links.id AS id,
          COALESCE(dmsf_folders.project_id, dmsf_links.project_id) AS project_id,
          dmsf_links.target_id AS revision_id,
          dmsf_links.name AS title,
          dmsf_folders.title AS filename,
          CAST(NULL AS decimal) AS size,
          COALESCE(dmsf_folders.updated_at, dmsf_links.updated_at) AS updated,
          CAST(NULL AS decimal) AS major_version,
          CAST(NULL AS decimal) AS minor_version,
          CAST(NULL AS decimal) AS workflow,
          CAST(NULL AS decimal) AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          ''folder-link'' AS type,
          dmsf_links.deleted AS deleted,
          0 AS sort  FROM [dmsf_links] LEFT JOIN dmsf_folders ON dmsf_links.target_id = dmsf_folders.id LEFT JOIN users ON users.id = COALESCE(dmsf_folders.user_id, dmsf_links.user_id) WHERE [dmsf_links].[target_type] = @3 AND [dmsf_links].[project_id] = @4 AND [dmsf_links].[dmsf_folder_id] IS NULL AND [dmsf_links].[deleted] = @5) ) [dmsf_folders]) UNION ALL (SELECT 
          dmsf_files.id AS id,
          dmsf_files.project_id AS project_id,
          dmsf_file_revisions.id AS revision_id,
          dmsf_file_revisions.title AS title,
          dmsf_file_revisions.name AS filename,
          dmsf_file_revisions.size AS size,
          dmsf_file_revisions.updated_at AS updated,
          dmsf_file_revisions.major_version AS major_version,
	        dmsf_file_revisions.minor_version AS minor_version,
          dmsf_file_revisions.workflow AS workflow,
          dmsf_file_revisions.dmsf_workflow_id AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          ''file'' AS type,
          dmsf_files.deleted AS deleted,
          1 AS sort  FROM [dmsf_files] INNER JOIN [dmsf_file_revisions] ON [dmsf_file_revisions].[dmsf_file_id] = [dmsf_files].[id] LEFT JOIN users ON dmsf_file_revisions.user_id = users.id WHERE (dmsf_file_revisions.id = (SELECT r.id FROM dmsf_file_revisions r WHERE r.created_at = (SELECT MAX(created_at) FROM dmsf_file_revisions rr WHERE rr.dmsf_file_id = dmsf_files.id) AND r.dmsf_file_id = dmsf_files.id ORDER BY id DESC LIMIT 1)) AND [dmsf_files].[project_id] = @6 AND [dmsf_files].[dmsf_folder_id] IS NULL AND [dmsf_files].[deleted] = @7) ) [dmsf_folders]) UNION ALL (SELECT 
          dmsf_links.id AS id,
          dmsf_files.project_id AS project_id,
          dmsf_files.id AS revision_id,
          dmsf_links.name AS title,
          dmsf_file_revisions.name AS filename,
          dmsf_file_revisions.size AS size,
          dmsf_file_revisions.updated_at AS updated,
          dmsf_file_revisions.major_version AS major_version,
	        dmsf_file_revisions.minor_version AS minor_version,
          dmsf_file_revisions.workflow AS workflow,
          dmsf_file_revisions.dmsf_workflow_id AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          ''file-link'' AS type,
          dmsf_links.deleted AS deleted,
          1 AS sort  FROM [dmsf_links] JOIN dmsf_files ON dmsf_files.id = dmsf_links.target_id JOIN dmsf_file_revisions ON dmsf_file_revisions.dmsf_file_id = dmsf_files.id LEFT JOIN users ON dmsf_file_revisions.user_id = users.id WHERE (dmsf_file_revisions.id = (SELECT r.id FROM dmsf_file_revisions r WHERE r.created_at = (SELECT MAX(created_at) FROM dmsf_file_revisions rr WHERE rr.dmsf_file_id = dmsf_files.id) AND r.dmsf_file_id = dmsf_files.id ORDER BY id DESC LIMIT 1)) AND [dmsf_links].[target_type] = @8 AND [dmsf_links].[project_id] = @9 AND [dmsf_links].[dmsf_folder_id] IS NULL AND [dmsf_links].[deleted] = @10) ) [dmsf_folders]) UNION ALL (SELECT 
          dmsf_links.id AS id,
          dmsf_links.project_id AS project_id,
          CAST(NULL AS decimal) AS revision_id,
          dmsf_links.name AS title,
          dmsf_links.external_url AS filename,
          CAST(NULL AS decimal) AS size,
          dmsf_links.updated_at AS updated,
	        CAST(NULL AS decimal) AS major_version,
          CAST(NULL AS decimal) AS minor_version,
          CAST(NULL AS decimal) AS workflow,
          CAST(NULL AS decimal) AS workflow_id,
          users.firstname AS firstname,
          users.lastname AS lastname,
          users.id AS author,
          ''url-link'' AS type,
          dmsf_links.deleted AS deleted,
           1 AS sort  FROM [dmsf_links] LEFT JOIN users ON dmsf_links.user_id = users.id WHERE [dmsf_links].[target_type] = @11 AND [dmsf_links].[project_id] = @12 AND [dmsf_links].[dmsf_folder_id] IS NULL AND [dmsf_links].[deleted] = @13) ) [dmsf_folders]', N'@0 int, @1 int, @2 int, @3 nvarchar(10), @4 int, @5 int, @6 int, @7 int, @8 nvarchar(10), @9 int, @10 int, @11 nvarchar(10), @12 int, @13 int', @0 = 0, @1 = 1, @2 = 0, @3 = N'DmsfFolder', @4 = 1, @5 = 0, @6 = 1, @7 = 0, @8 = N'DmsfFile', @9 = 1, @10 = 0, @11 = N'DmsfUrl', @12 = 1, @13 = 0):
  
plugins/redmine_dmsf/app/models/dmsf_query.rb:97:in `rescue in dmsf_count'
plugins/redmine_dmsf/app/models/dmsf_query.rb:92:in `dmsf_count'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:75:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:73:in `show'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'

**Comment by picman** [comment]
Which DB do you use?

**Comment by hiyagou** [comment]
MS SQL Server
The problem is sql LIMIT and SELECT TOP 1.

**Comment by picman** [comment]
I've created a workaround for MS SQL. Could you test it, please?

**Comment by hiyagou** [comment]
I had tried #1198 MSSQLworkaround. 
It seems to be working fine. It's awesome. thanks !

**Comment by vergelli** [comment]
I'm having the same issue after updating to 2.4.5, when pressing on DMS but I'm using Postgres as my DB engine.
I've tried [this workaround](https://github.com/danmunn/redmine_dmsf/commit/f07e58abdb04f1b3eb7cf6a69221c01a6f89636d), but it doesn't seem to be working. I receive the same result.

**Comment by picman** [comment]
What's the SQL error in Postgres?

**Comment by picman** [comment]
No feedback => closing.

**Comment by quadur** [comment]
> What's the SQL error in Postgres?

I think I can provide the error: 
<pre>Completed 500 Internal Server Error in 23ms (ActiveRecord: 5.4ms)

Query::StatementInvalid (PG::SyntaxError: ERROR:  subquery has too many columns
LINE 35: ...ts" WHERE (( projects.status <> 9 OR (projects.id IN (SELECT...
                                                              ^
: SELECT COUNT(*) FROM ( (SELECT
        dmsf_folders.id AS id,
        dmsf_folders.project_id AS project_id,
        CAST(NULL AS integer) AS revision_id,
        dmsf_folders.title AS title,
        NULL AS filename,
        CAST(NULL AS integer) AS size,
        dmsf_folders.updated_at AS updated,
        CAST(NULL AS integer) AS major_version,
        CAST(NULL AS integer) AS minor_version,
        CAST(NULL AS integer) AS workflow,
        CAST(NULL AS integer) AS workflow_id,
        users.firstname AS firstname,
        users.lastname AS lastname,
        users.id AS author,
        'folder' AS type,
        dmsf_folders.deleted AS deleted,
        1 AS sort  FROM "dmsf_folders" LEFT JOIN users ON dmsf_folders.user_id = users.id WHERE (1=0)) UNION ALL (SELECT
      projects.id AS id,
      projects.id AS project_id,
      CAST(NULL AS integer) AS revision_id,
      projects.name AS title,
      projects.identifier AS filename,
      CAST(NULL AS integer) AS size,
      projects.updated_on AS updated,
      CAST(NULL AS integer) AS major_version,
      CAST(NULL AS integer) AS minor_version,
      CAST(NULL AS integer) AS workflow,
      CAST(NULL AS integer) AS workflow_id,
      '' AS firstname,
      '' AS lastname,
      CAST(NULL AS integer) AS author,
      'project' AS type,
      CAST(0 AS integer) AS deleted,
      0 AS sort  FROM "projects" WHERE (( projects.status <> 9 OR (projects.id IN (SELECT
      projects.id AS id,
      projects.id AS project_id,
      CAST(NULL AS integer) AS revision_id,
      projects.name AS title,
      projects.identifier AS filename,
      CAST(NULL AS integer) AS size,
      projects.updated_on AS updated,
      CAST(NULL AS integer) AS major_version,
      CAST(NULL AS integer) AS minor_version,
      CAST(NULL AS integer) AS workflow,
      CAST(NULL AS integer) AS workflow_id,
      '' AS firstname,
      '' AS lastname,
      CAST(NULL AS integer) AS author,
      'project' AS type,
      CAST(0 AS integer) AS deleted,
      0 AS sort , "projects"."id" FROM "projects" INNER JOIN "issues" ON "issues"."project_id" = "projects"."id" WHERE (( projects.status <> 9 AND EXISTS (SELECT 1 AS one FROM enabled_modules em WHERE em.project_id = projects.id AND em.name='issue_tracking') OR ( (issues.id IN (SELECT "issues"."id" FROM "issues" INNER JOIN "watchers" ON "watchers"."watchable_id" = "issues"."id" AND "watchers"."watchable_type" = 'Issue' WHERE "watchers"."user_id" = 16)) AND ( 1=1 )) ) ))) )) AND "projects"."parent_id" IS NULL) ) "dmsf_folders"):

plugins/redmine_dmsf/app/models/dmsf_query.rb:95:in `rescue in dmsf_count'
plugins/redmine_dmsf/app/models/dmsf_query.rb:92:in `dmsf_count'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:92:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:90:in `show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:73:in `index'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:56:in `call'</pre>

**Comment by picman** [comment]
The workaround is related to MS SQL only. There is no need to patch it due to Postgres or MySQL. I think you had to do a mistake by patching it as the SQL query from your production.log is completely wrong.

```sql
OR (projects.id IN (SELECT
      projects.id AS id,
      projects.id AS project_id,
```

Use a stable release.
