### ISSUE TITLE
Full text research doesn't work

### ISSUE THREAD

**Issue by remi912** [danmunn/redmine_dmsf#1202]
Hi,
I have been installing the Redmine dmsf plugin in a debian docker container.
Apparently, everything is ok, when I would search a document using a word inside it, I find nothing.

This is my environnment configuration :

```

> Environment:
>   Redmine version                4.1.1.stable
>   Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
>   Rails version                  5.2.4.2
>   Environment                    production
>   Database adapter               PostgreSQL
>   Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
>   Mailer delivery                smtp
> SCM:
>   Subversion                     1.10.4
>   Mercurial                      4.8.2
>   Bazaar                         2.8.0
>   Git                            2.20.1
>   Filesystem                     
> Redmine plugins:
>   redmine_dmsf                   2.4.5
>   redmine_drawio                 0.9.0
> 

```
The message when I execute the xapian_indexer script 

> ```
> 
> root@d5a6309799a7:/usr/src/redmine# ruby plugins/redmine_dmsf/extra/xapian_indexer.rb -v
> Trying to load Redmine environment <</usr/src/redmine/config/environment.rb>>...
> W, [2021-01-12T16:06:29.602641 #260]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
> W, [2021-01-12T16:06:29.810568 #260]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
> W, [2021-01-12T16:06:29.829501 #260]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
> Redmine environment [RAILS_ENV=production] correctly loaded ...
> /usr/src/redmine/dmsf_index/french does not exist, creating ...
> /usr/bin/omindex -s french --db /usr/src/redmine/dmsf_index/french /usr/src/redmine/files/dmsf --url / --depth-limit=0 -v
> [Entering directory ""]
> [Entering directory "2021/"]
> [Entering directory "2021/01/"]
> Indexing "2021/01/210112135424_1_linux_hardening.pdf" as application/pdf ... no text extracted from document body, but indexing metadata anyway
> added
> Indexing "2021/01/210112155649_2_error.txt" as text/plain ... added
> Redmine DMS documents indexed
> 
> ```

![image](https://user-images.githubusercontent.com/35763941/104342280-f2620780-54fa-11eb-9242-5f15f0d5953f.png)

Could you help me please ?

**Comment by picman** [comment]
1. Check the plugin's settings. section _Full-text search_, especially the path to the database you've created with _xapian_indexer_.
2. Check the production.log for any messages related to the searching,

**Comment by remi912** [comment]
It's works !
Thanx !
I used french database in the xapian_indexer, and english database in the section Full-text search
