### ISSUE TITLE
my account not working after install DMSF

### ISSUE THREAD

**Issue by Blazeplan21** [danmunn/redmine_dmsf#1205]
I have installed bitnami redmine 4.1.1.7  and install dmsf plugin. 
install info 

redmine : bitnami redmine 4.1.1.7
dmsf plugin : 2.4.5
OS : Windows 10 pro (Korean)

every dmsf work are doing very well.

but when my account menu click, redmine dont working.  just show internal error page.

log text is here

> Started GET "/redmine/my/account" for 127.0.0.1 at 2021-02-04 10:54:11 +0900
> Processing by MyController#account as HTML
>   Current user: blazeplan (id=31)
>   Rendering my/account.html.erb within layouts/base
>   Rendered users/_mail_notifications.html.erb (5.0ms)
>   Rendered users/_preferences.html.erb (7.7ms)
>   Rendered plugins/redmine_dmsf/app/views/hooks/redmine_dmsf/_view_my_account.html.erb (98.0ms)
>   Rendered my/account.html.erb within layouts/base (117.0ms)
> Completed 500 Internal Server Error in 237ms (ActiveRecord: 4.1ms)
>   
> ActionView::Template::Error (undefined method `dmsf_tree_view' for #<UserPreference:0x0000000011da55c8>):
>     21: %>
>     22: 
>     23: <%= labelled_fields_for :pref, @user.pref do |pref_fields| %>
>     24:   <p><%= pref_fields.check_box :dmsf_tree_view %></p>
>     25: <% end %>
>   
> lib/redmine/views/labelled_form_builder.rb:36:in `check_box'
> plugins/redmine_dmsf/app/views/hooks/redmine_dmsf/_view_my_account.html.erb:24:in `block in _42ac80544792265fda97590c5dc713c6'
> app/helpers/application_helper.rb:1365:in `labelled_fields_for'
> plugins/redmine_dmsf/app/views/hooks/redmine_dmsf/_view_my_account.html.erb:23:in `_42ac80544792265fda97590c5dc713c6'
> plugins/redmine_dmsf/lib/redmine_dmsf/hooks/views/my_account_view_hooks.rb:31:in `view_my_account_preferences'
> lib/redmine/hook.rb:63:in `block (2 levels) in call_hook'
> lib/redmine/hook.rb:63:in `each'
> lib/redmine/hook.rb:63:in `block in call_hook'
> lib/redmine/hook.rb:60:in `tap'
> lib/redmine/hook.rb:60:in `call_hook'
> lib/redmine/hook.rb:98:in `call_hook'
> app/views/my/account.html.erb:50:in `block in _2cb2aed04ca3c037eb39598b70debfb3'
> app/helpers/application_helper.rb:1358:in `labelled_form_for'
> app/views/my/account.html.erb:14:in `_2cb2aed04ca3c037eb39598b70debfb3'
> lib/redmine/sudo_mode.rb:65:in `sudo_mode'
> plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'

plz help this issue.

**Comment by picman** [comment]
If you check the source code of [v.2.4.5](https://github.com/danmunn/redmine_dmsf/tree/v2.4.5/lib/redmine_dmsf/hooks) There is no such file _plugins/redmine_dmsf/app/views/hooks/redmine_dmsf/_view_my_account.html.erb_. It seems that you have copied the new version over an old version. I'd recommend deleting _redmine_dmsf_ sub-folder and clone it again from GitHub:
```
cd plugins
git clone https://github.com/danmunn/redmine_dmsf.git
```

**Comment by Blazeplan21** [comment]
It solved with your comment.

I have installed old version in backup drive and update 2.4.5.
So redmine have error. 

Delete DSMF all file and reinstall 2.4.5. 
Redmine is working well. 

Thank you very much.
