### ISSUE TITLE
Java program to move 140 000 files from another server into Redmine DMSF files management system

### ISSUE THREAD

**Issue by remi912** [danmunn/redmine_dmsf#1208]
Hi, i'm trying to use a script to move a large amount of document (142 000) from an external source to our new redmine server wich use DMSF for document management.

To do that, I have created a Java program to move correctly file into DMSF.
I discover that, file are indexing in 3 tables.

> - dmsf_folders
> - dmsf_files
> - dmsf_file_revisions

I also viewed that file are split in the dmsf folder into year directories and month directories.
Files are also renamed including date, file id, and original name. This new name is writed in the  dmsf_file_revisions table.
After do that, DMSF system display our documents but can't open it.
It produce 404 error.

Could you determine what i have missed to correctly index my files ?
Or could you explain where I can find the ruby script to add new documents ? (I dont know how ruby works but it could help me)

**Comment by picman** [comment]
The problem might be in that that a file location must correspond with created_on column in the database. You can confirm that by looking into production.log file.
At any rate I think that copying new files to the disk and creating DB records is bad approach. I'd personally do that task using either REST API or WebDAV.
1) REST API
There is wiki page https://github.com/danmunn/redmine_dmsf/wiki/REST-API and also some examples in scripts in plugins/redmine_dmsf/extra/api.
2) WebDAV
Mount DMSF as a network disk and copy files and folders there.

**Comment by remi912** [comment]
Thanx you very much for your quick answer.
I decided to do it manualy, because we need to keep the lastModified time.
With REST API, could I keep this date ?
I will know explore all options you suggest me.

By the way, I didn't find the production log file. I did a "locate production.log" but I found nothing (I'm using docker container). Could you tell me where I can find it ?

**Comment by picman** [comment]
1. Column Date in GUI is taken from dmsf_file_revision.updated_on. There will be the date of creating the revision. It will for sure differ from lastModified of the file on the disk. But you can update the column in the database later from a script.
2. The standard log is log/production.log. Look into log sub-folder.

**Comment by remi912** [comment]
I'm very surprise, because, this directory is empty in my container.
And i'm not able to find any log file in the container using command : `updatedb && locate .log | grep "redmine" `. I will check for that !
Thanx a lot for your answers.
