### ISSUE TITLE
WebDav doesn't show all projects

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1210]
We have the following structure in Redmine (projects and sub projects):

- Department 1 (dmsf not enabled)
-- Projects (dmsf not enabeld)
--- Project 1 (dmsf enabled)
--- Project 2 (dmsf enabled)

If a user only has access to Project 1 and Project 2 WebDav doesn't show these 2 projects.
If the user has access to the whole structure (access is also granted to Department 1 and Projects) then the structure is also visible in WebDav.

A user  should also have WebDav-Access to "sub projects" if that user is only granted access to sub projects.

**Comment by mmundi72** [comment]
DMSF: 2.4.5
Redmine: 4.1.1

**Comment by picman** [comment]
The sub-project should be available on the following URLs:
/dmsf/webdav/Project 1
/dmsf/webdav/Project 2
Here you see nothing as you are not allowed to see it
/dmsf/webdav/Department 1

**Comment by mmundi72** [comment]
You are right. If a user understands the technical structure and how to handle it, then a user can access the documents via WebDav. But that is exactly the problem: this is only ok for power users...

We have mounted DMSF as a drive in Windows and I get the following result in Windows Explorer:

![grafik](https://user-images.githubusercontent.com/7224922/108357065-3f698580-71ed-11eb-87c9-0932e6b38b4f.png)


The three projects on the left are all top level projects. But all other projects from my department are not visible. Yes, by manually  adding the project identifier in the adresse bar I can access the documents. But a "normal" user does not understand this.

Any idea of how such "deep projects" could made available on the WebDav root? It's a matter of usability...

**Comment by picman** [comment]
Yes, that was the original solution, a flat structure with all dmsf-enabled projects independent on their position in project tree. At the moment the structure is as a tree and if a project is not visible for the given user, its sub=projects are hidden.
I think that the right solution is to enable parent projects. It sounds me strange to be able to enter a sub-project of banned parent project.

**Comment by mmundi72** [comment]
OK, thanks for the explanation. The banned parent projects are there for organizational purposes only. That means a specific user for adepartment is allowed to create new projects within its own department. That way we have a good view which projects belong to which departments. The department projects are mainly empty and we actually don't want to show that structure to a normal user. But it seems we have to live with that new approach.
