### ISSUE TITLE
When accessing any file in DMS it shows 404 the file is not accessible

### ISSUE THREAD

**Issue by ar-sumesh** [danmunn/redmine_dmsf#1212]
i encounter this problem when i moved dmsf files and postgresql data folder from official redmine docker conatainer to new sameersbn redmine docker container , as i wanted that redmine should start up without the requirement of internet connection for downloading the plugins dependencies every time we start and stop the redmine container that why i done this switch.

**Comment by picman** [comment]
Check the log/production.log file. Very probably the path set in plugin's settings doesn't correspond to physical location of moved files.

**Comment by ar-sumesh** [comment]
i am attaching the logs from production.log and screenshot what i can see when i clicked file 

> Started GET "/dmsf/files/3/view" for 192.168.208.1 at 2021-02-22 18:11:02 +0530
Processing by DmsfFilesController#view as HTML
  Parameters: {"id"=>"3"}
  Current user: admin (id=1)
Sent file /home/redmine/redmine/files/dmsf/2020/06/file.pptx (0.6ms)
Cannot read file /home/redmine/redmine/files/dmsf/2020/06/file.pptx
  Rendering common/error.html.erb within layouts/base
  Rendered common/error.html.erb within layouts/base (0.7ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (3.5ms)
  Rendered plugins/redmine_wktime/app/views/wkbase/_base_header.html.erb (0.5ms)
  Rendered plugins/redmineup_tags/app/views/tags/_additional_assets.html.erb (0.2ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_sidebar.html.erb (0.0ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_recent_projects.html.erb (1.9ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_attendance_widget.html.erb (0.9ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (1.9ms)
  Rendered plugins/redmineup_tags/app/views/tags/_select2_transformation_rules.html.erb (0.3ms)
  Rendered plugins/redmine_people/app/views/common/_people_select2_data.html.erb (0.2ms)
  Rendered plugins/redmine_people/app/views/common/_layout_bottom.html.erb (0.3ms)
Completed 404 Not Found in 203ms (Views: 103.3ms | ActiveRecord: 60.5ms)
Started GET "/issue_badge" for 192.168.208.1 at 2021-02-22 18:11:02 +0530
Processing by IssueBadgeController#index as */*
  Current user: admin (id=1)
Completed 200 OK in 40ms (Views: 0.4ms | ActiveRecord: 13.5ms)

![404-issue](https://user-images.githubusercontent.com/59471926/108834025-a2935780-75f3-11eb-9700-7f6ac90abe47.png)

**Comment by picman** [comment]
```Cannot read file /home/redmine/redmine/files/dmsf/2020/06/file.pptx```

=> Try to find why the file is not where is expected.

**Comment by ar-sumesh** [comment]
The requested file is already present in that location , i think that why it is able to list  that file inside the DMS plugin.

Is this the problem because of  permission defined on the directory??
right now i am the owner and group of that directory

**Comment by picman** [comment]
The files must be accessible by the user under which is run the web server. E.g. if the web is run under the user www-data, the files must be read/write for www-data.

**Comment by ar-sumesh** [comment]
Directory in host system `./redmine` is  mounted to `data` directory inside redmine docker container , for example in my case 

> ./redmine:/home/redmine/data

 i checked permission of `data` directory from inside docker container it is `redmine:redmine` . i think there is no problem with respect to permission here as i can see those files in web pages .

**Comment by picman** [comment]
What you see in the web interface is take from the database not from the filesystem. The filesystem comes into play when you want to download a file. It's 100% a permission problem.
```Cannot read file /home/redmine/redmine/files/dmsf/2020/06/file.pptx```
Tre from CLI e.g.: ```sudo -u redmine cat /home/redmine/redmine/files/dmsf/2020/06/file.pptx```

**Comment by ar-sumesh** [comment]
i tried the command like `docker exec -it <container name> sudo -u redmine cat /home/redmine/data/files/dmsf/2020/06/file.pptx`.

The above command is  able to open the file

**Comment by ar-sumesh** [comment]
Thanks , that issue is now solved , i given the `/home/redmine/data/files/dmsf` path in dmsf plugin settings page.

now i am able to download files
