### ISSUE TITLE
DMS Documents > New file does not respect theme styles properly

### ISSUE THREAD

**Issue by milanbx** [danmunn/redmine_dmsf#1215]
Used theme: Bootsmine - https://bestredminetheme.com/boostmine/
If you go to create ne file in DMS, the "Upload" submit button is not styled properly according tu theme used - see snapshot:
![image](https://user-images.githubusercontent.com/37396169/109283080-a1923e00-781e-11eb-85a1-718afc0db10a.png)
The edge of `class="box tabular"` crosses the button.
This behaviour is not experienced with any other dialog, no mater if Redmine core or DMSF (e.g. New issue, New DMS Folder etc.). Those all work fine and look good.
I have not succeeded in solving this within CSS. It may be caused by the order of divs generated in the appropriate view.
The difference is, that for New document the `<div class="form-actions">` is placed inside of the  `<div class="box tabular">`.
In other dialogs, the `<div class="form-actions">` is placed outside of (after) the  `<div class="box tabular">`.
Hope it helps.
Thanks.

**Comment by picman** [comment]
Fixed.
