### ISSUE TITLE
DMS Documents list > document revision: possibly wrong usage of style in action icons

### ISSUE THREAD

**Issue by milanbx** [danmunn/redmine_dmsf#1216]
Used theme: Bootsmine - https://bestredminetheme.com/boostmine/
Go to `/dmsf/files` and use context menu icons (3 dots) on the right side of selected document (item row), select Edit. It brings you to list of revisions, in my case `/dmsf/files/2`.  And each revision has also context menu menu (3 dots). However, it is bordered, which does not look good - see snapshot:
![image](https://user-images.githubusercontent.com/37396169/109286160-3185b700-7822-11eb-9b81-cd77d187ba99.png)
The red arrow point to style classes, that may cause this difference.
I have tried to solve this within CSS, but without success.
Thanks.

**Comment by picman** [comment]
The theme is not for free, co I can't test it and with the standard theme it doesn't happen.
Try browser developer tools <F12> and find the property responsible for the frame. If you find it, you can simply override it in a .css file.

![image](https://user-images.githubusercontent.com/779003/109301727-9ea44700-7838-11eb-8128-c0a74e0d6340.png)

**Comment by milanbx** [comment]
Well, I have already tried to change it in the CSS, but this gives no solution, as the style class is used at other places too. The problem is in the span tag, which should use another class. I will try to change it in the dev inspector and let you know, if I find a proper solution.

**Comment by picman** [comment]
No feedback => closing.
