### ISSUE TITLE
Question: where is the action multi_upload defined

### ISSUE THREAD

**Issue by keineahnung2345** [danmunn/redmine_dmsf#1218]
Sorry if this is a newbie question. I am trying to trace the codes, and I have problem finding the definition of the action `multi_upload`.

In [config/routes.rb](https://github.com/danmunn/redmine_dmsf/blob/master/config/routes.rb#L73), it assumes the controller `dmsf_upload` has an action `multi_upload`, but when I look into [app/controllers/dmsf_upload_controller.rb](https://github.com/danmunn/redmine_dmsf/blob/master/app/controllers/dmsf_upload_controller.rb), I can only find action with name `upload` but not `multi_upload`, so how does the code work?

Thanks in advance.

**Comment by picman** [comment]
It's not mandatory to declare a controller method. In our case it's the same as there would be this in the controller:
```ruby
  def multi_upload
  end
```
So the process goes directly to view app/views/dmsf_upload/multi_upload.html.erb

**Comment by keineahnung2345** [comment]
I've never thought of that, thank you!
