### ISSUE TITLE
WebDav and [Brackets]

### ISSUE THREAD

**Issue by RobertDiemer** [danmunn/redmine_dmsf#1219]
First of all, thank you very much for your great job you always do!
I have a question: Wherer/in which file do I have to change the brackets, which are shown for folders in WebDav?
Are there any pitfalls, which may occure, when I change the brackets?

Background is, that Excel makes problems, when using these paths... :-(

Thanks in advance!
Robert

**Comment by picman** [comment]
That's no so easy. Maybe it would be easier to fix the Excel issue. Could you describe your case in details(path, Excel version, reported error, production.log,...).

**Comment by RobertDiemer** [comment]
It seems to be an Excel issue, which is widely known and there seems to be no solution yet.

(look at https://excel.uservoice.com/forums/304921-excel-for-windows-desktop-application/suggestions/34817812-allow-brackets-in-filename-or-path)

Sorry for the circumstances!
