### ISSUE TITLE
How to set dmsf mail notification

### ISSUE THREAD

**Issue by letitbe13** [danmunn/redmine_dmsf#1222]
Hi! I would like to set user dmsf notification preference automaticaly for users withcertain project roles. I use Custom_workflow_plugin script (Project before save)
I tried like that:
```
my_project.members.each do |m|
     m.member_roles.each do |role|
       if [3,8].include?(role.role_id)
         m.dmsf_mail_notification = true # <-------???
       end
    end
end
```
but it doesn't work (without any errors in log) I tried to examine dmsf models and controllers... But didn't find the clue. I miss something simple, but need help!

![image](https://user-images.githubusercontent.com/49904609/109959313-5aadb800-7cf8-11eb-9da4-72e27de437f7.png)

**Comment by picman** [comment]
```m.save``` is missing?
