### ISSUE TITLE
Question: where is the definition of the function find_project called in dmsf_context_menus_controller.rb?

### ISSUE THREAD

**Issue by keineahnung2345** [danmunn/redmine_dmsf#1224]
There is no definition of the function `find_project` in [dmsf_context_menus_controller.rb](https://github.com/danmunn/redmine_dmsf/blob/master/app/controllers/dmsf_context_menus_controller.rb), and `find_project`  doesn't look like [the function given by redmine](https://www.rubydoc.info/github/edavis10/redmine/ApplicationController:find_project) because it doesn't take any parameters, also, `DmsfContextMenusController ` just inherits from `ApplicationController`, which is empty, so it doesn't own the function itself.

I can find the definition of `find_project` in dmsf_workflows_controller.rb and [dmsf_folder_permissions_controller.rb](https://github.com/danmunn/redmine_dmsf/blob/master/app/controllers/dmsf_folder_permissions_controller.rb#L64), but in dmsf_workflows_controller.rb, `find_project` is declared as private, so I guess dmsf_context_menus_controller.rb calls `find_project` from dmsf_folder_permissions_controller.rb.

Is it correct? If it is correct, how could that happen without inheritance or `require`?
Thanks in advance.

**Comment by picman** [comment]
If you check _ApplicationController in Redmine, you can see _find_project_ method which is called from _DmsfContextMenuController_. No parameter is needed here to call the method as it has got an implicit parameter.

```ruby
# Find project of id params[:id]
  def find_project(project_id=params[:id])
    @project = Project.find(project_id)
  rescue ActiveRecord::RecordNotFound
    render_404
  end
```

**Comment by keineahnung2345** [comment]
That makes sense. So many thanks!!
