### ISSUE TITLE
How to set search function?

### ISSUE THREAD

**Issue by smiledimple** [danmunn/redmine_dmsf#1225]
Hi,

How can I edit search option?
As you know, we can use the columns as a search tab.
The default is only one column on the Search tab. How can I add or modify more of these search tabs?

I want to add 'Product', 'Module' Columns as a search tab.
Now it has only 'Product'
![search](https://user-images.githubusercontent.com/80310825/110432316-4865bc80-80f2-11eb-9915-0838f56dc62a.JPG)

Could you give me a guide?
I need your help. Thanks.

[Version below]

redmine_dmsf                   1.6.2

Environment:
  Redmine version                3.4.10.stable
  Ruby version                   2.2.0-p0 (2014-12-25) [x86_64-linux]
  Rails version                  4.2.11.1

**Comment by picman** [comment]
Only the first DMSF custom field is available as a filter. In order to use all custom fields, you have to upgrade DMSF plugin to v2.4.5.

**Comment by smiledimple** [comment]
Thank you for your help,
Is it possible to use v2.4.5 on my redmine version?

**Comment by picman** [comment]
No, Redmine 4.1 is required.

**Comment by smiledimple** [comment]
Thanks,
One more question,
How can I change columns sequence?

For example
title , size, modified ....(now)
to size, title, modified ... (after)

**Comment by smiledimple** [comment]
Thanks,
