### ISSUE TITLE
Check if a document contains a signature

### ISSUE THREAD

**Issue by wolfc01** [danmunn/redmine_dmsf#1227]
Hi,

is there a possebility to check if a document contains a signature? I would onky like to have a succesful approve if document is electronically signed.

br
Carl

**Comment by picman** [comment]
Does exist a specification how to check that a document has got an electronic signature? Which types of documents? PDF, ODT,...?

**Comment by wolfc01** [comment]
Hi Karel,

there are a number of ways to accomplish this..

Therefore some kind of pre commit / pre upload hook (server side) would be
nice. Having such a hook capability enables one to add server side scripts
there.

Such a script  then can e.g. check the uploaded doc for a signature before
accepting it in dms.

e.g:
IF version == 1.0 AND aboutToRelease == true
THEN
   result=checksignature;
   return result.
ELSE
   return True

is this a nice powerful feature?

br
carl.






Op wo 24 mrt. 2021 10:49 schreef Karel Picman ***@***.***>:

**Comment by picman** [comment]
I've added such a hook, which is called before any approval is committed. The implementation of the hook could be as follows.
```ruby
class DmsfWorkflowControllerHooks < Redmine::Hook::Listener

    def dmsf_workflow_controller_before_approval(context={})
      revision = context[:revision]
      step_action = context[:step_action]
      if 1==1  # Here is the result of the signature's check
        context[:controller].flash[:error] = 'Doc not signed'
        false
      else
        true
      end
    end
end
```
