### ISSUE TITLE
letter version deffect

### ISSUE THREAD

**Issue by Mdiaz-PMO** [danmunn/redmine_dmsf#1228]
Hi! i would wanna know if its possible to fix the following feature, when I upload a file, select the version in "letters" for my doc and save it, i got a mistake in it, because then in the file list it appears in negative numbers. When i click into the file id to see its info it seams to have the correct version there. I attached a image for better understanding.
thanks!

Plugin version: 2.4.4
Redmine version:4.0.3.stable

Ruby version:2.5.5-p157 (2019-03-15) [x86_64-linux]
Rails version: 5.2.2.1

![dms version feature -  issue](https://user-images.githubusercontent.com/70598326/112199659-2473a200-8bed-11eb-94b0-5a34afca1e00.jpg)

**Comment by picman** [comment]
Duplicates #1166.
