### ISSUE TITLE
Error when sorting by a custom field

### ISSUE THREAD

**Issue by koledas** [danmunn/redmine_dmsf#1229]
Hello!
I am getting an error when sorting by a custom field.

It seems to me that one of the reasons is here:
https://github.com/danmunn/redmine_dmsf/blob/79ba86d682b033fa2d4850b0a793870fce607f99/app/models/dmsf_query.rb#L161

This might fix the problem:
`order_option[1].gsub!("COALESCE(cf_#{id}.value, '')", "cf_#{id}")`

But at the same time, any filter must be specified, otherwise the column cf_#{id} is absent in the SQL-query.
Therefore, you probably need to remove all conditions:
`if statement.present?`

**Comment by picman** [comment]
Thank you for reporting the bug. Fixed as suggested.
