### ISSUE TITLE
Redmine 4.2.0 support

### ISSUE THREAD

**Issue by liaham** [danmunn/redmine_dmsf#1230]
Hi Karel,

Redmine 4.2.0 is released. 

However, it is not compatible with your devel-2.4.6 branch due to the double listed gem rubyzip which is introduced in Redmine 4.2.0 for the first time.

I couldn't find a way to conditionally load it from your Gemfile. Therefore, I assume it must be removed or added manually depending on what you like to support.

I think Redmine 4.2.0 will be popular with the community due to its 2FA feature.

What do you think? Do you have another idea?

Best Regards,
Liane

**Comment by picman** [comment]
I see no other way than to remove the gem from the Gemfile and due to a missing gem in lower Redmine versions to add a dependency on Redmine 4.2. It means that DMSF 2.4.6 will require Redmine 4.2.
