### ISSUE TITLE
Export as csv internal error

### ISSUE THREAD

**Issue by Mdiaz-PMO** [danmunn/redmine_dmsf#1234]
**Bug:**
When trying to export a list from DMS in csv , I get an internal error.

**Screenshot:**

![export-csv-internalerror](https://user-images.githubusercontent.com/70598326/114191051-5fcadc00-9922-11eb-9007-5721b0800c0b.jpg)

**Environment:**
Plugin version: 2.4.4
Redmine version:4.0.3.stable
Ruby version:2.5.5-p157 (2019-03-15) [x86_64-linux]
Rails version: 5.2.2.1

thanks!

**Comment by picman** [comment]
Duplicates #1175.
