### ISSUE TITLE
DMS interaction with Python-Redmine library (Consult)

### ISSUE THREAD

**Issue by vergelli** [danmunn/redmine_dmsf#1235]
Hello, I'd like to ask if there is any documentation around [Python-Redmine](https://python-redmine.com/) library interacting with DMS.
I m looking for taking control of the plugin using this library in particular. Do you think it may be possible?

**Comment by picman** [comment]
No, there is no such documentation. In general it should work as it is mentioned there that it supports external Redmine plugin API.
