### ISSUE TITLE
create directories and symbolic links on the fly towards files (feature request)

### ISSUE THREAD

**Issue by wolfc01** [danmunn/redmine_dmsf#1236]
Hello,

the following feature would be helpful:

dmsf should maintain a separate directory filled with directories equal to the directories created in a project. From those directories create then symbolic links to the actual files in the File storage directory. 

This way this directory could be readonly exposed via smb/windows file share. Then windows users can use a normal browser to find and access the latest files perfectly in the directory structure.

Best regards
Carl.

**Comment by picman** [comment]
Try WebDAV. I think, that's exactly what you're looking for. You can try read only access via browser https://yourdomain/dmsf/webdav or mount it as a network drive. You can access all projects via /dmsf/webdav or a particular project via /dmsf/webdav/myproject-identifier. Don't forget to enable WebDAV in plugin's settings. To share physical files from the disk makes no sense as they are renamed and also all revisions are there. Therefore for a common user is impossible to find the right file.

**Comment by wolfc01** [comment]
Hi,

I tried webdav but didn't manage to get it working. Windows keeps saying something is wrong. I also saw a change into the coming version 2.4.6 regarding webdav?

Br
Carl.

**Comment by picman** [comment]
It works in v2.4.5 too.
1. Enable WebDAV in plugin's settings.
2. Open https://yourdomain/dmsf/webdav in your browser.
3. Check _log/production.log_ for any errors.
