### ISSUE TITLE
Support question on approval workflows

### ISSUE THREAD

**Issue by wolfc01** [danmunn/redmine_dmsf#1237]
Hi 

I have the following questions:
- is the reviewer / approver still able to edit the document in order to put review comments in it even when the approval is under way?
- is it possible to abort the workflow on a document in case somebody started an approval workflow accidentally? 
- is it possible to abort a worflow on a document in the case somebody deleted the workflow definition? Now i can delete a workflow definition even when that workflow definition is active or historically used on a document.

Br
Carl

**Comment by picman** [comment]
1. No, every update to the document means a new revision that also resets the assigned workflow.
2. and 3. You have to create a new revision of the document. (It's not necessary to upload the document again, just to edit the document and add a new revision without any changes.)
