### ISSUE TITLE
ubuntu 20.04 dependencies install problem

### ISSUE THREAD

**Issue by acosonic** [danmunn/redmine_dmsf#1238]
Hi, on ubuntu 20.04 it says no xpdf while trying to apt-get install...

The workaround I used is from this stackoverflow answer

[https://askubuntu.com/a/1245582/513874](https://askubuntu.com/a/1245582/513874)

I guess that

apt-get install xapian-omega ruby-xapian libxapian-dev xpdf poppler-utils antiword  unzip catdoc libwpd-tools \
libwps-tools gzip unrtf catdvi djview djview3 uuid uuid-dev xz-utils libemail-outlook-message-perl

should be updated or something else proposed for ubuntu 20.04

**Comment by picman** [comment]
I think that _xpdf_ is not needed at all as _poppler-utils_ package contains the required command _pdftotext_. So I've simply remove it.
