### ISSUE TITLE
file size Question 

### ISSUE THREAD

**Issue by Mdiaz-PMO** [danmunn/redmine_dmsf#1240]
Hi, is it possible to increase the size of the file that I will upload to dms? current limit 5MB, I have seen the plugin settings but the option is not available there.

Thanks!

**Comment by picman** [comment]
The limit is taken from Redmine's _**Settings**_ -> **_Files_** -> **Maximum attachment size**.

**Comment by Mdiaz-PMO** [comment]
thak you very much!
