### ISSUE TITLE
Get File by API with Custom Fields

### ISSUE THREAD

**Issue by vergelli** [danmunn/redmine_dmsf#1241]
Hello, I'm using Python Request to work with the API, I'm doing good till now but I'm having some problems with getting a file.
here is my request:
```
response = requests.get("https:URL/projects/49/dmsf/files/105.json")
response
```
where 49 is the id of the project, and 105 is the id of the file I intent to get information of.
Sadly it returns a `<Response [404]>`
I'm seeking a .json with the file attributes, so I can see the custom fields it has. I don't know if this is the proper way to do it
__________________________________________________________________________________________________________________________________
**UPDATE**: I was introducing it wrong, the request was `https://URL/dmsf/files/105.json` and not `https://URL/projects/49/dmsf/files/105.json`, as I was introducing incorrectly. Seems the files are not project_dependent.

Anyway, it doesn't show up anything related to custom fields, which is what I want to get information about.
Do you know how can I list all the custom fields of a file?

**Comment by picman** [comment]
This was completely missing. Added. The change is quite small, so I think you can easily update your installed version  according to the commit related to this issue.

**Comment by vergelli** [comment]
That's good, I will change it myself. Anyway, how a request would look like now? Will it be shown with the rest of the info on `/dmsf/files/id_file.json`?

**Comment by picman** [comment]
The request format is the same. The response is extended by custom fields.

**Comment by vergelli** [comment]
> The request format is the same. The response is extended by custom fields.

Checked and it worked, thanks!
