### ISSUE TITLE
Missing drag&drop area on Remdine 4.1?

### ISSUE THREAD

**Issue by karagounis78** [danmunn/redmine_dmsf#1244]
Hi to everyone,
I didn't find any issue related to this problem in the forum, so I open a new one hoping you can help my answering to a question: Iinstalled the DMSF plugin (2.4.5 release) after upgrading my instance to Redmine 4.1.

Comparing to previous Redmine 3.4 I see new functionalities and different UI. 
But I cannot see any Upload area for Drag&Drop files to be uploaded. See pictures below: the first is the new Redmine 4.1, the second is the old DMSF.
I have tested on different browsers and none shows the drag&drop. Do I miss something? 
Could you help me and  suggest how to resolve?

![DMSF 2 4 5 on redmine4 1](https://user-images.githubusercontent.com/29229097/116068307-63809180-a68a-11eb-9b5f-2e806e598031.png)
![DMSF on Redmine 3 4](https://user-images.githubusercontent.com/29229097/116068310-64192800-a68a-11eb-899c-3e84d0a8974e.png)

Thanks
Fabio

**Comment by picman** [comment]
There is no upload area in the new version. You have to click on New file button in the top right menu.

**Comment by karagounis78** [comment]
Thanks you for quick answer. It was a good feature, appreciated by my users.
I supposed it was a problem in my Redmine because of DMSF_user documentation: the guide still mentions the Upload area.
So Drag&Drop is no more possible, is it?

**Comment by picman** [comment]
New file form provides drag&drop feature. The user's manual is not up to date.

**Comment by karagounis78** [comment]
Ok. I have found the right place where to drop the files. Thanks.
HEre the explanation I will share with my users. Maybe can be useful also  for other Redmine users and a new revision of the guide.

![drop area](https://user-images.githubusercontent.com/29229097/116077456-cd526880-a695-11eb-9c8a-69d8d6eca00c.png)

**Comment by picman** [comment]
thx
