### ISSUE TITLE
Update custom fields of a file with REST API

### ISSUE THREAD

**Issue by vergelli** [danmunn/redmine_dmsf#1245]
I was going to make this question in the last post but I rather make a new one. 

Have you have contemplated a syntaxis for updating fields of a file? 
I want to update the custom fields of a file with the rest API, without uploading the file again. I don't want to touch anything else, just wonder if there is a particular syntax for it.  

I imagine it can be similar [to this](https://www.redmine.org/projects/redmine/wiki/Rest_Issues), making a PUT request with a body but I have tried many ways and I received 400 code. 

How would you do it?

**Comment by picman** [comment]
See [REST API wiki](https://github.com/danmunn/redmine_dmsf/wiki/REST-API). At the moment you have to upload an already existing file and then call commit. If the file name is the same, just new revision of the document will be created. To change a Document you have to always create a new revision.

**Comment by picman** [comment]
Definitely it would make sense to allow to create a new revision of a document without uploading the file. Maybe we should create a feature request from your question.

**Comment by vergelli** [comment]
I was about to code methods based on what you said first, on making a new revision of each file, but if you say it can be a new feature I'd definitely wait. Actually, it would be very good since I am already seeing complicated stuff to do otherwise.  =.="

Maybe it can be like the [issue](https://www.redmine.org/projects/redmine/wiki/Rest_Issues) update request model?, as it's described on the wiki, it looks simple idk.

**Comment by vergelli** [comment]
@picman One question, is there any chance I can get the code before the 2.4.7 release?

**Comment by picman** [comment]
Probably yes, related commit will be reverenced here, so you will be be able to copy the changes into your code. Or, you can directly switch to devel-2.4.7 branch. However you can't expect a solution soon as I have other tasks with a higher priority.

**Comment by vergelli** [comment]
@picman
 Got it. I'll be attentive to this thread. 

Thank you

**Comment by picman** [comment]
So, there is a new REST API call [Create revision](https://github.com/danmunn/redmine_dmsf/wiki/REST-API#7-create-a-revision).
