### ISSUE TITLE
Custom fields of documents are not shown and not editable - What do I wrong?

### ISSUE THREAD

**Issue by CubaLibre84** [danmunn/redmine_dmsf#1246]
I have several issues with custom fields. Some of them might be my mistake, as I'm new to the plugin.

**Prerequisites/Tests:**
1. As an admin, I created a custom field in the category "DMS".
2. In the plugin settings, I activated, that this field should be displayed as a column.
3. When adding a new document or a new revision, the field is displayed and I can enter a value.
4. The filter for this custom field works within the DMS view table.

**Issues:**
1. ~The field is not shown in the DMS view table (besides the title, size, date, ...)~  Below "Filter" there is another section called "Options". Here we first need to add the column to the visible ones, using the button [->].
2. In the right menu of a document (...) -> [edit],  I can only **see** the revision with the custom field but I can not change the custom value
3. I can't find the document by using the global search by searching for the custom value ([DMS documents] is ticked)
4. ~The custom fields are not part of the response, if I do an API GET request (e.g. http://IP/projects/ID/dmsf.json?folder_id=2)~ Fixed by #1241 in DMSF Version 2.4.6
5. I can not change the title nor the version of the document after the creation

Many thanks in advance for any help!

**Comment by picman** [comment]
You have to create a new revision of the document to be able to change its properties. Click on the plus icon in the edit form.

**Comment by CubaLibre84** [comment]
Thank you for the feedback! Changing (correcting) custom field values without uploading a new version is very important for us! What about all the other issues?

**Comment by picman** [comment]
1) You can set default columns in plugin's settings. Additionally you can select temporary columns with Options.
2) You have to create a new revision to modify document's custom fields.
3) Check whether the custom field is set as searchable.
4) DMSF 2.4.6
5) You have to create a new revision to change the title or version.

**Comment by CubaLibre84** [comment]
Thanks picman again for the feedback. I already edited the description above.
Issue 3 won't fix (only for version fields) due to a RedMine limitation:
https://www.redmine.org/issues/35138
I will cose the ticket now.
