### ISSUE TITLE
Make DMS document available as Type of a custom field

### ISSUE THREAD

**Issue by jankokert** [danmunn/redmine_dmsf#1248]
It would be great if in the list of types of custom fields (text, integer, link, list, ...) another type could be added, which is a link to a DMS document.

**Example:**
Consider a case where you have a sales offer as PDF for every version of a project. You could configure you projects in a way that for all versions there is this custom field "offer" which has the type DMS. When creating a new version, the pdf document could be chosen from a drop-down menu, containing all documents of the selected project and all its parent projects.
To show also the list of all document in parent projects is important for use cases such as #916.

**Comment by picman** [comment]
There is a new type of custom field. **DMS Document revision** is based on the last document revision or can be se manually if _Fast link_ option is set on.
