### ISSUE TITLE
How to get the path for a document with known ID

### ISSUE THREAD

**Issue by RobertDiemer** [danmunn/redmine_dmsf#1250]
Dear all, many thanks for this great plugin!

I have the problem to find the path in DMSF, when I only know the document's ID.
e.g. I have wiki pages using dmsf-macros like {{dmsftn(1000)}}. How can I get the path, where the document with ID 1000 is stored?
I want to access this file by WebDav, so I need the path....

Thanks for your help in advance!

Best wishes,
Robert

**Comment by picman** [comment]
If you enter the following URL with your document's ID into your browser, you will see the folder.

http://localhost:3000/dmsf/files/232564

![image](https://user-images.githubusercontent.com/779003/117804451-1559b980-b258-11eb-8e97-b2cc3a4533c4.png)

**Comment by RobertDiemer** [comment]
Hi picman,

thank you very much! You made my day!
Now it is much easier to find the files...

Best wishes,
Robert
