### ISSUE TITLE
WebDAV error

### ISSUE THREAD

**Issue by kvlahrobal** [danmunn/redmine_dmsf#1252]
After upgrading redmine to 4.2.1.stable and dmsf to version 2.4.6 i can not add the ressource to win10. 
I can add the master dms webdav ressource, but i can not add specific projects and i can not see them from the master.
The problem exists only by subprojects.

**Comment by picman** [comment]
**Sub-projects as sub-folders** option is checked in the plugin's settings?

**Comment by kvlahrobal** [comment]
Yes, it is.

**Comment by picman** [comment]
The right URL you can get from the link  Also available in WebDAV under documents on DMS tab. It should looks like https:://domain.org/redmine/dmsf/webdav/[project-identifier] or https:://domain.org/redmine/dmsf/webdav/[project-identifier]/[sub-project-identifier].
Another cause of your problems might be that you run Redmine in a sub-uri, right? See [this](https://github.com/danmunn/redmine_dmsf/blob/0cd7670ccd853a28f72ec34948efa43cea0a16ff/README.md#installation-in-a-sub-uri).

**Comment by kvlahrobal** [comment]
Before the update i get the webdav folder of an suproject also with:
https://domain.org/redmine/dmsf/webdav/[project-identifier] 
after the update it is:
https://domain.org/redmine/dmsf/webdav/[project-identifier]/[sub-project-identifier].

The WebDAV link under documents on DMS tab is also:
https://domain.org/redmine/dmsf/webdav/[sub-project-identifier].

Ich also added the config parameter and restarted my redmine.

**Comment by picman** [comment]
Both URLs should be working. I you click the WebDAV link, does it open in web browser?

**Comment by kvlahrobal** [comment]
No, i got a 404

**Comment by picman** [comment]
And what is in the _production.log_?

**Comment by kvlahrobal** [comment]
nothing, if  i click the link nothing happens in the log (tail -f ...)

**Comment by picman** [comment]
Update the master branch and try it again. I've just made a fix there. 
a966244
