### ISSUE TITLE
Sub Folder creation via REST API

### ISSUE THREAD

**Issue by vergelli** [danmunn/redmine_dmsf#1255]
I was looking for a way to create a subfolder into DMS projects, but I found no resources. I was reading that the [wiki](https://github.com/danmunn/redmine_dmsf/wiki/REST-API) includes a part which says:
 _iputs: project id, parent folder id, name_

 and I thought I could make use of the "_parent folder id_" to control this, but I don't see it very clear. ¿Could you give me a better example?

I'm working on a way of creating folder trees in DMS, reading a directories tree as an argument.
It would good to have that feature, anyway, there must be a way to tackle this now.

**Comment by picman** [comment]
Have a look [here](https://github.com/danmunn/redmine_dmsf/tree/master/extra/api)

```bash
curl -v -H "Content-Type: application/xml" -X POST --data "@folder.xml" -u your_login:your_password http://localhost:3000/projects/your_project_identifier/dmsf/create.xml
```

_folder.xml_
```xml
<?xml version="1.0" encoding="utf-8" ?>
<dmsf_folder>
  <title>rest_api</title>
  <description>A folder created via REST API</description>
  <dmsf_folder_id>your_parent_folder_id</dmsf_folder_id>
</dmsf_folder>
```

**Comment by vergelli** [comment]
@picman  I'm not sure I understand. [This](https://github.com/danmunn/redmine_dmsf/tree/master/extra/api) files here, are the ones I need to edit?

  Or this two: 
* [(1)](https://github.com/danmunn/redmine_dmsf/commit/7ea21837577192adefdac354f5e79223f9696cf0)
* [(2) ](https://github.com/danmunn/redmine_dmsf/commit/7ea21837577192adefdac354f5e79223f9696cf0)

As I am now, I make the following request with no luck:

This is the folder
```
folder = { "dmsf_folder": {
    "title": "folder_test_1",
    "description": "A folder created via REST API",
    "dmsf_folder_id": "21"
 }
}
```

This is the request

```
response = requests.post('https://url:port/projects/49/dmsf/create.json', 
                                          json=folder, auth=( redmineconfig.REDMINE_USER, 
                                                                         redmineconfig.REDMINE_PASSWORD))
```
What I get is, that the  "folder_test_1" folder, is created at the root of the 49 project, and no, inside folder 21, which is also at the root of project 49.

I'm not sure what files do I need to edit in order to get it working.

**Comment by picman** [comment]
No, create your own file _folder.xml_ with the content according to the example above and from the same folder call the utility _curl_.

**Comment by vergelli** [comment]
@picman I have tried but I receive the same result. Is weird because I am making as you said but I keep getting the folder created at the root, and not inside the folder I specified.   

`curl -k -v -H "Content-Type: application/xml" -X POST -d @folder.xml -u account:password https://url:port/projects/49/dmsf/create.xml`

```
<?xml version="1.0" encoding="utf-8" ?>
<dmsf_folder>
  <title>folder_test_1</title>
  <description>A folder created via REST API</description>
  <dmsf_folder_id>21</dmsf_folder_id>
</dmsf_folder>
```

Here is the folder of name _folder_test_1_ but is not inside folder with id=21
![Error2](https://user-images.githubusercontent.com/21988764/118877115-6c990300-b8c4-11eb-9cdc-f846940600c7.png)



One thing I forgot to mention, I am using DMSf version 2.4.4 on Redmine 4.0.3stable

**Comment by picman** [comment]
Fixed.
