### ISSUE TITLE
Act as attachable - 

### ISSUE THREAD

**Issue by joter2** [danmunn/redmine_dmsf#1257]
I have a problem with documents attached to issues
After checking the option "Act as attachable" can not create a link to the document. I enclose information about the installed version. Please answer. 
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.5.8-p224 (2020-03-31) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  additionals                    3.0.1-master
  custom_tables                  1.0.6
  redmine_agile                  1.5.3
  redmine_announcements          2.0.0
  redmine_checklists             3.1.16
  redmine_contacts               4.3.1
  redmine_contacts_helpdesk      4.1.9
  redmine_contacts_invoices      4.2.3
  redmine_crm_mailchimp          1.0.4
  redmine_custom_css             0.1.7
  redmine_custom_workflows       1.0.3
  redmine_dmsf                   2.4.5

Regards 
J. Rycerz

**Comment by picman** [comment]
Please add a detailed description what you do, what happened and what you expect. Also post a chunk of production.log related to the problem.

**Comment by joter2** [comment]
Thank you for your quick reply. I have enabled the options one by one -
images 1 and 2
When editing an issue there is no option to include a link to the file -
images 3 and 4
Z pozdrowieniami,
Jarek Rycerz


pt., 28 maj 2021 o 14:39 Karel Picman ***@***.***> napisał(a):

**Comment by picman** [comment]
As you updated the issue via email, no images were attached. Also the log is missing.

**Comment by picman** [comment]
No feedback => closing.
