### ISSUE TITLE
Redmine version dependency differs between readme.md and init.rb 

### ISSUE THREAD

**Issue by martinbra** [danmunn/redmine_dmsf#1262]
Regarding the plugins redmine version dependency, there is a discrepancy at the documentation.
in README.md it says:
```
Features
--------
  * Compatible with Redmine 4.2.x

Dependencies
------------  
  * Redmine 4.0.0 or higher
 ```

but in init.rb it requires: 
```
requires_redmine version_or_higher: '4.2.0'
```

Is the plugin still compatible with redmine 4.0.x or 4.1.x?

**Comment by picman** [comment]
No, it isn't. Redmine 4.2 required.

**Comment by martinbra** [comment]
Thanks for the info.
Amazing plugin by the way. Thanks for your time and effort maintaining it!
