### ISSUE TITLE
Letters on document version cause Internal Error

### ISSUE THREAD

**Issue by vergelli** [danmunn/redmine_dmsf#1263]
Redmine version:  4.2.1.stable ( on Docker)
DMSf version: 2.4.6
DB: Postgres

**Steps to Reproduce:**
Trying to upload a document with a letter as version
![1](https://user-images.githubusercontent.com/21988764/122116784-67b06c00-cdfc-11eb-91d1-de5e14d18658.png)

Docker shows the following:

```
container_redmine | http://url:3000/projects/projecto1/dmsf/upload/files?folder_id=2 -> /projects/projecto1/dmsf/upload/commit?folder_id=2
container_redmine | someUrl - - [10/Jun/2021:03:01:28 UTC] "GET /projects/projecto1/dmsf?folder_id=2 HTTP/1.1" 500 648
container_redmine | http://url:3000/projects/projecto1/dmsf/upload/files?folder_id=2 -> /projects/projecto1/dmsf?folder_id=2

```

I was having problems trying to install the 2.4.7 version that's why I couldn't try with it.

**Comment by picman** [comment]
Could you please add also what is in Redmine's production.log?

**Comment by vergelli** [comment]
Sorry, I am having some issues trynna find the production.log. There is nothing on the logs folder. Am I missing something? maybe some configuration, or permissions thing?

**Comment by picman** [comment]
It should be located in _redmine/log/production.log_.

**Comment by picman** [comment]
No feedback => closing.
