### ISSUE TITLE
Cannot upload some PDF files

### ISSUE THREAD

**Issue by meolic** [danmunn/redmine_dmsf#1264]
Some regular and not to big PDF files (typicaly those produced with LaTeX) are not possible to upload - maybe their size is wrongly determined.

![image](https://user-images.githubusercontent.com/15260936/122531679-0668e280-d020-11eb-99df-aca3f9c5f699.png)

**Comment by picman** [comment]
Could you attach such a file, please? To be able to test it locally.

**Comment by meolic** [comment]
Here is a test file that does not work for me.
[redmine-test.pdf](https://github.com/danmunn/redmine_dmsf/files/6692593/redmine-test.pdf)

**Comment by picman** [comment]
The attached file has got size of 4,9MB. If I limit **Maximum attachment size** to 4096KB in Redmine's settings, the file can't be uploaded due to _The file cannot be uploaded because it exceeds the maximum allowed file size (4MB)_. If I increase the **Maximum attachment size** to 8192KB, the upload works.
What is the size of the file in your file system and what is the limit? The size of the same file might vary in different filesystems and if your maximum is set near the file's size, it might be the cause.

**Comment by meolic** [comment]
I confirm that if I include much smaller image in exactly the same document then the upload works (file is much smaller).

I have changed Administration -> Settings and now I have this:

![image](https://user-images.githubusercontent.com/15260936/122907178-261b4600-d353-11eb-9978-a3be2ba26f38.png)

I have restarted server (and changed language to English but some text i still localized).

I have the following plugin setting:

![image](https://user-images.githubusercontent.com/15260936/122903342-9aec8100-d34f-11eb-9c85-f922ec74ea89.png)

I still get the error for the file that has size 4,885,165 B (4,7M). Where else I have to setup the max size? The dialog for choosing the file reports "Maximum size: 64 MB" that is consistent with settings.

![image](https://user-images.githubusercontent.com/15260936/122907365-595dd500-d353-11eb-871d-343a4997821a.png)

![image](https://user-images.githubusercontent.com/15260936/122902711-008c3d80-d34f-11eb-99e6-0b97ce785453.png)

**Comment by picman** [comment]
Nowhere. This is the only option taken into account. The problem is then very probably not related to the max size but something else.

1. Check the production.log for any errors.
2. Check the Web Developer console in your browser <F12>.

**Comment by meolic** [comment]
Hm, I am using webrick to run Redmine server. When I try to upload the small file I get this:

```
127.0.0.1 - - [22/Jun/2021:12:49:32 CEST] "GET /projects/portal-sumo-redmine/dmsf/upload/multi_upload?folder_id=72 HTTP/1.0" 200 12663
https://redmine.operato.eu/projects/portal-sumo-redmine/dmsf?folder_id=72 -> /projects/portal-sumo-redmine/dmsf/upload/multi_upload?folder_id=72
127.0.0.1 - - [22/Jun/2021:12:51:03 CEST] "POST /dmsf_uploads.js?attachment_id=3&filename=redmine-test1.pdf&content_type=application%2Fpdf HTTP/1.0" 200 390
https://redmine.operato.eu/projects/portal-sumo-redmine/dmsf/upload/multi_upload?folder_id=72 -> /dmsf_uploads.js?attachment_id=3&filename=redmine-test1.pdf&content_type=application%2Fpdf
```

However, when I try to upload the larger file, there is no POST request, just nothing is written out. I do not know how to check Web Developer console. No errors in the prodcution.log.

**Comment by meolic** [comment]
OK, now I managed to open Developer console. In fact, there appears a message when I try to upload the large file (no such message when uploading small file).

![image](https://user-images.githubusercontent.com/15260936/123059100-be740200-d409-11eb-859d-7661ee52f5b9.png)

**Comment by meolic** [comment]
And the file type is not important, only size matters! Using bisection I have determined, that the limit for upload is exactly 1 MB. File test1024.txt will proceed while test1025.txt will fail with an error.

```
[meolic@localhost ~]$ dir test1024.txt test1025.txt 
-rw-rw-r--. 1 meolic meolic 1048576 jun 23 10:19 test1024.txt
-rw-rw-r--. 1 meolic meolic 1049600 jun 23 10:21 test1025.txt

```

**Comment by picman** [comment]
According to your screen-shots you have set **Maximum attachment size** = 65536KB in Settings/Files
Check the source code of the **_Browse..._** button, for your settings *Maximum attachment size** = 65536KB in Settings/Files, you should see something like this:

```html
<span class="dmsf_add_attachment add_attachment">
<input type="file" name="dmsf_attachments[dummy][file]" class="file_selector" multiple="multiple" onchange="dmsfAddInputFiles(this);" data-max-file-size="67108864" data-max-file-size-message="This file cannot be uploaded because it exceeds the maximum allowed file size (64 MB)" data-max-concurrent-uploads="2" data-upload-path="/dmsf_uploads.js" data-description-placeholder="Optional description" data-project="c1" data-description="true" data-awf="false">
<span class="info"> (Maximum size: 64 MB)</span>
```
Notice `data-max-file-size="67108864"` which corresponds in bytes with set 65536KB.

Do you have the same value in the source code of the button?

**Comment by meolic** [comment]
I have the same:

```
<span class="dmsf_add_attachment add_attachment">
  <input type="file" name="dmsf_attachments[dummy][file]" class="file_selector" multiple="multiple" onchange="dmsfAddInputFiles(this);" data-max-file-size="67108864" data-max-file-size-message="This file cannot be uploaded because it exceeds the maximum allowed file size (64 MB)" data-max-concurrent-uploads="2" data-upload-path="/dmsf_uploads.js" data-description-placeholder="Optional description" data-project="portal-sumo-redmine" data-description="true" data-awf="false" />
</span>
<span class="info">
    (Maximum size: 64 MB)
</span>

```

**Comment by meolic** [comment]
Now I have tested in Edge and Brave browser, they respond the same:

![image](https://user-images.githubusercontent.com/15260936/123083867-cdb27a00-d420-11eb-9ab6-85d10ebd2034.png)

**Comment by picman** [comment]
Hm, I really don't know what is wrong then...

**Comment by meolic** [comment]
Thank you for trying. Would it help to you if I give you access and account on our redmine?

**Comment by picman** [comment]
Yes, we can try it.

**Comment by picman** [comment]
Check this:
_/etc/nginx/nginx.conf_
```client_max_body_size 1M;```

**Comment by meolic** [comment]
This solves the problem!

Indeed, our redmine server is being proxied by nginx. There was no such line in nginx.conf but default is 1M (https://stackoverflow.com/questions/28476643/default-nginx-client-max-body-size). Now I have added the following in the server block:

       client_max_body_size 0;

**Comment by picman** [comment]
Very well. BTW, you should limit the _client_max_body_size_ due to security of your server. Maybe you should set it to the same value you have set in Redmine, 64MB.
