### ISSUE TITLE
WebDav link error

### ISSUE THREAD

**Issue by Blazeplan21** [danmunn/redmine_dmsf#1266]
OS : Windows 10
Redmine : Bitnami 4.2.1
DMSF : 2.4.7

if i click WebDAV link in dmsf page then always have internal server error

production.log 

`Started GET "/redmine/dmsf/webdav/" for 127.0.0.1 at 2021-06-25 18:21:20 +0900
Processing WebDAV request: /redmine/dmsf/webdavC:/ (for 192.168.0.1 at 2021-06-25 18:21:20 +0900) [GET]
WebDAV Error: path must be present and start with a /
path must be present and start with a /
`
i cant find solutions.

**Comment by picman** [comment]
Have you read this?
https://github.com/danmunn/redmine_dmsf#installation-in-a-sub-uri

**Comment by Blazeplan21** [comment]
> Have you read this?
> https://github.com/danmunn/redmine_dmsf#installation-in-a-sub-uri

yes i try it. but problem didnt solved.

**Comment by picman** [comment]
What URL is behind the link?

**Comment by Blazeplan21** [comment]
/redmine/dmsf/webdav/%5Btest_temp%201%5D/

**Comment by Blazeplan21** [comment]
/redmine/dmsf/webdav/

**Comment by Blazeplan21** [comment]
i dont understand why request link add C:

in production.log
Processing WebDAV request: **/redmine/dmsf/webdavC:/** (for 192.168.0.1 at 2021-06-25 20:41:49 +0900) [GET]

**Comment by picman** [comment]
Yes, that's strange and obviously wrong.

**Comment by Blazeplan21** [comment]
i tried install same os, redmine, dmsf plugin at new computer. 
but have same issue and same log.

Started GET "/redmine/dmsf/webdav/" for 127.0.0.1 at 2021-06-26 11:39:52 +0900
Processing WebDAV request: **/redmine/dmsf/webdavC:/** (for 127.0.0.1 at 2021-06-26 11:39:52 +0900) [GET]
WebDAV Error: path must be present and start with a /
path must be present and start with a /

**Comment by picman** [comment]
Try Linux instead of Windows. At least there won't be any `C:`.

**Comment by picman** [comment]
Probably fixed in #1356.
