### ISSUE TITLE
Version 2.4.7 not compatible with Redmine 4.1

### ISSUE THREAD

**Issue by karagounis78** [danmunn/redmine_dmsf#1268]
Hello,
my Redmine instance, v. 4.1.1, is running with DMSF 2.4.5. 
I would like to provide my users the new functionality of sub-projects asd sub-folders provided by latest 2.4.7. I have tried to install that but I have problem with Rake file when migrate the db: RAKE requires Redmine 4.2 and I cannot proceed.
For the bundle install, after small modification to Gemfile, there is no problem.

Is 2.4.7 version compatible also with previous 4.1 Redmine or I need 4.2 for the new function?
Thanks

**Comment by picman** [comment]
No, it's not. Redmine 4.2 required.
