### ISSUE TITLE
Folder Permission and REST API

### ISSUE THREAD

**Issue by RobertDiemer** [danmunn/redmine_dmsf#1271]
Dear all,

I have one question: Is it possible to set the folder permissions via REST API?
I want to set/reset equal permissions for a whole sub-tree without clicking each folder....
It seems, that some sub-sub-folders have different permissions than the inherited ones.

Thank you in advance,
Robert

**Comment by picman** [comment]
Yes, it should be generally possible. You should extend the XML with permissions part. Something like this
```xml
<?xml version="1.0" encoding="utf-8" ?>
   <dmsf_folder>
     <title>rest_api</title>
     <description>A folder updated via REST API</description>
   </dmsf_folder>
  <permissions>
     <user_ids>
      <user_id1>1</user_id1>
      <user_id2>2</user_id2>
     </user_ids>
  </permissions>
```
However, it should be enough to set permissions for the top folder. All its sub-folders should inherit their permissions from the parent folders.

**Comment by RobertDiemer** [comment]
Dear picman,
thanks for the really quick reply!
Is it possible, that the inherited permissions don't rule, as soon as "folder-special" permissions are set?

E.g. Inherited Permssions:
+ Manager
+ Developer

Local Permissions:
- Manager
+ Developer

--> Manager doesn't have permission to view the folder

Best wishes,
Robert

**Comment by RobertDiemer** [comment]
Oh sorry, I just saw, that the signs have changed.
Granted Permissions by Inheritance:
+ Manager
+ Developer

Locally Granted Permission
+ Developer
Locally Denied Permission
- Manager

--> Manager doesn't have permission to view the folder.

If I don't grant any permission locally, the inherited permissions rule...

Best wisher,
Robert

**Comment by picman** [comment]
Exactly, as soon as a folder has got its own permissions, the parent folder's permission are not taken into account; neither for it nor for it's sub-folders.

**Comment by RobertDiemer** [comment]
Dear picman,

thanks again. That helps me a lot!
