### ISSUE TITLE
Document tagging/filtering: filter not working when tag has multiple values 

### ISSUE THREAD

**Issue by hermannkm** [danmunn/redmine_dmsf#1272]
I successfully enabled tagging on 2.4.8 devel. I setup some tags and enabled "Use as filter".

Now when I use e.g. two tags A, B for some documents having A, B or both tagged, e.g.
d1(A), d2(B), d3(A, B)
filtering with A and B selected gives d1, d2 but NOT d3.

So I understand filtering when using multiple filter values as OR (which is fine) but I do not understand why meeting both criteria (which an OR should give true also) does not render my document.

**Comment by hermannkm** [comment]
Testing again and giving an example:

```
#;Titel;Tag;Größe;Datum
10;d1;Tablets;19,8 MB;23.07.2021 05:21
144;d2;Prim;5,74 MB;22.07.2021 08:40
147;d3;Prim, Tablets;15 MB;22.07.2021 12:30
```

Filtering with 'Prim' checked renders #144, with 'Tablets' checked #10, with both checked (after clicking the "+" sign) renders #10 and #144.
#147 is never given as a result which is very disturbing: the multiple filter is neither acting as OR (as written before) nor as EQUAL.

**Comment by hermannkm** [comment]
As the tag field is not searchable I am left at the moment with only single tags working.

**Comment by picman** [comment]
Fixed.

**Comment by hermannkm** [comment]
Great, thank you. Verified successfully with above test data.
