### ISSUE TITLE
Multiple documents actions options

### ISSUE THREAD

**Issue by vergelli** [danmunn/redmine_dmsf#1274]
Hello, I was wondering if there is a chance that this can be done.  When you select multiple documents and press on 'actions', some of the options that are available for a single document aren't there. For example:

For a single document, we've got this

![Actions3](https://user-images.githubusercontent.com/21988764/127152188-c0495410-2381-456b-b9fa-0468d7cdee28.png)

But if I select multiple documents I get this actions:

![Actions4](https://user-images.githubusercontent.com/21988764/127152288-309fe114-6c31-4447-a124-e20a3418c340.png)

I wonder if there is a chance to have `Copy/Move` and `Assignment` added into multiple documents selection actions:

![Actions5](https://user-images.githubusercontent.com/21988764/127152597-df884d71-a7e8-4a6d-87e2-fe3a9fb857d1.png)

Regards.

**Comment by picman** [comment]
Duplicates #1132.
