### ISSUE TITLE
link issues to a document (not from attach)

### ISSUE THREAD

**Issue by Mdiaz-PMO** [danmunn/redmine_dmsf#1275]
Hey Karel is there the possibility to link an issue from dms module? I mean, create a file in dms and then link it to an existing issue? I understand that I can do the inverse process (generate an issue and link it to an existing dms file); but i need to do it from dms in order to know wich issues are linked to a file; also can it be added as a filter?
thanks!

**Comment by picman** [comment]
No, there is no such option.
