### ISSUE TITLE
Problem with editing an exisiting link

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1280]
I have created a new link to a folder in another project. Now I wanted to modify the title of this link, which does not seem to be possible:

![grafik](https://user-images.githubusercontent.com/7224922/130053173-11eb0fdc-c692-426a-a6a9-19a2c9d4fccd.png)

I have discovered the following problems:

- Clicking on Edit in the menu opens the edit form of the folder in the other project. It does not open an edit form to change the settings of the link
- The link # - 63 in this case - opens an edit form of the folder number 63. This folder belongs to a completely different project for which I do not have access permissions. It also shows a false location in which project that folder resides. 

My expection is that I can modify the description of a link and that the links (Edit + #) are properly showing an edit form to make that change.

Thank you.

**Comment by picman** [comment]
1. Editing of links is not supported. If you want to, for instance change the title, you must delete the link and create it again.
2. I've just tested edit and always the right target folder is opened for editing. If the user hasn't got access to the target project, 403 - access denied is correctly displayed.

> It also shows a false location in which project that folder resides.

Please provide a screen-shot.

**Comment by mmundi72** [comment]
I have have attached a short video showing what happens when clicking on #. I then search for that folder and I do not get a result.
When I log in as administrator and search for the same folder I get the correct location of that folder. In the video I did not have permission for that project.


https://user-images.githubusercontent.com/7224922/130057673-dd9ae0c3-3218-49f2-a733-3466fd0d6e18.MP4

Screenshot logged in as admin:

<img width="516" alt="Snag_134b78e" src="https://user-images.githubusercontent.com/7224922/130057685-1a4a0901-c26e-44ca-a29f-95be8792a25f.png">

As you can see in the video it shows a different project name in the header as in the screenshot. 

Well, if editing an link is not possible then at least remove the "edit" functions for a link as this is not logical at all.

**Comment by picman** [comment]
What DMSF version do you use. I cannot reproduce the problem. If I click on #, 403 Access denied appears.

**Comment by mmundi72** [comment]
2.4.5 - currently I do not have a test environment with a more current version. We are still on Redmine 4.1 that's why we haven't upgraded DMSF either.

**Comment by picman** [comment]
So, it's very probably a former problem which has been already solved. An upgrade is necessary on your side.

**Comment by mmundi72** [comment]
Ok, I just installed a blank Redmine installation with DMSF devel-2.4.8. It properly shows 403 Access denied.

But have a look at the different links and explain. I don't understand, why two different folder are accessed:

1: Have a look at the link which is being accessed by clicking edit in the menu:
![grafik](https://user-images.githubusercontent.com/7224922/130485079-270f88b2-1762-4770-9bcf-4c910658cd19.png)

2: and now this time I click on the ID and a different folder is being accessed. why?
![grafik](https://user-images.githubusercontent.com/7224922/130485175-c1b09057-5ebd-4759-82b0-71a0db56644a.png)

**Comment by picman** [comment]
Fixed.
