### ISSUE TITLE
Linking an specific file version

### ISSUE THREAD

**Issue by ramezquitao** [danmunn/redmine_dmsf#1281]
Thanks for this really usefull plugin for Redmine. 

I know it is possible to link files stored in the DMSF using a sintax like this ->  {{dmsf(17)}} . My question is:  Is it possible to specify not only the file ID, but also the file revision or version?

**Comment by hermannkm** [comment]
From Macro Documentation:

```
dmsf
Wiki link to DMSF file:

{{dmsf(file_id [, title [, revision_id]])}}

_file_id_ / _revision_id_ can be found in the link for file/revision download.
```
