### ISSUE TITLE
current view changed after adding new revision

### ISSUE THREAD

**Issue by hibit-2709** [danmunn/redmine_dmsf#1282]
In each project we have in Documents many folders and files.
I open folder X, file in it. When I add a revision, I finally see the root directory (Documents) and all folders closed, not the X folder and its files.
What am I doing wrong?

**Comment by picman** [comment]
It's a feature. You are redirected to the default view from the form.

**Comment by hibit-2709** [comment]
But now it is not as intuitive as, for example, in version 2.4.1. 
All our users treated DMSF as a file system.
I open the folder and work in it until I decide to leave it.
And by the way, thanks for the great work.

**Comment by picman** [comment]
I think that that hasn't changed. Provide a screen-shot how do you think it worked or should work.

**Comment by hibit-2709** [comment]
I open the folder. (red ellipse)
![DMSF_before](https://user-images.githubusercontent.com/84457821/130758240-ab78d5fd-bdf9-41f4-af53-03c66b3df73e.png)
Then lock file (red ellipse on the right), and after it i see
![DMSF_after](https://user-images.githubusercontent.com/84457821/130758569-59b90966-86c0-4f9e-b09a-0d7111c47ca1.png)

**Comment by hibit-2709** [comment]
In version 2.4.1 i see after the same view as on the start.

**Comment by picman** [comment]
Fixed.
