### ISSUE TITLE
Rest API: link file to an issue

### ISSUE THREAD

**Issue by kty0mka** [danmunn/redmine_dmsf#1283]
Hi!

I am playing with DMSF API. As I understand, it is possible to link a file to another folder, but is it possible to link a file to an issue? In other words, can we use the API to do the same as clicking a "Link from" button in the issue edit form (when "Act as attachable" is enabled).

<img width="381" alt="Знімок екрана 2021-08-27 о 16 43 56" src="https://user-images.githubusercontent.com/57333179/131137351-84cd849a-c8ca-4cdb-802f-beda6715847f.png">

Thanks!

**Comment by picman** [comment]
It should be theoretically possible. Each issue with attached documents has got its system folder like _.Issues/issue_id - issue_subject_. They are visible in DMS module with **Display system folders** permission.
So, if you create a link in such a folder using REST API, it will be assigned to the issue. If the corresponding folder hasn't been created yet, create it in advance using REST API too.

![image](https://user-images.githubusercontent.com/779003/131352551-26e53d05-cec2-4d49-9732-12d2b329106f.png)

**Comment by kty0mka** [comment]
Yes, I also thought so at first, but I can't create a folder anywhere except the root using the API.

I tried like this:
```
<?xml version="1.0" encoding="utf-8" ?>
<dmsf_folder>
  <title>My Folder</title>
  <description>Some Description</description>
  <dmsf_folder_id>1112</dmsf_folder_id>
</dmsf_folder>
```
And like this:
```
<?xml version="1.0" encoding="utf-8" ?>
<dmsf_folder>
  <title>My Folder</title>
  <description>Some Description</description>
  <folder_id>1112</folder_id>
</dmsf_folder>
```
Where "1112" is the ID of the desired parent folder. But all attempts were unsuccessful – it simply ignores this parameter.
In both cases, I get a valid response:
```
<?xml version="1.0" encoding="UTF-8"?>
<dmsf_folder>
  <id>1135</id>
  <title>My Folder</title>
</dmsf_folder>
```
But my folder is only created at the root folder of DMSF.

At first I thought that the DMSF does not allow to manually create a folder inside the ".Issues" system folder, just as it does not allow to do this in the web interface, but now I checked with any other folder and the result is the same unsuccessful.

What am I doing wrong?

**Comment by picman** [comment]
It was a bug and it has been already fixed. The right format now is:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<dmsf_folder>
  <title>My Folder</title>
  <description>Some Description</description>
  <dmsf_folder_id>1112</dmsf_folder_id>
</dmsf_folder>
```

**Comment by kty0mka** [comment]
Yes, with devel-2.4.8 branch it really works. Thanks!

**Comment by kty0mka** [comment]
> Yes, with devel-2.4.8 branch it really works. Thanks!

Above I meant that creating a folder using the REST API inside the .Issues folder works, but the idea to create a file link to the issue in this way did not work. I think DMSF associates these folders with Issues for more than just name. Perhaps it keeps some kind of correspondence table between Issues ID and Folders ID?

Anyway, I don't see a way to link the file to the issue using the API. Could this be a feature request?

**Comment by kty0mka** [comment]
I understand your idea to create a link to a file in the corresponding issue folder.

If such a folder with issue files was created automatically by the plugin itself earlier (for example, we previously attached the file to the issue in the form of issue editing and the plugin itself created folder "/.Issue/ID - Subject") – then yes, such actions will take effect.

But if we create "/.Issue/ID - Subject" folder manually using the API – it does not work. Folder creation is possible, but adding files or links to such folder will not take effect: these documents will not appear in the issue page.

I looked at table "dmsf_folders" in the redmine database. There is a "system" column for each folder. All folders created automatically by the plugin have a value "1" in this column and, accordingly, manually created folders have a value "0".

I tried to manually set the value "1" in the "system" column for my folder, created using the API, and after that the method you proposed worked: the necessary documents were displayed in the issue page.

But as you can see, it is not possible to simply attach documents to an issue using just the API, if no one has previously attached documents to this issue from the edit page of the issue itself and the corresponding folder was not automatically created with the "system" flag in the folder record. Proposed method requires the "system" flag in the database, and it will not be set on its own using the API.

<img width="1064" alt="Знімок екрана 2021-09-02 о 16 22 11" src="https://user-images.githubusercontent.com/57333179/131851522-e44f94ac-2efa-4564-be58-7f089ad86d06.png">

**Comment by picman** [comment]
You are actually right. I've extended folder XML with system tag. So you can create such a system folder with the following XML now.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<dmsf_folder>
  <title>REST API</title>
  <description>A folder created via REST API</description>
  <dmsf_folder_id> your .Issue folder's ID</dmsf_folder_id>
  <system>1</issue>
</dmsf_folder>

```

**Comment by kty0mka** [comment]
Sorry for the long answer, couldn't check out the changes quickly.
So yes, now everything is working as expected, thanks a lot!
