### ISSUE TITLE
Unlock directory get 404 error

### ISSUE THREAD

**Issue by xandre31** [danmunn/redmine_dmsf#1285]
Hello,

I wanted to unlock a directory (included subdirectory and files like during lock process) but I got a 404 error.
Here are the redmine logs:

```
Started GET "/projects/4/dmsf/unlock?folder_id=4" for xxxxx at 2021-08-30 15:12:56 +0200
Processing by DmsfController#unlock as HTML
  Parameters: {"folder_id"=>"4", "id"=>"4"}
  Current user: XXXXX (id=28)
  Rendering common/error.html.erb within layouts/base
  Rendered common/error.html.erb within layouts/base (1.6ms)
Filter chain halted as :find_project rendered or redirected
Completed 404 Not Found in 70ms (Views: 51.5ms | ActiveRecord: 9.7ms)
```

Thanks for your help.
Regards.

**Comment by picman** [comment]
>Filter chain halted as :find_project rendered or redirected
It seems that there is no project with id = 4. Wrong URL?

**Comment by xandre31** [comment]
Folder id 4 is good :

![image](https://user-images.githubusercontent.com/57406741/131361654-5d611709-8254-4c38-812b-167f4428fcc6.png)

When I click on "CV internes", url is https://xxxxxxxxxx/projects/knowledge-management/dmsf?**folder_id=4**

**Comment by picman** [comment]
/projects/**4**/dmsf/unlock?folder_id=4

The first '4' stands for project's id.

**Comment by xandre31** [comment]
URL is given by the unlock button into dms tab : 

directory unlock https://xxxxxx/projects/4/dmsf/unlock?folder_id=4

Is it a bug in the unlock button on a directory because on a file URL is not the same : 

file unlock : https://xxxx/projects/knowledge-management/dmsf?folder_id=4#

**Comment by xandre31** [comment]
I replaced project ID by project name in the directory unlck URL and it worked.
There might be a bug in unlock button for directories : numeric project ID is used instead of alpha project ID

**Comment by picman** [comment]
What version of DMSF do you use?
Post a screen-shot of the button.

**Comment by xandre31** [comment]
here are redmine informations:

```
Environment:
  Redmine version                4.2.1.stable
  Ruby version                   2.7.2-p137 (2020-10-01) [x86_64-linux]
  Rails version                  5.2.5
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_ckeditor               1.2.3
  **redmine_dmsf                   2.4.7**
```

The screenshot (URL is at the bottom left):
![image](https://user-images.githubusercontent.com/57406741/131484432-416a3a74-47fd-4824-b9ee-f34920252727.png)

**Comment by picman** [comment]
Duplicates  #1258.
