### ISSUE TITLE
Allowing Read-only or read-write access

### ISSUE THREAD

**Issue by xandre31** [danmunn/redmine_dmsf#1286]
Hello,

Is there a way to manage right access (read-only or read-write) on files and directories please ?
I didn't find such a feature.

Thank you.
Regards,

**Comment by picman** [comment]
There is no such feature. Permissions are driven by roles the same way as for other modules in Redmine. There is a permission  extension for DMS, but it allows/disallows access/visibility of folder/files.

**Comment by xandre31** [comment]
OK thank you for your feedback.
