### ISSUE TITLE
Webdav Issue

### ISSUE THREAD

**Issue by ramezquitao** [danmunn/redmine_dmsf#1287]
Hello. I'm using webdav from the DMSF plugin,  and everything seems to be working fine except one thing: when accessing the root of the webdav from the redmine web interface or from many webdav clients (http://my_server/redmine/dmsf/webdav in my case), there are some webdav project's folders not listed. When I use the project's dms menu I can access the files correctly and when I write the full path (including the project name) in the webdav client (or click in the webdav link at the bottom of the dms page), I can access also the files.

I see no errors in the apache log files, so I dont know where to look for the problem.

This is my system information, in case it is needed

Environment:
  Redmine version                4.2.2.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Mercurial                      4.8.2
  Bazaar                         2.8.0
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  additional_tags                1.0.0
  additionals                    3.0.3
  redmine_checklists             3.1.19
  redmine_dmsf                   2.4.7
  redmine_per_project_formatting 0.1.0
  redmine_scm                    0.5.1
  redmine_wysiwyg_editor         0.22.0

**Comment by picman** [comment]
Could you test it with devel-2.4.8 please?

**Comment by ramezquitao** [comment]
@picman 

No, sorry, still the same

**Comment by picman** [comment]
Please post some screen-shots.

**Comment by ramezquitao** [comment]
Sorry, but the server has sensitive information, so I can not send screenshots. But checking carefully I realized the following: The Folders that are "invisible" belong g to sub-proyects. If I enable **Sub-projects as sub-folders** they are visible. Sorry for the report, but I think it was my mistake. 
I only have two question left: if **Sub-projects as sub-folders** is disabled, is it the intended behavior that sub-project DMS folders get invisible? 
Should I close the Issue?

**Comment by picman** [comment]
_**Sub-projects as sub-folders**_ = **off** => sub-projects folders shouldn't be visible/accessible.

The same is valid for WebDAV and normal view. In both clients you should see the same folders.
