### ISSUE TITLE
File storage directory hardcoded in indexer?

### ISSUE THREAD

**Issue by hermannkm** [danmunn/redmine_dmsf#1288]
I am (very fond) user of xapian indexing but decided previously to use files/dmsf as file storage directory which can be configured via plugin.
In xapian_indexer.rb, line 35 the directory seems to be replaced by a constant path obviously not suitable for me.

```
# DMSF document location $redmine_root/$files
$files = 'dmsf'
```

**Comment by picman** [comment]
Just modify the value according to your environment or create a symbolic link dmsf->files/dmsf. The reason why it has been changed is that that if you use Xapian for searching in both modules Files and DMS then you would search *files* and then *files/dmsf/*. The Files' index would contain results from DMS module too.

**Comment by hermannkm** [comment]
Manually changing is no problem although I would have to do this after every git pull. 

So this was a bad idea storing my dmsf files in files/dmsf? I stumbled upon xapian not finding my "normal" files when setting it to files/dmsf (, e.g. ticket attachments not done via dmsf. What would be best practice to find both -- keeping the 'files' setting? (Sorry, I am a Redmine newbie).


Connected to this setting is 

`$stem_langs     = ['english']
`
which too does not use the plugins settings, which are

` ['german','English']`

for me.

**Comment by picman** [comment]
If you modify your *xapian_indexer.rb* locally, `git pull` will keep your changes.
I use redmine_dmsf plugin to index DMS documents and redmine_xapian to index attachments. Therefore I need files and documents in two independent folders.

**Comment by hermannkm** [comment]
According to your explanations I successfully modified my directory structure linking
files -> storage/files
dmsf -> storage/dmsf
and modifying only Redmine_dmsf/extra/xapian_indexer.rb to point to dmsf.
Now everything is working perfectly, I can search for all my files. Thanks for the clarification.
