### ISSUE TITLE
Links show wrong ID(#)

### ISSUE THREAD

**Issue by MWKim-Sugentech** [danmunn/redmine_dmsf#1291]
DMSF Link file might show 'target_id' but the last version (v2.4.7) shows 'id'.

Before (v2.4.2)
![image](https://user-images.githubusercontent.com/64888143/133727782-05294dac-ed32-46f4-9b6b-28afdf34da71.png)

Now (v2.4.7)
![image](https://user-images.githubusercontent.com/64888143/133727855-9415c351-d242-4969-ad74-2aba5818ad30.png)

There are no problems in SQL.

Please check it :)

**Comment by mdecker** [comment]
I see this problem with 2.4.3 and 2.4.5 (cannot upgrade to a higher version as I'm currently stuck on redmine 4.0.7)

I'm wondering if this is related with another linking problem I see or a different bug:
Can you actually click the link to get to the file? In my case ".0" gets appended to the dmsf file ID and this leads to a 404 instead  of showing the file. Manually removing the ".0" after the ID makes the file accessible. 

When testing I also generated a folder link which has the same ".0" appended to the ID - but still works as expected.

**Comment by picman** [comment]
Fixed in 2.4.8.

**Comment by mdecker** [comment]
Any chance you can point us to the commit that fixes this?

**Comment by picman** [comment]
I think that it should be this commit https://github.com/danmunn/redmine_dmsf/commit/a5bca770dcf7cbf2aa3a46e80bde9766697fab6b.

**Comment by picman** [comment]
Duplicates #1280.
