### ISSUE TITLE
Unable to create Sub-folder through the UI

### ISSUE THREAD

**Issue by vergelli** [danmunn/redmine_dmsf#1295]
Hello there! I was checking the creation of subfolders into the DMSf module of Redmine, and I came to realize that whenever I try to create a subfolder on a particular folder, it just pops on the root of the dms of the project. Shouldn't it be inside the folder? I already figure out that I can, like, grab the folder into the one I want it to be, but I think it's not very intuitive. Is this a configuration option? or maybe I'm missing something,

Regards!

**Comment by picman** [comment]
It would be more clear if you post a screen-shot. You have to be inside the sub-folder to create another sub-folder inside the sub-folder.

**Comment by vergelli** [comment]
2.4.7 atm
