### ISSUE TITLE
xapian_indexer.rb There was an error parsing `Gemfile`

### ISSUE THREAD

**Issue by costanzagit** [danmunn/redmine_dmsf#1305]
hi,
i'm having issue by executing xapian_indexer.rb

[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `additionals.gemspec`: uninitialized constant Additionals::VERSION. Bundler cannot continue.

 #  from /var/www/redmine/plugins/additionals/additionals.gemspec:9
 #  -------------------------------------------
 #    spec.name          = 'additionals'
 >    spec.version       = Additionals::VERSION
 #    spec.authors       = ['AlphaNodes']
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /var/www/redmine/plugins/additionals/Gemfile:4
 #  -------------------------------------------
 #  # Specify your gem's dependencies in additionals.gemspec
 >  gemspec
 #
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /var/www/redmine/Gemfile:116
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------

Environment:
  Redmine version                4.2.3.devel
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  6.0.0
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
SCM:
  Subversion                     1.10.4
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  additional_tags                1.0.0
  additionals                    3.0.4-master
  mega_calendar                  1.7.5
  redmine_dashboard              2.11.0
  redmine_dmsf                   2.4.10
  redmine_ics_export             4.0.1.dev
  redmine_messenger              1.0.9

**Comment by picman** [comment]
It has just been fixed in Additionals.
