### ISSUE TITLE
Consult - Edit file upload View

### ISSUE THREAD

**Issue by vergelli** [danmunn/redmine_dmsf#1307]
Hello there. I have a question about editing an actual view of the plugin.

I want to add a series of drop-down lists into the file upload view, just right where the red rectangle is:

![Publicacion 1](https://user-images.githubusercontent.com/21988764/139681066-973e19a3-7ac9-4f7d-9eee-feae5dbbd734.png)

I'm not an expert with rails sadly, but I'm starting to get involved with this technology as I need to.  I assume this view is on `app/views/dmsf_upload/` am I right? 

Regards

**Comment by picman** [comment]
*app/views/dmsf_files/_file_new_revision.html.erb*

**Comment by picman** [comment]
Why you don't simply add a DMS custom field in the administration. It will appear on the upload page automatically?

**Comment by vergelli** [comment]
Yes, in fact, I added it. What I'm trying to do is, add 3 drop-down lists, and every selection of one of these, will concatenate the selection ( just text) into the custom field input, such that when I press on **create**, the custom field consumes this string formed by these 3 pieces of text that come from those lists.  I'm just trying to figure out how to, with my 3-hours Rails course lmao.
