### ISSUE TITLE
Show Multi (drag/drop depending on browser) upload/download

### ISSUE THREAD

**Issue by Gollis** [danmunn/redmine_dmsf#1310]
Hello, 

after migrating to the last REDMINE (4.1.1. > 4.2.3, clean install to a new VM, migrating DB and files), I also had to update DMSF from 2.4.1 to 2.4.11.
I don't see the Download, Email, Delete, Upload Drag and Drop field,  after the update. Can I turn it on somewhere?

Thank you for helping

![1](https://user-images.githubusercontent.com/47415136/141777790-594dd2ab-8eac-4ee4-8c7c-fd7562cbdb12.png)
![2](https://user-images.githubusercontent.com/47415136/141777799-432f8cf5-4a37-4bef-84a3-ff4f5c88ac5e.png)

**Comment by picman** [comment]
The buttons have been replaced with a context menu. Either the tree dots next to the plus buttons or a right click menu directly on folders and documents.

**Comment by Gollis** [comment]
> 
> 
> The buttons have been replaced with a context menu. Either the tree dots next to the plus buttons or a right click menu directly on folders and documents.


Thank you for the quick reply. I meant Drag and Drop box (rainbow wheel) under the menu. In dmsf_user_guide.odt, this is the third option of paragraph 8.1.10 Add documents.

**Comment by picman** [comment]
The drag&drop box has been replaced with the plus buttons.

**Comment by Gollis** [comment]
OK THX
