### ISSUE TITLE
Deleting the link between files and issues

### ISSUE THREAD

**Issue by liaham** [danmunn/redmine_dmsf#1311]
Hi

I have been observing a behaviour when trying to delete a link between files and issues where it is inconsistent to me and probably reveals a bug. I will try to explain it:

Given a Redmine instance with two projects. Project B holds all relevant files in the DMS module and project A is the project where operative tasks are defined and controlled. Let a user having in each project a different role. In project B the user is allowed to 

* View documents
* Browse documents
* Email documents
* File manipulation
* File approval

In project A she is allowed to do everything in the DMS module except deleting files.

When the user navigates to Project A and starts to edit an issue by linking a file from project B to this issue everything works as expected so far.

**a) first observation**
Assuming the user would like to remove this link from the issue in project A, she cannot delete the link directly from the issue since it is disabled due to the missing permission. When she navigates instead to the DMS module of project A to have a look at the ```.Issues``` directory she will discover that she could delete the link between the file and the issue. This is the inconsistency.

Is deleting a link the same for you as deleting the file where the link points to? 
If so, then a user without permission to delete should not be allowed to do so with a entry in ```.Issues``` directory. 
If not, then a user should be allowed to delete the link in the issue and in the ```.Issues``` directory.

**b) second observation**
When a user deletes the link in ```.Issues``` directory as described above then it behaves as expected. Both the entry in DMS module of project A is deleted and the link in the respective issue is deleted.

But if the same user decides to link the same issue with the same file as it was then she will get this link but there is no entry in the DMS module of project A anymore. Hence, she cannot delete the link a second time.

I would expect that a user is able to link and unlink a file as much as she like. Therefore, I would consider it as a bug.

What do you think?

Best regards 
Liane

**Comment by picman** [comment]
**add a)** This clear, I will fix it. The link deletion should be allowed in the issue form as deletion of links is controlled by file_manipulation permission.
**add b)** This is unclear for me. What do you mean with "to link the same issue with the same file as it was"?

**Comment by liaham** [comment]
What I meant with  "to link the same issue with the same file as it was" was: adding the link between the file and the issue again assuming somebody deleted the link by accident and wanted to make it undo.

I hope I have explained it more understandable now. If not, I can try to make a gif of that process and attach it here.

**Comment by picman** [comment]
I've just tested it and I can delete and read the same link without any problems:
1) Upload a document into DMS.
2) Creating an issue.
3) Link the document to the issue.
4) Deletion of link in .Issue folder => Link disappears from the issue too.
5) Link the same document to the issue again.
6) Deletion of link in .Issue folder => Link disappears from the issue too.

**Comment by liaham** [comment]
I've also tested it with a fresh database in my development environment and I've observed the same as you now. 
I will keep an eye on the behaviour I observed earlier ... For now, you can ignore part b) of this issue.
