### ISSUE TITLE
Impossible to use macro in the revision comment field.

### ISSUE THREAD

**Issue by mrak0s** [danmunn/redmine_dmsf#1313]
It seems that it is impossible to use macros in the revision comment and description fields.
I try to remove the call of h() function in lines:
https://github.com/danmunn/redmine_dmsf/blob/a96624448eeea530e999c668b94fc4c24df7cacd/app/views/dmsf_files/show.html.erb#L102
https://github.com/danmunn/redmine_dmsf/blob/a96624448eeea530e999c668b94fc4c24df7cacd/app/views/dmsf_files/show.html.erb#L131
and this solve the issue, but I'm not sure if it's safe solution…

Environment:
  Redmine version                4.2.1.stable
  Ruby version                   2.5.3-p105 (2018-10-18) [x86_64-linux]
  Rails version                  5.2.5          
Redmine plugins:
  project_section                0.1.1
  redmine_contacts               4.3.3
  redmine_dmsf                   2.4.7
  redmine_lightbox2              0.5.1

**Comment by picman** [comment]
Yes, it is a good solution. Thank you.
