### ISSUE TITLE
All nodes of a particular project query?

### ISSUE THREAD

**Issue by vergelli** [danmunn/redmine_dmsf#1316]
Hello there, Greetings!

I was wondering if there is a query to GET all the nodes of a particular project, for example:

`GET projects/233/dmsf.json?all`

and the response would be each and every one of the nodes, not just the ones contained on the root.

Why am I saying this, I'm working on a python project in which I'm in the need of listing all existing files of a project, and I'm facing that, I'm working with this recursively, I mean, making a recursive function that travels between the folders structure. It's been a pleasure to code it, and very challenging, but I wonder if there is a way to tackle this by just one query.

**Comment by picman** [comment]
No, there is no such API call available, sorry.

**Comment by vergelli** [comment]
No problem, maybe I can release a tool if someone ever needs it
