### ISSUE TITLE
easy_gantt compatibility

### ISSUE THREAD

**Issue by andreav** [danmunn/redmine_dmsf#1318]
Hello,
I'm using the latest version of redmine_dmsf and easy_gantt.

Until dmsf is alone (without easy_gantt installed), dmsf works.

After adding easy_gantt, redmine starts no more.

The problem should be in the Gemfile of dmsf:

```
unless %w(easyproject easy_gantt).any? { |plugin| Dir.exist?(File.expand_path("../../#{plugin}", __FILE__)) }
    gem 'redmine_extensions', '~> 0.3.9'
    gem 'simple_enum'
     ... 
  end
```

simple_enum does not seems to be installed by easy_gantt, so now bundle install removes this gem and dmsf no more works.

I created a Gemfile.local adding this gem and everything started working again.

Thank you for this great plugin.

**Comment by picman** [comment]
Thank you for reporting that and also for the workaround.

**Comment by psi-4ward** [comment]
Where did you put the `Gemfile.local`? It doesnt work for me but moving ` gem 'simple_enum'` out of the `unless` block.
Thanks for the report.

**Comment by andreav** [comment]
In the root of the app. Not inside the plugin. Next to top level Gemfile.


Il Sab 29 Gen 2022, 14:30 Christoph Wiechert ***@***.***> ha
scritto:

**Comment by whotopia** [comment]
Just to confirm that I still had this issue today with 
 Redmine version                4.2.5.stable
  Ruby version                   2.7.5-p203 (2021-11-24) [x86_64-linux]
  Rails version                  5.2.6.3
  
  easy_gantt                     1.13
  redmine_dmsf                   2.4.11
  
  
  Manually adding   gem 'simple_enum' to the redmine_dmsf/Gemfile  outside of the unless ... gantt_easy  fixes the issue.
