### ISSUE TITLE
Dmsf custom fields Table 

### ISSUE THREAD

**Issue by vergelli** [danmunn/redmine_dmsf#1320]
Hello, I have a question. 
Are the custom fields values of DMS stored in a particular table?
The table I was searching for values is the one called `custom_values`, yet I'm not sure, where is this data stored?

**Comment by picman** [comment]
DMS custom field values are stored in _custom_values_ table as all the others custom field values. You can search them by their type:

```sql
select * from custom_values where customized_type like 'Dmsf%';
```

**Comment by vergelli** [comment]
Thank you !

**Comment by vergelli** [comment]
Thank you. 

Is there a way to filter files of the DMS based on the values of one of their custom_fields? 
Using the DB. Because I noticed that the table custom_values doesn't really have any reference to the file it belongs to. Am I right? or am I missing something maybe

**Comment by picman** [comment]
There certainly is a relation via _customized_id_:

```sql
select f.name from dmsf_files f join custom_values v on v.customized_id = f.id where v.customized_type = 'DmsfFileRevision' limit 1;
```

**Comment by vergelli** [comment]
There must be something I'm missing. You are saying that the field `customized_id` maps into `id` from the dmsf_files table, but I'm finding inconsistency.

For example, I have this file right here ( sorry for the quality)

![1](https://user-images.githubusercontent.com/21988764/147665054-7565db17-b759-4061-acc0-38e13ab14d48.png)

on the DB:
![6](https://user-images.githubusercontent.com/21988764/147665102-de3d8095-13af-4f42-a1b8-f995a0272e8e.png)

you can see there are a bunch of Custom fields with the values "123"
![2](https://user-images.githubusercontent.com/21988764/147665189-531057b4-68e1-448e-880c-3969db0c77f2.png)

Now I look into the `custom_values` DB and go to the146 file but I see a completely different scenario
![3](https://user-images.githubusercontent.com/21988764/147665585-1ffa26d2-0875-416e-9aaa-627f0f66a329.png)

Those custom fields are not in the file as you can see, maybe I'm missing something but seems that the fields are not matching.

If I go a little lower I see this:

![4](https://user-images.githubusercontent.com/21988764/147665716-8c173177-180e-494c-95fe-82f66d98b499.png)

It looks like it is the `146` file but even though I'm not sure now.


Best Regards

**Comment by picman** [comment]
You are right, _customized_id_ refers to _dmsf_file_revision_ table. So the query should look like follows:

```sql
select r.name from dmsf_file_revisions r join custom_values v on v.customized_id = r.id where v.customized_type = 'DmsfFileRevision' limit 1;
```
