### ISSUE TITLE
edit content (MS Office) can't open the file for editing

### ISSUE THREAD

**Issue by Thommi1969** [danmunn/redmine_dmsf#1321]
if I choose "edit content" from the file menu ... for an MS Office document (Word, Excel) after opening MS Office, i get the Message "Microsoft Excel cannot acces the file ..... there are several possible reasons" 

- the file name or path doesn't exist
- the file is being used by another program
- the workbook you are trying to save has the same name as a currently open workbook

nothing of this reasons is valid for me.  if I open via WEBDAV or just click in the file itself for downloading it's working.

best regards.

**Comment by picman** [comment]
Please provide the following information
1. DMSF vesrion
2. Redmine version
3. MS Office version
4. Lines corresponding to the opening a document in MS Office in log/production.log
5. Do you run Redmine in sub-uri?
6. Do you use HTTPS?
7. Do you use basic authentication for users?

**Comment by Thommi1969** [comment]
1. 2.4.10
2. Redmine 4.2.1.stable
3. MS Office Pro Plus 2016
4. Started GET "/projects/test-2/dmsf?folder_id=1" for 192.168.126.1 at 2022-01-05 09:50:45 +0100
Processing by DmsfController#show as HTML
  Parameters: {"folder_id"=>"1", "id"=>"test-2"}
  Current user: admin (id=1)
  Rendering plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_main.html.erb (1.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.2ms)
  Rendered queries/_filters.html.erb (2.2ms)
  Rendered queries/_columns.html.erb (0.4ms)
  Rendered queries/_query_form.html.erb (3.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb (27.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb (29.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_sidebar.html.erb (1.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_main.html.erb (37.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (37.2ms)
  Rendered plugins/redmine_people/app/views/common/_people_select2_data.html.erb (0.1ms)
  Rendered plugins/redmine_people/app/views/common/_layout_bottom.html.erb (0.2ms)
Completed 200 OK in 73ms (Views: 53.6ms | ActiveRecord: 8.8ms)
Started GET "/projects/dmsf/context_menu?folder_id=1&utf8=%E2%9C%93&authenticity_token=RqHp0OzQMM9DtVeP5SwlLS6_r4-ePfvWBXeevP3lo6Scf5xfsTc7QAF9U6oDixwJ9qnuBx2UpnHrG7a5jCB7Kg&back_url=%2Fprojects%2Ftest-2%2Fdmsf%3Ffolder_id%3D1&c%5B%5D=title&c%5B%5D=size&c%5B%5D=modified&c%5B%5D=version&c%5B%5D=workflow&c%5B%5D=author&ids%5B%5D=file-1" for 192.168.126.1 at 2022-01-05 09:50:48 +0100
Processing by DmsfContextMenusController#dmsf as */*
  Parameters: {"folder_id"=>"1", "utf8"=>"✓", "authenticity_token"=>"RqHp0OzQMM9DtVeP5SwlLS6_r4-ePfvWBXeevP3lo6Scf5xfsTc7QAF9U6oDixwJ9qnuBx2UpnHrG7a5jCB7Kg", "back_url"=>"/projects/test-2/dmsf?folder_id=1", "c"=>["title", "size", "modified", "version", "workflow", "author"], "ids"=>["file-1"]}
  Current user: admin (id=1)
  Rendering plugins/redmine_dmsf/app/views/dmsf_context_menus/dmsf.html.erb
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_approval_workflow.html.erb (5.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_file.html.erb (14.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/dmsf.html.erb (20.9ms)
Completed 200 OK in 36ms (Views: 25.3ms | ActiveRecord: 3.1ms)
Started OPTIONS "/dmsf/webdav/[test-2]/testordner/" for 192.168.126.1 at 2022-01-05 09:50:55 +0100
Processing WebDAV request: /dmsf/webdav/[test-2]/testordner/ (for 192.168.126.1 at 2022-01-05 09:50:55 +0100) [OPTIONS]
Completed in: 6 ms | 401 [http://redmine.example.com/dmsf/webdav/[test-2]/testordner/]
Started GET "/projects/dmsf/context_menu?folder_id=1&utf8=%E2%9C%93&authenticity_token=RqHp0OzQMM9DtVeP5SwlLS6_r4-ePfvWBXeevP3lo6Scf5xfsTc7QAF9U6oDixwJ9qnuBx2UpnHrG7a5jCB7Kg&back_url=%2Fprojects%2Ftest-2%2Fdmsf%3Ffolder_id%3D1&c%5B%5D=title&c%5B%5D=size&c%5B%5D=modified&c%5B%5D=version&c%5B%5D=workflow&c%5B%5D=author&ids%5B%5D=file-1" for 192.168.126.1 at 2022-01-05 09:56:27 +0100
Processing by DmsfContextMenusController#dmsf as */*
  Parameters: {"folder_id"=>"1", "utf8"=>"✓", "authenticity_token"=>"RqHp0OzQMM9DtVeP5SwlLS6_r4-ePfvWBXeevP3lo6Scf5xfsTc7QAF9U6oDixwJ9qnuBx2UpnHrG7a5jCB7Kg", "back_url"=>"/projects/test-2/dmsf?folder_id=1", "c"=>["title", "size", "modified", "version", "workflow", "author"], "ids"=>["file-1"]}
  Current user: admin (id=1)
  Rendering plugins/redmine_dmsf/app/views/dmsf_context_menus/dmsf.html.erb
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_approval_workflow.html.erb (3.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_file.html.erb (5.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/dmsf.html.erb (5.3ms)
Completed 200 OK in 44ms (Views: 3.7ms | ActiveRecord: 25.8ms)
Started OPTIONS "/dmsf/webdav/[test-2]/testordner/" for 192.168.126.1 at 2022-01-05 09:56:35 +0100
Processing WebDAV request: /dmsf/webdav/[test-2]/testordner/ (for 192.168.126.1 at 2022-01-05 09:56:35 +0100) [OPTIONS]
Completed in: 4 ms | 401 [http://redmine.example.com/dmsf/webdav/[test-2]/testordner/]

5. what does it mean?
6. I tried both
7. yes just standard basic redmine login. 

best regards

**Comment by picman** [comment]
> Completed in: 4 ms | 401 [http://redmine.example.com/dmsf/webdav/[test-2]/testordner/]

MS Office doesn't support basic authentication via HTTP. You have to switch to HTTPS first.

**Comment by Thommi1969** [comment]
okay, in my other VM with https is now working. THX !!!
