### ISSUE TITLE
is there the posibility to add extra approvers?

### ISSUE THREAD

**Issue by Mdiaz-PMO** [danmunn/redmine_dmsf#1322]
Hey, I was wondering if there is any  possibility to add extra approvers, once an approval work flow has been started.

thanks!

**Comment by picman** [comment]
No, it's not. You have to create a new workflow or to modify the existing one with new approvers, then add a new document's revision and assign the new/modified workflow again

**Comment by Mdiaz-PMO** [comment]
thanks
