### ISSUE TITLE
sent notice to members while objects be changed in DMS

### ISSUE THREAD

**Issue by sanpichen** [danmunn/redmine_dmsf#1324]
How can the admin or owner specify a number of recipients as a consistent-property of the DMS's folders ,no matter updated or added new files in the willing DMS folders, Redmine will sent notice to the recipients automatically?
It would be efficient to our daily office works.

under version :
Redmine 4.1.1.stable ; DMSF 2.4.5
<img width="712" alt="微信图片_20220114085541" src="https://user-images.githubusercontent.com/38068938/149445725-cc263d9b-644d-4ca7-a6c6-83129f388898.png">

**Comment by mmundi72** [comment]
Feature Request #557 is open since 2016 as it would word the same way as with tickets / issues. In my opinion the best solution.

**Comment by picman** [comment]
Duplicates #557.

**Comment by picman** [comment]
There is no such option. Notifications are sent to all project's members.
