### ISSUE TITLE
Starting error Redmine "4.2.3" with plugin DMSF "2.4.11" and plugin Easy Gantt

### ISSUE THREAD

**Issue by merouan-khouttoul** [danmunn/redmine_dmsf#1325]
Hi,

System parameter :
- Redmine version 4.2.3
- Redmine DMSF version 2.4.11
- Easy gantt free version 1.13  "https://www.easyredmine.com/redmine-gantt-plugin"
- Ruby version 2.6.6-p146 (2020-03-31) [x86_64-linux]
- Rails version 5.2.6

It's impossible to starting redmine with plugin DMSF and plugin Easy gantt !
Here are the error logs : 
######################################################

- exec gosu redmine:1000 rails server -b 0.0.0.0
- Booting WEBrick
- Rails 5.2.6 application starting in production on http://0.0.0.0:3000
- Run `rails server -h` for more startup options
/opt/redmine/plugins/redmine_ckeditor/init.rb:22: warning: constant Loofah::HTML5::WhiteList is deprecated
Exiting
Traceback (most recent call last):
	71: from bin/rails:4:in `<main>'
	70: from bin/rails:4:in `require'
	69: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/commands.rb:18:in `<top (required)>'
	68: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/command.rb:46:in `invoke'
	67: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/command/base.rb:69:in `perform'
	66: from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	65: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	64: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	63: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/commands/server/server_command.rb:142:in `perform'
	62: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/commands/server/server_command.rb:142:in `tap'
	61: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	60: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/commands/server/server_command.rb:53:in `start'
	59: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
	58: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
	57: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
	56: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	55: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/commands/server/server_command.rb:27:in `app'
	54: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	53: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	52: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	51: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	50: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	49: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	48: from config.ru:3:in `block in <main>'
	47: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
	46: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
	45: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
	44: from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	43: from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	42: from /opt/redmine/config/environment.rb:15:in `<top (required)>'
	41: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/application.rb:361:in `initialize!'
	40: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/initializable.rb:60:in `run_initializers'
	39: from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	38: from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	37: from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	36: from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
	35: from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
	34: from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	33: from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	32: from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	31: from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	30: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block in run_initializers'
	29: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
	28: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `instance_exec'
	27: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	26: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/application/finisher.rb:69:in `each'
	25: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/engine.rb:356:in `eager_load!'
	24: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/engine.rb:475:in `eager_load!'
	23: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/engine.rb:475:in `each'
	22: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/engine.rb:477:in `block in eager_load!'
	21: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/engine.rb:477:in `each'
	20: from /usr/local/bundle/gems/railties-5.2.6/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
	19: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:246:in `require_dependency'
	18: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:334:in `depend_on'
	17: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:356:in `require_or_load'
	16: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `load_interlock'
	15: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:13:in `loading'
	14: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	13: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	12: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	11: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:378:in `block in require_or_load'
	10: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
	 9: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
	 8: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
	 7: from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	 6: from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	 5: from /opt/redmine/plugins/redmine_dmsf/app/models/dmsf_lock.rb:24:in `<top (required)>'
	 4: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
	 3: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
	 2: from /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
	 1: from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': No such file to load -- simple_enum.rb (LoadError)

######################################################

Yet, plugin easy gantt starts correctly without the DMSF plugin.

Information : The Gemfile "redmine_dmsf/Gemfile" contains configuration about plugin easy gantt.
Is this normal ?

Can you help me on the subject ?

Thank you in advance for your answer.

**Comment by picman** [comment]
Duplicates #1318.
