### ISSUE TITLE
Where are files uploaded to DMS stored?

### ISSUE THREAD

**Issue by luckygg** [danmunn/redmine_dmsf#1327]
Hello all.
I need your help seriously. 😢

- Environments
Synology DSM 6.2.4-25556 Update 3
Docker 20.10.3-0554
Redmine 3.3.6-0051 update to 3.4.13-0057
DMSF Plugin: v1.6.0, 1.6.2
phpMyAdmin 4.9.7-0191
MariaDB 10.3.29-0070
PHP 7.3.24-0010

- Symptoms
I upgraded Redmine v3.3.6-0051 to 3.4.13-0057, then it had a problem.
I reinstalled Redmine and DMSF plugin as below procedure.

※ I'm using Synology's Hyper backup feature, all files (including subpaths) in 'docker' were backed up.

1. Reinstall Redmine
2. Restore 'docker/redmine/files'
3. Install DMSF Plugin v1.6.0
4. Import phpMyAdmin db file
5. Restart Redmine

After restoring Redmine, the list of DMS files is fine.
![image](https://user-images.githubusercontent.com/17895255/150291878-3d8cc656-b352-41c9-822c-ed37d3af4abb.png)

But there is a 404 error when I click the item.
![image](https://user-images.githubusercontent.com/17895255/150292045-a003e1d3-1a8e-43d7-8f9b-801985b9eb52.png)
The message is "_The page you requested has been deleted or moved_".

Here is the log message when I clicked the item.
![image](https://user-images.githubusercontent.com/17895255/150292324-02f1bcb3-2bca-41a6-b338-7c36465c3e91.png)

If I enter the path, there is no same name file.

- Questions
1) Where are files uploaded to DMS stored?
2) Are there any precautions when restoring DMSF?

Could you please advise for me...? 😢 

Thank you!

**Comment by picman** [comment]
Check the plugin's settings. There is an option **File Storage Directory**. Check whether the path corresponds with the physical location of your files in the file system. The doubled 'redmine' looks suspicious _/home/redmine.redmine/files/dmsf_.

**Comment by luckygg** [comment]
@picman
Thank you for your quick reply 😃 

I found that the default directory is _/home/redmine/redmine_ (Synology Docker's Redmine).
(I installed Redmine with default value)
If this is correct, is it correct that DMS data is stored in _/home/redmine/redmine/files/dmsf_?

**Comment by picman** [comment]
I don't know. You must know where are the files located and set the plugin's option accordingly.

**Comment by luckygg** [comment]
Okay. I understand that what you said. This is my last question... 😃 
Is there a way to find the plugin's option values in my phpMyAdmin DB file or dmsf plugin files?

**Comment by picman** [comment]
```sql
select value from settings where name = 'plugin_redmine_dmsf';
```

**Comment by luckygg** [comment]
thank you for your help
