### ISSUE TITLE
Problem moving a folder with locked files.

### ISSUE THREAD

**Issue by hibit-2709** [danmunn/redmine_dmsf#1329]
If there is a locked file in the folder, then when you move the folder to another project, there is a problem with accessing such a file.
In the database, the project ID for such a file does not change.
Locking a file should probably prevent its content from changing, not its location.

**Comment by picman** [comment]
What version of DMSF do you use? I think that this problem has already been fixed. At lease in the last released version it works fine.

**Comment by hibit-2709** [comment]
DMSF v.2.4.11.

**Comment by picman** [comment]
You are right. I didn't test it properly. Fixed.
