### ISSUE TITLE
Trouble with dmsff macro

### ISSUE THREAD

**Issue by hibit-2709** [danmunn/redmine_dmsf#1330]
Trouble with dmsff macro If we do not insert the folder ID in the {{dmsff()}} macro, we get the '**Documents**' link on the screen. If such a macros appears in a project where the DMS module is inactive, an error will appear. It seems that it would be more correct if the user saw the inscription **{{dmsff()}}**.

**Comment by picman** [comment]
I've changed it so that if the user is not allowed to view DMS folders or the module DMS is off the following error message is displayed.

`Error executing the dmsff macro (You are not authorized to access this page.)`

**Comment by hibit-2709** [comment]
Haste is a bad adviser. I think the solution is ok.
