### ISSUE TITLE
Recursive filtering in the topmost DMS menu

### ISSUE THREAD

**Issue by majkinetor** [danmunn/redmine_dmsf#1331]
I was surprised that topmost DMS menu doesn't support recursive filtering:

![image](https://user-images.githubusercontent.com/85767/150638621-ee9f1e15-b4dd-48f7-8b0e-26631e99b6f3.png)

![image](https://user-images.githubusercontent.com/85767/150638624-fef17cbf-af37-4b7e-83f7-d57dd995295c.png)

Without this option its hard for me to see the point of this menu - it contains DMS projects without any DMS file and you can't filter out things (for example, don't show any empty DMS projects, show me files where I am author across all my projects  etc)

**Comment by picman** [comment]
It duplicates #1247.
