### ISSUE TITLE
reporting old simple_enum issue on 2.4.11

### ISSUE THREAD

**Issue by sbh1fr** [danmunn/redmine_dmsf#1332]
hi, i was migrating redmine on a new server and installed few plugins including dmfs
but got this error

App 13073 output:   Rendering plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base
App 13073 output:   Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_main.html.erb (8.4ms)
App 13073 output:   Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.4ms)
App 13073 output:   Rendered plugins/redmine_dmsf/app/views/dmsf/_description.html.erb (0.1ms)
App 13073 output:   Rendered queries/_filters.html.erb (6.2ms)
App 13073 output:   Rendered queries/_columns.html.erb (1.5ms)
App 13073 output:   Rendered queries/_query_form.html.erb (13.3ms)
App 13073 output:   Rendered plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb (37.8ms)
App 13073 output:   Rendered plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb (45.7ms)
App 13073 output:   Rendered plugins/redmine_dmsf/app/views/dmsf/_main.html.erb (76.2ms)
App 13073 output:   Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (78.0ms)
App 13073 output: Completed 500 Internal Server Error in 233ms (ActiveRecord: 46.8ms)
App 13073 output:
App 13073 output: LoadError (cannot load such file -- simple_enum):
App 13073 output:
App 13073 output: plugins/redmine_dmsf/app/models/dmsf_lock.rb:24:in `<top (required)>'
App 13073 output: plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:36:in `lock'
App 13073 output: plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:28:in `locked?'
App 13073 output: plugins/redmine_dmsf/app/helpers/dmsf_queries_helper.rb:43:in `column_value'
App 13073 output: app/helpers/queries_helper.rb:236:in `column_content'
App 13073 output: plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb:44:in `block (2 levels) in _plugins_redmine_dmsf_app_views_dmsf__query_rows_erb__3087354347195777062_70060198317120'
App 13073 output: plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb:43:in `each'
App 13073 output: plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb:43:in `block in _plugins_redmine_dmsf_app_views_dmsf__query_rows_erb__3087354347195777062_70060198317120'
App 13073 output: plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb:28:in `each'
App 13073 output: plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb:28:in `_plugins_redmine_dmsf_app_views_dmsf__query_rows_erb__3087354347195777062_70060198317120'
App 13073 output: plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb:49:in `block in _plugins_redmine_dmsf_app_views_dmsf__query_list_html_erb___1431732616739589951_70060198227040'
App 13073 output: plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb:26:in `_plugins_redmine_dmsf_app_views_dmsf__query_list_html_erb___1431732616739589951_70060198227040'
App 13073 output: plugins/redmine_dmsf/app/views/dmsf/_main.html.erb:74:in `_plugins_redmine_dmsf_app_views_dmsf__main_html_erb__1075400766387613047_70060197775720'
App 13073 output: plugins/redmine_dmsf/app/views/dmsf/show.html.erb:25:in `_plugins_redmine_dmsf_app_views_dmsf_show_html_erb___3690068966346731322_70060186304000'
App 13073 output: plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:95:in `block (2 levels) in show'
App 13073 output: plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:91:in `show'
App 13073 output: lib/redmine/sudo_mode.rb:61:in `sudo_mode'

after some time trying to investigate and fix the issue i uninstalled easy_gantt and somehow it fixed the problem

**Comment by picman** [comment]
Duplicates #1318.
