### ISSUE TITLE
Memory problem in 'My page' with 'Open aprovals' option

### ISSUE THREAD

**Issue by jlsblasco** [danmunn/redmine_dmsf#1333]
Hi, 
I have a 1.6.1 DMSF version in 3.4.9.stable Redmine.
When include in 'Mi page' the 'Open aprovals' options, the system delay more time.
The log say:
 Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb **(3128.6ms)**
 I have more than 150 lines of this type. I have files in more than 1000 projects.
In the last line:
Rendered plugins/redmine_dmsf/app/views/my/blocks/_open_approvals.html.erb **(91063.2ms)**
The memory of the machine increase more than 4 GB for this operation, and when the memory machine is full (16 GB), the process abort an I need to restart ruby redmine process.
If the user is inside a proyect and send a query inside the DMS module, the time its:
Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (29.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (237.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (594.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (401.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (657.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (533.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (795.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (30.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (26.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (20.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (8.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (63.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dmsf_rows.erb (2259.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_tree_view.erb (2263.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (3.0ms)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (1.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (2305.0ms)

How I can reduce the time of process and the memory use for 'My Page' option.

Regards

**Comment by picman** [comment]
The command button causing the slow down has been replaced with context menu. It's corresponding to Redmine's standard and it's much faster, as the menu is created after it's needed.

**Comment by jlsblasco** [comment]
Hi, Thank you for you support.
I don't undestand 'has been replaced with context menu'. Now, we use the 'My page' option.
![image](https://user-images.githubusercontent.com/50949839/151946980-b4163e7b-268e-4a08-bd58-49db8d415dd4.png)

The other method its inside the proyects and use de DMS option, but I have more than 1000 projects and its not possible to use it.
![image](https://user-images.githubusercontent.com/50949839/151947463-b3e2592c-26b0-41ea-aa72-bf6137cd98c0.png)

 
How I can use the 'context menu' ?.

Thank you in advance,

**Comment by picman** [comment]
![image](https://user-images.githubusercontent.com/779003/151948320-803a2989-a9bd-4e04-b725-d90f01d2789c.png)

**Comment by picman** [comment]
I've only modified _**MyPage->Open approvals**_. It will be available in v2.4.12. To test it, you have to use the branch _redmine_notifications_.

**Comment by jlsblasco** [comment]
Thank you.
Now I have a 1.6.1 DMS version over 3.4.9 Redmine version.
When the 2.4.12 will be available, It's possible migrate from my versions.?
Regards

**Comment by picman** [comment]
v1.6.1 is pretty obsolete. DMSF 2.4.12 requires Redmine >= 4.2.
