### ISSUE TITLE
xapian_indexer.rb -> error with additionals

### ISSUE THREAD

**Issue by ephysthos** [danmunn/redmine_dmsf#1335]
Hello, when i execute ruby "redmine/plugins/redmine_dmsf/extra/xapian_indexer.rb" is got : 

[!] There was an error while loading `additionals.gemspec`: uninitialized constant Additionals::PluginVersion::VERSION. Bundler cannot continue.

Is something to do specific with additionals plugin in order to work ?

**Comment by ephysthos** [comment]
i have to remove the require and indicate physically the version in additionals for supporting it.

**Comment by picman** [comment]
Duplicates #1305.

**Comment by picman** [comment]
It has just been fixed in Additionals.
