### ISSUE TITLE
move/copy folder from project1 to project2

### ISSUE THREAD

**Issue by Wbordeau** [danmunn/redmine_dmsf#1338]
Hi everyone,
After upgrade to Redmine 4.2.3,
I am no longer able to move or copy folders from a project to another one. In the scrolling menu, only folders from the project 1 are available even with my administrator right. Can you already heard about it and/or help me please ?
I have installed the 2.4.12 version of 17 December 2021
Thanks in advance for your response

William

![image](https://user-images.githubusercontent.com/84776982/153422883-6a983bf8-5af5-4224-934a-e9c864585735.png)

**Comment by picman** [comment]
The target folder pick list contains only folders from the project which is selected in the project pick list. You can't change the project in the project pick list?

**Comment by Wbordeau** [comment]
Yes i have changed the project in the project pick list but the only folders shown by the list is the folder in the source project

**Comment by Wbordeau** [comment]
Sorry, my explication was clear or not ?! I have Folders "M" in project 1 and i can't copy this folders into Folders "F" which belong to project 2

**Comment by picman** [comment]
Your explanation is clear. Though, I'm not able to reproduce the problem.

**Comment by Wbordeau** [comment]
I have an explanation. If i want to move a file from subfolder A to subfolder B i have to move to "root" folder B first and after to move it to subfolder B. Is it right ? that's why there in any subfolders B in the pick list

**Comment by picman** [comment]
I see the problem now. I will fix it.

**Comment by Wbordeau** [comment]
Everything is alright now. Thanks
