### ISSUE TITLE
Not show action menu to unlock folder

### ISSUE THREAD

**Issue by jaramosc2016** [danmunn/redmine_dmsf#1339]
Hi,
We recently upgraded redmine from 4.1.3 to 4.2.3, redmine_dmsf plugin 2.4.5 to 2.4.11, and mariadb 10.3 to 10.6.7 in docker containers. Everything works fine, but now we can't unlock folders because the action menu doesn't show anything. 
![2022-02-21 16_00_16-emptyMenu](https://user-images.githubusercontent.com/100138705/154980614-8beb6a5a-6895-405d-808c-9386992631e7.png)

Everything works fine, but now we can't unlock folders because the actions menu doesn't show anything.
the user who locked the folder is the same user who is now trying to unlock. The log errors show these lines:
I, [2022-02-21T13:53:14.371776 #1]  INFO -- : Started GET "/projects/dmsf/context_menu?utf8=%E2%9C%93&authenticity_token=xxxxxxxxxxxxxxxx%2FhyQFKyW%2Fv3XYNdF9iNAo9gxDhos5qZYxgiC0K0kNOwtc%2F71kVQy1tZsPe7LfU0LxeadmQ%3D%3D&back_url=%2Fprojects%2Fgexpot%2Fdmsf&c%5B%5D=title&c%5B%5D=size&c%5B%5D=modified&c%5B%5D=version&c%5B%5D=workflow&c%5B%5D=author&ids%5B%5D=folder-24" for 82.xxx.xxx.xxx at 2022-02-21 13:53:14 +0000
I, [2022-02-21T13:53:14.373257 #1]  INFO -- : Processing by DmsfContextMenusController#dmsf as */*
I, [2022-02-21T13:53:14.373338 #1]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"xxxxxxxxxxxxxxxx/hyQFKyW/v3XYNdF9iNAo9gxDhos5qZYxgiC0K0kNOwtc/71kVQy1tZsPe7LfU0LxeadmQ==", "back_url"=>"/projects/gexpot/dmsf", "c"=>["title", "size", "modified", "version", "workflow", "author"], "ids"=>["folder-24"]}
I, [2022-02-21T13:53:14.379874 #1]  INFO -- :   Current user: xxxxxxx (id=35)
I, [2022-02-21T13:53:14.391861 #1]  INFO -- : Completed 500 Internal Server Error in 18ms (ActiveRecord: 4.4ms)
F, [2022-02-21T13:53:14.392874 #1] FATAL -- :
F, [2022-02-21T13:53:14.393013 #1] FATAL -- : NoMethodError (undefined method `owner' for #<DmsfLock:0x00007f403cdb9600>):
F, [2022-02-21T13:53:14.393029 #1] FATAL -- :
F, [2022-02-21T13:53:14.393042 #1] FATAL -- : plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:99:in `block (2 levels) in locked_for_user?'
plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:96:in `block in locked_for_user?'
plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:93:in `each'
plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:93:in `locked_for_user?'
plugins/redmine_dmsf/app/controllers/dmsf_context_menus_controller.rb:42:in `dmsf'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:56:in `call'

Environment:
  Redmine version                4.2.3.stable
  Ruby version                   2.7.5-p203 (2021-11-24) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.14.1
  Mercurial                      5.6.1
  Bazaar                         3.1.0
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   2.4.11

Thank you for your helping,
Regards.

**Comment by picman** [comment]
It seems to me that you haven't run plugin's migration task, have you?

`bundle exec rake redmine:plugins:migrate RAILS_ENV=production`

**Comment by jaramosc2016** [comment]
Hi picman,
Thanks for answer quickly, we run these commands:
root@19ec6ec60429:/usr/src/redmine# apt install build-essential
root@19ec6ec60429:/usr/src/redmine# cp -r /tmp/redmine_dmsf/ ./plugins
root@19ec6ec60429:/usr/src/redmine# sed -i -e 's/config.eager_load = true/config.eager_load = false/g' config/environments/production.rb
root@19ec6ec60429:/usr/src/redmine# sed -i -e 's/Tacho/Papelera/g' plugins/redmine_dmsf/config/locales/es.yml
root@19ec6ec60429:/usr/src/redmine# sed -i -e 's/ducument/document/g' plugins/redmine_dmsf/config/locales/es.yml
root@19ec6ec60429:/usr/src/redmine# bundle config unset deployment
root@19ec6ec60429:/usr/src/redmine# bundle install --without development test
root@19ec6ec60429:/usr/src/redmine# RAILS_ENV=production bundle exec rake db:migrate
root@19ec6ec60429:/usr/src/redmine# RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf
root@19ec6ec60429:/usr/src/redmine# chown -R redmine:redmine plugins/redmine_dmsf

Among them is the command you indicate, but I run again this RAILS_ENV=production bundle exec rake redmine:plugins:migrate and now we can see the actions menu, but when we try to lock a folder, it gives us another error:

xxx.xxx.xxx.xxx - - [22/Feb/2022:09:27:15 UTC] "GET /projects/dmsf/context_menu?utf8=%E2%9C%93&authenticity_token=xxxxxxxxxxxxxx%2Bb7463hJ43jx%2BPpim5%2FEy6y5ZUIkL0iM9kTYoULLzyD2TInuuk6vugtuCgxuBJA%3D%3D&back_url=%2Fprojects%2Fgexpot%2Fdmsf&c%5B%5D=title&c%5B%5D=size&c%5B%5D=modified&c%5B%5D=version&c%5B%5D=workflow&c%5B%5D=author&ids%5B%5D=folder-24 HTTP/1.1" 200 1814
https://MYURL/projects/gexpot/dmsf -> /projects/dmsf/context_menu?utf8=%E2%9C%93&authenticity_token=xxxxxxxxxxxxxx%2Bb7463hJ43jx%2BPpim5%2FEy6y5ZUIkL0iM9kTYoULLzyD2TInuuk6vugtuCgxuBJA%3D%3D&back_url=%2Fprojects%2Fgexpot%2Fdmsf&c%5B%5D=title&c%5B%5D=size&c%5B%5D=modified&c%5B%5D=version&c%5B%5D=workflow&c%5B%5D=author&ids%5B%5D=folder-24
xxx.xxx.xxx.xxx - - [22/Feb/2022:09:27:19 UTC] "GET /projects/gexpot/dmsf/lock?back_url=%2Fprojects%2Fgexpot%2Fdmsf&folder_id=24 HTTP/1.1" 500 648
https://MYURL/projects/gexpot/dmsf -> /projects/gexpot/dmsf/lock?back_url=%2Fprojects%2Fgexpot%2Fdmsf&folder_id=24

![2022-02-22 10_30_10-Redmine 500 error](https://user-images.githubusercontent.com/100138705/155103439-be308175-b21b-4cc0-86ac-d5567a601ef0.png)

Note: we run these commands to improve translation
root@19ec6ec60429:/usr/src/redmine# sed -i -e 's/Tacho/Papelera/g' plugins/redmine_dmsf/config/locales/es.yml
root@19ec6ec60429:/usr/src/redmine# sed -i -e 's/ducument/document/g' plugins/redmine_dmsf/config/locales/es.yml

Regads.

**Comment by picman** [comment]
Post related errors from `production.log`. Web server log doesn't say much.

**Comment by picman** [comment]
Without information from the production.log I can hardly be any of help. In the original post you have got information from production.log. Where did you get them?

**Comment by jaramosc2016** [comment]
Hi,
I understand, in containers all stderr of a container can be redirected to the host's stdout, but I can't differentiate which line was written by what process.

I have tried again to lock a folder to capture the logs that I reproduce 

I, [2022-02-22T15:23:09.850019 #1]  INFO -- : Started GET "/projects/gexpot/dmsf" for xxx.xxx.xxx.xxx at 2022-02-22 15:23:09 +0000
I, [2022-02-22T15:23:09.851220 #1]  INFO -- : Processing by DmsfController#show as HTML
I, [2022-02-22T15:23:09.851258 #1]  INFO -- :   Parameters: {"id"=>"gexpot"}
I, [2022-02-22T15:23:09.860943 #1]  INFO -- :   Current user: jaramosc (id=89)
I, [2022-02-22T15:23:09.876637 #1]  INFO -- :   Rendering plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base
I, [2022-02-22T15:23:09.878206 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_context_menus/_main.html.erb (0.7ms)
I, [2022-02-22T15:23:09.878618 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.1ms)
I, [2022-02-22T15:23:09.878741 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_description.html.erb (0.0ms)
I, [2022-02-22T15:23:09.883430 #1]  INFO -- :   Rendered queries/_filters.html.erb (4.1ms)
I, [2022-02-22T15:23:09.885260 #1]  INFO -- :   Rendered queries/_columns.html.erb (0.6ms)
I, [2022-02-22T15:23:09.885923 #1]  INFO -- :   Rendered queries/_query_form.html.erb (7.0ms)
I, [2022-02-22T15:23:09.929905 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_query_rows.erb (41.1ms)
I, [2022-02-22T15:23:09.930604 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_query_list.html.erb (44.2ms)
I, [2022-02-22T15:23:09.933193 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_sidebar.html.erb (1.5ms)
I, [2022-02-22T15:23:09.933260 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_main.html.erb (56.4ms)
I, [2022-02-22T15:23:09.933427 #1]  INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (56.7ms)
I, [2022-02-22T15:23:09.953576 #1]  INFO -- : Completed 200 OK in 102ms (Views: 62.3ms | ActiveRecord: 22.6ms)
I, [2022-02-22T15:23:15.113068 #1]  INFO -- : Started GET "/projects/dmsf/context_menu?utf8=%E2%9C%93&authenticity_token=Q%2FxxxxxxxxxA2BoZAh1RRqwjTUxmJF1i8HkUqH0CL45W8kSm2jNbazavQoPn1QTKk%2BqJW245bmkaItUTq29w%3D%3D&back_url=%2Fprojects%2Fgexpot%2Fdmsf&c%5B%5D=title&c%5B%5D=size&c%5B%5D=modified&c%5B%5D=version&c%5B%5D=workflow&c%5B%5D=author&ids%5B%5D=folder-24" for xxx.xxx.xxx.xxx at 2022-02-22 15:23:15 +0000
I, [2022-02-22T15:23:15.115265 #1]  INFO -- : Processing by DmsfContextMenusController#dmsf as */*
I, [2022-02-22T15:23:15.115358 #1]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"Q/9r59JEjkwshA2BoZAh1RRqwjTUxmJF1i8HkUqH0CL45W8kSm2jNbazavQoPn1QTKk+qJW245bmkaItUTq29w==", "back_url"=>"/projects/gexpot/dmsf", "c"=>["title", "size", "modified", "version", "workflow", "author"], "ids"=>["folder-24"]}
I, [2022-02-22T15:23:15.123633 #1]  INFO -- :   Current user: jaramosc (id=89)
xxx.xxx.xxx.xxx - - [22/Feb/2022:15:23:15 UTC] "GET /projects/dmsf/context_menu?utf8=%E2%9C%93&authenticity_token=Q%2FxxxxxxxxxA2BoZAh1RRqwjTUxmJF1i8HkUqH0CL45W8kSm2jNbazavQoPn1QTKk%2BqJW245bmkaItUTq29w%3D%3D&back_url=%2Fprojects%2Fgexpot%2Fdmsf&c%5B%5D=title&c%5B%5D=size&c%5B%5D=modified&c%5B%5D=version&c%5B%5D=workflow&c%5B%5D=author&ids%5B%5D=folder-24 HTTP/1.1" 200 1814
https://redmine-ots-ja.egov-cities-apps.com/projects/gexpot/dmsf -> /projects/dmsf/context_menu?utf8=%E2%9C%93&authenticity_token=Q%2FxxxxxxxxxA2BoZAh1RRqwjTUxmJF1i8HkUqH0CL45W8kSm2jNbazavQoPn1QTKk%2BqJW245bmkaItUTq29w%3D%3D&back_url=%2Fprojects%2Fgexpot%2Fdmsf&c%5B%5D=title&c%5B%5D=size&c%5B%5D=modified&c%5B%5D=version&c%5B%5D=workflow&c%5B%5D=author&ids%5B%5D=folder-24
xxx.xxx.xxx.xxx - - [22/Feb/2022:15:23:19 UTC] "GET /projects/gexpot/dmsf/lock?back_url=%2Fprojects%2Fgexpot%2Fdmsf&folder_id=24 HTTP/1.1" 500 648
https://redmine-ots-ja.egov-cities-apps.com/projects/gexpot/dmsf -> /projects/gexpot/dmsf/lock?back_url=%2Fprojects%2Fgexpot%2Fdmsf&folder_id=24


Regards.

**Comment by picman** [comment]
Hm, there are no usefull information about the error in your error output. I believe that even in a docker container you can configure a logger and then get information related to the error.

_config/additional_environment.rb_

```ruby
config.logger = Logger.new("#{Rails.root}/log/#{Rails.env}.log", 'daily')
config.log_level = :info
```

=> _log/production.log_

**Comment by jaramosc2016** [comment]
Hi,
I have modified the config/additional_environment.rb file so that it generates the production log and I have restarted the container to apply changes. I have tested locking a folder and it worked fine, so I think the problem was that I needed a reboot after running the plugin's migration task.

Thanks a lot, I am so grateful for your patience and dedication.
regards.
