### ISSUE TITLE
Question: MS Office 2021

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1341]
Our IT departments plans the roll-out of MS Office 2021 and is asking to check if any applications do have compatibility issues with this Office version.
Unfortunately I cannot check it at the moment by myself. 

Hence my question: do you expect any issues with DMSF + MS Office 2021? 

Thanks for your help.

**Comment by picman** [comment]
I don't but I also cannot test it.

**Comment by mmundi72** [comment]
OK, we will test that together with Redmine 5 as soon as I get internally an Office 2021 copy.
