### ISSUE TITLE
Migrating from Redmine 3.3.1 / DMSF 1.5.8

### ISSUE THREAD

**Issue by isoboroff** [danmunn/redmine_dmsf#1342]
Hi, I am migrating a Redmine install which is coming from some pretty ancient versions -- 3.3.1 and DMSF 1.5.8.  I find that the DMSF migration task generates lots of file-not-found complaints and tries to create a number of directories in the wrong places.  I am starting with a fresh Redmine install, importing the old database from a dump, and then installing DMSF.

Can you help me navigate the code that does the migrations, so I can try to step through it and nurse it into accepting my data?  Alternatively, if there's another way I should try to migrate, I can try that.

Thanks in advance.

**Comment by picman** [comment]
The files are moved to a new structure during the migration. The migration is in `db/migrate/20170422104901_migrate_documents.rb`. Please see the discussion under #1130.

**Comment by isoboroff** [comment]
Thank you!  If I get a chance I will try to turn those issues into a documentation file, since the problem and solution might be hard for others to find.
