### ISSUE TITLE
Need support Redmine 5

### ISSUE THREAD

**Issue by ericbrun-73** [danmunn/redmine_dmsf#1344]
Hi, 

Two days ago, Redmine 5.0.0 was released. 
Have you planned to support Redmine 5 soon ?

Thanks for your work !

Cheers 

Eric

**Comment by picman** [comment]
Yes, Redmine 5 will be supported. The devel branch _devel-2.4.12_ should be compatible with Redmine 5. You can try it. There are no open issues for the next DMSF version. I will release it after I finish testing at the end of April or beginning of May.

Related to #1340

**Comment by ericbrun-73** [comment]
Very good news !
I will try the devel branch soon.

Thanks a lot Karel !
