### ISSUE TITLE
Conflict with RedmineUP invoice plugin

### ISSUE THREAD

**Issue by uart-aplex** [danmunn/redmine_dmsf#1345]
If installed with the redimineup invoice plugin, it will got "internal error" web page when Start or Approve DMSF workflow, And it will not generate any records in redmine's log.

https://www.redmineup.com/pages/plugins/invoices

**Comment by picman** [comment]
I've downloaded redmine_contacts_invoices and it's dependent plugin redmine_contacts and I cannot get over the following problem in migration task.
```
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
undefined method `acts_as_priceable' for #<Class:0x0000559f79434090>
redmine/plugins/redmine_contacts_invoices/app/models/invoice_line.rb:36
```
So, sorry, but I cannot test it.
If an internal errror is generated, there must be something either in the Redmine's production log or in the web server's error log. Please check it again.

**Comment by uart-aplex** [comment]
Could you try following command to install invoice plugin?

_bundle install --without development test --no-deployment
bundle exec rake redmine:plugins NAME=redmine_contacts_invoices RAILS_ENV=production_

**Comment by picman** [comment]
The same result `act_as_priceable` is not defined.

**Comment by uart-aplex** [comment]
Strange, I clear the log file first before click Approve, and then Clicked Approve, there will be 500 internal error on redmine page, but the log file has no new record.
![image](https://user-images.githubusercontent.com/24597310/161221293-8b2c2b34-3dab-480c-9419-398d6a2b05b1.png)

**Comment by picman** [comment]
Something is obviously wrong in your environment...

**Comment by uart-aplex** [comment]
> Something is obviously wrong in your environment...

I have tested that if I removed the invoice plugin, then this problem is gone, and then I installed invoice again, this problem also happened again.

**Comment by picman** [comment]
Could you test it with devel-3.0.1 branch? I've made there some changes related to RedmineUp's plugins.

**Comment by uart-aplex** [comment]
It works well now.
![image](https://user-images.githubusercontent.com/24597310/169291053-fcd0dc83-b68a-4ab2-8b0c-a0f9a623d3bd.png)

**Comment by picman** [comment]
Perfect. Thanks for testing it.
