### ISSUE TITLE
Custom Fields not shown on folder level

### ISSUE THREAD

**Issue by fhaefemeier** [danmunn/redmine_dmsf#1348]
I defined a couple of custom fields to fill in additional informations. I can see the values on file level, but I don't see these values on folder level, if I put values in (during folder edit).

* Edit folder
<img width="929" alt="Bildschirmfoto 2022-04-15 um 22 23 45" src="https://user-images.githubusercontent.com/17227813/163628690-53b26985-b51e-422c-8cc9-228ce09152ad.png">
* View folder
<img width="579" alt="Bildschirmfoto 2022-04-15 um 22 21 42" src="https://user-images.githubusercontent.com/17227813/163628596-6a7b1726-0639-4771-a7ff-4aecca6da4c6.png">

Bug or feature?

## System Environment

Redmine: 4.2.5
DMSF: 2.4.11

**Comment by picman** [comment]
It is a feature. So far nobody has requested to see custom fields in a folder's view despite the fact that it sounds quite logical...

**Comment by picman** [comment]
![image](https://user-images.githubusercontent.com/779003/166925863-f00eb2cb-b419-4f32-b5d8-c4f23ce3da4e.png)

**Comment by picman** [comment]
I've done that similar way how the project's custom fields are presented.
