### ISSUE TITLE
QueryColumn - Error

### ISSUE THREAD

**Issue by blackhase** [danmunn/redmine_dmsf#1349]
Hello, 

i have a Problem with redmine 5.0.0. 
After plugin migrate exec, 
i get an error: 

` Error: The application encountered the following error: uninitialized constant QueryColumn (NameError)
App 4265 output:     /var/www/redmine/plugins/redmine_dmsf/app/models/dmsf_version_query_column.rb:23:in `<top (required)>'`

Ubuntu Server 22.04
Ruby 3.0
MSSQL 2014

Regards. 
Andi

**Comment by picman** [comment]
DMSF 3.0.0?

**Comment by blackhase** [comment]
Yes, 
I downloded today.

**Comment by picman** [comment]
Could you try to add `require 'query'` into _/var/www/redmine/plugins/redmine_dmsf/app/models/dmsf_version_query_column.rb_ so the file would look like follows? Please also post the exact command you run and a bit larger chunk of the output.
```ruby
require 'query'

class DmsfVersionQueryColumn < QueryColumn

  def value_object(object)
    DmsfFileRevision.version object.major_version, object.minor_version, object.patch_version
  end

end
```

**Comment by blackhase** [comment]
This works! 

Thank you.
