### ISSUE TITLE
OX throws error

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1351]
Hi there
I just tried to install DMSF 3.0.0 on a blank Bitnami Redmine installation (on a Mac). 
Bundle Install throws this error (no other plugins installed!):

Installing ox 2.14.11 with native extensions
**Gem::Ext::BuildError: ERROR: Failed to build gem native extension.**

    current directory: /opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/ox-2.14.11/ext/ox

/opt/bitnami/ruby/bin/ruby -I /opt/bitnami/ruby/lib/ruby/site_ruby/3.0.0 -r ./siteconf20220508-4057-s9ojlo.rb extconf.rb
>>>>> Creating Makefile for ruby version 3.0.4 on x86_64-linux <<<<<

checking for rb_time_timespec()... yes
checking for rb_struct_alloc_noinit()... yes
checking for rb_obj_encoding()... yes
checking for rb_ivar_foreach()... yes
checking for rb_ext_ractor_safe() in ruby.h... yes
checking for pthread_mutex_init()... yes
checking for rb_enc_interned_str()... yes
checking for rb_time_nano_new()... yes
checking for index()... yes
checking for ruby/st.h... yes
checking for sys/uio.h... yes
checking for struct tm.tm_gmtoff... yes
creating Makefile
extconf.rb:52:in ``': No such file or directory - make (Errno::ENOENT)
	from extconf.rb:52:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  **/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0-static/ox-2.14.11/mkmf.log**

extconf failed, exit code 1

Gem files will remain installed in /opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/ox-2.14.11 for inspection.
Results logged to /opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0-static/ox-2.14.11/gem_make.out

  /opt/bitnami/ruby/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:95:in `run'
  /opt/bitnami/ruby/lib/ruby/site_ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /opt/bitnami/ruby/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /opt/bitnami/ruby/lib/ruby/site_ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /opt/bitnami/ruby/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:164:in `build_extension'
  /opt/bitnami/ruby/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
  /opt/bitnami/ruby/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:195:in `each'
  /opt/bitnami/ruby/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:195:in `build_extensions'
  /opt/bitnami/ruby/lib/ruby/site_ruby/3.0.0/rubygems/installer.rb:853:in `build_extensions'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/source/rubygems.rb:204:in `install'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/installer/gem_installer.rb:54:in `install'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/installer/parallel_installer.rb:171:in `install_serially'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/installer/parallel_installer.rb:97:in `call'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/installer.rb:259:in `install_in_parallel'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/installer.rb:209:in `install'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/installer.rb:89:in `block in run'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/process_lock.rb:12:in `block in lock'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/process_lock.rb:9:in `open'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/process_lock.rb:9:in `lock'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/installer.rb:71:in `run'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/installer.rb:23:in `install'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/cli/install.rb:62:in `run'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/cli.rb:255:in `block in install'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/settings.rb:131:in `temporary'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/cli.rb:254:in `install'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/cli.rb:31:in `dispatch'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/cli.rb:25:in `start'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/exe/bundle:48:in `block in <top (required)>'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/exe/bundle:36:in `<top (required)>'
  /opt/bitnami/redmine/bin/bundle:113:in `load'
  /opt/bitnami/redmine/bin/bundle:113:in `<main>'

**An error occurred while installing ox (2.14.11), and Bundler cannot continue.**

In Gemfile:
  ox

------
attached is the mkmf.log file (as mentioned in the error)

Any idea what's wrong?

[mkmf.log](https://github.com/danmunn/redmine_dmsf/files/8646760/mkmf.log)

**Comment by picman** [comment]
From the output it seems that `make` command is missing in the system. In Linux I would solve it by installing these two packages:
``` shell
apt-get install make build-essentials
```
