### ISSUE TITLE
Cannot preview my doc

### ISSUE THREAD

**Issue by chengpeng321** [danmunn/redmine_dmsf#1353]
Cannot preview Microsoft Office(*.doc , *.docx, *.xls, *.xlsx, *.ppt, *.pptx)

**Comment by picman** [comment]
What do you mean with preview?

**Comment by chengpeng321** [comment]
> What do you mean with preview?

I want View office files on a web page

**Comment by picman** [comment]
Related to #1355.

**Comment by picman** [comment]
Done. If you click on an office document and LibreOffice is installed on the server, the document id displayed inline as PDF.
