### ISSUE TITLE
Redmine Configuration Page not working when DMSF is installed  together with RedmineUp resources plugin

### ISSUE THREAD

**Issue by Stsfr63** [danmunn/redmine_dmsf#1354]
The web server error.log will show something like

App 4555 output: Started GET "/settings" for 192.168.10.40 at 2022-05-12 14:19:14 +0200
App 4555 output: Processing by SettingsController#index as HTML
App 4555 output:   Current user: StefanS (id=5)
App 4555 output: Completed 500 Internal Server Error in 141ms (ActiveRecord: 125.1ms)
App 4555 output:
App 4555 output: SystemStackError (stack level too deep):
App 4555 output:
App 4555 output: plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:40:in `all'
App 4555 output: plugins/redmine_resources/lib/redmine_resources/patches/notifiable_patch.rb:37:in `all_with_resources'
App 4555 output: plugins/redmine_dmsf/lib/redmine_dmsf/patches/notifiable_patch.rb:40:in `all'

when calling the settings page for redmine.

===================================
Environment:
  Redmine version                4.2.5.stable.21566
  Ruby version                   2.5.8-p224 (2020-03-31) [x86_64-linux-gnu]
  Rails version                  5.2.8
 
  redmine_dmsf                   3.0.0
  redmine_resources              1.0.7
  
===================================

changing in notifiable_patch.rb

# Apply the patch
if Redmine::Plugin.installed?(:easy_extensions)
  RedmineExtensions::PatchManager.register_patch_to_be_first 'Redmine::Notifiable',
    'RedmineDmsf::Patches::NotifiablePatch', prepend: true, first: true
else
  Redmine::Notifiable.prepend RedmineDmsf::Patches::NotifiablePatch
end

to

# Apply the patch
#if Redmine::Plugin.installed?(:easy_extensions)
  RedmineExtensions::PatchManager.register_patch_to_be_first 'Redmine::Notifiable',
    'RedmineDmsf::Patches::NotifiablePatch', prepend: true, first: true
#else
 # Redmine::Notifiable.prepend RedmineDmsf::Patches::NotifiablePatch
#end

fixed the primary problem. I am not sure is everything is working now.

**Comment by picman** [comment]
Definitely not. If [EasyExtension plugin](https://github.com/easyredmine/redmine_extensions) is not installed, it won't simply work.

Duplicates #1350.

**Comment by picman** [comment]
Your solution is good in your environment. I see no problem there. However, I still hasn't found a general solution working in all environments, e.g. redmine_extension gem is not compatible with Redmine 5.0.
The main problem is the conflict between alias_method and prepend. In my opinion, prepend is the right approach despite the fact it breaks RedmineUp plugins.

**Comment by picman** [comment]
So I've just added an ugly workaround that should solve the problem. Could you test the _devel_ branch in your environment, please?

**Comment by picman** [comment]
Fixed.
