### ISSUE TITLE
Hook Request

### ISSUE THREAD

**Issue by HugoHasenbein** [danmunn/redmine_dmsf#1355]
Dear Dan,

I am the author of redmine_more_previews, a plugin for redmine, which allows for previewing a variety of file formats in the browser by converting those files into pdf, html or text. By far the most liked feature is the preview of Microsoft Office files, which are converted in the backend with LibreOffice. The plugin's architecture is to eventually just let one program do a conversion, whereby the converted file is cached (if configured so) or it is converted live (causing a bit of latency).

I wasn't prepared that the plugin enjoys pretty much attention. Often I am being asked if my plugin could add it's capabilities to redmine_dmsf, your plugin. In this case I answer, that I do not want to patch another plugin, which would likely create a big mess. Still, I wonder if there would in fact be a way to let our plugins work together.

From a brief inspection of your plugin I assume dmsf_files_controller#show provides the file to the user. If this methods could include a hook like call_hook(:dmsf_files_controller_before_show, context: {file: @file} ) and check if this hook returns true/false (delivered content / did no do anything) and in response to true or false delivers or does not deliver content by itself, then I think we can make many users happy.

I would appreciate your answer and keep up the good work

Stephan

**Comment by picman** [comment]
A very good idea! However, I have several comments to your proposal. Firstly, a hook cannot return a value, so I passed it as a referenced argument. Secondly, we need a view method hook. The show method is to display document's revisions.

So, the implementation in DMSF is as follows.

```ruby
def view
  ...
  # Allow a preview of the file by an external plugin
  result = { processed: false }
  call_hook(:dmsf_files_controller_before_view, { file: @revision.disk_file, result: result })
  return if result[:processed]
  ...
end
```

You should implement the hook in your plugin this way.

```ruby
 def dmsf_files_controller_before_view(context={})
   # Display a preview of the file
   file = context[:file]
   # Inform DMSF that the file has been already displayed
   result = context[:result]
   result[:processed] = true
 end
```
You can test it in _devel-3.0.1_ branch. If you provide me a link to your plugin with an implementation of the hook, it will be a pleasure for me to test it too.

**Comment by HugoHasenbein** [comment]
dear Karel,

according to Redmine::Hook::Helper

    # Helper module included in ApplicationHelper and ActionController so that
    # hooks can be called in views like this:
    #
    #   <%= call_hook(:some_hook) %>
    #   <%= call_hook(:another_hook, :foo => 'bar') %>
    #
    # Or in controllers like:
    #   call_hook(:some_hook)
    #   call_hook(:another_hook, :foo => 'bar')
    #
    # Hooks added to views will be concatenated into a string. Hooks added to
    # controllers will return an array of results.
    #
    # Several objects are automatically added to the call context:
    #
    # * project => current project
    # * request => Request instance
    # * controller => current Controller instance
    # * hook_caller => object that called the hook
    #
    module Helper
      def call_hook(hook, context={})
        if is_a?(ActionController::Base)
          default_context = {:controller => self, :project => @project, :request => request, :hook_caller => self}
          Redmine::Hook.call_hook(hook, default_context.merge(context))
        else
          default_context = { :project => @project, :hook_caller => self }
          default_context[:controller] = controller if respond_to?(:controller)
          default_context[:request] = request if respond_to?(:request)
          Redmine::Hook.call_hook(hook, default_context.merge(context)).join(' ').html_safe
        end
      end
    end

a hook added to a controller should return an array of results. So we would not need to pass in the result variable.

best regards

Stephan

**Comment by picman** [comment]
You are right, so:

The implementation in DMSF is as follows.

```ruby
def view
  ...
  # Allow a preview of the file by an external plugin
  results = call_hook(:dmsf_files_controller_before_view, { file: @revision.disk_file })
  return if results.first == true
  ...
end
```

You should implement the hook in your plugin this way.

```ruby
 def dmsf_files_controller_before_view(context={})
   # Display a preview of the file
   file = context[:file]
   # Inform DMSF that the file has been already displayed
   return true
 end
```

**Comment by picman** [comment]
I have take a look on your solution and it seems to bee very simple and clever. So I will add such a preview directly into DMSF ( #1353).

**Comment by HugoHasenbein** [comment]
Dear Karel,

I am currently working on another problem, before I was going to add some stuff to redmine_more_previews.

There is one issue, though: let's assume, Libre converts "mydoc.docx" with images (assets) to index.html, then the assets need to be accessible, too. I do this with routes. So if you add the functionality to dmsf, then the routes should also honor an access to assets.

best regards

Stephan

**Comment by picman** [comment]
I convert office documents into PDF and then send the PDF to the browser as an inline file to be displayed. So, I haven't to care about any assets, I think.

**Comment by HugoHasenbein** [comment]
Do you want to just do the conversion yourself or do you want to integrate my plugin, as I planned to integrate your plugin (which would take care of assets as well?

**Comment by picman** [comment]
I will provide my own implementation but also the hook will be there.
