### ISSUE TITLE
Progress bar modal when handling document upload

### ISSUE THREAD

**Issue by dnyamy** [danmunn/redmine_dmsf#1361]
Hello,
I have been using this plugin for some few years now, with a lot of satisfaction.
Thank you very much for the tool.

Over time, I have added little customizations, like performing some checks when a new revision is submitted and rejecting "bad" uploads (filename not matching internal rules, wrong values in file meta data...)

I would like to go a bit further. When a user submit its new revision, and the file passes all the checks and is accepted, I want to perform a custom processing which can take a little time, and then give feedback to user. 

For me the best way is :
- Add a progress bar modal that makes the user aware a processing is being performed, an compels him to wait
- At the end of the processing, in case of failure of the task, flash an error/warning to user with some explanations

The goal of the new feature is not to check before accepting the submission. The file has already been accepted. Even if the processing fails, the revision should be kept.

Please, any opinion about that ?
And please can someone give me a lift on how to achieve it ?

Thanks once more
Regards

Dn

**Comment by picman** [comment]
I'd implement it as follows:

1. I'd add a hook call into `DmsUploadController::commit_files_internal`
```ruby
def commit_files_internal(commited_files)
    @files, failed_uploads = DmsfUploadHelper.commit_files_internal(commited_files, @project, @folder, self)
++    call_hook(:dmsf_upload_controller_after_commit, { files: @files })
    respond_to do |format|
      format.js
      format.api  { render_validation_errors(failed_uploads) unless failed_uploads.empty? }
      format.html { redirect_to dmsf_folder_path(id: @project, folder_id: @folder) }
    end
  end
```
2. Somewhere in your plugin, you can implement files processing. E.g.:
```ruby
class DmsfUploadControllerHooks < Redmine::Hook::Listener
        def dmsf_upload_controller_after_commit(context={})
          sleep(5) # Files processing
          context[:controller].flash[:info] = 'Okay'
        end
end
```
3. Concerning the progress bar I'd use the Redmine's ajax indicator.
In *upload_files.html.erb* view switch it on (*onclick* added)):
```ruby
<%= submit_tag l(:label_upload), class: 'button-positive', onclick: "$('#ajax-indicator').show();" %>
```
and in *_main.html.erb* at the bottom I'd switch it off:
```ruby
<% late_javascript_tag do %>
  "$('#ajax-indicator').hide();"
<% end %>
```

A complete diff without the implementation of the hook:
```
diff --git a/app/controllers/dmsf_upload_controller.rb b/app/controllers/dmsf_upload_controller.rb
index b2590f2..2515b47 100644
--- a/app/controllers/dmsf_upload_controller.rb
+++ b/app/controllers/dmsf_upload_controller.rb
@@ -132,6 +132,7 @@ class DmsfUploadController < ApplicationController
 
   def commit_files_internal(commited_files)
     @files, failed_uploads = DmsfUploadHelper.commit_files_internal(commited_files, @project, @folder, self)
+    call_hook(:dmsf_upload_controller_after_commit, { files: @files })
     respond_to do |format|
       format.js
       format.api  { render_validation_errors(failed_uploads) unless failed_uploads.empty? }
diff --git a/app/views/dmsf/_main.html.erb b/app/views/dmsf/_main.html.erb
index 923748c..2f32e0c 100644
--- a/app/views/dmsf/_main.html.erb
+++ b/app/views/dmsf/_main.html.erb
@@ -130,3 +130,7 @@
     });
   <% end %>
 <% end %>
+
+<% late_javascript_tag do %>
+  "$('#ajax-indicator').hide();"
+<% end %>
diff --git a/app/views/dmsf_upload/upload_files.html.erb b/app/views/dmsf_upload/upload_files.html.erb
index 7af5684..d0a7dfc 100644
--- a/app/views/dmsf_upload/upload_files.html.erb
+++ b/app/views/dmsf_upload/upload_files.html.erb
@@ -45,7 +45,8 @@
       <% end %>
     <% end %>
     <div class="form-actions">
-      <%= submit_tag l(:label_upload), class: 'button-positive' %>
+      <%= submit_tag l(:label_upload), class: 'button-positive',
+                     onclick: "$('#ajax-indicator').show();" %>
     </div>
   <% end %>
 <% end %>
```

If it makes sense for you this way, I can add the hook call and the indicator on/off into the _devel_ branch.
