### ISSUE TITLE
Conflict with plugin redmine_issue_evm

### ISSUE THREAD

**Issue by voohoo2000** [danmunn/redmine_dmsf#1363]
**[Environment]**
1. Redmine 5.0.1
2. Plugins
    1) redmine_issue_evm 6.0.1
        https://github.com/momibun926/redmine_issue_evm
    2) redmine_dmsf 3.0.0

**[Issue]**
1. When install redmine_dmsf only, workflow function of dmsf works well
   1) create workflow: OK
   2) edit workflow: OK
3. After install redmine_issue_evm, workflow function failed
   1) create workflow: OK
   2) edit workflow: NG (only name of workflow could be changed, no steps' edit box show)

Maybe caused by issue of redmine_issue_evm, I don't know.

**Comment by voohoo2000** [comment]
Quiet quick response !
After installed '3.0.1 devel' or release 'v3.0.1', The issue above is resolved but the configure of this plugin become not possible, which shows "internal error" always.

**Comment by voohoo2000** [comment]
> Fixed.

Quiet quick response !
After installed '3.0.1 devel' or release 'v3.0.1', The issue above is resolved but the configure of this plugin become not possible, which shows "internal error" always.

**Comment by picman** [comment]
I cannot reproduce this problem. Configuration of DMSF plugin works as expected. What is in `production.log`?

![image](https://user-images.githubusercontent.com/779003/172161405-304c72d2-4a8b-4b72-a27c-d7e1a7e89f3a.png)

![image](https://user-images.githubusercontent.com/779003/172161441-38deeea1-4763-473c-9fb2-09b35bded8b3.png)

**Comment by voohoo2000** [comment]
> I cannot reproduce this problem. Configuration of DMSF plugin works as expected. What is in `production.log`?
> 
> ![image](https://user-images.githubusercontent.com/779003/172161405-304c72d2-4a8b-4b72-a27c-d7e1a7e89f3a.png)
> 
> ![image](https://user-images.githubusercontent.com/779003/172161441-38deeea1-4763-473c-9fb2-09b35bded8b3.png)

After I upgraded redmine_dmsf from 3.0.0 to 3.0.1, workflow can be edited now, but configuration shows 500 internal server error,
![image](https://user-images.githubusercontent.com/11582675/172313278-b68cb868-f76d-4737-a05a-944ba129d558.png)

There is no log saved under redmine log folder.

**Comment by picman** [comment]
Enable logging in _config/additional_environment.rb_, e.g.:
``` ruby
config.logger = Logger.new("#{Rails.root}/log/#{Rails.env}.log", 'daily')
config.log_level = :info
```

**Comment by voohoo2000** [comment]
![image](https://user-images.githubusercontent.com/11582675/172344319-2aeb266b-e9de-4a12-94f1-6837a2bc7462.png)

**Comment by picman** [comment]
Fixed.
