### ISSUE TITLE
Wrong translation in Persian and probably some other languages

### ISSUE THREAD

**Issue by salmanmp** [danmunn/redmine_dmsf#1368]
Hi
Some languages like Persian, have different syntax to make "Noun + Noun", e.g. in this situation the result of below line must be in reverse order to be correct in Persian.
https://github.com/danmunn/redmine_dmsf/blob/852678481b9f928ec1444d8fadb2bba99212fa2d/app/views/settings/_dmsf_settings.html.erb#L156
It's recommended to define new locale entry as `:label_dmsf_columns`

**Comment by picman** [comment]
Fixed as suggested. BTW, if you have a Persian localization for DMSF, couldn't you add it via a pull request to the project?

**Comment by salmanmp** [comment]
> Fixed as suggested. BTW, if you have a Persian localization for DMSF, couldn't you add it via a pull request to the project?

Thanks. I'll add Persian localization in a PR.
