### ISSUE TITLE
Mail rendering of DMSF file link reports undefined method error

### ISSUE THREAD

**Issue by JDQuackers** [danmunn/redmine_dmsf#1371]
When attempting to use a DMSF link as part of textile formatting, the resulting email notification to involved users displays an error instead of the expected link. From the patched help files, it lists the following as the correct textile syntax:

- {{dmsf(17)}} (a link to the file with id 17)

And the example that I tried was the following:

`Testing DMSF link to this project: {{dmsf(96)}}`

The email HTML text contains:

> Testing DMSF link to this project:
>
> Error executing the dmsf macro (undefined method `view_dmsf_file_path' for #<ActionView::Base:0x000000000196b8> Did you mean? view_dmsf_file_url)

whereas I would expect it to display the following:

> Testing DMSF link to this project: $file_name

### My environment:

```
Environment:
  Redmine version                5.0.0.stable
  Ruby version                   3.0.0-p0 (2020-12-25) [x86_64-linux]
  Rails version                  6.1.4.7
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   3.0.2
```

**Comment by picman** [comment]
Fixed in #1372.
