### ISSUE TITLE
Possible XSS Vulnerability by using eval()

### ISSUE THREAD

**Issue by liaham** [danmunn/redmine_dmsf#1374]
Hi @picman,

a content security policy was blocking the `dmsfToogle` which is used to expand and collapse the folder tree in an enabled DMS module of a project because of using `eval()`. The affected code is in `redmine_dmsf.js: 145`. 

Though `eval()` seems not to operate on user input but it might also be detected by automated security scanner since `eval()` is present in many malicious scripts.

Therfore, I would appreciate if you could find an alternative for `eval()`.  

Perhaps these articles are some inspiration:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!
* https://www.delftstack.com/howto/javascript/javascript-eval-alternative/

Thank you very much!

Best Regards,
liaham

**Comment by picman** [comment]
I have replaced `eval` with `Function` as recommended on the first link. Thank you!

**Comment by liaham** [comment]
Thank you very much for your fast response!
