### ISSUE TITLE
Hide the link in the TOP menu

### ISSUE THREAD

**Issue by CSCSxx** [danmunn/redmine_dmsf#1375]
Since not all projects or users use the plugin, it would be great if you could hide the link in the TOP menu  (link list at the top) globally in the plugin settings. It appears in the project menu (2nd list of links), if activated...

**Comment by picman** [comment]
The top link is for a global DMS view over all projects. The project's tab is related to the project only. If you hide the top menu's tab in the settings, it won't be available even for users which would use it.

**Comment by CSCSxx** [comment]
I understand that, but we don't need a global function in our use case, so this link is more annoying than useful, especially since we have a lot of entries in the bar

**Comment by picman** [comment]
I've added it as option-able into the plugin's settings.
