### ISSUE TITLE
Unable to start workflow when subversion is >0

### ISSUE THREAD

**Issue by magic-k** [danmunn/redmine_dmsf#1376]
Redmine 4.2.5
DMSF 3.0.0

I created a workflow and wanted to use it on a document. But the option is greyed out because the subversion is not 0. Is there a reason for this behaviour as this worflow is for documents that are to be released to our customer and we don't have the freedom to use arbitrary versions?

**Comment by picman** [comment]
You can change it in the plugin's settings. The option **Only approval zero minor version** under *Approval Workflow*.

**Comment by magic-k** [comment]
Ok, thank you.
