### ISSUE TITLE
Unable to copy or move files

### ISSUE THREAD

**Issue by sachilles** [danmunn/redmine_dmsf#1382]
I'm running Redmine in version 4.2.7 (stable) and redmine_dmsf in version 3.0.2. Unfortunately I can't move or copy uploaded files within the dmsf module.

By selecting "copy/move" any file the corresponding page for copying or moving won't be opened and instead the corresponding file or files will be downloaded.

**Comment by picman** [comment]
Fixed. Thank you for reporting that.
