### ISSUE TITLE
Consult - letters version workarround

### ISSUE THREAD

**Issue by vergelli** [danmunn/redmine_dmsf#1383]
Hello, I've been trying to modify the plugin to set the file version only to letters. To do so, I've been doing the following changes:

1.  First I take off the numbers from the function above:  `redmine_dmsf/app/helpers/dmsf_upload_helper.rb`
![image](https://user-images.githubusercontent.com/21988764/179825655-01b876bd-6bde-4711-a81e-adef6a32b07d.png)

2. Then I set the value of the default major_version variable on the model to -65:  `redmine_dmsf/app/models/dmsf_upload.rb`
![image](https://user-images.githubusercontent.com/21988764/179826665-e4da86dd-5b06-42da-a72c-fb6c463f5a3e.png)
 I did this because, if I understand correctly by this comments here:  `redmine_dmsf/app/helpers/dmsf_upload_helper.rb`
![image](https://user-images.githubusercontent.com/21988764/179827064-fda89436-1bd4-40df-899e-30b23c1f3f5a.png)
The functions turns it into an "A"

3.  After this I can see on the UI the following result:`/projects/dms/dmsf/upload/files?folder_id=134`
![image](https://user-images.githubusercontent.com/21988764/179827795-045a082b-8067-43df-a342-a917cdfbb98b.png)
All perfect. Just as I wanted to. BUT, when I commit the file, it turns the version to **2.1**, as you can see here `/dmsf/files/97`
![image](https://user-images.githubusercontent.com/21988764/179828245-0e20a1e7-59c7-4d5f-abd6-de66e472e5c9.png)

My question is, what can I do to make the version take the letter that shows in the UI. In this case for example, if I take the "A" the version should be "A.1" and the next Major_version should be "B".

Where in the plugin structure should I look for changing this behavior.

Thank you in advance.
Regards.

**Comment by picman** [comment]
This worked for me (65, not -65).
```ruby
$ git diff
diff --git a/app/helpers/dmsf_upload_helper.rb b/app/helpers/dmsf_upload_helper.rb
index fcc2c03..a19684e 100644
--- a/app/helpers/dmsf_upload_helper.rb
+++ b/app/helpers/dmsf_upload_helper.rb
@@ -151,7 +151,7 @@ module DmsfUploadHelper
 
   # 0..99, A..Z except O
   def self.major_version_select_options
-    (0..99).to_a + ('A'..'Y').to_a - ['O']
+    ('A'..'Y').to_a - ['O']
   end
 
   # 0..999, ' '
diff --git a/app/models/dmsf_upload.rb b/app/models/dmsf_upload.rb
index fb463a8..bb48d7e 100644
--- a/app/models/dmsf_upload.rb
+++ b/app/models/dmsf_upload.rb
@@ -82,7 +82,7 @@ class DmsfUpload
     if file.nil? || file.last_revision.nil?
       @title = DmsfFileRevision.filename_to_title(@name)
       @description = uploaded[:comment]
-      @major_version = 0
+      @major_version = 65
       @minor_version = 0
       @patch_version = nil
       @workflow = nil
```

**Comment by vergelli** [comment]
It didn't work, it shows the number 65 directly:

![image](https://user-images.githubusercontent.com/21988764/180209512-94c96549-8463-4467-9f92-b9c59760f198.png)

Somehow the function `self.gui_version(-65)` returns `"A"`. This behavior is ok for me, the problem is that once you commit the document, by pressing on Upload, then it uploads with version 2.1, instead of "A". What could it be?

**Comment by vergelli** [comment]
My bad, I forget this lines should also be edited:


```
        if file
          if file.last_revision
            last_revision = file.last_revision
            new_revision.source_revision = last_revision
            new_revision.major_version = last_revision.major_version
            new_revision.minor_version = last_revision.minor_version
          else
            new_revision.minor_version = 0
            new_revision.major_version = -65
          end
        else
          file = DmsfFile.new
          file.project_id = project.id
          file.name = name
          file.dmsf_folder = folder
          file.notification = Setting.plugin_redmine_dmsf['dmsf_default_notifications'].present?
          new_revision.minor_version = 0
          new_revision.major_version = -65
        end
```
