### ISSUE TITLE
Changing default file query

### ISSUE THREAD

**Issue by hibit-2709** [danmunn/redmine_dmsf#1386]
How to change default file query in DMS?
Is any method to change it?

**Comment by picman** [comment]
You mean to create a custom query with filters and options and then mark and use it as the default query whenever the user opens DMS tab?

**Comment by hibit-2709** [comment]
Exactly.

**Comment by picman** [comment]
There is no such option now, but it would be a nice feature.

**Comment by picman** [comment]
I've implemented it similar to to default issue query. There is the global default query in plugin's options, users' default query in the user's preferences and project's default query in project's settings. The highest priority has got the user's default query, then project's and the global one has got the lowest priority.
Could you test it a bit in the _devel_ branch?

**Comment by hibit-2709** [comment]
Sorry for the delay. After 30 minutes of testing, I see it's OK.
It is a great pleasure to work with you. That's exactly what we wanted. Best regards.

**Comment by picman** [comment]
Super.
