### ISSUE TITLE
Custom field in DMS Columns

### ISSUE THREAD

**Issue by hibit-2709** [danmunn/redmine_dmsf#1388]
Redmine 5.02
DMS 3.0.3

Enabling custom field in DMS Columns (DMS settings) causes error 500 to appear when the DMS tab is selected.
Further checking showed that the problem occurs, when a custom field is added as an option to the query, and the current view is for the Documents and not DMSF folder.

Production log:

> I, [2022-08-03T19:48:22.596797 #104523]  INFO -- : [ab027b62-78bd-44bb-bbfd-4db6dcf28e5a] Started GET "/projects/svan001900/dmsf" for 127.0.0.1 at 2022-08-03 19:48:22 +0200
I, [2022-08-03T19:48:22.599910 #104523]  INFO -- : [ab027b62-78bd-44bb-bbfd-4db6dcf28e5a] Processing by DmsfController#show as HTML
I, [2022-08-03T19:48:22.600022 #104523]  INFO -- : [ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]   Parameters: {"id"=>"svan001900"}
I, [2022-08-03T19:48:22.648722 #104523]  INFO -- : [ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]   Current user: admin_bk (id=1)
I, [2022-08-03T19:48:22.840122 #104523]  INFO -- : [ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]   Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (Duration: 104.8ms | Allocations: 53863)
I, [2022-08-03T19:48:22.840337 #104523]  INFO -- : [ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]   Rendered layout layouts/base.html.erb (Duration: 105.1ms | Allocations: 53924)
I, [2022-08-03T19:48:22.840571 #104523]  INFO -- : [ab027b62-78bd-44bb-bbfd-4db6dcf28e5a] Completed 500 Internal Server Error in 240ms (ActiveRecord: 48.6ms | Allocations: 138877)
F, [2022-08-03T19:48:22.841510 #104523] FATAL -- : [ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]   
[ab027b62-78bd-44bb-bbfd-4db6dcf28e5a] ActionView::Template::Error (undefined method `visible?' for #<DmsfFolder id: 2755, project_id: 1959, title: "SV104B detale", deleted: 0>):
[ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]     41:       <%= check_box_tag('ids[]', "#{node.type}-#{node.id}", false, id: nil) unless system %>
[ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]     42:     </td>
[ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]     43:     <% query.inline_columns.each do |column| %>
[ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]     44:       <%= content_tag 'td', column_content(column, node), class: column.css_classes %>
[ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]     45:     <% end %>
[ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]     46:     <td class="buttons">
[ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]     47:       <% unless system %>
[ab027b62-78bd-44bb-bbfd-4db6dcf28e5a]   
[ab027b62-78bd-44bb-bbfd-4db6dcf28e5a] app/helpers/application_helper.rb:298:in `format_object'
[ab027b62-78bd-44bb-bbfd-4db6dcf28e5a] app/helpers/queries_helper.rb:277:in `column_value'

**Comment by picman** [comment]
This is strange. I cannot reproduce the error. In the screen-shot I have added two custom fields, **Tag** as a  default column in DMSF plugin's settings and **Confidentality** in _Options_. I've no crash on **_Documents_** tab.

![image](https://user-images.githubusercontent.com/779003/183651254-78ef7772-d54b-4012-8b28-1d196d1ad1f4.png)

From the log I conclude that the problem is in a call of DmsfFolder::visible? method which doesn't exist and it really doesn't. If I check `format_object` method in _application_helper.rb_, the `visible?` method is called only in case of an _Issue_.

**Comment by hibit-2709** [comment]
I've disabled all other plugins. Added new CF 'comment' identical to that generate problem. Then set query:

![DMS_Err0](https://user-images.githubusercontent.com/84457821/185092992-72c93b3e-215a-4bbc-9ee7-8f2ea6baa798.png)
All is OK. Then I add to query CF 'Zagadnienia powiazane' defined years ago:
![DMS_Err1](https://user-images.githubusercontent.com/84457821/185093568-a270824f-1991-46ab-92e2-0f8fd0082015.png)

And after 'Apply" it have Error. Any idea?

> I, [2022-08-17T11:47:37.916902 #71044]  INFO -- : [90a580c6-0d2d-48c8-839f-c161eb56bc6e]   Parameters: {"utf8"=>"✓", "set_filter"=>"1", "sort"=>"title", "f"=>["title", ""], "op"=>{"title"=>"~"}, "v"=>{"title"=>[""]}, "c"=>["id", "size", "modified", "version", "author", "cf_83", "cf_12"], "group_by"=>"", "t"=>[""], "id"=>"svan003095"}
> I, [2022-08-17T11:47:37.980028 #71044]  INFO -- : [90a580c6-0d2d-48c8-839f-c161eb56bc6e]   Current user: admin_bk (id=1)
> I, [2022-08-17T11:47:38.136524 #71044]  INFO -- : [90a580c6-0d2d-48c8-839f-c161eb56bc6e]   Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (Duration: 73.2ms | Allocations: 50408)
> I, [2022-08-17T11:47:38.136605 #71044]  INFO -- : [90a580c6-0d2d-48c8-839f-c161eb56bc6e]   Rendered layout layouts/base.html.erb (Duration: 73.4ms | Allocations: 50469)
> I, [2022-08-17T11:47:38.136815 #71044]  INFO -- : [90a580c6-0d2d-48c8-839f-c161eb56bc6e] Completed 500 Internal Server Error in 220ms (ActiveRecord: 59.8ms | Allocations: 134878)
> F, [2022-08-17T11:47:38.137937 #71044] FATAL -- : [90a580c6-0d2d-48c8-839f-c161eb56bc6e]   
> [90a580c6-0d2d-48c8-839f-c161eb56bc6e] ActionView::Template::Error (undefined method `visible?' for #<DmsfFolder id: 909, project_id: 3154, title: "SA 40 PAK", deleted: 0>):
> [90a580c6-0d2d-48c8-839f-c161eb56bc6e]     41:       <%= check_box_tag('ids[]', "#{node.type}-#{node.id}", false, id: nil) unless system %>
> [90a580c6-0d2d-48c8-839f-c161eb56bc6e]     42:     </td>
> [90a580c6-0d2d-48c8-839f-c161eb56bc6e]     43:     <% query.inline_columns.each do |column| %>
> [90a580c6-0d2d-48c8-839f-c161eb56bc6e]     44:       <%= content_tag 'td', column_content(column, node), class: column.css_classes %>
> [90a580c6-0d2d-48c8-839f-c161eb56bc6e]     45:     <% end %>
> [90a580c6-0d2d-48c8-839f-c161eb56bc6e]     46:     <td class="buttons">
> [90a580c6-0d2d-48c8-839f-c161eb56bc6e]     47:       <% unless system %>
> [90a580c6-0d2d-48c8-839f-c161eb56bc6e]   
> [90a580c6-0d2d-48c8-839f-c161eb56bc6e] app/helpers/application_helper.rb:298:in `format_object'
>

**Comment by picman** [comment]
Could you also post how the 'Zagadniena powiezana' is defined. And to what values it is set by 'SA 40 PAK' folder and  '4WSA...' document?

**Comment by picman** [comment]
Meantime you can try to add the missing function into _app/models/dmsf_folder.rb_.

```ruby
 def visible?
    if self.respond_to?(:type)
      if /^folder/.match?(type)
        return DmsfFolder.visible.where(id: self.id).exists?
      end
    end
    true
  end
```

**Comment by hibit-2709** [comment]
![DMS_Err2](https://user-images.githubusercontent.com/84457821/185107507-1ea74917-831c-44c0-814b-5c8d128ba4f9.png)

For folder, this field is empty. For files, usually has '#issue_number'. I've trading empty it, and only 'issue_number', without success.

**Comment by picman** [comment]
It seems to be in the value. What is the value of **Zagadenie powiązane** of 'SA 40PAK' folder?

**Comment by hibit-2709** [comment]
It helps. I've added this after line:
`before_create: default_values`

**Comment by picman** [comment]
OK
