### ISSUE TITLE
Custom code for handling file commit not working

### ISSUE THREAD

**Issue by dnyamy** [danmunn/redmine_dmsf#1389]
Hello Karel,
The question is related to closed issue #1361
By the way, thanks again for the quick handling of that one.

I have tried to implement my add on to check files after commit. I don't know why, but the code is not being executed.
I have even added simple log instructions at the place of the hook calling (app/controllers/dmsf_upload_controller.rb).

`  def commit_files_internal(commited_files)
    @files, failed_uploads = DmsfUploadHelper.commit_files_internal(commited_files, @project, @folder, self)
    Rails.logger.info "Files successfully commited"
    flash.now[:info] = "Files successfully commited"
    respond_to do |format|
      format.js
      format.api  { render_validation_errors(failed_uploads) unless failed_uploads.empty? }
      format.html { redirect_to dmsf_folder_path(id: @project, folder_id: @folder) }
    end
  end`

Nothing is written in the logs, and no info is flashed on the interface. I wonder whether the function commit_files_internal is ever called. Or what am I doing wrong ?

Thanks in advance
Dn

**Comment by picman** [comment]
If I add a flash message into the code as follows, I always see the info message after an upload and commit.

```ruby
  def commit_files_internal(commited_files)
++    flash[:info] = 'commit_files_internal called'
      @files, failed_uploads = DmsfUploadHelper.commit_files_internal(commited_files, @project, @folder, self)
      call_hook :dmsf_upload_controller_after_commit, { files: @files }
      respond_to do |format|
        format.js
        format.api  { render_validation_errors(failed_uploads) unless failed_uploads.empty? }
        format.html { redirect_to dmsf_folder_path(id: @project, folder_id: @folder) }
      end
    end
```

**Comment by dnyamy** [comment]
Strange,
Not working on my side, even the flash message
Some lines of log, where I am expecting my info
I am really puzzled

`Started POST "/dmsf_uploads.js?attachment_id=1&filename=modele-essais_interieur.docx&content_type=application%2Fvnd.openxmlformats-officedocument.wordprocessingml.document" for 176.160.208.49 at 2022-08-09 20:16:41 +0000`
`Processing by DmsfUploadController#upload as JS
  Parameters: {"attachment_id"=>"1", "filename"=>"modele-essais_interieur.docx", "content_type"=>"application/vnd.openxmlformats-officedocument.wordprocessingml.document"}`
`  Current user: dnyamy (id=5)`
`Saving attachment '/opt/redmine/files/2022/08/220809201641_modele-essais_interieur.docx' (286560 bytes)
  Rendering plugins/redmine_dmsf/app/views/dmsf_upload/upload.js.erb
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload.js.erb (2.2ms)`
`Completed 200 OK in 255ms (Views: 25.9ms | ActiveRecord: 206.9ms)`
`Started POST "/dmsf/files/23/revision/create" for 176.160.208.49 at 2022-08-09 20:16:46 +0000`
`Processing by DmsfFilesController#create_revision as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"JQThNj4UhtAjpKAOR8D+3h9HQnzpukC7eaVWS6RdN0h7LZdQXDXQ7JbTfNuBMQEwjPeY
9cZf+wlV8uMSwXzTcg==", "back_url"=>"", "dmsf_file_revision"=>{"title"=>"Intérieur", "name"=>"modele-essais_interieur.docx", "description"=>"test"}, "version"=>"1", "dmsf_attachments"=>{"1"=>{"filename"=>"modele-essais_interieur.docx", "token"=>"14925.56445d13cc12c96a1266e941b9aa93895263f328df97ad8f3deda005421cec63"}}, "commit"=>"Créer", "id"=>"23"}`
`  Current user: dnyamy (id=5)`

**Comment by picman** [comment]
How do you upload the files?

**Comment by dnyamy** [comment]
Hello,
I upload it through the GUI
Here is a screen
(I use a custom theme)
Thanks

![image](https://user-images.githubusercontent.com/43039376/184131315-c7db9ffd-e687-4c28-9e6f-941076434914.png)

**Comment by picman** [comment]
There is another hook, you can implement: `call_hook :dmsf_helper_upload_after_commit, { file: @file }`
