### ISSUE TITLE
Version of revision in wiki

### ISSUE THREAD

**Issue by magic-k** [danmunn/redmine_dmsf#1390]
Hi, for our long running application we have several documents from our customer. It's important for us to see which version of these documents were relevant for a certain project. I'm trying to put a list into the project wiki with name and version.
While i can refer to a specific revision of a document with {{dmsf(13,,42)}} which gives me a link to revision 42 from document 13, i also want to print the version of that document. The only macro i found is {{dmsfversion(13)}}, which only shows me the most current version of the document.
I don't want to put the version in the document name as that is redundant information. Is there another way or would it be possible to extend dmsfversion to accecpt a revision?

**Comment by picman** [comment]
`{{dmsfversion(document_id [, revision_id])}}`
