### ISSUE TITLE
Email notifications for workflows are not sent

### ISSUE THREAD

**Issue by yxiaoa** [danmunn/redmine_dmsf#1394]
1. Administration settings - email notifications - Approval workflows is ticked
2. "My account" - Email notifications is allowed
3. Display notified recipients actived, but there is no message about that when file is "start"

Any other configuration needed to send email?

If Dmsf legacy notifications is ticked, email will be sent when upload a file, but the recipients is wrong.

**Comment by picman** [comment]
Fixed. Could you test the _devel_ branch?

**Comment by yxiaoa** [comment]
Yes, it's really helpful. The emails are sent and displayed message is correct.

Thank you so much！
