### ISSUE TITLE
Repeatable rake task to sync documents

### ISSUE THREAD

**Issue by albenik85** [danmunn/redmine_dmsf#1396]
There is this great rake task which converts files from the default document module to DMSF. Unfortunately, it can't be used twice for the same project because the module is already activated and/or because the folder structure already exists. As some other plugins are still using the default module to attach files to a project or to issues, it would be beneficial to have the possibility to run this job again and again like some kind of sync job

**Comment by albenik85** [comment]
one more point: It looks like the tasks converts only documents which are directly attached to a project, but not the files that are attached to issues. Hope this could be enabled, too.

**Comment by picman** [comment]
Done. Could you test the _devel_ branch?

**Comment by albenik85** [comment]
Nice, it seems like the job would be repeatable now. Any ideas/suggestions how to handle files which are attached to issues? It is probably a different internal module, isn't it?

**Comment by picman** [comment]
Just add a parameter `issues=1` to the rake task.

**Comment by albenik85** [comment]
awesome, it is working like a charm, thanks a lot!
