### ISSUE TITLE
Possibility to open msg files

### ISSUE THREAD

**Issue by albenik85** [danmunn/redmine_dmsf#1398]
Currently msg files can just be downloaded from DMSF and I have to open them afterwards in outlook (or whatever mail client is selected as default). It would be great to have the possibility to open them directly with the default mail client without downloading them first

**Comment by picman** [comment]
I think that there are just two options. Either the browser is capable to open a file itself, e.g. text files, images, pdf or  downloads it. Then, if you click on the downloaded file and its extension is associated with an application, the application opens the file.
Maybe we can associate _msg_ extension with MS Outlook and allow a direct opening via the context menu item "Edit content". What do you think?

**Comment by albenik85** [comment]
I couldn't find a way for changing the browser behavior yet.
Associating msg extension with MS Outlook and the context menu item would be a good solution I believe

**Comment by picman** [comment]
I've been studying it for a while and Outlook/*.msg are not supported to be opened in Outlook. You can have a look [here](https://docs.microsoft.com/en-us/office/client-developer/office-uri-schemes). I think that the right solution is to associate msg extension with Outlook in your browser. E.g. in Firefox:

![image](https://user-images.githubusercontent.com/779003/188605395-0fba3976-b2dd-4421-8140-9157d9727fce.png)
