### ISSUE TITLE
How to add a new member into current approval workflows?

### ISSUE THREAD

**Issue by uart-aplex** [danmunn/redmine_dmsf#1400]
I only can find the Delete member but no Add member, is there anyway to add member to a step of current workflows?

For example, when the member's position changes, resignation and other reasons need to add the member.

![image](https://user-images.githubusercontent.com/24597310/187570728-995554c1-0e2d-4a80-953c-e3f67bd50e7d.png)

**Comment by picman** [comment]
Simply click on "New step or New Approver" and in the following form change "New step" onto an existing one.
