### ISSUE TITLE
Error after upgrading to 3.0.6

### ISSUE THREAD

**Issue by armenlan** [danmunn/redmine_dmsf#1405]
After upgrading to version 3.0.6, plugin settings, project settings, and user settings stopped working.

![2022-09-27_14h51_52_01](https://user-images.githubusercontent.com/114485833/192519021-20e92347-4a13-4806-82d2-6306b294e9ed.jpg)

**Comment by picman** [comment]
Check _log/production.log_ and post the related part here. Plus Redmine version and installed plugins.

**Comment by armenlan** [comment]
The administrator went on vacation. I don't know how to look at the log.

![2022-09-27_15h03_59_01](https://user-images.githubusercontent.com/114485833/192531432-435f9c4b-bdfb-4159-a661-580b4d073bda.jpg)

**Comment by armenlan** [comment]
<p>
<%= content_tag :label, l(:label_default_query) %>
<% options = [[l(:label_none), nil]] %>
<% options.concat DmsfQuery.only_public.where(project_id: nil).pluck(:name, :id) %>
<%= select_tag 'settings[dmsf_default_query]',
options_for_select(options, selected: @settings['dmsf_default_query']) %>
</p>

**Comment by armenlan** [comment]
Hello. Tell me, is there any solution? It is no longer possible to roll back. The error blocks the normal operation of Redmine

**Comment by picman** [comment]
Unfortunately, DMSF 3.0.6 requires Redmine >= 5.0. So, either downgrade DMSF to 3.0.5 or upgrade Redmine to 5.0.

**Comment by armenlan** [comment]
thanks
