### ISSUE TITLE
Lost attachment 2

### ISSUE THREAD

**Issue by lyollix** [danmunn/redmine_dmsf#1408]
Hello!

We have two projects
The first project has an issue with children
the child issue has an attachment
When we transfer the main issue to the second project,
the attachment is not transferred to the corresponding project folder and is lost

For example, this solution fixes the problem
Please check it for correctness

// issues_controller_hooks.rb

def controller_issues_after_save(context, edit = false)
    ....
    
    issue.descendants.each do |i|
        old_system_folder_desc = i.system_folder(false, old_project_id)

        if old_system_folder_desc
        new_main_system_folder_desc = i.main_system_folder(true)

        if new_main_system_folder_desc
            old_system_folder_desc.dmsf_folder_id = new_main_system_folder_desc.id
            old_system_folder_desc.project_id = project_id

            unless old_system_folder_desc.save
            controller.flash[:error] = old_system_folder_desc.errors.full_messages.to_sentence
            Rails.logger.error old_system_folder_desc.errors.full_messages.to_sentence
            end

            i.dmsf_files.each do |dmsf_file|
            dmsf_file.project_id = project_id
            unless dmsf_file.save
                controller.flash[:error] = dmsf_file.errors.full_messages.to_sentence
                Rails.logger.error dmsf_file.errors.full_messages.to_sentence
            end
            end
        end

        i.dmsf_links.each do | dmsf_link|
            dmsf_link.project_id = project_id
            unless dmsf_link.save
            controller.flash[:error] = dmsf_link.errors.full_messages.to_sentence
            Rails.logger.error dmsf_link.errors.full_messages.to_sentence
            end
        end
        
        end
    end
    ....
end

**Comment by picman** [comment]
Cannot you create a pull request?

**Comment by lyollix** [comment]
I can't do it but here is my code
https://github.com/lyollix/redmine_dmsf/blob/master/lib/redmine_dmsf/hooks/controllers/issues_controller_hooks.rb

**Comment by lyollix** [comment]
yes, did
