### ISSUE TITLE
WebDav doesn't show subprojects

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1410]
DMSF Version: 3.0.6

Using WebDav (Windows) all subprojects are not visible. It looks like this:
![grafik](https://user-images.githubusercontent.com/7224922/202155301-d7aa7149-9cca-4e8f-9adc-0bc8aba508b7.png)

The subprojects are visible in the Global DMS View:
![grafik](https://user-images.githubusercontent.com/7224922/202155680-eee980b9-b760-4210-a0dd-5235ec4b347e.png)

I expect to have the suprojects available in WebDav.  Please check on this issue.

Thank you.

**Comment by picman** [comment]
Do the sub-projects contain any folders/documents?

**Comment by picman** [comment]
I cannot reproduce the issue. Try to double click [stv-projekte] folder. Try to mount [stv-projekte] directly. How does it behave?

**Comment by mmundi72** [comment]
I checked all subprojects and activated in all of them DMSF and I added 1 folder and 1 file to each. It is still not working in WebDav. 
Here a short video showing that I manually opened WebDav for a subprojects. Then I go back to [stv-projekte] - only the folders/files of that project are visible but not the subprojects. Afterwards I open again the subproject by manually entering the Identifier.



https://user-images.githubusercontent.com/7224922/208110244-40e48bce-8ae7-41fd-a3f6-d4bbc913c533.mp4

**Comment by picman** [comment]
**Sub-projects as sub-folders** plugin's option is on? If yes, could you add the following two lines into your _plugins/redmine_dmsf/lib/redmine_dmsf/webdav/project_resource.rb_ and check the log then?
```ruby
32 # Sub-projects
      ...
33 load_projects(project.children) if Setting.plugin_redmine_dmsf['dmsf_projects_as_subfolders']
++ Rails.logger.info ">>> #{Setting.plugin_redmine_dmsf['dmsf_projects_as_subfolders'] ? 'yes' : 'no'}"
++ Rails.logger.info ">>> #{@children.size}"
   if project.module_enabled?(:dmsf)
   ...
```

**Comment by picman** [comment]
Or, even better, try the new branch _webdav_, where I have added log messages. Then post what is in the log.

**Comment by mmundi72** [comment]
Option Sub-projects as sub-folders was disabled. I just activated that option and now it's working as expected.
Thank you for your help - I was not aware of this option.
