### ISSUE TITLE
How to define the path in dmsf for the files? And internal server error 500 while opening dmsf-admin-view.

### ISSUE THREAD

**Issue by Andreas3C** [danmunn/redmine_dmsf#1412]
Hi,

@picman many thanks for your help in [1406](https://github.com/danmunn/redmine_dmsf/issues/1406)!

That worked well, but now I have another question. The path of Redmine has changed on our new server, so DMSF did not find the files anymore. Here I could help myself with a symlink in Linux. Is there still a way to adjust the path?

Furthermore, the scheme for storing files seems to be different than before. Either this is because of the DMSF version, or maybe it can be defined.
Until now, the files of DMSF were stored in the following scheme (on our old server):
/var/www/redmine/files/dmsf/p_projectname/.

There the files are located, but now they are not found. Instead, the following folder is created, where DMSF obviously looks for the file. Because the log also says that the file cannot be found in this folder (on our new server):
/var/www/redmine/files/dmsf/2019/03/

Therefore my question, if it is possible to adjust the path.
I have looked for settings in the admin area for this, but when I get the DMSF plugin I get a server error 500. Here's what it says in the log:

```
Started GET "/redmine/admin" for 10.0.11.48 at 2022-11-23 14:00:37 +0100
Processing by AdminController#index as HTML
  Current user: admin (id=1)
  Rendering admin/index.html.erb within layouts/admin
  Rendered admin/_menu.html.erb (4.2ms)
  Rendered admin/index.html.erb within layouts/admin (7.7ms)
  Rendering layouts/base.html.erb
  Rendered layouts/base.html.erb (14.8ms)
Completed 200 OK in 70ms (Views: 29.2ms | ActiveRecord: 6.3ms)
Started GET "/redmine/admin/plugins" for 10.0.11.48 at 2022-11-23 14:00:39 +0100
Processing by AdminController#plugins as HTML
  Current user: admin (id=1)
  Rendering admin/plugins.html.erb within layouts/admin
  Rendered admin/plugins.html.erb within layouts/admin (2.5ms)
  Rendered admin/_menu.html.erb (2.3ms)
  Rendering layouts/base.html.erb
  Rendered layouts/base.html.erb (15.6ms)
Completed 200 OK in 38ms (Views: 19.6ms | ActiveRecord: 9.8ms)
Started GET "/redmine/settings/plugin/redmine_dmsf" for 10.0.11.48 at 2022-11-23 14:00:41 +0100
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_dmsf"}
  Current user: admin (id=1)
  Rendering settings/plugin.html.erb within layouts/admin
LibreOffice's command line binary 'libreoffice' not available
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (3.4ms)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_settings.html.erb (35.8ms)
  Rendered settings/plugin.html.erb within layouts/admin (38.9ms)
Completed 500 Internal Server Error in 87ms (ActiveRecord: 7.0ms)
  
ActionView::Template::Error (undefined method `only_public' for #<Class:0x000056248815e2c8>):
    170: <p>
    171:   <%= content_tag :label, l(:label_default_query) %>
    172:   <% options = [[l(:label_none), nil]] %>
    173:   <% options.concat DmsfQuery.only_public.where(project_id: nil).pluck(:name, :id) %>
    174:   <%= select_tag 'settings[dmsf_default_query]',
    175:        options_for_select(options, selected: @settings['dmsf_default_query']) %>
    176: </p>
  
plugins/redmine_dmsf/app/views/settings/_dmsf_settings.html.erb:173:in `_plugins_redmine_dmsf_app_views_settings__dmsf_settings_html_erb___4381347639946418646_122660'
app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__3250679592296933463_122640'
app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__3250679592296933463_122640'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

Can someone please help me, does anyone have any idea?

Many thanks in advance!
Andreas

**Comment by picman** [comment]
Yes, documents are stored in folders based on  the date when they were created. The original documents stored in projects related folders are migrated to the new schema in DB migration. The related migration is 20170422104901_migrate_documents.rb. Without this migration being run, you won's find old documents in DMSF.

The error "only_public" is probably related to versions Redmine/DMSF. Which versions do you use? I think that Redmine >= 5.0.0 is required.

**Comment by picman** [comment]
No feedback => closing.
