### ISSUE TITLE
Is it possible to maintain latest DMSF compatible with redmine 4.x

### ISSUE THREAD

**Issue by uart-aplex** [danmunn/redmine_dmsf#1415]
I just download DMSF V3.0.7 and try to install into redmine but failed, because V3.0.7 requests Redmine 5.x.

Due to some unsolvable plugins compatibility reasons, I cannot upgrade redmine to version 5.0, and can only continue to use version 4.2.x, I believe there are many redmine 4.x users who have the same problem.

**Comment by picman** [comment]
One of the main feature of Redmine 5 is its support for Rails 6.1 with Zeitwerk autoloding. It meant a big rework of the source code of the plugin. Therefore it is no more compatible with Redmine 4. Thefore, my answer to your question is no.
