### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by picman** [danmunn/redmine_dmsf#1421]
There is a new item **Help** in the main DMS context menu that displays a popup window with DMS documentation.

**Comment by picman** [comment]
Done.

**Comment by liaham** [comment]
Just found out that the document *dmsf_help.html* ist not available in language folders other than :en.  When there is no copy for all other languages it would raise an exception due to a routing error:

```shell
No route matches [GET] "/plugin_assets/redmine_dmsf/help/de/dmsf_help.html"
```

Thought you didn't recognized it yet.

**Comment by picman** [comment]
Fixed. If the localized version is not available, the English version is displayed instead.
