### ISSUE TITLE
Check for Illegal characters in file name

### ISSUE THREAD

**Issue by ChrisABailey** [danmunn/redmine_dmsf#1423]
Love your tool and we use it everyday...

I just found a bug where I was updating the document Title field of n existing document.  I did a cut and paste from a pdf which evidently had some hidden characters.  The resulted in an illegal document title and we could no longer open the directory/folder in the web view with that file in it.

Internally the log file shows:
F, [2023-01-24T18:13:36.277922 #1] FATAL -- :   
ActionView::Template::Error (path name contains null byte):
    41:       <%= check_box_tag('ids[]', "#{node.type}-#{node.id}", false, id: nil) unless system %>
    42:     </td>
    43:     <% query.inline_columns.each do |column| %>
    44:       <%= content_tag 'td', column_content(column, node), class: column.css_classes %>
    45:     <% end %>
    46:     <td class="buttons">
    47:       <% unless system %>
  
lib/redmine/mime_type.rb:66:in `extname'
lib/redmine/mime_type.rb:66:in `of'
plugins/redmine_dmsf/app/helpers/dmsf_queries_helper.rb:170:in `column_value'
app/helpers/queries_helper.rb:239:in `column_content'

The workaround was to go into the webdav interface and rename the file.  Which replaced the title with a new filename.

It would be nice to validate the title before accepting the change.

**Comment by picman** [comment]
I've added some code to replace invalid byte sequences in text strings. If you would be able to reproduce your case and test it on the _devel_ branch, it would be super.

**Comment by picman** [comment]
No feedback => closing.
