### ISSUE TITLE
change path for files by default

### ISSUE THREAD

**Issue by ashrafalzyoud** [danmunn/redmine_dmsf#1428]
Hi
I hope you are fine

The custom field type file it's have ( browse file)
When u click on it by default it's open my computer

How I can change the path for
/D:/new folder/

**Comment by picman** [comment]
What does it have to do with DMSF?

**Comment by ashrafalzyoud** [comment]
I wanna change the default path when choose file

**Comment by picman** [comment]
It's a Redmine feature, not related to DMSF plugin.
