### ISSUE TITLE
DMSF link in not visible in menu

### ISSUE THREAD

**Issue by kazaa8** [danmunn/redmine_dmsf#1429]
After installation module and turn on all options like:
- Global DMS menu disabled - not selected
- Changed permissions for all roles (also admin not see this)
- Add DMS module in project

DMS button is not visible in project menu... If you input link manually like projects/procject_name/dmsf  -> site with DMS is working well.
So how to add this button to all new projects?

 Redmine version                5.0.4.stable
  Ruby version                   2.7.0-p0 (2019-12-25) [x86_64-linux-gnu]
  Rails version                  6.1.7

Redmine plugins:
  000_redmine_x_ux_upgrade       1.3.9
  redmine_dmsf                   3.0.8

Script with error:

`<html>
<body>

//<![CDATA[
--
  |  
  | $(function() {
  | $("table.dmsf tr").removeClass("ui-draggable-dragging ui-droppable-active ui-droppable-hover ui-draggable-handle");
  | $(".dmsf-draggable").draggable({
  | helper: function(event, ui) {
  | var ret = $(this).clone();
  | var width = $(this)[0].offsetWidth;
  | var myHelper = [];
  | myHelper.push('<table style="width: ' + width + 'px; background-color: #ffffdd;">');
  | myHelper.push(ret.html());
  | myHelper.push('</table>');
  | helper = myHelper.join('');
  | return helper;
  | },
  | axis: "y",
  | revert: "invalid"
  | });
  | $(".dmsf-droppable" ).droppable({
  | drop: function(event, ui) {
  | let handle = $(this);
  | let dragObjectId = ui.draggable.find("td").find("input").val()
  | let dropObjectId = handle.attr('id');
  | let data = {};
  | handle.addClass("ui-state-highlight ajax-loading")
  | data['dmsf_folder'] = { drag_id: dragObjectId, drop_id: dropObjectId};
  | $.ajax({
  | url: 'https://********l/projects/lots/dmsf',
  | type: 'put',
  | dataType: 'script',
  | data: data,
  | error: function(jqXHR, textStatus, errorThrown){
  | alert(errorThrown);
  | ui.draggable.animate(ui.draggable.data("ui-draggable").originalPosition, "slow");
  | },
  | complete: function(jqXHR, textStatus, errorThrown){
  | handle.removeClass("ui-state-highlight ajax-loading")
  | if(textStatus == 'success'){
  | if(!handle.hasClass('dmsf-not-loaded')){
  | var m = handle.attr("id").match(/^(\d+)span$/);
  | if(m){
  | $('.' + m[1]).remove();
  | handle.removeClass("dmsf-expanded");
  | handle.addClass("dmsf-collapsed dmsf-not-loaded");
  | }
  | ui.draggable.remove();
  | }
  | window.location.reload();
  | }
  | }
  | });
  | }
  | });
  | });
  |  
  | //]]>

</body>
</html>`

Errors in console:
`<button class="tab-left" onclick="moveTabLeft(this); return false;"></button>
`

`<button class="tab-right" onclick="moveTabRight(this); return false;"></button>
`

`<input type="text" name="q" id="projects-quick-search" value="" class="autocomplete" data-automcomplete-url="/projects/autocomplete.js?jump=dmsf" autocomplete="off" data-value-was="">
`

`<input type="text" name="v[title][]" id="values_title" size="30" class="value">
`

`<input type="checkbox" name="ids[]" value="folder-4">
`

`<input type="checkbox" name="ids[]" value="folder-link-1">
`

`<select id="operators_title" name="op[title]">
`

`<a href="#" class="mobile-toggle-button js-flyout-menu-toggle-button"></a>
`

`<a id="hide-sidebar" href="#"><span class="far fa fa-plus"></span></a>
`

**Comment by picman** [comment]
Where is the error? You posted just snippets of JavaScript and HTML code...
Check the _log/production.log_ for any errors.

**Comment by kazaa8** [comment]
> log/production.log

ok we find out that problem comes when we enable redmineX plugin

**Comment by picman** [comment]
I tested it with that plugin too and it worked.

**Comment by kazaa8** [comment]
> I tested it with that plugin too and it worked.

Very interesting, did you use plugin from https://www.redmine-x.com (redmine_x_ux_upgrade 1.3.9 + Redmine version 5.0.4.stable) ??
Any special steps during installation did you use?

**Comment by picman** [comment]
No I didn't
