### ISSUE TITLE
Error while de-installing the plugin "Validation failed: Name contains invalid character(s)"

### ISSUE THREAD

**Issue by Andreas3C** [danmunn/redmine_dmsf#1438]
Good morning,

after our tests in the new Redmine system were successful, I wanted to take the new system productive (Redmine V5). I had previously found out that to do this, I need to uninstall the DMSF plugin before importing the data and database from the old server (Redmine V3). Then I can reinstall the DMSF plugin.
This worked fine during the initial installation of the new system, but when I wanted to import the data and database from the old system again, I got the following error when uninstalling the DMFS plugin (Validation failed: Name contains invalid character(s)).

`root@hostname:/home/redmine/redmine# rake redmine:plugins:migrate NAME=redmine_dmsf VERSION=0 RAILS_ENV=production
== 20220906151100 AddProjectsDefaultDmsfQueryId: reverting ====================
-- remove_column(:projects, :default_dmsf_query_id, :integer, {:default=>nil})
   -> 0.0422s
== 20220906151100 AddProjectsDefaultDmsfQueryId: reverted (0.0454s) ===========

== 20220317100901 AddPatchVersion: reverting ==================================
-- remove_column(:dmsf_file_revisions, :patch_version, :integer, {:null=>true, :after=>:minor_version})
   -> 0.0669s
== 20220317100901 AddPatchVersion: reverted (0.0671s) =========================

== 20210115120901 AddOwnerToDmsfLock: reverting ===============================
-- remove_column(:dmsf_locks, :owner, :string, {:null=>true})
   -> 0.0263s
== 20210115120901 AddOwnerToDmsfLock: reverted (0.0265s) ======================

== 20200813075501 ChangeIndexInDmsfLocks: reverting ===========================
-- remove_index(:dmsf_locks, [:entity_id, :entity_type])
   -> 0.0109s
-- add_index(:dmsf_locks, :entity_id)
   -> 0.0156s
== 20200813075501 ChangeIndexInDmsfLocks: reverted (0.0266s) ==================

== 20200423071301 AddIndexesOnDmsfFolderId: reverting =========================
-- remove_index(:dmsf_links, :dmsf_folder_id)
   -> 0.0419s
-- remove_index(:dmsf_files, :dmsf_folder_id)
   -> 0.0117s
== 20200423071301 AddIndexesOnDmsfFolderId: reverted (0.0538s) ================

== 20200218142414 AddIndexOnDmsfFileRevisionIdToAccess: reverting =============
-- remove_index(:dmsf_file_revision_accesses, :dmsf_file_revision_id)
   -> 0.0284s
== 20200218142414 AddIndexOnDmsfFileRevisionIdToAccess: reverted (0.0286s) ====

== 20192703123101 WorkflowStartedBy: reverting ================================
-- rename_column(:dmsf_file_revisions, :dmsf_workflow_started_by_user_id, :dmsf_workflow_started_by)
   -> 0.0174s
-- rename_column(:dmsf_file_revisions, :dmsf_workflow_assigned_by_user_id, :dmsf_workflow_assigned_by)
   -> 0.0470s
== 20192703123101 WorkflowStartedBy: reverted (0.0647s) =======================

== 20180903132101 FastLinks: reverting ========================================
-- remove_column(:members, :dmsf_fast_links, :boolean, {:default=>false, :null=>false})
   -> 0.0148s
== 20180903132101 FastLinks: reverted (0.0150s) ===============================

== 20180216152501 RenameTitleFormat: reverting ================================
-- rename_column(:members, :dmsf_title_format, :title_format)
   -> 0.0163s
== 20180216152501 RenameTitleFormat: reverted (0.0164s) =======================

== 20171110155901 AddIndexToDmsfFolder: reverting =============================
-- remove_index(:dmsf_folders, :dmsf_folder_id, {:name=>"index_dmsf_folders_on_dmsf_folder_id"})
   -> 0.0120s
== 20171110155901 AddIndexToDmsfFolder: reverted (0.0149s) ====================

== 20171027124101 ChangeRevisionDigestLimitTo64: reverting ====================
== 20171027124101 ChangeRevisionDigestLimitTo64: reverted (0.0000s) ===========

== 20170526144701 DmsfAttachable: reverting ===================================
-- remove_column(:projects, :dmsf_act_as_attachable)
   -> 0.0149s
== 20170526144701 DmsfAttachable: reverted (0.0150s) ==========================

== 20170422104901 MigrateDocuments: reverting =================================
[manual deleted lines, because it where many linses, but this step worked fine]
== 20170422104901 MigrateDocuments: reverted (13.2987s) =======================

== 20170421101901 DmsfFileContainerRollback: reverting ========================
-- index_exists?(:dmsf_files, :project_id, {:name=>"index_dmsf_files_on_project_id"})
   -> 0.0013s
-- remove_index(:dmsf_files, :project_id, {:name=>"index_dmsf_files_on_project_id"})
   -> 0.0118s
-- rename_column(:dmsf_files, :project_id, :container_id)
   -> 0.0128s
-- add_column(:dmsf_files, :project_id, :int, {:null=>true})
   -> 0.0122s
-- add_column(:dmsf_files, :container_type, :string, {:limit=>30, :null=>false, :default=>"Project"})
   -> 0.0125s
-- remove_column(:dmsf_files, :project_id)
   -> 0.0115s
-- index_exists?(:dmsf_files, [:container_id, :container_type], {:name=>"index_dmsf_files_on_container_id_and_container_type"})
   -> 0.0013s
-- add_index(:dmsf_files, [:container_id, :container_type])
   -> 0.0233s
-- remove_column(:dmsf_folders, :system)
   -> 0.0142s
== 20170421101901 DmsfFileContainerRollback: reverted (0.1312s) ===============

== 20170330131901 CreateDmsfFolderPermissions: reverting ======================
-- remove_index(:dmsf_folder_permissions, :dmsf_folder_id, {:name=>"index_dmsf_folder_permissions_on_dmsf_folder_id"})
   -> 0.0118s
-- drop_table(:dmsf_folder_permissions, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.0076s
== 20170330131901 CreateDmsfFolderPermissions: reverted (0.0237s) =============

== 20170323131231 DmsfDescriptionLimit: reverting =============================
-- change_column(:projects, :dmsf_description, :text)
   -> 0.0144s
-- change_column(:dmsf_folders, :description, :text)
   -> 0.0105s
== 20170323131231 DmsfDescriptionLimit: reverted (0.0251s) ====================

== 20170217141601 AddDmsfNotInheritableToCustomFields: reverting ==============
-- remove_column(:custom_fields, :dmsf_not_inheritable, :boolean, {:null=>true})
   -> 0.0141s
== 20170217141601 AddDmsfNotInheritableToCustomFields: reverted (0.0143s) =====

== 20170214153223 AddDmsfFileLastRevisionIdToDmsfLock: reverting ==============
-- rename_column(:dmsf_locks, :dmsf_file_last_revision_id, :revision)
   -> 0.0176s
== 20170214153223 AddDmsfFileLastRevisionIdToDmsfLock: reverted (0.0177s) =====

== 20170204214753 AddRevisionToDmsfLock: reverting ============================
-- remove_column(:dmsf_locks, :revision, :integer, {:null=>true})
   -> 0.0137s
== 20170204214753 AddRevisionToDmsfLock: reverted (0.0139s) ===================

== 20170118142001 DmsfFileContainer: reverting ================================
-- remove_index(:dmsf_files, [:container_id, :container_type], {:name=>"index_dmsf_files_on_container_id_and_container_type"})
   -> 0.0121s
-- remove_column(:dmsf_files, :container_type)
   -> 0.0114s
-- rename_column(:dmsf_files, :container_id, :project_id)
   -> 0.0126s
-- add_index(:dmsf_files, :project_id)
   -> 0.0214s
== 20170118142001 DmsfFileContainer: reverted (0.0673s) =======================

== 20170103164701 AddNameToAppovalWorkflowStep: reverting =====================
-- remove_column(:dmsf_workflow_steps, :name, :string, {:limit=>30, :null=>true})
   -> 0.0151s
== 20170103164701 AddNameToAppovalWorkflowStep: reverted (0.0153s) ============

== 20161223133200 CreateDmsfPublicUrls: reverting =============================
-- remove_index(:dmsf_public_urls, :token, {:name=>"index_dmsf_public_urls_on_token"})
   -> 0.0117s
-- drop_table(:dmsf_public_urls, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.0066s
== 20161223133200 CreateDmsfPublicUrls: reverted (0.0216s) ====================

== 20160421150501 AddDigestToRevision: reverting ==============================
== 20160421150501 AddDigestToRevision: reverted (0.0000s) =====================

== 20160222140401 ApprovalWorkflowStdFields: reverting ========================
-- remove_column(:dmsf_workflows, :updated_on)
   -> 0.0204s
-- remove_column(:dmsf_workflows, :created_on)
   -> 0.0135s
-- remove_column(:dmsf_workflows, :author_id)
   -> 0.0472s
== 20160222140401 ApprovalWorkflowStdFields: reverted (0.0814s) ===============

== 20160217133001 StatusDeleted: reverting ====================================
-- change_column(:dmsf_folders, :deleted, :boolean, {:null=>false, :default=>false})
   -> 0.0462s
-- change_column(:dmsf_files, :deleted, :boolean, {:null=>false, :default=>false})
   -> 0.0488s
-- change_column(:dmsf_file_revisions, :deleted, :boolean, {:null=>false, :default=>false})
   -> 0.0856s
-- change_column(:dmsf_links, :deleted, :boolean, {:null=>false, :default=>false})
   -> 0.0381s
== 20160217133001 StatusDeleted: reverted (0.2192s) ===========================

== 20160215125801 ApprovalWorkflowStatus: reverting ===========================
-- remove_column(:dmsf_workflows, :status)
   -> 0.0110s
== 20160215125801 ApprovalWorkflowStatus: reverted (0.0111s) ==================

== 20151209100001 TitleFormat: reverting ======================================
-- remove_column(:members, :title_format, :text, {:null=>true, :limit=>100})
   -> 0.0164s
== 20151209100001 TitleFormat: reverted (0.0166s) =============================

== 20151020141801 LargeFiles: reverting =======================================
-- change_column(:dmsf_file_revisions, :size, :int, {:null=>true})
   -> 0.0874s
== 20151020141801 LargeFiles: reverted (0.0876s) ==============================

== 20150910153701 TitleNotNull: reverting =====================================
-- change_column(:dmsf_file_revisions, :title, :string, {:null=>true})
   -> 0.1402s
== 20150910153701 TitleNotNull: reverted (0.1404s) ============================

== 20150202010301 AddUserToLinks: reverting ===================================
-- remove_column(:dmsf_links, :user_id, :integer)
   -> 0.0145s
== 20150202010301 AddUserToLinks: reverted (0.0147s) ==========================

== 20150130052716 AddExternal: reverting ======================================
-- remove_column(:dmsf_links, :external_url)
   -> 0.0458s
== 20150130052716 AddExternal: reverted (0.0459s) =============================

== 20150120152101 NotificationsNullable: reverting ============================
== 20150120152101 NotificationsNullable: reverted (0.0000s) ===================

== 20141205143001 RemoveUniquenessFromWf: reverting ===========================
== 20141205143001 RemoveUniquenessFromWf: reverted (0.0000s) ==================

== 20141015132701 RemoveFolderFromRevision: reverting =========================
-- add_column(:dmsf_file_revisions, :dmsf_folder_id, :integer, {:null=>true})
   -> 0.0154s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Validation failed: Name contains invalid character(s)
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/validations.rb:80:in `raise_validation_error'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/validations.rb:53:in `save!'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:302:in `block in save!'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize              '
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:302:in `save!'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/suppressor.rb:48:in `save!'
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20141015132701_remove_folder_from_revision.rb:33:in `block in down'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:71:in `block (2 levels) in find_each'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:71:in `each'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:71:in `block in find_each'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:138:in `block in find_in_batches'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:245:in `block in in_batches'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:229:in `loop'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:229:in `in_batches'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:137:in `find_in_batches'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:70:in `find_each'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/querying.rb:22:in `find_each'
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20141015132701_remove_folder_from_revision.rb:30:in `down'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:870:in `public_send'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:870:in `exec_migration'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:850:in `block in migrate'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:849:in `migrate'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1037:in `migrate'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1329:in `block in execute_migration_in_transaction'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1382:in `ddl_transaction'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1302:in `each'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1302:in `migrate_without_lock'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1251:in `block in migrate'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1397:in `with_advisory_lock'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1251:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:478:in `down'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1065:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:500:in `migrate_plugin'
/home/redmine/redmine/lib/redmine/plugin.rb:441:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:452:in `migrate'
/home/redmine/redmine/lib/tasks/redmine.rake:151:in `block (3 levels) in <top (required)>'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::RecordInvalid: Validation failed: Name contains invalid character(s)
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/validations.rb:80:in `raise_validation_error'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/validations.rb:53:in `save!'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:302:in `block in save!'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize              '
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:302:in `save!'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/suppressor.rb:48:in `save!'
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20141015132701_remove_folder_from_revision.rb:33:in `block in down'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:71:in `block (2 levels) in find_each'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:71:in `each'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:71:in `block in find_each'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:138:in `block in find_in_batches'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:245:in `block in in_batches'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:229:in `loop'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:229:in `in_batches'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:137:in `find_in_batches'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:70:in `find_each'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/querying.rb:22:in `find_each'
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20141015132701_remove_folder_from_revision.rb:30:in `down'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:870:in `public_send'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:870:in `exec_migration'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:850:in `block in migrate'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:849:in `migrate'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1037:in `migrate'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1329:in `block in execute_migration_in_transaction'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1382:in `ddl_transaction'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1302:in `each'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1302:in `migrate_without_lock'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1251:in `block in migrate'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1397:in `with_advisory_lock'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1251:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:478:in `down'
/var/lib/gems/3.0.0/gems/activerecord-6.1.7/lib/active_record/migration.rb:1065:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:500:in `migrate_plugin'
/home/redmine/redmine/lib/redmine/plugin.rb:441:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:452:in `migrate'
/home/redmine/redmine/lib/tasks/redmine.rake:151:in `block (3 levels) in <top (required)>'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
root@hostname:/home/redmine/redmine#
`
Is there a solution for this?

Many thanks in advance and best regards
Andreas

Edit:
Environment:
  Redmine version                5.0.4.stable
  Ruby version                   3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  6.1.7
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Kgu_training
SCM:
  Git                            2.34.1
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   3.0.7

**Comment by picman** [comment]
Could you retry it with the _devel_ branch?

**Comment by picman** [comment]
Hm, probably the migrations are in a bad state due to the previous error. I suggest restoring the database from a backup and run it again. 
Concerning the _devel_ branch it is easier to work directly with git:
```shell
cd plugins
rm -r redmine_dmsf
git clone https://github.com/danmunn/redmine_dmsf.git
cd redmine_dmsf
git checkout devel
```

**Comment by Andreas3C** [comment]
I'll try and come back to you. Thank you!
