### ISSUE TITLE
Cannot map webdav in windows 

### ISSUE THREAD

**Issue by nanaksingh13** [danmunn/redmine_dmsf#1440]
webdav works in browser and webdav clients like Winscp and other thirdparty software but it does not work with windows

**Comment by nanaksingh13** [comment]
webdav works in browser and webdav clients like Winscp and other thirdparty software but it does not work with windows

**Comment by picman** [comment]
Usual problem in MS Windows is that Redmine is not run over HTTPS. Because, MS Windows doesn't support basic authentication over HTTP. Cannot it be also your case too?

**Comment by nanaksingh13** [comment]
Yes my Redmine is running on http. So, is there any fix to mapping

**Comment by picman** [comment]
Yes, it is. Move it to HTTPS.
