### ISSUE TITLE
Cannot map webdav in windows even in https

### ISSUE THREAD

**Issue by nanaksingh13** [danmunn/redmine_dmsf#1441]
webdav works in browser and webdav clients like Winscp and other thirdparty software but it does not work with windows.

**Comment by picman** [comment]
Post some screenshots an production.log.

**Comment by nanaksingh13** [comment]
![Untitled](https://user-images.githubusercontent.com/66524832/228446369-7084b55a-c9ce-4c29-8546-db77a7c788e3.jpg)

**Comment by nanaksingh13** [comment]
I couldn't find any logs related to this in production.log

**Comment by mmundi72** [comment]
Maybe you should check if the Windows Service "WebClient" is running on your machine or not. If it is not running then WebDav won't work.

**Comment by picman** [comment]
Really, an excellent screenshot... URL hidden by error message that the URL is wrong.

**Comment by picman** [comment]
I've a positive experience with usage of the link at the bottom of the mapping form.
![image](https://user-images.githubusercontent.com/779003/228480820-3cb8896e-952b-4c6b-9589-b4c3a5aff55e.png)

**Comment by nanaksingh13** [comment]
my url was http://192.168.0.203/redmine/dmsf/webdav/ i tried https://192.168.0.203/redmine/dmsf/webdav/

**Comment by nanaksingh13** [comment]
can you confirm that dmsf's WebDAV mapping is working on your machine

**Comment by mmundi72** [comment]
I can confirm that this is working on my machine. Here a screenshot - Windows 11, but it's als working on Windows 10:

<img width="701" alt="webdav" src="https://user-images.githubusercontent.com/7224922/228559174-3fa90d72-feea-4701-b37e-4cc345b7a0c9.png">

We also had this issue but it was always related to the Windows Service "WebClient" as mentioned above.

**Comment by nanaksingh13** [comment]
@mmundi72  I think I'm also facing same issue can explain how did you resolve the problem.

**Comment by mmundi72** [comment]
As mentioned above: make sure that the Windows Service "WebClient" is running. Start "Computer Management" -> Services -> Look for "WebClient". Should be running! Here is a screenshot (sorry, it's in German):

![grafik](https://user-images.githubusercontent.com/7224922/228741727-bb484b99-a1fa-4a26-bc73-4344f533d9d2.png)

**Comment by jmgomez-IAA** [comment]
Sorry didn't know, does it apply to Linux?  I have tried in some linux machines (Fedora and ArchLinux) and it complains the same way.

``sudo mount -t davfs http://udit7.iaa.es:3180/dmsf/webdav/ /mnt --verbose
Please enter the username to authenticate with server
http://udit7.iaa.es:3180/dmsf/webdav/ or hit enter for none.
  Username: jmgomez
Please enter the password to authenticate user jmgomez with server
http://udit7.iaa.es:3180/dmsf/webdav/ or hit enter for none.
  Password:
/usr/bin/mount.davfs: Mounting failed.
501 Not Implemented``

My experience is limited with this things, any advise? I have followed the installation instructions. I am using the official redmine image at dockerhub:

```
Environment:
  Redmine version                5.0.5.stable
  Ruby version                   3.1.3-p185 (2022-11-24) [x86_64-linux]
  Rails version                  6.1.7.2
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Subversion                     1.14.1
  Mercurial                      5.6.1
  Bazaar                         3.1.0
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.6.4
  redmine_dmsf                   3.0.12

```

**Comment by nanaksingh13** [comment]
use https to connect windows with WebDAV. I used WinSCP to check my http WebDAV was working. there are other 3rd party software that will help you map http drive to windows. hope this was helpful to you
