### ISSUE TITLE
Is there a side effect of removing # symbol from INVALID_CHARACTERS ?

### ISSUE THREAD

**Issue by zheng-wei-wu** [danmunn/redmine_dmsf#1442]
Due to the usage requirements, the uploaded filename will need to include the # symbol. However, will removing the # symbol from INVALID_CHARACTERS cause any other side effects in the whole system ?

**Comment by picman** [comment]
Probably not.

**Comment by zheng-wei-wu** [comment]
> Probably not.

Thank you for the information !
