### ISSUE TITLE
uncompare with plugins additionals

### ISSUE THREAD

**Issue by AndreySolod** [danmunn/redmine_dmsf#1447]
Good day.
Apparently, the part of the functionality responsible for xapian is incompatible with the plugins "Additionals" and "Additional_tags": when using ruby, xapian_indexer.rb returns the following error:

![image](https://user-images.githubusercontent.com/32464577/232190158-8b96593f-8fb1-42ca-b4ab-a7c2b3a35728.png)

There are no other problems related to the installation or use of the plugin.
Is there any way to fix this error? There are no conflicts with other plugins.
Redmine v 5.0.5, ruby v3.0.4p208, ubuntu 22.10

**Comment by picman** [comment]
Duplicates #1305.
