### ISSUE TITLE
Lost attachment on bulk edit

### ISSUE THREAD

**Issue by lyollix** [danmunn/redmine_dmsf#1449]
When we change the project_id of issues on the bulk editing form, 
all attachments are lost.

This happens because hook 
controller_issues_bulk_edit_after_save 
is missing in Redmine.

Need an alternative solution.

Is it possible to take out the attachment code to hook
controller_issues_before_save 
if not Easy Redmine?

**Comment by picman** [comment]
I will look at it later.

**Comment by picman** [comment]
A good catch and a simple solution suggested. Thank you.
