### ISSUE TITLE
After file convert view permissions missing

### ISSUE THREAD

**Issue by Rocksau80** [danmunn/redmine_dmsf#1454]
After converting the documents to DMSF all folders are missing the permissions.
I have to change permissions for every folder in a project so that users can see the files. Is there a rake task for that? Or did I miss something during conversion?
Folders are showed as created by anonymous while the files are showed as created by uploader. But the checkboxes for the permission groups are empty for every folder.

**Comment by picman** [comment]
1. Folder permissions is an extension. They are empty as default. Access to  folders is driven by rights to the project. If you want to limit access to a certain folder, you can specify it with the folder permissions.
2. Each file can have different author. Who should be then the author of the folder?

**Comment by Rocksau80** [comment]
Thank you very much for your efforts. I tried the workflow again during the weekend with the same result.
I used `rake redmine:dmsf_convert_documents issues=1 dry_run=1 RAILS_ENV="production"` and it went through without any errors. But the documents were already converted even if I set dry_run=1. After that only for my administrator account the files were visible. All other users couldn't see any file no matter which privilege they had for DMS.
I also found something in the wiki: [here](https://github.com/danmunn/redmine_dmsf/wiki/Migrating-from-Documents-to-DMSF) it says the syntax is `dry=true` but [here](https://github.com/danmunn/redmine_dmsf#setup--upgrade) in point 11 it says `dry_run=1`.

**Comment by picman** [comment]
I've fixed several problems there. It should work now. Concerning `dry_run`, it doesn't matter what is there. It checks whether it is  empty.

**Comment by Rocksau80** [comment]
Looks very promising right now. Files are converted and accessible for the users. I'm doing some more tests here.

**Comment by picman** [comment]
Files attached to issues are independent on Files module. I think that in Redmine is no such option to disable attachments for issues. Maybe we could extend the pick list to serve third option "Documents only" and hide the Files upload area then.

**Comment by Rocksau80** [comment]
I guess I'll open a discussion and/or ticket on the Redmine page about that. It's a bit confusing that if I disable the files and the documents module users still are able to upload stuff. Normally I would disable files for a reason - at the moment because there is a way better option to handle files called DMSF.
