### ISSUE TITLE
Wiki Macros present a 'http' link regardless of whether redmine is configured for http or https

### ISSUE THREAD

**Issue by dbodorkos** [danmunn/redmine_dmsf#1457]
I have an issue where users attempting to download a dmsf file from a wiki page are getting the following error:

![image](https://github.com/danmunn/redmine_dmsf/assets/18393287/622bfad1-58d7-4084-a2ed-2e58206476d7)

On inspecting the link in chrome, it shows that the links generated by the dmsf macro are http only:

The wiki links are being setup as follows:

![image](https://github.com/danmunn/redmine_dmsf/assets/18393287/4ecbd4a2-488b-41bd-9935-a84ad0e9c0da)

When inspecting these links on the published wiki page, I am seeing the following:

![image](https://github.com/danmunn/redmine_dmsf/assets/18393287/e35d6dba-2eab-4c05-b211-431d05210c0f)

Redmine protocol settings set to https:

![image](https://github.com/danmunn/redmine_dmsf/assets/18393287/e9821c0d-f30b-4f3c-8e5b-b54d4a8e7020)

Version Details:
Redmine version 5.04.stable
DMSF version 3.0.8

I have tested DMSF version 3.0.12 in a test environment, but the behaviour is the same.

**Comment by picman** [comment]
I'd consider this as fixed then.
