### ISSUE TITLE
V3.0.13 update error: Error in bundle plugins vault&dashboard

### ISSUE THREAD

**Issue by marmat1** [danmunn/redmine_dmsf#1458]
It is possible to add add a condition for these plugins, or must I change the plugins Gemfile?

[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice coming from different sources.
You specified that rake (>= 0) should come from an unspecified source and locally installed gems
. Bundler cannot continue.

from /opt/redmine/plugins/redmine_dmsf/Gemfile:26
 >    gem 'rake'

from /opt/redmine/plugins/redmine_dmsf/Gemfile:29
 >    gem 'zip-zip'

/opt/redmine/plugins/vault/Gemfile:20:gem 'zip-zip'
/opt/redmine/plugins/redmine_dashboard/Gemfile:8:gem 'rake'

**Comment by picman** [comment]
Which condition? I don't know how to solve it but to comment out `gem 'rake'` in one of the plugin's _Gemfile_.

**Comment by marmat1** [comment]
To be honest... no idea about which condition, I just read it in: https://github.com/danmunn/redmine_dmsf/issues/1387#issuecomment-1209312451
and I supposed you have a way to to that...
I will comment the line in the Gemfile. 
Thanks!

**Comment by picman** [comment]
You are right. We can add a condition for existence of _redmine_dashboard_ plugin.

**Comment by picman** [comment]
If you wish to fix it using a condition in the _Gemfile_, reopen the issue.

**Comment by marmat1** [comment]
There are two duplicated gems:
rake -> redmine_dashboard -> https://github.com/jgraichen/redmine_dashboard
ip-zip -> vault -> https://github.com/noshutdown-ru/vault 

Thanks!
