### ISSUE TITLE
Upload new revision content via API

### ISSUE THREAD

**Issue by kty0mka** [danmunn/redmine_dmsf#1463]
Hi!

As I understand REST API Specification, it is possible to upload new file via API and it is possible to create new file revision.

Is it possible to create new revision with new file (attachment) content via REST API?
In other words, it would be useful to upload new attachment, but commit it not to a new file, but to a new revision of existing file.

Thanks!

**Comment by picman** [comment]
Yes, it is. If the filename is identical, just a new revision of an existing document is created the same way as in GUI. (# 3. Upload a document in _extra/api_client.sh_)

**Comment by kty0mka** [comment]
Thanks! It was not obvious to me. Maybe it makes sense to add an explicit mention of this feature in the specification?

**Comment by picman** [comment]
I've updated the wiki page accordingly.
