### ISSUE TITLE
WebDAV created links is undesirably pointing to port 80

### ISSUE THREAD

**Issue by Raw1mage** [danmunn/redmine_dmsf#1467]
Here I show a screen shot, 
wherein the framework gives wrong links (port 80) when directing to other folders.
This happens not only to "link to upper folder" but also other project folders.
I'm not sure if this is a misconfiguration or bug.
There's no where in the system to configure port 80.
![image](https://github.com/danmunn/redmine_dmsf/assets/40973866/4f96b412-4d9a-445c-af36-5ba457a93a67)

Great Plugin anyway, and I appreciate the team's work.

**Comment by picman** [comment]
Please check the protocol in the settings.
![image](https://github.com/danmunn/redmine_dmsf/assets/779003/ac245cbd-6dfd-4199-a2ea-d1850d81bf14)

**Comment by Raw1mage** [comment]
Thanks for the kind reply.
The settings was already https when the bug happens.
![image](https://github.com/danmunn/redmine_dmsf/assets/40973866/5178790e-198e-4a34-8c77-3d4bd601d9d0)

I'm wondering the number ":80" comes from inside the codes.
Since my redmine box is a docker image running on port 3000, mapped to port 3434 of the host, and all requests coming from public IP port 443 are proxy_forwarded to that port 3434.   
There is no related to ":80" in my configuration.

**Comment by Raw1mage** [comment]
and I assume this is the same bug causing Windows 10 unable to access the webdav url.

**Comment by picman** [comment]
Please follow my recommendation for #1468.
