### ISSUE TITLE
Created folder IDs are erroneously associated to issue IDs

### ISSUE THREAD

**Issue by Raw1mage** [danmunn/redmine_dmsf#1468]
I just created some folders, and the document listing function shows irrelevant issue links.
As depicted below.

![image](https://github.com/danmunn/redmine_dmsf/assets/40973866/279f99fc-7ce7-4942-9feb-7c29e039e974)

**Comment by picman** [comment]
This is a very odd behaviour which I'm not able to reproduce. You have to investigate it yourself. I would start with removing all other plugins but DMSF. If it is alright with DMSF as the only plugin, I'd add one plugin after another and test it. There is probably a conflict between DMSF and another plugin.

**Comment by Raw1mage** [comment]
Thanks for the direction, picman.
Regarding the errnoneous link in the file id, 

**redmine_wk_time plugin is the source of conflict.**

I can't replicate the port 80 problem from a fresh installed docker.  
Will look for  an nginx rewrite solution.

I respectfully hope this would contribute to the development work.
Thank you.
