### ISSUE TITLE
Getting DMSF to view files of Asia fonts

### ISSUE THREAD

**Issue by Raw1mage** [danmunn/redmine_dmsf#1471]
I'm not sure if this is a bug or just configuration.
My system runs with locale=zh-TW
and dmsf does not show file views as expected.

relative fonts are installed.
apt install fonts-wqy-zenhei fonts-arphic-ukai fonts-arphic-uming fonts-arphic-gbsn00lp fonts-arphic-gkai00mp

As a benchmark, the other plugin redmine_more_preview works fine under the same box, which also employs libreoffice packages.

![image](https://github.com/danmunn/redmine_dmsf/assets/40973866/bc1d20c6-57d9-406c-b36f-6461ce1fc0d8)

Any enlightment ? Thanks

**Comment by picman** [comment]
Could you post here such a file to be able to test it locally?

**Comment by Raw1mage** [comment]
OK, 
I reupload the same file after the fonts are installed, the Chinese letters in the newly 
upload file are displayed normally.  Also I observed that the displayed view is acutally turning my doc into a pdf.  
Therefore it can be concluded as a configuration issue, where the fonts must be installed before the system converts any document.
