### ISSUE TITLE
Failed upgrade up to version 3.1.1 from version 3.0.12

### ISSUE THREAD

**Issue by dskibarko** [danmunn/redmine_dmsf#1472]
Hello!
Failed upgrade up to version 3.1.1 from version 3.0.12 bacause can't update xapian-ruby  after BUNDLE UPDATE command.

![xapian-ruby](https://github.com/danmunn/redmine_dmsf/assets/20500604/74b35c53-d69d-4fb6-8674-e58649ef068a)

Can you investigate situation and resolve?

**Comment by picman** [comment]
Obviously _ruby-xapian_ gem cannot be built in your Bitnami environment. Investigate the _gem_make.out_ file mentioned in the build output. Probably a library is missing in your system.

**Comment by dskibarko** [comment]
_Could you please help to investigate gem_make.out content below?_

**current directory: c:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/gems/xapian-ruby-1.4.22
c:/Bitnami/redmine-5.0.3-0/ruby/bin/ruby.exe -rrubygems c:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/gems/rake-13.0.6/exe/rake RUBYARCHDIR\=c:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/xapian-ruby-1.4.22 RUBYLIBDIR\=c:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/xapian-ruby-1.4.22
rake aborted!


Tasks: TOP => default
(See full trace by running task with --trace)
tar -xJf xapian_source/xapian-core-1.4.22.tar.xz
tar -xJf xapian_source/xapian-bindings-1.4.22.tar.xz
mkdir -p lib
sed -i".bak" -e "s/darwin\[91\]/darwin[912]/g" configure
./configure --prefix=c:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/gems/xapian-ruby-1.4.22 --exec-prefix=c:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/gems/xapian-ruby-1.4.22

rake failed, exit code 1**

**Comment by picman** [comment]
Hm, there are no useful information. I'd suggest installing a normal Linux server. You will save a lot of time.

**Comment by ahorek** [comment]
yes, Xapian doesn't support Windows at all, but DMS still does work without it, right?

this way it won't be installed on Windows
```ruby
gem 'xapian-ruby', platforms: [:mri]
```
but search features will be limited. If you need them, use WSL / VM. These are better options than Bitnami.

**Comment by picman** [comment]
I've added an option to call bundle install without Xapian and updated README accordingly. Would you be able to test the _devel_ branch on Windows?
```
bundle config set --local without 'xapian'
bundle install
```

**Comment by dskibarko** [comment]
After 
**bundle config set --local without 'xapian'** 
try to continue without paying attention to the message?

![bundle_devel_result1](https://github.com/danmunn/redmine_dmsf/assets/20500604/4227cf3f-b061-4af5-994c-b5c2a4708456)

**Comment by dskibarko** [comment]
And system is down... 
**rake redmine:plugins:migrate RAJLS_ENV=production** aborted
NameError: uninitialized constant redmine::plugin::setting

**Comment by dskibarko** [comment]
![bundle_devel_result2](https://github.com/danmunn/redmine_dmsf/assets/20500604/15000bd8-310e-4748-988b-1afe52b2804f)

**Comment by picman** [comment]
I think that you should keep your original setting too, so:

`bundle config set --local without 'xapian test development zip-zip sqlite`
