### ISSUE TITLE
I have a bug on create project or copy project

### ISSUE THREAD

**Issue by genzo76** [danmunn/redmine_dmsf#1475]
Have you idea why I have this problem?

The log to follow:

[e610c034-7145-4d15-9833-c7d2dbbad0a3] ActiveModel::UnknownAttributeError (unknown attribute 'dmsf_description' for Project.

          raise UnknownAttributeError.new(self, k.to_s)
          ^^^^^):
[e610c034-7145-4d15-9833-c7d2dbbad0a3]   
[e610c034-7145-4d15-9833-c7d2dbbad0a3] app/models/project.rb:120:in `initialize'
[e610c034-7145-4d15-9833-c7d2dbbad0a3] plugins/redmine_dmsf/lib/redmine_dmsf/patches/project_patch.rb:32:in `initialize'
[e610c034-7145-4d15-9833-c7d2dbbad0a3] app/models/project.rb:942:in `copy_from'
[e610c034-7145-4d15-9833-c7d2dbbad0a3] app/controllers/projects_controller.rb:147:in `copy'
[e610c034-7145-4d15-9833-c7d2dbbad0a3] lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**Comment by picman** [comment]
Have you run the plugin migration rake task?
`bundle exec rake redmine:plugins:migrate RAILS_ENV=production`

**Comment by picman** [comment]
No feedback => closing.
