### ISSUE TITLE
xo gem problem

### ISSUE THREAD

**Issue by leekwah** [danmunn/redmine_dmsf#1478]
I installed REDMINE on NAS through Docker.
The REDMINE version is 5.0.5, and I cloned the plug-in from git.

After entering the plugins directory through the root command,  `bundle install` 

The following error has occurred.
```bash
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=parent+directory+is+world+writable%2C+Bundler++FileUtils%23remove_entry_secure+does+not+work%3B+abort++%22%2Fusr%2Flocal%2Fbundle%2Fgems%2Fox-2.14.
```

I don't know what to do...
Please tell me what I should do.

**Comment by picman** [comment]
Take a look here for some useful tips.

https://github.com/rubygems/bundler/issues/4630
