### ISSUE TITLE
Cannot uninstall plugin

### ISSUE THREAD

**Issue by jmtemmos** [danmunn/redmine_dmsf#1479]
Cannot uninstall the plugin.

```
Environment:
  Redmine version                5.0.5.stable.22130
  Ruby version                   3.0.0-p0 (2020-12-25) [x86_64-linux]
  Rails version                  6.1.7.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
SCM:
  Subversion                     1.14.1
  Mercurial                      6.1.1
  Cvs                            1.12.13
  Bazaar                         3.2.1
  Git                            2.34.1
  Filesystem                     
Redmine plugins:
  additional_tags                3.0.9
  additionals                    3.0.9
  redmine_checklists             3.1.22
  redmine_dashboard              2.12.3
  redmine_db                     3.0.9
  redmine_dmsf                   3.1.2
  redmine_drawio                 1.4.7
  redmine_extended_watchers      5.0.2
  redmine_impersonate            2.0.0
  redmine_leaflet_maps           0.2
  redmine_privacy_terms          1.0.6
  redmine_web_forms              1.0.0
  redmine_wktime                 4.7
```

When running

> rake redmine:plugins:migrate NAME=redmine_dmsf VERSION=0 RAILS_ENV=production

got error :
> ActiveRecord::StatementInvalid: Mysql2::Error: Data truncated for column 'minor_version' at row 2158

When trying to work around the error by adapting the migration file, replacing 
>    change_column :dmsf_file_revisions, :minor_version, :integer, null: false
by:

>change_column_null :dmsf_file_revisions, :minor_version, false, 0 # set default as 0

in 20230105082201_null_minor_version.rb migration file, getting plenty of other errors in file :

20170421101901_dmsf_file_container_rollback.rb

**Comment by picman** [comment]
A very good catch and also a very good suggestion how to fix it. I've modified the code accordingly. If there are any other errors, please post them.
