### ISSUE TITLE
DMS Interface not displaying folders link

### ISSUE THREAD

**Issue by jmtemmos** [danmunn/redmine_dmsf#1480]
When clicking on DMF link (redmineurl/projects/projectname/dmsf)

Interface does not display correct folder id and navigation icons, as displayed in the image below

![image](https://github.com/danmunn/redmine_dmsf/assets/4980349/ff46bddb-79b2-4d0e-b155-8f5a104bd1da)

instead, files are listed as "issues"

Access to Webdav is working fine, though

**Comment by picman** [comment]
Could you post how does the same folder looks in via WebDAV?

**Comment by jmtemmos** [comment]
Sure.

In DMS interface:
![image](https://github.com/danmunn/redmine_dmsf/assets/4980349/42715f39-7f17-49f8-8ceb-3aa8a47d491f)

Webdav:
![image](https://github.com/danmunn/redmine_dmsf/assets/4980349/de3de26e-8d11-43f9-b82d-3d509a3e8502)

No hyperlink and if I display #, it points to issues instead of files/folder

**Comment by jmtemmos** [comment]
I think I found a hint.
It seems to be linked to ERPMine / wktime plugin.
When I remove it, hyperlinks appear again.

I do not know how to solve the incompatibility however....

Thanks for your support and your great plugin


Regards

**Comment by jmtemmos** [comment]
It is linked to the following issue :

https://github.com/danmunn/redmine_dmsf/issues/1468#issue-186061236

**Comment by picman** [comment]
There is not much I can do with that.
Duplicates #1468.
