### ISSUE TITLE
How to export full list with subfolders?

### ISSUE THREAD

**Issue by kyvaith** [danmunn/redmine_dmsf#1482]
I have a list with subfolders:

![image](https://github.com/danmunn/redmine_dmsf/assets/107579/2ad71bb6-620a-44e0-9d7b-58c347dbf5a4)

But in exported CSV I have only the root level listed:

![image](https://github.com/danmunn/redmine_dmsf/assets/107579/2c7b9d5d-fc9c-484a-8833-125c8872b517)

Thank you for any help.

**Comment by picman** [comment]
A CVS export contains only folders and documents on the current level. Sub-folders and their content is not exported. There is no option how to export a complete directory tree.

**Comment by kyvaith** [comment]
Hi @picman! Is is something planned? Is it possible to have a SQL query or any "backend" way from you to export such a list?

**Comment by picman** [comment]
As a workaround you can use a filter, e.q. 'Title = any'. Then you will see a complete list of folders and documents in the given project and you can export it as CSV.
![image](https://github.com/danmunn/redmine_dmsf/assets/779003/331c3ef5-1de2-4abb-9016-2465af2cf85f)
