### ISSUE TITLE
Release 3.1.2

### ISSUE THREAD

**Issue by deining** [danmunn/redmine_dmsf#1488]
The latest commit [cb72c2efbe](https://github.com/danmunn/redmine_dmsf/commit/cb72c2efbe56e1d0407f17650b3009d2b0789a6a) ist titled `v3.1.2 release`, but I cannot see a release 3.1.2 in the [release list](https://github.com/danmunn/redmine_dmsf/releases). And there is not tag `v3.1.2` either. Is that on purpose? Thanks for provoding and maintaining `redmine_dmsf`!

**Comment by picman** [comment]
You are right. I forgot to make a release. It is available now.
