### ISSUE TITLE
Release 3.1.2: wrong tag

### ISSUE THREAD

**Issue by deining** [danmunn/redmine_dmsf#1489]
Thanks for resolvong #1488 by adding release 3.1.2!

However, the tag assigned to this new release is [2.3.1](https://github.com/danmunn/redmine_dmsf/releases/tag/v2.3.1), while it should be 3.1.2. Can you please correct this? Thanks.

**Comment by picman** [comment]
Fixed.

**Comment by deining** [comment]
> Fixed.

Thanks!
