### ISSUE TITLE
Not sending documents when sender is set to user

### ISSUE THREAD

**Issue by GetxoSystems** [danmunn/redmine_dmsf#1494]
Last version of redmine with correct configured notifications, a user is specifically used to send notification: eredmineuser@ourdomain
Notifications work

When I send a document, the plugin has a setting (attached image) that if left empty means the sender is the user.
In this case the email is not sended, in exchange we see that correct authentication is done with  eredmineuser@ourdomain but no further comunication is logged in exchange, in redmine the log (even in debug) only gives 
*ERROR -- : Email delivery error: 501 5.1.7 Invalid address*

When changed the sender to eredmineuser@ourdomain, the email is sended correctly

![image](https://github.com/danmunn/redmine_dmsf/assets/152709240/4fab35d5-6188-4cc5-af18-0e7a84442bf2)

**Comment by picman** [comment]
What do you see in "Send documents by email" form? Has the currently logged user a valid email address?
![image](https://github.com/danmunn/redmine_dmsf/assets/779003/59c59355-12e5-4a4f-ab2a-b47c1f961dd2)

**Comment by GetxoSystems** [comment]
The user has a valid email (the email is valid and the email is on the profile), I tested from redmine with telnet to the exchange server with my own user and the server reports ok when I try to send in my own name.
From redmine web, when sending and debugging in exchange we saw correct logging with eredmineuser@ourdomain but no more traffic, and in any case more traffic
A screenshot of what I see. When the user is the user configured to notify redmine users it works (as in the image eredmineuser ), but when the real user logged in try to send files or links (it doesn't matter if you tick only links), error is submitted to log. 

![image](https://github.com/danmunn/redmine_dmsf/assets/152709240/1d8ed6b9-fb62-4073-bc85-d6866e6c745f)

Additional note: we don't use Textile so in any case the preview is undefined even if it sends the email correctly
![image](https://github.com/danmunn/redmine_dmsf/assets/152709240/12fe1604-86fc-4249-98cd-c92a312a28b1)
![image](https://github.com/danmunn/redmine_dmsf/assets/152709240/bed0b4af-7d8b-4642-8883-f7537558ddc7)

**Comment by picman** [comment]
1. Preview - fixed
2. You posted a screen-shot when the from field is set in the DMS options. Post a screen-shot when that option is empty and the current user is used for the from field. That's the case we need to investigate, right?

**Comment by GetxoSystems** [comment]
You're right. I found the problem. When importing family names (we use 2 in Spain) from our AD, there is a comma between them.
Removing the comma in the user profile solves the problem, and gives credit to the error message.
So I apologize because the mistake was mine.
Thanks for the support and thanks for supporting this awesome plugins

**Comment by picman** [comment]
No problem.
