### ISSUE TITLE
DMSF doesn't ignore filepattern when LOCK and UNLOCK requests.

### ISSUE THREAD

**Issue by hwiorn** [danmunn/redmine_dmsf#1495]
I tested latest DMSF with MacOS Sonoma and Bigsur. This issue is always happened. I think this is related to #1446.
DMSF ignores webdav file pattern when `PUT` requests, Correctly.
However, If the `LOCK` and `UNLOCK` are requested, the empty locked files going to be created and User can not delete it. These are like zombie files.

![SC 2023-12-20 PM 12 39 20](https://github.com/danmunn/redmine_dmsf/assets/1394254/498a5a56-4a27-48fe-ba95-a75d32a77d15)

Currently, there is no rake task for deleting corrupted documents. The only way is to delete those locked files forcefully.
```ruby
# Run this snippet in rails console.
DmsfFile.all.each do |f|
  if f.name.include? "DS_Store" or f.name.start_with? "._"
    # f.delete won't work because locked already.
    f.destroy
  end
end
```

Then, remove the files in DMSF.
```sh
bundle exec rake redmine:dmsf_maintenance RAILS_ENV="production"
```

I added the code to ignore the files like `PUT` in `LOCK` and `UNLOCK` method. So, the empty files have not been created.

```diff
diff --git a/plugins/redmine_dmsf/lib/redmine_dmsf/webdav/dmsf_resource.rb b/plugins/redmine_dmsf/lib/redmine_dmsf/webdav/dmsf_resource.rb
index 39f78c2..8bb364e 100644
--- a/plugins/redmine_dmsf/lib/redmine_dmsf/webdav/dmsf_resource.rb
+++ b/plugins/redmine_dmsf/lib/redmine_dmsf/webdav/dmsf_resource.rb
@@ -431,6 +431,14 @@ module RedmineDmsf

       # Lock
       def lock(args)
+        # Ignore file name patterns given in the plugin settings
+        pattern = Setting.plugin_redmine_dmsf['dmsf_webdav_ignore']
+        pattern = /^(\._|\.DS_Store$|Thumbs.db$)/ if pattern.blank?
+        if basename.match(pattern)
+          Rails.logger.info "#{basename} ignored"
+          return NoContent
+        end
+
         unless parent&.exist?
           e = Dav4rack::LockFailure.new
           e.add_failure @path, Conflict
@@ -503,6 +511,14 @@ module RedmineDmsf
       # Token based unlock (authenticated) will ensure that a correct token is sent, further ensuring
       # ownership of token before permitting unlock
       def unlock(token)
+        # Ignore file name patterns given in the plugin settings
+        pattern = Setting.plugin_redmine_dmsf['dmsf_webdav_ignore']
+        pattern = /^(\._|\.DS_Store$|Thumbs.db$)/ if pattern.blank?
+        if basename.match(pattern)
+          Rails.logger.info "#{basename} ignored"
+          return NoContent
+        end
+
         return super(token) unless exist?

         if token.blank? || (token == '<(null)>') || User.current.anonymous?
```

**Comment by picman** [comment]
Can't you create a pull request with those changes?

**Comment by picman** [comment]
I think that the suggested solution is not optimal as LOCK method is expected to create a nonexistent file according to WebDAV specification. I will have a look at it.

**Comment by picman** [comment]
It seems to be enough to apply your patch for LOCK request only. Could you test the _devel_ branch please?

**Comment by hwiorn** [comment]
Sorry for late reply. I was so busy. I think that pattern checking in LOCK request is enough. Because lock file creation is only inside LOCK method only. Thank you for the fix. I'll check it later when the new version is released.
