### ISSUE TITLE
Office files preview OK, but text and markdown file downloaded directly

### ISSUE THREAD

**Issue by chjq68** [danmunn/redmine_dmsf#1502]
Great plugin,thank you very much.
After struggle few days, I made this plugin work with redmine 5.1.1 very well.

when click document name, office files can be previewed by pdf.
text file and .md file is downloaded directly.

This is first time I use the plugin. I don't know it's the designed action, or my configure problem?
text  file and markdown file can be preview expected.

addtion: my redmine site behind nginx proxy.

**Comment by picman** [comment]
I can convert them to PDF and preview them the same ways as Office document or I can implement an embedded preview similar to Redmine's attachments. What do you think?

**Comment by picman** [comment]
Hm, probably better would be the embedded preview due to Redmine's macros in textile and markdown files.

**Comment by picman** [comment]
Text, Textile and Mardown files are now displayed inline.

**Comment by chjq68** [comment]
@picman sorry i notice the  upgrade right now. that's just i want. thank you very much! great ！
