### ISSUE TITLE
".Issues" folder visibility

### ISSUE THREAD

**Issue by Wrightie** [danmunn/redmine_dmsf#1504]
I'm using DMSF 3.0.12 with Redmine 5.0.5.
The ".Issues" folder popped up after a while, as users started to attach files to their issues.
I can see the ".Issues" folder as admin; some users can see it, some others can't (looks like a random behavior to me, but I don't know the rules driving the algo).
How can I set the folder visibility for all users?
Thank you in advance.

**Comment by picman** [comment]
Look for **Display system folders** in **_Administration->Roles&Permissions_**.

**Comment by Wrightie** [comment]
Worked like a charm.
Thanks a lot!
