### ISSUE TITLE
Compatibility Issue Fixed in dmsf_folder.rb with Custom Code on Redmine 5.1.1 with Ruby 3.0.6

### ISSUE THREAD

**Issue by Daugava** [danmunn/redmine_dmsf#1509]
Issue Title: Fixed Compatibility Issue in dmsf_folder.rb Module on Redmine 5.1.1 with Ruby 3.0.6

Description:
A specific issue was identified in the dmsf_folder.rb module of our Redmine 5.1.1.stable installation, running on Ruby version 3.0.6-p216 and Rails version 6.1.7.6, based on a Bitnami stack. Despite the Ruby environment supporting the intersect? method, we encountered errors in the permissions checking functionality of the document management system. It was observed that this issue does not occur when logged in as the Redmine administrator.

Log Fragment:
```
FATAL -- : [90f848df-9c28-43df-9510-106512e2ad9c]
[90f848df-9c28-43df-9510-106512e2ad9c] NoMethodError (undefined method `intersect?' for [4, 5, 6, 3]:Array Did you mean?  intersection):
[90f848df-9c28-43df-9510-106512e2ad9c] plugins/redmine_dmsf/app/models/dmsf_folder.rb:127:in `permissions?'

```
Original Code Snippet (Before):
In dmsf_folder.rb, the problematic section involved using intersect? method which unexpectedly led to errors despite the Ruby version compatibility.
`return true if role_ids.intersect?(role_permission_ids)`

Resolution:
The issue was resolved by implementing a custom solution provided by Chat-GPT, which involved modifying the code to use a combination of & and empty? methods for compatibility across Ruby versions.

Modified Code Snippet (After):
`return true unless (role_ids & role_permission_ids).empty?`

This change ensures that the permissions checking functionality works as expected without throwing errors related to the intersect? method, except when accessed under the Redmine administrator account, under which the issue does not manifest.

Affected Versions:

Redmine version: 5.1.1.stable
Ruby version: 3.0.6-p216 (2023-03-30) [x86_64-linux]
Rails version: 6.1.7.6
Environment: Based on Bitnami stack

**Comment by picman** [comment]
Duplicates #1500
