### ISSUE TITLE
dmsf macro not expanding inside tracker custom filed

### ISSUE THREAD

**Issue by andreav** [danmunn/redmine_dmsf#151]
Hi,
thank you for this plugin!

I'm wondering if it is possible to link to a document by means of {{dmsf(n)}} macro from inside a custom field.

I'm trying to substitute the built-in redmine file attachment mechanism.
I hope to build a centralised document repository; trackers will reference it.

At the moment, using a text or extended text field, the macro does not seem to be evaluated.

Do you know a solution/workaround?
Thank you!

Redmine version: 2.2.3.stable
redmine_dmsf:    1.4.5p1 stable

**Comment by picman** [comment]
duplicates #48
