### ISSUE TITLE
Those marked with a checkbox do not have access to files after 3.0.12 upgrade to 3.1.3 

### ISSUE THREAD

**Issue by dskibarko** [danmunn/redmine_dmsf#1512]
_Reprodused on 3.1.3(Master) and 3.1.4(Devel)._
### Scenario for reproduce:
1. Go to DMS menu in any project
2. Select folder and go to edit folder property 
3. Set the checkboxes for feature "Allow access only to" (for roles)

### Observed behavior:
If  version 3.0.12 DMSF used then roles (were checkboxes are set) have access to DMS  - correct behavior.
if version 3.1.3  DMSF (or 3.1.4 Devel) used and roles (were checkboxes are set) have not access to DMS - incorrect behavior. 
if version 3.1.3  DMSF (or 3.1.4 Devel) used and roles (were checkboxes are resets) there is access - behavior same as 3.0.12 DMSF version.

**Comment by picman** [comment]
I'm afraid that I can't reproduce it.

1. v3.0.12 -  Access to a certain folder is limited to Developer role only. Developers has access - Ok.
2. Upgrade to the current devel branch (3.1.4 devel) - Developers still has access to the folder - Ok.

Try to investigate it deeper. From my perspective it works well.

**Comment by dskibarko** [comment]
So far, I have removed all the checkboxes in the project where they are set. It's like an speed solution. 
There are no ideas on how to test deeper. 
Any ideas?

**Comment by picman** [comment]
Cannot reproduce.
