### ISSUE TITLE
New version: Error when create a version with custom field of "File" type

### ISSUE THREAD

**Issue by MorrisAsic** [danmunn/redmine_dmsf#1514]
Hi,
congratulations for your incredible plugin!

I have follow issue:

Following this path:
Open existing issue -> Edit -> Target Version -> Create new one with green button.

I have a "File" custom field that is not required but when i try to save version after enter the name, the system say me that the custom field is not valid.
I try to delete it and create another one but i obtain the same error ( only with "File" custom field ).

System informations:

Environment:
Redmine version 5.1.0.stable
Ruby version 3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]
Rails version 6.1.7.6
Environment production

SCM:
Mercurial 6.1.1
Git 2.34.1
Filesystem
Redmine plugins:
redmine_dmsf 3.1.3

**Comment by picman** [comment]
Isn't it related to #1517?

**Comment by MorrisAsic** [comment]
Yes! Thanks. 
I wait the 3.1.5 release.
