### ISSUE TITLE
The file is not uploaded to the custom file field

### ISSUE THREAD

**Issue by vvenslav** [danmunn/redmine_dmsf#1517]
Dear @picman, thanks a lot for useful plugins!

The following problem occurred when you upload a file to a custom file field, then when a new revision is created, it is not displayed in this field.
![file_1](https://github.com/danmunn/redmine_dmsf/assets/123180818/282ce7e4-21b2-4dc6-be25-8fa4c7c740e9)
![file_2](https://github.com/danmunn/redmine_dmsf/assets/123180818/09d367d1-4963-447e-95a5-9f0f02b495f4)

**Comment by picman** [comment]
Please describe the problem in more details. From your description it is not clear for me.

**Comment by picman** [comment]
Could you test it in the _devel_ branch, please?

**Comment by vvenslav** [comment]
> Could you test it in the _devel_ branch, please?

Yes! It's working!

**Comment by picman** [comment]
Excellent. Thank you for your feedback.

**Comment by vvenslav** [comment]
Thank you!
