### ISSUE TITLE
Cannot save file when lock timed out

### ISSUE THREAD

**Issue by OblongZebra** [danmunn/redmine_dmsf#152]
When a file was locked (by opening it in windows) and the timeout expires, the file doesn't show locked in the redmine UI, but when trying to save or lock in the file, I get an error. The database shows the lock is expired, but the lock is still set. Removing the lock from the locks table results in correct behaviour.

**Log**

    Started GET "/redmine/projects/ef/dmsf?folder_id=1" for 127.0.0.1 at 2013-09-12     10:46:33 +0200
    Processing by DmsfController#show as HTML
      Parameters: {"folder_id"=>"1", "id"=>"ef"}
      Current user: carla (id=4)
      Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (1.0ms)
      Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (1.0ms)
      Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (1.0ms)
      Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (1.0ms)
      Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (1.0ms)
      Rendered plugins/redmine_dmsf/app/views/dmsf/_multi_upload.html.erb (4.0ms)
      Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (159.0ms)
    Completed 200 OK in 260ms (Views: 198.0ms | ActiveRecord: 32.0ms)
    Started POST "/redmine/dmsf/files/101/lock" for 127.0.0.1 at 2013-09-12 10:46:39 +0200
    Processing by DmsfFilesController#lock as HTML
      Parameters: {"utf8"=>"✓",  "authenticity_token"=>"EteE9w41oxYBfr8g8YmjOAm3veAKsGYDM9XW98R9zjA=", "id"=>"101"}
      Current user: carla (id=4)
    Completed 500 Internal Server Error in 24ms

**Comment by picman** [comment]
No feedback so far => closing
