### ISSUE TITLE
[ ] in webdav paths seem to make issues with ms-office products

### ISSUE THREAD

**Issue by TheEmperator** [danmunn/redmine_dmsf#1522]
With one of the last versions redmine_dmsf introduced this symbols [ ] around project names in the webdav paths.
We since then have a lot of issues with ms-office saving to the connected webdav-folder. (LibreOffice is working just fine!)

Here is an example of such an error:
![image](https://github.com/danmunn/redmine_dmsf/assets/67643953/27bee82f-5eb7-4b3f-948c-414acc754ec8)
We checked all mentioned causes, but the third one "Path must not conain < > ? [ ] : | or *" is actually true.

The [ ] for the project names should be optional, to avoid this issue.
An according option for the configuration should be added, so you're backwards compatible, but people running into this issue, have the option to deactivate those symbols.

**Comment by picman** [comment]
Related to #1464
