### ISSUE TITLE
DMSF markup macros not in wiki help?

### ISSUE THREAD

**Issue by DirkHoffmann** [danmunn/redmine_dmsf#1524]
As opposed to the statement made [in the README](https://github.com/danmunn/redmine_dmsf?tab=readme-ov-file#linking-dmsf-object-from-wiki-entries-macros), I do not find any help about the (very much appreciated) *dmsf* macros in the wiki editor/toolbar. It would be nice to have a list elsewhere, and unless a quick fix can be found to make them available online, I list here, what I could extract from [macros.rb](https://github.com/danmunn/redmine_dmsf/blob/master/lib/redmine_dmsf/macros.rb).

* **dmsf** - (download) link to DMSF file
* **dmsff** - link to a folder
* **dmsfd** - link to document's details
* **dmsfdesc** - text referring to the document's description
* **dmfsversion** - text referring to the document's version
* **dmsflastupdate** - text referring to the document's last update timestamp
* **dmsft**  - link to the document's content preview
* **dmsf_image** - link to an image (restricted to some file formats)
* **dmsf_video**  - link to a video (restricted to some file formats)
* **dmsftn** - link to an image thumbnail (restricted to some file formats, obviously)
* **dmsfw** - link to a document's approval workflow status

Usage: {{*macro_name*(*dmsf_id*)}}, e.g. `{{dmsfd(1234)}}` for the link to the details of DMSF document 1234.

From what I understood, DMFS numbers (IDs) are unique, no project-prefix needed.
DMFS folder numbers use a separate, unique sequence.

**Comment by liaham** [comment]
Hi @DirkHoffmann ,

Did you notice that you can create a full list of all macros in any text field containing the wiki toolbar? 

You only need to add the macro `{{macro_list}}`  in a wiki page for example. This would be a quick first solution for your problem.

Best Regards,
@liaham

**Comment by DirkHoffmann** [comment]
Yes, that's an excellent first solution!

However, a search for "dmsf macros textile redmine" does not give a single useful result. (I ended up finding this github repo, which is the best I could find. And of course, I can do a look-in-the-sourcecode, which is the most reliable source of information.)
But I think it is still worth lowering the hurdle for Redmine users, who are not familiar with programming (in Ruby). So, unless there is a better solution already on the way, I would try to suggest an addition to the DMSF wiki (including correcting the link for cloning, which is outdated/dead). If OK, what would be the best way to do that?

**Comment by picman** [comment]
There is such a help in the wiki toolbar:
![image](https://github.com/danmunn/redmine_dmsf/assets/779003/21549831-f23e-4038-abbb-c606fe17bb41)
![image](https://github.com/danmunn/redmine_dmsf/assets/779003/afe6bbf6-4562-4fb5-ade5-787c4848896f)

**Comment by DirkHoffmann** [comment]
> There is such a help in the wiki toolbar: [...]

What is the prerequisite to have this available in the standard editor? The icon shown in your screenshot is not available on my instance:

![image](https://github.com/danmunn/redmine_dmsf/assets/1778649/30a0ffae-ce9a-4ff2-9383-2bfa3ede2ba5)

(And of course, that does not make it "googlable", even if it works in each Redmine instance.)

**Comment by DirkHoffmann** [comment]
Thanks for the indication. But would you mind to cite the URL of that ordinary HTML page here?

The first result close to a DMSF macro list that I get in a search for "redmine dmsf   help page" is [this one](https://groups.google.com/g/redmine-dmsf/c/hCMwv7QQe_0).

I get it also with the search term "redmine dmsf  macro  help page", in addition to this (wiki page)[https://hephaistos.lpp.polytechnique.fr/redmine/projects/instru/wiki/MacroList] based on a rather private initiative.

My point is that there should be an institutional DMSF-macro markup help page provided within the framework of this project. But I am done discussing. If you don't see the point, please close the ticket.
My offer to provide an update to the wiki of this project is still valid though (albeit a bit difficult to introduce through PR). Just let me know.
