### ISSUE TITLE
3.1.7 missing

### ISSUE THREAD

**Issue by J0WI** [danmunn/redmine_dmsf#1527]
Why have the release 3.1.7 been withdrawn?
Last week https://github.com/danmunn/redmine_dmsf/archive/v3.1.7.tar.gz worked just fine, now it's 404.
3.1.6 was somehow re-released two days ago. It appears that the commit history have been rewritten or at least the tags changed. What's the reason for this?

**Comment by picman** [comment]
The release 3.1.6 was named 3.1.7. So I removed it and created the same with the correct name 3.1.6 including tags.
