### ISSUE TITLE
How does the watcher feature work?

### ISSUE THREAD

**Issue by leushaka** [danmunn/redmine_dmsf#1530]
In the DMS permission 
These watchers options seem to have no effect? 
​​How do they work?

* View document's watchers
* Add document's watchers
* Delete document's watchers
* View folder's watchers
* Add folder's watchers
* Delete folder's watchers
* View project's watchers
* Add project's watchers
* Delete project's watchers

This is  my environment:
```
  Redmine version                5.1.3.stable
  Ruby version                   3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  6.1.7.8
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Tw-style (includes JavaScript)
SCM:
  Git                            2.34.1
  Filesystem                     
Redmine plugins:
  redmine_calendar_events_daily  0.0.2
  redmine_dmsf                   3.1.6
  redmine_issue_templates        1.1.2
  redmine_issues_panel           1.0.1
  redmine_issues_tree            0.0.15
  redmine_logs                   0.3.0
```

**Comment by picman** [comment]
Documents and folders of DMS are watchable the same way as issues for example. Permissions view/add/delete watchers correspond with availability of that functionality according to the user's role.

![image](https://github.com/danmunn/redmine_dmsf/assets/779003/07bb11d5-5939-4448-a1b5-2164a1340d58)

**Comment by leushaka** [comment]
Thank you for clearing up my doubts.
