### ISSUE TITLE
version 3.1.5(upper) doesn't convert office file to pdf preview

### ISSUE THREAD

**Issue by nreo** [danmunn/redmine_dmsf#1539]
version 3.1.5(upper) doesn't convert office file to pdf preview

3.1.5 add Setting file_max_size_displayed option to  app/models/dmsf_file.rb
but Redmine → settings → plug-in → dmsf configure not have does option
after update always office file just download, not preview(never convert)
in redmine setting have `Maximum size of text files displayed inline` but this option increase some side effect(maybe)

plz add option column in dmsf configure page for office file only
(now delete `&& size <= Setting.file_max_size_displayed.to_i.kilobyte` or increase max text files displayed inline size everything ok in 3.1.9)

![image](https://github.com/user-attachments/assets/d8e45306-2b5e-4225-82be-20b38d674686)

**Comment by picman** [comment]
It's taken from Redmine's settings and you can increase the value there.

![image](https://github.com/user-attachments/assets/7ba22149-bb49-4175-9077-02edb74d8df9)

**Comment by nreo** [comment]
thanks your explanation
but i think that max size separate office size & text size(just my opinion)
i will increase that's setting in my redmine, thank you agin

**Comment by picman** [comment]
I agree but I don't wont to overwhelm the settings with another item.
