### ISSUE TITLE
Activity stream is not showing the document name

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1540]
DMSF Version 3.0.6 - in Activity stream the name of an updated document was visible:
![grafik](https://github.com/user-attachments/assets/08f2f040-068b-484f-8aef-85d2ddce01fe)

Last week we updated to version 3.1.7 - the document name is not showing in activity stream:
![grafik](https://github.com/user-attachments/assets/39bb0eae-eb02-4fa9-86ea-6fe5d0374237)

**Comment by picman** [comment]
Fixed.
