### ISSUE TITLE
Missing Digest

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#1541]
Hi
With the new Digest Authentication I observed some strange behavior:
- I need to reset the digest about every other day  (logged in as a "normal" user)
- This morning I tried to checkout a document from DMSF and it was not working
- I checked the digest and I get the message that the digest is missing:

![grafik](https://github.com/user-attachments/assets/0c5b2745-61a8-4342-9c0c-1d848a6c399f)

Is the digest just valid for a certain time?
Why is the digest missing at all? 

If  I login a as an administrator it seems that the digest is automatically created after login. Because with an admin user I get the message that the digest has been created less than a minute ago.

**Comment by picman** [comment]
That's strange. The digest is never removed but reset when a user log in using login and password. That must be a bug. Could you check the log when you are logging in as the administrator and as an ordinary user? Are there any warnings or errors?

**Comment by mmundi72** [comment]
Could it be that my ordinary user is actually logged in since 18.07.2024 and with the admin user I logged in this morning:
![grafik](https://github.com/user-attachments/assets/2bc6a346-afdf-46e4-8b8b-7c4268c942c1)

**Comment by picman** [comment]
The digest is created either manually by the user in **My account** or automatically upon a login using login and password.

**Comment by mmundi72** [comment]
Yes, I know. I created the digest last week several time manually and so did I now. WebDav connection is now working after a manual reset. But I don't understand why it was missing this morning.
Could it be that I have activated the "stay connected" flag in the login screen for the ordinary user?

I try to get the log details - unfortunately I do not have access to these details by myself.

**Comment by picman** [comment]
I've just tested the case with an ordinary user and **Stay logged in** and found no issues.

**Comment by mmundi72** [comment]
I just rebooted my computer and started Firefox. It was working. But I am pretty sure that tomorrow it won't work unless I manually reset the digest. I will let you know.

**Comment by picman** [comment]
> Digest authentication: no digest found for MUIS

The digest is stored in _tokens_ table. E.g.:
```
MariaDB [redmine]> select * from tokens where user_id = 9 and action = 'dmsf-webdav-digest';
+---------+---------+--------------------+----------------------------------+---------------------+---------------------+
| id      | user_id | action             | value                            | created_on          | updated_on          |
+---------+---------+--------------------+----------------------------------+---------------------+---------------------+
| 1612950 |       9 | dmsf-webdav-digest | 9683b4************c844395ede85ba | 2024-07-19 14:19:28 | 2024-07-19 14:19:28 |
+---------+---------+--------------------+----------------------------------+---------------------+---------------------+
1 row in set (0,001 sec)
```
Check the database for your user and try to find out who is responsible for the fact that this value disapears.

**Comment by picman** [comment]
Any updates on the issue?

**Comment by mmundi72** [comment]
Unfortunately no. Due to the holiday season it's not easy to get the people to investigate this. 
What I can say is that the digest token seems to disapear after 48 hours. Therefore I've set the AutoLogin-Setting to 1 day so that every user has to manually login once a day. I will observe the impact of that change.

**Comment by picman** [comment]
Didn't you call the rake task `redmine:tokens:prune`? It seems that it deletes DMSF tokens older than one day.

**Comment by picman** [comment]
I've fixed it. Unfortunately, a database migration is needed. So, please test the _devel_ branch and don't forget to call `bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_dmsf`.

**Comment by picman** [comment]
As a workaround you can comment out calling the rake task `redmine:tokens:prune` in your cron.

**Comment by mmundi72** [comment]
Thank you for your work. I found the culprit with your hint concerning the rake task. We have updated to the latest "Automation Plugin" from Alphanodes and that plugin activated the rake task tokens:prune. That has been deactivated last week and this morning it was working as expected.
