### ISSUE TITLE
Webdav require authentication

### ISSUE THREAD

**Issue by patricklanvin** [danmunn/redmine_dmsf#1542]
Hi,

Thank you for the work on this plugin 👍 

i'm using digest authentication with the 3.2.0 version, unfortunately, an authentication windows open when i would edit a file.

My environment :
* Redmine 5 with docker container sameersbn/redmine:latest
* Active Directory user authentication

Logs indicates this :
![image](https://github.com/user-attachments/assets/5da38bdb-277b-48d8-955f-feec7ae1f53e)

An idea to guide me ?

Best regards,

Patrick

**Comment by picman** [comment]
I think that it's alright that you are asked to authorize prior editing a document. That's how it works.

**Comment by patricklanvin** [comment]
thank for your reply.

Maybe i don't understand something. I tried with my redmine login/pass but the authentication windows reappear each time.

In the log, authentication method is bearer, while i set it to Digest. Is is normal ?

Regards

**Comment by picman** [comment]
Check the **My account** whether you have got your personal DMSF digest generated.

**Comment by patricklanvin** [comment]
I was able to move forward with my problem. The login ID is case sensitive . It works now, but only with LibreOffice, I get an error message with MS Word. I continue to look for a solution :)

Thank

**Comment by patricklanvin** [comment]
My redmine is HTTP...
From https://github.com/danmunn/redmine_dmsf/issues/1024#issuecomment-513176803

I will try to activate HTTPS before to close this ticket.

**Comment by patricklanvin** [comment]
After some difficulty, I managed to get a windows explorer network drive to work.
2 key points in my context, client side Windows 11 :
- adding the certificate in "Trusted Root Certification Authorities" Certificate Store
- Activation of the DIGEST authentication in the registry (https://help.dreamhost.com/hc/en-us/articles/216473357-Accessing-WebDAV-with-Windows)

Best regards
