### ISSUE TITLE
New version: field "File" mandatory

### ISSUE THREAD

**Issue by MorrisAsic** [danmunn/redmine_dmsf#1547]
Hi,

i've create this issue #1514 but the problem persist.

Now the file is visible when save the new version but if the type field "File" is setted not mandatory, when save with no file attached, the system say that the field is not valid.

Environment:
  Redmine version                5.1.0.stable
  Ruby version                   3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  6.1.7.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Minimalflat2asiccustom (includes JavaScript)
SCM:
  Mercurial                      6.1.1
  Git                            2.34.1
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   3.2.1

<img width="454" alt="Image" src="https://github.com/user-attachments/assets/0144b1a1-b0c8-47eb-9419-eed85e5226db">

<img width="1055" alt="Image2" src="https://github.com/user-attachments/assets/ae5cda13-f72d-4867-9b1d-5ff38bc47923">

**Comment by picman** [comment]
Custom field format _File_ is Redmine's internal custom field and has nothing to do with DMSF plugin. The custom field related to DMSF is _DMS Document rev._
Check log/production.log for any relevant information.

**Comment by picman** [comment]
No feedback => closing.
