### ISSUE TITLE
Documents not deleted phisically from filesystem folder

### ISSUE THREAD

**Issue by robertova** [danmunn/redmine_dmsf#1549]
When i press delete document it´s deleted from redmine interface but not from filesystem. The default Documents module of redmine is working correctly and deleting. I have the same persmissions on redmine folders.

**Comment by picman** [comment]
If you delete a document, it's moved to the trash bin only. If you remove it from the trash bin, it is deleted from the file system.

**Comment by robertova** [comment]
I have tested it but although i´m emptying the recycle bin the documents are still on disk.

**Comment by picman** [comment]
**Physical file delete** plugin's option is on?

**Comment by robertova** [comment]
Oh my fault, sorry, that option was not checked. I´ve checked it and now is working as intended.
