### ISSUE TITLE
I Can't install the plugin in redmine

### ISSUE THREAD

**Issue by Adebar24** [danmunn/redmine_dmsf#1554]
Hallo,

i can't install the plugin "DMSF" to "redmine". I get no error message. I get only a list Gemfiles. I make the install over githu explanation.
The "Bundle install" only gives a list and the initialize/update database gives nothing.
I restartet the webserver new.

The Plugin is not in Administration -> Plugins.

When I use "git clone git@github.com:danmunn/redmine_dmsf.git" it says: Could not read from remote repository. So I used ""wget https://github.com/danmunn/redmine_dmsf/archive/master.zip". I unpack the file and rename the directory accordingly.

How can I install the plugin?
Nico Leiteritz

**Comment by picman** [comment]
```bash
cd redmine/plugins
git clone https://github.com/danmunn/redmine_dmsf.git
cd ..
bundle install
...
```

**Comment by Adebar24** [comment]
I was able to install DMSF. There are now more Gemfiles available.

But the database initialization went wrong:
`/var/opt/redmine/plugins/redmine_dmsf/app/validators/dmsf_file_name_validator.rb:23: warning: already initialized constant DmsfFileNameValidator::ALL_INVALID_CHARACTERS
/var/opt/redmine/plugins/redmie_dmsf_/app/validators/dmsf_file_name_validator.rb:23: warning: previous definition of ALL_INVALID_CHARACTERS was here
/var/opt/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/project_patch.rb:75: warning: already initialized constant Project::ATTACHABLE_DMS_AND_ATTACHMENTS
/var/opt/redmine/plugins/redmie_dmsf_/lib/redmine_dmsf/patches/project_patch.rb:75: warning: previous definition of ATTACHABLE_DMS_AND_ATTACHMENTS was here
/var/opt/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/project_patch.rb:76: warning: already initialized constant Project::ATTACHABLE_ATTACHMENTS
/var/opt/redmine/plugins/redmie_dmsf_/lib/redmine_dmsf/patches/project_patch.rb:76: warning: previous definition of ATTACHABLE_ATTACHMENTS was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/utils.rb:15: warning: already initialized constant Dav4rack::Utils::DEFAULT_HTTP_VERSION
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/utils.rb:15: warning: previous definition of DEFAULT_HTTP_VERSION was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:34: warning: already initialized constant Dav4rack::HttpStatus::STATUS_MESSAGES
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:34: warning: previous definition of STATUS_MESSAGES was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::Continue
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of Continue was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::SwitchingProtocols
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of SwitchingProtocols was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::Processing
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of Processing was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::OK
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of OK was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::Created
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of Created was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::Accepted
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of Accepted was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::NonAuthoritativeInformation
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of NonAuthoritativeInformation was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::NoContent
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of NoContent was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::ResetContent
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of ResetContent was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::PartialContent
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of PartialContent was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::MultiStatus
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of MultiStatus was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::MultipleChoices
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of MultipleChoices was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::MovedPermanently
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of MovedPermanently was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::Found
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of Found was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::SeeOther
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of SeeOther was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::NotModified
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of NotModified was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::UseProxy
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of UseProxy was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::TemporaryRedirect
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of TemporaryRedirect was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::BadRequest
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of BadRequest was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::Unauthorized
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of Unauthorized was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::PaymentRequired
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of PaymentRequired was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::Forbidden
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of Forbidden was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::NotFound
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of NotFound was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::MethodNotAllowed
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of MethodNotAllowed was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::NotAcceptable
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of NotAcceptable was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::ProxyAuthenticationRequired
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of ProxyAuthenticationRequired was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::RequestTimeout
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of RequestTimeout was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::Conflict
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of Conflict was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::Gone
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of Gone was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::LengthRequired
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of LengthRequired was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::PreconditionFailed
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of PreconditionFailed was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::RequestEntityTooLarge
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of RequestEntityTooLarge was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::RequestURITooLarge
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of RequestURITooLarge was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::UnsupportedMediaType
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of UnsupportedMediaType was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::RequestRangeNotSatisfiable
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of RequestRangeNotSatisfiable was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::ExpectationFailed
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of ExpectationFailed was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::UnprocessableEntity
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of UnprocessableEntity was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::Locked
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of Locked was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::FailedDependency
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of FailedDependency was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::InternalServerError
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of InternalServerError was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::NotImplemented
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of NotImplemented was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::BadGateway
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of BadGateway was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::ServiceUnavailable
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of ServiceUnavailable was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::GatewayTimeout
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of GatewayTimeout was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::HTTPVersionNotSupported
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of HTTPVersionNotSupported was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:89: warning: already initialized constant Dav4rack::HttpStatus::InsufficientStorage
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:89: warning: previous definition of InsufficientStorage was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/http_status.rb:83: warning: already initialized constant Dav4rack::HttpStatus::STATUS_CLASSES
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/http_status.rb:83: warning: previous definition of STATUS_CLASSES was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:6: warning: already initialized constant Dav4rack::XmlElements::DAV_NAMESPACE
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:6: warning: previous definition of DAV_NAMESPACE was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:7: warning: already initialized constant Dav4rack::XmlElements::DAV_NAMESPACE_NAME
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:7: warning: previous definition of DAV_NAMESPACE_NAME was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:8: warning: already initialized constant Dav4rack::XmlElements::DAV_XML_NS
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:8: warning: previous definition of DAV_XML_NS was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:9: warning: already initialized constant Dav4rack::XmlElements::XML_VERSION
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:9: warning: previous definition of XML_VERSION was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:10: warning: already initialized constant Dav4rack::XmlElements::XML_CONTENT_TYPE
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:10: warning: previous definition of XML_CONTENT_TYPE was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_ACTIVELOCK
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_ACTIVELOCK was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_DEPTH
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_DEPTH was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_ERROR
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_ERROR was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_HREF
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_HREF was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_LOCKDISCOVERY
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_LOCKDISCOVERY was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_LOCKENTRY
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_LOCKENTRY was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_LOCKROOT
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_LOCKROOT was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_LOCKSCOPE
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_LOCKSCOPE was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_LOCKTOKEN
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_LOCKTOKEN was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_LOCK_TOKEN_SUBMITTED
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_LOCK_TOKEN_SUBMITTED was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_LOCKTYPE
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_LOCKTYPE was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_MULTISTATUS
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_MULTISTATUS was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_OWNER
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_OWNER was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_PROP
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_PROP was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_PROPSTAT
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_PROPSTAT was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_RESPONSE
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_RESPONSE was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_STATUS
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_STATUS was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:32: warning: already initialized constant Dav4rack::XmlElements::D_TIMEOUT
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:32: warning: previous definition of D_TIMEOUT was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:35: warning: already initialized constant Dav4rack::XmlElements::INFINITY
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:35: warning: previous definition of INFINITY was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/xml_elements.rb:36: warning: already initialized constant Dav4rack::XmlElements::ZERO
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/xml_elements.rb:36: warning: previous definition of ZERO was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/resource.rb:361: warning: already initialized constant Dav4rack::Resource::DAV_PROPERTIES
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/resource.rb:361: warning: previous definition of DAV_PROPERTIES was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack/request.rb:137: warning: already initialized constant Dav4rack::Request::REDIRECTABLE_CLIENTS
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack/request.rb:137: warning: previous definition of REDIRECTABLE_CLIENTS was here
/var/opt/redmine/plugins/redmine_dmsf/lib/dav4rack.rb:35: warning: already initialized constant Dav4rack::IS_18
/var/opt/redmine/plugins/redmie_dmsf_/lib/dav4rack.rb:35: warning: previous definition of IS_18 was here
/var/opt/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:26: warning: already initialized constant RedmineDmsf::Webdav::AUTHENTICATION_RE                    ALM
/var/opt/redmine/plugins/redmie_dmsf_/lib/redmine_dmsf/webdav/custom_middleware.rb:26: warning: previous definition of AUTHENTICATION_REALM was here
/var/opt/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/webdav/base_resource.rb:32: warning: already initialized constant RedmineDmsf::Webdav::BaseResource::DIR_FIL                    E
/var/opt/redmine/plugins/redmie_dmsf_/lib/redmine_dmsf/webdav/base_resource.rb:32: warning: previous definition of DIR_FILE was here
rake aborted!
Child already added
/var/opt/redmine/lib/redmine/menu_manager.rb:386:in `add_at'
/var/opt/redmine/lib/redmine/menu_manager.rb:403:in `add'
/var/opt/redmine/lib/redmine/menu_manager.rb:321:in `push'
/var/opt/redmine/plugins/redmine_dmsf/after_init.rb:28:in `block in dmsf_init'
/var/opt/redmine/lib/redmine/menu_manager.rb:251:in `map'
/var/opt/redmine/plugins/redmine_dmsf/after_init.rb:27:in `dmsf_init'
/var/opt/redmine/plugins/redmine_dmsf/after_init.rb:124:in `<top (required)>'
/var/opt/redmine/plugins/redmine_dmsf/init.rb:70:in `require_relative'
/var/opt/redmine/plugins/redmine_dmsf/init.rb:70:in `<top (required)>'
/var/opt/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/var/opt/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/var/opt/redmine/lib/redmine/plugin_loader.rb:108:in `each'
/var/opt/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `instance_exec'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `catch'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:199:in `block in halting'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `each'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `invoke_before'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:105:in `run_callbacks'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:88:in `prepare!'
/var/lib/gems/2.5.0/gems/railties-6.1.6/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/var/lib/gems/2.5.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.5.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.5.0/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/2.5.0/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.5.0/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
/var/opt/redmine/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/2.5.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
/var/lib/gems/2.5.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.5.0/gems/railties-6.1.6/lib/rails/application.rb:367:in `require_environment!'
/var/lib/gems/2.5.0/gems/railties-6.1.6/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/var/lib/gems/2.5.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment'

The error message only came up because I had already done it once?

**Comment by picman** [comment]
Post an exact list of commands you call.

**Comment by Adebar24** [comment]
The exact list of command:
cd plugins
git clone https://github.com/danmunn/redmine_dmsf.git
cd ..
bundle install
RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf

**Comment by picman** [comment]
Looks good. Can you also post the contain of your plugn directory? 
`ls plugins`

**Comment by Adebar24** [comment]
`eka  README  redmine_dmsf  redmineup_tags`

**Comment by picman** [comment]
Hm, I don't know. The log suggests that it can't add Approval Workflow into the menu 'case it's already been added. It looks like the initialization is run twice.
