### ISSUE TITLE
The "Link from" doesn't work after upgrading the browsers.

### ISSUE THREAD

**Issue by Daugava** [danmunn/redmine_dmsf#1568]
The issue with the "Link from" function has been confirmed in the latest versions of Chrome, Edge, and Chromium browsers.

When the "Create a symbolic link" window is open and you change either the "Source project" or "Source folder," the "Source file" field is cleared.

**Comment by picman** [comment]
It has got its logic. If you choose a file to be linked and then you change the project or folder of that file, the field is cleared out because the location has changed. The Source file pick list is updated with the content of just selected project/folder.

**Comment by Daugava** [comment]
It has its logic, but after changing the project or folder, the file information is not updated with new data, and the field remains empty. This issue was not present in older browser versions.

**Comment by picman** [comment]
You mean that the pick list is empty and doesn't contain files from the changed project/folder?

**Comment by Daugava** [comment]
Yes, the pick list remains empty, and this behavior depends solely on the browser version.

**Comment by Daugava** [comment]
The pick list for "Source folder" has the same problem when you change the project, even if the starting project is the selected "Source project."

**Comment by picman** [comment]
I've just tested the _devel_ branch with the latest Chromium (Version 130.0.6723.116 (Official Build) snap (64-bit)) and can't reproduce the problem. In Firefox (132.0.2 (64-bit)) it works also fine, Safari too. What version of DMSF do you use?

**Comment by Daugava** [comment]
We have problem with: 
Chrome Version 131.0.6778.86 (Official Build) (64-bit)
Brave Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (64-bit)
Microsoft Edge Version 131.0.2903.70 (Official build) (64-bit)

The previous versions of these browsers and the latest version of Firefox do not reproduce the problem in our environment.

Redmine 5.1.1
DMFS version 3.1.3

**Comment by picman** [comment]
v3.1.3 is more than one year old. Upgrade to the latest stable release. Chromium in v3.2.4 works fine. Nobody will fix anything in v3.1.3.

**Comment by Daugava** [comment]
I was able to reproduce this issue in version 3.2.4 in our test environment.
Your version of Chromium (130.0.6723.116) isn't the latest.

**Comment by picman** [comment]
I'll try it.

**Comment by dimkaslav** [comment]
Bogged down by the same problem...

**Comment by picman** [comment]
I can confirm the problem in Version 131.0.6778.85 (Official Build) snap (64-bit).

**Comment by picman** [comment]
Fixed.
