### ISSUE TITLE
Proposal to modify the Gemfile files

### ISSUE THREAD

**Issue by kay54068** [danmunn/redmine_dmsf#166]
Proposal to modify the Gemfile files:

source 'https://rubygems.org'

gem 'rubyzip', '>= 1.0.0'
gem 'zip-zip' # Just to avoid 'cannot load such file -- zip/zip' error
gem 'simple_enum'
gem 'nokogiri', '>= 1.6.0'
gem 'uuidtools', '~> 2.1.1'

#Allows --without=xapian
group :xapian do
gem 'xapian-full', :require => false
end

**Comment by picman** [comment]
I've removed *nokogiri* from the *Gemfile*.
