### ISSUE TITLE
Document and Folder Access Control. This issue may be duplicated as I saw it on google code some time ago.

### ISSUE THREAD

**Issue by gogo52cn** [danmunn/redmine_dmsf#170]
Can DMSF team add the functionality to manage access control by document or by folder?
This issue may be duplicated as I saw it on google code some time ago.

**Comment by jmfarina** [comment]
I'm quite interested on this feature as well, and as someone else suggested, I would be willing to make a monetary contribution.

**Comment by kushlces** [comment]
Hi, we would like to use this functionality as well. Any chance, there will be work on this in future? Thanks for a great plugin.

**Comment by picman** [comment]
The plan is to add a possibility to assign roles to folders and consequently manage access by roles. It will have been implemented by the end of spring 2017.

**Comment by vsirvent** [comment]
Hi, we would also like this functionality. We will be happy to make some donation to get it.

**Comment by kushlces** [comment]
Sorry for delay - Thanks much picman for planning this feature. Really appreciate it. DMSF is really amazing and this feature will massively help us, so thanks in advance.

**Comment by picman** [comment]
I've just committed the first version. In the folder details form you can define roles or users for which the folder is visible. Test in devel-1.6.0 if you can.

**Comment by carukc** [comment]
Wow... fantastic news!  Thank you.  we will be testing too.

**Comment by paulaener** [comment]
Thank you so much for your time and effort.
Paula

**Comment by man2004** [comment]
Now this great commit can control if the folder is visible or not. Is there any plan to control if the folder is read / write accessible?

**Comment by picman** [comment]
Not yet, I'm afraid.

**Comment by picman** [comment]
User groups support added.
