### ISSUE TITLE
500 Internal Server Error in first page

### ISSUE THREAD

**Issue by river0825** [danmunn/redmine_dmsf#171]
I have error message like this when I go "http://10.113.11.207:3000/projects/myproject/dmsf"

NoMethodError (undefined method `visible' for #<Class:0x9d608cc>):
  activerecord (3.2.13) lib/active_record/dynamic_matchers.rb:55:in `method_missing'
  activerecord (3.2.13) lib/active_record/relation/delegation.rb:14:in `block in visible'
  activerecord (3.2.13) lib/active_record/relation.rb:241:in `block in scoping'
  activerecord (3.2.13) lib/active_record/scoping.rb:98:in `with_scope'
  activerecord (3.2.13) lib/active_record/relation.rb:241:in `scoping'
  activerecord (3.2.13) lib/active_record/relation/delegation.rb:14:in `visible'
  activerecord (3.2.13) lib/active_record/associations/collection_proxy.rb:100:in `method_missing'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:32:in `show'
  actionpack (3.2.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
 

bundler (1.3.5, 1.0.22)
rubyzip (1.0.0)
uuidtools (2.1.4)
simple_enum (1.6.7)

 Environment:
  Redmine version                          2.2.4.stable
  Ruby version                             1.9.3 (i686-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_code_review                      0.6.2
  redmine_dmsf                             1.4.6 stable
  redmine_screenshot_paste                 2.1.0
  redmine_wiki_extensions                  0.6.3

thanks

**Comment by picman** [comment]
Already solved in sope of #240 and #270.
