### ISSUE TITLE
Error 500 cannot access Administration -> Custom Fields page

### ISSUE THREAD

**Issue by agauba** [danmunn/redmine_dmsf#178]
Hi, 

I have recently installed the latest version of Redmine:
 Redmine version                2.4.0.stable
  Ruby version                   1.9.3-p448 (2013-06-27) [x86_64-linux]
  Rails version                  3.2.15
  Environment                    production
  Database adapter               Mysql2

When I install the dmsf plugin 1.4.6 (or even the devel-1.4.7), I cannot access the custom fields page in the Administration. It immediately give an Error 500. The logs shows the following error:

Rendered custom_fields/index.html.erb within layouts/admin (2.4ms)
Completed 500 Internal Server Error in 36.1ms

ActionView::Template::Error (uninitialized constant CustomField::CUSTOM_FIELDS_NAMES):
    1: <%= title l(:label_custom_field_plural) %>
    2:
    3: <%= render_tabs custom_fields_tabs %>
  app/views/custom_fields/index.html.erb:3:in `_app_views_custom_fields_index_html_erb__1873138176689810900_59710120'

Any support or help would be great. 

Thanks.

**Comment by zlinhng** [comment]
I got this problem with version 2.6.5
