### ISSUE TITLE
DMSF via reverse proxy

### ISSUE THREAD

**Issue by teleport789** [danmunn/redmine_dmsf#188]
Please help me, i installed Redmine 2.4.0 stable with dmsf plugin on MS Windows Server2008 using this tutorial http://www.redmine.org/boards/1/topics/32693, but instead apache  use IIS with reverse proxy. Redmine running local (127.0.0.1:3000) and configured with IIS reverse proxy to external address (redmine.example.com). The trouble is that plugin downloads documentation, but we couldnt download it because link to download doc in local (127.0.0.1:3000) not external (redmine.example.com). How we can fix it? Thank you!

**Comment by picman** [comment]
No feedback for quite a long time => closed
