### ISSUE TITLE
More than one file attached to same #id

### ISSUE THREAD

**Issue by tafkey** [danmunn/redmine_dmsf#189]
Would it be possible to have two alternative versions of a document attached at the same DMSF entry? The user story goes like this: 

> "As a user-manual maintainer I need to be able to upload the odt file along with the pdf file for a new version of the manual" (without the hassle for duplicating the information in two different DMSF entries).

**Comment by picman** [comment]
I think you ca create two revisions of the same document. One revision with ODT file and another one with PDF file.
