### ISSUE TITLE
unable to create Custom Field when DMSF plugin installed

### ISSUE THREAD

**Issue by dscott22099** [danmunn/redmine_dmsf#202]
Environment:
  Redmine version                2.4.1.stable
  Ruby version                   1.9.3-p231 (2012-05-25) [i386-mingw32]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.4
  Git                            1.8.3
  Filesystem
Redmine plugins:
  redmine_better_gantt_chart     0.9.0
  redmine_dmsf                   1.4.6 stable
  redmine_todos                  2.0.5

If I try to create a Custom Field, I get an error from Redmine that says:

Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error.

In the title bar of the browser is says http error 500.  I have created a clean production.log so it only contains the server starting, me trying to create a custom field, me selecting Workflow, then me trying to create a custom field again.  

Here is the log file:

Connecting to database specified by database.yml
Connecting to database specified by database.yml
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Started GET "/projects" for 127.0.0.1 at 2014-01-09 18:48:06 -0500
Processing by ProjectsController#index as _/_
  Current user: doug (id=3)
  Rendered projects/index.html.erb within layouts/base (171.9ms)
Completed 200 OK in 546.9ms (Views: 265.6ms | ActiveRecord: 171.8ms)
Started GET "/admin" for 127.0.0.1 at 2014-01-09 18:48:14 -0500
Processing by AdminController#index as HTML
  Current user: doug (id=3)
  Rendered admin/_menu.html.erb (15.6ms)
  Rendered admin/index.html.erb within layouts/admin (62.5ms)
  Rendered layouts/base.html.erb (250.1ms)
Completed 200 OK in 500.1ms (Views: 281.2ms | ActiveRecord: 93.8ms)
Started GET "/custom_fields" for 127.0.0.1 at 2014-01-09 18:48:20 -0500
Processing by CustomFieldsController#index as HTML
  Current user: doug (id=3)
  Rendered custom_fields/index.html.erb within layouts/admin (15.7ms)
Completed 500 Internal Server Error in 62.5ms

ActionView::Template::Error (uninitialized constant CustomField::CUSTOM_FIELDS_NAMES):
    1: <%= title l(:label_custom_field_plural) %>
    2: 
    3: <%= render_tabs custom_fields_tabs %>
  app/views/custom_fields/index.html.erb:3:in `_app_views_custom_fields_index_html_erb__1051345038_29869512'

Started GET "/workflows/edit" for 127.0.0.1 at 2014-01-09 18:48:30 -0500
Processing by WorkflowsController#edit as HTML
  Current user: doug (id=3)
  Rendered workflows/_action_menu.html.erb (0.0ms)
  Rendered workflows/edit.html.erb within layouts/admin (15.6ms)
  Rendered admin/_menu.html.erb (15.6ms)
  Rendered layouts/base.html.erb (31.3ms)
Completed 200 OK in 218.7ms (Views: 62.4ms | ActiveRecord: 125.0ms)
Started GET "/admin" for 127.0.0.1 at 2014-01-09 18:48:34 -0500
Processing by AdminController#index as HTML
  Current user: doug (id=3)
  Rendered admin/_menu.html.erb (15.6ms)
  Rendered admin/index.html.erb within layouts/admin (15.6ms)
  Rendered layouts/base.html.erb (31.3ms)
Completed 200 OK in 46.9ms (Views: 31.3ms | ActiveRecord: 15.6ms)
Started GET "/custom_fields" for 127.0.0.1 at 2014-01-09 18:48:37 -0500
Processing by CustomFieldsController#index as HTML
  Current user: doug (id=3)
  Rendered custom_fields/index.html.erb within layouts/admin (15.6ms)
Completed 500 Internal Server Error in 15.6ms

ActionView::Template::Error (uninitialized constant CustomField::CUSTOM_FIELDS_NAMES):
    1: <%= title l(:label_custom_field_plural) %>
    2: 
    3: <%= render_tabs custom_fields_tabs %>
  app/views/custom_fields/index.html.erb:3:in `_app_views_custom_fields_index_html_erb__1051345038_29869512'

If I remove the DMSF plugin, I have no problem creating custom fields.

Not sure if there is enough information here for this issue.  Thanks for anything you can do.

**Comment by zlinhng** [comment]
Environment:
Redmine version 2.6.5.stable
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
Rails version 4.2.1
Environment production
Database adapter Mysql2

Redmine plugins:
redmine_dmsf 1.5.1
luxury_bottons 2.0.1

If I try to create a Custom Field, I get an error from Redmine that says:
ActionView::Template::Error (undefined local variable or method `add_cf' for #<#<Class:0x007ff794f19850>:0x007ff794f18a18>):
    5: <%= title l(:label_custom_field_plural) %>
    6: 
    7: <% if @custom_fields_by_type.present? %>
    8:   <%= render_custom_fields_tabs(@custom_fields_by_type.keys) %>
    9: <% else %>
    10:   <p class="nodata"><%= l(:label_no_data) %></p>
    11: <% end %>
  app/views/custom_fields/index.html.erb:8:in `_app_views_custom_fields_index_html_erb___395616676009350123_70350666262960'

Someone could help would be great.

Thanks.
