### ISSUE TITLE
Required DMSF custom field prevents documents to be saved

### ISSUE THREAD

**Issue by maxrossello** [danmunn/redmine_dmsf#214]
If I create a required DMSF custom field then documents don't get uploaded and a message is displayed:

```
Some files were not commited due to validation errors: <name of file>
```

If I set the field as not required, everything goes fine.

Version: 1.4.7-stable, Redmine 2.4.2

**Comment by JuanceV20** [comment]
Good day, 

I have the same issue on Redmine V4.1 with the DMSF plugin. Please can you assist?

**Comment by picman** [comment]
Check the _production.log_ for any errors related to the upload.
