### ISSUE TITLE
Feature request: watchers for notifications email

### ISSUE THREAD

**Issue by GAnatoliy** [danmunn/redmine_dmsf#217]
Hello.

Now if notifications are enabled for file each users in project receive it. It isn't very convenient. 
Would be good to have something like "watching" system. 

Thanks.

**Comment by jaracic** [comment]
I saw in #557 a enhancement request for adding the "watch" paradigm on dmsf files... this request makes sense... but for the moment dsmf is based on a "permission" paradigm...
Now the question is how notification could be better managed : 
I personally think it could be relevant the notification recipient list  is defined as a "bitwise mask" of : 
* the list of project recipients (default list if no specific permission is defined)
* the list of recipients define by folder permissions (hierarchically)
* the list of recipients the file

In that way I see more simple enhancement to implement (only the notification process to adapt)

**Comment by picman** [comment]
Duplicates #557.
