### ISSUE TITLE
Better referencing macro

### ISSUE THREAD

**Issue by majkinetor** [danmunn/redmine_dmsf#231]
Currently `{{dmsf(id_file, title, id_revision)}}` doesn't allow for skipping title which I don't want to change most of the time. It would be great if we could omit tittle in some way for instance `{{dmsf(idf, , idr}}` or `{{dmsfr(idf, idr[, title])}}` or even using some special char to signify omition like `-`.

Additionally, some other options would be great to have here, like automatic addition of version/revision number in the link text which could perhaps be added as additional optional argument: `{{dmsf(idf, , idr, options}}` where `option` could be string determining which additional file meta-properties to show: `{{dmsf(idf, , idr, vsm}}` where v is for version, s for size and m for mime type. 

Totally verbose macro could also be created: `{{dmsfv(id [,options])}}` could put similar information available in file information page to the calling page (options would be there to fine tune info similar as above). For instance, this could by default show rectangle containing file name on first line, description in next paragraph and number of downloads.

**Comment by picman** [comment]
- related to #637 
- You can omit the title as follows: ```{{dmsf(196064, , 246385)}}``` or ```{{dmsf(196064, '', 246385)}}```.
- Title formating is a part of DMS options.
