### ISSUE TITLE
Documents tagging

### ISSUE THREAD

**Issue by picman** [danmunn/redmine_dmsf#236]

**Comment by barts2108** [comment]
I am just starting with Redmine (2.6.0.stable.13817) and DMSF (1.4.9 stable) and I like it. I agree with @oussjarrouse about the extra points for tagging. IMO some additional features might come in handy here so I just list them here

* When documents are added and a tag does not exist, a possibility to add tags would be nice (maybe with a setting to allow only certain users to add tags)
* As far as I can see the tags filter only uses the first of multiple tag selections to filter. A more extensive filter would be nice where a user can choose to filter on multiple tags with AND or OR functionality. This combined with an option to choose between "this project" and "this project with sub-projects" would allow global search. 
* Other functionality that may be useful is to filter on tags AND e.g. author.

**Comment by picman** [comment]
Implemented in scope of #1080. There are filters and options now.
