### ISSUE TITLE
Easy Document link macro creation

### ISSUE THREAD

**Issue by dvader** [danmunn/redmine_dmsf#239]
Currently, creating a link to a DMSF document/folder in an issue or wiki is very cumbersome: you have to remember the macro syntax but more importantly you have to find the document/folder ID. The only way I found to do that is either hover over the file and look at the link or click on the details and the ID is in the address bar. Not very practical.
Some suggestions (in order of complexity & preference, low to high):
- Add a column on the file browser with the ID
- Add a button on the right of the file/folder section (where the delete, lock, etc are) to put the macro with the file/folder ID on the clipboard.
- Add a "insert DMSF link" button on the textile toolbar that would open a DMSF file browser and insert the macro once the file/folder is selected

**Comment by picman** [comment]
Related to #555.

**Comment by picman** [comment]
I've added a DMS macro button into the wiki's toolbar. There is also a help link with macros' description. Concerning the possibility to choose the document/folder's ID from a list, I don't consider it as practical, especially in case of a big folders/documents structure. You can add ID column into the main view. The ID is also available in document/folder's details form.
