### ISSUE TITLE
Feature Request: nautilus-like folders-files list view

### ISSUE THREAD

**Issue by oussjarrouse** [danmunn/redmine_dmsf#252]
While using the plugin, i though that having a nautilus-like folders-files view for the main DMSF  plugin view would be a great user usability enhancement.
I mean by nautilus the gnome file manager
Here is a screenshot: http://i.stack.imgur.com/0kxyh.png

This will make features like dragging and dropping files, multiple files selection much more easier to implement and to present.

**Comment by picman** [comment]
Done. The tree view is option-able from user's preferences.
