### ISSUE TITLE
Custom fields tabs not work with last custom_fields_helper_patch.rb

### ISSUE THREAD

**Issue by RSAspace** [danmunn/redmine_dmsf#267]
Redmine. Error 500
Global_error
undefined local variable or method `add_cf' for #<#<Class:0x00000009566f68>:0x0000000658a308>

/var/www/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/patches/custom_fields_helper_patch.rb:51:in `render_custom_fields_tabs_with_render_custom_tab'
/var/www/redmine/app/views/custom_fields/index.html.erb:8:in `_app_views_custom_fields_index_html_erb___1850731759258162307_78128160'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_view/template.rb:145:in `block in render'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/notifications.rb:125:in `instrument'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_view/template.rb:143:in `render'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/notifications.rb:123:in `block in instrument'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/notifications.rb:123:in `instrument'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_view/renderer/template_renderer.rb:18:in `render'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_view/renderer/renderer.rb:36:in `render_template'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_view/renderer/renderer.rb:17:in `render'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/abstract_controller/rendering.rb:110:in `_render_template'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/streaming.rb:225:in `_render_template'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/abstract_controller/rendering.rb:103:in `render_to_body'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/abstract_controller/rendering.rb:88:in `render'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/rendering.rb:16:in `render'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/core_ext/benchmark.rb:5:in `ms'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-3.2.18/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/instrumentation.rb:39:in `render'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/abstract_controller/base.rb:167:in `process_action'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:502:in `_run__435903700129012063__process_action__2840212486595769393__callbacks'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/abstract_controller/callbacks.rb:17:in `process_action'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/notifications.rb:123:in `block in instrument'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/notifications.rb:123:in `instrument'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-3.2.18/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/abstract_controller/base.rb:121:in `process'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/abstract_controller/rendering.rb:45:in `process'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal.rb:203:in `dispatch'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_controller/metal.rb:246:in `block in action'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/routing/route_set.rb:73:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/routing/route_set.rb:36:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/usr/local/rvm/gems/ruby-2.1.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/usr/local/rvm/gems/ruby-2.1.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/routing/route_set.rb:608:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/head.rb:14:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/var/www/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/flash.rb:242:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-3.2.18/lib/active_record/query_cache.rb:64:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in `_run__1914575052215051480__call__2980438749155296894__callbacks'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/railties-3.2.18/lib/rails/rack/logger.rb:32:in `call_app'
/usr/local/rvm/gems/ruby-2.1.1/gems/railties-3.2.18/lib/rails/rack/logger.rb:16:in `block in call'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/tagged_logging.rb:22:in `tagged'
/usr/local/rvm/gems/ruby-2.1.1/gems/railties-3.2.18/lib/rails/rack/logger.rb:16:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/request_store-1.0.6/lib/request_store/middleware.rb:8:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/activesupport-3.2.18/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/static.rb:63:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
/usr/local/rvm/gems/ruby-2.1.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/railties-3.2.18/lib/rails/engine.rb:484:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/railties-3.2.18/lib/rails/application.rb:231:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/railties-3.2.18/lib/rails/railtie/configurable.rb:30:in `method_missing'
/usr/local/rvm/gems/ruby-2.1.1/gems/passenger-4.0.42/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/usr/local/rvm/gems/ruby-2.1.1/gems/passenger-4.0.42/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/local/rvm/gems/ruby-2.1.1/gems/passenger-4.0.42/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/usr/local/rvm/gems/ruby-2.1.1/gems/passenger-4.0.42/lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

**Comment by atopcu** [comment]
Hello, this conflict still exist on my redmine instance.

Redmine contacts version: 3.4.5-pro
Redmine_dmsf version: 1.5.1 stable

Redmine Environment:
  Redmine version                2.6.5.stable.14266
  Ruby version                   2.0.0-p481 (2014-05-08) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2

**Comment by atopcu** [comment]
Hello picman,
I found a workaround for my problem. I converted add_cf definition to in-line code:


	diff --git a/lib/redmine_dmsf/patches/custom_fields_helper_patch.rb b/lib/redmine_dmsf/patches/custom_fields_helper_patch.rb
	index 1b66980..53bf149 100644
	--- a/lib/redmine_dmsf/patches/custom_fields_helper_patch.rb
	+++ b/lib/redmine_dmsf/patches/custom_fields_helper_patch.rb
	@@ -40,23 +40,32 @@ module RedmineDmsf
		   module InstanceMethods

			 def render_custom_fields_tabs_with_render_custom_tab(types)
	-          add_cf
	+#          add_cf
	+          cf = {:name => 'DmsfFileRevisionCustomField', :partial => 'custom_fields/index', :label => :dmsf}
	+          unless CustomFieldsHelper::CUSTOM_FIELDS_TABS.index { |f| f[:name] == cf[:name] }
	+            CustomFieldsHelper::CUSTOM_FIELDS_TABS << cf
	+          end
			   render_custom_fields_tabs_without_render_custom_tab(types)
			 end

			 def custom_field_type_options_with_custom_tab_options
	-          add_cf
	+#          add_cf
	+          cf = {:name => 'DmsfFileRevisionCustomField', :partial => 'custom_fields/index', :label => :dmsf}
	+          unless CustomFieldsHelper::CUSTOM_FIELDS_TABS.index { |f| f[:name] == cf[:name] }
	+            CustomFieldsHelper::CUSTOM_FIELDS_TABS << cf
	+          end
			   custom_field_type_options_without_custom_tab_options
			 end

		   private

	+        cf = {:name => 'DmsfFileRevisionCustomField', :partial => 'custom_fields/index', :label => :dmsf}
			 def add_cf
	-          cf = {:name => 'DmsfFileRevisionCustomField', :partial => 'custom_fields/index', :label => :dmsf}
			   unless CustomFieldsHelper::CUSTOM_FIELDS_TABS.index { |f| f[:name] == cf[:name] }
				 CustomFieldsHelper::CUSTOM_FIELDS_TABS << cf
			   end
			 end
		 
I'm not ruby developer. But this works for me. Is it possible to apply your code ?

regards..

**Comment by picman** [comment]
Yes, it is, no problem.
