### ISSUE TITLE
Improve/AJAXify DMSF browsing UI

### ISSUE THREAD

**Issue by danmunn** [danmunn/redmine_dmsf#29]
At present the UI for DMSF is quite clunky and I think it could do with an overhaul.

The following is proposed:
- Replace current file / folder browse functionality
- Implement an AJAX powered replacement
- enable drag/drop functionality into the UI - enabling files and folders to be moved with ease.
- enable renaming file elements with ease
- Interaction with said area with keyboard shortcuts (F2, delete, enter, arrow keys - perhaps even ctrl+c/ctrl+v/ctrl+x)
- Enable multi object selection for interaction within said area.
- Provide full functionality for graceful degradation should user not have JS enabled browser.

This is an open issue, and it'd be great to get feedback from users about functionality they'd like to see - or even some assistance / input on UI design (and subsequent ideas) etc.

**Comment by picman** [comment]
Many required feature implemented within the scope of #1080.
