### ISSUE TITLE
How to easily copy the Link to a folder or a file?

### ISSUE THREAD

**Issue by sulliwane** [danmunn/redmine_dmsf#291]
Hello there,

first of all thanks a lot to the developers who created redmine_dmsf, which is a great tool.

I start playing with it, and one thing that seems missing would be a way to easily copy the link to a file/folder, in order to insert it in a redmine issue description or comment (or wiki).

Having to look in the url for the file/folder ID, and then building the link of the form {{dmsf(x)}} is not easy for non-it profession. A simple "copy" for special paste in wiki or issues would be great!

Thank you for you feedback on this question!

**Comment by tjaeger** [comment]
That would be a huge help in terms of usability. IMHO the Feature has to come from Redmine rather DMSF. It would require a "picker" in wiki and Issue toolbar, ... that allows to browse DMSF and pick a File and than insert the DMSF-Link {{dmsf()}}

**Comment by picman** [comment]
Duplicates #239.
