### ISSUE TITLE
uninitialized constant RedmineDmsf::Patches::ProjectPatch::DmsfFolder

### ISSUE THREAD

**Issue by ekimd** [danmunn/redmine_dmsf#297]
I get the following error when running rake redmine:plugins:migrate RAILS_ENV="production"

rake aborted!
uninitialized constant RedmineDmsf::Patches::ProjectPatch::DmsfFolder
/var/www/redmine-2.5/plugins/dmsf/lib/redmine_dmsf/patches/project_patch.rb:39:in `block in included'
/var/www/redmine-2.5/plugins/dmsf/lib/redmine_dmsf/patches/project_patch.rb:29:in `class_eval'
/var/www/redmine-2.5/plugins/dmsf/lib/redmine_dmsf/patches/project_patch.rb:29:in `included'
/var/www/redmine-2.5/plugins/dmsf/lib/redmine_dmsf/patches/project_patch.rb:100:in `include'
/var/www/redmine-2.5/plugins/dmsf/lib/redmine_dmsf/patches/project_patch.rb:100:in `block in <top (required)>'
/var/www/redmine-2.5/config/environment.rb:17:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

This appears to be the same as Issue #250.  However, I get this error when using both the "git clone" and zip file.  I've also tried going back to revisions as old as April, but I continue to receive the same error.

Ideas?

**Comment by eLvErDe** [comment]
I can confirm this issue, it breaks Redmine completely. Any idea ?

**Comment by picman** [comment]
Duplicates #250
