### ISSUE TITLE
Error when converting documents in DRY mode

### ISSUE THREAD

**Issue by rajanyaG** [danmunn/redmine_dmsf#302]
Issueing the command
rake redmine:dmsf_convert_documents project=25 dry=true RAILS_ENV="production"
leads to error:
Dry check folder: myfolder
Dry check file: myfile.pdf
Creating file: myfile.pdf failed
==>*File id is not set*

Doing find/grep lead me to file ./lib/tasks/dmsf_convert_documents.rake.
In line 96 file object is set, then initialized from attachment.
What actually is missing is assigning the file.id from attachment.id:
file.id = attachment.id
After that, DRY run is fine.

Actually I have no clue about ruby/redmine, but propper initialization is something beyond...
Left a little speechless.

**Comment by picman** [comment]
Thank you for the bug report.
