### ISSUE TITLE
Put a folder or document as private

### ISSUE THREAD

**Issue by paulaener** [danmunn/redmine_dmsf#309]
Hello,

Another improvement  suggestion: 

"Put a folder or document as private"

Thank you,
Paula

**Comment by cityant** [comment]
I also support this idea, we need it also :)

**Comment by setempler** [comment]
I am also looking forward for this feature!

**Comment by picman** [comment]
Related to #170. There will be possible to define roles or even members with access to the folder.

**Comment by paulaener** [comment]
Hello,
The true pioneers make the world go round.

Thanks,
Paula
