### ISSUE TITLE
Administration UI Overhaul

### ISSUE THREAD

**Issue by danmunn** [danmunn/redmine_dmsf#31]
Lets face it, the plugin has some basic configuration options however makes no attempt to integrate with the administration portion of redmine. I think it would be beneficial (if possible) to see the ability to run safe data cleanup operations, and perhaps even see notifications where DMSF is update (if this is possible).

Are there other functionalities that people can conceive that perhaps could/should be added?

**Comment by picman** [comment]
The ideas are 6 years old and the plugin has made some progress since => closing.
