### ISSUE TITLE
Link between Issues and DMSF documents

### ISSUE THREAD

**Issue by Pierstoval** [danmunn/redmine_dmsf#316]
It's a following of the issue #151  which asks questions about the current Redmine system.
 
What I'd like to see is a _real_ link between issues and documents.
 
We currently can make a link between them only by creating a custom field, allowing "text formatting", and writing {{dmsf(%document_id%)}} in this field if we want to link items.
But the problem is, the people who use redmine and are only managers have no time to remember this pattern, because it is freaking NOT user-friendly, and forces the manager to search for the id, which is barely sustainable for a very busy manager.
A better use would be the issues-searchbox we have when we are linking a parent issue, for example.
 
What I was thinking about is a completely new section in the issue, the same we have with the two sections under it. In french they're called "Sous-tâches" (I guess "sub-tasks") and "Demandes Liées" (I guess "relations" or "associated issues").
You can "add" a relationship between an issue and a document, and then it adds a link with details about the document itself : id (not mandatory, obviously), name, author, flux status, version... Any of them in fact, but the main ones are these ones in my opinion.
 
This tasks probably needs a new association table in the database, new views and forms, and damn myself I don't know Ruby, or I would have developed this feature.
 
I just count on ya'll to tell me if you would find this useful ! (In fact, I REALLY need a feature like that :D ) 
 
Thanks for reading and supporting this incredibly awesome plugin :heart:

**Comment by ppoektos** [comment]
+1

**Comment by jansor** [comment]
+1 as well, would be a great functionallity

**Comment by Keltrex** [comment]
+1 Would be a major bonus if this was implemented!

**Comment by eurodba** [comment]
+1

**Comment by algorys** [comment]
+1

**Comment by ericLemanissier** [comment]
+1

**Comment by fastuser** [comment]
+1

**Comment by Pierstoval** [comment]
Does anybody have the skills to work on this?

**Comment by picman** [comment]
Here are some skills but lack of time....

**Comment by picman** [comment]
Duplicates #48
