### ISSUE TITLE
webdav problem after upgrading to 1.4.9 from 1.4.6

### ISSUE THREAD

**Issue by dgutkowsky** [danmunn/redmine_dmsf#319]
In 1.4.6 I was able to use webdav via windows file explorer.
In 1.4.9 (stable) I can' t even add a network location (webdav)

In changelog there is mention that webdav was rebuild and new gem is used for that - but the outcome for me is that I can't access files via webdav anymore.

(Redmine 2.3.3)

**Comment by Keltrex** [comment]
I don't know if this the exact problem you were having, but after a month of hair-pulling, i found that editing the routes.rb and the no_parse.rb files as mentioned here, https://github.com/danmunn/redmine_dmsf/issues/332 fixed my problem completely. I am now able to view, edit and copy files into a mapped drive.
Essentially, you just need to change any entries in routes.rb and no_parse.rb from '/dmsf/webdav' to '/redmine/dmsf/webdav'
Hope it helps!

**Comment by jevo** [comment]
Hi,

I've tested **Keltrex** hint and changed the routes.rb and no_parse.rb (for more information see #332)
I'm running the plugin version 1.4.8. 

And it works. Thank you Keltex.
