### ISSUE TITLE
ArgumentError: Unknown key: :conditions. (when running migration in redmine 2.6)

### ISSUE THREAD

**Issue by kovpack** [danmunn/redmine_dmsf#327]
When running `rake redmine:plugins:migrate RAILS_ENV="production"` I get
```
(in /home/adminuser/ruby_projects/redmine)
rake aborted!
ArgumentError: Unknown key: :conditions. Valid keys are: :class_name, :class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table
```

http://www.redmine.org/plugins/dmsf states that is it 2.6.x compatible, but I suppose, that is just mistake there. Hope soon everything will be fine.

**Comment by soncu** [comment]
In Rails 4.x.x 
ArgumentError: Unknown key: :conditions
in 
redmine_dmsf/lib/redmine_dmsf/patches/project_patch.rb

Please correct the conditions:
as suggested following link:
https://teamtreehouse.com/forum/unknown-key-conditions
http://stackoverflow.com/questions/24621827/unknown-key-in-rails-association

**Comment by picman** [comment]
Duplicates #308

**Comment by petercheco** [comment]
I still encounter the same problem in Redmine 2.5.2.

My server configuration: Debian Jessie

Environment:
Redmine version 2.5.2
Ruby version 2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
Rails version 4.1.9
Environment production
Database adapter Mysql2
SCM:
Subversion 1.8.10
Git 2.1.4

**Comment by vivek2007** [comment]
Same error in rails 4
ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/hash/keys.rb:75:in `block in assert_valid_keys': Unknown key: :order. Valid keys are: :class_name, :class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table, :foreign_type (ArgumentError)
