### ISSUE TITLE
Redmine DMSF installation error

### ISSUE THREAD

**Issue by taogone** [danmunn/redmine_dmsf#328]
I installed bitnami redmine stack (v2.6.0) and tried to install redmine dmsf plugin.

I have met mini_portile problem. It seems mini_portile v0.6.1 is required but I cannot install that gem.

===============================================================================
C:\Bitnami\redmine-2.6.0-2\apps\redmine\htdocs\plugins>gem install mini_portile
ERROR:  Could not find a valid gem 'mini_portile' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect retur
ned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (
https://rubygems.org/latest_specs.4.8.gz)
===============================================================================

Is there any manual install command? I appreciate your help in advance.

**Comment by quangnngithub** [comment]
i got same issues. it took days to googling and now i install succesfully (bitnami redmine 2.5.2  on windows server 2003). If you still concern, please drop your email, i will email you log to install step by step. Hope you help.

**Comment by taogone** [comment]
My email address is taogone@gmail.com, thanks in advance for your consideration about this matter.

I will wait email from you.

**Comment by myama2630** [comment]
I even yesterday, in the same issue me googled saw this article.
Perhaps I think as bundle install has not been well.
Once in Redmine installation folder, please try the bundle install --no-deployment.
I've resolved in this way.

**Comment by gabrielvlopes** [comment]
I have the exact same problem, using bundle install --no-deployment goes a little further, but i'm stuck with the "Could not find gem 'transifex-ruby (>= 0) ruby' in git://github.com/jgraichen/transifex-ruby.git (at master). Source does not contain any versions of 'transifex-ruby (>= 0) ruby'" error.

**Comment by taogone** [comment]
Hi Guys try bellow procedure when you met DMSF installation error. I have successfully installed DMSF with bellow.
==============================================================================
INSTALL dfms plugin on Bitnami redmine 2.5.2-2 on window server 2003

1. Set path

SET GEM_HOME=C:\Bitnami\redmine-2.5.2-2\ruby\lib\ruby\gems\2.0.0\gems
SET PATH=C:\Redmine\git\bin;
C:\Bitnami\redmine-2.5.2-2\ruby\bin 

2. Stop bitnami redmine servers

3. In case of upgrade BACKUP YOUR DATABASE first

4. Put redmine_dmsf plugin directory into plugins

5. cd C:\Bitnami\redmine-2.5.2-2\apps\redmine\htdocs

6. bundle install --no-deployment --without=xapian
	
7. rake redmine:plugins:migrate RAILS_ENV="production"

8. start bitnami redmine servers

9. Set roles and permissions

10. Settings\Projects: default enable modules for new projects DMSF

11. Enable project\settings\modules --> enable dmsf
