### ISSUE TITLE
HowTo resolve a problem compiling xapian-full-alaveteli in a phusion docker image

### ISSUE THREAD

**Issue by carukc** [danmunn/redmine_dmsf#329]
Hello,

First, many thanks for the cool plugin.  it works VERY well!

I've been using it successfully on ubuntu 14.04 with rvm and recently I've decided to dockerize my redmine installs (using the phusion docker image).  All is working well except for the xapian-full-alaveteli gem.  Compilation of it fails with :

    /usr/include/ruby-2.1.0/ruby/ruby.h:24:25: fatal error: ruby/config.h: No such file or directory
     #include "ruby/config.h"

I see that config.h IS NOT in /usr/include/ruby-2.1.0/ruby/ but IS in /usr/include/x86_64-linux-gnu/ruby-2.1.0/ruby/.  

I suspect that this is NOT a problem with the gem but rather a problem with the way that ruby is installed in the docker image and I've found that 

ln -s /usr/include/x86_64-linux-gnu/ruby-2.1.0/ruby/config.h  /usr/include/ruby-2.1.0/ruby/config.h

solves the problem.

Hopefully someone will find this useful.

Chris

**Comment by Vitexus** [comment]
Thank you! This problem exist in debian jessie.

**Comment by asgh** [comment]
In debian run:

    dpkg-divert --rename --divert /usr/include/ruby-2.1.0/ruby/config.h --add /usr/include/x86_64-linux-gnu/ruby-2.1.0/ruby/config.h

or (for 32bit)

    dpkg-divert --rename --divert /usr/include/ruby-2.1.0/ruby/config.h --add /usr/include/i386-linux-gnu/ruby-2.1.0/ruby/config.h

Instead of a symlink that will cause you trouble.
