### ISSUE TITLE
File link cannot download/email

### ISSUE THREAD

**Issue by halida** [danmunn/redmine_dmsf#330]
I've upload a file into `temp/data.pdf`, then link it as `share/data.pdf`, I cannot batch select this file and download/email it, It will cause an error:

    undefined method `+' for nil:NilClass

After digging into the source code, I found  it calls: `dmsf_controller.rb -> download_entries`, it goes into: 
 https://github.com/danmunn/redmine_dmsf/blob/master/app/controllers/dmsf_controller.rb#L432

```ruby
zip.add_file(file, (@folder.dmsf_path_str if @folder)) if file          
```
But @folder is `share` folder, inside zip.add_file: https://github.com/danmunn/redmine_dmsf/blob/master/lib/dmsf_zip.rb#L44

```ruby
  def add_file(file, root_path = nil)
    string_path = file.folder.nil? ? '' : "#{file.folder.dmsf_path_str}/"
    string_path = string_path[(root_path.length + 1) .. string_path.length] if root_path
    string_path += file.name   
    ...
```

It cheats root_path as `temp/`, but which is `share/`, then cause this bug.

You should find a way to fix it.

**Comment by picman** [comment]
Fixed. Thank you for the bug report.
