### ISSUE TITLE
Redmine v2.3.2 install issue nokogiri gem

### ISSUE THREAD

**Issue by scottmblair** [danmunn/redmine_dmsf#331]
I'm trying to install the DMSF plugin on a Bitnami Redmine v2.3.2 stack.  I'm getting the error when I try running rake redmine:plugins:migrate....

The error it gives me is:  "You cannot specify the same gem twice with different version requirements.  You specified: nokogiri << 1.6.0> and nokogiri <>= 1.5.10> "

Any suggestions?

Thanks.
Scott

**Comment by picman** [comment]
Just comment out nokogiri requirement in the Gemfile:
```ruby
#group :production do
#  gem 'nokogiri', '>= 1.5.10'
#end
```

There is a conflict with gem requirements from another plugin very probably.
