### ISSUE TITLE
webdav not working in ssl virtuel hosts

### ISSUE THREAD

**Issue by dimpfelmoser** [danmunn/redmine_dmsf#332]
I am trying to setup redmine with dmsf. It almost works, except I can't get the webdav functionality going. Versions are shown below. Server is Ubuntu 12.04, Apache, Mysql. There are several SSL-VirtualHosts in sub-directories on this webserver. Everything else is working as expected: redmine, phpmyadmin, phpmyfaq, webdav with egroupware, all with SSL.

Situation: I have a redmine project with id "server". When I do (on a remote Linux box)
mount -t davfs https://bla.dom/redmine/dmsf/webdav /mnt/tmp
I get asked for credentials, confirm the self-signed certificate and then a 404 error is posted.

In redmine production.log I get

Started OPTIONS "/redmine/dmsf/webdav/" for 46.115.141.167 at 2015-01-05 20:04:04 +0100
  AnonymousUser Load (0.5ms)  SELECT `users`.* FROM `users` WHERE `users`.`type` IN ('AnonymousUser') LIMIT 1
Started OPTIONS "/redmine/dmsf/webdav/" for 46.115.141.167 at 2015-01-05 20:04:04 +0100
  User Load (0.1ms)  SELECT `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`login` = 'marcs'
  SQL (2.5ms)  UPDATE `users` SET `last_login_on` = '2015-01-05 20:04:04' WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`id` = 3
Started PROPFIND "/redmine/dmsf/webdav/" for 46.115.141.167 at 2015-01-05 20:04:04 +0100
  User Load (0.5ms)  SELECT `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`login` = 'marcs'
  SQL (0.6ms)  UPDATE `users` SET `last_login_on` = '2015-01-05 20:04:04' WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`id` = 3
  Project Load (0.1ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`identifier` = 'redmine' LIMIT 1

As you can see, in the SQL query it looks for a project called "redmine", which isn't there. There are no apache errors logged. Do I have to include the project in the webdav path?

Any help is appreciated.
Thank you,
Marc

Environment:
  Redmine version                2.5.2.stable
  Ruby version                   1.9.3-p0 (2011-10-30) [i686-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  redmine_auto_assigned_user     0.2.0
  redmine_dmsf                   1.4.9 stable
  redmine_knowledgebase          3.0.4
  redmine_maintenance_mode       1.1.0

**Comment by picman** [comment]
Yes, the project identifier must be included. So the correct URL would be https://bla.dom/redmine/dmsf/webdav/[project identifier].

**Comment by picman** [comment]
I will change the description in the plugin settings.

**Comment by dimpfelmoser** [comment]
Hmm, it is still the same behaviour:

Started OPTIONS "/redmine/dmsf/webdav/server/" for 46.115.174.198 at 2015-01-06 16:15:44 +0100
  AnonymousUser Load (0.5ms)  SELECT `users`.* FROM `users` WHERE `users`.`type` IN ('AnonymousUser') LIMIT 1
Started OPTIONS "/redmine/dmsf/webdav/server/" for 46.115.174.198 at 2015-01-06 16:15:45 +0100
  User Load (0.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`login` = 'marcs'
  SQL (2.7ms)  UPDATE `users` SET `last_login_on` = '2015-01-06 16:15:45' WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`id` = 3
Started PROPFIND "/redmine/dmsf/webdav/server/" for 46.115.174.198 at 2015-01-06 16:15:45 +0100
  User Load (0.5ms)  SELECT `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`login` = 'marcs'
  SQL (0.7ms)  UPDATE `users` SET `last_login_on` = '2015-01-06 16:15:45' WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`id` = 3
  Project Load (0.1ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`identifier` = 'redmine' LIMIT 1


When I am logged into redmine, the URL to dmsf for project server is
https://bla.dom/redmine/projects/server/dmsf

**Comment by picman** [comment]
I see it now. You have installed Redmine in a sub-directory. Maybe that's the problem. I've never tested it. Sorry.

**Comment by dimpfelmoser** [comment]
OK, thanks anway, could you suggest a starting point for me to start looking at the code?

**Comment by dimpfelmoser** [comment]
Here we go, just changed the path in the sources and now it works:

--- a/config/routes.rb
+++ b/config/routes.rb
@@ -1,3 +1,4 @@
+# -*- coding: utf-8 -*-
 # Redmine plugin for Document Management System "Features"
 #
 # Copyright (C) 2011    Vít Jonáš <vit.jonas@gmail.com>
@@ -102,7 +103,7 @@ RedmineApp::Application.routes.draw do
   # DAV4Rack implementation of Webdav [note: if changing path you'll need to update lib/redmine_dmsf/webdav/no_parse.rb also]
   #   /dmsf/webdav
   mount DAV4Rack::Handler.new(
-    :root_uri_path => "/dmsf/webdav",
+    :root_uri_path => "/redmine/dmsf/webdav",
     :resource_class => RedmineDmsf::Webdav::ResourceProxy,
     :controller_class => RedmineDmsf::Webdav::Controller
   ), :at => "/dmsf/webdav"
diff --git a/lib/redmine_dmsf/webdav/no_parse.rb b/lib/redmine_dmsf/webdav/no_parse.rb
index ee8625b..040dcbd 100644
--- a/lib/redmine_dmsf/webdav/no_parse.rb
+++ b/lib/redmine_dmsf/webdav/no_parse.rb
@@ -47,4 +47,4 @@ end
 #   automatically without the need to add a "/dmsf/webdav" configuration to it, as if the route is changed
 #   the functonality of this patch will effectively break.
 Rails.configuration.middleware.insert_before(ActionDispatch::ParamsParser,
-                                   RedmineDmsf::NoParse, :urls => ['/dmsf/webdav'])
+                                   RedmineDmsf::NoParse, :urls => ['/redmine/dmsf/webdav'])
