### ISSUE TITLE
Delete documents configuration works for all the roles

### ISSUE THREAD

**Issue by aivorra** [danmunn/redmine_dmsf#336]
Hi!, I'm working with DMSF and i'm trying to set a role (Role Name: Preparadores) without the permission to delete files. So I unckeck the "Delete Documents Box". But the user (User Name: test-preparador) with this role can delete files.

Thanks.

![captura de pantalla de 2015-01-13 09 46 38](https://cloud.githubusercontent.com/assets/10197214/5720902/698fb7c4-9b09-11e4-81cc-554c89da0d2a.png)
![captura de pantalla de 2015-01-13 09 46 30](https://cloud.githubusercontent.com/assets/10197214/5720903/699aa45e-9b09-11e4-99bb-3d2e43896fa0.png)

**Comment by picman** [comment]
Related to #317.

**Comment by picman** [comment]
Fixed. Thank you for the bug report.
