### ISSUE TITLE
Dmsf plugin in Redmine 2.6.1

### ISSUE THREAD

**Issue by soncu** [danmunn/redmine_dmsf#338]
Hi Dears,
Recently upgraded from Redmine 2.6.0 to 2.6.1
Dmsf plugin was unsuccesfull in 2.6.0 (even could not install)
In 2.6.1. it is successfully installed/migrated but following actions results Argument Error
---------------------------------------------------------------------------------
head to Administration>Plugins>Configure:

<pre>
ArgumentError (undefined class/module ActionController::Parameters):
  app/models/setting.rb:97:in `value'
  app/models/setting.rb:110:in `[]'
  app/models/setting.rb:139:in `plugin_redmine_dmsf'
  app/controllers/settings_controller.rb:69:in `plugin'
</pre>
---------------------------------------------------------------------------------
Enable project module DMSF from Project>Settings Ok, head Go to DMSF tab

<pre>
ArgumentError (undefined class/module ActionController::Parameters):
  app/models/setting.rb:97:in `value'
  app/models/setting.rb:110:in `[]'
  app/models/setting.rb:139:in `plugin_redmine_dmsf'
</pre>
---------------------------------------------------------------------------------
mysql> select value from settings where name = 'plugin_redmine_dmsf';

<pre>
--- !ruby/hash:ActionController::Parameters
dmsf_max_file_upload: '0'
dmsf_max_file_download: '0'
dmsf_max_email_filesize: '0'
dmsf_max_ajax_upload_filesize: '100'
dmsf_storage_directory: /usr/share/redmine/files/dmsf
dmsf_default_notifications: ''
dmsf_display_notified_recipients: ''
dmsf_webdav: '1'
dmsf_webdav_strategy: WEBDAV_READ_ONLY
dmsf_index_database: ''
dmsf_stemming_lang: turkish
dmsf_stemming_strategy: STEM_NONE
</pre>

How can i solve this problem?

Thanks and Best Regards.

**Comment by picman** [comment]
Not yet tested with 2.6.1 but I will try it.

**Comment by soncu** [comment]
Ok, I am impatienty waiting for it. Until that, we could not use this useful plugin.

**Comment by picman** [comment]
I've just upgraded Redmine to 2.6.1 (Redmine 2.6.1.stable.13953) and haven't faced such problems.

Have you run?

``` ruby
bundle install --without postgresql sqlite
rake db:migrate RAILS_ENV="production"
rake redmine:plugins:migrate RAILS_ENV="production"
```

Please provide a little bigger chunk of the log.

**Comment by soncu** [comment]
Dear picman,
I redo your suggestions again and just get:
<pre>
Migrating redmine_dmsf (DMSF)...
</pre>
And it seemed that it was successful.
After restarting apache server, i went to admin/plugins(settings/plugin/redmine_dmsf)
It says:
<pre>
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error.
Back
</pre>
in the browser. And When i looked at the log/production.log file:
<pre>
Started GET "/redmine/settings/plugin/redmine_dmsf" for 95.0.172.179 at 2015-01-28 13:40:24 +0200
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_dmsf"}
  Current user: mine (id=80)
Completed 500 Internal Server Error in 11.1ms

ArgumentError (undefined class/module ActionController::Parameters):
  app/models/setting.rb:97:in `value'
  app/models/setting.rb:110:in `[]'
  app/models/setting.rb:139:in `plugin_redmine_dmsf'
  app/controllers/settings_controller.rb:69:in `plugin'
</pre>
And my environement is:
<pre>
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.3.5
  redmine_dmsf                   1.4.9 stable
</pre>
Where else can i look for the problem?

**Comment by picman** [comment]
No idea, sorry.

```ruby
bundle exec rake tmp:cache:clear tmp:sessions:clear
```

?

**Comment by soncu** [comment]
I did it now but problem is the same.
How can i do low level debugging?
Or What parameters, variables do you want to see?
My bundle install output is:
<pre>
Using rake 10.4.2
Using i18n 0.6.11
Using multi_json 1.10.1
Using activesupport 3.2.21
Using builder 3.0.4
Using activemodel 3.2.21
Using erubis 2.7.0
Using journey 1.0.4
Using rack 1.4.5
Using rack-cache 1.2
Using rack-test 0.6.3
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.2.3
Using actionpack 3.2.21
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 3.2.21
Using arel 3.0.3
Using tzinfo 0.3.42
Using activerecord 3.2.21
Using activeresource 3.2.21
Using coderay 1.1.0
Using mini_portile 0.6.2
Using nokogiri 1.6.5
Using uuidtools 2.1.5
Using dav4rack 0.3.0
Using rack-ssl 1.3.4
Using json 1.8.2
Using rdoc 3.12.2
Using thor 0.19.1
Using railties 3.2.21
Using jquery-rails 3.1.2
Using mysql2 0.3.17
Using net-ldap 0.3.1
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using bundler 1.7.12
Using rails 3.2.21
Using rbpdf 1.18.4
Using redcarpet 2.3.0
Using request_store 1.0.5
Using rmagick 2.13.4
Using rubyzip 1.1.6
Using simple_enum 1.6.9
Using xapian-full-alaveteli 1.2.9.5
Using zip-zip 0.3
</pre>

**Comment by soncu** [comment]
Dear picman,
May the problem be related with that i have migrated the redmine from BitNami and plugin was successfull in BitNami(windows) there?
Before migrating and upgrading redmine from BitNami, i removed the plugin, upgraded the redmine then
tried to install the plugin. 
May the problem also related with that it was installed (meaning database have old plugin residuals) before?

**Comment by picman** [comment]
I'd recommend you to start from scratch. Redmine instalation in a Linux enviroment is prette straightforward. The only thing what shoul be copied from the previous system are the database and stored DMSF files. Redmine and all plugins should be installed in their lates stable version.

**Comment by soncu** [comment]
Thank you sir, I will try them all soon.

**Comment by emersonlemmos** [comment]
Dear @soncu,

I am facing the same problem, did you find a solution? Could you please share it with us?

Thank you.

**Comment by soncu** [comment]
We upgraded to 3.1.0 and it is pretty well working.

**Comment by picman** [comment]
Great!
