### ISSUE TITLE
Maximum Upload Size

### ISSUE THREAD

**Issue by ralgozino** [danmunn/redmine_dmsf#339]
Hello!

 I'm having problems uploading files greater than 1GB to DMSF, via webdav and via ajax. I've increased the max file size for ajax in the config but doesn't help. Is there another parameter that can be tweaked? is this possible?

Thanks a lot in advance and great plugin btw!

EDIT: Forgot to mention that I also tried modifying the Attachment Size in the Redmine General Config

**Comment by picman** [comment]
There is also the 2GB limit for 32b browsers but it's not obviously your problem. One possible problem could be the memory size of your server. Have you checked RAM occupation during your upload and consequent error messages in logs?
All in all, provide a log record with the problems occurrences, please.

**Comment by ralgozino** [comment]
Hello @picman 

I won't be able to access the server for a few days to verify the RAM occupation (but should be enough a priori).

By the logs do you mean production.log? or is there another log I don't know about?

Please give me a few days to gather the information.

Thanks!

**Comment by picman** [comment]
Yes, I mean production.log. However, the web server error log might contain some useful information as well.

**Comment by ralgozino** [comment]
Roger that :)

**Comment by tmontes** [comment]
@ralgozino, @picman,

Chiming in as an interested party in "larger-than-common" file upload performance. Please checkout the details I provided a while ago in issue #49 -- even though this was experienced with older software revisions, I believe most of what I observed and measured regarding uploads may still hold.

**Comment by picman** [comment]
The upload has been noticeable sped up.

**Comment by tmontes** [comment]
@picman - I've been a little away from this, but I am still an interested party. Could you please point out the changes that have been made to improve the upload speed? I tried looking at the recent commits but could not identify a particular one -- maybe I missed it.

From memory, one of the factors contributing for the "slowness" of large file uploades, was the fact that the file was copied around once or twice on the server side before reaching its final destination.

Thanks in advance for sharing.

**Comment by picman** [comment]
Yeah, that's my fault. I should have committed it as a separated commit. The problem was in the file copying after it's upload. The procedure was as follows:

1) Upload via browser into /tmp/xyz_tmp_file
2) Copying either by DMSF to /tmp/xyz_tmp_dmsf_file or by Redmine::Attachment into 2015/04/attachment_file depending on the chosen upload way
3) Copying to /dmsf/project_id/file

The copying could be a pretty slow especially i case of large files.
I've simply replaced copy with move in the steps 2 and 3

See the commit https://github.com/danmunn/redmine_dmsf/commit/c5d279e266b0985c980d9dd21c01ecfd4e55baa6

app/controllers/dmsf_upload_controller.rb

```ruby
- File.open("#{DmsfHelper.temp_dir}/#{@disk_filename}", 'wb') do |f| 
-    while (buffer = @tempfile.read(8192))
-      f.write(buffer)
-    end
-  end
+ FileUtils.mv(@tempfile.path, "#{DmsfHelper.temp_dir}/#{@disk_filename}")
```

app/models/dmsf_upload.rb

``` ruby
-  File.open(a.diskfile, 'rb') do |fr|   
-    File.open("#{DmsfHelper.temp_dir}/#{uploaded[:disk_filename]}", 'wb') do |fw| 
-      while (buffer = fr.read(8192))
-        fw.write(buffer)
-      end
-   end
-  end
+ FileUtils.mv(a.diskfile, "#{DmsfHelper.temp_dir}/#{uploaded[:disk_filename]}")
```
