### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by KueWW** [danmunn/redmine_dmsf#345]
Hello Everybody,

first of all thanks for that great plugin!
I have a question using the workflow. Is it possible to set up a workflow in combination with document versioning?
What I want to do is as follows:
User 1 has to work on a document after that user 2 has to work on that document. During that work I want to see the workflow.

**Comment by picman** [comment]
I'm afraid that this is impossible. Immediately you start an approval workflow, the document is locked and no changes are allowed until the worflow finishes and is unlocked again.

**Comment by KueWW** [comment]
Hello picman,

thanks for your quick reply.

Do you have any ideas how to create a "feedback workflow" using redmine to work with shared documents inside a users group? Tools like SVN are not usable for that kind of groups.
I'd like to have history versions and all that stuff.

As you may have known someone who has solved this problem.

best regards

**Comment by picman** [comment]
I'm sorry. No idea.
