### ISSUE TITLE
Maximal reaction time and step name

### ISSUE THREAD

**Issue by jmbiollaz** [danmunn/redmine_dmsf#346]
You documentation states that the maximum reaction time for approving or rejecting an approval step is hard coded on 2 working days. Obviously this won't work for all scenarios. Would this hard coded setting be configurable in a future version?

Additionally would it be possible to give a name to the different workflow's steps? instead of 1, 2, 3, it would be useful to have 'QA', 'Owner', etc.

Thank's

**Comment by picman** [comment]
You are right, there in the specification is written 2 working days. However, as it's correctly described in the user's guide, it's realized by a rake task dmsf_alert_approvals. How often you run it it's up to you.
