### ISSUE TITLE
What is the latest version of DMSF?

### ISSUE THREAD

**Issue by eurodba** [danmunn/redmine_dmsf#348]
Dear `picman`, I have following question (current ticket is not an Issue - only question). I carefully monitor activity of the repository `redmine_dmsf`. And I see, during last weeks you have actively working on all open issues (both - recently opened and the old ones). However, you have not created any new release(es) - only merges into current trunk, increasing version - 1.4.9 => 1.5.0 => 1.5.1 and so on.

So, my questions:

* on the main page of `redmine_dmsf` (https://github.com/danmunn/redmine_dmsf), first row of *README.md* says: *The current version of Redmine DMSF is 1.4.9 Build Status*. However, as we already know, latest version (commits) are more recent than 1.4.9. So, question is - should I download latest available version and upgrade my currently installed 1.4.9 to the new one without risk?
* is there some URL, where I can always check, which version is latest available, highest one? Not to check every time all new comments, trying to find latest *mentioned* version between comments?

**Comment by picman** [comment]
The version 1.4.9 is the lates stable release. All new work either a new development or bugs fixing is done in scope of 1.5.1 - https://github.com/danmunn/redmine_dmsf/milestones . There are still some open issues. Immediately these issues are fixed, I will do testing and consequently release a new version 1.5.1.
The lastes released version is always available on the main page of this project: https://github.com/danmunn/redmine_dmsf .
All already released version are available among releases here: https://github.com/danmunn/redmine_dmsf/releases .
The latest source code - 1.5.1-devel, you can download and use on your own risk. However, the same is valid for stable releases ;-) I can recommend it. At least you will help with testing of the new version.

**Comment by eurodba** [comment]
OK, it's clear now, thanks.
Last question - how to upgrade from current release (1.4.9) to the 1.5.1 (and to the all further commits in devel- tree, e.g. 1.5.1 => 1.5.2 and so on)?

**Comment by picman** [comment]
You must localy switch to the branch devel-1.5.1:
``` bash
cd redmine/plugins
git clone https://github.com/danmunn/redmine_dmsf.git
cd redmine_dmsf
git fetch
git checkout devel-1.5.1
```
http://stackoverflow.com/questions/1783405/checkout-remote-git-branch

**Comment by eurodba** [comment]
Thanks, it's clear - to update all plugin's files to the latest version. My question was (sorry that I was not too specific) - should I perform any DB change, e.g. perform `db migrate` ?

**Comment by picman** [comment]
Yes, always perform:

```ruby
bundle update
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```

**Comment by eurodba** [comment]
Thanks, all is clear now. Can I create Wiki page for all that we have discussed hre, within current thread and pull it to the current repo? Do you accept pull requests for WIki?

**Comment by picman** [comment]
Yes.
