### ISSUE TITLE
Feature Request: Tree View of Folders/Files

### ISSUE THREAD

**Issue by fabianjs** [danmunn/redmine_dmsf#349]
Since we currently have a project with a rather deep folder structure, it would be a great improvement to be able to "unfold" folders, similar to an explorer tree view of files on the hard drive, without having to navigate through the subfolders themselves. See the image below for an example of what i mean.

![17-02-2015 09-18-02](https://cloud.githubusercontent.com/assets/1330112/6225101/fbac254c-b685-11e4-9468-50bce99ab723.png)

Are there plans on implementing such a feature in the future?

**Comment by picman** [comment]
No such plans. Sorry.

**Comment by picman** [comment]
Duplicates #252
