### ISSUE TITLE
Link seems wrong in when clicking "Approval workflow name"

### ISSUE THREAD

**Issue by tjaeger** [danmunn/redmine_dmsf#350]
In DMSF overview clicking on "waiting for approval" link - which brings up a popup window.
Top of this i can click "Workflow name: <workflow name>"
which directs to https://redmine/dmsf_workflows/1/edit and ends up in an http_404.
The real url seems to be https://redmine/dmsf_workflows/1  though.
Using DMSF_1.4.9 on RM_2.6.1.stable.13876

![2015-02-17_22-22-49](https://cloud.githubusercontent.com/assets/5296371/6237531/03ecddb4-b6f4-11e4-90ff-5c292a55efe9.png)

![2015-02-17_22-21-49](https://cloud.githubusercontent.com/assets/5296371/6237542/14e12fd0-b6f4-11e4-9e89-1c24116ee209.png)

**Comment by picman** [comment]
Fixed. Thank you for the bug report.
