### ISSUE TITLE
[Feature Request] - overriding preconfigured Revision Tags/Steps

### ISSUE THREAD

**Issue by tjaeger** [danmunn/redmine_dmsf#351]
In some cases a Document comes with a given Revision. When uploading to DMSF only predefined Versions/Revisions can be used (0.x, x.0 etc). 
Request is being able to override the given steps and define your own Revision.
Example: i upload a Doc which is REV_1.0 - than i receive a new Doc which is already REV_2.8 - so i want to upload the Doc as new Revision and give it straight Version 2.8.

**Comment by picman** [comment]
![custom_version](https://cloud.githubusercontent.com/assets/779003/6246669/c03c70c0-b76b-11e4-875f-3b5dca7a3095.png)

**Comment by tjaeger** [comment]
Perfect. Thanks a lot. Looking forward you mark 1.5.x as GA.
