### ISSUE TITLE
[Enhancement] - DMSF Macro to display inline Pictures in wiki

### ISSUE THREAD

**Issue by tjaeger** [danmunn/redmine_dmsf#352]
Basically all Files/Asset should be stored in DMSF. In this special request its asked for displaying inline Pictures in Wiki, sourcing from DMSF. Storing a File twice/multiple is not acceptable really.
basically: !{{dmsf(68)}}!  or !{width:200px}{{dmsf(18)}}!

Workaround is to give absolut links like:
!{width:200px}https://redmine/dmsf/files/68/view!
Backdraw is that it obviously points to an absolut position (FQDN/IP) rather than relative to the DMSF and its File ID.

**Comment by picman** [comment]
I've just added a new macro:

```ruby
{{dmsf_image(file_id, [size=640x480])}}
```
