### ISSUE TITLE
Link to User in Doc-Revision seems to point to wrong target link

### ISSUE THREAD

**Issue by tjaeger** [danmunn/redmine_dmsf#353]
I assume the desired function, when clicking on the Username in the Revision, is to link to that Users Page ?  like: target=https://redmine/users/1/
Instead the target points to the Revision File itself https://redmine/dmsf/files/6
It's true for both 1.4.9 and 1.5.1-devel

![2015-02-20_17-04-46](https://cloud.githubusercontent.com/assets/5296371/6289795/f3f6f170-b922-11e4-9576-ac85c9c6f6ff.png)

**Comment by picman** [comment]
Fixed. Thank you for the bug report.
