### ISSUE TITLE
How to move document between project (not folders!)

### ISSUE THREAD

**Issue by eurodba** [danmunn/redmine_dmsf#355]
Hi, DMSF provides functionality to move document between folders. However, as far as I see, folders should be within one project. And I have not found possibility to move docement between folders, located in different projects. Is that true? Do you plan to realized such functionality?

I have investigated table's structure - I do not see any blocking moments in the DB schema:

* table DMSF_FOLDERS 
 * column ID
 * column PROJECT_ID
 * column DMSF_FOLDER_ID
* table DMSF_FILES
 * column ID
 * column PROJECT_ID
 * column DMSF_FOLDER_ID

So, in order to realize functionality to move document across projects, you need to change value of DMSF_FILES.PROJECT_ID.

**Comment by picman** [comment]
You can choose a destination project different from the current one in the document copy form:

![doc_copy](https://cloud.githubusercontent.com/assets/779003/6324372/7ac3285a-bb39-11e4-9d77-149ec6d15c66.png)

**Comment by eurodba** [comment]
That means, for moving documents between folders, for each document I should do 2 steps - copy and then delete? Why not to develop "normal" function for moving documents? Or extend current functionality, but adding possibility to see in folders dropdown projects as well? (can be non-useful, if structure is large, and projects count is large).

Anyway, to develop or no move function - it's your choice. Question - about case, when there are lots of documents, which need to be move across projects. Is it safe to to change (UPDATE) value of DMSF_FILES.PROJECT_ID ? By "safe" I mean - there are no references, or this value is not used in some other places in code?

**Comment by picman** [comment]
You don't see the button _Move_ in my screen-shot?

It should be save, don't forget on dmsf_folder_id if you would move documents between folders.

**Comment by eurodba** [comment]
Dear `picman`, now I see - I am sorry for that - of course I see now button "Move" on your screenshot !!!

Can you please clarify - which version you have used for mentioned screenshot? Is it something new, from **1.5.1-devel** version? As I have just checked also on **1.5.1-devel**, but maybe not so "fresh" like yours - **Move"* button is not there...

**Comment by picman** [comment]
I'm not sure since which version it is very a old feature. Maybe you mix files and folders. In case of a file you can copy/move but in case of a folder you can copy only.
