### ISSUE TITLE
Development environment for smooth, easy work on DMSF patches

### ISSUE THREAD

**Issue by eurodba** [danmunn/redmine_dmsf#356]
Dear picman, can you please share your experience, how to organize development environment for smooth, easy work on DMSF patches. As a first attempt, I have tried to work on issue #239 (for example, to add new column ID on the main DMSF view **show.html.erb**). However, it takes too long - each change for check/test requires restart of 2 Redmine process (**Thin** in my case). It takes up to 60 sec, it's absolutely unacceptable ( I use BitNami stack).

So, can you please teach a bit, how you work, how you have organized your development environment, which tools (IDE) you use, which other tools and so on.

Hope, if you will provide us more or less detailed instructions - as a result stream of pull requests will be significantly increased. At least I hope so, as for me such info is very important - am I novice in Ruby/Rails/DMSF development (however, proficient in many other technologies).

Thanks in advance,

Rostislav

**Comment by picman** [comment]
I personally use NetBeans IDE with Ruby and Rails plugin. Ubuntu Linux as OS. First I install Redmine in a folder, e.g. /home/karel/NetBeansProjects/redmine and then from the IDE I create a new Rails project from existing source. Development is preete straightforward and Redmine starts without any delay in the debug mode.

```
NetBeans IDE 8.0.2 (Build 201411181905)
Ruby and Rails plugin 0.111 
Fast Debugger (ruby-debug-ide 0.4.22, ruby-debug-base19x 0.11.30.pre15)
```

**Comment by eurodba** [comment]
OK, thanks a lot, how it will help!
