### ISSUE TITLE
Redmine 3.0.0 released! Compatibility with DMSF?

### ISSUE THREAD

**Issue by eurodba** [danmunn/redmine_dmsf#357]
Hi, as you already (I hope) know, on **2015/Feb/19** was released **Redmine 3.0.0**:

http://www.redmine.org/projects/redmine/wiki/Changelog

Have you tested compatibility? What is your estimation - how risky is to upgrade Redmine to 3.0.0 in scope of stable work of DMSF plugin?

**Comment by picman** [comment]
I know, the main problem will be with Rails 4.2. 1.4.9 won't be compatible with Redmine 3.0.0. DMSF 1.5.1 will be modified in order to be compatible with the new release of Redmine during this week.

#308

**Comment by picman** [comment]
Redmine 3.0.0 depends on rubygems > 2.0. This package is not available for Debian Wheeze. I will postpone DMSF upgrade to new Redmine untill new Debian Jessie is released.
https://www.debian.org/releases/jessie/

**Comment by eurodba** [comment]
But what is the reason, why you have changed your opinion twice during one day - you use Debian Wheeze as your desktop OS?

**Comment by picman** [comment]
I've just tried it and realized that it's impossible to install rubygems 2.0 from standard package sources.
I use Ubuntu and the situation is similar to Debian there.

**Comment by picman** [comment]
1.5.1 should work with Redmine 3.0.0 now.

**Comment by yueno0730** [comment]
Hi,
I installed ver1.5.1 redmine_dmsf plugin on Redmine 3.0.1.
However, it has become not put in a project setting screen.
