### ISSUE TITLE
Ability to upload directory and the files it contains

### ISSUE THREAD

**Issue by bolahg** [danmunn/redmine_dmsf#359]
Ability to upload directory and the files it contains. 
I added 10 folders and files contained in them at a time. A lot of time is spent on that to create a folder in dmsf, and then upload files
I think it would be a cool addition to the functional plugin.
For example, I now need to download these folders, each folder has 10 folders and 100 files on them.
![for examples](https://cloud.githubusercontent.com/assets/9381510/6351718/ebf6cbba-bc67-11e4-8c2b-75faa1047a82.jpg)

**Comment by ppoektos** [comment]
You could enable web-dav, create top-level folder you need in dmsf
and then upload all your folders and files through web-dav.

On Tue, Feb 24, 2015 at 4:58 PM, Roman <notifications@github.com> wrote:

> Ability to upload directory and the files it contains.
> I added 10 folders and files contained in them at a time. A lot of time is
> spent on that to create a folder in dmsf, and then upload files
> I think it would be a cool addition to the functional plugin.
> For example, I now need to download these folders, each folder has 10
> folders and 100 files on them.
> [image: for examples]
> <https://cloud.githubusercontent.com/assets/9381510/6351718/ebf6cbba-bc67-11e4-8c2b-75faa1047a82.jpg>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/danmunn/redmine_dmsf/issues/359>.
>



-- 

Best / ó ÎÁÉÌÕÞÛÉÍÉ ÐÏÖÅÌÁÎÉÑÍÉ


 *Pavel Potcheptsov*

   LLC EKTOS-Ukraine

System administrator

   1, Academika Proskury

Mobile UA: +38 050 3642391

Home UA: +380 572 931115

   61070 Kharkiv

   www.ektos.com.ua <http://www.ektos.net/>

E-mail:

ppo@ektos.net


  Skype:      potcheptsov.pavel

**Comment by bolahg** [comment]
I'm not the only one. Many people with whom I work have to download folder.
And not everyone has the opportunity and skills to connect through webdav.
We are not programmers.We are designers and builders and the computer for most of us shamanic box. You can not imagine what works should get some use redmine, instead of paper with a pencil

**Comment by ppoektos** [comment]
You don't need any skills to do that.
- enable web-dav RW mode in dmsf setting
- from Win7 map network drive to http://your_redmine/dmsf/webdav/
- copy your data to webdav network drive.

On Tue, Feb 24, 2015 at 5:22 PM, Roman <notifications@github.com> wrote:

> I'm not the only one. Many people with whom I work have to download folder.
> And not everyone has the opportunity and skills to connect through webdav.
> We are not programmers.We are designers and builders and the computer for
> most of us shamanic box. You can not imagine what works should get some use
> redmine, instead of paper with a pencil
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/danmunn/redmine_dmsf/issues/359#issuecomment-75776138>
> .
>



-- 

Best / ó ÎÁÉÌÕÞÛÉÍÉ ÐÏÖÅÌÁÎÉÑÍÉ


 *Pavel Potcheptsov*

   LLC EKTOS-Ukraine

System administrator

   1, Academika Proskury

Mobile UA: +38 050 3642391

Home UA: +380 572 931115

   61070 Kharkiv

   www.ektos.com.ua <http://www.ektos.net/>

E-mail:

ppo@ektos.net


  Skype:      potcheptsov.pavel

**Comment by bolahg** [comment]
Not worked
![2015-02-24 21-36-34](https://cloud.githubusercontent.com/assets/9381510/6352606/1db94078-bc6e-11e4-8cb8-215f1e2b6417.png)
![2015-02-24 21-39-49](https://cloud.githubusercontent.com/assets/9381510/6352607/1dbbe710-bc6e-11e4-82ab-6d98af0d2a79.png)
in browser - work
![2015-02-24 21-42-10](https://cloud.githubusercontent.com/assets/9381510/6352623/2d597fac-bc6e-11e4-869e-a72ccb1058a6.png)
Even if I decide this issue, it would still be very good if everyone could download directory via the loader module dmsf

**Comment by picman** [comment]
The Redmine must by run with HTTPS as MS Windows doesn't support basic authentication via HTTP.

**Comment by carukc** [comment]
Hello,

I am having trouble getting WebDav working on Windows (version 10).  I've tried connecting to both:

* https://my.url/dmsf/webdav/ 
* https://my.url/projects/test-project/dmsf/webdav/

.. but I cannot seem to map the drive.

With https://my.url/projects/test-project/dmsf/webdav/ is does ask for my credentials so something must be happening... After entering a valid set of credentials... windows just sits there... Attempting to connect...  until I finally cancel (after 5 to 10 minutes).

In my case I am using Ubuntu 14.04, passenger 5.0.18, nginx 1.8 that is proxying to nginx/passenger/redmine/dmsf in a docker container...   and I have told Windows to 'Connect using different credentials'.

I see that there is module that I can compile into nginx for webdav... do I need to create a custom version of nginx?  I would have thought that nginx would be passing the webdav commands on to redmine via https so I would not think that this would be required.

Perhaps the problem is occurring because https is happening on the nginx proxy rather than the dockerized server?

What do you think?

Many Thanks
Chris

**Comment by picman** [comment]
Have you checked the production.log?

**Comment by carukc** [comment]
Yes... I did... I see a message that seems to be related to the connection attempt but noting more.  Here's what I'm getting:

Started PROPFIND "/projects/test-project/dmsf/webdav" for 90.155.11.150 at 2015-09-24 12:40:58 +0100

ActionController::RoutingError (No route matches [PROPFIND] "/projects/test-project/dmsf/webdav"):
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

Strangely... I've only ever received this message once...., now when I attempt to connect Windows asks for credentials and then says that it cannot connect.

Looking at the message it seems to be saying that I'm using the wrong URL... OK... got it! 

https://my.url/dmsf/webdav/ now seems to work... I have NO idea why it was not working before... perhaps a credentials thing.

Thanks for the help.
Chris

**Comment by picman** [comment]
Yes, the right URL is https://my.url/dmsf/webdav/my_project_identifier

**Comment by bolahg** [comment]
Do you plan to add the ability to download the directory with files through the browser. If so then when?- very necessary. To all to whom this function is necessary to support please.
The topic has long been hanging marked enhancement

**Comment by picman** [comment]
I've already checked the Plupload control allowing drag&drop functionality in DMSF and the control seems to support folders as well as files. Maybe in the next release.

**Comment by carukc** [comment]
Hi Again,  Thanks again for assisting with the webdav problem!  Unfortunately we're still having trouble with the WebDav functionality.  I suspect that the problem has to do with timeouts and over zealous rules on a corporate firewall rather than your fine plugin.

We would love to have the folder drag and drop functionality too.  Perhaps it will work better for us.  Is there anything we can do to help with this feature request?

Thanks
Chris

**Comment by maniachhz** [comment]
@picman 

I need this feature too.

This plugin is very very good. Thanks.

**Comment by bolahg** [comment]
@picman
Ability to download the directory with files through the browser - plan in this release?

**Comment by picman** [comment]
No more support for Russians.
