### ISSUE TITLE
Include plugin dmsf issue 

### ISSUE THREAD

**Issue by bolahg** [danmunn/redmine_dmsf#360]
When working with the task very often have to put one and same files and documents, it would be very convenient if a task was embedded module dmsf, well, just really, really need to be able to link files in a folder with the tasks within the module dmsf.

**Comment by picman** [comment]
You can use wiki formatted links: {{dmsf(12)}}

**Comment by bolahg** [comment]
Here tried to draw what I mean
![example](https://cloud.githubusercontent.com/assets/9381510/6371725/9af6184e-bd28-11e4-840e-6575613a6a49.jpg)
Thank you for what you are doing

**Comment by picman** [comment]
Hm I see it now.

**Comment by anidea** [comment]
I agree if DMSF had the ability to manage all files, that would be great.  EasyRedmine does version control task files.  I think should be be an option or an additional module.

**Comment by carlolars** [comment]
A two-way relation between issue(s) and files/folders would be very nice to have. Today you must add a reference to the issue in the DMSF file/folder description and also add a link in the issue to the DMSF file/folder, and the link in the issue could be in either the description or below in a comment so it can be hard to find.
Having real relations that are listed and used in the same way as subtasks and related issues, both in the issue and the DMSF file/folder would be great.

**Comment by picman** [comment]
Duplicates #48 => closing.
