### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by tpepitone** [danmunn/redmine_dmsf#362]
Attempting install on a working system the command:

rake redmine:plugins:migrate RAILS_ENV="production"

returns:

Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    simple_enum (>= 0) ruby depends on
      activesupport (>= 4.0.0) ruby

    rails (= 3.2.21) ruby depends on
      activesupport (3.2.21)

Details of environment:

Environment:
  Redmine version                2.6.2.stable.14044
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  no plugin installed

Any help appreciated.

**Comment by picman** [comment]
Have you run ```bundle install``` ?

**Comment by tpepitone** [comment]
Yes, with the following results:

Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Installing i18n 0.7.0
Using json 1.8.2
Installing minitest 5.5.1
Installing thread_safe 0.3.4
Installing tzinfo 1.2.2
Installing activesupport 4.2.0
Installing mini_portile 0.6.2
Installing nokogiri 1.6.6.2
Installing rack 1.6.0
Installing uuidtools 2.1.5
Installing dav4rack 0.3.0
Installing rubyzip 1.1.7
Installing simple_enum 2.1.1
Installing xapian-full-alaveteli 1.2.9.5
Installing zip-zip 0.3
Using bundler 1.8.3
Bundle complete! 7 Gemfile dependencies, 16 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by picman** [comment]
Try to install activesupport 3.2.21 if it's required:

```gem install activesupport -v 3.2.21```

**Comment by tpepitone** [comment]
Same result:

gem install activesupport -v 3.2.21
Successfully installed activesupport-3.2.21
Parsing documentation for activesupport-3.2.21
unable to convert "\x80" from ASCII-8BIT to UTF-8 for lib/active_support/values/unicode_tables.dat, skipping
Installing ri documentation for activesupport-3.2.21
1 gem installed


rake redmine:plugins:migrate RAILS_ENV="production"
(in /opt/redmine/current)
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    simple_enum (>= 0) ruby depends on
      activesupport (>= 4.0.0) ruby

    rails (= 3.2.21) ruby depends on
      activesupport (3.2.21)

**Comment by picman** [comment]
Pleas post your ```gem list``` output.

**Comment by tpepitone** [comment]
*** LOCAL GEMS ***

actionmailer (4.2.0, 3.2.21)
actionpack (4.2.0, 3.2.21)
actionview (4.2.0)
activejob (4.2.0)
activemodel (4.2.0, 3.2.21)
activerecord (4.2.0, 3.2.21)
activeresource (4.0.0, 3.2.21)
activesupport (4.2.0, 3.2.21)
arel (6.0.0, 3.0.3)
bigdecimal (1.2.7, 1.2.0)
builder (3.2.2, 3.0.4)
bundler (1.8.3, 1.7.6)
bundler-unload (1.0.2)
coderay (1.1.0)
daemon_controller (1.2.0)
dav4rack (0.3.0)
erubis (2.7.0)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
globalid (0.3.3)
hike (2.1.3, 1.2.3)
i18n (0.7.0, 0.6.11)
io-console (0.4.2)
journey (1.0.4)
jquery-rails (4.0.3, 3.1.2)
json (1.8.2, 1.7.7)
loofah (2.0.1)
mail (2.6.3, 2.5.4)
mime-types (2.4.3, 1.25.1)
mini_portile (0.6.2)
minitest (5.5.1, 4.3.2)
multi_json (1.10.1)
mysql2 (0.3.18)
net-ldap (0.11, 0.3.1)
nokogiri (1.6.6.2)
passenger (4.0.59)
polyglot (0.3.5)
psych (2.0.13, 2.0.0)
rack (1.6.0, 1.4.5)
rack-cache (1.2)
rack-openid (1.4.2)
rack-ssl (1.4.1, 1.3.4)
rack-test (0.6.3)
rails (4.2.0, 3.2.21)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.5)
rails-html-sanitizer (1.0.1)
rails-observers (0.1.2)
railties (4.2.0, 3.2.21)
rake (10.4.2, 0.9.6)
rbpdf (1.18.5)
rdoc (4.0.0, 3.12.2)
redcarpet (2.3.0)
request_store (1.0.5)
rmagick (2.13.4)
ruby-openid (2.3.0)
rubygems-bundler (1.4.4)
rubyzip (1.1.7)
rvm (1.11.3.9)
simple_enum (2.1.1)
sprockets (2.12.3, 2.2.3)
sprockets-rails (2.2.4)
test-unit (2.0.0.0)
thor (0.19.1)
thread_safe (0.3.4)
tilt (1.4.1)
treetop (1.4.15)
tzinfo (1.2.2, 0.3.43)
uuidtools (2.1.5)
xapian-full-alaveteli (1.2.9.5)
zip-zip (0.3)

**Comment by picman** [comment]
No idea, sorry.

**Comment by isdsc** [comment]
How about changing `gem 'simple_enum'` line in your Gemfile to:
`gem 'simple_enum', "< 2.0.0"`
then, run
`bundle install`

**Comment by tpepitone** [comment]
Actually I think it's sorted out now.
