### ISSUE TITLE
EasyRedmine DMSF compatibility issues

### ISSUE THREAD

**Issue by anidea** [danmunn/redmine_dmsf#363]
I've upgraded my Redmine to EasyRedmine but I want to keep the awesome functionality of DMSF, not to mention I have a lot of files there.  It most works, but there are a few compatibility issues.

1.  The .hidden ccs flag conflicts with EasyRedmines and inhibits file uploading in the EasyRedmine task, file upload screen.

![image](https://cloud.githubusercontent.com/assets/4162332/6537177/2fe6f126-c422-11e4-9ed4-03f92b348554.png)

If I remove the .hidden tag from above, the button works.  With hidden active with DMSF active, the button won't work.

2.  In the DMSF screen, two buttons, lock and notifications icons do not show.  The width and height tags are driven to 0 (I'm not a ccs person) and hide the icons.

![image](https://cloud.githubusercontent.com/assets/4162332/6537160/167c5988-c422-11e4-9e76-ed194e217152.png)

I really love this module.  Please help me get this fixed.  I'm happy to test.

Thanks,

Gabriel

**Comment by picman** [comment]
I've renamed hidden ccs style to invisible. That might help. Could you test the development branch 1.5.1-devel with EasyRedmine, please?

**Comment by anidea** [comment]
I loaded it up and 1.5.1 crashed the whole thing.  Is there an upgrade script?  I'm currently running 1.49, so I would assume 1.5 is greater than that.  Is there a simple patch I could apply or generate?

**Comment by picman** [comment]
You must certainly run bundle install and plugin migration.
--
Karel Pièman

On 16. 3. 2015, at 18:28, anidea <notifications@github.com<mailto:notifications@github.com>> wrote:


I loaded it up and 1.5.1 crashed the whole thing. Is there an upgrade script? I'm currently running 1.49, so I would assume 1.5 is greater than that. Is there a simple patch I could apply or generate?

**Comment by anidea** [comment]
I'll have to figure out another way to test.  This is a production box and if I migrate, I'll get stuck on a newer/test version.  I'll keep you posted.

**Comment by picman** [comment]
You can make the changes manually. See the last commit referred above:

https://github.com/danmunn/redmine_dmsf/commit/046a6b8fcd1684025fca85e5f6bb3a45235eca7d

**Comment by anidea** [comment]
Worked great!  Since this seems to be a plugin name space issue, I may suggest all plugin styles start with dmsf like dmsf_hidden.

I can select the add attachment button now!

Now that this worked, is this the same issue as the lock and notifications icons?

Thanks Picman!

**Comment by picman** [comment]
No, it's not, I'm afraid. The only style added by the plugin to the element is the icon. E.g. in case of  the lock:

``` css
.icon-dmsf-lock {
    background-image: url("../images/lock.png");
}
```

Could you check with _Inspect Element_ (in Firefox) what property sets with and height to zero and which css file is responsible for that?

![firefox_inspector](https://cloud.githubusercontent.com/assets/779003/6692162/51ff7fce-cccb-11e4-8012-66aa1462bab7.png)

**Comment by anidea** [comment]
It does set the width and height to zero.
![image](https://cloud.githubusercontent.com/assets/4162332/6692303/58bfa7c2-cca2-11e4-85ac-d066b83bc9f2.png)

I see a few things.  1.  The names of the icons are the same as dmsf.  Note the icons I posted are not the DMSF ones.  2.  I don't see any styles which set them to a size or force them to zero.  

Can the ordering of the 'cascading' of the style sheet be changed?

![image](https://cloud.githubusercontent.com/assets/4162332/6692402/dffb318e-cca2-11e4-8850-8a64ce190fe1.png)

This is after I forced an icon to 21x19 pixels.

Does this help?

**Comment by picman** [comment]
I'm sorry, no idea...

**Comment by anidea** [comment]
Thanks for your help.  Should I re-post the second issue or will someone else pick up this thread?

**Comment by picman** [comment]
No new issue needed as this remains open.

**Comment by picman** [comment]
I've just changed commands icons in scope of #414. Can you  test the master branch. please?

**Comment by anidea** [comment]
Hi Karel,

Thank you, but I had to move from DMSF.  I can no longer test.

Take care,

Gabriel

Gabriel Goldstein
CEO/Chief Product Designer
New Address!!
Anidea Engineering, Inc.
8020 Belvedere Rd. Ste #1
West Palm Beach, FL 33411
Direct:  561-806-0110
Tel:  561-383-7311 x7110
Cell: 954-254-9898
Email:  gabrielg@anidea-engineering.com<mailto:gabrielg@anidea-engineering.com>
www.anidea-engineering.com<http://www.anidea-engineering.com/>
P Please consider the environment before printing this e-mail
THIS DOCUMENT CONTAINS INFORMATION INTENDED FOR THE EXCLUSIVE USE OF THE INDIVIDUAL TO WHOM IT IS ADDRESSED AND MAY CONTAIN INFORMATION THAT IS PROPRIETARY, PRIVILEGED, CONFIDENTIAL AND/OR EXEMPT FROM DISCLOSURE UNDER APPLICABLE LAW. IF YOU ARE NOT THE INTENDED RECIPIENT (OR ANY EMPLOYEE OR AGENT RESPONSIBLE FOR DELIVERING THIS DOCUMENT TO THE INTENDED RECIPIENT), OR HAVE RECEIVED THIS COMMUNICATION IN ERROR, YOU ARE HEREBY NOTIFIED THAT ANY COPYING, DISCLOSURE OR DISTRIBUTION OF THIS INFORMATION MAY BE SUBJECT TO LEGAL RESTRICTION OR SANCTION. IN SUCH EVENT, PLEASE NOTIFY THE SENDER TO ARRANGE FOR THE RETURN OR DESTRUCTION OF THE INFORMATION AND ALL COPIES.
