### ISSUE TITLE
unable to properly uninstall under Redmine 3.0.1

### ISSUE THREAD

**Issue by topkool** [danmunn/redmine_dmsf#366]
Procedure:
1. Install the plugin => rake redmine:plugins:migrate RAILS_ENV=production
2. Uninstall the plugin => rake redmine:plugins:migrate VERSION=0 RAILS_ENV=production NAME=redmine_dmsf

Redmine version 3.0.1

---------------------------------------

(in /usr/share/redmine-3.0.1)
Migrating redmine_dmsf (DMSF)...
== 20150202010301 AddUserToLinks: reverting ===================================
-- remove_column(:dmsf_links, :user_id)
   -> 0.2441s
== 20150202010301 AddUserToLinks: reverted (0.2442s) ==========================

== 20150130052716 AddExternal: reverting ======================================
-- change_column(:dmsf_links, :target_id, :integer, {:null=>false})
   -> 0.2086s
-- remove_column(:dmsf_links, :external_url)
   -> 0.2089s
== 20150130052716 AddExternal: reverted (0.4177s) =============================

== 20150120152101 NotificationsNullable: reverting ============================
-- change_column(:projects, :dmsf_notification, :boolean, {:default=>true, :null=>false})
rake aborted!
An error has occurred, all later migrations canceled:

Mysql2::Error: Data truncated for column 'dmsf_notification' at row 1: ALTER TABLE `projects` CHANGE `dmsf_notification` `dmsf_notification` tinyint(1) DEFAULT 1 NOT NULL/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:517:in `change_column'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/usr/share/redmine-3.0.1/plugins/redmine_dmsf/db/migrate/20150120152101_notifications_nullable.rb:28:in `down'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:827:in `down'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:802:in `migrate'
/usr/share/redmine-3.0.1/lib/redmine/plugin.rb:474:in `migrate_plugin'
/usr/share/redmine-3.0.1/lib/redmine/plugin.rb:446:in `migrate'
/usr/share/redmine-3.0.1/lib/redmine/plugin.rb:457:in `migrate'
/usr/share/redmine-3.0.1/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by picman** [comment]
Fixed.

**Comment by topkool** [comment]
Fast and efficient, thanks
