### ISSUE TITLE
Unable to create a folder

### ISSUE THREAD

**Issue by topkool** [danmunn/redmine_dmsf#367]
Redmine Version: 3.0.1 (with redmine_dmsf freshly installed)

- Go to the DMSF tab
- Click on "Create folder"
- Enter the "Title" and leave "Description" empty
- Click on "Create"

The error message is "Title cannot be blank"

**Comment by picman** [comment]
Could you post a corresponding part of the production.log, please?

**Comment by topkool** [comment]
Of course!

This is the production log when I click on "Create"

-----------------------------------

Started POST "/projects/term/dmsf/create" for <masked> at 2015-03-26 10:50:51 +0100
Processing by DmsfController#create as HTML
  Parameters: {"utf8"=>"?", "authenticity_token"=>"<masked>", "dmsf_folder"=>{"title"=>"Title", "dmsf_folder_id"=>"", "description"=>""}, "commit"=>"Create", "id"=>"terminal"}
  Current user: <masked> (id=8)
WARNING: Can't mass-assign protected attributes for DmsfFolder: title, description, dmsf_folder_id

  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/edit.html.erb within layouts/base (7.1ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (2.4ms)
  Rendered plugins/redmine_pretend/app/views/user/_unpretend.html.erb (0.2ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.5ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (1.1ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (3.6ms)
Completed 200 OK in 100ms (Views: 62.6ms | ActiveRecord: 3.8ms)

**Comment by picman** [comment]
Can you re-test it, please?

**Comment by topkool** [comment]
Great, it works. Thanks
