### ISSUE TITLE
search is broken on redmine3

### ISSUE THREAD

**Issue by kiorky** [danmunn/redmine_dmsf#370]
Something i forgot to reactivate is the search, it is currently broken and my RoR knowledge is a bit low to refactor it correctly.

The search api changed, but the big problem is more that with_scope has been phased out and things in redmine_dmsf/app/models/dmsf_file.rb and (folder) need to be reimplemented

**Comment by kiorky** [comment]
see https://github.com/makinacorpus/redmine_dmsf/commit/8c7d1e05899de73943c5d0bc8c5677cfef5b26d4

**Comment by kiorky** [comment]
the other thing is that we need to add a "search_result_ranks_and_ids" method.

**Comment by kiorky** [comment]
cc @danmunn

**Comment by kiorky** [comment]
This is not sufficient isnt it ? (as with_scope does not exists anymore)

**Comment by picman** [comment]
I agree with you but I haven’t installed a Rails4 environment yet. So if you don't provide the changes that must be made, they won't be made.

**Comment by picman** [comment]
Try it now, please.

**Comment by kiorky** [comment]
Yes i understand, i also do not have the timespan to do it myself for now, as i m also not really a RoR dev :), so i ll have to spend a bunch of time on it.

I ll read and maybe install or review your changeset as soon as i can.

**Comment by kiorky** [comment]
@picman 
found the bug !
The current code is working perfectly with my upgrade to redmine 3.0.3

**Comment by kiorky** [comment]
(sorry for the delay but i didnt found a window to test it until today)
