### ISSUE TITLE
Can't move file via WebDav

### ISSUE THREAD

**Issue by traftcools** [danmunn/redmine_dmsf#372]
Move file via WebDav.

･Folder_A
･Folder_B
 └ Folder_B_1

When the file move from Folder_A to Folder_B, "500 Internal Server Error" is returned. but the file is moved.
In another case, When the file move from Folder_B_1 to Folder_B, "412 Precondition Failed" is returned.

I hope the fix for this problem.

**Comment by picman** [comment]
The first case fixed. The second one I'm not able to reproduce. Try it with the updated code, please.
