### ISSUE TITLE
internal 500 error : 1.5.1 stable with redmine 3.0.1 when search in dmsf enabled project

### ISSUE THREAD

**Issue by inseopark** [danmunn/redmine_dmsf#373]
How to reproduce:

Install dmsf & enable in certain project ,

and use search option.
Internal 500 error in browser

in Production Log

ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'projects.status' in 'where clause': SELECT COUNT(*) FROM `dmsf_files` WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='dmsf') ...

**Comment by picman** [comment]
Could you provide a bigger chunk of the log and what were you searching for, the selected option, I mean, please?

**Comment by inseopark** [comment]
Hello Karel,

I hope this log can help this issue.

Thanks for your big effort

Regards

2015-04-07 19:42 GMT+09:00 Karel Picman <notifications@github.com>:

**Comment by picman** [comment]
Which log?

**Comment by inseopark** [comment]
Gmail have cut off production.log file.

I will send tomorrow.
 2015. 4. 8. 오후 3:27에 "Karel Picman" <notifications@github.com>님이 작성:

**Comment by kkayleng** [comment]
I have experienced this issue after installing 1.5.1 to my redmine 3.0.0.stable.
For me, basically any search terms I entered will trigger the Internal 500 server error.

Below snippet is the error found in the "production.log" immediately after I entered a search term "test" in a project with id = "project-cash-calculator".

Started GET "/projects/project-cash-calculator/search?utf8=%E2%9C%93&q=test" for 1.2.3.4 at 2015-04-13 02:11:02 +0000
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"✓", "q"=>"test", "id"=>"project-cash-calculator"}
  Current user: kkayleng@wealthx.com (id=4)
Mysql2::Error: Unknown column 'projects.status' in 'where clause': SELECT COUNT(*) FROM `dmsf_files` WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='dmsf') AND dmsf_files.project_id IN (41) AND dmsf_files.deleted = 0) AND (((LOWER(dmsf_files.name) LIKE '%test%') OR (LOWER(dmsf_file_revisions.title) LIKE '%test%') OR (LOWER(dmsf_file_revisions.description) LIKE '%test%')))
Completed 500 Internal Server Error in 16ms

ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'projects.status' in 'where clause': SELECT COUNT(*) FROM `dmsf_files` WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='dmsf') AND dmsf_files.project_id IN (41) AND dmsf_files.deleted = 0) AND (((LOWER(dmsf_files.name) LIKE '%test%') OR (LOWER(dmsf_file_revisions.title) LIKE '%test%') OR (LOWER(dmsf_file_revisions.description) LIKE '%test%')))):
  lib/redmine/search.rb:127:in `block in load_result_ids'
  lib/redmine/search.rb:125:in `each'
  lib/redmine/search.rb:125:in `load_result_ids'
  lib/redmine/search.rb:115:in `block in load_result_ids_from_cache'
  lib/redmine/search.rb:114:in `load_result_ids_from_cache'
  lib/redmine/search.rb:99:in `result_ids'
  lib/redmine/search.rb:70:in `result_count'
  app/controllers/search_controller.rb:65:in `index'

**Comment by picman** [comment]
Fixed.
