### ISSUE TITLE
Error while trying to move a file

### ISSUE THREAD

**Issue by jmfarina** [danmunn/redmine_dmsf#375]
Hello,
I'm using an app to sync a local folder against Redmine through DMSF's WebDAV functionality, and I'm getting an error while synchronizing. It seems that this app first uploads the file as a temp file (with a temp name, that is), and afterwards attempts to rename it to its proper name. That's when it fails with this error:

NoMethodError (Undefined method: rev for class #<RedmineDmsf::Webdav::DmsfResource:0x00000007d375a0>.):
  dav4rack (0.3.0) lib/dav4rack/resource.rb:114:in `method_missing'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/dmsf_resource.rb:316:in `move'
  dav4rack (0.3.0) lib/dav4rack/resource.rb:116:in `method_missing'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/resource_proxy.rb:115:in `move'
  dav4rack (0.3.0) lib/dav4rack/resource.rb:116:in `method_missing'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/controller.rb:97:in `move'
  dav4rack (0.3.0) lib/dav4rack/handler.rb:30:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.1) lib/rack/openid.rb:99:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.16) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.16) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `_run__2205263011314916917__call__3197804520419583706__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.16) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.16) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.16) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.16) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.16) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:143:in `pass'
  rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
  rack-cache (1.2) lib/rack/cache/context.rb:71:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.16) lib/rails/engine.rb:484:in `call'
  railties (3.2.16) lib/rails/application.rb:231:in `call'
  railties (3.2.16) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.43) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.43) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.43) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.43) lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

Excellent plugin, BTW. Very useful!

**Comment by picman** [comment]
This bug should be fixed in v1.5.1. Which version do you use?

**Comment by jmfarina** [comment]
My bad, we were using 1.4.9 in that env and I couldn't find any similar reported bugs.
Unfortunately I couldn't test it with 1.5.1 since our current Redmine version is lower that the 2.5 required by the plugin. I'll try upgrading as soon as possible.
Thanks!

**Comment by picman** [comment]
Please see the bug #372  and check the revisions https://github.com/danmunn/redmine_dmsf/commit/a9512306d1566eab2d31f0c519b79bffac28e6c5#diff-df1bebdb6eca112123da2e459ac8cfb1 and https://github.com/danmunn/redmine_dmsf/commit/b6e8b08622034ec38419f7076e290ed234e8114a#diff-df1bebdb6eca112123da2e459ac8cfb1
If you make these small amendments in your source code, it should work also in 1.4.9.

**Comment by jmfarina** [comment]
Excellent, worked like a charm. Thank you very much!

I've also added a line to adjust the revision's title, which was being set to a hash; with this patch it's set to match the file name. I've checked the latest revision and this seems to be missing there too.

diff --git a/lib/redmine_dmsf/webdav/dmsf_resource.rb b/lib/redmine_dmsf/webdav/dmsf_resource.rb
index cff5ad3..a7b7887 100644
--- a/lib/redmine_dmsf/webdav/dmsf_resource.rb
+++ b/lib/redmine_dmsf/webdav/dmsf_resource.rb
@@ -313,6 +313,7 @@
             # Update Revision and names of file [We can link to old physical resource, as it's not changed]            
             file.last_revision.name = resource.basename if file.last_revision            
             file.name = resource.basename
+            file.last_revision.title = DmsfFileRevision.filename_to_title(resource.basename)
 
             # Save Changes
             (file.last_revision.save! && file.save!) ? Created : PreconditionFailed

**Comment by picman** [comment]
The line added again. Thank you for your contribution.
