### ISSUE TITLE
Can access WebDAV when redmine is located under sub-URI

### ISSUE THREAD

**Issue by cityant** [danmunn/redmine_dmsf#377]
Hi Picman, my redmine is installed with apache httpd under a sub-uri, such as: http://myserver/redmine, and accordingly, I tried to access WebDAV using uri:  http://myserver/redmine/dmsf/webdav, but nothing showed.

**Comment by picman** [comment]
Please see #332 and let me know whether the fix works. I'll try to modify the code then.

**Comment by cityant** [comment]
Hi, I changed config/routes.rb and lib/redmine_dmsf/webdav/no_parse.rb as dimpfelmoser suggested in #332, and it works.

**Comment by picman** [comment]
Great!

**Comment by picman** [comment]
Having not found a standard way how to detect that Redmine has been installed in a sub-uri I've add a description concerning this issue in the README.

**Comment by cityant** [comment]
Seems there is a global configuration variable Redmine::Utils::relative_url_root. I don't know if the plugin can use it or not.
refer to: http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_on_subdirectory_(sub-URI)_on_Apache

**Comment by picman** [comment]
Solved using Redmine::Utils::relative_url_root
