### ISSUE TITLE
Document Redmine 3.x compatibility

### ISSUE THREAD

**Issue by fbender** [danmunn/redmine_dmsf#379]
Can you please document what is *known to work* **and** *known to be broken* when `dmsf` is used with Redmine 3.x? This is not only useful for admins but also developers who want to fix the remaining issues. The information can but put e.g. into the README or (only for the *known to be broken* items) you can create a bug tag like `compat-3.0` and link to the specific tag search in the README.

**Comment by picman** [comment]
If you are aware of a bug just create a new issue. No extra system needed.
