### ISSUE TITLE
Is there a version of this that works, everything shows failing build

### ISSUE THREAD

**Issue by robgar-rocket** [danmunn/redmine_dmsf#381]
Please let me know

**Comment by picman** [comment]
?

**Comment by robgar-rocket** [comment]
all the builds are showing as failed. I need to know if there is a usable version?

**Comment by Keltrex** [comment]
I'm assuming that you're referring to this:
![failing](https://cloud.githubusercontent.com/assets/10455797/7235059/83264f76-e740-11e4-9afe-6348065d54c7.jpg)

That is unrelated to the condition of the build, it is more the tests themselves failing than the plugin.

DMSF 1.5.1 is the current Stable build, you shouldn't have many problems with it

**Comment by picman** [comment]
There are always problems with Travis CI. Use 1.5.1. Don't worry.
