### ISSUE TITLE
REST API - list of document produces invalid XML

### ISSUE THREAD

**Issue by xwinus** [danmunn/redmine_dmsf#382]
Hello,
I've noticed that the XML code produced by API request for obtaining the list of documents (the code under the _response_ heading here: https://github.com/danmunn/redmine_dmsf/wiki/REST-API#list-of-documents-in-a-given-folder-or-the-root-folder) is not valid. According to the XML spec (http://www.w3.org/TR/2008/REC-xml-20081126/), _There is exactly one element, called the root, or document element, no part of which appears in the content of any other element._ However, in the DMSF REST API this is violated by having two "root elements", `<dmsf_folders />` and `<dmsf_links />`. You can easily check the invalidity by copy&paste the example XML output to any XML validator, for example http://www.xmlvalidation.com.

Thank you, Vaclav Svejcar (Tranetic, s.r.o.)

**Comment by picman** [comment]
Fixed. Changed in wiki too. Thank you for the bug report.
