### ISSUE TITLE
Error when trying to uninstall DMSF

### ISSUE THREAD

**Issue by jmbiollaz** [danmunn/redmine_dmsf#384]
Hello,

On my Redmine 3.0.1, I get the following error when trying to uninstall DMSF.
LoadError: cannot load such file -- dispatcher

Any suggestion?
Thank you,

D:\Programs\Redmine\apps\redmine\htdocs>rake redmine:plugins:migrate NAME=redmin
e_dmsf VERSION=0 RAILS_ENV=production
DL is deprecated, please use Fiddle
rake aborted!
LoadError: cannot load such file -- dispatcher
D:/Programs/Redmine/apps/redmine/htdocs/plugins/redmine_dmsf/init.rb:20:in `<top
 (required)>'
D:/Programs/Redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:155:in `block in l
oad'
D:/Programs/Redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `each'
D:/Programs/Redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `load'
D:/Programs/Redmine/apps/redmine/htdocs/config/initializers/30-redmine.rb:21:in
`<top (required)>'
D:/Programs/Redmine/apps/redmine/config/environment.rb:14:in `<top (required)>'
D:/Programs/Redmine/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_conv
ert_documents.rake:32:in `<top (required)>'
D:/Programs/Redmine/apps/redmine/htdocs/lib/tasks/redmine.rake:179:in `block in
<top (required)>'
D:/Programs/Redmine/apps/redmine/htdocs/lib/tasks/redmine.rake:179:in `each'
D:/Programs/Redmine/apps/redmine/htdocs/lib/tasks/redmine.rake:179:in `<top (req
uired)>'
D:/Programs/Redmine/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by jmbiollaz** [comment]
If I cannot disable the plugin, is there a way to manually drop the dmsf info in the schema?
Now I get errors in Redmine which prevent to access some Redmine features, like:

ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass: 'DmsfFileRevisionCustomField'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite CustomField.inheritance_column to use another column for that information.):
  app/controllers/custom_fields_controller.rb:29:in `block (2 levels) in index'
  app/controllers/custom_fields_controller.rb:27:in `index'
...

**Comment by picman** [comment]
Just remove the plugin folder from the file system.

**Comment by jmbiollaz** [comment]
I have tried that, but still get the Redmine error, when I want to open the custom fields in Redmine Administration

**Comment by picman** [comment]
Check custom_filelds table for DMSF custom_fields and remove them:

```sql
delete from custom_fields where name like 'Dmsf%;
delete from custom_values where custom_field_id not in (select id from custom_fields);
```

**Comment by jmbiollaz** [comment]
Thank you, I have also to issue :

delete from custom_fields where type like 'Dmsf%';

to get rid of all dmsf custom fields and get it working.

Thank you for your support!

**Comment by picman** [comment]
It seems to be your Windows environment problem.

Anyway I've re-test the whole process of migration and rollback and fixed a few errors.
