### ISSUE TITLE
Cannot get email notifications to stop!

### ISSUE THREAD

**Issue by zlacelle** [danmunn/redmine_dmsf#385]
I recently migrated an older DMSF/Redmine instance (Redmine 2.2) to a newer instance (Redmine 2.6.2, newest DMSF).  The default notifications for already existing folders seems to have been "enabled."  This is fine, but...I cannot get notifications to turn off!

I've gone into the DMSF settings and switched it to "Deactivated," as well as made sure that "Notifications On" was showing (indicating that they were off, and that one should turn them on...this is misleading, by the way).

Any ideas about how to make the email spam stop?

**Comment by picman** [comment]
1. DMSF settings option *Notifications* switches on/off notifications for the currently logged project member only.
2. Email notifications for the current folder are manageable from the top command menu.
3. Email notifications for listed files and folders are manageable from the right command menu.
4. The only change that has been made is that the default state of notification is **ON**. You can change it in the plugin settings - **File default notifications**.

**Comment by mettbest** [comment]
Hi ! I have the same problem:
1. DMSF settings option Notifications in the single project is set to DEACTIVATED
2. DMSF plugin settings - File default notifications is set to DEACTIVATED

But still, I get always notifications if I upload a new file.
Redmine v2.4.2.stable
DMSF v1.4.9 stable

How to solve this?
