### ISSUE TITLE
Deleting folders does not delete them entirely

### ISSUE THREAD

**Issue by ubiq314** [danmunn/redmine_dmsf#389]
Create a folder called "X". Delete it. It appears to be gone. Try to recreate it, and get the message "Title has already been taken." Sure enough, the folder is still listed in dmsf_tables (deleting the record manually fixes the problem).

Environment:
  Redmine version                2.6.3.stable
  Ruby version                   2.1.1-p76 (2014-02-24) [x86_64-linux]
  Rails version                  3.2.21
  redmine_dmsf                   1.4.9 stable

**Comment by picman** [comment]
It has been already fixed. Please upgrade DMSF to a newer version. 1.5.1 recommended.

**Comment by ubiq314** [comment]
Thanks.

**Comment by ubiq314** [comment]
I upgraded to 1.5.1, and find the problem has not completely gone away. I performed the following steps:
1. Create a folder called test.2. Delete folder. This appears to succeed, but in fact there is still a record for the folder in dmsf_folders.
3. Create another folder called test. This succeeds (amazingly, in my opinion). Now there are two records for a folder with title "test" in dmsf folders.4. Attempt to delete folder. This fails, with "Title has already been taken." The two records remain.
If you'd like me to write this up as an issue, I'd be glad to. On the other hand, if this is already known to you, I apologize for taking up your time.
-richard

**Comment by picman** [comment]
If you delete a folder, it remains in the database but is marked as deleted. In the user interface it disappears from the main view but it's still visible in the trash bin (an icon in the top right corner).

The internal constraint checks uniqueness of [title, deleted]. So it's allowed to have two folders of the same title; one in the main view and one in the trash bin. However, it's not allowed to have two folders of the same title either in the main view or in the trash bin.

That's the reason of the behaviour you're describing.

**Comment by ubiq314** [comment]
I get it. So the second time try to delete it, I'm really trying to move it to the trash folder, which already has a file by that name, so it disallows the duplicate. Thanks.
-richard

**Comment by ubiq314** [comment]
Am I correct in understanding that DMSF will not support Redmine 3.0 until release 1.5.2? If so, do you have an estimated release date? Thanks for your help.
Richard HoffmanParsons Corporationcontractor to the Army Research Laboratory

**Comment by picman** [comment]
Yes, you're. However, 1.5.2 has been already released.
--
Karel Pičman

On 24. 7. 2015, at 19:20, ubiq314 <notifications@github.com<mailto:notifications@github.com>> wrote:

Am I correct in understanding that DMSF will not support Redmine 3.0 until release 1.5.2? If so, do you have an estimated release date? Thanks for your help.
Richard HoffmanParsons Corporationcontractor to the Army Research Laboratory

**Comment by ubiq314** [comment]
When I look at https://github.com/danmunn/redmine_dmsf, I see:
    The current version of Redmine DMSF is 1.5.2 
I should ignore the "build failing" part and download it?
-richard

**Comment by picman** [comment]
Yes, you can download it. Travis build system doesn't work very well.
