### ISSUE TITLE
Searchable document details

### ISSUE THREAD

**Issue by mrazek** [danmunn/redmine_dmsf#391]
First, thanks for great plugin, it is really helpful!

Second, I would like to ask whether it is possible to make document description and document comment searchable in redmine. I am not able to search throuh these fields now.

**Comment by picman** [comment]
It should work now. Do not forget to uncheck _Search titles only_ option while searching.

**Comment by mrazek** [comment]
Thank you for quick patch. I tried to upgrade to 1.5.2 version, unfortunately this version didn't work for me so I came back to 1.5.1 which works. I have to try it later again when I am not so busy.

**Comment by mrazek** [comment]
I finally get it to work, but had to manually add a column "limit" to the "dmsf_files" table otherwise and error occured when I tried to search. Once I manually added limit column and set it to 11 for all files, I was able to search through the comments. However, I am not sure whether I made this correctly. Shouldn't be the database upgraded during migrate command automatically?

**Comment by mrazek** [comment]
One more comment just to describe more in detail what was the process of upgrade...
I purged the database in 1.4.9 and retored it in 1.5.1 version (I migrated between servers) and the I tried to upgrad dmsf to 1.5.2-devel version.

**Comment by picman** [comment]
I'm pretty sure that there shouldn’t be LIMIT column in DMS_FILES table. Please post the error message you've got.

**Comment by mrazek** [comment]
Here is the output from production.log
```
Started GET "/search?utf8=%E2%9C%93&q=Nemistna+poznamka" for 109.107.211.244 at 2015-05-26 16:15:37 +0200
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"âś“", "q"=>"Nemistna poznamka"}
  Current user: honza (id=3)
Completed 500 Internal Server Error in 428.8ms

ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column dmsf_files.limit does not exist
LINE 1: ...iles"."id" WHERE "dmsf_files"."deleted" = 'f' AND "dmsf_file...
                                                             ^
: SELECT DISTINCT COUNT(DISTINCT "dmsf_files"."id") FROM "dmsf_files" INNER JOIN "projects" ON "projects"."id" = "dmsf_files"."project_id" INNER JOIN "dmsf_file_revisions" ON "dmsf_file_revisions"."dmsf_file_id" = "dmsf_files"."id" WHERE "dmsf_files"."deleted" = 'f' AND "dmsf_files"."limit" = 11 AND (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='dmsf')) AND (((LOWER(dmsf_files.name) LIKE '%nemistna%') OR (LOWER(dmsf_file_revisions.title) LIKE '%nemistna%') OR (LOWER(dmsf_file_revisions.description) LIKE '%nemistna%') OR (LOWER(dmsf_file_revisions.comment) LIKE '%nemistna%')) AND ((LOWER(dmsf_files.name) LIKE '%poznamka%') OR (LOWER(dmsf_file_revisions.title) LIKE '%poznamka%') OR (LOWER(dmsf_file_revisions.description) LIKE '%poznamka%') OR (LOWER(dmsf_file_revisions.comment) LIKE '%poznamka%')))):
  app/controllers/search_controller.rb:74:in `block in index'
  app/controllers/search_controller.rb:73:in `each'
  app/controllers/search_controller.rb:73:in `index'
```

**Comment by picman** [comment]
I really don't know :-(
``` sql
AND "dmsf_files"."limit" = 11
```
its a mystery for me.

I've installed Postgres to test it because generated SQL statements may differ from MySQL. But, whereas your generated query looks like follows:

```sql
SELECT DISTINCT COUNT(DISTINCT "dmsf_files"."id") 
FROM "dmsf_files" 
INNER JOIN "projects" ON "projects"."id" = "dmsf_files"."project_id" 
INNER JOIN "dmsf_file_revisions" ON "dmsf_file_revisions"."dmsf_file_id" = "dmsf_files"."id" WHERE "dmsf_files"."deleted" = 'f' 
AND "dmsf_files"."limit" = 11 
AND (projects.status <> 9 
AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='dmsf')) 
AND (((LOWER(dmsf_files.name) LIKE '%nemistna%') 
OR (LOWER(dmsf_file_revisions.title) LIKE '%nemistna%') 
OR (LOWER(dmsf_file_revisions.description) LIKE '%nemistna%') 
OR (LOWER(dmsf_file_revisions.comment) LIKE '%nemistna%')) 
AND ((LOWER(dmsf_files.name) LIKE '%poznamka%') 
OR (LOWER(dmsf_file_revisions.title) LIKE '%poznamka%') 
OR (LOWER(dmsf_file_revisions.description) LIKE '%poznamka%') 
OR (LOWER(dmsf_file_revisions.comment) LIKE '%poznamka%'))))
```

my query looks like follows:

```sql
SELECT DISTINCT "dmsf_files".* 
FROM "dmsf_files"
INNER JOIN "projects" ON "projects"."id" = "dmsf_files"."project_id" 
INNER JOIN "dmsf_file_revisions" ON "dmsf_file_revisions"."dmsf_file_id" = "dmsf_files"."id" 
WHERE "dmsf_files"."deleted" = 'f' 
AND (projects.status <> 9 
AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='dmsf')) 
AND (((LOWER(dmsf_files.name) LIKE '%nemistna%') 
OR (LOWER(dmsf_file_revisions.title) LIKE '%nemistna%') 
OR (LOWER(dmsf_file_revisions.description) LIKE '%nemistna%') 
OR (LOWER(dmsf_file_revisions.comment) LIKE '%nemistna%')) 
AND ((LOWER(dmsf_files.name) LIKE '%poznamka%') 
OR (LOWER(dmsf_file_revisions.title) LIKE '%poznamka%') 
OR (LOWER(dmsf_file_revisions.description) LIKE '%poznamka%') 
OR (LOWER(dmsf_file_revisions.comment) LIKE '%poznamka%')))
```

**Comment by mrazek** [comment]
Sounds interesting. I really don't know what is the difference. I run it on debian 8.1, postgres 9.4.3. This is configuration taken from Redmine info.
```
Environment:
  Redmine version                2.5.3.stable.14266
  Ruby version                   2.1.3-p242 (2014-09-19) [i686-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.5.2 devel
```
But I cannot imagine whay i should add a condition to the query just because of different PostgreSQL version or Rails version... Just for case if it helps somehow. I may go through the code for myself, but I have never coded in ruby so this may take a while... If I'll bump into something, I'll let you know.

Again, thanks for very useful plugin!

**Comment by picman** [comment]
I work with Redmine 3.0.3 and consequently with newer Rails and Ruby. All in all I appreciate any insight.
The SQL query for searching is generated in _app/models/dmsf_file.rb_ in function _self.search_.

You can add a code snippet on the line 334 just bellow results assignment as follows:

``` ruby
results = []    
    
visible.joins(:project, :revisions).
where(project_conditions.join(' AND ')).scoping do
  where(find_options[:conditions]).scoping do        
    results = where(limit_options).uniq
  end
end
++ Rails.logger.info results.to_sql
```
and than to try to find who is responsible for the _limit_ column in the lines above.

**Comment by picman** [comment]
No reply for almost one month => closed.

**Comment by mrazek** [comment]
Just for an info.. 
Last weeks I was really busy and after that I had holidays. I will try to do what you suggested within one or two weeks, hopefully.

**Comment by mrazek** [comment]
I found some time today to give it a try, all I was able to get from log is that variable `limits_options` takes the `limit=>11` option from `options` variable. 
```
limit_options:
{:limit=>11}
options:
{:all_words=>true, :titles_only=>false, :limit=>11, :offset=>nil, :before=>true}
```
Dunno if it is helpful. I will try to give it a tray in next days again...

**Comment by picman** [comment]
I see the problem now.

**Comment by picman** [comment]
Fixed. Thank you for the bug report.

**Comment by mrazek** [comment]
I am glad it was helpful.
Thank you for fixing it.
