### ISSUE TITLE
File can't be created in storage directory (Redmine 3.0.3)

### ISSUE THREAD

**Issue by tlaskows** [danmunn/redmine_dmsf#393]
I am attempting to migrate a Redmine 2.5.x server to the newest Redmine and getting this error in plugin settings.  The path specified in the settings exists and has owner set as www-data:www-data.

Environment:
  Redmine version                3.0.3.stable
  Ruby version                   2.0.0-p645 (2015-04-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Git                            1.9.5
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.5.1 stable

**Comment by picman** [comment]
Please check whether there is rw access for the folder owner and provide a part of the log corresponding with the error.
(For Redmine version >= 3, I recommend using DMSF 1.5.2)

**Comment by tlaskows** [comment]
Hi,

The permissions appear to be correct.

I was going to try 1.5.2, but when removing the current version I get en error:

Migrating redmine_dmsf (DMSF)...
== 20140314132501 NotificationsOn: reverting ==================================
-- change_column(:projects, :dmsf_notification, :boolean, {:default=>false, :null=>true})
   -> 0.0053s
-- change_column(:dmsf_folders, :notification, :boolean, {:default=>false, :null=>false})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Data truncated for column 'notification' at row 130: ALTER TABLE `dmsf_folders` CHANGE `notification` `notification` tinyint(1) DEFAULT 0 NOT NULL/opt/redmine-3.0.3-0/apps/redmine/htdocs/plugins/redmine_dmsf/db/migrate/20140314132501_notifications_on.rb:28:in `down'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/plugin.rb:474:in `migrate_plugin'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/plugin.rb:446:in `migrate'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/plugin.rb:457:in `migrate'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

Could there be some database corruption going on?

Thanks,

-Tom

**Comment by picman** [comment]
It probably means that the column notification contains values that can't be converted to the data type tinyint. Try to fix it prior the migration. The column should contain 1 or 0 only.
