### ISSUE TITLE
Error when uploading files

### ISSUE THREAD

**Issue by Atmis** [danmunn/redmine_dmsf#396]
Hi,

I migrated this week-end our installation with Redmine trunk, and DMSF 1.5.2-devel (both downloaded last sunday).
We are not able to upload files anymore with JS, and we get the following message :
![screenshot 2015-06-23 19_41_06 pma](https://cloud.githubusercontent.com/assets/5329747/8312986/450c9ede-19e0-11e5-9fdd-d4df71436836.png)

If we use the standard interface to drop files, then it works fine :
![screenshot 2015-06-23 19_45_17 pma](https://cloud.githubusercontent.com/assets/5329747/8313013/71e3593e-19e0-11e5-9f9e-343ec477d285.png)

We are currently on a Windows Platform :
```
Environment:
  Redmine version                3.0.3.devel
  Ruby version                   2.0.0-p645 (2015-04-13) [x64-mingw32]
  Rails version                  4.2.2
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            1.9.5
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.10
  redmine_checklists             3.1.1
  redmine_contacts               4.0.1
  redmine_csv_with_bom           0.0.2
  redmine_dmsf                   1.5.2 devel
  redmine_inline_note_images_plugin 0.0.1
  redmine_landing_page           0.1.0
  redmine_last_updated_by_column 0.3.0
  redmine_lightbox2              0.2.2
  redmine_local_avatars          0.2.0
  redmine_mail_handler_clean_body_regexp 0.1
  redmine_my_page_queries        2.1.6
  redmine_silencer               0.4.0
  redmine_stealth                0.6.0
  sidebar_hide                   0.0.7
```

I investigated a little, and here is the Redmine log, at a debug level :
```
Started POST "/projects/test/dmsf/upload/file" for 123.123.123.123 at 2015-06-23 19:18:30 +0200
Processing by DmsfUploadController#upload_file as */*
  Parameters: {"name"=>"Organisation 2015.pptx", "authenticity_token"=>"AZERTYUIOPQSDFGHJKLMWXCVBN1234567890", "file"=>#<ActionDispatch::Http::UploadedFile:0x0000000648f098 @tempfile=#<Tempfile:C:/TEMP/RackMultipart20150623-4164-19bhq0o.pptx>, @original_filename="Organisation 2015.pptx", @content_type="application/vnd.openxmlformats-officedocument.presentationml.presentation", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"Organisation 2015.pptx\"\r\nContent-Type: application/vnd.openxmlformats-officedocument.presentationml.presentation\r\n">, "id"=>"test"}
  [1m[36m (0.0ms)[0m  [1mSELECT MAX("settings"."updated_on") FROM "settings"[0m
  [1m[35mUser Load (0.0ms)[0m  SELECT  "users".* FROM "users" WHERE "users"."type" IN ('User', 'AnonymousUser') AND "users"."status" = $1 AND "users"."id" = $2 LIMIT 1  [["status", 1], ["id", 70]]
  Current user: administrateur (id=70)
  [1m[36m (0.0ms)[0m  [1mSELECT MAX("contacts_settings"."updated_on") FROM "contacts_settings"[0m
  [1m[35mProject Load (15.6ms)[0m  SELECT  "projects".* FROM "projects" WHERE "projects"."identifier" = $1 LIMIT 1  [["identifier", "test"]]
  [1m[36m (0.0ms)[0m  [1mSELECT "enabled_modules"."name" FROM "enabled_modules" WHERE "enabled_modules"."project_id" = $1[0m  [["project_id", 1]]
Completed 500 Internal Server Error in 16ms (ActiveRecord: 15.6ms)

Errno::EACCES (Permission denied - (C:/TEMP/RackMultipart20150623-4164-19bhq0o.pptx, C:/TEMP/150623191830_Organisation_2015.pptx)):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
It seems that the file can't be renamed properly, and stays in the TEMP folder :
![screenshot 2015-06-23 19_41_23 pma](https://cloud.githubusercontent.com/assets/5329747/8313116/0bbb5cb4-19e1-11e5-9ad0-16b790d49a71.png)
Originally, the path for the TMP folder was c:\Windows\TEMP, I changed it to C:\TEMP (this is setup in an environment variable), and I doubled checked the authorization for that folder. It is all open.

Any idea on a way to solve this ?

**Comment by picman** [comment]
Yes, it'a obviously a permission problem:
```
Errno::EACCES (Permission denied - (C:/TEMP/RackMultipart20150623-4164-19bhq0o.pptx, C:/TEMP/150623191830_Organisation_2015.pptx)):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
The web application is not allowed to moved files from c:/temp folder very probably.

There was on change in v1.5.2. Uploaded files are now moved instead of copied and deleted in order to speed up the uploading.

I can't help you more as I'm not familiar with Windows installation. I see no sudo_mode.rb in my Redmine installation.

**Comment by Atmis** [comment]
Ok, until we find a solution, I switched back to dmsf 1.5.1 stable which works fine. It seems related to that  change you introduce (move instead of copy and delete).

I checked again the authorizations of the temp folder, but a can't setup less permission (everyone is allowed to modify).

I had a quick look on the internet, apparently some people get issues with FileUtils.mv on Windows, maybe because the file itself is locked by the ruby handle. It could be a lead.

The sudo mode has been introduced in Redmine trunk for release in version 3.1. I haven't activated it tough.
http://www.redmine.org/issues/19851

**Comment by picman** [comment]
Can you try it with 1.5.2 again, please?

**Comment by Atmis** [comment]
Hi Karel,

You are always the best :+1:  I tried your fix and it works fine, thank you ! The file is renamed in the temp folder after upload, and deleted after the file is commited.

I looked at your change, but I don't understand exactly what you did. Have you switch back to the old behavior (copy and delete ?)

Pierre

**Comment by picman** [comment]
In short, yes.

--
Karel Pičman

On 24. 6. 2015, at 16:13, Atmis <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Karel,

You are always the best [:+1:]  I tried your fix and it works fine, thank you ! The file is renamed in the temp folder after upload, and deleted after the file is commited.

I looked at your change, but I don't understand exactly what you did. Have you switch back to the old behavior (copy and delete ?)

Pierre

**Comment by Atmis** [comment]
Ok, I am sorry that the fileutils.mv command is unreliable on Windows platform, and that it may impact the speed upload on other platforms.

**Comment by soncu** [comment]
I saw the same error after converting documents to dmsf files and noticed that created folder under `dmsf` has root ownership instead of **www-data**. After changing the owner, problem was solved.

**Comment by picman** [comment]
It might be caused by running the rake task as root. You shoul run it as www-data instead:

```ruby
sudo -u www-data rake...
```

**Comment by soncu** [comment]
Thanks for the tip.
