### ISSUE TITLE
CMIS support

### ISSUE THREAD

**Issue by danmunn** [danmunn/redmine_dmsf#4]
Investigation the provision of CMIS support within DMSF

**Comment by StefanPofahl** [comment]
I added DMSF in the corresponding Wikipedia article:  
[Content Management Interoperability Services](https://en.wikipedia.org/wiki/Content_Management_Interoperability_Services#CMIS_Servers)
[Content Management Interoperability Services (Deutsch)](https://de.wikipedia.org/w/index.php?title=Content_Management_Interoperability_Services&stable=0#Liste_der_Implementierungen)

**Comment by picman** [comment]
There is a typo: DMFS X DMSF, in both languages.
