### ISSUE TITLE
Documents not found after upgrade from DMSF v1.3 to v1.4.5

### ISSUE THREAD

**Issue by nieboe** [danmunn/redmine_dmsf#40]
We upgraded the DMSF plugin from v1.3 to v1.4.5. After the upgrade, a few DMSF documents were missing (download failed with "Redmine 500 error"). This is the top of the backtrace in our production.log:
```
ActionController::MissingFile (Cannot read file /var/redmine-dmsf/p_newproject/130209148904_159_my_document.docx):
  actionpack (3.2.6) lib/action_controller/metal/data_streaming.rb:71:in `send_file'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:48:in `send_file'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:46:in `send_file'
  plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:220:in `send_revision'
  plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:51:in `show'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
```

The missing documents had been copied from project "oldproject" to "newproject" before the upgrade. "oldproject" was archived after the documents were copied.
The document has not been updated after it had been copied.
The missing file was moved to "p_oldproject" during the upgrade.

It looks like DMSF does not create a new file on the hard drive when a document is copied in the DMSF web interface, and the migration script fails to create copies in all target folders during the upgrade.

**Comment by picman** [comment]
Fixed.
