### ISSUE TITLE
internal server error fulltext search

### ISSUE THREAD

**Issue by softadminlesia** [danmunn/redmine_dmsf#400]
Hi

with redmine 3.0.3.stable.14294 and dmsf v1.5.1

i experienced 
Started GET "/search?utf8=%E2%9C%93&q=canvas" for .....
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"✓", "q"=>"canvas"}
  Current user: anonymous
Completed 500 Internal Server Error in 144ms (ActiveRecord: 10.2ms)

NoMethodError (undefined method `id' for #<Hash:0x00000006c03b08>):
  lib/redmine/search.rb:127:in `block in load_result_ids'
  lib/redmine/search.rb:125:in `each'
  lib/redmine/search.rb:125:in `load_result_ids'
  lib/redmine/search.rb:115:in `block in load_result_ids_from_cache'
  lib/redmine/search.rb:114:in `load_result_ids_from_cache'
  lib/redmine/search.rb:99:in `result_ids'
  lib/redmine/search.rb:70:in `result_count'
  app/controllers/search_controller.rb:65:in `index'

could you help me debug this ?

thanks

**Comment by picman** [comment]
Redmine 3.0.3 is not compatible with DMSF 1.5.1 I'm afraid. Please use 1.5.2-devel instead or wait for 1.5.2 release (It will be release this or the next week.
--
Karel Pičman

On 2. 7. 2015, at 13:57, softadminlesia <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

with redmine 3.0.3.stable.14294 and dmsf v1.5.1

i experienced
Started GET "/search?utf8=%E2%9C%93&q=canvas" for .....
Processing by SearchController#index as HTML
Parameters: {"utf8"=>"✓", "q"=>"canvas"}
Current user: anonymous
Completed 500 Internal Server Error in 144ms (ActiveRecord: 10.2ms)

NoMethodError (undefined method id' for #<Hash:0x00000006c03b08>):
lib/redmine/search.rb:127:inblock in load_result_ids'
lib/redmine/search.rb:125:in each'
lib/redmine/search.rb:125:inload_result_ids'
lib/redmine/search.rb:115:in block in load_result_ids_from_cache'
lib/redmine/search.rb:114:inload_result_ids_from_cache'
lib/redmine/search.rb:99:in result_ids'
lib/redmine/search.rb:70:inresult_count'
app/controllers/search_controller.rb:65:in `index'

could you help me debug this ?

thanks
