### ISSUE TITLE
Link between project on Redmine 3.0

### ISSUE THREAD

**Issue by algorys** [danmunn/redmine_dmsf#401]
Hello,

I've installed your plugin on my redmine 3.0 server.

When I attempt to link a document between two different projects, 501 error happens. I've tried inside sub-project and aside project and I have similar issue.

Have you an idea to solve this ?

Thanks,

My configuration :
Debian wheezy
Redmine 3.0.3
DMSF : 1.5.1 stable
Other plugins :
 * [Advanced roadmap & milestones plugin](https://github.com/ekylibre/redmine_advanced_roadmap_v2) 2.4.2
 * [Redmine Agile plugin (Light version)](http://redminecrm.com) 1.3.9
 * [Redmine Bootstrap Kit plugin](https://github.com/jbox-web/redmine_bootstrap_kit) 0.2.3	
 * [Redmine CRM plugin (Light version)](http://redminecrm.com) 4.0.1
 * [Redmine Git Remote](https://github.com/dergachev/redmine_git_remote) 0.0.1	
 * [Redmine Jenkins plugin](https://github.com/jbox-web/redmine_jenkins) 1.0.1	
 * [Redmine LDAP Sync](https://github.com/thorin/redmine_ldap_sync) 2.0.7.devel.g202f7c74b9

**Comment by picman** [comment]
DMSF 1.5.1 is not compatibile with Redmine >= 3.0, I'm afraid. Please try 1.5.2-devel or wait for 1.5.2 release.

**Comment by algorys** [comment]
Ok, thanks for added the bug to devel version. I'll test 1.5.2 on server's test and wait release to put it in production.

**Comment by algorys** [comment]
Solved
