### ISSUE TITLE
Cannot get Webdav to work

### ISSUE THREAD

**Issue by marchoeppner** [danmunn/redmine_dmsf#402]
Hi,

been happily testing dmsf but realized that the webdav feature of it doesn't work for me. Specifically:

- Navigating to "http://server_ip/redmine/dsmf/webdav returns an empty page
- Connecting to the same address from OsX Finder fails at the authentication (tried both the admin user and my own user, which is "Manager" and has all dmsf permissions set

The log file just states:
Started GET "/redmine/dmsf/webdav" for some_ip at 2015-07-10 13:17:03 +0200

That's it. 

Setup is a Ubuntu 14.04 virtual machine with the following specs:

Default administrator account changed	True
Attachments directory writable	True
Plugin assets directory writable (./public/plugin_assets)	True
RMagick available (optional)	True
ImageMagick convert available (optional)	True

Environment:
  Redmine version                2.6.6.stable
  Ruby version                   2.0.0-p643 (2015-02-25) [x86_64-linux]
  Rails version                  3.2.22
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.5.1 stable

**Comment by marchoeppner** [comment]
Maybe some further information:

The site is served through Apache2 - and the DMSF Documentation does not make any mention of specific Apache2 settings needed to make dmsf webdav work. Are there any?

**Comment by picman** [comment]
1. Have you enabled WebDAV in the plugin settings?

![webdav](https://cloud.githubusercontent.com/assets/779003/8645317/9fc91332-2946-11e5-8b6e-f50430176df1.png)

2. Add a project identifier to the URL. Eg

```
cadaver https://your_redmine.com/dmsf/webdav/your_project
```

**Comment by marchoeppner** [comment]
Hi,

yes the webdav plugin is enabled as shown in your screenshot. I also tried adding a project name to the url, same issue. I am wondering if this has to do with https versus http? Port 443 is blocked on the machine (requested for it to be opened now).

**Comment by picman** [comment]
If you access WebDAV from a Windows machine, the server application must be available on HTTPS (port 443) otherwise basic authentication used in the application is not supported in Windows.
