### ISSUE TITLE
directory can't remove via webdav

### ISSUE THREAD

**Issue by HeuJung** [danmunn/redmine_dmsf#407]
![image](https://cloud.githubusercontent.com/assets/10345170/8740986/3eb7d2e6-2c8d-11e5-82d0-def90d77595e.png)

1. I created a "test dir" directory.
2. And removed.
3. And again created a "test dir" directory.
4. I can not remove.
5. Empty the Trash.
6. I can finally removed.

**Comment by picman** [comment]
I'm afraid that it works for me:

``` bash
$ cadaver http://localhost:3000/dmsf/webdav/c1
dav:/dmsf/webdav/c1/> mkdir trash
Creating `trash': succeeded.
dav:/dmsf/webdav/c1/> rmcol trash
Deleting collection `trash': succeeded.
dav:/dmsf/webdav/c1/> mkdir trash
Creating `trash': succeeded.
dav:/dmsf/webdav/c1/> 
```

Can you post your Redmine and DMSF plugin version and a corresponding log records related to the issue, please?

**Comment by picman** [comment]
No feedback for a long time => Closed.
