### ISSUE TITLE
after upgrade 1.5.1 -> 1.5.2. "top level based search" results in http:500 when "Documents" is included

### ISSUE THREAD

**Issue by tjaeger** [danmunn/redmine_dmsf#408]
Do below messages reveal anything i may oversee ?
- - - - - - - - - - - - - - - - - - - - - - 
/log/redmine.log
```
Parameters: {"utf8"=>"✓", "q"=>"TEST"}
  Current user: tjaeger (id=14)
Completed 500 Internal Server Error in 154.2ms

NoMethodError (undefined method `event_description=' for #<DmsfFile:0x007faf2c62d828>):
  app/controllers/search_controller.rb:74:in `block in index'
  app/controllers/search_controller.rb:73:in `each'
  app/controllers/search_controller.rb:73:in `index'
```
- - - - - - - - - - - - - - - - - - - - - - 
```
Environment:
  Redmine version                2.6.6.stable.14445
  Ruby version                   2.1.3-p242 (2014-09-19) [x86_64-linux]
  Rails version                  3.2.22
  Environment                    production
  Database adapter               Mysql2
```
```
From https://github.com/danmunn/redmine_dmsf
 * branch            master     -> FETCH_HEAD
   1b22655..fa07cd7  master     -> origin/master
Updating 1b22655..fa07cd7
```

**Comment by tjaeger** [comment]
![2015-07-17_16-42-59](https://cloud.githubusercontent.com/assets/5296371/8749673/778ca36a-2ca3-11e5-8b7a-d5aeee8f49e4.png)


![2015-07-17_16-43-40](https://cloud.githubusercontent.com/assets/5296371/8749678/7d914a5e-2ca3-11e5-81bb-a5bc76b69e66.png)


![2015-07-17_16-43-20](https://cloud.githubusercontent.com/assets/5296371/8749687/853a6aba-2ca3-11e5-9444-90a8b5684596.png)

**Comment by picman** [comment]
Please test.

**Comment by tjaeger** [comment]
Thanks! Just checked out 1.5.2d and gave it a try - looks to me like the same behavior actually. I verified the code in /models/dmsf_file.rb to make sure checkout worked. So code is changed but i get the same error.
A bit of more test showed that i actually also get an error when i am within a certain project and use the "top bar" search field.
```
$ git status
HEAD detached at v1.5.2d
```
![2015-07-20_10-48-29](https://cloud.githubusercontent.com/assets/5296371/8772535/6b0d20fc-2ecd-11e5-97cc-131cfd514135.png)
![2015-07-20_10-51-18](https://cloud.githubusercontent.com/assets/5296371/8772539/7052b586-2ecd-11e5-984a-f284c542d25a.png)

**Comment by picman** [comment]
The problem related change was:
```ruby
- dmsf_file.event_description = dochash['sample'].force_encoding('UTF-8') if dochash['sample']
+ dmsf_file.description = dochash['sample'].force_encoding('UTF-8') if dochash['sample']
```
so, the calling event_description= has been removed.
Do you still see the following error in the log?
```ruby
NoMethodError (undefined method `event_description=' for #<DmsfFile:0x007faf2c62d828>):
```

**Comment by picman** [comment]
How about upgrading Rails to >= 3?

**Comment by tjaeger** [comment]
It's method "search" - so my description was too unprecise on the recent test, sorry for that.

```
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"✓", "q"=>"Xilinx", "scope"=>"", "all_words"=>"1", "titles_only"=>"", "issues"=>"1", "changesets"=>"1", "wiki_pages"=>"1", "dmsf_files"=>"1", "dmsf_folders"=>"1", "commit"=>"Submit", "id"=>"fpga-transition-project"}
  Current user: tjaeger (id=8)
Completed 500 Internal Server Error in 16.0ms

NoMethodError (undefined method `search' for #<Class:0x007f5bb0796950>):
  app/controllers/search_controller.rb:74:in `block in index'
  app/controllers/search_controller.rb:73:in `each'
  app/controllers/search_controller.rb:73:in `index'
```

**Comment by picman** [comment]
Which Redmine version do you use?

**Comment by tjaeger** [comment]
I upgraded to 2.6.3 -> 2.6.6.stable.14426 (along with DMSF 1.5.1->1.5.2).
```
Rails 3.2.22
ruby 2.1.4p265
```

**Comment by picman** [comment]
Please try it again with the master branch.

**Comment by tjaeger** [comment]
Did this earlier already.
```
$ sudo git status
On branch master
Your branch is up-to-date with 'origin/master'.
/plugins/redmine_dmsf$ git show
commit 3a1f88ec53340f3e5e4e98ab19063f1210ce985b
```
and  got (in logfile) :
``` NoMethodError (undefined method `search' for #<Class:0x00000003a8e528>): ```

**Comment by picman** [comment]
Can you try to check one module only while searching in order to find which module causes the problem?

**Comment by tjaeger** [comment]
with "module" you mean "plugin" ?

**Comment by picman** [comment]
No, I mean to check _Documents_ only and to apply a search and then to check _Folders_ only and to apply a search.

**Comment by tjaeger** [comment]
With "Documents only" i get the Error, with "Folders only" it works.
But: While errormsg before your fix listed DMSF, the logentry now is
```NoMethodError (undefined method `search' for #<Class:0x00000004a54d68>):```

I need to investigate first now if this has to do with DMSF or actually not, as the reference isn't clear.

**Comment by tjaeger** [comment]
i quickly deinstalled a suspect plugin (improved search box). The search still behaves incorrect now (as documented before) - but the module refers to:
```
NoMethodError (undefined method `name' for "DmsfFile":ActiveModel::Name):
  app/controllers/search_controller.rb:74:in `block in index'
  app/controllers/search_controller.rb:73:in `each'
  app/controllers/search_controller.rb:73:in `index'
```

**Comment by tjaeger** [comment]
not sure if this gives another clue:
Directly (and only once) after restarting httpd i see:
```
NoMethodError (undefined method `name' for "DmsfFile":ActiveModel::Name):
  app/controllers/search_controller.rb:74:in `block in index'
  app/controllers/search_controller.rb:73:in `each'
  app/controllers/search_controller.rb:73:in `index'
```
than the following errors will be:
```
NoMethodError (undefined method `search' for #<Class:0x000000032935a8>):
  app/controllers/search_controller.rb:74:in `block in index'
  app/controllers/search_controller.rb:73:in `each'
  app/controllers/search_controller.rb:73:in `index'
```
But overall effect is as documented before.

**Comment by picman** [comment]
I've replace model_name.name with model_name.to_s. That should solve the first error. But the second one really  doesn't seem to be related to DMSF:

```ruby
#<Class:0x000000032935a8>
```

**Comment by tjaeger** [comment]
Thank you so much really for your support here. I just upgraded: I now experience the following error only - Basically whenever i search and includes the "Documents" Module.
I tried various combinations, but when there is a http/500 i can see below error msg.
I tried my "original Installation" (which is on standard 1.5.2) - there i also only see the below message.
One thing i noticed: As (on original - without your recent fixes) i get this error only for files which are indexed it seems. If i search for a Word which is not indexed than i receive this error. This is just a quick observation though..

```
NoMethodError (undefined method `description=' for #<DmsfFile:0x007f22b07f4f20>):
  app/controllers/search_controller.rb:74:in `block in index'
  app/controllers/search_controller.rb:73:in `each'
  app/controllers/search_controller.rb:73:in `index'
```

**Comment by tjaeger** [comment]
when i delete the INDEX Files in dmsf_index than the Search works (ie results in nor error). As soon as i regenerate the Indexfiles and so the search again it results in http:500 as reported.

**Comment by tjaeger** [comment]
i quickly downgraded 1.5.2 -> 1.5.2 and there it works. upgraded to 1.5.2 (master) again and i get the error as reported.

**Comment by picman** [comment]
This should fix your problem.

**Comment by picman** [comment]
_"i quickly downgraded 1.5.2 -> 1.5.2 and there it works. upgraded to 1.5.2 (master) again and i get the error as reported."_

Just

```
pull origin master
```

**Comment by tjaeger** [comment]
I checked when this was introduced:
No Error:  266676d9a9ec0d60a74d922e28f34094f1297da9
Error:  48d83d571f400045874ce93a979deb4715e8a242 (24. Apr)

**Comment by tjaeger** [comment]
quick test showed your recent change fixed it apparantly... will do some more tests ASAP. THANKS ALREADY !! Much appreciated.
