### ISSUE TITLE
File uploads failing after redmine upgrade

### ISSUE THREAD

**Issue by mholliman** [danmunn/redmine_dmsf#412]
I just upgraded from redmine 1.4 to 3.0, and am getting an error when trying to upload files in DMSF.  The host is running Debian Jessie, and Redmine was installed through aptitude from a standard debian mirror.  

Versions:
Apache 2.4
Rails 4.1.12
Ruby 2.1.5
Redmine 3.0
DMSF 1.5.2c

For the upgrade, I installed everything fresh and then followed the Redmine upgrade instructions (http://www.redmine.org/projects/redmine/wiki/RedmineUpgrade).  I then followed the upgrade instructions for DMSF (https://github.com/danmunn/redmine_dmsf).  

The debian package didn't create some of the necessary folders, so I manually created ~/redmine/plugins and dropped the redmine_dmsf folder in there.  I also then had to manually create ~public/plugin_assets and a symlink named redmine_dmsf that points to ~plugins/redmine_dmsf/assets

The DMSF interface shows correctly, but after dragging a file into the upload box and clicking "Start Upload" I see the message below in my apache logs:

App 15020 stderr: Started POST "/projects/redmine-admin/dmsf/upload/files?folder_id=146" for 195.xxx.xxx.xxx at 2015-07-22 12:20:02 +0100
App 15020 stderr: Processing by DmsfUploadController#upload_files as HTML
App 15020 stderr:   Parameters: {"utf8"=>"â", "authenticity_token"=>"x=", "x_count"=>"0", "uploaded"=>{"1"=>{"disk_filename"=>"150722122002_UC_1_Updated_Walkthrough.pptx", "content_type"=>"application/vnd.openxmlformats-officedocument.presentationml.presentation", "original_filename"=>"UC 1 Updated Walkthrough.pptx"}}, "folder_id"=>"146", "id"=>"redmine-admin"}
App 15020 stderr:   Current user: msh (id=x)
App 15020 stderr: Completed 500 Internal Server Error in 12ms (ActiveRecord: 0.9ms)
App 15020 stderr: 
App 15020 stderr: TypeError (Cannot visit ActiveModel::Name):
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/visitor.rb:28:in `rescue in visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/visitor.rb:22:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:11:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:62:in `binary'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/visitor.rb:22:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:11:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:56:in `block in nary'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:56:in `each'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:56:in `nary'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/visitor.rb:22:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:11:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:162:in `block in visit_Array'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:162:in `each'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:162:in `visit_Array'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/visitor.rb:22:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:11:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:139:in `visit_Arel_Nodes_SelectCore'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/visitor.rb:22:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:11:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:162:in `block in visit_Array'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:162:in `each'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:162:in `visit_Array'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/visitor.rb:22:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:11:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:146:in `visit_Arel_Nodes_SelectStatement'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/visitor.rb:22:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/depth_first.rb:11:in `visit'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/visitors/visitor.rb:5:in `accept'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/arel/nodes/node.rb:52:in `each'
App 15020 stderr:   activerecord (4.1.12) lib/active_record/relation/query_methods.rb:870:in `grep'
App 15020 stderr:   activerecord (4.1.12) lib/active_record/relation/query_methods.rb:870:in `build_arel'
App 15020 stderr:   activerecord (4.1.12) lib/active_record/relation/query_methods.rb:842:in `arel'
App 15020 stderr:   activerecord (4.1.12) lib/active_record/relation.rb:611:in `exec_queries'
App 15020 stderr:   activerecord (4.1.12) lib/active_record/relation.rb:493:in `load'
App 15020 stderr:   activerecord (4.1.12) lib/active_record/relation.rb:238:in `to_a'
App 15020 stderr:   activerecord (4.1.12) lib/active_record/relation/delegation.rb:46:in `each'
App 15020 stderr:   plugins/redmine_dmsf/app/models/dmsf_link.rb:91:in `find_link_by_file_name'
App 15020 stderr:   plugins/redmine_dmsf/app/models/dmsf_upload.rb:59:in `initialize'
App 15020 stderr:   plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:49:in `new'
App 15020 stderr:   plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:49:in `block in upload_files'
App 15020 stderr:   plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:48:in `each_value'
App 15020 stderr:   plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:48:in `upload_files'
App 15020 stderr:   actionpack (4.1.12) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
App 15020 stderr:   actionpack (4.1.12) lib/abstract_controller/base.rb:189:in `process_action'
App 15020 stderr:   actionpack (4.1.12) lib/action_controller/metal/rendering.rb:10:in `process_action'
App 15020 stderr:   actionpack (4.1.12) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/callbacks.rb:113:in `call'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/callbacks.rb:113:in `call'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/callbacks.rb:502:in `call'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/callbacks.rb:502:in `call'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/callbacks.rb:86:in `run_callbacks'
App 15020 stderr:   actionpack (4.1.12) lib/abstract_controller/callbacks.rb:19:in `process_action'
App 15020 stderr:   actionpack 
App 15020 stderr: (4.1.12) lib/action_controller/metal/rescue.rb:29:in `process_action'
App 15020 stderr:   actionpack (4.1.12) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/notifications.rb:159:in `block in instrument'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/notifications.rb:159:in `instrument'
App 15020 stderr:   actionpack (4.1.12) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
App 15020 stderr:   actionpack (4.1.12) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
App 15020 stderr:   activerecord (4.1.12) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
App 15020 stderr:   actionpack (4.1.12) lib/abstract_controller/base.rb:136:in `process'
App 15020 stderr:   actionview (4.1.12) lib/action_view/rendering.rb:30:in `process'
App 15020 stderr:   actionpack (4.1.12) lib/action_controller/metal.rb:196:in `dispatch'
App 15020 stderr:   actionpack (4.1.12) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
App 15020 stderr:   actionpack (4.1.12) lib/action_controller/metal.rb:232:in `block in action'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/routing/route_set.rb:82:in `call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/routing/route_set.rb:50:in `call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/journey/router.rb:73:in `block in call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/journey/router.rb:59:in `each'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/journey/router.rb:59:in `call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/routing/route_set.rb:692:in `call'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/rack/openid.rb:98:in `call'
App 15020 stderr:   rack (1.5.5) lib/rack/etag.rb:23:in `call'
App 15020 stderr:   rack (1.5.5) lib/rack/conditionalget.rb:35:in `call'
App 15020 stderr:   rack (1.5.5) lib/rack/head.rb:11:in `call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
App 15020 stderr:   plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/middleware/flash.rb:254:in `call'
App 15020 stderr:   rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
App 15020 stderr:   rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/middleware/cookies.rb:562:in `call'
App 15020 stderr:   activerecord (4.1.12) lib/active_record/query_cache.rb:36:in `call'
App 15020 stderr:   activerecord (4.1.12) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/callbacks.rb:82:in `run_callbacks'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
App 15020 stderr:   railties (4.1.12) lib/rails/rack/logger.rb:38:in `call_app'
App 15020 stderr:   railties (4.1.12) lib/rails/rack/logger.rb:20:in `block in call'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/tagged_logging.rb:68:in `block in tagged'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/tagged_logging.rb:26:in `tagged'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/tagged_logging.rb:68:in `tagged'
App 15020 stderr:   railties (4.1.12) lib/rails/rack/logger.rb:20:in `call'
App 15020 stderr:   request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/middleware/request_id.rb:21:in `call'
App 15020 stderr:   rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
App 15020 stderr:   rack (1.5.5) lib/rack/runtime.rb:17:in `call'
App 15020 stderr:   activesupport (4.1.12) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
App 15020 stderr:   actionpack (4.1.12) lib/action_dispatch/middleware/static.rb:84:in `call'
App 15020 stderr:   rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
App 15020 stderr:   railties (4.1.12) lib/rails/engine.rb:514:in `call'
App 15020 stderr:   railties (4.1.12) lib/rails/application.rb:144:in `call'
App 15020 stderr:   railties (4.1.12) lib/rails/railtie.rb:194:in `public_send'
App 15020 stderr:   railties (4.1.12) lib/rails/railtie.rb:194:in `method_missing'
App 15020 stderr:   /usr/lib/ruby/vendor_r
App 15020 stderr: uby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
App 15020 stderr:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
App 15020 stderr: 
App 15020 stderr:

**Comment by mholliman** [comment]
Also, it appears that the directory structure has changed from the previous DMSF version.  After running the rake command for upgrading the database I see individual folders for each project under ~redmine/project/files/dmsf.  But in the old version of DMSF the files were all stored in a single directory.  Is there a script for moving the existing files into the new directory structure, or is this something you'd like to see contributed to the project/documentation?

**Comment by picman** [comment]
DMSF 1.5.1 is not compatible with Redmine 3. Please upgrade to DMSF 1.5.2.

**Comment by picman** [comment]
Yes, documents are now saved in folders according to their parent projects. You can leave your old files where they are. Correct file paths are stored in the database.
There is no rake task to migrate old DMSF documents.

**Comment by mholliman** [comment]
I'm running DMSF 1.5.2c

**Comment by picman** [comment]
No feedback for more than one month => closed.
If the problem persist, please reopen it.
