### ISSUE TITLE
No route matches

### ISSUE THREAD

**Issue by hmdanman** [danmunn/redmine_dmsf#425]
hi,
Environment:
  Redmine version                2.6.6.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.22
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Mercurial                      2.2.2
  Bazaar                         2.6.0
  Git                            1.7.10.4
  Filesystem                     
Redmine plugins:
  redmine_checklists             3.1.1
  redmine_contacts               3.4.4
  redmine_contacts_helpdesk      2.3.0
  redmine_contacts_invoices      3.2.2
  redmine_dmsf                   1.5.2
  redmine_tags                   2.1.0

i've downloaded the latest version and i get this error message

ActionController::RoutingError (No route matches [GET] "/projects/bso-intern-wiki/dmsf/webdav"):
  actionpack (3.2.22) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.22) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.22) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.22) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.22) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.22) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.22) lib/rails/engine.rb:484:in `call'
  railties (3.2.22) lib/rails/application.rb:231:in `call'
  railties (3.2.22) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.20) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  passenger (4.0.20) lib/phusion_passenger/request_handler/thread_handler.rb:140:in `accept_and_process_next_request'
  passenger (4.0.20) lib/phusion_passenger/request_handler/thread_handler.rb:108:in `main_loop'
  passenger (4.0.20) lib/phusion_passenger/request_handler.rb:441:in `block (3 levels) in start_threads'

**Comment by picman** [comment]
From your description is not clear after which action you got this error but a correct path to DMSF WebDAV should have the following format:
```
https://your-redmine.com/dmsf/webdav/your-project-identifier
```
so
```
/dmsf/webdav/bso-intern-wiki
```
instead of
```
/projects/bso-intern-wiki/dmsf/webdav
```

**Comment by hmdanman** [comment]
That’s it!

thank you!



Von: Karel Picman [mailto:notifications@github.com]
Gesendet: Dienstag, 28. Juli 2015 11:48
An: danmunn/redmine_dmsf <redmine_dmsf@noreply.github.com>
Cc: Wagner Daniel <dwagner@bso.at>
Betreff: Re: [redmine_dmsf] No route matches (#425)


From your description is not clear after which action you got this error but a correct path to DMSF WebDAV should have the following format:

https://your-redmine.com/dmsf/webdav/your-project-identifier

so

/dmsf/webdav/bso-intern-wiki

instead of

/projects/bso-intern-wiki/dmsf/webdav
