### ISSUE TITLE
dmsf problem. can not rewrite files. version management not function

### ISSUE THREAD

**Issue by wednowsxp** [danmunn/redmine_dmsf#429]
Hello Pickman, 
thank you very much for providing us such wonderbar plugin to fufill our need. 
im not a programmer, im just a projectmanager of other business area.
i know only some command of linux. i can only install redmine and plugin accoring to tutorials..
what i want:
dmsf: upload files and download files  direkt open a file such as txt file, edit and save it back via webdav.  i do not need version management function. if its possible, i want deaktive filelock and version managment function. i m not a informatiker i just want to edit the files myself and leting other mates to download them. 
Installation phase: i install all using root , on a linode vps (centOS 6.5). have no problem except without xapian installed. 
wget https://bitnami.com/redirect/to/65503/bitnami-rubystack-2.0.0-29-linux-x64-installer.run
wget https://bitnami.com/redirect/to/66086/bitnami-redmine-2.6.6-0-module-linux-x64-installer.run
chmod 755  *.run
./bitnami-rubystack-2.0.0-29-linux-x64-installer.run
./bitnami-redmine-2.6.6-0-module-linux-x64-installer.run
then i go using rubyconsole to install dmsf:

git clone https://github.com/danmunn/redmine_dmsf.git
chown daemon:daemon -R ....../htdoc/plugin/redmine_dmsf
yum install gcc (for nokogiri)
bundle config build.nokogiri --use-system-libraries
bundle --without=xapian
bundle install --no-deployment
rake redmine:plugins:migrate RAILS_ENV=production

after that i login as admin, go Administration plugin dmsf, and aktive the read/write of webdav. 
then i edit role to enable manager all the right to dmsf (check all)
then i creat a project with dmsf mould and user admin with manager role. 
in WebUI i can create folder, upload download files. all ok. 
then i connect the webdav. i can connect it without anyproblem.
i upload a txt file, and open it . but if i edit something, i can not save it. not permitted to upload .
the version are same each files: 0.1 0.1 0.1 0.1....
i go webui and found many files like new file-34210d92-d9d1-41d3-be14-548192cfa012 . 
i even chown daemon:daemon -R ..../redmein this whold folder. but same result. 

im almost crazy about that . i tried centos , ubuntu, tried redmine 3.03 and 2.66. i get same result...
can you please help this noob me?

PS: when i install gems (bundle install) iget warning about using root to install has risk. but i do not know how to install with out root... because if i sudo another acc. i get in ruby enviorment # symble too. (is that root ?)

thank you very much picman. 
![snap1](https://cloud.githubusercontent.com/assets/13603700/9044754/fbd64210-3a1e-11e5-9c78-b9a8e5dbf261.jpg)

**Comment by wednowsxp** [comment]
feed back 1.53 about this problem. 
Picman, thank you very much for so fast update!
i have tried this new version today, hier is my feedback
using administrator account, set up plugin to write&read,  Physical file delete: yes. edit roles with check all. 
1. connect webdav using windows 7. O.K
2. create TxT File and edit using windows Explorer .  function wunderbar! in WebUI- listed O.K.
3. copy files in webdav O.K.  in WebUI listed O.K.
4. copy pdf files and using acrobat to edit them then save. without any problem!
5. copy ms excel, ms word /create excel or word. edit them-- save not function. file can not be saved.  Im using office 2013. 
6. /htdoc/files/dmsf/ many files, even i delete using WebUI. i still find many files. versions.

i have 2 questions:
a. office files can not be saved after edit. ist that Microsoft bug ? or some special lock sequence?
b. can we chose to deaktive the version management function ?  i mean for the space. i have only 40GB on my Vps. 

many thanks Picman.
Stefan

**Comment by picman** [comment]
Add a.)
#185
Add b.)
There is no such option I'm afraid. => Do not upload the same files more than once or create a rake task that regularly delete all file revisions except the last one.
Add c.)
No, >= 3.0 is required
