### ISSUE TITLE
approval process for 3 users "user1 AND user2 AND user3"

### ISSUE THREAD

**Issue by chlipalski** [danmunn/redmine_dmsf#432]
approval process - "user1 AND user2 AND user3"
not working properly, user3 is not possible to accept or reject
correct operation only for 2 users "user1 AND user2"

we need to use the AND operator for 5 users

please help

**Comment by picman** [comment]
Could you provide a little more details what prevents the third user from an approval?

P.S. The related commit above is not directly related to the reported issue.

**Comment by chlipalski** [comment]
Hello
Redmine 3.1.0
DMFS 1.5.3

DMFS for 5 users accept the document:
user1 AND user2 AND user3 AND user4 AND user5

It works great!
thank you, thank you very much :)

**Comment by picman** [comment]
Reopened, why?

**Comment by chlipalski** [comment]
Welcome back,
Environment:
   Redmine version 3.1.1.stable
   Ruby version 1.9.3-p194 (2012-04-20) [x86_64-linux]
   Rails version 4.2.4
   Environment production
   Database Adapter Mysql2

Redmine plugins:
   redmine_dmsf 1.5.4

problems with the process of approval - 1 step
user1 AND user2, AND user3
receive the status of "accepted" only when acceptance will user1 AND user2, user3 is ignored

problems with the process of acceptance
Step 1 - user1 ANDd user2
Step 2 - user3 AND user4
the first step is ignored user2
the system moves to step 2
the second step is ignored user4 and obtain the status of "accepted"

please help

**Comment by picman** [comment]
I've just tried:

*The first problem*

1. step: user1 AND user2 AND user3

1) user1 assigns the approval workflow to the document and starts the workflow => An email notification is sent to all approvers in the first approval step
2) user1 approves
3) user2 approves
4) user3 approves => The documents is approved and an email notification is sent to all approvers

*The second problem*

1. step: user1 AND user2
2. step: user3

1) user1 assigns the approval workflow to the document and starts the workflow => An email notification is sent to all approvers in the first approval step
2) user1 approves
3) user2 approves => An email notification is sent to user1 and user3
4) user3 approves => The documents is approved and an email notification is sent to all approvers

I see no problem there and it behaves exactly as expected. Maybe you've a different settings or there are some strange circumstances.

**Comment by chlipalski** [comment]
Hello
The first problem
step: user1 AND user2 AND user3

in our process goes like this:
1.) user1 assigns the approval workflow to the document and starts the workflow => An email notification is sent to all approvers in the first approval step
2.) user1 approves
2.) user2 approves => The documents is approved and an email notification is sent to all approvers
3.) user3 inability to perform activities because the document has already been approved

if it is OK with you is probably my system is a mistake, I will check again.
 when it will be available version 1.5.5?

Regards

**Comment by picman** [comment]
Can you post the approval log? I mean the screen when you click on the approval workflow status.

**Comment by picman** [comment]
1.5.5 will be released probably by the end of October.

**Comment by chlipalski** [comment]
History:
https://drive.google.com/folderview?id=0B6p4iJzIRSFGRFh3MV9TWHFBY2M&usp=sharing

**Comment by picman** [comment]
That's strange. You've got the approval workflow approved even after the first approval. There should be _Zakceptowany_ on the last line only.
Could you post a screen of the approval workflow configuration (the steps) too?

BTW You can put images directly here by drag&drop.

**Comment by chlipalski** [comment]
![dmfs-workflow](https://cloud.githubusercontent.com/assets/10694870/10219731/a540f2e6-6841-11e5-90a2-1cb5ee9f57ca.JPG)

**Comment by picman** [comment]
It might happened when you have an approval workflow assigned to a document and then you change the approval steps. Couldn't that be your case? Does it happen when you assign the approval workflow to a new document too?

**Comment by chlipalski** [comment]
No, I only work with 1 and 1 document workflow

in a minute send problem with permissions to create a new workflow

**Comment by chlipalski** [comment]
when the document want to assign the work process and at the same time it is a new work process is getting a permissions error
![dmfs-new workflow](https://cloud.githubusercontent.com/assets/10694870/10220032/58f55bf4-6844-11e5-89b0-18aa0d7312e6.JPG)

![dmfs-new workflow-2](https://cloud.githubusercontent.com/assets/10694870/10220037/652560ae-6844-11e5-98fe-2f555d4e7369.JPG)
when the document want to assign the work process and at the same time it is a new work process is getting a permissions error

 DMFS wants to use http://xxxxx.pl/dmsf_workflows/new

 instead http://xxxxx.pl/dmsf_workflows/new?project_id=93

**Comment by chlipalski** [comment]
the user is not an administrator
He has the role of manager

**Comment by picman** [comment]
Yes, that's a bug. Fixed.

**Comment by chlipalski** [comment]
thanks, I am waiting for 1.5.5
 Regards
