### ISSUE TITLE
Cancelling the workflow

### ISSUE THREAD

**Issue by KueWW** [danmunn/redmine_dmsf#435]
Hello everybody,

is it possible to cancel a once started workflow?

Thanks for your help.

**Comment by picman** [comment]
If you add a new revision to the document in the document's details, the workflow will be consequently canceled.
--
Karel Pičman

On 18. 8. 2015, at 15:58, KueWW <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello everybody,

is it possible to cancel a once started workflow?

Thanks for your help.

**Comment by KueWW** [comment]
OK! Thanks.
The problem was that I had to create a new version to cancel the workflow up to date.
That doesn't look fine.
But I saw that it is now possible to set the version manually before checking in.
So that should work.

There's another question: Do the recipients recieve a message after I've canceled the workflow in that way?

**Comment by picman** [comment]
No email notification are sent upon the cancelling.

**Comment by KueWW** [comment]
Thanks a lot!
