### ISSUE TITLE
Can't upload PDF files

### ISSUE THREAD

**Issue by rps-repo** [danmunn/redmine_dmsf#437]
For some reason PDF files will not upload but all other file types will.  After the PDF file is selected for uploaded it is queued as normal but after the Start Upload button is clicked the commit page does not appear as it does with other files.  I have also checked the tmp folder and these files are being uploaded there when they are queued.  I have looked at the redmine log and see no errors there.
Any idea why this is happening?

  Redmine version                3.0.3.stable
  Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.1
 redmine_dmsf                   1.5.3

**Comment by picman** [comment]
No idea. Please post a corresponding part of the production.log.

**Comment by rps-repo** [comment]
Through firebug I have found that jquery is throwing an error when the PDF upload is attempted.
The error is:
SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 3 column 20 of the JSON data
query-1.11.1-ui-1.11.0-ujs-3.1.3.js  Line 4, col 15731

Here is the response JSON:
{"original_filename":"08032015TXVDAPayment.pdf", 
  "content_type":""application/pdf"",
  "disk_filename":"150831101959_08032015TXVDAPayment.pdf"}

It appears that the mime type is double quoted.

**Comment by rps-repo** [comment]
After inspecting the POST data in firebug when uploading a excel file and a PDF I found that the content type of the excel file is not quoted while the content type of the PDF file is.

Excel file:
Content-Disposition: form-data; name="file"; filename="IL1EXCReturnSummary.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

PDF file:
Content-Disposition: form-data; name="file"; filename="RT-2.pdf"
Content-Type: "application/pdf"

**Comment by rps-repo** [comment]
I fixed this by modifying /app/views/dmsf_upload/upload_file.html.erb with:

  "content_type":"<%= (@tempfile.content_type.gsub('"', '')).html_safe %>",

Pull request has been made for this change.
