### ISSUE TITLE
Append File Revision on filename when downloading file

### ISSUE THREAD

**Issue by jeick** [danmunn/redmine_dmsf#44]
A minor feature that would be excellent is if when the file is downloaded, either when clicked on or when packaged in a zip file, the major and minor version numbers would be included in the file name. Ideally they would appear tagged onto the end of the file. For example, a file Test.doc with version 1.4 would become Test_1-4.doc or something similar.

**Comment by picman** [comment]
There's a new option in project settings; tab *DMSF*; where each project member can set a format for file downloading. Eg. '%t_%v' => mydoc_0.1.odt
