### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by fastuser** [danmunn/redmine_dmsf#444]
Hi, Sorry I don't know how to use github or just create a comment here so I just made an issue.
The build status of 1.5.3 says it is failing. Does this mean I cannot install this plugin until it shows success ?
Also it is not entirely clear if it will work with Redmine 3.1.0\
Sorry for the noob questions but I FINALLY have a chance to try out this great sounding plugin.

**Comment by picman** [comment]
Yes, it's compatible with Redmine 3.1.
Post the error messages.

**Comment by picman** [comment]
No feedback => closed.

**Comment by fastuser** [comment]
Thanks, when I get time :)

Russell

**Comment by fastuser** [comment]
I have installed DMSF in a test VM and it worked great !
I then installed it in our production VM and it installed succesfully. I enabled it on a test project but the settings page for the test project is now not available. Any ideas ?

**Comment by fastuser** [comment]
Do I need to create a new issue ?

**Comment by picman** [comment]
No, it' not needed.

Have you checked the production log?

**Comment by fastuser** [comment]
Yes, I didn't notice anything. However after I uninstalled the plugin, Redmine was no longer accessible at all. After checking logs again (apache log I think) there were errors about writing to Gemfile.lock
So I followed this:
_____
If you see error "There was an error while trying to write to Gemfile.lock" then change ownership of Gemfile.lock or change permissions:
$ sudo touch /usr/share/redmine/Gemfile.lock
$ sudo chown www-data:www-data /usr/share/redmine/Gemfile.lock
______
(http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_on_Ubuntu_step_by_step)

Very strange that I had to do this, it was working fine before I installed the plugin.
So after fixing the permissions on Gemfile.lock Redmine was accessible again.

I have taken a full VM copy now so when I get a chance I will try and install it on that first.

**Comment by picman** [comment]
Okay => Closed.
