### ISSUE TITLE
Internal error when creating a new workflow 

### ISSUE THREAD

**Issue by rompic** [danmunn/redmine_dmsf#446]
an internal error is thrown after creating a workflow:

Processing by DmsfWorkflowsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"...HiDjAel3Oo5czkDEulpUKpJw==", "dmsf_workflow"=>{"name"=>"345"}, "dmsf_workflow_id"=>"0", "project_id"=>"141", "commit"=>"Anlegen"}
  Current user: roman (id=13)
PG::UndefinedFunction: ERROR:  operator does not exist: character varying = integer
LINE 1: ...IS NULL OR (project_id = 141 AND id != '345')) AND name = 6)
                                                                   ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT COUNT(*) FROM "dmsf_workflows" WHERE ((project_id IS NULL OR (project_id = 141 AND id != '345')) AND name = 6)
Completed 500 Internal Server Error in 13ms (ActiveRecord: 3.6ms)

ActiveRecord::StatementInvalid (PG::UndefinedFunction: ERROR:  operator does not exist: character varying = integer
LINE 1: ...IS NULL OR (project_id = 141 AND id != '345')) AND name = 6)
                                                                   ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT COUNT(*) FROM "dmsf_workflows" WHERE ((project_id IS NULL OR (project_id = 141 AND id != '345')) AND name = 6)):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

the workflow is created successfully though

seems like name and id are mixed up.
Environment:
  Redmine version                3.1.0.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.10
  redmine_agile                  1.3.11
  redmine_bootstrap_kit          0.2.3
  redmine_checklists             3.1.1
  redmine_ckeditor               1.1.2
  redmine_contacts               4.0.2
  redmine_dmsf                   1.5.3
  redmine_improved_searchbox     0.0.3
  redmine_ldap_sync              2.0.6
  redmine_lightbox2              0.2.2
  redmine_local_avatars          0.2.0
  redmine_logs                   0.1.0
  sidebar_hide                   0.0.7

**Comment by picman** [comment]
Try it now, please.

**Comment by picman** [comment]
No feedback. Probably Okay.

**Comment by rompic** [comment]
thanks for the fast response. I didn't have time to test it yet...
this is not included in 1.5.4 right?

**Comment by picman** [comment]
You must clone the master branch.
