### ISSUE TITLE
Multi upload via zip

### ISSUE THREAD

**Issue by carukc** [danmunn/redmine_dmsf#447]
Hello,

Thanks for the cool plugin.  We are getting alot of use out of it.

I would like to suggest a feature that allows someone to upload multiple files via a zip file.  

Perhaps wedav is the way to make large uploads easier but I cannot seem to get it working.

Chris

**Comment by picman** [comment]
Duplicates #359.

**Comment by carukc** [comment]
Thanks... I should have looked more closely
