### ISSUE TITLE
C:\fakepath\ added to Revision Filename Path

### ISSUE THREAD

**Issue by tjaeger** [danmunn/redmine_dmsf#448]
When creating a Revision with Safari (or as per research should be with most Webkit browsers): If i add a Revision and choose the new Revision File: The "NAME" of the File get a "C:\fakepath\" PREfixed. Consequently it fails if one clicks SAVE - without removing the prepended String.

As per Search that seems to be related to a Problem from HTML being send unclear to the Browser and some Browsers do nonsense.
http://stackoverflow.com/questions/21426232/how-to-remove-c-fakepath-in-webkit-browser-like-chrome-safari-opera

Chrome and Safari behave the same. Firefox doesn't behave like that. 
-1 Fix the HTML code being sent to remove the characters
-2 Use FF
-3 Remove Prepend manually before Saving

**Comment by picman** [comment]
Fixed. Thank you for the bug report.
