### ISSUE TITLE
Rake Error

### ISSUE THREAD

**Issue by codyliou** [danmunn/redmine_dmsf#449]
DL is deprecated, please use Fiddle
Migrating easy_gantt (Easy Gantt plugin)...
Migrating redmine_dmsf (DMSF)...
== 20140314132501 NotificationsOn: migrating ==================================
-- change_column(:projects, :dmsf_notification, :boolean, {:default=>true, :null=>true})
   -> 0.6406s
-- change_column(:dmsf_folders, :notification, :boolean, {:default=>true, :null=>false})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'redmine_test.dmsf_folders' doesn't exist: SHOW FULL FIELDS FROM `dmsf_folders`C:/Sites/redmine-3.1.1/plugins/redmine_dmsf/db/migrate/20140314132501_notifications_on.rb:25:in `up'
C:in `migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:481:in `migrate_plugin'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:453:in `migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:467:in `block in migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:466:in `each'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:466:in `migrate'
C:/Sites/redmine-3.1.1/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'redmine_test.dmsf_folders' doesn't exist: SHOW FULL FIELDS FROM `dmsf_folders`
C:/Sites/redmine-3.1.1/plugins/redmine_dmsf/db/migrate/20140314132501_notifications_on.rb:25:in `up'
C:in `migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:481:in `migrate_plugin'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:453:in `migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:467:in `block in migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:466:in `each'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:466:in `migrate'
C:/Sites/redmine-3.1.1/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Mysql2::Error: Table 'redmine_test.dmsf_folders' doesn't exist
C:/Sites/redmine-3.1.1/plugins/redmine_dmsf/db/migrate/20140314132501_notifications_on.rb:25:in `up'
C:in `migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:481:in `migrate_plugin'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:453:in `migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:467:in `block in migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:466:in `each'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:466:in `migrate'
C:/Sites/redmine-3.1.1/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by picman** [comment]
What do you mean with that:

*DL is deprecated, please use Fiddle
Migrating easy_gantt (Easy Gantt plugin)..*

This's a pretty serious error as dmsf_folders is one of the bas tables of DMSF.

*Mysql2::Error: Table 'redmine_test.dmsf_folders' doesn't exist*

**Comment by codyliou** [comment]
RUN  bundle exec rake redmine:plugins:migrate RAILS_ENV="production"

---

Migrating redmine_dmsf (DMSF)...
== 20140314132501 NotificationsOn: migrating ==================================
-- change_column(:projects, :dmsf_notification, :boolean, {:default=>true, :null=>true})
   -> 0.0689s
-- change_column(:dmsf_folders, :notification, :boolean, {:default=>true, :null=>false})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'redmine_test.dmsf_folders' doesn't exist: SHOW FULL FIELDS FROM `dmsf_folders`C:/Sites/redmine-3.1.1/plugins/redmine_dmsf/db/migrate/20140314132501_notifications_on.rb:25:in `up'
C:in `migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:481:in `migrate_plugin'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:453:in `migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:467:in `block in migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:466:in `each'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:466:in `migrate'
C:/Sites/redmine-3.1.1/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'redmine_test.dmsf_folders' doesn't exist: SHOW FULL FIELDS FROM `dmsf_folders`
C:/Sites/redmine-3.1.1/plugins/redmine_dmsf/db/migrate/20140314132501_notifications_on.rb:25:in `up'
C:in `migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:481:in `migrate_plugin'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:453:in `migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:467:in `block in migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:466:in `each'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:466:in `migrate'
C:/Sites/redmine-3.1.1/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Mysql2::Error: Table 'redmine_test.dmsf_folders' doesn't exist
C:/Sites/redmine-3.1.1/plugins/redmine_dmsf/db/migrate/20140314132501_notifications_on.rb:25:in `up'
C:in `migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:481:in `migrate_plugin'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:453:in `migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:467:in `block in migrate'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:466:in `each'
C:/Sites/redmine-3.1.1/lib/redmine/plugin.rb:466:in `migrate'
C:/Sites/redmine-3.1.1/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by picman** [comment]
Your system seems to be corrupted. I'd suggest to start from scratch.
