### ISSUE TITLE
Anonymous users cannot access documents

### ISSUE THREAD

**Issue by zas0006** [danmunn/redmine_dmsf#450]
I have DMSF 1.5.3 installed and running on my redmine 3.1.0 system, and for the most part is has gone smoothly.

I just tried to send a link for a document to a user that is NOT in redmine (they are support and do not have log in credentials for our redmine server as they utilize a separate ticket tracking system) and they can not access the document. The link they click on is requiring authentication before it will display the doc, and since they aren't a redmine user, they wont have this.

I have the Anonymous role in Redmine configured for view and browse access to DMSF as seen below but it doesn't change anything.

![dmsf issue](https://cloud.githubusercontent.com/assets/10713687/10111219/7a0ca9d0-63a0-11e5-8be0-44d53c4c6d5a.PNG)

Here is some additional info in regards to our setup:
Environment:
  Redmine version                3.1.0.stable
  Ruby version                   2.2.2-p95 (2015-04-13) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2

And I don't know if it matters, but we do utilize LDAP authentication for our system, and we have the 'Authentication Required' option in redmine turned off (specifically to allow restricted 'public' access to our support teams)

Any assistance or suggestions will be appreciated.

Thanks,

Adam

**Comment by zas0006** [comment]
I was just informed that non-member users are having the same issue. I have my non-member role set up the same way as the anonymous users (in regards to DMSF) so the config would be the same. If additional info is required, please let me know.

**Comment by picman** [comment]
Is the project set as public?
