### ISSUE TITLE
Request - Synchronization with PC Server

### ISSUE THREAD

**Issue by soncu** [danmunn/redmine_dmsf#451]
It is working perfect. Is there a way to sync all the files and folders with pre-defined server file systems?
For example: I will set one of my folder in my pc as the root of DMSF. After adding and removing any files to that root(drag and drop, new create etc.), will refrect to in the redmine dmsf space in a project. 
Is this possible? How can we achive such a behavior?
Thanks.

**Comment by picman** [comment]
It's possible using WebDAV. See the documentation how to set up such a folder.

**Comment by soncu** [comment]
In my plugin settings page, webdav is activated and strategy is read-only.
But when I go to project/xyz/dmsf/webdav it gives page not found error.
And there is no file or folder named webdav in /redmine/files/dmsf/.
Documentation about webdav is superficial.
Can you help about this?

**Comment by picman** [comment]
The right URL is https://[your domain]/dmsf/webdav/[project identifier] and not https://[your domain]/[project identifier]/dmsf/webdav.

**Comment by soncu** [comment]
Do I have to get the latest version to take this effect? 
Because https://[my domain]/dmsf/webdav/[project identifier] is not working either.

**Comment by picman** [comment]
No, it has always been working. Post what says the production log.

**Comment by soncu** [comment]
No error on production log or log/apache2/error.log. Only 404 page not found.
What might be the problem?

**Comment by picman** [comment]
Post the exact error line from the Apache error log, please.

**Comment by soncu** [comment]
>[IP address] - - [06/Oct/2015:17:02:26 +0300] "GET /dmsf/webdav/12xyz51 HTTP/1.1" 404 519 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36" in **access.log**

And in the chrome page:
```
Not Found

The requested URL /dmsf/webdav/12xyz51 was not found on this server.

Apache/2.4.7 (Ubuntu) Server at redmine.myhost.com Port 80
```

**Comment by picman** [comment]
That's strange. There is no /dmsf/webdav folder in the webserver off course. The path /dmsf/webdav should be caught by the application and forwarded to the plugin that returns required files.
If there is no record in the production.log, it seems to me that the webserver doesn't forward the request to the application.

I see in my access log:

```
192.168.1.251 - - - [07/Oct/2015:09:46:10 +0200] "-" "OPTIONS /dmsf/webdav/dp/ HTTP/1.1" 401 506 325 "-" "cadaver/0.23.3 neon/0.29.1"
```

and in the production log:

```
I, [2015-10-07T09:46:10.788273 #29865]  INFO -- : Started OPTIONS "/dmsf/webdav/dp/" for 192.168.1.251 at 2015-10-07 09:46:10 +0200
```

**Comment by soncu** [comment]
Dear picman,
I dig down and make webdav run in my local server without redmine as localhost/webdav.
I did similar settings in production server that redmine runs but having difficulties to make it work.

I go to *redmine.[myhost].com/dmsf/webdav* and see following logs:
>production.log:
	Started GET "/dmsf/webdav/12xyz51" for [IP] at 2015-10-08 20:07:48 +0300
>apache2/access.log:
	[IP] - smile [08/Oct/2015:20:09:05 +0300] "GET /dmsf/webdav HTTP/1.1" 401 399 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36"

and chrome shows Authentication Required prompt to enter username and password: 
I enter valid username and password(i set it up previously with *htpasswd*), click OK
same prompt comes again, I reenter but it goes again and again.
*production.log* and *apache2/access.log* messages printed everytime when i click OK.
Server runs *apache2* and *phusionpassenger* services for redmine. My virtual host configurations for apache is as following.
```
ServerName redmine.[myhost].com
DocumentRoot /usr/share/redmine/public
<Directory /usr/share/redmine>
    RailsBaseURI /
    PassengerResolveSymlinksInDocumentRoot on
</Directory>
<Location />
    Options Indexes
    DAV On
    AuthType Basic
    AuthName "webdav"
    AuthUserFile /etc/apache2/webdav.password
    Require valid-user
</Location>
```
What configs breaks the webdav functionality? What is your configuration?
Thanks in advanced.

**Comment by picman** [comment]
For a WebDAV connection to DMSF:
1. No Apache configuration is needed => Remove it.
2. No .htpasswd file is needed => Remove it.
3. For WebDAV authentication use the Redmine credentials.

**Comment by soncu** [comment]
I followed [this](https://www.digitalocean.com/community/tutorials/how-to-configure-webdav-access-with-apache-on-ubuntu-12-04) tutorial about webdav setup and thought these configurations necessary.
After removing apaches configs It is working well on linux and windows. 
*Windows needs more configs (win7:kb907306 update, WebClient service, BasicAuthLevel regedit)*
Thank you.
