### ISSUE TITLE
Internal 500 Error when clicking DMSF Link

### ISSUE THREAD

**Issue by bpmcauliffe** [danmunn/redmine_dmsf#452]
Hello, I am running Redmine 3.0.3 with DMSF 1.5.2, and when i click on the DMSF link I get an Internal Error 500 Page. the log from .../redmine/log/production.log says:

Started GET "/projects/backlog/files" for 173.165.0.57 at 2015-09-30 21:04:05 +0000
Processing by FilesController#index as HTML
  Parameters: {"project_id"=>"backlog"}
  Current user: bmcauliffe (id=66)
  Rendered files/index.html.erb within layouts/base (16.4ms)
Completed 200 OK in 44ms (Views: 30.6ms | ActiveRecord: 3.2ms)
Started GET "/projects/backlog/dmsf" for 173.165.0.57 at 2015-09-30 21:04:08 +0000
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"backlog"}
  Current user: bmcauliffe (id=66)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (1.4ms)
Completed 500 Internal Server Error in 11ms (ActiveRecord: 0.6ms)

ActionView::Template::Error (undefined method `dmsf_notification' for #<Project:0x000000088b1e08>):
    56:       <% end %>
    57:     <% end %>
    58:     <% unless @folder %>
    59:       <% if @project.dmsf_notification %>
    60:        <%= link_to(l(:label_notifications_off),
    61:           notify_deactivate_dmsf_path(:id => @project),
    62:           :title => l(:title_notifications_active_deactivate),
  activemodel (4.2.1) lib/active_model/attribute_methods.rb:433:in `method_missing'
  plugins/redmine_dmsf/app/views/dmsf/show.html.erb:59:in `_plugins_redmine_dmsf_app_views_dmsf_show_html_erb___4316674919313277924_39721500'
  actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:148:in `block (2 levels) in show'
  actionpack (4.2.1) lib/action_controller/metal/mime_responds.rb:215:in `call'
  actionpack (4.2.1) lib/action_controller/metal/mime_responds.rb:215:in `respond_to'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:146:in `show'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  rack (1.6.1) lib/rack/etag.rb:24:in `call'
  rack (1.6.1) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.1) lib/rack/head.rb:13:in `call'
  actionpack-xml_parser (1.0.2) lib/action_dispatch/xml_params_parser.rb:16:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.1) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  railties (4.2.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

**Comment by picman** [comment]
Have you run the plugin migration?
```ruby
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```
Please check your database; the table projects must contain a column dmsf_notification.

**Comment by bpmcauliffe** [comment]
You are right the column is missing in the projects table, what kind of data type should it be?

Thanks for your help!

**Comment by picman** [comment]
mysql> desc projects;
+-------------------+--------------+------+-----+---------+----------------+
| Field             | Type         | Null | Key | Default | Extra          |
+-------------------+--------------+------+-----+---------+----------------+
| id                | int(11)      | NO   | PRI | NULL    | auto_increment |
| name              | varchar(255) | NO   |     |         |                |
| description       | text         | YES  |     | NULL    |                |
| homepage          | varchar(255) | YES  |     |         |                |
| is_public         | tinyint(1)   | NO   |     | 1       |                |
| parent_id         | int(11)      | YES  |     | NULL    |                |
| created_on        | datetime     | YES  |     | NULL    |                |
| updated_on        | datetime     | YES  |     | NULL    |                |
| identifier        | varchar(255) | YES  |     | NULL    |                |
| status            | int(11)      | NO   |     | 1       |                |
| lft               | int(11)      | YES  | MUL | NULL    |                |
| rgt               | int(11)      | YES  | MUL | NULL    |                |
| dmsf_description  | text         | YES  |     | NULL    |                |
| inherit_members   | tinyint(1)   | NO   |     | 0       |                |
| dmsf_notification | tinyint(1)   | YES  |     | 0       |                |
+-------------------+--------------+------+-----+---------+----------------+

**Comment by bpmcauliffe** [comment]
My projects table is missing both the dmsf_description and dmsf_notification columns. are those created when you run the 
bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
command?

**Comment by picman** [comment]
Yes.

**Comment by bpmcauliffe** [comment]
So I uninstalled the plugin, removed the folder. and now when i try reinstalling it I get the following error during the "bundle exec rake" (it looks like there are still entries/tables left in theredmine db and it is not finished the migration):

** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
Rails Error: Unable to access log file. Please ensure that /usr/share/redmine/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /usr/share/redmine/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
** Execute redmine:plugins:migrate
Migrating redmine_dmsf (DMSF)...
Migrating to CreateHierarchy (1)
== 1 CreateHierarchy: migrating ===============================================
-- create_table(:dmsf_folders)
Mysql2::Error: Table 'dmsf_folders' already exists: CREATE TABLE `dmsf_folders` (`id` int(11) auto_increment PRIMARY KEY, `project_id` int(11) NOT NULL, `dmsf_folder_id` int(11), `name` varchar(255) NOT NULL, `description` text, `notification` tinyint(1) DEFAULT 0 NOT NULL, `user_id` int(11) NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'dmsf_folders' already exists: CREATE TABLE `dmsf_folders` (`id` int(11) auto_increment PRIMARY KEY, `project_id` int(11) NOT NULL, `dmsf_folder_id` int(11), `name` varchar(255) NOT NULL, `description` text, `notification` tinyint(1) DEFAULT 0 NOT NULL, `user_id` int(11) NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:208:in `create_table'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:462:in `create_table'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:417:in `method_missing'
/usr/share/redmine/plugins/redmine_dmsf/db/migrate/01_create_hierarchy.rb:21:in `up'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:569:in `up'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/usr/share/redmine/lib/redmine/plugin.rb:474:in `migrate_plugin'
/usr/share/redmine/lib/redmine/plugin.rb:446:in `migrate'
/usr/share/redmine/lib/redmine/plugin.rb:457:in `migrate'
/usr/share/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/lib/ruby/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate

**Comment by bpmcauliffe** [comment]
would it be safe to just alter the projects table and add the dmsf_notifactions and dmsf_description columns?

**Comment by picman** [comment]
I don't know. Hard to say in what state is your installation now. You can't simply un-install the plugin by removing the folder only. If you havn't got any DMSF data in your database, I'd recommend to remove all dmsf_* tables from the database ad than re-run the migration task. In case of an error about an existing column, simple remove it and re-run the migration again. As the first step I'd strongly recommend fixing the Rails error concerning logging.

**Comment by bpmcauliffe** [comment]
AH, i dropped all the dmsf_* tables, reran the rake, followed all of the normal instructions from there and it is working. Going to backup my actual production server and attempt the same thing there. I appreciate you help, thank you very much.
