### ISSUE TITLE
Upload fails due to C:\fakepath\

### ISSUE THREAD

**Issue by wzinet** [danmunn/redmine_dmsf#453]
When I'm adding a modification to a document, I do the following:

Click on the "Edit" associated with the document
Click on the "+" for a new revision
Add comment/version as appropriate
Select a new file using the "Choose file" button
- This populates the "File" with the line: c:\fakepath\<filename>

click on "create"

When I do this I get an error:
Name contains invalid character(s), Name contains invalid character(s)

If I remove the "C:\fakepath\" part from the name, then it works fine.

Version information:
Environment:
  Redmine version                3.1.1.stable.14634
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.5.4

Host: Linux
Client: Mac OS X, Chrome.

**Comment by picman** [comment]
Duplicates #448. Please use the branch 1.5.5-devel or wait for the next relaease.
