### ISSUE TITLE
Clarification on how to find document/revision id.

### ISSUE THREAD

**Issue by wzinet** [danmunn/redmine_dmsf#454]
I would love to be able to link to files, but I really can't find the document/revision id anywhere!

The {{dmsf(9)}} macro works just fine, but I'm never sure which doc/revision it will link to (kind of defeats the purpose)...

Any chance of a screenshot with an arrow to help fools like myself?

**Comment by picman** [comment]
The document id is eg. visible in the bottom of a browser window if you hover your mouse pointer over the document in DMSF document list:

![doc_id](https://cloud.githubusercontent.com/assets/779003/10275171/afdb012c-6b45-11e5-81e0-af77941e42f6.png)

or if you click the document details both document and revision numbers are available in this form:

![rev_id](https://cloud.githubusercontent.com/assets/779003/10275176/b320da96-6b45-11e5-80d2-7fd806dc9ddf.png)

Please see the red ellipses.
