### ISSUE TITLE
Error uploading documents 

### ISSUE THREAD

**Issue by alternative4** [danmunn/redmine_dmsf#455]
Hi. I am running DMSF on redmine with the following Windows 2008R2 configuration:

Environment:
  Redmine version                3.1.1.stable
  Ruby version                   2.1.6-p336 (2015-04-13) [x64-mingw32]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
Redmine plugins:
  redmine_dmsf                   1.5.4

When I try to upload document, which has russian letters in its name (from the document details screen), I get the following error:
![image](https://cloud.githubusercontent.com/assets/10988501/10279540/470f77c0-6b6f-11e5-9769-911649e9af5c.png)

The log says:
Started POST "/dmsf/files/611/revision/create" for 172.0.0.0 at 2015-10-05 14:44:13 +0000
Processing by DmsfFilesController#create_revision as HTML
  Parameters: {"utf8"=>"âœ“", "authenticity_token"=>"vp/7BHf3SQnh3osXhXzrWqsWnr4/HQupUAtw61ec6z4YvDzIXOB3nIO9FLO2g3ylVs08rq3g+h8g==", "dmsf_file_revision"=>{"title"=>"Ð ÐµÐ³Ð»Ð°Ð¼ÐµÐÐ¦Ð", "name"=>"C:\\fakepath\\Ð ÐµÐ³Ð»Ð°Ð¼ÐµÐ½Ñ‚ ÑÐºÑÐ¿.doc", "description"=>"", "comment"=>"Ð¸Ñ‚"}, "version"=>"1", "custom_version_major"=>"2", "custom_version_minor"=>"2", "file_upload"=>#<ActionDispatch::Http::UploadedFile:0x000000178a7d18 @tempfile=#<Tempfile:C:/Windows/Temp/RackMultipart20151005-4952-1esoae0.doc>, @original_filename="Ð ÐµÐ³Ð»Ð°Ð¼ÐµÐ½Ñ‚ ÑÐºÑÐ¿Ð»ÑƒÐ°Ñ‚Ð°Ñ†Ð¸Ð¸ Ð Ð¦Ð.doc", @content_type="application/msword", @headers="Content-Disposition: form-data; name=\"file_upload\"; filename=\"\xD0\xA0\xD0\xB5\xD0\xB3\xD0\xBB\xD0\xB0\xD0\xBC\xD0\xB5\xD0\xBD\xD1\x82 \xD1\x8D\xD0\xBA\xD1\x81\xD0\xBF\.doc\"\r\nContent-Type: application/msword\r\n">, "commit"=>"Create", "id"=>"611"}
  Current user: ka (id=3)
Redirected to http://redmine/dmsf/files/611
Completed 302 Found in 125ms (ActiveRecord: 15.6ms)

When I upload file from drag-and-drop, everything is OK.

**Comment by picman** [comment]
Duplicates #453
