### ISSUE TITLE
Everything is set to DEACTIVATED but still I got notifications

### ISSUE THREAD

**Issue by mettbest** [danmunn/redmine_dmsf#456]
Hi ! I cannot stop the system to send notifications in case of a new upload of a file.
1. DMSF settings option Notifications in the single project is set to DEACTIVATED
2. DMSF plugin settings - File default notifications is set to DEACTIVATED

But still, I get always notifications if I upload a new file:
"UserXX has just actualized documents of ProjectName as follows "

Redmine v2.4.2.stable
DMSF v1.4.9 stable

How to solve this?

**Comment by picman** [comment]
Deactivate notification for the given folder.

![notifications](https://cloud.githubusercontent.com/assets/779003/10430315/c7a34fee-70fe-11e5-9a33-c027affb2176.png)

Or, you must do an upgrade.
