### ISSUE TITLE
Folder name Documents inaccessible

### ISSUE THREAD

**Issue by soncu** [danmunn/redmine_dmsf#457]
In project X, we created a folder named "Documents" from redmine interface and put files in it. There is no problem with this. But when we want to access this folder from the webdav in pc(linux or windows), it gives error as following,
>**Windows**:Z:\x\Documents refers to a location that is unavailable. It could be on a hard drive on this computer, or on a network. Check to make sure that disk is properly inserted, or that you are connected to the Internet or your network, and then try again. It if still cannot be located, the information might have been moved to a different location.

>**Linux**:Unable to find the requested file. Please check the spelling and try again.
Unhandled error message: HTTP Error: Not Found

**Comment by soncu** [comment]
I think found the reason. My colleague named it "Documents " with a trailing space character from the DMSF page. When I deleted that and make name exactly "Documents", it is working without error.
Maybe, you should trim spaces when creating or editing folder names.

**Comment by picman** [comment]
A very good hint. Thank you.
