### ISSUE TITLE
WebDav Windows 

### ISSUE THREAD

**Issue by meron1122** [danmunn/redmine_dmsf#459]
Windows after reboot lose WebDav path(?) I must remount again.
When i remount i can't jump to project folder -error "\\ip\DavWWWRoot(wtf?)\redmine\dmsf\webdav\test is not avalible.
From web works fine.
Is implementation issue?
Ofc i disabled ssl in registry.
On linux all works fine.
On ruby logs nothing special.
If you need windows logs, can you call me where find it?

Btw, thanks for contributing this bundle!

**Comment by picman** [comment]
1. Have you checked the option _Reconnect at logon_?
2. To mount a WebDAV folder use always the right URL in the format of https://your_domain/dmsf/webdav/project_identifier. Don't care about what MS windows displays in the mounted path.

![webdav](https://cloud.githubusercontent.com/assets/779003/10607911/0d823acc-773d-11e5-9821-2bd4a95bafd7.png)

**Comment by meron1122** [comment]
Thanks for response, I might is bad mounting options, I used this tutorial - https://www.onemetric.com.au/documentation/windows/mounting-a-webdav-share-windows-7 .
Now I mount like Windows Share (according from your screen shot).
Permissions work, little files work, but high files upload very fast and stuck near the end.

Log redmine

```
Started GET "/redmine/dmsf/files/5/view" for 192.168.5.84 at 2015-10-20 15:21:44 +0200
Processing by DmsfFilesController#view as HTML
  Parameters: {"id"=>"5"}
  Current user: admin (id=1)
2015-10-20 15:21:44 admin@192.168.5.84/: downloaded dmsf://test/5/6
Sent file /files/redmine-3.1/files/dmsf/p_test/151020152134_5_webDAV.reg (0.6ms)
Completed 200 OK in 116ms (ActiveRecord: 81.7ms)
Started PROPFIND "/redmine/dmsf/webdav/" for 192.168.5.41 at 2015-10-20 15:21:51 +0200
Started PROPFIND "/redmine/dmsf/webdav/" for 192.168.5.41 at 2015-10-20 15:21:51 +0200
Started PROPFIND "/redmine/dmsf/webdav/" for 192.168.5.41 at 2015-10-20 15:21:51 +0200
Started PROPFIND "/redmine/dmsf/webdav/" for 192.168.5.41 at 2015-10-20 15:21:51 +0200
Started PROPFIND "/redmine/dmsf/webdav" for 192.168.5.41 at 2015-10-20 15:22:03 +0200
Started PROPFIND "/redmine/dmsf/webdav/test/pl_windows_7_ultimate_n_with_sp1_x86_dvd_u_677610.iso" for 192.168.5.41 at 2015-10-20 15:22:04 +0200
Started PUT "/redmine/dmsf/webdav/test/pl_windows_7_ultimate_n_with_sp1_x86_dvd_u_677610.iso" for 192.168.5.41 at 2015-10-20 15:22:04 +0200
pl_windows_7_ultimate_n_with_sp1_x86_dvd_u_677610.iso 0b ignored
Started LOCK "/redmine/dmsf/webdav/test/pl_windows_7_ultimate_n_with_sp1_x86_dvd_u_677610.iso" for 192.168.5.41 at 2015-10-20 15:22:04 +0200
Path doesn't exist: /test/pl_windows_7_ultimate_n_with_sp1_x86_dvd_u_677610.iso
Started PROPFIND "/redmine/dmsf/webdav/test" for 192.168.5.41 at 2015-10-20 15:22:05 +0200
Started LOCK "/redmine/dmsf/webdav/test/pl_windows_7_ultimate_n_with_sp1_x86_dvd_u_677610.iso" for 192.168.5.41 at 2015-10-20 15:22:49 +0200
Path doesn't exist: /test/pl_windows_7_ultimate_n_with_sp1_x86_dvd_u_677610.iso
Started HEAD "/redmine/dmsf/webdav/test/pl_windows_7_ultimate_n_with_sp1_x86_dvd_u_677610.iso" for 192.168.5.41 at 2015-10-20 15:23:14 +0200
Started LOCK "/redmine/dmsf/webdav/test/pl_windows_7_ultimate_n_with_sp1_x86_dvd_u_677610.iso" for 192.168.5.41 at 2015-10-20 15:23:29 +0200
Path doesn't exist: /test/pl_windows_7_ultimate_n_with_sp1_x86_dvd_u_677610.iso
```

Log apache
```
[ 2015-10-20 15:23:55.5367 1348/7ffae4d5b780 apache2/Hooks.cpp:732 ]: Unexpected error in mod_passenger: An error occurred while receiving HTTP upload data: The timeout specified has expired (70007)
  Backtrace:
     in 'boost::shared_ptr<Passenger::BufferedUpload> Hooks::receiveRequestBody(request_rec*)' (Hooks.cpp:1190)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:546)
```

Thanks!

**Comment by meron1122** [comment]
@picman I migrate from apache + passenger to nginx+thin, and conclusion is this same:
-Horibbly slow on a lot of small files ( for example 3 thousand text files)
-Upload big file crash at the end, in log nothing special.

**Comment by picman** [comment]
I've just tried a 3GB file:

Nautilus -> Webrick OK
Nautilus -> Apache+Passenger NOK

Then I tried co configure a WebDAV + Apache only, without DMSF and Rails, just a WebDAV shared folder over Apache and it behaves very similar, so it seems to me that this is related to the web server and its configuration and not to DMSF itself.

**Comment by meron1122** [comment]
Webrick can be a production server?

**Comment by picman** [comment]
It wouldn't be the best choice, I think. I use it for development only.
--
Karel Pičman
Senior IT Consultant
IT Application Services
Kontron
Teslova 1 | 301 00 Plzeň | Czech Republic
P: +420 378775485 | M: +420 608136974
karel.picman@kontron.com<mailto:karel.picman@kontron.com>

Website<http://www.kontron.com/> | Blog<http://blog.kontron.com/> | Twitter<https://twitter.com/Kontron> | LinkedIn<https://www.linkedin.com/company/kontron?trk=top_nav_home> | Facebook<https://www.facebook.com/kontron>

KONTRON ECT design s.r.o.
Sídlo společnosti / Registered Office: Teslova 1, 30100 Plzeň, Czech Republic
Rejstříkový soud / Local District Court Plzeň: C 12038
Jednatel / General Manager: Martin Pilař

Otevřením tohoto e-mailu souhlasíte s Kontron podmínkami  pro elektronickou komunikaci<http://www.kontron.com/about-kontron/legal-and-copyright-information>
By opening this email you are agreeing to Kontron’s Electronic Communications Policy<http://www.kontron.com/about-kontron/legal-and-copyright-information>


On Thu, 2015-10-22 at 00:55 -0700, Marcin Golonka wrote:
Webrick can be a production server?

**Comment by meron1122** [comment]
![windows 7](https://cloud.githubusercontent.com/assets/2895090/10660458/7e8a44e2-78a7-11e5-8c06-a76837632579.png)
Most big files.
Webrick log:
```
[2015-10-22 10:12:34] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:10 
	/usr/lib/ruby/2.1.0/webrick/httpserver.rb:80:in `eof?'
	/usr/lib/ruby/2.1.0/webrick/httpserver.rb:80:in `run'
	/usr/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
[2015-10-22 10:17:25] ERROR invalid body size.
```

**Comment by picman** [comment]
It seems to me that the limit size is 2GB. Files of size less that 2GB work; larger not. Nevertheless I've 64b systems on both sites.
Clear upload via WebDAV (without DMSF) behaves the same. So, it's not related to DMSF itself.

Immediately at the beginning of the upload of a file greater then 2GB I get an error message in the Appache log:

<pre>
192.168.1.251 - - - [29/Oct/2015:15:43:49 +0100] "-" "PUT /dmsf/webdav/c1/large_file_3000.img HTTP/1.1" 500 3551 984 "-" "gvfs/1.24.2"
</pre>

I've no idea where the error comes from.
