### ISSUE TITLE
Webdav: Parent-sub Project Folders Seperated

### ISSUE THREAD

**Issue by soncu** [danmunn/redmine_dmsf#460]
Hi,
We use parent and sub project relation very much in our redmine. We also want to use webdav in network mounted drive. But when project is a sub project, their dmsf folders (project_identifier) are placed in the root seperately. For example our project structure is like this:

```
* Project1
  * Project2
     * Project3
  * Project4
* Project5
```

But in webdav folder they are stays like;

```
project1
project2
project3
project4
project5
```

And we want the folder structure to be;

```
project1
  project2
    project3
  project4
project5
```

How can we achive this kind of nested folder structure ?

**Comment by soncu** [comment]
Any solution for this issue?

**Comment by picman** [comment]
It would require changes in the WebDAV module. It's definitely possible, but I've no such plans at the moment, I'm afraid.

**Comment by soncu** [comment]
If I want to do the changes, where would you advice me to begin from? At least guide me about this.
Thank you.

**Comment by picman** [comment]
All WebDAV business is implemented in lib/redmine_dmsf/webdav. If you plan to merge your changes to this project, do that optional from the plugin configuration, please.

**Comment by JL2014** [comment]
+1

**Comment by i-and** [comment]
+1

**Comment by acosonic** [comment]
+1

**Comment by acosonic** [comment]
I don't see subprojects at all, what do I need to do to see them?

**Comment by acosonic** [comment]
Hm, no actually, what I want to achieve is if I have projects like

* Project1
  * Project2
     * Project3
  * Project4
* Project5

and I access
/dmsf/webdav/project2

I want to see all folders of project2 there and Project3 as folder
(recursieveley)...

**Comment by acosonic** [comment]
Where to donate? 🥇
