### ISSUE TITLE
Webdav: Folder Names

### ISSUE THREAD

**Issue by soncu** [danmunn/redmine_dmsf#461]
Hello again,
Dmsf puts folder names as project identifier for _webdav_ functionality. But we need to change them, for example give them any folder name like in _Windows_ or _Linux_ folder names(upper names, including space in names etc.)
Is that possible? What is the workaround for it?

**Comment by soncu** [comment]
Any solution for this issue?

**Comment by picman** [comment]
On of the reason why identifiers have been used instead of the project names was that the identifiers are unique. The second was that identifiers can consist of a limited set of characters and therefore we prevented problems with special characters such as '!', '\', '/',...
An alternative would be to use project names but we'd need to solve these problems first, I think.

**Comment by soncu** [comment]
I have some solution about this actually. For example it ask user to enter valid name if it contains such characters. For instance in our projects, none of them have these chars.  Another workaround is that it tries to create that folder with the project name, if it is not permissible, force the user until valid one.
Also space and upper characters are valid in all OS for file or folder names as I know.

**Comment by i-and** [comment]
+1

**Comment by carlolars** [comment]
I have implemented this feature, optionally enabled in the settings.
It uses the project name, replaces invalid characters with underscore and appends the project id (not identifier) within square brackets to make the string unique (two projects could have the same name).
Here is a screenshot of how it looks now:
![image](https://cloud.githubusercontent.com/assets/13761538/22969261/1dcaa4ba-f36e-11e6-88dc-709cfd0284ae.png)

I have to adjust the invalid character replacing, by laziness I currently use `/\W/` but that replaces all characters that are not _`a-zA-Z0-9_`_, so no dots or spaces.
I will probably change this to having a set of known invalid characters in the code, that way other character sets that I have no knowledge about will hopefully work in most cases.

**Comment by i-and** [comment]
Great decision! How difficult is it to implement a hierarchy of Redmine projects displayed in the WebDav folder structure (go from flat model to hierarchical folders)?

**Comment by carlolars** [comment]
@picman I see that you added this to the 1.6.0 milestone, would you like for me to hold on to it or push it to 1.5.9?

@i-and The hierarchy is a lot more work, this one was relatively simple.

**Comment by picman** [comment]
I'd like to release 1.5.9, so I'd prefer postponing bigger changes to 1.6.0. if it's a small change please go ahead.

**Comment by carlolars** [comment]
I'll make a mr and you can decide.

**Comment by picman** [comment]
Can we close it?

**Comment by carlolars** [comment]
Yes, close it.
