### ISSUE TITLE
Search is not working for me

### ISSUE THREAD

**Issue by ubiq314** [danmunn/redmine_dmsf#463]
I am using Redmine 3.1.1 and DMSF 1.5.5. I created my index directories using "ruby xapian_indexer.rb -f". One of my dmsf files contains the word "sudo", but when I search for it, nothing shows up. I put log statements in dmsf_file.rb and found that it is finding the file (that is, in the block beginning "if matchset", filename is being set to "dmsf/p_initial-test-project/151021130427_9_upgrading_dmsf.txt", which is the name of the file containing the word "sudo"), but is not finding any dmsf_attrs, and is exiting the loop. What are these dmsf_attrs and how do I get them to be there?

My redmine directory is /www/redmine. DMSF files are in /www/redmine/files/dmsf. The index directory is /www/redmine/files/dmsf_index.

The config section of my my edited version of xapian_indexer.rb looks like this:

$redmine_root = '/www/redmine'
$files = 'files'
$scriptindex  = '/usr/bin/scriptindex'
$omindex      = '/usr/bin/omindex'
$dbrootpath   = '/www/redmine/files/dmsf_index'
$stem_langs     = ['english']
$tempdir        = '/tmp'

I commented out the $projects line since I understood that I would get all projects that way.

Thanks very much for your help.

**Comment by picman** [comment]
If your files are located in _/www/redmine/files/dmsf_, the _$files_ must be set to _files/dmsf_ and not just _files_.
Furthermore, I recommend running the indexer with -v to check the command output.

**Comment by ubiq314** [comment]
That was the problem, thank you.
