### ISSUE TITLE
How to get files and/or folders ID

### ISSUE THREAD

**Issue by poinot** [danmunn/redmine_dmsf#464]
Hi, thanks for the plugin.

I wonder how to find out the ID of an entry (that is a folder, a file, a file in a folder...) so that I could use it in the wiki ? Plus, how to get the full list in the wiki (something like {{dmsf(?)}} ) ?

TIA

**Comment by picman** [comment]
1. If you hover your mous pointer above a folder or document, you will see the ID as a part of the URL link at the bottom edge of the browser window.
2. There is no DMSF macro providing a full content of a folder yet.

**Comment by poinot** [comment]
ok got it,

but folder external links I see the url itself, so no way to refer to it using the dmsf macro ?

**Comment by picman** [comment]
DMSF macros do not support DMSF links.
