### ISSUE TITLE
Install using debian 8 (jessie)

### ISSUE THREAD

**Issue by wolfc01** [danmunn/redmine_dmsf#465]
hello,

apt-get install libxapian-ruby1.9.1 xapian-omega libxapian-dev xpdf xpdf-utils antiword unzip\ catdoc libwpd-0.9-9 libwps-0.2-2 gzip unrtf catdvi djview djview3 uuid uuid-dev

Fails, as libxapian-ruby1.9.1. is nonexistent in debian 8 (jessie). I hope it is package  ruby-xapian instead....

Best regards
Carl.

**Comment by wolfc01** [comment]
Hello,

The following command succeeds on debian 8(jessie): 

sudo apt-get install ruby-xapian xapian-omega libxapian-dev xpdf xpdf-utils antiword unzip catdoc libwpd-0.10-10 libwps-0.3-3 gzip unrtf catdvi djview djview3 uuid uuid-dev

I still have to test it using this install command...

Best regards
Carl.

**Comment by picman** [comment]
I've installed neither libxapian-ruby1.9.1 nor ruby-xapian but libxapian22 and it works. I'll have to test it which libraries are really needed.

**Comment by picman** [comment]
The library is not needed to install as it's installed as xapian-ruby gem during bundle install.
