### ISSUE TITLE
DMSF Plugin compatible with 2.5,2.6 version

### ISSUE THREAD

**Issue by Shruthiss** [danmunn/redmine_dmsf#467]
Hi,
I am using redmine 2.5 and redmine 2.6 version .I had installed dmsf plugin before and also uninstalled it.But Now again I want to install it in 2.5 and 2.6 redmine version.But i am not getting Dmsf plugin which is compatible with 2.5 and2.6 version.How do i get dmsf plugin compatible with 2.5 and 2.6 version of redmine.

**Comment by picman** [comment]
As you can see e.g here: http://www.redmine.org/plugins/dmsf Redmine 2.5, 2.6 was supported in the version 1.5.1. Then you can download the corresponding released version here: https://github.com/danmunn/redmine_dmsf/releases.

**Comment by Shruthiss** [comment]
Thanks For the quick reply.
I could install version 1.5.2 in redmine 2.6.2.
Thank you so much
