### ISSUE TITLE
Display contents of text file in Wiki page

### ISSUE THREAD

**Issue by ranzia** [danmunn/redmine_dmsf#468]
Hi DMSF team,

I use your plugin in Redmine to reference text file with revision. It's awesome.

Hovewer, I want display the content of text file (.txt, .ini) in Wiki page. Each content to display is light : <20 lines.

How to display a content of file in <pre></pre> ?

Bye and thank's

**Comment by picman** [comment]
Not implemented yet. I've added it on the feature list.

**Comment by ranzia** [comment]
Thank you a lot

**Comment by ranzia** [comment]
Thank you also.

**Comment by picman** [comment]
Link to the preview of the first 5 lines from a file with id 17:
```{{dmsft(17, 5)}}```

**Comment by ranzia** [comment]
I download the last devel version, this new functionnality is Ok.
Test with : text file
- UNIX + ANSI : OK
- DOS + ANSI : OK
- UNIX + UTF8 : OK
- DOS + UTF8 : OK
Thank you
