### ISSUE TITLE
dmsfd doesn't reuse Wiki syntax in Wiki page

### ISSUE THREAD

**Issue by ranzia** [danmunn/redmine_dmsf#469]
Hi,

I want to display the description of document in a standard Wiki page.
The description of document (ID=5) is multi-lines and contents Wiki syntax, like this : 
========== example =========
<pre>
line 1
line 2
line 3
</pre>
========== EOF ============
But in Wiki page, if a use {{dmsfd(5)}}, then Wiki page display "<pre>line 1 line 2 line 3 </pre>" without decoding "<pre>" and without multi-lines.

Can you a solution, please ?
Bye.

**Comment by picman** [comment]
Fixed. Thank you for the bug report.

**Comment by ranzia** [comment]
I download the last devel version, this bug is out :)
Thank you
