### ISSUE TITLE
sort function

### ISSUE THREAD

**Issue by chlipalski** [danmunn/redmine_dmsf#470]
hello, 
please, sort functions :)

![image](https://cloud.githubusercontent.com/assets/10694870/11180716/4d537708-8c5d-11e5-8df3-8a16677a049a.png)

Regards
Waldemar Chlipalski

**Comment by chlipalski** [comment]
cool thanks

**Comment by picman** [comment]
Do not close the issue. I haven't implemented it yet....

**Comment by chlipalski** [comment]
OK :)

**Comment by picman** [comment]
Could you translate following strings in apostrophes in the right column to Polish?

```json
{
	"sProcessing":   "Processing...",
	"sLengthMenu":   "Show _MENU_ entries",
	"sZeroRecords":  "No matching records found",
	"sInfo":         "Showing _START_ to _END_ of _TOTAL_ entries",
	"sInfoEmpty":    "Showing 0 to 0 of 0 entries",
	"sInfoFiltered": "(filtered from _MAX_ total entries)",
	"sInfoPostFix":  "",
	"sSearch":       "Filter:",
	"sUrl":          "",
	"oPaginate": {
		"sFirst":    "First",
		"sPrevious": "Previous",
		"sNext":     "Next",
		"sLast":     "Last"
	}
}
```

**Comment by chlipalski** [comment]
{
    "sProcessing":   "Przetwarzanie...",
    "sLengthMenu":   "Pokaż MENU",
    "sZeroRecords":  "Nie znaleziono wpisów pasujących do zapytania",
    "sInfo":         "Pokaż wszystkie",
    "sInfoEmpty":    "Brak informacji ",
    "sInfoFiltered": "(przefiltrowano wszystkie wpisy)",
    "sInfoPostFix":  "",
    "sSearch":       "Szukaj/Filtruj:",
    "sUrl":          "",
    "oPaginate": {
        "sFirst":    "Pierwszy",
        "sPrevious": "Poprzedni",
        "sNext":     "Następny",
        "sLast":     "Ostatni"
    }
}

**Comment by picman** [comment]
Thank you for your contribution.
