### ISSUE TITLE
Trouble uploading large file on IE

### ISSUE THREAD

**Issue by ubiq314** [danmunn/redmine_dmsf#472]
Using Redmine 3.1.1, DMSF 1.5.5, IE 9.0. When I attempt to upload a 1G file, I get a 500 error. It works fine with Firefox. Here is the log:

INFO -- :  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.5ms)
INFO -- :  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_files.html.erb within layouts/base (3.6ms)
INFO -- : Completed 500 Internal Server Error in 67ms (ActiveRecord: 2.8ms)
FATAL -- : ActionView::Template::Error (undefined method `locked' for nil:NilClass):
```
    33: <%= form_tag({:action => 'commit_files', :id => @project, :folder_id => @folder},
    34:   :method=>:post) do %>
    35:   <% @uploads.each do |upload| %>
    36:     <% if upload.locked %>
    37:       <%= render(:partial => 'upload_file_locked', :locals => {:upload => upload, :i => i}) %>
    38:     <% else %>
    39:       <%= render(:partial => 'upload_file', :locals => {:upload => upload, :i => i}) %>
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Please let me know if you need additional information. Thank you.

**Comment by picman** [comment]
1. Are you able to upload this file into Files tab?
2. Do you use the Drag&Drop panel or how did you upload the file?

**Comment by ubiq314** [comment]
1. Yes, it works with the Files tab.
2. I attempted to upload the file via the Upload button, after setting the file size to >100 MN. Drag & drop is not available (that is, the words "drag & drop" do not appear on the screen as they do when I use firefox, and dragging a file to that area only results in the file's display). I understood this was a limitation of IE. SHOULD drag & drop be available?

**Comment by picman** [comment]
Related to #480.

**Comment by picman** [comment]
IE9 is quite obsolete browser. Please use FF instead.
