### ISSUE TITLE
WebDAV and versioning

### ISSUE THREAD

**Issue by zlacelle** [danmunn/redmine_dmsf#473]
It seems that, if you drag and drop a new file with the same name over an old file in DMSF WebDAV, it simply replaced the old file (and does not create a new revision).  Is this the case?  Is there any way to add a new revision to a file over WebDAV?

**Comment by picman** [comment]
Could you provide some background to the issue, please? The standard behaviour is that a new revision should be always created. I've just tried it and it works as expected.

**Comment by zlacelle** [comment]
Sorry it took a bit to get back to you on this one.

My terminology was incorrect.  It does in fact create a new revision, but the "Version" number is the exact same.  I suppose this isn't a huge issue, but it would be nice if you could specify a behavior such as "increment minor version number on update."

Anyways, we can mark this issue as resolved since it does create a new revision, but adding functionality to increment version numbers would be a very good thing.

**Comment by picman** [comment]
If the version of the new revision is the same it's a bug. Let's leave it open.

**Comment by logirard** [comment]
The issue is that if you have a file revision 0.1 and drop a new file, it will 0.2, then 0.3... but you are never able to create 1.0 through WebDAV and through DMSF in Redmine, you are not able to change the revision from 0.3 to 1.0 : it's too late.

**Comment by picman** [comment]
Yes, indeed. How would you do that? There is no user interface for a version selection in WebDAV protocol.
If you want to change the version, simply add a new revision via the + button on the document's details and select a required version.
