### ISSUE TITLE
All images cropped to 200x200

### ISSUE THREAD

**Issue by soncu** [danmunn/redmine_dmsf#474]
When uploading image files (png,jpg etc.) it resizes and reduces the quality.
This is not expecting behaviour.
Is there a config setting about "dont touch image when uploading" ?
Thanks.

**Comment by picman** [comment]
Duplicates #441. What version do you use?

**Comment by soncu** [comment]
My DMSF version is `1.5.3`. So I have to update my dmsf plugin to `1.5.4`.
What is the best way doing that?
Thanks.

**Comment by picman** [comment]
If you've installed the plugin using git you can

```bash
git pull origin master
bundle install
chown -R www-data:www-data plugins/redmine_dmsf
bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
service apache2 restart
```

**Comment by soncu** [comment]
Thank you very much, it working now.
