### ISSUE TITLE
Files Kept After Project Deletion

### ISSUE THREAD

**Issue by soncu** [danmunn/redmine_dmsf#477]
I had many file and folders under dmsf. I deleted the project from administration panel but have seen that
all the files are there under `files/dmsf/p_project_identifier`.
What is the reason behind?
Thank you.

**Comment by picman** [comment]
Have you checked *Physical file delete* in the plugin's settings?

**Comment by soncu** [comment]
Sorry, It was unchecked.
Thank you.
