### ISSUE TITLE
xapian indexer

### ISSUE THREAD

**Issue by acosonic** [danmunn/redmine_dmsf#478]
Hi guys, I'm writing a book on Redmine, and writing about your plugin. It's awesome, however I can't get xapian indexer to work on multiple setups, where redmine is running on user's account.

I get this error:
xapian_indexer.rb:441:in `system_or_raise': "/usr/bin/omindex -s english --db /var/tmp/omindex/english /home/ibi/redmine-3.0/files --url / > /dev/null" failed (RuntimeError)
        from xapian_indexer.rb:505:in `block in <main>'
        from xapian_indexer.rb:490:in `each'
        from xapian_indexer.rb:490:in `<main>'

**Comment by picman** [comment]
And if your run the command directly?

```bash
/usr/bin/omindex -s english --db /var/tmp/omindex/english /home/ibi/redmine-3.0/files --url /
```

**Comment by acosonic** [comment]
Exception: DatabaseCreateError: Cannot create directory `/var/tmp/omindex/english' (No such file or directory)

I attempted creation of directory, and it worked...

So probably some better error message will solve similar future issues...

**Comment by acosonic** [comment]
I'm running Redmine as non-root nor sudo user...

**Comment by picman** [comment]
The error messaging will be much better in the upcoming release.
