### ISSUE TITLE
Cannot "edit" workflow

### ISSUE THREAD

**Issue by fastuser** [danmunn/redmine_dmsf#479]
Version 1.5.4
I do not have the "edit workflow" option.
This makes workflow completely useless since there also seems to be a bug in selecting multiple users for a single approval step. The list of users to select is small, so selecting one, then searching for another and selecting does not keep the previously selected users. I need to perhaps edit the step to add extra users for approval for that step.

I have checked Roles and Permissions, Manager role has all approval workflow permissions checked.
Also tried setting my Role as manger only.

![approval workflow](https://cloud.githubusercontent.com/assets/1543002/11463845/c0a6c806-9773-11e5-85ab-2c0d6bc1da89.png)
![roles-permissions](https://cloud.githubusercontent.com/assets/1543002/11463847/c306475c-9773-11e5-8b72-536298fa2a50.png)

**Comment by picman** [comment]
1. If you haven't got *Manage workflow* permissions you're not allowed to do that. I don't understand why it makes the approval workflow useless...
2. A standard Redmine user selection form is used here. So it's a feature not a bug. I you change the search text, all previous selections are cleared.
