### ISSUE TITLE
Feature Request: Linking Issues and DMSF Documents

### ISSUE THREAD

**Issue by jeick** [danmunn/redmine_dmsf#48]
Another great feature that our group would really enjoy is when an issue is created/updated, it would be excellent to be able to reference a specific document in DMSF. Is this even possible?

**Comment by ericLemanissier** [comment]
+1

**Comment by carlolars** [comment]
Hi
I have seen some traces of this while looking through the code and I did some thinking about this some time ago that I would like to share.

My idea was as follows:
Create a new table with issue-document relations to enable having many-to-many relations between documents and issues.

When adding an attachment to an issue the file would be created in the projects DMSF in a default folder, like _/attachments/issue-id/_. So attaching a document named "readme.txt" to issue 1234 would upload the file to _/attachments/1234/readme.txt_. The issue-id and dmsf file-id is added to the relations table to identify the relation between issue and file.
Also when the redmine server is adding issues/notes by parsing incoming e-mails the e-mail attachments must also be added to DMSF.

Issue details view: Related documents are listed in the same way as related issues are, with an "Add" button to add a relation to existing dmsf documents using the same style of search-textbox as when adding issue-relations, and for each document a delete relation.

DMSF documents details view: Related issues are listed, with a delete button for every related issue and an add issue relation button.

The default folder, _/attachments/issue-id/_, is just a simple way to have the attachments available in DMSF. The files can be moved from there and the relation would still be working.

At the time when I thought about this I didn't know how it could be realized, or if it could. And I for sure didn't have the knowledge to do it. But now when I've seen that you started this I dug up my old notes again and, well.

**Comment by picman** [comment]
Thanks for your ideas. I've already started with implementation. What I've done so far:

1. Replaced project_id in the dmsf_files table with container_id and container_type the same way as it's done in attachments.
2. The Redmine functionality of attaching files to different objects is kept.
3. There is a new field in the issue form allowing to attach DMSF documents.
4. Attached documents are visible bellow attached files in the issues.

Next steps:

1. To enable approving documents directly in by issues.
2. To display attached documents in the main DMSF view, in a special system folder probably.

**Comment by carlolars** [comment]
Ok, that sounds good.

Will it be possible to attach files that already exist in DMSF to an issue?

> Replaced project_id in the dmsf_files table with container_id and container_type the same way as it's done in attachments.
So it can be possible to replace the attachments management for other types than issues also, like the wiki?

**Comment by picman** [comment]
I've just completely re-programmed it. dmsf_files.container_id and dmsf_files.container_type have been thrown away. At the moment attached documents are stored in special folders as follows:
.Issue
  {issue ID} - {issue subject}
The special folders have got a different colour and their visibility depends on a flag in the plugin settings.

To attach existing documents to issues is not possible at the moment.

**Comment by picman** [comment]
A few tuning in progress...

**Comment by picman** [comment]
Done.

**Comment by nachommm** [comment]
Hi there, I am using this option, but only works well for admin user, other's users can't download the file or navigate into .issues directory, I got a 403 error and show that I do not have permission to access the file.

**Comment by nachommm** [comment]
Hi there, I am using this option, but only works well for admin user, other's users can't download the file or navigate into .issues directory, I got a 403 error and show that I do not have permission to access the file.

**Comment by picman** [comment]
Show system folders permission granted?

**Comment by nachommm** [comment]
Yes, it granted... I got this error on Redmine Log:

Started GET "/projects/delivery/dmsf?folder_id=1" for 190.210.119.125 at 2017-11-21 11:30:17 -$
Processing by DmsfController#show as HTML
  Parameters: {"folder_id"=>"1", "id"=>"delivery"}
  Current user: xxxuirre (id=8)
Completed 500 Internal Server Error in 230ms (ActiveRecord: 19.7ms)

NoMethodError (undefined method `issue' for #<Class:0x0000000896a908>):
  plugins/redmine_dmsf/app/models/dmsf_folder.rb:114:in `permissions?'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:42:in `permissions'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

The only way to get it working is given Administrator permission on user...

![captura](https://user-images.githubusercontent.com/6294983/33078472-875746ee-ceb1-11e7-91d6-31818270248f.PNG)

**Comment by picman** [comment]
Hm, that's strange. I've tested it and it worked for me. Your plugin source codes are up to date?

**Comment by nachommm** [comment]
My plugin is 1.6.0

Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_checklists             3.1.9
  redmine_contacts               4.1.1
  redmine_dmsf                   1.6.0
  redmine_favorite_projects      2.0.3
  redmine_subtask_list_accordion 1.3.3

**Comment by nachommm** [comment]
Finally I comment line 114 on file dmsf_folder.rb and its works... I don't have much time to review why issue method is not working...

if folder && folder.system
      return false if (!allow_system || !User.current.allowed_to?(:display_syst$
     #  return false unless self.issue && self.issue.visible?(User.current)
    end

**Comment by PeterSpiegler** [comment]
Hi, I upgraded to Redmine 3.4.3 and have the same issue: Error 403 if I want show a document in the issue which was inserted by the DMS document button (over comments) and not appended as file (below comments).  
The reason was: The DMS Modul was not activated in the project configuration. After activation the documents can accessed. 
Although DMS was not activated the DMS document button is active. It is a little confusing, that the user can add documents and files. What is the difference? The issue documents ar not shown on the dmsf page.

**Comment by picman** [comment]
I've just tried it with up to date master branch:

1. Attached a document to an issue.
2. Switched DMS module off.
3. Edited the issue
=>
- Attached document is not visible.
- The control/button to attach documents is not visible

It worked as expected from my point of view. Have you the last master branch code?

**Comment by PeterSpiegler** [comment]
It was the plugin Version 1.5.9. I upgraded to 1.6.  as user redmine with 
sudo git pull origin master
bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
But now the documents are not shown anymore in the issues. DMS is activated in the project.
Also in a new project with DMS module activated  I have no document button in a new issue.
How can I get it back?

**Comment by picman** [comment]
It was the plugin Version 1.5.9. I upgraded to 1.6. as user redmine with
sudo git pull origin master
bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
But now the documents are not shown anymore in the issues. DMS is activated in the project.
Also in a new project with DMS module activated I have no document button in a new issue.
How can I get it back?

**Comment by picman** [comment]
Check the following settings:
1. Administration -> Plugins -> DMSF -> Act as attachable [checked]
2. Project -> Settings -> Act as attachable [Diles & DMS]
3. Administration -> Permissions [File manipulation checked]

**Comment by PeterSpiegler** [comment]
It was unchecked:
1. Administration -> Plugins -> DMSF -> Act as attachable [checked]

Now the Documents button is shown again.

But not the previous uploaded documents in the issues.

The rake task show some problems
rake redmine:dmsf_maintenance dry_run=1 RAILS_ENV="production"
/var/lib/gems/2.1.0/gems/actionpack-4.2.8/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::VCF
/var/lib/gems/2.1.0/gems/actionpack-4.2.8/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of VCF was here

Files...
Documents...
        /opt/redmine/redmine-3.4.3/files/dmsf/2017/03/170315103604_2_CalibrationCertificate_SpectraDAQ-200_72340995.pdf
        /opt/redmine/redmine-3.4.3/files/dmsf/2017/03/170315103604_3_CalibrationCertificate_SpectraDAQ-200_72341001.pdf
        /opt/redmine/redmine-3.4.3/files/dmsf/2017/03/170315103604_4_Rechnung_M3C_2xSpectraDAQ200.pdf
        /opt/redmine/redmine-3.4.3/files/dmsf/2017/04/170411114023_9_Rittal-9791045.pdf
        /opt/redmine/redmine-3.4.3/files/dmsf/2017/05/170517090850_11_Rittal-2433000.pdf
        /opt/redmine/redmine-3.4.3/files/dmsf/2017/05/170517090850_12_Rittal-2584000.pdf
        /opt/redmine/redmine-3.4.3/files/dmsf/2017/06/170609184102_13_AEG.pdf
        /opt/redmine/redmine-3.4.3/files/dmsf/2017/06/170609191641_14_EBO.pdf
        /opt/redmine/redmine-3.4.3/files/dmsf/2017/06/170620135549_23_3.png
        /opt/redmine/redmine-3.4.3/files/dmsf/2017/08/170822152351_24_SnipImage.JPG
        /opt/redmine/redmine-3.4.3/files/dmsf/2017/10/171026162237_25_Anforderungen.txt

0 files havn't got a coresponding revision and can be deleted.
0 Bytes can be released.

0 links can be deleted.
11 corrupted documents.

`
This files are in other folder:
/opt/redmine/redmine-3.4.3/files/dmsf/p_<ProjectIdentifier>

Have I upload the documents again?

**Comment by picman** [comment]
In scope of a migration all documents should have been moved from _dmsf/p_.._. to _dmsf/YYYY/MM/..._ Obviously the migration failed. In case of 11 documents only, I'd suggest moving them manually to the right location as listed above.
This should prevent error 404 not found when clicking a document.
If the documents are missing in the user interface. That's another problem.

**Comment by PeterSpiegler** [comment]
I moved it. The rake task dont show an error.
But only some are shown in the UI. In one issue I have 3 documents, but only the first is shown in the issue and the DMSF page.

**Comment by picman** [comment]
Check the permision _Display system folders_. If granted you should see .Issue folder in DMS and a sub-folders named by issues with attached documents. All attached documents should be stored in the corresponding folder. How many documents do you see there?

**Comment by PeterSpiegler** [comment]
I see the .Issue folder with one document. I show in the database with MySQL Workbench and the  problem is, that in the table dmsf_files the dmsf_folder_id is only set with an value (=2)  for the first entry . I updated also the both other records from NULL to 2 and now all 3 documents are shwon in the issue. Also in DMS Page  Documents/.Issues/IssueName.

**Comment by PeterSpiegler** [comment]
For documents of an issue from an other person I get on http://redmineserver/dmsf/files/9/view
403
You are not authorized to access this page.

But I'm administrator and also Manager in the project.

**Comment by PeterSpiegler** [comment]
I go back to the last version redmine 3.3.2 ( with dmsf 1.5.9). And activated the DMSF module in each project which has attached documents. Then update to 3.4.3 and dmsf 1.6. But the migration show yet some problems:
== 20170422104901 MigrateDocuments: migrating =================================
-- DmsfFileRevisions ID 2: Origin '/opt/redmine/redmine-3.3.2/files/dmsf/p_test/170315103604_2_CalibrationCertificate_SpectraDAQ-200_72340995.pdf' doesn't exist
-- DmsfFileRevisions ID 3: Origin '/opt/redmine/redmine-3.3.2/files/dmsf/p_test/170315103604_3_CalibrationCertificate_SpectraDAQ-200_72341001.pdf' doesn't exist
-- DmsfFileRevisions ID 4: Origin '/opt/redmine/redmine-3.3.2/files/dmsf/p_test/170315103604_4_Rechnung_M3C_2xSpectraDAQ200.pdf' doesn't exist
mv /opt/redmine/redmine-3.3.2/files/dmsf/p_messstelle-bremsenquietschen/170327152706_8_rauheitsspektren.docx /opt/redmine/redmine-3.3.2/files/dmsf/2017/03/170327152706_8_rauheitsspektren.docx
-- DmsfFile ID 9: project = nil
-- DmsfFile ID 11: project = nil
-- DmsfFile ID 12: project = nil
-- DmsfFile ID 9: project = nil
-- DmsfFile ID 13: project = nil
-- DmsfFile ID 14: project = nil
-- DmsfFile ID 23: project = nil
-- DmsfFile ID 24: project = nil
-- DmsfFile ID 25: project = nil
== 20170422104901 MigrateDocuments: migrated (0.0282s) ========================
My Solution: attach the documents again.

**Comment by picman** [comment]
> My Solution: attach the documents again.

 +1
