### ISSUE TITLE
Big files ( > 500mb) uploading problems

### ISSUE THREAD

**Issue by Solvegam** [danmunn/redmine_dmsf#480]
Hi, Karl

I use Redmine 2.6.1 with DMSF plugin 1.4.9 and I faced with the problem of not uploading of files bigger than 500 mb. 
Am I doing something wrong?
Or maybe there was a decision for this issue already?
![screenshot](https://cloud.githubusercontent.com/assets/10787896/11555914/2db28cd4-99ac-11e5-9c67-70c1598c56c8.JPG)

**Comment by picman** [comment]
I'm able to upload 4Gb file in DMSF 1.5.6/Redmine 3.1.

**Comment by ppoektos** [comment]
You need to meet some requirements on redmine server:
- size of /tmp partition has at least 500*2 MB free space
- size of RAM at least 1 GB
- set timeouts and maximum transfer size in your nginx/apache/unicorn, etc.
