### ISSUE TITLE
A "locked" file can be modifies through Webdav

### ISSUE THREAD

**Issue by logirard** [danmunn/redmine_dmsf#485]
In DMSF in Redmine, lock a file with the "Key+" icon ![lock](https://cloud.githubusercontent.com/assets/10209405/11593818/aaf55e24-9aa6-11e5-9eae-8af57a758662.png). Connect through webdav and replace the file with a new version of this file with same file name. The file is replaced. It should not as it is locked (I guess).

**Comment by picman** [comment]
This is possible if you're the document owner or you've got *Force file unlock' permission. Isn't it your case?

**Comment by picman** [comment]
No feedback => closed.
