### ISSUE TITLE
Ambigous name in Redmine search

### ISSUE THREAD

**Issue by acosonic** [danmunn/redmine_dmsf#486]
It's a bit confusing I figured the last Documents is actually searching trough DMSF contents.

http://prntscr.com/9be2jh

**Comment by picman** [comment]
And what should be there? DMSF module consists of Documents and Folders, so there are searchable Documents and Folders.

**Comment by acosonic** [comment]
Just a different name instead of "Documents", so it's not ambiguous, like "DMSF Documents", or just "DMSF"

**Comment by picman** [comment]
If you want to change it, change it locally in your config/locales/*.yml files:
```ruby
label_dmsf_file_plural: Documents
label_dmsf_folder_plural: Folders
```
I will keep Documents and Folders there.

**Comment by acosonic** [comment]
Thanks, very good!

**Comment by picman** [comment]
I've added an option into *init.rb* to remove the original *Documents* from searching options:
```ruby
# Uncomment to remove the original Documents from searching (replaced with DMSF)
# Redmine::Search.available_search_types.delete('documents')
```
