### ISSUE TITLE
Not able to view the url link file, but able to Download

### ISSUE THREAD

**Issue by yinhaoliew** [danmunn/redmine_dmsf#487]
I have a setup where author of the documents will have full access to DMSF on "Doc (master)" project. Once document has been approved, we will create a link to "Doc (read-only)" project.
For user where they only need to access the document (not authoring), we will add them as member in "Doc (read-only)" project but they are not member for "Doc (master)" project. These users are not able to access the file when click on it (url is: http://server/dmsf/files/1/view), but they are able to download it by mark the checkbox and download as zip.

I think the correct behaviour should allow user to access those file where it's linked. But it may be difficult to implement (since it's in different project). Quick workaround for now is to remove the url link (make it just text), such that it does not give false sense of access authorization.

**Comment by picman** [comment]
On the contrary, in my opinion you shouldn't have access to documents from a project which is not accessible for you. Eg, if you remove a member from a project you haven't to be aware of all previously created links. Consequently the user will keep access to the documents nevertheless your intention was to ban it.

**Comment by picman** [comment]
So, I modified the code accordingly. Users without permissions to the target document are not allowed to view, download or email it.

**Comment by yinhaoliew** [comment]
From Redmine project access permission perspective, I am totally agree with you.
But for my use case, I need a way to release a selective set of documents (not all of the documents) to a group of user. I thought I can use "Link to/from" to add selective set of documents from one project to another. It partially served my use case (where user is able to download as zip). But with the modification in f360e1dbfa5b965469e1f30a6263878081b85ac0, user will no longer able to download.

Any good suggestion on how to make my use case works?

**Comment by picman** [comment]
Not a clue.
