### ISSUE TITLE
Author Name

### ISSUE THREAD

**Issue by mprati** [danmunn/redmine_dmsf#489]
When uploading a document DMSF makes an incorrect assumption that the logged in user is the Author of the document. There does not seem to be any way to edit Author.

**Comment by picman** [comment]
That's a feature. The author means the owner in fact similar as in file systems.

**Comment by lccostajr** [comment]
@picman, I also interested in defining the author. Is it possible to do it or maybe have another searchable extra attribute?

**Comment by picman** [comment]
You can certainly use custom fields for such purpose.
