### ISSUE TITLE
LoadError: cannot load such file -- dav4rack

### ISSUE THREAD

**Issue by tarkhil** [danmunn/redmine_dmsf#490]
Hello

redmine@de4ca41146f8:~/redmine$ bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
rake aborted!
LoadError: cannot load such file -- dav4rack

Installed dav4rack as root, no success.

**Comment by picman** [comment]
Run *bundle install* first to install dependencies.

**Comment by picman** [comment]
I've updated the README file accordingly.

**Comment by tarkhil** [comment]
I've tried it already.

redmine@de4ca41146f8:~/redmine$ bundle install
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.3
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.4
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.3
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using loofah 2.0.3
Using rails-html-sanitizer 1.0.2
Using actionview 4.2.4
Using rack 1.6.4
Using rack-test 0.6.3
Using actionpack 4.2.4
Using globalid 0.3.6
Using activejob 4.2.4
Using mime-types 2.6.2
Using mail 2.6.3
Using actionmailer 4.2.4
Using actionpack-action_caching 1.1.1
Using actionpack-xml_parser 1.0.2
Using activemodel 4.2.4
Using arel 6.0.3
Using activerecord 4.2.4
Using coderay 1.1.0
Using dalli 2.7.4
Using htmlentities 4.3.1
Using thor 0.19.1
Using railties 4.2.4
Using jquery-rails 3.1.4
Using kgio 2.10.0
Using mysql2 0.3.20
Using net-ldap 0.3.1
Using pg 0.18.4
Using protected_attributes 1.1.3
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using bundler 1.10.6
Using sprockets 3.4.0
Using sprockets-rails 2.3.3
Using rails 4.2.4
Using raindrops 0.15.0
Using rbpdf 1.18.7
Using redcarpet 3.3.3
Using request_store 1.0.5
Using rmagick 2.15.4
Using unicorn 5.0.1
Updating files in vendor/cache
Bundle complete! 31 Gemfile dependencies, 52 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into ./vendor/bundle.

dav4rack exists, it is in $PATH, but problem is still here

**Comment by tarkhil** [comment]
Any ideas to check?

**Comment by picman** [comment]
Post the output of:
```ruby
gem install dav4rack
gem list | grep dav4rack
```

**Comment by tarkhil** [comment]
root@de4ca41146f8:/home/redmine/redmine# gem install dav4rack
Successfully installed dav4rack-0.3.0
Parsing documentation for dav4rack-0.3.0
Done installing documentation for dav4rack after 0 seconds
1 gem installed
root@de4ca41146f8:/home/redmine/redmine# gem list | grep dav4rack
dav4rack (0.3.0)
root@de4ca41146f8:/home/redmine/redmine# su - redmine
redmine@de4ca41146f8:~$ gem list | grep dav4rack
dav4rack (0.3.0)
redmine@de4ca41146f8:~$ cd redmine/
redmine@de4ca41146f8:~/redmine$ env RAILS_ENV="production" bundle exec rake redmine:plugins:migrate
rake aborted!
LoadError: cannot load such file -- dav4rack

**Comment by tarkhil** [comment]
Any ideas?

**Comment by picman** [comment]
Not a clue.

**Comment by hammady** [comment]
I have the same issue, Ubuntu 16.04, redmine 3.2.1. Any clue?

**Comment by hammady** [comment]
I had to cat the contents of Gemfile from the plugin source to the main redmine Gemfile! This fixed the problem, but it is fragile as further updates of redmine will conflict with Gemfile and i have to merge manually.

**Comment by hammady** [comment]
Forget about my latest comment. The problem appeared to be installing the plugin in the wrong directory!
i had no "plugins" directory but rather "lib/plugins". The latter is an internal directory used by core redmine. If you don't have the former, mkdir it then chown as appropriate and everything should work.

**Comment by lego12239** [comment]
+1 to hammady. The same situation - there is no plugins directory by default, but lib/plugins exist. And this is confuse.

**Comment by picman** [comment]
There is _plugin_ directory by default.
http://www.redmine.org/projects/redmine/repository/show/trunk
