### ISSUE TITLE
Still using original uploaded filename after filename renamed (PDF file)

### ISSUE THREAD

**Issue by yinhaoliew** [danmunn/redmine_dmsf#491]
There are 3 ways to download a file (in my case, it's PDF file).

1. mark the checkbox and download/email
2. right click on the link and select "save link as .."
3. click on the link:
   1. if the file type can be displayed by browser, it will open in new tab/window, when we can save
   2. if the file type is not supported by browser, it will show the save as window (same as no. 2)

For the case of PDF (and using chrome), when click the link, it will open in new tab and display the PDF file content. If click on the save button, it prompt to save the file to disk but the file name is using the original uploaded file name as default name, instead of the new filename.

This is not critical issue, just not consistent with what is expected.

**Comment by picman** [comment]
Very probably solved in scope of #44.
