### ISSUE TITLE
Does the redmine_dmsf support to choose the members of current project when email  ?

### ISSUE THREAD

**Issue by raeuz** [danmunn/redmine_dmsf#492]
Hi,

I want to email the document link to the members of current project, but from the GUI,  i can't find  where i  can search  the  members  to add to recipients input. Does the redmine_dmsf supports?

![screenshot from 2016-01-05 16 00 00](https://cloud.githubusercontent.com/assets/9192796/12110555/5edc8626-b3c8-11e5-8881-b7ad36c63d43.png)

**Comment by picman** [comment]
No, it doesn't, I'm afraid.

**Comment by maniachhz** [comment]
Got it. 
Can you add this feature?

Thanks.

**Comment by vvklymchuk-trade-active** [comment]
I would like this feature too. It's very useful thing

**Comment by picman** [comment]
![add_email](https://user-images.githubusercontent.com/779003/35378052-b11c82b8-01b1-11e8-9463-a432204949b8.png)
