### ISSUE TITLE
Not able to upload any file

### ISSUE THREAD

**Issue by farzans** [danmunn/redmine_dmsf#495]
I installed the latest dmsf plugin yesterday and installed successfully on Bitnami stack 3.1 on Windows without Xapian Search. Now after configuration whenever I tried to upload any files, it never works for me. Am I missing anything.

**Comment by farzans** [comment]
This is what I see on my Chrome console.

Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

**Comment by farzans** [comment]
am using DMSF v 1.5.5

**Comment by picman** [comment]
1. Windows was a bad choice.
2. Open the plugin settings, see the **File storage directory** parameter and check whether the folder exists in the system and it's writeable be the application.

**Comment by farzans** [comment]
Yes, dmsf folder exists - C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/files/dmsf

I am able to manually copy the files to this location.

Please let me know if I need to try anything else.

**Comment by picman** [comment]
Please check the production log (*/log/production.log*) and post the part related to the error

**Comment by farzans** [comment]
Please find the snapshot of the production log attached here. I do not see any error. 

[production-log.txt](https://github.com/danmunn/redmine_dmsf/files/95383/production-log.txt)

Whenever I clicked on upload file, nothing happens and no logs getting updated.

**Comment by picman** [comment]
Something is wrong with your installation or your browser. What do you exactly mean with *Upload*? *Add files* or *Start upload*? Have you tried to switch the option "File size" in the top right corner of the uploading area and therefore to try the Redmine classical upload? Do you have Javascript enabled in your browser? Have you tried a different browser, let's say Firefox?

Your log is full of other errors. Fix them first.

```ruby
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_planning/javascripts/planning_old.js"):
```

**Comment by farzans** [comment]
I tried IE, Chrome and Firefox on my laptop but still not working.

Today I tried on others system running on Chrome and this is working perfectly fine as expected.

**Comment by picman** [comment]
So, can we close it?

**Comment by farzans** [comment]
Yes please. Thanks for your support.
