### ISSUE TITLE
file.image ignore SVG type

### ISSUE THREAD

**Issue by helmerfud** [danmunn/redmine_dmsf#497]
Hello,
first of all, i very thank you for this great plugin.

My question: is it possible to add SVG type file to the macro dmsf_image().

After some search i've found that the file.image function could be modify like this:
app/models/dmsf_file.rb
```
  def image?
    self.last_revision && !!(self.last_revision.disk_filename =~ /\.(bmp|gif|jpg|jpe|jpeg|png|svg)$/i)
  end
```

**Comment by picman** [comment]
SVG type added.
