### ISSUE TITLE
Webdav: Invalid handling of files with '[' or ']' in file name

### ISSUE THREAD

**Issue by morpav** [danmunn/redmine_dmsf#498]
It is possible to upload a file with '[' or ']' in its name (e.g. "Global-Constraints[J.C.Régin].pdf") and everything is fine from web interface. But the file is *not visible* thru webdav.

When I copy a file containing these characters to mounted fs directly, the file is properly uploaded, it is shown in web interface, but "disappears" from the file system.

I would guess it is some name escaping issue, but there is no one in our team using ruby so it is difficult for us to look around ourselves.

Thank you for all your great work.

**Comment by picman** [comment]
Encoding of *[]* added => fixed.
