### ISSUE TITLE
[Feature Request] Add column "type/extension" in folder content view

### ISSUE THREAD

**Issue by JL2014** [danmunn/redmine_dmsf#499]
Hi,

Could you add a column in the folder content view, I have many files in folders, and I would like to click on this "file extension" column (or maybe file type/extension) to sort the list of files by file extension.

I know it's more for Windows user and could understand if this feature will be activated on an option.

Greetings, JL.

**Comment by picman** [comment]
You can select _Extension_ column to be visible in the plugin's settings.
