### ISSUE TITLE
[Enhancement] If a folder or file  is locked, we can't activate or deactivate notifications

### ISSUE THREAD

**Issue by JL2014** [danmunn/redmine_dmsf#501]
Hi,

When A folder or a file is locked by someone, we can't access to the buttons for activate or deactivate notifications. Is it normal ? I think the notifications are not related to the locked feature even if you wan't not to notify modifications during the time the file is locked ?

I have some files that are locked during long time, and would be able to unsuscribe from notifications without to have to wait that the file is unlocked.

Greetings, JL.

**Comment by picman** [comment]
The problem is that notifications are related to all project members not only to the current user. That's the reason why notifications manipulation is not available while the file or folder is locked.

**Comment by picman** [comment]
Nevertheless, I've made a revision of the functionality based on Locked/Unlocked status.
