### ISSUE TITLE
Information about migrating documents

### ISSUE THREAD

**Issue by JL2014** [danmunn/redmine_dmsf#503]
Hi,

Could you add a remark on your wiki page, when use this command :

`rake redmine:dmsf_convert_documents RAILS_ENV="production"`

This command reset the permissions on files, you should, after this command, have to reset the permissions on dmsf folder, for example : 

`chown -R www-data:www-data /redmine/files/dmsf`

Else, you will have an 500 Internal Error, for example :

```
Completed 500 Internal Server Error in 36ms (ActiveRecord: 7.8ms)

Errno::EACCES (Permission denied @ sys_fail2 - (/tmp/xxx, /redmine/files/dmsf/yyy)):
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:217:in `block in commit_files_internal'
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:138:in `each_value'
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:138:in `commit_files_internal'
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:114:in `commit_files'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
```

Greetings, JL.

**Comment by picman** [comment]
It depends on the user account under the rake command is run. Eg.:
```bash
sudo -u www-data rake redmine:dmsf_convert_documents RAILS_ENV="production"
```
would prevent it.

**Comment by picman** [comment]
Nevertheless, I've added such an information to the README file.

Thank you.
