### ISSUE TITLE
Non-fatal MySQL error when migrating documents

### ISSUE THREAD

**Issue by JL2014** [danmunn/redmine_dmsf#504]
Hi,

I have a non-fatal error when migrating documents to DMSF, the error is only on redmine documents when the document doesn't have any file attached: 

```
Processing document: example document
Creating folder: example document
Mysql2::Error: Field 'user_id' doesn't have a default value: INSERT INTO `dmsf_folders` (`project_id`, `title`, `description`, `created_at`, `updated_at`, `notificatio`) VALUES (111, 'example document', '\n', '2016-02-08 16:24:55', '2016-02-08 16:24:55', NULL)
```

I think the case of a drafted redmine document is not converted to a dmsf document. Maybe that should convert the drafted document into a Rich-Text-Format file or a HTML file in DMSF ?

Greetings.

**Comment by picman** [comment]
Fixed.
