### ISSUE TITLE
Handling large files

### ISSUE THREAD

**Issue by xJom** [danmunn/redmine_dmsf#505]
When uploading files larger than 3 Gb, Redmine crashes.

Since I configured the maximum file size to be 6000 Mb, it might not be a problem with DMSF.

The error is "Upload URL might be wrong or doesn't exist."

The only thing visible in the productionlog is status => failed.

**Comment by picman** [comment]
1. Check your Web server and client browser configuration, whether they support such large files.
2. Attach a screen-shot(s) and production log.
3. Working with 3GB files is time consuming. Does the problem occur with a 2GB, 1GB, 500MB file?

**Comment by ppoektos** [comment]
Check that you have enough RAM and free space in /tmp available.
If you upload file with $FileSize then your RAM and free space in /tmp must
be more then $FileSize.
I'm not an expert but this is related how rails works with uploading: it
passes your file through RAM to /tmp/$TempFile and only after that drops
uploaded bytes to defined storage in file system.
So when your system doesn't meet above requirements that rails fails to
complete upload.
I don't know if rails return back some exceptions for this case so
application like DMSF plugin could correctly handle it and inform you with
detailed error.

On Fri, Feb 12, 2016 at 5:44 PM, Karel Picman <notifications@github.com>
wrote:

>
>    1. Check your Web server and client browser configuration, whether
>    they support such large files.
>    2. Attach a screen-shot(s) and production log.
>    3. Working with 3GB files is time consuming. Does the problem occur
>    with a 2GB, 1GB, 500MB file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danmunn/redmine_dmsf/issues/505#issuecomment-183379241>
> .
>



-- 

Best / С наилучшими пожеланиями


*Pavel Potcheptsov*

   LLC EKTOS-Ukraine

System administrator

   1, Academika Proskury

Mobile UA: +38 050 3642391

Home UA: +380 572 931115

   61070 Kharkiv

   www.ektos.com.ua <http://www.ektos.net/>

E-mail:

ppo@ektos.net


  Skype:      potcheptsov.pavel

**Comment by xJom** [comment]
Java is hooking up a lot of memory. The \tmp has 10 Gb free.

The largest file I succeeded with, or even tried with, before this happened is 312 Mb.

The production.log just keeps the response with status=>failed from the call to store the files.

It's probably a memory issue, then. Both:
http://www.jedi.be/blog/2009/04/10/rails-and-large-large-file-uploads-looking-at-the-alternatives/
and
https://github.com/phallstrom/el_finder/issues/19
points in that direction regarding Webrick. I might try to install nginx on the SLES 12.
This issue can be closed.
