### ISSUE TITLE
Upload Not Possible Anymore for Certain File Types

### ISSUE THREAD

**Issue by apusgrz** [danmunn/redmine_dmsf#507]
After an upgrade to Redmine 3.2 with the latest version of the DMSF plugin 1.5.6 the file upload doesn't work anymore ~~except when you're a Redmine administrator~~ for every user.

I suspect a bug within the new plugin ~~/ right management of Redmine~~.

Rights of a normal user which is currently not allowed to upload files:

![screen1](https://cloud.githubusercontent.com/assets/17274070/13079212/65e359ec-d4c3-11e5-8b0c-b063df72034a.png)

Error message when trying to upload a file:

![screen2](https://cloud.githubusercontent.com/assets/17274070/13079213/65e8a5d2-d4c3-11e5-92c6-59851f592bc4.png)

Uploading to this location has worked before with an older version of Redmine (2.5.2) and the plugin (1.4.6). No error log messages can be found.

Please help investigating if this is really a bug or a mis-configuration.

**Comment by picman** [comment]
First of all check the plugin settings. Especially **File storage directory**. Save the settings and check whether your web server user has write permissions to that directory.

**Comment by apusgrz** [comment]
Thanks for your reply.

Here's a screenshot of the plugin settings:

![dmsf_settings](https://cloud.githubusercontent.com/assets/17274070/13079737/f39a3128-d4c5-11e5-9469-8c4de2a04858.png)

We also followed the update procedure as described on Github and again checked the file/folder permissions and paths on Linux for correctness. I suspect no problems here because as said a user with administration rights can upload files normally. 

Downloading and even moving the files between folders works!

**Comment by apusgrz** [comment]
We just found out that the upload is restricted to certain file types! It seems to work with .txt and .docx but not with .pdf or .rpm (Redhat Package Management - very important for us!).

Is the upload really restricted or is this just a mis-configuration?

**Comment by apusgrz** [comment]
After longer investigation we finally found and solved the problem. Another plugin messed up the restrictions on the upload folder so that the upload was actually restricted to a certain file size (not file type!). We removed this buggy plugin and now the upload with DMSF works again.
