### ISSUE TITLE
Email Notification when someone downloads a file

### ISSUE THREAD

**Issue by rajeshkotianp** [danmunn/redmine_dmsf#513]
Hi

Thanks for a great Document Management plugin. its very useful. just have one query.

can we get a email notification to the manager, when some one downloads the file?
due to confidentiality of the document, it would be good if the manager gets notified.

Thanks & Regards
Rajesh Kotian

**Comment by picman** [comment]
Since v3.0.0, you can watch any document.

**Comment by uart-aplex** [comment]
I just test DMSF V3.0.5 with document watched, but when I downloaded the file, it didn't sent email notification for the file been downloaded.

Is it possible to add document been downloaded notifocation with: 
Download Date & Time
Download By User
(Maybe) IP address

**Comment by mmundi72** [comment]
I recommend to have a additional option for this enhancement. In my opinion I am just interested to get notified, when someone change a document. If someone downloaded a file is already available within DMSF - there is just no mail sent. 
Sending a mail for every download causes to send a lot of additional mails. I'm not sure if everyone would be happy with this behavior.

**Comment by picman** [comment]
That is a good point. It will be definitely optional.

**Comment by picman** [comment]
Implemented as follows:

- **My account** has been extended with a new option **Receive download notification**.
- A notification is sent if a file is being downloaded, **Receive download notification** is on and the downloaded file is watched.
