### ISSUE TITLE
Using WebDAV gives HTTP Error 502 - bad Gateway - when creating a directory

### ISSUE THREAD

**Issue by rg-artcom** [danmunn/redmine_dmsf#514]
After Updating to Redmine 3.1.3 and dmsf 1.5.6 I can not create a folder via WebDAV. Tested with OSX 10.10.5 Finder, OSX 10.11.3 Finder and Ubuntu 14.04 as Clients.
In the Web logfile I see:
 PROPFIND /dmsf/webdav/rh-rethinking/Neuer%20Ordner HTTP/1.1" 404

After this it tries to create the folder:
 MKCOL /dmsf/webdav/rh-rethinking/Neuer%20Ordner HTTP/1.1" 502

I don't see more details / errors in the production.log.

**Comment by picman** [comment]
Check your plugin settings. That error _502 - Bad gateway_ might occur if the option **Webdav strategy** is **read-only**.

**Comment by rg-artcom** [comment]
Yes, thx, you are right. It was a plugin setting. Now it working fine.
