### ISSUE TITLE
Internal Error (500)

### ISSUE THREAD

**Issue by EricOVGU** [danmunn/redmine_dmsf#516]
I switch to a project and click on settings and got an internal error. The dmsf plugin seems to be the reason. Here is the error log:

Completed 500 Internal Server Error in 640ms (ActiveRecord: 35.7ms)

ActionView::Template::Error (undefined method `title_format' for #<Member:0x007fd3b67a0648>):
    21: <% member = @project.members.where(:user_id => User.current.id).first %>
    22: <% if member %>
    23:   <% mail_notification = member.dmsf_mail_notification %>
    24:   <% title_format = member.title_format %>
    25: <% end %>
    26:
    27: <%= form_tag(dmsf_user_pref_save_path(@project)) do %>
  plugins/redmine_dmsf/app/views/dmsf_state/_user_pref.html.erb:24:in `_plugins_redmine_dmsf_app_views_dmsf_state__user_pref_html_erb__4435447778902001083_70273638077440'
  app/views/common/_tabs.html.erb:17:in `block in _app_views_common__tabs_html_erb___519792543958703811_20535180'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_app_views_common__tabs_html_erb___519792543958703811_20535180'
  app/helpers/application_helper.rb:324:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___1502917615796179335_28404960'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'

Any idea? Did i something wrong?
Thanks for help!

**Comment by picman** [comment]
Have you run plugin migration? The members table should contain _title_format_ column then.

```ruby
bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
```

**Comment by EricOVGU** [comment]
Hello karel,
thank you for the hint. Sorry for the stupid question. I thought that i ran migration. now it works!
