### ISSUE TITLE
DMSF migration issue

### ISSUE THREAD

**Issue by igorp74** [danmunn/redmine_dmsf#517]
In migration from Redmine 3.0.2. to 3.2.0 (both on ubuntu servers 14) I've had an issue.

I've dumped the mysql database and made the "redmine/files" backup, then restore them on new machine and new redmine installation.

I can see all of my Redmine files and folders, but when I click to see any of them, I've got 

```
404
The page you were trying to access doesn't exist or has been removed.
```

Projects, tasks and wiki contents are cloned fine and I can see them all. But I can't see the DMSF files.

I've tried to re-install the plugin, I've refreshed the database, 

```
rake generate_secret_token
rake db:migrate RAILS_ENV=production
rake redmine:plugins:migrate RAILS_ENV=production
rake tmp:cache:clear
rake tmp:sessions:clear
```

even to turn the url re-writing on & off just to see if that works, but I still cannot see my DMSF files.

Please see if there is some solution to this, or am I missing something.

```
System:
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2

Redmine plugins:
  redmine_dmsf                   1.5.6
```

Thank you!

**Comment by picman** [comment]
Post the corresponding part of the production.log.
--
Karel Pičman

On 16. 3. 2016, at 16:08, igorp74 <notifications@github.com<mailto:notifications@github.com>> wrote:


In migration from Redmine 3.0.2. to 3.2.0 (both on ubuntu servers 14) I've had an issue.

I've dumped the mysql database and made the "redmine/files" backup, then restore them on new machine and new redmne installation.

I can see all of my Redmine files and folders, but when I click to see any of them, I've got

404
The page you were trying to access doesn't exist or has been removed.


Projects, tasks and wiki contents are cloned fine and I can see them all. But I can't see the DMSF files.

I've tried to re-install the plugin, I've refresh the database,

rake generate_secret_token
rake db:migrate RAILS_ENV=production
rake redmine:plugins:migrate RAILS_ENV=production
rake tmp:cache:clear
rake tmp:sessions:clear


even to turn the url re-writing on & off just to see if that works, but I still cannot see my DMSF files.

Please see if there is some solution to this, or am I missing something.

System:
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2

Redmine plugins:
  redmine_dmsf                   1.5.6


Thank you!

**Comment by igorp74** [comment]
```
Started GET "/redmine/projects/project-document-tracking-system/issues/new" for 192.168.2.78 at 2016-03-16 12:18:08 +0100
Processing by IssuesController#new as HTML
  Parameters: {"project_id"=>"project-document-tracking-system"}
  Current user: igorp (id=92)
  Rendered issues/_form_custom_fields.html.erb (7.2ms)
  Rendered issues/_attributes.html.erb (19.6ms)
  Rendered issues/_form.html.erb (27.4ms)
  Rendered attachments/_form.html.erb (2.7ms)
  Rendered issues/new.html.erb within layouts/base (42.2ms)
Completed 200 OK in 136ms (Views: 52.1ms | ActiveRecord: 42.0ms)
Started GET "/redmine/projects/project-document-tracking-system/settings" for 192.168.2.78 at 2016-03-16 12:18:12 +0100
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"project-document-tracking-system"}
  Current user: igorp (id=92)
  Rendered plugins/redmine_dmsf/app/views/hooks/redmine_dmsf/_view_projects_form.html.erb (0.0ms)
  Rendered projects/_form.html.erb (13.6ms)
  Rendered projects/_edit.html.erb (14.4ms)
  Rendered projects/settings/_modules.html.erb (2.9ms)
  Rendered projects/settings/_members.html.erb (40.1ms)
  Rendered projects/settings/_versions.html.erb (1.6ms)
  Rendered projects/settings/_issue_categories.html.erb (0.9ms)
  Rendered projects/settings/_wiki.html.erb (0.9ms)
  Rendered projects/settings/_activities.html.erb (7.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_state/_user_pref.html.erb (1.8ms)
  Rendered common/_tabs.html.erb (73.0ms)
  Rendered projects/settings.html.erb within layouts/base (73.4ms)
Completed 500 Internal Server Error in 114ms (ActiveRecord: 35.5ms)

ActionView::Template::Error (undefined method `title_format' for #<Member:0x007f24f57985d0>):
    21: <% member = @project.members.where(:user_id => User.current.id).first %>
    22: <% if member %>
    23:   <% mail_notification = member.dmsf_mail_notification %>
    24:   <% title_format = member.title_format %>
    25: <% end %>
    26:
    27: <%= form_tag(dmsf_user_pref_save_path(@project)) do %>
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb__2069943915328749087_69898358487720'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb__2069943915328749087_69898358487720'
  app/helpers/application_helper.rb:324:in `render_tabs'
```

```  
  Started GET "/redmine/" for 192.168.2.78 at 2016-03-16 14:20:42 +0100
Processing by WelcomeController#index as HTML
  Current user: igorp (id=92)
  Rendered welcome/index.html.erb within layouts/base (18.4ms)
Completed 200 OK in 335ms (Views: 226.6ms | ActiveRecord: 61.2ms)
Started GET "/redmine/projects" for 192.168.2.78 at 2016-03-16 14:20:45 +0100
Processing by ProjectsController#index as HTML
  Current user: igorp (id=92)
  Rendered projects/index.html.erb within layouts/base (30.4ms)
Completed 200 OK in 176ms (Views: 44.9ms | ActiveRecord: 33.6ms)
Started GET "/redmine/projects/hamag-bicro-2015" for 192.168.2.78 at 2016-03-16 14:20:47 +0100
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"hamag-bicro-2015"}
  Current user: igorp (id=92)
  Rendered plugins/redmine_git_hosting/app/views/projects/_git_urls.html.haml (8.3ms)
  Rendered projects/_members_box.html.erb (1.9ms)
  Rendered projects/_sidebar.html.erb (1.1ms)
  Rendered projects/show.html.erb within layouts/base (54.7ms)
Completed 200 OK in 192ms (Views: 85.5ms | ActiveRecord: 41.7ms)
Started GET "/redmine/projects/hamag-bicro-2015/dmsf" for 192.168.2.78 at 2016-03-16 14:20:50 +0100
```

```
  Processing by DmsfController#show as HTML
  Parameters: {"id"=>"project-document-tracking-system"}
  Current user: igorp (id=92)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (10.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (36.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (9.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (9.4ms)
  Rendered attachments/_form.html.erb (1.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (2.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (78.5ms)
Completed 200 OK in 134ms (Views: 89.6ms | ActiveRecord: 36.7ms)
Started GET "/redmine/projects/project-document-tracking-system/dmsf?folder_id=9" for 192.168.2.78 at 2016-03-16 14:39:59 +0100
Processing by DmsfController#show as HTML
  Parameters: {"folder_id"=>"9", "id"=>"project-document-tracking-system"}
  Current user: igorp (id=92)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (8.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (7.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (21.6ms)
  Rendered attachments/_form.html.erb (1.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (2.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (56.8ms)
Error: dmsf_file id 69 has no revision!
```

**Comment by igorp74** [comment]
I don't know if I sent you the right parts of the log, but that is the last I've done on server/redmine.

**Comment by picman** [comment]
Yes, you did. This is the crucial part:
```ruby
ActionView::Template::Error (undefined method `title_format' for #<Member:0x007f24f57985d0>)
```
It means that the plugin migration either hasn't been run or hasn't succeeded.
Re-run the plugin migration and check the result. The _members_ table must have *title_format* after the migration.

**Comment by igorp74** [comment]
What I did (several times) is the following:

After successfully restored the mysql databse (saw all projects/tasks/wikis), and
restore /redmine/files/dmsf folder (with all ownership and permission as it shoud be)

# DMSF Installation
Stop the redmine service
```bash
sudo service apache2 stop
```
Switch to redmine user:
```bash
sudo su - redmine
```
Go to Redmine plugins directory
```bash
cd redmine/plugins
rm -rf redmine_dmsf
```
Get the latest version of DMSF
```bash
git clone https://github.com/danmunn/redmine_dmsf.git
```
Install dependencies:
```bash
bundle install
```
Initialize/Update database:
```bash
bundle exec rake redmine:plugins:migrate RAILS_ENV="production".
exit
```
Start the redmine service
```bash
sudo service apache2 start
```

That didn't hep.

So I do the following:

```bash
rake generate_secret_token
rake db:migrate RAILS_ENV=production
rake redmine:plugins:migrate RAILS_ENV=production
rake tmp:cache:clear
rake tmp:sessions:clear
```

Restart the apache
```bash
sudo service apache2 start
```

That didn't hep too.


Any ideas ?

**Comment by picman** [comment]
What is the output from rake _redmine:plugins:migrate RAILS_ENV=production_?

**Comment by igorp74** [comment]
Migrating redmine_dmsf (DMSF)...
== 20151020141801 LargeFiles: migrating =======================================
-- change_column(:dmsf_file_revisions, :size, :bigint, {:null=>true})
   -> 0.2635s
== 20151020141801 LargeFiles: migrated (0.2637s) ==============================

== 20151209100001 TitleFormat: migrating ======================================
-- add_column(:members, :title_format, :text, {:null=>true, :limit=>100})
   -> 0.2511s
== 20151209100001 TitleFormat: migrated (0.2512s) =============================

== 201500910153701 TitleNotNull: migrating ====================================
-- change_column(:dmsf_file_revisions, :title, :string, {:null=>false})
   -> 0.2346s
== 201500910153701 TitleNotNull: migrated (0.2347s) ===========================

**Comment by igorp74** [comment]
I did the same thing I've already done, and it works now ?!?!?!?  :+1:

**Comment by igorp74** [comment]
If this would help, these are the full installation steps I've done on Redmine 3.2.0.:

#Installation
Stop the redmine service
```bash
sudo service apache2 stop
```
Switch to redmine user:
```bash
sudo su - redmine
```
Go to Redmine plugins directory
```bash
cd redmine/plugins
```
If you have an old version of DMSF plugin, delete the folder
```bash
rm -rf redmine_dmsf
```
Get the latest version of DMSF
```bash
git clone https://github.com/danmunn/redmine_dmsf.git
```
Install dependencies:
```bash
cd redmine
bundle install
```
Initialize/Update database:
```bash
bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
exit
```
Start the redmine service
```bash
sudo service apache2 start
```
