### ISSUE TITLE
Error migration

### ISSUE THREAD

**Issue by drdelportillo** [danmunn/redmine_dmsf#519]
Hello

**after installing the necessary gems I run the rake command and gives me the following error**

C:\Bitnami\redmine-3.0.1-0\apps\redmine\htdocs>ruby bin/rake redmine:plugins RAI
LS_ENV="production"
DL is deprecated, please use Fiddle
Migrating redmine_dmsf (DMSF)...
== 1 CreateHierarchy: migrating ===============================================
-- create_table(:dmsf_folders)
   -> 0.0700s
-- create_table(:dmsf_files)
   -> 0.1700s
-- create_table(:dmsf_file_revisions)
   -> 0.1100s
-- create_table(:dmsf_file_locks)
   -> 0.1300s
-- create_table(:dmsf_user_prefs)
   -> 0.1500s
== 1 CreateHierarchy: migrated (0.6499s) ======================================

== 2 DmsfNormalization: migrating =============================================
-- rename_column(:dmsf_folders, :name, :title)
   -> 0.2400s
== 2 DmsfNormalization: migrated (0.2400s) ====================================

== 3 Dmsf080: migrating =======================================================
-- add_column(:projects, :dmsf_description, :text)
   -> 0.2600s
== 3 Dmsf080: migrated (0.2600s) ==============================================

== 4 Dmsf090: migrating =======================================================
-- add_column(:members, :dmsf_mail_notification, :boolean)
   -> 0.2800s
-- drop_table(:dmsf_user_prefs)
   -> 0.0400s
== 4 Dmsf090: migrated (0.3400s) ==============================================

== 5 Dmsf0901: migrating ======================================================
-- create_table(:dmsf_file_revision_accesses)
   -> 0.1100s
== 5 Dmsf0901: migrated (0.1200s) =============================================

== 6 Dmsf120: migrating =======================================================
-- add_column(:dmsf_file_revisions, :project_id, :integer, {:null=>true})
   -> 0.2600s
-- change_column(:dmsf_file_revisions, :project_id, :integer, {:null=>false})
   -> 0.3200s
== 6 Dmsf120: migrated (0.6099s) ==============================================

== 7 Dmsf144: migrating =======================================================
-- add_column(:dmsf_file_locks, :entity_type, :integer, {:null=>true})
   -> 0.3900s
-- add_column(:dmsf_file_locks, :lock_type_cd, :integer, {:null=>true})
   -> 0.2400s
-- add_column(:dmsf_file_locks, :lock_scope_cd, :integer, {:null=>true})
   -> 0.2200s
-- add_column(:dmsf_file_locks, :uuid, :string, {:null=>true, :limit=>36})
   -> 0.2010s
-- add_column(:dmsf_file_locks, :expires_at, :datetime, {:null=>true})
   -> 0.2220s
-- Preserving 0 file lock(s) found in old schema
-- Applying default lock scope / type - Exclusive / Write
-- change_column(:dmsf_file_locks, :entity_type, :integer, {:null=>false})
   -> 0.1700s
-- change_column(:dmsf_file_locks, :lock_type_cd, :integer, {:null=>false})
   -> 0.2000s
-- change_column(:dmsf_file_locks, :lock_scope_cd, :integer, {:null=>false})
   -> 0.1800s
-- rename_column(:dmsf_file_locks, :dmsf_file_id, :entity_id)
   -> 0.1900s
-- remove_column(:dmsf_file_locks, :locked)
   -> 0.3350s
-- rename_table(:dmsf_file_locks, :dmsf_locks)
   -> 0.0400s
-- Completing one-time file migration ...
-- Action was not successful
undefined local variable or method `generated_feature_methods' for #<Class:0x5ea
6d48>
["C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/li
b/active_record/dynamic_matchers.rb:26:in `method_missing'", "C:/Bitnami/redmine
-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/protected_attributes-1.0.5/lib/active_rec
ord/mass_assignment_security/nested_attributes.rb:30:in `block in accepts_nested
_attributes_for'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/pro
tected_attributes-1.0.5/lib/active_record/mass_assignment_security/nested_attrib
utes.rb:16:in `each'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems
/protected_attributes-1.0.5/lib/active_record/mass_assignment_security/nested_at
tributes.rb:16:in `accepts_nested_attributes_for'", "C:/Bitnami/redmine-3.0.1-0/
apps/redmine/htdocs/plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:31:in
`<class:DmsfFileRevision>'", "C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/plu
gins/redmine_dmsf/app/models/dmsf_file_revision.rb:22:in `<top (required)>'", "C
:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/
active_support/dependencies.rb:274:in `require'", "C:/Bitnami/redmine-3.0.1-0/ru
by/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.
rb:274:in `block in require'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.
0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dep
endency'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activesuppo
rt-4.2.0/lib/active_support/dependencies.rb:274:in `require'", "C:/Bitnami/redmi
ne-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/
dependencies.rb:360:in `require_or_load'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/
ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:494:
in `load_missing_constant'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.
0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_miss
ing'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4
.2.0/lib/active_support/dependencies.rb:526:in `load_missing_constant'", "C:/Bit
nami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/activ
e_support/dependencies.rb:184:in `const_missing'", "C:/Bitnami/redmine-3.0.1-0/a
pps/redmine/htdocs/plugins/redmine_dmsf/db/migrate/07_dmsf_1_4_4.rb:89:in `up'",
 "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/li
b/active_record/migration.rb:569:in `up'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/
ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `e
xec_migration'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activ
erecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate
'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/2.0.0/benchmark.rb:281:in `measure
'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0
/lib/active_record/migration.rb:589:in `block in migrate'", "C:/Bitnami/redmine-
3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/conne
ction_adapters/abstract/connection_pool.rb:292:in `with_connection'", "C:/Bitnam
i/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_re
cord/migration.rb:588:in `migrate'", "C:in `migrate'", "C:/Bitnami/redmine-3.0.1
-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/migration.
rb:995:in `block in execute_migration_in_transaction'", "C:/Bitnami/redmine-3.0.
1-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/migration
.rb:1043:in `ddl_transaction'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2
.0.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migr
ation_in_transaction'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gem
s/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'",
"C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib
/active_record/migration.rb:952:in `each'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib
/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `
migrate'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/activerecor
d-4.2.0/lib/active_record/migration.rb:820:in `up'", "C:/Bitnami/redmine-3.0.1-0
/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/migration.rb
:798:in `migrate'", "C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/lib/redmine/
plugin.rb:474:in `migrate_plugin'", "C:/Bitnami/redmine-3.0.1-0/apps/redmine/htd
ocs/lib/redmine/plugin.rb:446:in `migrate'", "C:/Bitnami/redmine-3.0.1-0/apps/re
dmine/htdocs/lib/redmine/plugin.rb:460:in `block in migrate'", "C:/Bitnami/redmi
ne-3.0.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:459:in `each'", "C:/Bitnami
/redmine-3.0.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:459:in `migrate'", "C
:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/lib/tasks/redmine.rake:127:in `blo
ck (3 levels) in <top (required)>'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/g
ems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'", "C:/Bitnami/redmine-
3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block
 in execute'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10
.4.2/lib/rake/task.rb:235:in `each'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/
gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'", "C:/Bitnami/redm
ine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `b
lock in invoke_with_call_chain'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/2.0.
0/monitor.rb:211:in `mon_synchronize'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/rub
y/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'",
 "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/
task.rb:165:in `invoke'", "C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/lib/ta
sks/redmine.rake:52:in `block (2 levels) in <top (required)>'", "C:/Bitnami/redm
ine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `c
all'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib
/rake/task.rb:240:in `block in execute'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/r
uby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'", "C:/Bitnami/red
mine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `
execute'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2
/lib/rake/task.rb:179:in `block in invoke_with_call_chain'", "C:/Bitnami/redmine
-3.0.1-0/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'", "C:/Bitnami/r
edmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in
 `invoke_with_call_chain'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0
/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'", "C:/Bitnami/redmine-3.0.1-0
/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invok
e_task'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/
lib/rake/application.rb:106:in `block (2 levels) in top_level'", "C:/Bitnami/red
mine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:1
06:in `each'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10
.4.2/lib/rake/application.rb:106:in `block in top_level'", "C:/Bitnami/redmine-3
.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:115:in
`run_with_threads'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/r
ake-10.4.2/lib/rake/application.rb:100:in `top_level'", "C:/Bitnami/redmine-3.0.
1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `blo
ck in run'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4
.2/lib/rake/application.rb:176:in `standard_exception_handling'", "C:/Bitnami/re
dmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:
75:in `run'", "C:/Bitnami/redmine-3.0.1-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.
4.2/bin/rake:33:in `<top (required)>'", "bin/rake:16:in `load'", "bin/rake:16:in
 `<main>'"]
== 7 Dmsf144: migrated (2.4898s) ==============================================

== 20120822100401 CreateDmsfWorkflows: migrating ==============================
-- create_table(:dmsf_workflows)
   -> 0.0500s
-- add_index(:dmsf_workflows, [:name], {:unique=>true})
   -> 0.1200s
-- change_table(:dmsf_file_revisions)
   -> 0.9329s
== 20120822100401 CreateDmsfWorkflows: migrated (1.1229s) =====================

== 20120822100402 CreateDmsfWorkflowSteps: migrating ==========================
-- create_table(:dmsf_workflow_steps)
   -> 0.1200s
-- add_index(:dmsf_workflow_steps, :dmsf_workflow_id)
   -> 0.0900s
== 20120822100402 CreateDmsfWorkflowSteps: migrated (0.2200s) =================

== 20120822100403 CreateDmsfWorkflowStepAssignments: migrating ================
-- create_table(:dmsf_workflow_step_assignments)
   -> 0.1400s
-- add_index(:dmsf_workflow_step_assignments, [:dmsf_workflow_step_id, :dmsf_fil
e_revision_id], {:name=>"index_dmsf_wrkfl_step_assigns_on_wrkfl_step_id_and_frev
_id", :unique=>true})
   -> 0.5639s
== 20120822100403 CreateDmsfWorkflowStepAssignments: migrated (0.7139s) =======

== 20120822100404 CreateDmsfWorkflowStepActions: migrating ====================
-- create_table(:dmsf_workflow_step_actions)
   -> 0.0600s
-- add_index(:dmsf_workflow_step_actions, :dmsf_workflow_step_assignment_id, {:n
ame=>"idx_dmsf_wfstepact_on_wfstepassign_id"})
   -> 0.1800s
== 20120822100404 CreateDmsfWorkflowStepActions: migrated (0.2400s) ===========

== 20130819013955 UpdateProjects: migrating ===================================
-- add_column(:projects, :dmsf_notification, :boolean)
   -> 0.1800s
== 20130819013955 UpdateProjects: migrated (0.1800s) ==========================

== 20131108141401 AddIndexToDmsfFiles: migrating ==============================
-- add_index(:dmsf_files, :project_id)
   -> 0.1200s
== 20131108141401 AddIndexToDmsfFiles: migrated (0.1200s) =====================

== 20131108141402 AddIndexToDmsfFolders: migrating ============================
-- add_index(:dmsf_folders, :project_id)
   -> 0.1200s
== 20131108141402 AddIndexToDmsfFolders: migrated (0.1200s) ===================

== 20131113141401 AddIndexToDmsfFileRevision: migrating =======================
-- add_index(:dmsf_file_revisions, :dmsf_file_id)
   -> 0.1600s
== 20131113141401 AddIndexToDmsfFileRevision: migrated (0.1600s) ==============

== 20131113141402 AddIndexToDmsfLock: migrating ===============================
-- add_index(:dmsf_locks, :entity_id)
   -> 0.1900s
== 20131113141402 AddIndexToDmsfLock: migrated (0.2000s) ======================

== 20131113141403 CreateDmsfLinks: migrating ==================================
-- create_table(:dmsf_links)
   -> 0.2500s
-- add_index(:dmsf_links, :project_id)
   -> 0.1300s
== 20131113141403 CreateDmsfLinks: migrated (0.3800s) =========================

== 20140314132501 NotificationsOn: migrating ==================================
-- change_column(:projects, :dmsf_notification, :boolean, {:default=>true, :null
=>true})
   -> 0.1500s
-- change_column(:dmsf_folders, :notification, :boolean, {:default=>true, :null=
>false})
   -> 0.1000s
== 20140314132501 NotificationsOn: migrated (0.2500s) =========================

== 20140519133201 TrashBin: migrating =========================================
-- add_column(:dmsf_folders, :deleted, :boolean, {:default=>false, :null=>false}
)
   -> 0.5799s
-- add_column(:dmsf_folders, :deleted_by_user_id, :integer)
   -> 0.3700s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined local variable or method `generated_feature_methods' for #<Class:0x675
8898>C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/plugins/redmine_dmsf/app/mod
els/dmsf_folder.rb:49:in `<class:DmsfFolder>'
C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/plugins/redmine_dmsf/app/models/d
msf_folder.rb:22:in `<top (required)>'
C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/plugins/redmine_dmsf/db/migrate/2
0140519133201_trash_bin.rb:27:in `up'
C:in `migrate'
C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:474:in `mig
rate_plugin'
C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:446:in `mig
rate'
C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:460:in `blo
ck in migrate'
C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:459:in `eac
h'
C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:459:in `mig
rate'
C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/lib/tasks/redmine.rake:127:in `bl
ock (3 levels) in <top (required)>'
C:/Bitnami/redmine-3.0.1-0/apps/redmine/htdocs/lib/tasks/redmine.rake:52:in `blo
ck (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

C:\Bitnami\redmine-3.0.1-0\apps\redmine\htdocs>

**Comment by drdelportillo** [comment]
as additional data Gem xapian not install

**Comment by picman** [comment]
1. Try *bundle update protected_attributes*.
2. Xapian is not available for Windows as far as I know, so you must call *bundle install --without xapian* (It's written in the README)
3. The Windows was a very bad choice. With Linux is the life much easier.

**Comment by picman** [comment]
No more support for MS Windows.

**Comment by drdelportillo** [comment]
thanks for your answer
