### ISSUE TITLE
Document link after a search ...

### ISSUE THREAD

**Issue by ncister** [danmunn/redmine_dmsf#520]
Hi.
Using the standard search box with the keyword "open", I obtain 2 results (for example: "RF-Open.pdf" and "IM-Open.pdf") but the links of documents are in the format "http://...../dmsf/files/3"  so, clicking on them, I navigate to the document detail.
I think that could be more useful build the link in the format "http://...../dmsf/files/3/**view**" so, clicking on them I can open the file.
Thanks.

**Comment by picman** [comment]
Changed to view.
