### ISSUE TITLE
Files do not inherit folder permissions

### ISSUE THREAD

**Issue by abhigginbotham** [danmunn/redmine_dmsf#521]
I do not know if this is a bug on configuration error.  I am trying to backup the files directory using rsync.  When I run my script it creates all the folders but I get a permissions issue on all the files I have added through the dmsf tab of my redmine site.  When I examined the folders the permissions = 0755 which allows read and execute for everyone.  However, the files placed in that directory are given permission = 0600 read/write only for the owner.  This is ok in the context of uploading/downloading through the redmine site but won't allow me to run an rsync script under my user account and backup the directory.  

Can someone explain why I have this problem and how to work around it?  

If this is the wrong venue for this question I apologize.

**Comment by DarkSideGeek** [comment]
Much of what you describe is going to be a function of the web server (eg Apache, nginx, etc) and/or the Rails engine (eg Passenger), not Redmine per se. I suggest you research 'umask' for your particular setup. Redmine just does whatever the web server permissions allow, which in turn is dependent upon the OS.

However, I suspect that if you were to "chmod g+s" on the main /files/ directory, then everything that gets created thereafter will inherit the mode of the parent. The setting of the setuid bit in the group set (of a directory) will turn on permissions inheritance for the files.
