### ISSUE TITLE
File Storage Directory does not change

### ISSUE THREAD

**Issue by dalfry** [danmunn/redmine_dmsf#522]
Excellent plugin! Thanks for all the hard work.

One issue -
Tried changing the file storage location in plugin config. It seems to take the new directory and I see a "dmsf" directory being created in the new storage location but when new files are uploaded, they still go to redmine/files/dmsf....

Is this a bug or am I missing anything?

**Comment by picman** [comment]
Try to restart the application (web server).

**Comment by picman** [comment]
From v1.5.7 no application restart will be required after the storage path change.
