### ISSUE TITLE
Bug with "delegate approval step"

### ISSUE THREAD

**Issue by MaxizAtGitHub** [danmunn/redmine_dmsf#523]
Hello!
After searching user, when generating new labels, label name changed from "**step_action**" to "**user_ids[]**" and radio buttons don't work well. In row 31 of "app/helpers/dmsf_workflows_helper.rb
" I change 'user_ids[]' to 'step_action' and solve this problem for me. Can you fix it in next build?

**Comment by picman** [comment]
Fixed. Thank you for reporting such an old bug and also for the solution.
