### ISSUE TITLE
Redmine Documents userwise

### ISSUE THREAD

**Issue by ashwanthrao** [danmunn/redmine_dmsf#525]
Is it possible to assign roles and permission to documents to view

**Comment by picman** [comment]
No, it isn't.

**Comment by ashwanthrao** [comment]
Any plans in near future?

**Comment by picman** [comment]
No, Redmine permissions model is kept.

**Comment by ashwanthrao** [comment]
Did you checked the  link https://www.easyredmine.com/software/easy-redmine-2016
which had document module,I just wanted to know whether both are same?

**Comment by picman** [comment]
No, it's the standard Redmine document module.

**Comment by picman** [comment]
v1.6.0 contains a new feature - Folder permissions. In the folder details form you can set members or roles permissions to the folder.
