### ISSUE TITLE
[Feature request] Add MD5 of each revision in the detail view of documents

### ISSUE THREAD

**Issue by JL2014** [danmunn/redmine_dmsf#527]
Hi,

Could you add the MD5 value of each revision of a document in the revisions list of each document ?
(between the filename and type properties for example)
 
My problem is: I want to remove duplicates revisions of a document, the MD5 could help me in this process.

Greetings.

**Comment by picman** [comment]
Done. I've also added a rake test to create the checksum for all the existing revisions.
