### ISSUE TITLE
full text search does not work on Redmine 3.2.0 stable with DMSF 1.5.6

### ISSUE THREAD

**Issue by aydintd** [danmunn/redmine_dmsf#528]
Hello all,

I have a Redmine 3.2.0-stable version and trying to use DMSF (currently v1.5.6) with its full text search which looks great. 

But I had no luck with the searching in full text after plugin installation on redmine.

Here's my redmine environment information :

> Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Git                            2.1.4 Filesystem                     
Redmine plugins:
  redmine_backlogs               v1.0.6
  redmine_ckeditor               1.1.3
  redmine_dmsf                   1.5.6
  redmine_monitoring_controlling 0.1.1>

I'm running my redmine with single user rvm which is redmine unix user on my linux box. (Debian 8 Jessie)

I did not run into any problems on dmsf installation (bundle install, rake plugins:migrate etc.) everything looks good.

Here's my installed gems :

> redmine@redminetest:/opt/redmine$  gem list
> 
> *** LOCAL GEMS ***
> 
> actionmailer (4.2.5)
> actionpack (4.2.5)
> actionpack-action_caching (1.1.1)
> actionpack-xml_parser (1.0.2)
> actionview (4.2.5)
> activejob (4.2.5)
> activemodel (4.2.5)
> activerecord (4.2.5)
> activesupport (4.2.5)
> addressable (2.4.0)
> arel (6.0.3)
> autotest-rails (4.2.1)
> bigdecimal (1.2.6)
> builder (3.2.2)
> bundler (1.8.4)
> bundler-unload (1.0.2)
> capybara (2.5.0)
> childprocess (0.5.9)
> climate_control (0.0.3)
> cocaine (0.5.8)
> coderay (1.1.0)
> concurrent-ruby (1.0.0)
> css_parser (1.3.7)
> daemons (1.2.3)
> dav4rack (0.3.0)
> docile (1.1.5)
> erubis (2.7.0)
> eventmachine (1.0.9.1)
> executable-hooks (1.3.2)
> ffi (1.9.10)
> gem-wrappers (1.2.7)
> globalid (0.3.6)
> holidays (1.0.8)
> htmlentities (4.3.1)
> i18n (0.7.0)
> icalendar (2.3.0)
> io-console (0.4.3)
> jquery-rails (3.1.4)
> json (1.8.3, 1.8.1)
> kaminari (0.16.3)
> loofah (2.0.3)
> mail (2.6.3)
> metaclass (0.0.4)
> mime-types (2.99)
> mini_portile2 (2.0.0)
> minitest (5.8.3, 5.4.3)
> mocha (1.1.0)
> multi_json (1.11.2)
> mysql2 (0.3.20)
> net-ldap (0.12.1)
> nokogiri (1.6.7.1)
> open-uri-cached (0.0.5)
> pandoc-ruby (1.0.0)
> paperclip (4.2.4)
> pdf-core (0.6.0)
> power_assert (0.2.2)
> prawn (2.0.2)
> protected_attributes (1.1.3)
> psych (2.0.8)
> puma (2.15.3)
> rack (1.6.4)
> rack-openid (1.4.2)
> rack-raw-upload (1.1.1)
> rack-test (0.6.3)
> rails (4.2.5)
> rails-deprecated_sanitizer (1.0.3)
> rails-dom-testing (1.0.7)
> rails-html-sanitizer (1.0.2)
> railties (4.2.5)
> rake (10.5.0, 10.4.2)
> rbpdf (1.19.0)
> rbpdf-font (1.19.0)
> rdoc (4.2.1, 4.2.0)
> redcarpet (3.3.4)
> request_store (1.0.5)
> rmagick (2.15.4)
> roadie (3.1.1)
> roadie-rails (1.1.0)
> ruby-openid (2.3.0)
> rubygems-bundler (1.4.4)
> rubyzip (1.1.7)
> rvm (1.11.3.9)
> sass (3.4.21)
> sass-rails (5.0.4)
> selenium-webdriver (2.49.0)
> simple_enum (2.3.0)
> simplecov (0.9.2)
> simplecov-html (0.9.0)
> sprockets (3.5.2)
> sprockets-rails (3.0.0)
> test-unit (3.0.8)
> thor (0.19.1)
> thread_safe (0.3.5)
> tilt (2.0.2)
> ttfunk (1.4.0)
> tzinfo (1.2.2)
> uuidtools (2.1.5)
> websocket (1.2.2)
> xapian-full-alaveteli (1.2.21.1)
> xpath (2.0.0)
> yard (0.8.7.6)
> ZenTest (4.5.0)
> zip-zip (0.3) 
> 

I also did not run into any problem on database migration process. All necessary tables which comes with DMSF migrated successfully.

And here's my redmine_dmsf/extra/xapian_indexer.rb

> Redmine installation directory
> $redmine_root = '/opt/redmine'
> 
> DMSF document location $redmine_root/$files
> $files = 'files/dmsf'
> 
> scriptindex binary path
> $scriptindex  = '/usr/bin/scriptindex'
> 
> omindex binary path
> $omindex      = '/usr/bin/omindex'
> 
> Directory containing xapian databases for omindex (Attachments indexing)
> $dbrootpath   = '/opt/redmine/files/dmsf-index'
> 
> Verbose output, values of 0 no verbose, greater than 0 verbose output
> $verbose      = 1
> 
>  Define stemmed languages to index attachments Eg. [ 'english', 'italian', 'spanish' ]
>  Repository database will be always indexed in english
>  Available languages are danish dutch english finnish french german german2 hungarian italian kraaij_pohlmann lovins norwegian porter portuguese romanian russian spanish swedish turkish:
> $stem_langs     = [ 'english', 'turkish' ]
> 
>  Project identifiers that will be indexed eg. [ 'prj_id1', 'prj_id2' ]
> $projects       = [ 'prj_id1', 'prj_id2' ]
> 
>  Temporary directory for indexing, it can be tmpfs
> $tempdir        = '/tmp'
> 
>  Binaries for text conversion
> $pdftotext = '/usr/bin/pdftotext -enc UTF-8'
> $antiword        = '/usr/bin/antiword'
> $catdoc          = '/usr/bin/catdoc'
> $xls2csv         = '/usr/bin/xls2csv'
> $catppt          = '/usr/bin/catppt'
> $unzip           = '/usr/bin/unzip -o'
> $unrtf           = '/usr/bin/unrtf -t text 2>/dev/null'

I also installed all these recommended debian packages on the wiki page.
When i run the xapian_indexer.rb manually, it seems it creates my documents index :

> redmine@redminetest:/opt/redmine/plugins$ ruby redmine_dmsf/extra/xapian_indexer.rb -f -v                                                                                                                                                                                      
> Trying to load Redmine environment <</opt/redmine/config/environment.rb>>...
> Redmine environment [RAILS_ENV=production] correctly loaded ...
> /opt/redmine/files/dmsf-index/english does not exist, creating ...
> /usr/bin/omindex -s english --db /opt/redmine/files/dmsf-index/english /opt/redmine/files/dmsf --url / -v
> [Entering directory ""]
> [Entering directory "p_testing/"]
> Indexing "p_testing/160421171945_8_sources.list" as text/plain ... added
> [Entering directory "p_deneme-projesi/"]
> Indexing "p_deneme-projesi/160421163239_3_ldap-client-entegrasyonu.txt" as text/plain ... added
> Indexing "p_deneme-projesi/160421163040_3_ldap-client-entegrasyonu.txt" as text/plain ... added
> Indexing "p_deneme-projesi/160421164131_6_Setup-a-Clonezilla-Server-on-Debian-Ubuntu.pdf" as application/pdf ... added
> Indexing "p_deneme-projesi/160421170934_7_sources.list" as text/plain ... added
> Indexing "p_deneme-projesi/160421162812_2_ldap-caching-mechanism.pdf" as application/pdf ... added
> Indexing "p_deneme-projesi/160421164131_5_Learning-Go-latest.pdf" as application/pdf ... added
> Indexing "p_deneme-projesi/160421163502_4_CV__ablonu-Son.doc" as application/msword ... added
> Indexing "p_deneme-projesi/160421162652_1_PardusNetworkDiagram.pdf" as application/pdf ... added
> /opt/redmine/files/dmsf-index/turkish does not exist, creating ...
> /usr/bin/omindex -s turkish --db /opt/redmine/files/dmsf-index/turkish /opt/redmine/files/dmsf --url / -v
> [Entering directory ""]
> [Entering directory "p_testing/"]
> Indexing "p_testing/160421171945_8_sources.list" as text/plain ... added
> [Entering directory "p_deneme-projesi/"]
> Indexing "p_deneme-projesi/160421163239_3_ldap-client-entegrasyonu.txt" as text/plain ... added
> Indexing "p_deneme-projesi/160421163040_3_ldap-client-entegrasyonu.txt" as text/plain ... added
> Indexing "p_deneme-projesi/160421164131_6_Setup-a-Clonezilla-Server-on-Debian-Ubuntu.pdf" as application/pdf ... added
> Indexing "p_deneme-projesi/160421170934_7_sources.list" as text/plain ... added
> Indexing "p_deneme-projesi/160421162812_2_ldap-caching-mechanism.pdf" as application/pdf ... added
> Indexing "p_deneme-projesi/160421164131_5_Learning-Go-latest.pdf" as application/pdf ... added
> Indexing "p_deneme-projesi/160421163502_4_CV__ablonu-Son.doc" as application/msword ... added
> Indexing "p_deneme-projesi/160421162652_1_PardusNetworkDiagram.pdf" as application/pdf ... added
> Redmine files indexed

And here's the filesystem view of the index directory :

> redmine@redminetest:/opt/redmine/files/dmsf-index$ ls -lR
> .:
> total 8
> drwxr-xr-x 2 redmine redmine 4096 Apr 22 09:58 english
> drwxr-xr-x 2 redmine redmine 4096 Apr 22 09:58 turkish
> 
> ./english:
> total 556
> -rw-r--r-- 1 redmine redmine      0 Apr 22 09:58 flintlock
> -rw-r--r-- 1 redmine redmine     28 Apr 22 09:58 iamchert
> -rw-r--r-- 1 redmine redmine     13 Apr 22 09:58 position.baseA
> -rw-r--r-- 1 redmine redmine     17 Apr 22 09:58 position.baseB
> -rw-r--r-- 1 redmine redmine 155648 Apr 22 09:58 position.DB
> -rw-r--r-- 1 redmine redmine     13 Apr 22 09:58 postlist.baseA
> -rw-r--r-- 1 redmine redmine     19 Apr 22 09:58 postlist.baseB
> -rw-r--r-- 1 redmine redmine 311296 Apr 22 09:58 postlist.DB
> -rw-r--r-- 1 redmine redmine     13 Apr 22 09:58 record.baseA
> -rw-r--r-- 1 redmine redmine     14 Apr 22 09:58 record.baseB
> -rw-r--r-- 1 redmine redmine   8192 Apr 22 09:58 record.DB
> -rw-r--r-- 1 redmine redmine     13 Apr 22 09:58 termlist.baseA
> -rw-r--r-- 1 redmine redmine     14 Apr 22 09:58 termlist.baseB
> -rw-r--r-- 1 redmine redmine  57344 Apr 22 09:58 termlist.DB
> 
> ./turkish:
> total 588
> -rw-r--r-- 1 redmine redmine      0 Apr 22 09:58 flintlock
> -rw-r--r-- 1 redmine redmine     28 Apr 22 09:58 iamchert
> -rw-r--r-- 1 redmine redmine     13 Apr 22 09:58 position.baseA
> -rw-r--r-- 1 redmine redmine     17 Apr 22 09:58 position.baseB
> -rw-r--r-- 1 redmine redmine 155648 Apr 22 09:58 position.DB
> -rw-r--r-- 1 redmine redmine     13 Apr 22 09:58 postlist.baseA
> -rw-r--r-- 1 redmine redmine     20 Apr 22 09:58 postlist.baseB
> -rw-r--r-- 1 redmine redmine 344064 Apr 22 09:58 postlist.DB
> -rw-r--r-- 1 redmine redmine     13 Apr 22 09:58 record.baseA
> -rw-r--r-- 1 redmine redmine     14 Apr 22 09:58 record.baseB
> -rw-r--r-- 1 redmine redmine   8192 Apr 22 09:58 record.DB
> -rw-r--r-- 1 redmine redmine     13 Apr 22 09:58 termlist.baseA
> -rw-r--r-- 1 redmine redmine     14 Apr 22 09:58 termlist.baseB
> -rw-r--r-- 1 redmine redmine  57344 Apr 22 09:58 termlist.DB

But nothing appears at all whenever i search anything in my redmine search bar related to my DMSF docs.

I don't know what to do, where to look and ran out of ideas.

Any help would be appreciated. 
Thanks.

**Comment by picman** [comment]
Have you unchecked _Search titles only_?

**Comment by aydintd** [comment]
Hey @picman , thanks for your answer first of all

Yes, I only checked "all words" option and I also have extra "Documents" and "Folders" and these are all checked too. But I can't find any keywords in my documents when i searched them.

**Comment by picman** [comment]
An what does say the production log when you're searching?

**Comment by aydintd** [comment]
you're a genious @picman : there was an error caused by a stupid typo has been done from me 
(i'd examined the production logs before but i think i missed that tiny error):

error logs were like those :

> Started GET "/projects/testing/search?utf8=%E2%9C%93&q=debian&scope=&all_words=&all_words=1&titles_only=&issues=1&news=1&documents=1&changesets=1&wiki_pages=1&messages=1&dmsf_files=1&dmsf_folders=1&attachments=0&options=0&commit=Submit" for 127.0.0.1 at 2016-04-22 14:52:
> 13 +0300
> Processing by SearchController#index as HTML
>   Parameters: {"utf8"=>"✓", "q"=>"debian", "scope"=>"", "all_words"=>"1", "titles_only"=>"", "issues"=>"1", "news"=>"1", "documents"=>"1", "changesets"=>"1", "wiki_pages"=>"1", "messages"=>"1", "dmsf_files"=>"1", "dmsf_folders"=>"1", "attachments"=>"0", "options"=>"0", "
> commit"=>"Submit", "id"=>"testing"}
> Settings cache cleared.
>   Current user: aydin.doyak (id=5)
> REDMAIN_XAPIAN ERROR: Xapian database is not properly set or initiated or is corrupted.
> DatabaseOpeningError: Couldn't stat '/opt/redmine/files/dmsf_index/english'
>   Rendered search/index.html.erb within layouts/base (8.9ms)
>   Rendered plugins/redmine_backlogs/app/views/hooks/_rb_include_scripts.html.erb (1.2ms)
> Completed 200 OK in 209ms (Views: 44.8ms | ActiveRecord: 64.9ms)

I mis-typed "dmsf-index" directory in Redmine Admin Plugin Panel with "dmsf_index" so that's why it didnt work. Now I fixed it and it works like a charm as expected.

Sorry for kept you busy for a while and thanks for your helps.
