### ISSUE TITLE
Modified timestamps lost after migration

### ISSUE THREAD

**Issue by hammady** [danmunn/redmine_dmsf#532]
After migrating old "Documents" to DMSF using the rake task, all files have the same modified at timestamps.
Timestamps are important, so is there a way to keep the same modification timestamps?

**Comment by picman** [comment]
Which time stamp do you refer to?

I've just tested the migration as follows:
1. Redmine _Documents_ module activated.
2. A document Med created at 10:30.
3. Migration rake run at 10:33 => _Documents_ module deactivated, _DMSF_ activated. A new folder Med (Modified 10:33) created. A new file med (Modified 10:30) created.

So the time of file modification is kept by the document.

![0 0 0 0_2016-06-03_10-38-41](https://cloud.githubusercontent.com/assets/779003/15773481/5d07f748-2977-11e6-9c2a-72bde32930db.png)
