### ISSUE TITLE
Email notification permissions

### ISSUE THREAD

**Issue by rolandfelber** [danmunn/redmine_dmsf#533]
Email notification is not working when users don't have "Edit Rights" on files and folders in "Roles and Rights" under DMSF.
Some customers should only be able to view/read the documents and still get notifications when the file version changed or new files were added to a specific folder.

**Comment by rolandfelber** [comment]
Hi Picman,

do you know when 1.5.7 will be released?`

Regards,
Roland

**Comment by picman** [comment]
I'm pretty busy now, I'm afraid. End of June, no sooner.

**Comment by rolandfelber** [comment]
Thanks for the quick reply.

Hav a nice day.

Regards,
Roland

**Comment by picman** [comment]
Are you sure that the users not receiving the notifications haven't set in their account profile "Only for things I..."? Only in this case I believe they don't receive notifications.

**Comment by rolandfelber** [comment]
I'll test it today in give you feedback.

Best regards,
Roland

Mit freundlichen Grüßen,
Roland Felber

Sent from my iPhone

Am 10.06.2016 um 09:05 schrieb Karel Picman <notifications@github.com<mailto:notifications@github.com>>:


Are you sure that the users not receiving the notifications haven't set in their account profile "Only for things I..."? Only in this case I believe they don't receive notifications.

**Comment by picman** [comment]
Anyway, I've slightly modified the behaviour as follows:

You receive notifications if:

**Only things I am the owner of**, **Only things I am assigned to** => If you are the author of the last revision.
**Only things I watch or I'm involved in** =>If you are the author of any revision.

**Comment by rolandfelber** [comment]
Hi,

the problem is, that users with readable rights on the DMSF library can’t get notifications because they don’t have “edit” or “author” rights.

BR,
Roland

Von: Karel Picman [mailto:notifications@github.com]
Gesendet: Freitag, 10. Juni 2016 09:41
An: danmunn/redmine_dmsf <redmine_dmsf@noreply.github.com>
Cc: Felber Roland <Roland.Felber@ghp-holding.net>; Author <author@noreply.github.com>
Betreff: Re: [danmunn/redmine_dmsf] Email notification permissions (#533)


Anyway, I've slightly modified the behaviour as follows:

You receive notifications if:

Only things I am the owner of, Only things I am assigned to => If you are the author of the last revision.
Only things I watch or I'm involved in =>If you are the author of any revision.

**Comment by picman** [comment]
That's not true. Test it and describe a use case when it doesn't work as expected.

**Comment by picman** [comment]
No feedback for more than one month => closed.
