### ISSUE TITLE
ActionView::Template::Error (undefined method `as_enum' for #<Class:0x00000004d12ca8>):

### ISSUE THREAD

**Issue by obm0rok** [danmunn/redmine_dmsf#535]
we updated redminie from ver 2.5.2 to 3.2.2 also we updated dmsf from 1.5.2 -> 1.5.6 and this error occurs:

Started GET "/projects/rs/dmsf" for 127.0.0.1 at 2016-06-01 11:54:11 +0300
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"rs"}
  Current user: ysazanov (id=146)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (296.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (456.9ms)
Completed 500 Internal Server Error in 2189ms (ActiveRecord: 864.3ms)

ActionView::Template::Error (undefined method `as_enum' for #<Class:0x00000004d12ca8>):
    20: # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
    21: %>
    22:
    23: <% locked_for_user = subfolder && subfolder.locked_for_user? %>
    24: <% locked = subfolder && subfolder.locked? %>
    25:
    26: <td class="check"><%= check_box_tag(name, id, false,
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Please help to solve

**Comment by obm0rok** [comment]
Some additional info:
if i try to rename newly created folder on fresh installation of redmine 3.2.2 and DMSF 1.5.6
 i get the same error:

Started GET "/projects/rs/dmsf/edit?folder_id=1" for 127.0.0.1 at 2016-06-02 10:50:30 +0300
Processing by DmsfController#edit as HTML
  Parameters: {"folder_id"=>"1", "id"=>"rs"}
  Current user: admin (id=1)
  Rendered plugins/redmine_dmsf/app/views/dmsf/edit.html.erb within layouts/base (23.9ms)
Completed 500 Internal Server Error in 96ms (ActiveRecord: 33.9ms)

ActionView::Template::Error (undefined method `as_enum' for #<Class:0x00000007c6c8c8>):
    21:
    22: <div class="contextual">
    23:   <% if User.current.allowed_to?(:folder_manipulation, @project) && params[:action] == 'edit' %>
    24:     <% unless @folder.locked? %>
    25:        <%= link_to(l(:button_lock),
    26:           lock_dmsf_path(:id => @project, :folder_id => @folder),
    27:           :title => l(:title_lock_file),
  plugins/redmine_dmsf/app/models/dmsf_lock.rb:33:in `<class:DmsfLock>'
  plugins/redmine_dmsf/app/models/dmsf_lock.rb:25:in `<top (required)>'
  plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:35:in `lock'
  plugins/redmine_dmsf/lib/redmine_dmsf/lockable.rb:27:in `locked?'
  plugins/redmine_dmsf/app/views/dmsf/edit.html.erb:24:in `_plugins_redmine_dmsf_app_views_dmsf_edit_html_erb___3579102199956005234_67413840'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'

**Comment by picman** [comment]
Similar error has been discussed many times here. I've just tried Redmine 3.2.2 + DMSF 1.5.7-devel. It works.

_bundle install_ succeeded?
_simple_enum_ gem installed?

**Comment by obm0rok** [comment]
this error occurs on Gentoo linux with Ruby 2.1.
on Ubuntu Linux 16.0.4 with Ruby 2.3 all works fine
