### ISSUE TITLE
Make single Document or Folder anonymously accessible

### ISSUE THREAD

**Issue by tjaeger** [danmunn/redmine_dmsf#536]
This is a typical Feature from Services such as Dropbox or Google to share a Document with anonymous Users. To share a single Document or Folder with anonymous Users (but through a dedicated Link like https://www.linktoredmine.com/s/mxz6kqctvd6otjt/documents.zip?dl=0
The idea really is that i dont need to make my project accessible anonymously but only selected Documents through a "hashed" link.

**Comment by fahrplaner** [comment]
I would also like this feature. Please add the option to add a password and maybe a date until the link will be accessible.

**Comment by picman** [comment]
![image201701020935_1](https://cloud.githubusercontent.com/assets/779003/21673897/85fae0ee-d32b-11e6-816f-acc617012c65.png)

**Comment by picman** [comment]
#626
