### ISSUE TITLE
Webdav:  Filter Mac OS X "resource forks" Files

### ISSUE THREAD

**Issue by simonswine** [danmunn/redmine_dmsf#54]
Hi!

I've got a litte enhancement. 

As i got many mac os x user, that accessing dmsf via webdav. I'm seeing many "._*" files from max os x. This so called ressource forks, can be seen on the webinterface. I would find it great that there will be a filter for these files, so that they are not shown in the browser.

Thank you for the hard work!

**Comment by picman** [comment]
DMSF WebDAV module updated accordingly.
