### ISSUE TITLE
Link from commbo box sorting

### ISSUE THREAD

**Issue by mrazek** [danmunn/redmine_dmsf#542]
Hello, we use links to other documents in the DMSF. in the folder list, there is somehow weird-sorted list of folders of chosen project. I would assume it is sorted according to folder ID or something like that. Is it possible to do this more user-friendly, for example alphabetically sorted, searchabel or so...

However, many thanks for the plugin, it is great and very useful!!

**Comment by picman** [comment]
That's strange. The default is the alphabetical ordering. You should see a small arrow in the title column. Could you post a screen-shot from your application? Does the ordering work If you click a column header?

![kdpt kontron local_2016-07-18_13-45-33](https://cloud.githubusercontent.com/assets/779003/16913870/2dd8595a-4cee-11e6-84ca-87a08fef75ac.png)

**Comment by mrazek** [comment]
Thank you for you response, it is about sorting within the ComboBox during link creation. I attached screenchot so it is more clear now, I hope.
![dmsf_link](https://cloud.githubusercontent.com/assets/12605987/16914044/647aba06-4cef-11e6-91b6-41d15b1a2d63.png)

**Comment by picman** [comment]
I see it now. It's a bug. I'll fix it.

**Comment by picman** [comment]
Fixed. Thank you for the bug report.

**Comment by freemanT** [comment]
Is the sorting also fixed in 1.5.7 for comboboxes in Copy/Move-Dialog, New-Document-Dialog etc.?
Thank your for your feedback.

**Comment by picman** [comment]
Yes.

**Comment by freemanT** [comment]
Cool! Thanks for the fast answer!
