### ISSUE TITLE
1.5.7 devel branch: Setting Title format should be global setting, but released as local setting

### ISSUE THREAD

**Issue by dskibarko** [danmunn/redmine_dmsf#547]
Usually, not all users have permission to change projects  settings. 
Then i setting field "Title format:" then this setting is active for me only. 
Any over user download files without append to name  my settings.

Seems to need release 2 way of (administrator configurable) global setting "Title format:" 
1) global for all projects - used as default in project if field "Title format:" not filled in project settings
2) global for selected projects - used in specified project if  field "Title format:" filled in project settings

**Comment by picman** [comment]
Done.
