### ISSUE TITLE
Duplicate icons

### ISSUE THREAD

**Issue by aalmada** [danmunn/redmine_dmsf#548]
The icons show up multiple times as it can be seen in the picture: 
![dmsf](https://cloud.githubusercontent.com/assets/534533/16945580/7d23ef7e-4d9d-11e6-86a2-8b7f63d74d0c.png)

I'm using the latest source (1.5.6) and tried both on Chrome and Edge with the same result.

**Comment by picman** [comment]
It should be Okay in devel-1.5.7. Please try it.

**Comment by aalmada** [comment]
Thanks for looking at this issue but I still see the duplicate icons with devel-1.5.7

![2016-07-26 16_47_19-plugins - lusospace redmine](https://cloud.githubusercontent.com/assets/534533/17145061/c65a47de-5350-11e6-98d6-556e8c0c3837.png)

**Comment by aalmada** [comment]
I experience the same issue with the Redmine Issues Tree plugin. I hope this helps.

**Comment by aalmada** [comment]
I noticed you are setting in the CSS the icon as the background for the link. The Redmine links just next to  it use a different approach.
![2016-07-28 16_07_08-](https://cloud.githubusercontent.com/assets/534533/17217923/f41febae-54dd-11e6-8f34-e7133fe73cfa.png)

**Comment by picman** [comment]
Redmine 3.3 + DMSF 1.5.7-devel

Source code Edit icon (Redmine), Notification icon (DMSF):

```
<a title="Edit Documents" class="icon icon-edit" href="/projects/c1/dmsf/edit/root">Edit</a>
<a title="Notifications not active: Activate" class="icon dmsf_icon-notification-off" href="/projects/c1/dmsf/notify/activate">Notifications on</a>
```

Corresponding CSS, application.css 1125, redmine_dmsf.css 170

```
.icon-edit {
    background-image: url(../images/edit.png);
}

.dmsf_icon-notification-off {
    background-image: url(../images/notifynot.png);
    margin-left: 3px;
}
```

Which approach do you refer?
