### ISSUE TITLE
Dmsf still sending emails

### ISSUE THREAD

**Issue by Zaboon** [danmunn/redmine_dmsf#550]
Hello,

I have a redmine 3.2.3 with the latest version of dmsf. I have desactivated the notifications in the settings, but dmsf is still sending emails. Any idea ?

Thanks

**Comment by picman** [comment]
There is several places related to email notification settings:
1. Plugin's settings
2. User's settings
3. Project's settings
4. Folder's settings
5. Document's settings

Could you describe your case in more details, please? Notifications on the folder/document off?

**Comment by Zaboon** [comment]
My problem is in the plugin's settings. In fact, the email notifications settings are desactivated, but when we upload or delete a file, emails are still sending

**Comment by picman** [comment]
If the default notifications are off in the plugin's settings, the new folders and document have deactivated notifications. However, when a folder or document has manually activated notifications or had been created before the default value has been set off, the notification are sent.
Please check whether notifications are set on or off on the given folder/document too.
