### ISSUE TITLE
Default action for files viewing

### ISSUE THREAD

**Issue by mrazek** [danmunn/redmine_dmsf#551]
It would be great if the behaviour of file links in the DMSF table is the same as a general link to file on internet and that standard dialogue with options (Save File/Open File etc) will be shown. By now, default action is done regardless browser settings.

This is maybe more a question rather than an issue - is there any difference between classic file link and DMSF file link?

Many thanks!

**Comment by picman** [comment]
The default action is "show". If you want to download a document, you must use the context menu and choose "Save Link As"
This is a new feature. It use to be as you described. The default action was "download" and the user was offered with an option either to download or open the document.

The "show" seems to be more suitable in DMS.

**Comment by mrazek** [comment]
Many thanks for the response. Would it be too complicated to make it configurable in plugin settings? Download vs. Show document..

**Comment by picman** [comment]
Probably not. I keep is open as a feature request.

**Comment by picman** [comment]
I've synchronized with Redmine attachments. They use "show" for images and PDFs and "download" for others.
