### ISSUE TITLE
JQeury datatable not load correct language file

### ISSUE THREAD

**Issue by cartsofware** [danmunn/redmine_dmsf#554]
Hello,
I have created the it.json file with the language translations for the jquery datatable, which, however, continues to load only en.json

I think the problem is in the file 'plugins/redmine_dmsf/app/views/dmsf/show.html.erb' at the line 239:
sUrl = 'jquery.dataTables/en.json' the unless File.exist?(sUrl)

File.exist?(sUrl) always returns false, even if i'm sure the it.json is in the correct place...

in fact, if i use the following lines instead:
sUrl = 'jquery.dataTables/en.json'
sUrl = "jquery.dataTables/#{I18n.locale.to_s.downcase}.json" if I18n.locale && !I18n.locale.to_s.match(/^en.*/)
(taken from 'plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb')
it works!!

Thank you for your help.

**Comment by picman** [comment]
I will fix it. Can you post your it.json file? I'd add it into the project. Have you got it.yml too? It would be also great if we can add the Italien translation to the plugin.

**Comment by cartsofware** [comment]
Thank you very much!
for the italian lang file of course! here they are ...

bye
[Redmine_DMSF_it.zip](https://github.com/danmunn/redmine_dmsf/files/387910/Redmine_DMSF_it.zip)

**Comment by picman** [comment]
Fixed. Thank you for your contribution.
