### ISSUE TITLE
Plugin settings "File default notifications" does not apply!

### ISSUE THREAD

**Issue by cartsofware** [danmunn/redmine_dmsf#556]
Hi,
if i set "File default notifications" to "Activated" and then i create a new project, in DMSF section the generic link "Notification on / off" (at the top of page) is always off per default! and in fact email notification on new file are not send!

if i manually click on link and set "notifications on" and then upload a file, the email is sent correctly!
could it be a bug or is the correct behaviour?

```
Environment:
  Redmine version                3.3.0.stable
  Ruby version                   2.3.0-p0 (2015-12-25) [x86_64-linux]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Filesystem                     
Redmine plugins:
  redmine_checklists             3.1.3
  redmine_contacts               4.0.4
  redmine_custom_help_url        0.0.2
  redmine_custom_reports         0.1.5
  redmine_dmsf                   1.5.6
  redmine_favorite_projects      2.0.2
  redmine_ics_export             3.0.1.dev
  redmine_language_change        0.1.0
  redmine_monitoring_controlling 0.1.1
  redmine_people                 1.2.0
  redmine_stats                  0.0.3
  redmine_xlsx_format_issue_exporter 0.1.2
  sidebar_hide                   0.0.7
```

Kind regards

**Comment by cartsofware** [comment]
I realized that when "File default notifications" is set to "Activated" and then add a file in DMSF the file itself is set with "notifications on" (the icon down the file's row in the table) but email is not send!
generic notification icon (the one above table) is still off!

but if i add a revision to the same file the email is correctly sent...

**Comment by picman** [comment]
Fixed.
