### ISSUE TITLE
Watch Documents

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#557]
Tickets and Wiki pages can be watched. DMSF unfortunately uses a different functionality: notifications.

This confuses a lot of users as DMSF does not follow standard behaviour of redmine for documents.

Therefore I would suggest to add the "Watch" functionality for DMSF as well and that this works exactly the same way as for tickets. Maybe this could also be offered as a setting (something like "Use Watch or Notifications").

**Comment by ldmpub** [comment]
I agree with this enhancement.

Plus I would propose to allow user to define the frequency of the "watch mail notification" : immediatly, hourly, daily, weekly, monthly.

**Comment by mrazek** [comment]
+1 for "Watch" feature for DMSF documents (user is notified in case of any change of document, approval process, deteion...)

**Comment by ldmpub** [comment]
Be careful because as far as I know: if you use WebDav each save creates a version and may notify users ;-(.

**Comment by mrazek** [comment]
Well, if I want to know, that the watched document was updated/changed/deleted, I would appreciate if I am notified, even if it is twice per day... If I don't want to be notified, I would just not watch the document... But yes, daily summary of changes in watched documents could be enough.

**Comment by picman** [comment]
## I've just finished a basic functionality of watch/unwatch. Is there someone available for testing and feedback?

New functionality is available in _redmine_notifications_ branch (no migration, extra gems needed).

How does it work?

1. Settings
There are two new options in the global **Email notifications**:
- _Approval workflows_ - Set to true if you want to get notifications related to approval workflows.
- _Dmsf legacy notifications_ - Set to true if you want to the present notifications' functionality be still available.

![image](https://user-images.githubusercontent.com/779003/151549353-8a392f2b-7a7b-4c4f-8a14-dd976a136d0d.png)
2. Watch/Unwatch
Project, folder and file's context menus have been extended with Watch/Unwatch menu item. If there are some watchers also the sidebar is displayed/extended with watchers.
3. Notifications
Watchers are added to the recipients of notifications that might come from approval workflow's notifications or the legacy notifications. If you watch a project or folder, you consequently watch also all child item recursively.

**Comment by mmundi72** [comment]
Hi 
I just did some testing and this looks awesome. Thank you very much for your work. This is very much appreciated.

Here my first feedback:
If a the logged in user has set "I don't want to be notified of changes that I make myself" DMSF still shows this message:
![image](https://user-images.githubusercontent.com/7224922/152400697-30e027e6-1aa0-4c8a-8459-b211383cfda5.png)

This message is wrong as in reality no email has been sent to the user (as per setting in the user's account). The message shown is not correct. The behaviour of sending the mail works find.

One more optimization would be great: is it possible to show the "Watch"-Star-Icon in the table view? This would help a user to instantly see which documents/folder he/she is watching. I could be even a shortcut to activate/inactivate watching the object.

Not tested yet: Workflow (we do not use the workflow-feature) and behavior using WebDav.

**Comment by picman** [comment]
1. I fixed the problem with "I don't want to be notified of changes that I make myself" option.
2. I think that the star icon won't be in sync with other modules. There is also no star visible in the Issues module when an issue is watched.
3. Approval workflow and WebDAV module shouldn't be touched by the changes as watchers are added as an email recipients just before sending an email independently of from where the notification comes.

**Comment by mmundi72** [comment]
Thank you. Concerning 2:
You are right. But it's also different how you work with the objects: 

- Issues: you are opening an issue in the browser view and the user instantly sees if the issue is being watched or not
- Document: normally you just open the document as such. Doing this does not provide the information concerning the watch status. To get access to this information as user has to additionally open the context menu or click on the document id (-> document history). I'm not sure if users will understand this. That's why I thought it would be useful and straightforward. But it's also ok to just leave as it is.

**Comment by picman** [comment]
![image](https://user-images.githubusercontent.com/779003/153571019-3f38763a-1644-41b4-b859-11148eb50d68.png)
