### ISSUE TITLE
cannot create new projects if plugin is installed

### ISSUE THREAD

**Issue by ricger** [danmunn/redmine_dmsf#559]
I've installed v 1.5.7 on two different redmine 3.3.0 servers:
* both debian 8.5
* both xapian active 
* some other plugins on one of the servers / no other plugin on the other

DMSF works fine on existing projects, but creation of new project isn't possible. 
No error message, no success message. Nothing happens, UI remains in creation form, no new project has been created.
After deinstallation of redmine_dmsf everything works as expected again.

**Comment by picman** [comment]
Having not know the reason now, comment out following row in _lib/redmine_dmsf/patches/project_patch.rb_:
```ruby
def set_default_dmsf_notification
  if self.new_record?
   # self.dmsf_notification = Setting.plugin_redmine_dmsf['dmsf_default_notifications'] == '1'
  end
end
```

**Comment by picman** [comment]
It should be fixed now. Please get the updated source codes.

**Comment by ricger** [comment]
works perfekt, thanks!
