### ISSUE TITLE
Installation of 1.5.7 failed - redmine can no longer start.

### ISSUE THREAD

**Issue by FHDumay** [danmunn/redmine_dmsf#563]
A tried to install the commands as per the instructions, but after the bundle install part things  do not run as expected:

root@server /var/www/redmine/current/plugins/redmine_dmsf # bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Using rake 11.2.2
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.0
Using thread_safe 0.3.5
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 2.0.1
Using uuidtools 2.1.5
Using rubyzip 1.2.0
Using xapian-full-alaveteli 1.2.21.1
Using yard 0.9.5
Using bundler 1.12.5
Using tzinfo 1.2.2
Using nokogiri 1.6.8
Using zip-zip 0.3
Using activesupport 5.0.0.1
Using dav4rack 0.3.0
Using simple_enum 2.3.0
Bundle complete! 8 Gemfile dependencies, 19 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

root@server /var/www/redmine/current/plugins/redmine_dmsf # bundle exec rake redmine:plugins:migrate RAILS_ENV="production" --trace
(in /var/www/redmine/3.3.0)
rake aborted!
LoadError: cannot load such file -- rails/all
/var/www/redmine/3.3.0/config/application.rb:3:in `require'
/var/www/redmine/3.3.0/config/application.rb:3:in `<top (required)>'
/var/www/redmine/3.3.0/Rakefile:5:in `require'
/var/www/redmine/3.3.0/Rakefile:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_module.rb:28:in `load'
/var/lib/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/var/lib/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:686:in `raw_load_rakefile'
/var/lib/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:96:in `block in load_rakefile'
/var/lib/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:95:in `load_rakefile'
/var/lib/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:79:in `block in run'
/var/lib/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/var/lib/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'

root@server /var/www/redmine/current/plugins/redmine_dmsf # thin start
No adapter found for /var/www/redmine/3.3.0/plugins/redmine_dmsf
root@fhdumay /var/www/redmine/current/plugins/redmine_dmsf # 

So, that the installation failed is not as expected - fine, i could come back later and try again - however, i have no idea how to get redmine back up again. 

Any help/ideas are highly appreciated

**Comment by FHDumay** [comment]
Ok - i got redmine working again aftter moving the installation and the gems in /var/lib/gems/2.3.0 out of the way, and restoring yesterdays backup and partially redoing the redmine install.

Only question remaining - why did the install fail ?

**Comment by picman** [comment]
```
root@server /var/www/redmine/current/plugins/redmine_dmsf # bundle exec rake redmine:plugins:migrate RAILS_ENV="production" --trace
```
I think that bundle install and migration should be run in the Redmine directory and not in the plugin directory.

**Comment by FHDumay** [comment]
Hmm - seems i caused this issue all by my self. I do apoligize for the
noise; I have been working with redmine for about 2 weeks or so, so not a
real expert (yet).
