### ISSUE TITLE
Install : rake redmine:plugins:migrate table create error

### ISSUE THREAD

**Issue by nemesix29** [danmunn/redmine_dmsf#564]
Hello,

I tried to install dmsf after Redmine 3.3.0 upgrade, but I can't finalize plugin installation. 

The plugin migrate command return this error :

`~/redmine$ bundle exec rake redmine:plugins:migrate RAILS_ENV="production"                                                        `
`Migrating redmine_bootstrap_kit (Redmine Bootstrap Kit plugin)...                                                                 `
`Migrating redmine_dmsf (DMSF)...                                                                                                  `
`== 20120822100401 CreateDmsfWorkflows: migrating ==============================                                                   `
`-- create_table(:dmsf_workflows)                                                                                                  `
`   -> 0.0367s                                                                                                                     `
`-- add_index(:dmsf_workflows, [:name], {:unique=>true})                                                                           `
`   -> 0.0073s                                                                                                                     `
`-- change_table(:dmsf_file_revisions)                                                                                             `
`rake aborted!                                                                                                                     `
`StandardError: An error has occurred, all later migrations canceled:                                                              `
`                                                                                                                                  `
`Mysql2::Error: Table 'redmine.dmsf_file_revisions' doesn't exist: ALTER TABLE `dmsf_file_revisions` ADD `dmsf_workflow_id` int(11)`

If I retry, I get this : 

`Migrating redmine_bootstrap_kit (Redmine Bootstrap Kit plugin)...                                                                                                                               `
`Migrating redmine_dmsf (DMSF)...                                                                                                                                                                `
`== 20120822100401 CreateDmsfWorkflows: migrating ==============================                                                                                                                 `
`-- create_table(:dmsf_workflows)                                                                                                                                                                `
`rake aborted!                                                                                                                                                                                   `
`StandardError: An error has occurred, all later migrations canceled:                                                                                                                            `
`                                                                                                                                                                                                `
`Mysql2::Error: Table 'dmsf_workflows' already exists: CREATE TABLE `dmsf_workflows` (`id` int(11) auto_increment PRIMARY KEY, `name` varchar(255) NOT NULL, `project_id` int(11)) ENGINE=InnoDB `

Did you have this error in past ?

**Comment by nemesix29** [comment]
I forget to tell you the version used.
I tried to install the 1.5.7 tag.

**Comment by nemesix29** [comment]
Same issue with master.

**Comment by picman** [comment]
Your database is obviously corrupted. Is the plugin installed for the for the first time or is it an upgrade? I'd recommend deleting all tables with the prefix *dmsf_* and all records like '%redmine_dmsf' from *schema_migration* table and run the migration from the begining again.

**Comment by nemesix29** [comment]
Hi,
It's exactly that. The data base was modified by an old install, but not uninstalled.
I have succeeded to clean up the database.
Now it works fine.
Thank you.
