### ISSUE TITLE
Problem rack version on Debian jessie

### ISSUE THREAD

**Issue by guidtz** [danmunn/redmine_dmsf#567]
Hello,
  when I done bundle install I have 

```
Installing rack 2.0.1

Gem::InstallError: rack requires Ruby version >= 2.2.2.
```

So I have installed ruby with ruby build for get ruby 2.2.2 

```
ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

```

Do you know a solution to finalise installation ?

Thanks

**Comment by picman** [comment]
How is this related to the plugin?
