### ISSUE TITLE
Approve proccess not started on 1.5.7 version

### ISSUE THREAD

**Issue by dskibarko** [danmunn/redmine_dmsf#568]
Is not working new approve process then previous process was not finished (can not be finished!) and a new version of file was loaded. The icon for approve present on the screen but no reaction after mouse clicking.
I think requred way to reject started approve process from Manager of Administrator for resolve manually same collisions.

**Comment by picman** [comment]
Either finish the current approval workflow or create a new document revision. Approval workflows are always related to the last revision of the document.
