### ISSUE TITLE
Question: Email Notification when someone downloads a file and entry in activity stream

### ISSUE THREAD

**Issue by fahrplaner** [danmunn/redmine_dmsf#570]
Hello,

is somewhere documented when a notification is sent? Can it be configured?

Problem (using version 1.5.5): We do not want users beeing notified, if someone downloads a file and the document access should not be listed in the activity stream.

#513

**Comment by picman** [comment]
There is neither notification not activity record in case of download. I'm afraid that it hasn't been documented yet and it can't be configured.

**Comment by fahrplaner** [comment]
Thanks for your promt reply. I did further testing:

The information on the activity page is only visible for admins and can be configured for others via: admin -> roles -> (choose desired role) -> DMSF: View downloads / revisions  in Activity stream.

Thank you.
