### ISSUE TITLE
Uploading files with Russian characters

### ISSUE THREAD

**Issue by simargll** [danmunn/redmine_dmsf#572]
Hi!

When I upload files with Russian characters pop up error.
Also, if I try to create a folder with a Russian name
This error occurs when I upload file and change the file header into another language (Russian)
Tell me, please, what is the problem can be

ruby 2.3.1p112
Rails 4.2.6
redmine 3.3
--------------------
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error.

Back
--------------------------------------

**Comment by movcale** [comment]
see errors in logfile /redmine_dir/log/production.log

**Comment by simargll** [comment]
Thank you very much!

There was an error with character encodings in the database
