### ISSUE TITLE
Macro {{dmsfd(xx)}} produce blank value

### ISSUE THREAD

**Issue by movcale** [danmunn/redmine_dmsf#574]
After plugin upgrade has an issue with  {{dmsf**d**(xx)}} macro. It is not displayed.

I suppose to see a document name which lead to 
http://my_redmine.com/dmsf/files/xx

{{dmsf(xx)}} works fine and produce a link to the latest version of document
http://my_redmine.com/dmsf/files/xx/view

production.log has no errors

**Comment by picman** [comment]
I've just tested the macro and it works as expected, I think.

> I suppose to see a document name

_dmsfd_ macro displays the document's description not it's name. Your document description is empty and therefore nothing is displayed very probably.

**Comment by movcale** [comment]
Hello,
Yes, now behavior is as you described. But in previous versions of this plugin dmsfd works in different way.
See this
https://github.com/danmunn/redmine_dmsf/commit/d6500cb861fb56b77f70b74efb110c0f88bafafe#diff-242d0b4ac43f99fbb7c9023c1aca7166L144

I have a huge redmine database with dmsfd links to documents without description.

As a workaround I replace line 77 in 
plugins/redmine_dmsf/lib/redmine_dmsf/macros.rb
from
return textilizable(file.description)
to
return link_to h(file.title), dmsf_file_url(file)

So maybe left dmsfd macro as is and introduce a new macro for "description" will be more convenient way.

**Comment by picman** [comment]
That was a bug. If you want to display a link to a document, you should use _dmsf_ macro instead.

**Comment by movcale** [comment]
I need a macro link, with display document title and lead to "document revisions"
http://my_redmine.com/dmsf/files/xx
not no direct download
http://my_redmine.com/dmsf/files/xx/view

So what macro I should use ?

**Comment by picman** [comment]
Hm, maybe you're right the d meant details, not description. If I change it again, the users which use it as document description will claim :-(

dmsfd - will point to the document details form
dmsfdesc - will show the document description

?

**Comment by movcale** [comment]
> dmsfd - will point to the document details form
and will show a document title, not document description

>dmsfdesc - will show the document description
and be a link to either document details form or direct download (it is up to you)

**Comment by picman** [comment]
Done.

_dmsfdesc_ produces no link but text.

**Comment by movcale** [comment]
Just updated to dmsf ver. 1.5.8 and seems that dmsfd works as expected.
Thank you, picman !
