### ISSUE TITLE
Change Color of UI

### ISSUE THREAD

**Issue by thejulian** [danmunn/redmine_dmsf#575]
I need/want to change the color [here](http://imgur.com/NyPH95a) from blue to something else. I checked the `assets/stylesheets/dmsf.css` -file, but didn't find anything.

Where I have to change it?

**Comment by picman** [comment]
Web Developer usually helps here:

![web_developer](https://cloud.githubusercontent.com/assets/779003/18428302/714ecd3a-78cd-11e6-9735-fea27d1358a7.png)

**Comment by thejulian** [comment]
Thanks got it! :+1:
