### ISSUE TITLE
Installation problem 1.5.7 (step 4 of the guide)

### ISSUE THREAD

**Issue by gekmcfh** [danmunn/redmine_dmsf#576]
Environment:
Ubuntu 16.04 LTS
  Redmine version                3.3.0.stable
  Ruby version                   2.3.0-p0 (2015-12-25) [x86_64-linux]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  no plugin installed

Hello! I just wanna to view and touch possibilities of dmsf in my virtual machine. But i can't go throught 4th step of installation guide:

```
user@ubuntu:/var/www/redmine/plugins/redmine_dmsf-1.5.7$ bundle exec rake redmine:plugins:migrate RAILS_ENV="production"

/home/user/.rvm/gems/ruby-2.3.0@rails4/gems/bundler-1.13.1/lib/bundler/rubygems_integration.rb:336:in `block (2 levels) in replace_gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
        from /home/user/.rvm/gems/ruby-2.3.0@rails4/bin/rake:22:in `<main>'
        from /home/user/.rvm/gems/ruby-2.3.0@rails4/bin/ruby_executable_hooks:15:in `eval'
        from /home/user/.rvm/gems/ruby-2.3.0@rails4/bin/ruby_executable_hooks:15:in `<main>'

```
Okay, added gem 'rake' into Gemfile (was i wrong?) ,then:

```
user@ubuntu:/var/www/redmine/plugins/redmine_dmsf-1.5.7$ bundle exec rake redmine:plugins:migrate RAILS_ENV="production" --trace
(in /opt/redmine-3.3.0)
rake aborted!
LoadError: cannot load such file -- rails/all
/opt/redmine-3.3.0/config/application.rb:3:in `require'
/opt/redmine-3.3.0/config/application.rb:3:in `<top (required)>'
/opt/redmine-3.3.0/Rakefile:5:in `require'
/opt/redmine-3.3.0/Rakefile:5:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.3.0@rails4/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load'
/home/user/.rvm/gems/ruby-2.3.0@rails4/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/user/.rvm/gems/ruby-2.3.0@rails4/gems/rake-11.3.0/lib/rake/application.rb:686:in `raw_load_rakefile'
/home/user/.rvm/gems/ruby-2.3.0@rails4/gems/rake-11.3.0/lib/rake/application.rb:96:in `block in load_rakefile'
/home/user/.rvm/gems/ruby-2.3.0@rails4/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/user/.rvm/gems/ruby-2.3.0@rails4/gems/rake-11.3.0/lib/rake/application.rb:95:in `load_rakefile'
/home/user/.rvm/gems/ruby-2.3.0@rails4/gems/rake-11.3.0/lib/rake/application.rb:79:in `block in run'
/home/user/.rvm/gems/ruby-2.3.0@rails4/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/user/.rvm/gems/ruby-2.3.0@rails4/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/home/user/.rvm/gems/ruby-2.3.0@rails4/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.3.0@rails4/bin/rake:23:in `load'
/home/user/.rvm/gems/ruby-2.3.0@rails4/bin/rake:23:in `<main>'
/home/user/.rvm/gems/ruby-2.3.0@rails4/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.3.0@rails4/bin/ruby_executable_hooks:15:in `<main>'
```

Also, then i put redmine_dmsf-1.5.7 into /opt/redmine-3.3.0/plugins, redmine has crashed with passenger error:

 ```
<pre>Bundler:<wbr>:<wbr>PermissionError (Bundler:<wbr>:<wbr>PermissionError)
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/bundler-1.13.1/lib/bundler/shared_helpers.rb:<wbr>107:<wbr>in `rescue in filesystem_access&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/bundler-1.13.1/lib/bundler/shared_helpers.rb:<wbr>105:<wbr>in `filesystem_access&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/bundler-1.13.1/lib/bundler/definition.rb:<wbr>321:<wbr>in `lock&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/bundler-1.13.1/lib/bundler/runtime.rb:<wbr>130:<wbr>in `lock&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/bundler-1.13.1/lib/bundler/runtime.rb:<wbr>58:<wbr>in `setup&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/bundler-1.13.1/lib/bundler.rb:<wbr>99:<wbr>in `setup&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/bundler-1.13.1/lib/bundler/setup.rb:<wbr>20:<wbr>in `&lt;top (required)&gt;&apos;
  /home/user/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:<wbr>55:<wbr>in `require&apos;
  /home/user/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:<wbr>55:<wbr>in `require&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:<wbr>430:<wbr>in `activate_gem&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:<wbr>297:<wbr>in `block in run_load_path_setup_code&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:<wbr>435:<wbr>in `running_bundler&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:<wbr>296:<wbr>in `run_load_path_setup_code&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:<wbr>100:<wbr>in `preload_app&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:<wbr>156:<wbr>in `&lt;module:<wbr>App&gt;&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:<wbr>30:<wbr>in `&lt;module:<wbr>PhusionPassenger&gt;&apos;
  /home/user/.rvm/gems/ruby-2.3.0@rails4/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:<wbr>29:<wbr>in `&lt;main&gt;&apos;
</pre>
```

Then i have done next:
```
cd /opt/redmine-3.3.0/plugins/redmine_dmsf-1.5.7
gem install bundler
bundle install
```

passenger's error leaves, and redmine gets up but then i trying to go to ->administration->projects->new project it's returns 404 error page not found.
DMSF appears in modules menu, but then i click "configure" - it's returns 404 too.
Looks like there is some DMSF's admin menu at the Administration (links to redmine.test.local/workflow) - but returns 404 and calls "translation missing: en.label_dmsf_workflow_plural"
![dmsf](https://cloud.githubusercontent.com/assets/10114910/18810981/df05b5bc-82ac-11e6-9829-6741ae7e1d0b.PNG)

I think my problems caused by access rules, but for what exactly? I chown -R'ed /opt/redmine to www-data:user, what i've missed?

**Comment by picman** [comment]
The migration task must be run from within Redmine folder not the plugin folder.

**Comment by gekmcfh** [comment]
Thanks for advice! Look's like migrating gone well

```
user@ubuntu:/opt/redmine-3.3.0$ bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
Migrating redmine_dmsf (DMSF)...
```
But there is still access to some pages (http://rmtest.local.domain/my/account | http://rmtest.local.domain/settings/plugin/redmine_dmsf | http://rmtest.local.domain/projects/new | http://rmtest.local.domain/dmsf_workflows | http://rmtest.local.domain/projects/prj-id/settings) becomes broken down 

> 404
> The page you were trying to access doesn't exist or has been removed.
> Back

when i put redmine_dmsf-1.5.7 folder (with default permissions and chown -R'ed to www-data) to plugins dir. When i do guide-like Uninstalling DMSF, access to that pages (exclude dmsf pages) returns back.

**Comment by picman** [comment]
I don't fully understand your problem I'm afraid. Please try it explain in other words/simplier.

**Comment by gonter** [comment]
404?   What do the production.log and web server logs contain at the time when the error happend?

**Comment by gekmcfh** [comment]
I'm really sorry for english.

1. I have fresh installed redmine (see environment in the 1st message) for example rmtest.local.domain
   1.1 I try to go to http://rmtest.local.domain/my/account - it's works.
   1.2 I try to go to http://rmtest.local.domain/projects/new - it's works
   1.3 I try to go to http://rmtest.local.domain/projects/someproject/settings - it's works

2. I do install of dmsf like in the guide. Installation completes without any errors.

3. I reboot my virtual machine, now dmsf have appeared in http://rmtest.local.domain/admin/plugins but
   3.1 I try to go to http://rmtest.local.domain/settings/plugin/redmine_dmsf - it's returns 404 (screenshot)
![222](https://cloud.githubusercontent.com/assets/10114910/19344948/f6fdb998-9144-11e6-9dd4-1a27c1df0ab7.PNG)

   3.2 I try to go to http://rmtest.local.domain/projects/new - it's returns 404
   3.3 I try to go to http://rmtest.local.domain/projects/someproject/settings - it's returns 404
   3.4 I try to go to http://rmtest.local.domain/my/account - it's returns 404
   3.5 I try to go http://rmtest.local.domain/dmsf_workflows - it's returns 404
Seem's like all other pages works.

4. I make dmsf uninstalling  and reboot virtual machine. All pages works again like point 1.

**Comment by picman** [comment]
Post your production.log as gonter has already asked.

**Comment by gekmcfh** [comment]
I did in a previous message.

**Comment by pahjbo** [comment]
I think that the problems might be connected to the directory name of the plugin having the version suffix. I was having similar problems and renamed the directory to redmine_dmsf and reran the installation rake

**Comment by picman** [comment]
Yes, this wrong. rename the plugin folder to just *redmine_dmsf*. No suffux.

```ruby
cd /opt/redmine-3.3.0/plugins/redmine_dmsf-1.5.7
```

**Comment by gekmcfh** [comment]
Thank you, guys! That helped.

**Comment by pahjbo** [comment]
it is a problem that the github releases function puts the version number into the path

**Comment by VyBui** [comment]
> The migration task must be run from within Redmine folder not the plugin folder.

Do you mind to add this line to README.md? I am new to Ruby and did not know how to run it until read this comment!

Thanks!

**Comment by picman** [comment]
Added.

**Comment by VyBui** [comment]
@picman great, thank you very much!
