### ISSUE TITLE
Webdav always shows the create date

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#581]
I'm mostly accessing DMSF using the webdav folder of DMSF. This is a great feature.

In Windows Explorer the columns "Modified Date" always shows the same date. This is the date when the document was first uploaded to DMSF (create date). It doesn't show the "Modified" date as I can see it in Redmine.

Well, I would expect to see the "Modified" date, don't you?

DMSF-Version: 1.5.6

**Comment by picman** [comment]
Fixed.
