### ISSUE TITLE
Working with MS Office documents directly in mounted WebDAV share

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#587]
My company is using MS Office products for all documents and this is not likely to change. So it would be nice if it was possible to work directly in the WebDAV share (mounted as a network share in Win10) on the documents and it almost works.

The following workflow for editing documents is what is currently working:
1. Lock the file in the web-GUI.
2. Download the file locally and modify (either from web-GUI or WebDAV share).
3. When finished, upload the file (web-GUI or WebDAV).
4. Unlock the file in the web-GUI.

If this could be done using the WebDAV only then it would make things a lot easier.

When opening for example a Word file from the WebDAV network share the file is locked, and if closing the file without modifying it the file is unlocked. Ok.
But if the file is modified and saved, then a lot of stuff happens behind the scenes. Word creates temporary files and these are stored on the WebDAV as a totally new file with a new revision history. Then that new file is moved to the real file name, and this move is (probably) what causes the wipe of the revision history.
When closing Word after this then the file is not unlocked.

It works flawless when editing text-files that don't create a lot of intermediate files.

Sorry for the strange half-message, I accidently hit ctrl-enter =)

**Comment by picman** [comment]
?

**Comment by carlolars** [comment]
This is what happens when creating a new file in Word and storing it on the WebDAV share:
![image](https://cloud.githubusercontent.com/assets/13761538/19891572/fefba7a8-a040-11e6-9d51-cb3f507e3329.png)

![untitled](https://cloud.githubusercontent.com/assets/13761538/19891710/9947b234-a041-11e6-9734-df1200200a96.png)

**Comment by carlolars** [comment]
Word uses the following sequence when saving a file:
1. Write document to temporary file X.tmp
2. Move(rename) File.docx to Y.tmp
3. Move(rename) X.tmp to File.docx
4. Delete Y.tmp

The move in 2 causes the history for the word document to be moved to file Y.tmp, and the move in 3 causes the history of the word document to become the history of the newly created X.tmp.

**Comment by carlolars** [comment]
I implemented a fix that solves the revision problem, can be found here: [OfficeSupport](https://github.com/carlolars/redmine_dmsf/commits/OfficeSupport)

Here is what I'm doing:
1. When renaming a file to *.tmp then assume that it is MSOffice that is doing its save sequence and do a copy instead of move. This will leave the original file with its history.
2. When renaming a *.tmp file to an existing file then only copy the last revision of the *.tmp file (copy the file content to a new file with correct file-ending for Xapian), delete the *.tmp file when done.
MSOffice creates empty files before writing anything, so if the last revision is zero-sized then reuse that revision instead of creating a new.

Unfortunately I don't know Ruby so might have missed something... But it works as far as I can see.

**Comment by picman** [comment]
Could you create a pull request to the branch devel-1.5.9 in order to be able easily merge your changes?

**Comment by carlolars** [comment]
The only issue left is that MsOffice creates one temporary file when opening a file (~$File.docx), and one file when saving. Those files gets added to the dmsf database and then removed, but they remain on disk.
Maybe it should be possible to create temporary files that are visible in WebDAV but not added to the database?

**Comment by picman** [comment]
#589

**Comment by picman** [comment]
I've just merged your changes and tested it a bit. Open-Edit-Save seem to be working. But, when I open MS Word, create a new document and try to save it to a mounted DMSF folder, just zero size file is stored.

**Comment by carlolars** [comment]
Strange, it is working fine in a subfolder but not in the project root folder.
I don't have access to the log files until Monday, I'll take a look then.

**Comment by carlolars** [comment]
This is an authorization issue. MsOffice sends anonymous OPTIONS request on all folders and possibly also HEAD requests. The ResourceProxy.authenticate method have a special fix for anonymous OPTIONS but only for path '/'.
I'm working on a fix.

**Comment by carlolars** [comment]
I got it to work now, see my new pull request.

**Comment by picman** [comment]
Not yet perfect, I'm afraid. At the moment I'm not able open MS Office documents. MS Office raises an error: "Can not open ...."
Here is an output from my production.log.

A non MS Office document file3. After I double click the file, it's opened in Notepad. GET returns 200 OK.

```ruby
Started PROPFIND "/dmsf/webdav/c1" for 192.168.1.251 at 2016-11-08 12:58:38 +0100
Processing WebDAV request: /dmsf/webdav/c1 (for 192.168.1.251 at 2016-11-08 12:58:38 +0100) [PROPFIND]
Completed in: 90 ms | 207 [https://localhost:3000/dmsf/webdav/c1]
Started PROPFIND "/dmsf/webdav/c1/file3" for 192.168.1.251 at 2016-11-08 12:58:38 +0100
Processing WebDAV request: /dmsf/webdav/c1/file3 (for 192.168.1.251 at 2016-11-08 12:58:38 +0100) [PROPFIND]
Completed in: 144 ms | 207 [https://localhost:3000/dmsf/webdav/c1/file3]
Started PROPFIND "/dmsf/webdav/c1/file3" for 192.168.1.251 at 2016-11-08 12:58:38 +0100
Processing WebDAV request: /dmsf/webdav/c1/file3 (for 192.168.1.251 at 2016-11-08 12:58:38 +0100) [PROPFIND]
Completed in: 94 ms | 207 [https://localhost:3000/dmsf/webdav/c1/file3]
Started GET "/dmsf/webdav/c1/file3" for 192.168.1.251 at 2016-11-08 12:58:39 +0100
Processing WebDAV request: /dmsf/webdav/c1/file3 (for 192.168.1.251 at 2016-11-08 12:58:39 +0100) [GET]
Completed in: 120 ms | 200 [https://localhost:3000/dmsf/webdav/c1/file3]
```
A MS Office document cannot be open because GET returns 404 NOT FOUND.
 (GET is called twice. That's also strange).

```ruby
Started PROPFIND "/dmsf/webdav/c1/mwd.docx" for 192.168.1.251 at 2016-11-08 12:58:50 +0100
Processing WebDAV request: /dmsf/webdav/c1/mwd.docx (for 192.168.1.251 at 2016-11-08 12:58:50 +0100) [PROPFIND]
Completed in: 41 ms | 207 [https://localhost:3000/dmsf/webdav/c1/mwd.docx]
Started GET "/dmsf/webdav/c1/mwd.docx" for 192.168.1.251 at 2016-11-08 12:58:50 +0100
Processing WebDAV request: /dmsf/webdav/c1/mwd.docx (for 192.168.1.251 at 2016-11-08 12:58:50 +0100) [GET]
Completed in: 36 ms | 200 [https://localhost:3000/dmsf/webdav/c1/mwd.docx]
Started OPTIONS "/dmsf/webdav/c1/" for 192.168.1.251 at 2016-11-08 12:58:53 +0100
Processing WebDAV request: /dmsf/webdav/c1 (for 192.168.1.251 at 2016-11-08 12:58:53 +0100) [OPTIONS]
Completed in: 2 ms | 200 [https://localhost:3000/dmsf/webdav/c1]
Started HEAD "/dmsf/webdav/c1/mwd.docx" for 192.168.1.251 at 2016-11-08 12:58:54 +0100
Processing WebDAV request: /dmsf/webdav/c1/mwd.docx (for 192.168.1.251 at 2016-11-08 12:58:54 +0100) [HEAD]
Completed in: 6 ms | 404 [https://localhost:3000/dmsf/webdav/c1/mwd.docx]
Started GET "/dmsf/webdav/c1/mwd.docx" for 192.168.1.251 at 2016-11-08 12:58:54 +0100
Processing WebDAV request: /dmsf/webdav/c1/mwd.docx (for 192.168.1.251 at 2016-11-08 12:58:54 +0100) [GET]
Completed in: 0 ms | 401 [https://localhost:3000/dmsf/webdav/c1/mwd.docx]
```

Except that unit tests fail.

**Comment by carlolars** [comment]
The OPTIONS request returns 200 which it should not, and therefore MsOffice thinks that it is ok to access the file anonymously. That's why the second GET returns 401.
So the check for MsOffice does not work for your version of Word. I'll change it to look for "Microsoft Office" in the user-agent instead, hopefully that works for more versions.

I'll have a look at the tests also, unfortunately my environment does not run tests at all now so I'll have to find out what's wrong.

**Comment by picman** [comment]
It's even worse in my case (Win7 + Office 2010) now:

```ruby
Started PROPFIND "/dmsf/webdav/c1/dokument.docx" for 192.168.1.251 at 2016-11-09 12:19:46 +0100
Processing WebDAV request: /dmsf/webdav/c1/dokument.docx (for 192.168.1.251 at 2016-11-09 12:19:46 +0100) [PROPFIND]
Completed in: 46 ms | 207 [https://localhost:3000/dmsf/webdav/c1/dokument.docx]
Started GET "/dmsf/webdav/c1/dokument.docx" for 192.168.1.251 at 2016-11-09 12:19:46 +0100
Processing WebDAV request: /dmsf/webdav/c1/dokument.docx (for 192.168.1.251 at 2016-11-09 12:19:46 +0100) [GET]
Completed in: 41 ms | 200 [https://localhost:3000/dmsf/webdav/c1/dokument.docx]
Started PROPFIND "/dmsf/webdav/c1" for 192.168.1.251 at 2016-11-09 12:19:47 +0100
Processing WebDAV request: /dmsf/webdav/c1 (for 192.168.1.251 at 2016-11-09 12:19:47 +0100) [PROPFIND]
Completed in: 24 ms | 207 [https://localhost:3000/dmsf/webdav/c1]
Started PROPFIND "/dmsf/webdav/c1/dokument.docx" for 192.168.1.251 at 2016-11-09 12:19:47 +0100
Processing WebDAV request: /dmsf/webdav/c1/dokument.docx (for 192.168.1.251 at 2016-11-09 12:19:47 +0100) [PROPFIND]
Completed in: 40 ms | 207 [https://localhost:3000/dmsf/webdav/c1/dokument.docx]
Started OPTIONS "/dmsf/webdav/c1/" for 192.168.1.251 at 2016-11-09 12:19:47 +0100
Processing WebDAV request: /dmsf/webdav/c1 (for 192.168.1.251 at 2016-11-09 12:19:47 +0100) [OPTIONS]
Completed in: 3 ms | 405 [https://localhost:3000/dmsf/webdav/c1]
Started HEAD "/dmsf/webdav/c1/dokument.docx" for 192.168.1.251 at 2016-11-09 12:19:48 +0100
Processing WebDAV request: /dmsf/webdav/c1/dokument.docx (for 192.168.1.251 at 2016-11-09 12:19:48 +0100) [HEAD]
Completed in: 30 ms | 200 [https://localhost:3000/dmsf/webdav/c1/dokument.docx]
Started OPTIONS "/dmsf/webdav/c1/" for 192.168.1.251 at 2016-11-09 12:19:48 +0100
Processing WebDAV request: /dmsf/webdav/c1 (for 192.168.1.251 at 2016-11-09 12:19:48 +0100) [OPTIONS]
Completed in: 3 ms | 405 [https://localhost:3000/dmsf/webdav/c1]
Started LOCK "/dmsf/webdav/c1/dokument.docx" for 192.168.1.251 at 2016-11-09 12:19:48 +0100
Processing WebDAV request: /dmsf/webdav/c1/dokument.docx (for 192.168.1.251 at 2016-11-09 12:19:48 +0100) [LOCK]
Completed in: 0 ms | 401 [https://localhost:3000/dmsf/webdav/c1/dokument.docx]
Started GET "/dmsf/webdav/c1/dokument.docx" for 192.168.1.251 at 2016-11-09 12:19:48 +0100
Processing WebDAV request: /dmsf/webdav/c1/dokument.docx (for 192.168.1.251 at 2016-11-09 12:19:48 +0100) [GET]
Completed in: 0 ms | 401 [https://localhost:3000/dmsf/webdav/c1/dokument.docx]
Started GET "/dmsf/webdav/c1/dokument.docx" for 192.168.1.251 at 2016-11-09 12:19:48 +0100
Processing WebDAV request: /dmsf/webdav/c1/dokument.docx (for 192.168.1.251 at 2016-11-09 12:19:48 +0100) [GET]
Completed in: 0 ms | 401 [https://localhost:3000/dmsf/webdav/c1/dokument.docx]
Started GET "/dmsf/webdav/c1/dokument.docx" for 192.168.1.251 at 2016-11-09 12:19:48 +0100
Processing WebDAV request: /dmsf/webdav/c1/dokument.docx (for 192.168.1.251 at 2016-11-09 12:19:48 +0100) [GET]
Completed in: 0 ms | 401 [https://localhost:3000/dmsf/webdav/c1/dokument.docx]
```

**Comment by carlolars** [comment]
Can you add these two lines in the beginning of ResourceProxy.authenticate, rerun and post the log?
`Rails.logger.info {"ResourceProxy.authenticate: #{username.nil?} #{password.nil?}"}`
`Rails.logger.info {"ResourceProxy.authenticate: #{@request.user_agent}"} unless @request.user_agent.nil?`

I'm using Office 2014, I'll see if I can get hold of a computer with an earlier Office installed.

**Comment by picman** [comment]
```ruby
Started OPTIONS "/dmsf/webdav/c1/" for 192.168.1.251 at 2016-11-09 13:21:57 +0100
Processing WebDAV request: /dmsf/webdav/c1 (for 192.168.1.251 at 2016-11-09 13:21:57 +0100) [OPTIONS]
ResourceProxy.authenticate: true true
ResourceProxy.authenticate: Microsoft Office Protocol Discovery
Completed in: 20 ms | 405 [https://localhost:3000/dmsf/webdav/c1]
Started HEAD "/dmsf/webdav/c1/mwd.docx" for 192.168.1.251 at 2016-11-09 13:21:57 +0100
Processing WebDAV request: /dmsf/webdav/c1/mwd.docx (for 192.168.1.251 at 2016-11-09 13:21:57 +0100) [HEAD]
ResourceProxy.authenticate: true true
ResourceProxy.authenticate: Microsoft Office Existence Discovery
Completed in: 11 ms | 200 [https://localhost:3000/dmsf/webdav/c1/mwd.docx]
Started OPTIONS "/dmsf/webdav/c1/" for 192.168.1.251 at 2016-11-09 13:21:58 +0100
Processing WebDAV request: /dmsf/webdav/c1 (for 192.168.1.251 at 2016-11-09 13:21:58 +0100) [OPTIONS]
ResourceProxy.authenticate: true true
ResourceProxy.authenticate: Microsoft Office Existence Discovery
Completed in: 3 ms | 405 [https://localhost:3000/dmsf/webdav/c1]
Started LOCK "/dmsf/webdav/c1/mwd.docx" for 192.168.1.251 at 2016-11-09 13:21:58 +0100
Processing WebDAV request: /dmsf/webdav/c1/mwd.docx (for 192.168.1.251 at 2016-11-09 13:21:58 +0100) [LOCK]
ResourceProxy.authenticate: true true
ResourceProxy.authenticate: Microsoft Office Core Storage Infrastructure/1.0
Completed in: 0 ms | 401 [https://localhost:3000/dmsf/webdav/c1/mwd.docx]
Started GET "/dmsf/webdav/c1/mwd.docx" for 192.168.1.251 at 2016-11-09 13:21:59 +0100
Processing WebDAV request: /dmsf/webdav/c1/mwd.docx (for 192.168.1.251 at 2016-11-09 13:21:59 +0100) [GET]
ResourceProxy.authenticate: true true
ResourceProxy.authenticate: Microsoft Office Core Storage Infrastructure/1.0
Completed in: 0 ms | 401 [https://localhost:3000/dmsf/webdav/c1/mwd.docx]
Started GET "/dmsf/webdav/c1/mwd.docx" for 192.168.1.251 at 2016-11-09 13:21:59 +0100
Processing WebDAV request: /dmsf/webdav/c1/mwd.docx (for 192.168.1.251 at 2016-11-09 13:21:59 +0100) [GET]
ResourceProxy.authenticate: true true
ResourceProxy.authenticate: Microsoft Office Core Storage Infrastructure/1.0
Completed in: 0 ms | 401 [https://localhost:3000/dmsf/webdav/c1/mwd.docx]
Started GET "/dmsf/webdav/c1/mwd.docx" for 192.168.1.251 at 2016-11-09 13:21:59 +0100
Processing WebDAV request: /dmsf/webdav/c1/mwd.docx (for 192.168.1.251 at 2016-11-09 13:21:59 +0100) [GET]
ResourceProxy.authenticate: true true
ResourceProxy.authenticate: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; .NET CLR 1.1.4322; InfoPath.3; ms-office; MSOffice 14)
Completed in: 0 ms | 401 [https://localhost:3000/dmsf/webdav/c1/mwd.docx]
```

**Comment by carlolars** [comment]
This is really annoying.
I found a disc with Office 2007 that I installed on another computer, mounted the WebDAV share and tried to open a document. Nothing worked, Word tried to do GET with no user/pwd resulting in 401, same as you.
Unmounted the share and restarted the computer, mounted the share again and now Word 2007 is working! Maybe windows or office is caching something that were removed after the restart.

Anyways, I will try to find someone with Office 2010 installed at work tomorrow and see if I can get the same problem as you, as Office 2007 behaved different from both 2010 and 2014.

**Comment by carlolars** [comment]
I have now tested with Win7x64 and Office 2010 and it works.
Can you try to unmount your webdav and restart the computer and then mount again and test? That is how I think I solved the problem when it was not working for me yesterday.

**Comment by picman** [comment]
You're right. There must be some caching on Windows side. It was not working in my case even after re-mountig and computer restart. But, when I tried to mount a different project, it start working.

Great! I think we can close this issue. Thank you very much for your contribution to the plugin development.

**Comment by carlolars** [comment]
Great, thanks.
