### ISSUE TITLE
Approval workflows editing

### ISSUE THREAD

**Issue by mrazek** [danmunn/redmine_dmsf#590]
An error occurs when I try to edit Approval Workflows. Then I removed line
`<%= reorder_handle(@dmsf_workflow, :url => url_for(:action => 'edit', :id => @dmsf_workflow, :step => i) ) %>`
from `redmine_dmsf/app/views/dmsf_workflows/_steps.html.erb` and it seems, that it somehow works.

Using redmine 3.2.2 (database migrated from 2.5.3), dmsf 1.5.7 devel

Error message from production log is below.
`Processing by DmsfWorkflowsController#show as HTML
  Parameters: {"id"=>"16"}
  Current user: AAAA (id=3)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_steps.html.erb (83.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/show.html.erb within layouts/admin (83.4ms)
Completed 500 Internal Server Error in 96ms (ActiveRecord: 3.5ms)

ActionView::Template::Error (undefined method `reorder_handle' for #<#<Class:0x0000000903f2d8>:0x00000004ad3988>):
    62:             <% end %>
    63:           </td>
    64:           <td class="buttons">
    65: #            <%= reorder_handle(@dmsf_workflow, :url => url_for(:action => 'edit', :id => @dmsf_workflow, :step => i) ) %>
    66:             <%= delete_link edit_dmsf_workflow_path(@dmsf_workflow, :step => i) %>
    67:           </td>
    68:         </tr>
  plugins/redmine_dmsf/app/views/dmsf_workflows/_steps.html.erb:65:in `block in _plugins_redmine_dmsf_app_views_dmsf_workflows__steps_html_erb___1782623071555036781_75748740'
  plugins/redmine_dmsf/app/views/dmsf_workflows/_steps.html.erb:52:in `each'
  plugins/redmine_dmsf/app/views/dmsf_workflows/_steps.html.erb:52:in `_plugins_redmine_dmsf_app_views_dmsf_workflows__steps_html_erb___1782623071555036781_75748740'
  plugins/redmine_dmsf/app/views/dmsf_workflows/show.html.erb:19:in `_plugins_redmine_dmsf_app_views_dmsf_workflows_show_html_erb___4013172770624232475_75670920'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

**Comment by picman** [comment]
DMSF 1.5.7 requires Redmine >= 3.3.0.
