### ISSUE TITLE
modern upload file type don't work

### ISSUE THREAD

**Issue by kay54068** [danmunn/redmine_dmsf#593]
hi,
i use the modern type to upload is don't work
bug use classic work is fine.

Can you tell me how to fix it?

**Comment by picman** [comment]
Maybe, translate your text to English...
Then add some screen shots and corresponding production.log output.

**Comment by kay54068** [comment]
The production.log ...

Started GET "/plugin_assets/redmine_dmsf/javascripts/plupload/js/i18n/zh-tw.js" for 127.0.0.1 at 2016-11-04 17:58:40 +0800

ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dmsf/javascripts/plupload/js/i18n/zh-tw.js"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'


![image](https://cloud.githubusercontent.com/assets/3054544/20001484/58edb940-a2b7-11e6-8d14-d7a330811399.png)

**Comment by picman** [comment]
1. Try page reload
2. Try to change your Redmine language to English

**Comment by w0www** [comment]
Hello, i have this error too. 

I have tried page reaload, but not work
I have tried change language to English from spanish, not work.

**Comment by picman** [comment]
If you have such possibility, please try devel-1.5.9, whether the patch above fixes it.

**Comment by picman** [comment]
Any progress?

**Comment by picman** [comment]
No feedback => closed.
