### ISSUE TITLE
Working with WEBDAV redmine hangs

### ISSUE THREAD

**Issue by w0www** [danmunn/redmine_dmsf#597]
I have a netdrive as webdav and when i am uploading files and folders Redmine hangs and freezy. I only can restart apache to work again.

Why? Any solution?

**Comment by picman** [comment]
1. Check the plugin settings whether WeDAV is not set as read only.
2. Redmine/DMSF/Netdrive versions?
3. Post production.log part related to the issue.

**Comment by w0www** [comment]
1. My plugin settings is write and read.
2. The last version of netdrive, dmsf and redmine
3. My production log is:


Started PROPFIND "/dmsf/webdav/cliente-c-casa" for 192.168.4.140 at 2016-11-10 13:46:20 +0100
Processing WebDAV request: /dmsf/webdav/cliente-c-casa (for 192.168.4.140 at 2016-11-10 13:46:20 +0100) [PROPFIND]
Completed in: 66 ms | 401 [http://192.168.1.237/dmsf/webdav/cliente-c-casa]
Started PROPFIND "/dmsf/webdav/cliente-c-casa" for 192.168.4.140 at 2016-11-10 13:46:20 +0100
Processing WebDAV request: /dmsf/webdav/cliente-c-casa (for 192.168.4.140 at 2016-11-10 13:46:20 +0100) [PROPFIND]
Completed in: 775 ms | 207 [http://192.168.1.237/dmsf/webdav/cliente-c-casa]
Started PROPFIND "/dmsf/webdav/cliente-c-casa" for 192.168.4.140 at 2016-11-10 13:46:21 +0100
Processing WebDAV request: /dmsf/webdav/cliente-c-casa (for 192.168.4.140 at 2016-11-10 13:46:21 +0100) [PROPFIND]
Completed in: 125 ms | 207 [http://192.168.1.237/dmsf/webdav/cliente-c-casa]
Started PROPFIND "/dmsf/webdav/cliente-c-casa/Actas" for 192.168.4.140 at 2016-11-10 13:46:22 +0100
Processing WebDAV request: /dmsf/webdav/cliente-c-casa/Actas (for 192.168.4.140 at 2016-11-10 13:46:22 +0100) [PROPFIND]
Completed in: 120 ms | 207 [http://192.168.1.237/dmsf/webdav/cliente-c-casa/Actas]
Started PROPFIND "/dmsf/webdav/cliente-c-casa/Cuadro%20de%20Mando" for 192.168.4.140 at 2016-11-10 13:46:22 +0100
Processing WebDAV request: /dmsf/webdav/cliente-c-casa/Cuadro%20de%20Mando (for 192.168.4.140 at 2016-11-10 13:46:22 +0100) [PROPFIND]
Completed in: 54 ms | 207 [http://192.168.1.237/dmsf/webdav/cliente-c-casa/Cuadro%20de%20Mando]
Started PROPFIND "/dmsf/webdav/cliente-c-casa/Informes" for 192.168.4.140 at 2016-11-10 13:46:22 +0100
Processing WebDAV request: /dmsf/webdav/cliente-c-casa/Informes (for 192.168.4.140 at 2016-11-10 13:46:22 +0100) [PROPFIND]


I think that the conexion have some residual

**Comment by w0www** [comment]
Hello!!

The error was "bad conexion".

When I uploaded a lot of folders in webdav I restarted the server and then something crashed. I deleted the plugin and database and then reinstalled it
