### ISSUE TITLE
WebDAV: PROPFIND to "/" and "/dmsf" throws FATAL error

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#598]
When having the WebDAV folder mounted as a network share in windows then PROPFIND requests are sent for the paths "/" and "/dmsf" which results in a FATAL log entry "ActionController::RoutingError (No route matches [PROPFIND] "/dmsf"):".

**Comment by picman** [comment]
The same for OPTIONS:
```ruby
ActionController::RoutingError (No route matches [OPTIONS] "/"):
```

**Comment by picman** [comment]
Thinking about a solution, I'd add following routes into _routes.rb_:

```ruby
mount DAV4Rack::Handler.new(
    :root_uri_path => "#{Redmine::Utils::relative_url_root}/dmsf/webdav",
    :resource_class => RedmineDmsf::Webdav::ResourceProxy,
    :controller_class => RedmineDmsf::Webdav::Controller,
    :log_to => Rails.logger
  ), :at => '/', :via => :options

  mount DAV4Rack::Handler.new(
    :root_uri_path => "#{Redmine::Utils::relative_url_root}/dmsf/webdav",
    :resource_class => RedmineDmsf::Webdav::ResourceProxy,
    :controller_class => RedmineDmsf::Webdav::Controller,
    :log_to => Rails.logger
  ), :at => '/', :via => :propfind

  mount DAV4Rack::Handler.new(
    :root_uri_path => "#{Redmine::Utils::relative_url_root}/dmsf/webdav",
    :resource_class => RedmineDmsf::Webdav::ResourceProxy,
    :controller_class => RedmineDmsf::Webdav::Controller,
    :log_to => Rails.logger
  ), :at => '/dmsf', :via => :propfind
```

I've just tested it with the OPTION error which used to appear always after a folder is mounted in Windows and is gone now.

What do you think?

**Comment by carlolars** [comment]
Will that work for PROPFIND?
If I understand correctly '/' and '/dmsf' are mapped to /dmsf/webdav and the PROPFIND response will be that of '/dmsf/webdav' which include all the visible projects.

**Comment by picman** [comment]
And why not? I just redirect wrong requests _OPTIONS_ and _PROPFIND_ on _/_ and _/dmsf_ to the WebDAV engine.

```ruby
#
  # DAV4Rack implementation of Webdav
  dav_engine = DAV4Rack::Handler.new(
    :root_uri_path => "#{Redmine::Utils::relative_url_root}/dmsf/webdav",
    :resource_class => RedmineDmsf::Webdav::ResourceProxy,
    :controller_class => RedmineDmsf::Webdav::Controller,
    :log_to => Rails.logger
  )
  mount dav_engine, :at => '/dmsf/webdav'
  mount dav_engine, :at => '/', :via => :options
  mount dav_engine, :at => '/', :via => :propfind
  mount dav_engine, :at => '/dmsf', :via => :propfind
```

**Comment by carlolars** [comment]
Oh I see. Tested it now and it is actually a great fix, you can now mount the redmine root directory instead of having to go two folders down (/dmsf/webdav), so having the propfind for /dmsf is actually not needed if you only mount the root url.

Accessing the root (www.redmine.org/) from a browser will do a GET and get the normal webpage. To browse the webdav using a browser one must go to /dmsf/webdav/ and the dav_engine will respond to the GET.
Accessing the root from a webdav client will use the OPTIONS and PROPFIND requests, which are WebDAV specific, on which the dav_engine will respond. Can this cause a problem for the normal web site?

Here is a problem:
Create a project called "projects" (the project identifier must be "projects") and one project called "myfile" (the identifier must be "myfile").
Using a webdav client try to create a new file called _myfile_ in _/projects_.
The webdav engine will respond to the initial PROPFIND for /projects/myfile with 404 so the file does not already exist.
Then the webdav client then does a PUT on _/projects/myfile_ which is processed by the ProjectsController instead of the webdav engine...

So if a project identifier happens to get the same identifier as one of the sub-urls that redmine handles then there might be problems with GET and PUT.

**Comment by carlolars** [comment]
The mounted share gets the name "DavWWWRoot" when mounting the rooturl, is it possible to change this maybe?

**Comment by picman** [comment]
My intention was just prevent the FATAL errors. So maybe:

```ruby
def propfind
  return MethodNotAllowed unless @public_path.start_with?('/dmsf/webdav')
  ...
```

**Comment by carlolars** [comment]
You are right, keep it simple.

But, I tested the first part of your fix, with mapping the paths so that '/' and '/dmsf' got responses (incorrect but still valid responses). Then I restored the original routes.rb without that mapping and now windows does not do any more requests to '/' or '/dmsf'.

So the question is if MethodNotAllowed will satisfy windows, or if the responses must actually be correct responses.

**Comment by picman** [comment]
The problem is, that without the routes.rb fix, the propfind implementation is not reached and the FATAL error is thrown instead.

**Comment by picman** [comment]
> The mounted share gets the name "DavWWWRoot" when mounting the rooturl, is it possible to change this maybe?

_DavWWWRoot_ is a Windows keyword that tells Mini-Redirector that a WebDAV root folder is handled. It can't be changed, I'm afraid. Especially not on the WebDAV server side.

**Comment by willuhn** [comment]
@picman 

Regarding your comment on 2016-11-25 I had to change this (in lib/redmine_dmsf/webdav/controller.rb (line 81 in 1.5.9):

```ruby
def propfind
  return MethodNotAllowed unless @public_path.start_with?('/dmsf/webdav')
```
to:

```ruby
def propfind
  return MethodNotAllowed unless @public_path.start_with?(Redmine::Utils.relative_url_root + '/dmsf/webdav')
```
Otherwise all WebDAV requests will fail with HTTP/405 if Redmine is installed into a "sub" URI like (http://..../redmine)
