### ISSUE TITLE
indexer will not run

### ISSUE THREAD

**Issue by bluenevus** [danmunn/redmine_dmsf#601]
It ran previously and worked fine however, after the update to 1.5.8, indexer has this error.  I'm on redmine 3.3

root@redmine redmine/plugins# ruby redmine_dmsf/extra/xapian_indexer.rb -f
redmine_dmsf/extra/xapian_indexer.rb:428:in `system_or_raise': "/usr/bin/omindex -s english --db /var/www/redmine/files/dmsf_index/english /var/www/redmine/files --url /" failed (RuntimeError)
        from redmine_dmsf/extra/xapian_indexer.rb:481:in `block in <main>'
        from redmine_dmsf/extra/xapian_indexer.rb:462:in `each'
        from redmine_dmsf/extra/xapian_indexer.rb:462:in `<main>'

**Comment by picman** [comment]
Try it again and add _-v_ parameter in order to get more debug info.

**Comment by bluenevus** [comment]
Redmine environment [RAILS_ENV=production] correctly loaded ...

/usr/bin/omindex -s english --db /var/www/redmine/files/dmsf_index/english /var/www/redmine/files --url / -v

Exception: DatabaseCorruptError: Expected block 6 to be level 2, not 0

redmine_dmsf/extra/xapian_indexer.rb:426:in `system_or_raise': "/usr/bin/omindex -s english --db /var/www/redmine/files/dmsf_index/english /var/www/redmine/files --url / -v" failed (RuntimeError)

        from redmine_dmsf/extra/xapian_indexer.rb:481:in `block in <main>'

        from redmine_dmsf/extra/xapian_indexer.rb:462:in `each'

        from redmine_dmsf/extra/xapian_indexer.rb:462:in `<main>'

 

-- 

Vr, Frank

**Comment by bluenevus** [comment]
Deleted the database and reindex

 

Works fine now

 

sorry

 

-- 

Vr, Frank

 

From: Frank Tucker 
Sent: Tuesday, November 15, 2016 9:27 AM
To: 'danmunn/redmine_dmsf' <reply@reply.github.com>; danmunn/redmine_dmsf <redmine_dmsf@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [danmunn/redmine_dmsf] indexer will not run (#601)

 

 

 

Redmine environment [RAILS_ENV=production] correctly loaded ...

/usr/bin/omindex -s english --db /var/www/redmine/files/dmsf_index/english /var/www/redmine/files --url / -v

Exception: DatabaseCorruptError: Expected block 6 to be level 2, not 0

redmine_dmsf/extra/xapian_indexer.rb:426:in `system_or_raise': "/usr/bin/omindex -s english --db /var/www/redmine/files/dmsf_index/english /var/www/redmine/files --url / -v" failed (RuntimeError)

        from redmine_dmsf/extra/xapian_indexer.rb:481:in `block in <main>'

        from redmine_dmsf/extra/xapian_indexer.rb:462:in `each'

        from redmine_dmsf/extra/xapian_indexer.rb:462:in `<main>'

 

-- 

Vr, Frank
