### ISSUE TITLE
[1.5.8] Wrong file size detection for non English language

### ISSUE THREAD

**Issue by movcale** [danmunn/redmine_dmsf#605]
Hello,

If I use Russian as main Redmine language, then any uploaded file has size 2 bytes.
Nevertheless file uploaded and stored correctly.

See the same file uploaded in English
![eng](https://cloud.githubusercontent.com/assets/2082846/20427005/dc05f8f2-ad92-11e6-8d26-f3e12eea44bc.png)

in Russian
![rus](https://cloud.githubusercontent.com/assets/2082846/20427017/e5dfb66a-ad92-11e6-8bc1-277d80961f2a.png)

**Comment by picman** [comment]
I've just tested it iin 1.5.9 and it seems to be Okay. There was a bug in 1.5.8 when a new revision was created by uploading a new file content. The new size was wrongly reported as 2B then, independently on the real file size. However, it had nothing to do with the user's language. Please see #579.

![2016-11-22_13-00-05](https://cloud.githubusercontent.com/assets/779003/20523064/a41fd074-b0b3-11e6-86c1-a9822c674f6f.png)

**Comment by picman** [comment]
BTW. There is a few not yet translated texts in the Russian localization. Would you be as kind as to help me with a translation of following texts:

field_dmsf_tree_view: **Navigate folders in a tree**
label_classic: **Classic**
label_drag_drop: **Modern**
error_maximum_upload_filecount: **"No more than %{filecount} file(s) can be uploaded."**

**Comment by movcale** [comment]
Thank you for fix.

You may translate in the Russian as 
field_dmsf_tree_view: Навигация по папкам в виде дерева
label_classic: Обычный
label_drag_drop: Перетаскивание
error_maximum_upload_filecount: "Не более %{filecount} файла(ов) может быть загружено."

BTW, regarding "Navigate folders in a tree" feature. It does not work well for a big docs database. We have complex and big folders structure, so if that feature enabled, main dmsf page generation exceed server timeout. 
Maybe recursive subfolders scan should be restricted to 2-3 levels from current folder or something like this.

**Comment by picman** [comment]
It has been fixed too, in v1.5.8 I believe. Which version do you use?

**Comment by picman** [comment]
I've missed one more string:

label_title_format: Title format

**Comment by movcale** [comment]
label_title_format: Формат заголовка

p.s. I`ll check tree folder view in the latest version of dmsf.

**Comment by movcale** [comment]
Hi,

Could you please check this issue again.
I apply fix d7a0d8e on top of 1.5.8. So, when I upload a new file, size is correct.
But when I upload a new revision of existing file I again see file size as 2 byte.

**Comment by picman** [comment]
But, you must apply this fix:  	539daa5

**Comment by movcale** [comment]
correct my comment above, yes, I applied 539daa5

**Comment by picman** [comment]
I don't want to debug v1.5.8 and in v1.5.9 it seems to be working. Try to debug it yourself. Sorry.
