### ISSUE TITLE
DmsfFile.move_to does not update last_revision

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#606]
When moving a file the last_revision is not update but remains at the previous revision.

Example:
1. Create a file
Revisions:
r1 created...

2. Move file
Revisions:
r1 created...
r2 changed... "Moved from xxx"

After moving the file r1 is still the last revision instead of r2.

**Comment by picman** [comment]
Merged. Thank you.

**Comment by carlolars** [comment]
The fix is incomplete and ruins the trash bin, when deleting a file it reverts to the name from an old revision. 

But I still think there is something fishy about the revision numbering when moving files, imo the file revision should be the newest revision after a move.

**Comment by carlolars** [comment]
Alright, this fix is good. It is somewhere when deleting files that it goes wrong and it picks up an old revision.
