### ISSUE TITLE
Xapian search doesn't work

### ISSUE THREAD

**Issue by rodrigovalladares** [danmunn/redmine_dmsf#608]
Hello,

I have installed the plugin and uploaded some documents, and also configurated xapian_indexer.rb and executed the script. However, when I search for a word inside one of the documents that I've uploaded, the document isn't found. Is there any additional configuration to have xapian search work?

Thank you.

**Comment by picman** [comment]
1. Check the configuration values in xapian_indexer.rb.
2. Check  the configuration values related to Xapian in the plugin's settings.
3. Add -v argument to the indexer calling and check the result.
4. Do not forget to uncheck "Search titles only" while searching.
5. Check the production.log while searching.

**Comment by rodrigovalladares** [comment]
I change the stemming configuration to "Stem none" and now it works.

Thank you!
