### ISSUE TITLE
Revisions are sorted in the wrong order

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#611]
Revisions are sorted by major_version DESC, minor_version DESC and updated_at DESC.

When deleting a file or restoring it from the trash bin the _updated_at_ field is set to the same time for all revisions every time (most likely). 
So revisions that have the same major_version and minor_version, as they do after for example a rename in WebDAV or when manually creating revisions without changing the major or minor version, will actually get sorted by the id ascending causing the oldest revision to be sorted first which not correct.

I did a fix that instead only sorts by id DESC, I can not see why it should be sorted any other way.

**Comment by picman** [comment]
Thanks.
