### ISSUE TITLE
DMSF on Raspbian (question)

### ISSUE THREAD

**Issue by cereryman** [danmunn/redmine_dmsf#613]
Hi All,
I am currently running a simple setup for project management. A Raspberry pi 3 (model B) with Raspbian and Redmine 2.5.1.
I wanted to install the DMSF plugin but I realized it needs a newer version of Ruby and probably Redmine. So I was wondering if anyone here had managed this feat?
If so, which approach did you end up using? Upgrade the Redmine version? Change the DMSF version? Or use RVM and run different versions of Ruby?

Any help would appreciated. Just wondering if what I'm attempting is an impossible feat. :)

Cheers

**Comment by picman** [comment]
If you use an old Redmine, you must use an older version of DMSF to. v1.5.1 should be compatible with Redmine 2.5.x.
 https://github.com/danmunn/redmine_dmsf/releases/tag/v1.5.1
