### ISSUE TITLE
WebDAV caching (feedback)

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#614]
Hi
I have a few folders in a project that has 300-400 files and subfolders. When browsing these folders in the mounted share it took very long time for windows to show the content of the folders since every time I clicked a folder a new PROPFIND response was generated. So I started think about caching the response.

First step was to cache the PROPSTATS for each file which speed up the PROPFIND response generation (PROPFIND is build up of PROPSTATS for each file/folder in a directory).
The keys used for PROPSTATS were built from the path for folders and the id+revision for files, so when a file has a new revision the old cached value is automatically invalidated and will eventually be evicted from the cache.
This led to a speed up of one of my worst folders from 5.1 seconds down to 1.8 seconds when all PROPSTATS were in the cache. Pretty good but not enough.

Second step was to cache the entire PROPFIND response. Invalidation here is a bit trickier, but i overloaded the save method for files, folders and revisions so that when saving the cache entry for the parent folder is invalidated.
When rebuilding a PROPFIND response it uses the cached PROPSTATs for all files/folders that have not changed and only generates new PROPSTAT for modified files/folders.

The response time is now down to below 50 ms for PROPFIND and browsing the webdav share in windows is very smooth. 

I'm using the [memcached](https://github.com/memcached/memcached) server for caching so that the cached entries can be shared between processes.

I have pushed my current work to [WebDAV_Cache](https://github.com/carlolars/redmine_dmsf/commit/8ad48317349df4dbf6dfa7924e0f41ff1a3d2024), if you would have a look and maybe give me some feedback about the solution and implementation. I don't feel comfortable doing a PR yet since I was just finished today, but I will run the code next week on our server and see if it  works for us.

Update: Uploaded a cleaner branch with a single commit instead, easier to see all changes.

**Comment by picman** [comment]
Sounds promising. Go ahead.

**Comment by carlolars** [comment]
Just an update. We've been running this for more than week now with 5-10 active users. I have found one issue that I have not yet had the time to fix, I think I now what went wrong and it is easy to reproduce so it should not take long to fix. When that is done I'll wait a few more days to see if anything else emerges.
Hopefully I'll get some time this week to work on it, but since it is working "good enough" for our daily use the priority has dropped...

**Comment by picman** [comment]
Any progress?

**Comment by carlolars** [comment]
I just got back from my vacation today, I hope that I will be able to work on this later this week.
I have two open issues, but I think I have a robust solution to both.

**Comment by carlolars** [comment]
Fixed in #633

**Comment by picman** [comment]
I've just updated the localization. The new strings must be in all language files.
I've also tested it a little and it works. Great!
