### ISSUE TITLE
Install fails with methods_transplantable?

### ISSUE THREAD

**Issue by Brigithubert** [danmunn/redmine_dmsf#618]
Hi,

I am trying to move my old redmine system (Ubuntu 12.04.5 LTS, Redmine 2.5.2) to a new server (Ubuntu 16.04.1 LTS, Redmine 3.2.1). Unfortunately, I cannot install the dmsf plugin (identified v. 1.5.6 as the corresponding one).

I had to make a few adjustments (including commenting out ActionDispatch::XmlParamsParser in /redmine/config/application.rb:55). Now 
`bundle exec rake redmine:plugins:migrate RAILS_ENV="production"` fails with 
`NoMethodError: undefined method methods_transplantable? for Module:Class`.

Happy about any help
Nik

**Comment by picman** [comment]
Look here: http://apidock.com/rails/v4.1.8/Module/methods_transplantable%3F
```
methods_transplantable?() public
TODO: remove this after 1.9 support is dropped
```

I think your Rails + Redmine installation is not OK.
