### ISSUE TITLE
uploads silently failing using modern ui only

### ISSUE THREAD

**Issue by prost3tnik** [danmunn/redmine_dmsf#621]
seemed like uploads were broken with zero indication from logs. i tried an "old" upload - and it worked! with "modern ui" it would upload, files were stored on my servers /tmp directory - and thats all. no prompt for commit message, version etc.
and i found the cause (just by chance): in /settings?tab=api JSONP was disabled

so the bug is maybe a missing log entry or something

**Comment by picman** [comment]
I'm pretty sure that the "Modern UI" upload has nothing to do with JSONP option. There must have been another reason.

**Comment by prost3tnik** [comment]
i double checked and i can still upload. so you seem to be right. should have done that first, sorry for your time then. i dont have a clue what caused the broken uploads. but we are ok as its running fine atm and thanks for the plugin.
