### ISSUE TITLE
Option "Navigate folders in a tree" seems not to be saved

### ISSUE THREAD

**Issue by JL2014** [danmunn/redmine_dmsf#623]
Hi,

It seems that the option "Navigate folders in a tree" ("dmsf_tree_view"=>"1") is not saved when I check it and save in my account.

Greetings.

**Comment by picman** [comment]
It works fine for me. Can you provide any additional informations related to the issue? Eg. Redmine, version, DMS versions, production log,...

**Comment by Atmis** [comment]
Hi !
Same issue here !

Here is my configuration :
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x64-mingw32]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

DMSF 1.5.9

The value is here in the user_preferences table, but stay with 0 as a value :
` :dmsf_tree_view: '0'`

**Comment by picman** [comment]
It seems to be related to Redmine 3.4.

**Comment by picman** [comment]
Fixed.
