### ISSUE TITLE
Public URLs in email entries

### ISSUE THREAD

**Issue by picman** [danmunn/redmine_dmsf#626]
The email form will include an option to replace internal links with public ones.

**Comment by picman** [comment]
Done.

![public_urls](https://cloud.githubusercontent.com/assets/779003/21585607/e9a13ca2-d0c3-11e6-933c-36d4b0abb2a4.png)

**Comment by fahrplaner** [comment]
Dear Karel, is this feature implemented in 1.5.9? How does it work? Where do I find this option?

Cheers

**Comment by picman** [comment]
Yes, it is. When you sending a document(s) by email. A button in the document list header.
