### ISSUE TITLE
NoMethodError undefined method `mime_type'  (Can't post new version)

### ISSUE THREAD

**Issue by truelai** [danmunn/redmine_dmsf#627]
I am unable to post a new revision:

```
Started POST "/uploads.js?attachment_id=1&filename=scrum_note.odt&content_type=application%2Fvnd.oasis.opendocument.text" for 64.119.213.216 at 2017-01-03 20:58:07 +0000
Processing by AttachmentsController#upload as JS
  Parameters: {"attachment_id"=>"1", "filename"=>"scrum_note.odt", "content_type"=>"application/vnd.oasis.opendocument.text"}
  Current user: user (id=1)
Saving attachment '/home/ubuntu/redmine/files/2017/01/170103205807_scrum_note.odt' (139097 bytes)
  Rendered attachments/upload.js.erb (0.2ms)
Completed 200 OK in 20ms (Views: 0.8ms | ActiveRecord: 14.5ms)
Started POST "/dmsf/files/14/revision/create" for 64.119.213.216 at 2017-01-03 20:58:09 +0000
Processing by DmsfFilesController#create_revision as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"fake2b79f3873996334d4f1dc1aa1f623ebf2b79f3873996334d4f1dc1aa1f623ebf2b79f3873996334d4f1da1f", "dmsf_file_revision"=>{"title"=>"scrum notes", "name"=>"scrum_note.odt", "description"=>"", "comment"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."}, "version"=>"1", "custom_version_major"=>"2", "custom_version_minor"=>"76", "attachments"=>{"1"=>{"filename"=>"scrum_note.odt"}}, "commit"=>"Create", "id"=>"14"}
  Current user: user (id=1)
An attachment not found by its token: 
Completed 500 Internal Server Error in 17ms (ActiveRecord: 6.7ms)

NoMethodError (undefined method `mime_type' for nil:NilClass):
  plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:153:in `create_revision'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Environment:
  Redmine version                3.3.1.devel
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.1
  redmine_checklists             3.1.5
  redmine_contacts               4.0.4
  redmine_contacts_helpdesk      3.0.5
  redmine_dmsf                   1.5.8
  redmine_mentions               0.0.1

**Comment by truelai** [comment]
Also, thanks for creating a great plugin!

**Comment by picman** [comment]
This is the problem:
> An attachment not found by its token: 

1. Uploading attachments in Redmine works?
2. The path for document set in the plugin's setting exist and is writable for the web user?
3. Why do you upload via the classic Redmine interface and not via the modern one?

![upload](https://cloud.githubusercontent.com/assets/779003/21892467/5121d434-d8d7-11e6-96b0-71bfa3858e76.png)

**Comment by truelai** [comment]
Hey there. Sorry for the late response. I was on devel branch of Redmine. all is good now. Thanks again for the great plugin!

**Comment by picman** [comment]
Okay. No problem. Thanks for the update.
