### ISSUE TITLE
Disable versioning for certain files/file patterns

### ISSUE THREAD

**Issue by RealEnder** [danmunn/redmine_dmsf#630]
First, thanks for the great project!
We have this setup: DMSF enabled for a project and enabled webdav rw. Then using [Allway Sync](https://allwaysync.com/) we are doing webdav synchronizations over multiple computers, so the files are replicated on all computers (so everyone can work on them offline), then when there is connection to redmine server everything is synchronized(ala Dropbox). This works as expected, but Allway Sync (and other similar products) are using webdav stored _SYNCAPP/metadata.xml , which helps the tool to identify file changes. This file is written very often (depending on configuration) and produces a lot of unneeded revisions in redmine/DMSF database and unneeded file copies on the filesystem.
So is there a workaround to exclude certain files from revisions? This will be very useful for such scenarios.

**Comment by picman** [comment]
Done. Set the file name patterns in the plugin settings.

**Comment by carlolars** [comment]
I also wanted this feature, to disable versioning for file patterns.
What I was hoping for, and how I think @RealEnder meant was that some files should still be stored but without creating new revisions every time the file is saved.
Actually it is quite easy to implement the versioning disabling, the reusing of a revision is already implemented.
If you'd like I could give it a try.

But that being said, I do believe that the custom ignore file pattern is useful, previously which files that were ignored were hardcoded and could not be customized easily.

**Comment by RealEnder** [comment]
Hi, I've checked the solution and have two issues:
1. global ignore pattern prevents uploading (PUT operation). The idea was as @carlolars said to stop just versioning, but file have to still be written/read. This is still useful for temp files.
2. Trying to put a file, which is in the pattern currently yelds 404 error (tested with gnome client via ubuntu). The error log:

Started PROPFIND "/dmsf/webdav/test/test" for 10.240.0.103 at 2017-01-31 13:35:22 +0200
Processing WebDAV request: /dmsf/webdav/test/test (for 10.240.0.103 at 2017-01-31 13:35:22 +0200) [PROPFIND]
Completed in: 24 ms | 207 [http://ps-dev/dmsf/webdav/test/test]
Started PROPFIND "/dmsf/webdav/test/test" for 10.240.0.103 at 2017-01-31 13:35:22 +0200
Processing WebDAV request: /dmsf/webdav/test/test (for 10.240.0.103 at 2017-01-31 13:35:22 +0200) [PROPFIND]
Completed in: 10 ms | 207 [http://ps-dev/dmsf/webdav/test/test]
Started PROPFIND "/dmsf/webdav/test/test" for 10.240.0.103 at 2017-01-31 13:35:22 +0200
Processing WebDAV request: /dmsf/webdav/test/test (for 10.240.0.103 at 2017-01-31 13:35:22 +0200) [PROPFIND]
Completed in: 14 ms | 207 [http://ps-dev/dmsf/webdav/test/test]
Started PROPFIND "/dmsf/webdav/test/test/boza.txt" for 10.240.0.103 at 2017-01-31 13:35:22 +0200
Processing WebDAV request: /dmsf/webdav/test/test/boza.txt (for 10.240.0.103 at 2017-01-31 13:35:22 +0200) [PROPFIND]
Completed in: 10 ms | 404 [http://ps-dev/dmsf/webdav/test/test/boza.txt]
Started PUT "/dmsf/webdav/test/test/boza.txt" for 10.240.0.103 at 2017-01-31 13:35:22 +0200
Processing WebDAV request: /dmsf/webdav/test/test/boza.txt (for 10.240.0.103 at 2017-01-31 13:35:22 +0200) [PUT]
>>> WEBDAV_READ_WRITE
boza.txt ignored
Completed in: 15 ms | 204 [http://ps-dev/dmsf/webdav/test/test/boza.txt]
Started PROPFIND "/dmsf/webdav/test/test/boza.txt" for 10.240.0.103 at 2017-01-31 13:35:22 +0200
Processing WebDAV request: /dmsf/webdav/test/test/boza.txt (for 10.240.0.103 at 2017-01-31 13:35:22 +0200) [PROPFIND]
Completed in: 13 ms | 404 [http://ps-dev/dmsf/webdav/test/test/boza.txt]

**Comment by picman** [comment]
1) Okay. Let's keep it open, @carlolars will try to add an option to stop versioning. Please also keep the present version with disabling PUT for the given file names.

2) I think that 404 Not Found is okay when the application refuses to accept PUT request.
