### ISSUE TITLE
database migration error (from ver 0.9.1 to ver 1.5.8)

### ISSUE THREAD

**Issue by jackocleebrown** [danmunn/redmine_dmsf#632]
Upgrading a server to a new machine and migrating from Redmine 1.2.0.devel with DMSF 0.9.1 to Redmine 3.3.2.stable.16179 with DMSF 1.5.8

I restored the mysql database from a dump file taken on the old server and then tried to migrate the database using the command:

RAILS_ENV=production bundle exec rake redmine:plugins:migrate

This failed with the error attached log1.txt

I figured that the column project_id already existed and that was the issue, so I edited the file redmine_dmsf/db/migrate/06_dmsf_1_2_0.rb and commented out the line:
add_column :dmsf_file_revisions, :project_id, :integer, :null => true 

However, I then get another error (see log2.txt) since revision.dmsf_file doesn't exist.

Commenting out the whole section in redmine_dmsf/db/migrate/06_dmsf_1_2_0.rb allows the migrate to run successfully but I'm concerned that my database is not correct.

[log1.txt](https://github.com/danmunn/redmine_dmsf/files/705607/log1.txt)
[log2.txt](https://github.com/danmunn/redmine_dmsf/files/705612/log2.txt)

**Comment by picman** [comment]
Fixed.
