### ISSUE TITLE
File list behavior is inconsistent with redmine issue list

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#638]
In the redmine task lists, clicking the issue id or the issue subject both opens the same view (issue details).
In DMSF clicking the document id opens the document details but clicking the document title opens the actual document (or downloads it).

I think it would be better if both the document id and document title linked to the document details.

To download a document from the document list either make the filename a clickable link or add a download icon.

**Comment by picman** [comment]
I won't change the present behaviour as it's there since the beginning and nobody has claimed so far. I consider it as logical as it's implemented now.
