### ISSUE TITLE
Permission denied @ chown_internal after upgrade

### ISSUE THREAD

**Issue by wlmckeon** [danmunn/redmine_dmsf#640]
We were running redmine 2.4.7 with an old version of the dmsf plugin with everything working.  We recently upgraded to Redmine 3.3.2 using Ruby 2.3.3-p222 and Rails 4.2.7.1.  We decided to upgrade our version of dmsf as well to 1.5.8.  After the upgrade bonanza, everything seemed to be working until we tried to upload a document.  Now, we get the error "Permission denied @ chown_internal"  we haven't changed the permission on the paths or with the files.  That remained the same.  The files exist and people can pull the files down.  I don't know why we're now getting that error.

**Comment by picman** [comment]
It seems to me that your web server user is not allowed to change file permissions using chmod in your server file system. Please check.

app/controllers/dmsf_upload_controller.rb:
´´´
begin
      FileUtils.cp @tempfile.path, target
      FileUtils.chmod 'u=wr,g=r', target
    rescue Exception => e
      Rails.logger.error e.message
    end
´´´

**Comment by wlmckeon** [comment]
I've checked the permissions for the user everything has the proper permissions ( the temp file, the directory we're writing to, the process Passenger is running as).  One of my co workers did a little investigating and we believe that the problem is coming from the FileUtils.cp line that you noted above.  That makes an internal call to chown the file.  We don't know why that call is failing or why that call started failing on upgrade, but that seems to be the issue.

**Comment by picman** [comment]
You can try to comment out the chmod line. It should work without the line as well.

```ruby
begin
      FileUtils.cp @tempfile.path, target
      #FileUtils.chmod 'u=wr,g=r', target
rescue Exception => e
      Rails.logger.error e.message
end
```

**Comment by picman** [comment]
I keep this _chmod_ line in the code because files uploaded via the _plupload_ component haven't got read flag for group set while those uploaded via the standard Redmine upload form have.
It causes problems when another application want to read DMSF files on the disk.
I haven't found a better solution yet.
