### ISSUE TITLE
Unknown column 'dmsf_links.container_id'

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#642]
Starting from clean database, installed devel-1.5.9 and gets the following error when accessing DMSF via WebGUI:
```
Started GET "/projects/dmsf-test/dmsf" for 192.168.1.198 at 2017-01-31 22:28:50 +0100
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"dmsf-test"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 64ms (ActiveRecord: 22.1ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'dmsf_links.container_id' in 'where clause': SELECT COUNT(*) FROM `dmsf_links` WHERE `dmsf_links`.`deleted` = 1 AND `dmsf_links`.`container_id` = 1 AND `dmsf_links`.`container_type` = 'Project'):
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:691:in `get_display_params'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:51:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by carlolars** [comment]
Missing db migration script?

**Comment by picman** [comment]
Have you run the plugin migration task? There is a new migration script: https://github.com/danmunn/redmine_dmsf/blob/devel-1.5.9/db/migrate/20170118142001_dmsf_file_container.rb

**Comment by carlolars** [comment]
Yes I have run the plugin migration.
I don't see anything in the dmsf_file_container migration script that adds the container_id column to dmsf_links, only to dmsf_files.

**Comment by picman** [comment]
Yeah, I see. There're several bugs concerning the new container feature in the code. I will commit a fix tomorrow.
--
Karel Pičman

On 1 Feb 2017, at 17:17, carlolars <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes I have run the plugin migration.
I don't see anything in the dmsf_file_container migration script that adds the container_id column to dmsf_links, only to dmsf_files.

**Comment by picman** [comment]
Fixed.
