### ISSUE TITLE
Lock duration

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#648]
When a file is locked via webdav the lock duration is hardcoded to 1 hour by the dmsf webdav server.

This is a major problem for us since for example if you have a file open in Word and go on lunch break, when you get back Word still thinks that it has the lock but the lock has been released and Word fails to save the file, so the user must do _Save As_ to be able to save the file.

When locking via the WebUI then the lock duration is Infinite, any reasons that it shouldn't be Infinite when locking via webdav?

**Comment by picman** [comment]
I've no idea.
