### ISSUE TITLE
Cannot delete non-empty folders

### ISSUE THREAD

**Issue by axeloz** [danmunn/redmine_dmsf#649]
Hello, 

When trying to delete a folder I get an error message:
`Folder is not empty`

I cannot delete each child folder manually, there are too many... 
Is it a bug? 

Using DMSF 1.5.6	

Thanks

**Comment by picman** [comment]
No, that's a feature. You have to delete files in folders and then folders. Only empty folders can be deleted.

**Comment by axeloz** [comment]
That's a weird feature as it can become very painful when one has X levels of subfolders like I have. I have made some calculations : in my case I should navigate through at least 800 folders in order to delete their files, then delete the 800 folders one by one for finally being able to delete the root directory
...
