### ISSUE TITLE
Incomplete copy of a file to another project

### ISSUE THREAD

**Issue by rems4e** [danmunn/redmine_dmsf#651]
On Redmine 3.3.2 and DMSF 1.5.8, when I try to copy a file with some revisions from a project to another project, the revisions are not referenced in the new file.

Steps to reproduce:
* Create a file in Redmine
* Add one or more revision to this file in Redmine
* Copy this file to another project in Redmine

Expected:
* The copy has the same revisions count and details as the original

Actual:
* On the server filesystem, I can see that all the revisions files have been copied to the new projects (the last revision as well as all the old ones)
* But the copy has only one revision, namely the last one, shown in Redmine
* When I move the copy to the recycle bin, and empty it, only the last revision is removed from the server's filesystem. The old revisions are kept as files that I presume will be kept there forever.

**Comment by picman** [comment]
Fixed. However I've kept the original idea to copy the last revision only.

**Comment by rems4e** [comment]
If I understand well, this fix prevents the creation of the "ghost" files? And still only the last revision is copied ?

If so, would it be possible to add a feature to copy all the revisions history?

**Comment by picman** [comment]
Yes, exactly.

Okay, let's leave it as a feature request for a future release.

**Comment by rems4e** [comment]
OK, thanks!
