### ISSUE TITLE
Files without extension crashes webgui

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#656]
Uploading a file without an extension crashes the WebGUI when trying to show the file.

> Started GET "/projects/test/dmsf?folder_id=1" for 192.168.1.198 at 2017-02-10 20:01:29 +0100
> Processing by DmsfController#show as HTML
>   Parameters: {"folder_id"=>"1", "id"=>"test"}
>   Current user: admin (id=5)
>   Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.8ms)
>   Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (13.0ms)
>   Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (51.7ms)
>   Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (67.9ms)
> Completed 500 Internal Server Error in 248ms (ActiveRecord: 30.7ms)
> 
> ActionView::Template::Error (no implicit conversion of nil into String):
>     39:       :class => "icon icon-file #{DmsfHelper.filetype_css(file.name)}",
>     40:       :title => h(file.last_revision.try(:tooltip)),
>     41:       'data-downloadurl' => "#{file.last_revision.detect_content_type}:#{h(file.name)}:#{file_view_url}") %>
>     42:     <div class="dmsf_filename" title="<%= l(:title_filename_for_download)%>"><%= h(link ? link.path : file.display_name) %></div>
>     43:   </td>
>     44: <% end %>
>     45: <% if DmsfFolder.is_column_on?('extension') %>
>   plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:275:in `+'
>   plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:275:in `formatted_name'
>   plugins/redmine_dmsf/app/models/dmsf_file.rb:469:in `formatted_name'
>   plugins/redmine_dmsf/app/models/dmsf_file.rb:421:in `display_name'
>   plugins/redmine_dmsf/app/views/dmsf/_file.html.erb:42:in `_plugins_redmine_dmsf_app_views_dmsf__file_html_erb__2929490855154338163_38705780'
>   plugins/redmine_dmsf/app/views/dmsf/_list_view.erb:103:in `block in _plugins_redmine_dmsf_app_views_dmsf__list_view_erb__1619097318673136064_37895360'
>   plugins/redmine_dmsf/app/views/dmsf/_list_view.erb:97:in `_plugins_redmine_dmsf_app_views_dmsf__list_view_erb__1619097318673136064_37895360'
>   plugins/redmine_dmsf/app/views/dmsf/show.html.erb:107:in `block in _plugins_redmine_dmsf_app_views_dmsf_show_html_erb__4552531677669885650_36157580'
>   plugins/redmine_dmsf/app/views/dmsf/show.html.erb:85:in `_plugins_redmine_dmsf_app_views_dmsf_show_html_erb__4552531677669885650_36157580'
>   plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:59:in `block (2 levels) in show'
>   plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:57:in `show'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
> 
> 
>

**Comment by picman** [comment]
@carlolars We can close it. Can't we?

**Comment by carlolars** [comment]
Fixed in #657
