### ISSUE TITLE
Feature Request sync with other storage

### ISSUE THREAD

**Issue by therequest** [danmunn/redmine_dmsf#659]
it would be nice to add the ability to add some folder syncronisation options with other systems i.e. rsync, webdav, whatever.

my actual problem is, that we have another webdav, with another folder structure as a primary system and i want to get files from the other system to my project and publish them back, if there are some changes.
next problem is, that there is another linux fileserver, that has a further copy of the files and so my worst case: 3 different systems with 3 different file versions :(

so some sync option would be nice :)

**Comment by picman** [comment]
If you mount a DMSF folder via WebDAV, you can then synchronize it with another folder using _rsync_. However, I'd recommend using _cp --update_ instead as _rsync_ deletes the destination file first before updating and therefore breaks the versioning.
There are some bug fixes in v1.5.9 concerning rsync and cp, so rather test it in v1.5.9.

**Comment by therequest** [comment]
well, thanks for fast reply :)
that was my first idea, syncing both sides with a script using cp or rsync, i know that works with the webdav interface.
such similar option would also be cool in the webui (or something of store data remote and use the dmsf only for versioning), 'cause in my case so managers and windows admins use this tool also, and i don't believe they're able to handle some script options...

**Comment by picman** [comment]
This out of scope of this plugin, I'm afraid.

BTW who is not able to handle scriptwriting is not an admin.

**Comment by therequest** [comment]
👍 i totally agree...
okay so let's close this unicorn wishlist and get back to business
