### ISSUE TITLE
Installation error - activesupport requires Ruby version >= 2.2.2.

### ISSUE THREAD

**Issue by aws33** [danmunn/redmine_dmsf#661]
Hi all,

I get an installatio error following the set-up guide after performing 'bundle install' from within the plugin directory:
* /opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/

> Installing activesupport 5.0.1
> Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
> An error occurred while installing activesupport (5.0.1), and Bundler cannot continue.
> Make sure that `gem install activesupport -v '5.0.1'` succeeds before bundling.

As a result the DMSF plugin can't be used, the instance crashes.
I'am using Bitnami VM, Ubuntu 14.04, desktop installed, Redmine 3.3.x and the DMSF plugin 1.5.8

Any idea to fix this dependency ?

Thanks

**Comment by picman** [comment]
Bundle install should be run from the Redmine directory not the plugin directory. Please try it again.
