### ISSUE TITLE
Filter box missing in Debian redmine dmsf

### ISSUE THREAD

**Issue by tluu04** [danmunn/redmine_dmsf#666]
I have a redmine server (redmine bitnami v3.3.0) on my windows laptop and another redmine server (v3.3.1) on a debian linux machine, both with dmsf 1.5.8 installed.

When i access both dmsf redmine on my windows laptop, the bitnami dmsf shows a Filter box next to the Tag box whereas the debian dmsf only shows the Tag box.  

Is this a bug or normal?  how can i get the filter box to display?

Thong Luu

**Comment by picman** [comment]
Please provide some screen-shots.

**Comment by tluu04** [comment]
Here it is.

Thong Luu

![redmine_dmsf_filter_tl](https://cloud.githubusercontent.com/assets/25803800/23023023/a7a9c7fc-f421-11e6-81e1-e10069817f07.JPG)

**Comment by picman** [comment]
CSS file aren't obviously loaded on the right screen-shot:

1. Everything Okay on the Redmine info page?  /admin/info
2. All files in the Redmine folder are read-able for the webserver user? chown -R www-data:www-data *
3. Try to clear your web browser cache.
4. Check in the browser developer why the CSS files are not read.

**Comment by tluu04** [comment]
1. Everything looks OK on the info page (attached)
![dev2-admin_info-2](https://cloud.githubusercontent.com/assets/25803800/23024857/e2d77876-f429-11e6-8970-2a845a72c448.png)

2. All files are owned by www-data.www-data
3. done
4. The CSS files are read on one server and not the other (two screenshots above are both from the same browser).

**Comment by tluu04** [comment]
Per picman's suggestion, we updated the web-server configuration to allow access to the files in /var/cache/redmine/default/plugin_assets and the issue is resolved.  The view is the same as the windows redmine and also the drag and drop canvas.

Thank you
