### ISSUE TITLE
Number of selectable users for a step in the approval workflow design too small (only 10 are being displayed)

### ISSUE THREAD

**Issue by Mutniks** [danmunn/redmine_dmsf#668]
As the title says, only the first ten users of the redmine system are being displayed when a new approval workflow step is created (or am I missing something?). While other existing users can still be searched, this prevents from selecting all the users potentially needed in an "AND" or "OR" selection within a workflow step.
Potential solution: I changed the number "10" into "100" the following line in the file \plugins\redmine_dmsf\app\helpers\dmsf_workflows_helper.rb, thus increasing the selctable users from 10 to (up to) 100:
    principal_pages = Redmine::Pagination::Paginator.new principal_count, **100**, params['page']

Would be nice if a cleaner solution would be developed.

**Comment by picman** [comment]
Duplicated #662.
