### ISSUE TITLE
Notification button: confusing Tooltip Text 

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#678]
The tooltip text of the notification button always shows the following message:
**_"Notifications active: deactivate"_**

This is regardless of the actual state of the notifcations and it is quite confusing:

**Notifcations inactive:**

![dmsf-notifications-inactive](https://cloud.githubusercontent.com/assets/7224922/23123178/b1577b84-f767-11e6-8927-fcb4f31bfd83.png)

**Notifications active:**
![dmsf-notifications-active](https://cloud.githubusercontent.com/assets/7224922/23123223/d5cbefb8-f767-11e6-99e6-a551bd551c98.png)

**Comment by picman** [comment]
I can't reproduce your problem neither in 1.5.8 nor 1.5.9. Which version of DMSF do your use?

**Comment by mmundi72** [comment]
It 1.5.6 - if this is already solved in 1.5.8/1.5.9 then you can ignore the ticket and close it (we will probably upgrade to 1.5.9 as soon as it is officially published).
