### ISSUE TITLE
error installing plugin in redmine 3.3.2 bitnami VM

### ISSUE THREAD

**Issue by mnobler** [danmunn/redmine_dmsf#679]
Hi,
i need to install redmine_dmsf plugin in a new redmine 3.3.2 host: i downloaded bitnami redmine 3.3.2 virtual machine and i followed install instruction for redmine_dmsf plugin 1.5.8 but i encountered an error: what version of plugin can i install without having to upgrade the Ruby version?

_bitnami@ubuntu:~/apps/redmine/htdocs/plugins/redmine_dmsf$ bundle install --without xapian
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Installing concurrent-ruby 1.0.4
Installing i18n 0.8.1
Installing minitest 5.10.1
Installing thread_safe 0.3.6
Using tzinfo 1.2.2
Installing activesupport 5.0.1

Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
An error occurred while installing activesupport (5.0.1), and Bundler cannot continue.
Make sure that `gem install activesupport -v '5.0.1'` succeeds before bundling._

attached you can find environment infos.

thanks in advance

Marco Nobler

[bitnami-local-vm-gem-env.txt](https://github.com/danmunn/redmine_dmsf/files/799283/bitnami-local-vm-gem-env.txt)

**Comment by picman** [comment]
You should run the command from _~/apps/redmine/htdoc_. So the Redmine folder not the plugin folder.

**Comment by mnobler** [comment]
thank you for your feedback!

maybe i don't understand how "bundle install" works but, when i ran the command "bundle install --without xapian" from redmine root, this is the output:

[redmine_dmsf_installation_log_2.txt](https://github.com/danmunn/redmine_dmsf/files/804116/redmine_dmsf_installation_log_2.txt)

it's normal that the bundler install all that gems? I expected it will install only additional gems related to the redmine_dmsf plugin.

**Comment by picman** [comment]
Bundle install works with the current folder. So if you call it after Redmine installation and than again after adding a plugin, only these plugin related gems are added. Not only because of that you should always call it from the Redmine directory.

**Comment by mnobler** [comment]
ok, thanks a lot! now it works.
