### ISSUE TITLE
Config directory is 404?

### ISSUE THREAD

**Issue by aussieghostdog** [danmunn/redmine_dmsf#681]
Solved, clone the git directory, not download the master file 

I followed the information located  https://github.com/danmunn/redmine_dmsf. I must have done something wrong as after restarting the apache service, and going to the admin pane on Redmine there is 
![2017-02-27 15_25_14-administration](https://cloud.githubusercontent.com/assets/26053423/23349791/7dca1e08-fd01-11e6-9b42-89a2b6c4ab79.png)
In the plugins page I have 
![2017-02-27 15_29_24-plugins](https://cloud.githubusercontent.com/assets/26053423/23349981/f2849c68-fd02-11e6-9e58-33bce4f60ad8.png)

Clicking configure shows 
![2017-02-27 15_29_41-404](https://cloud.githubusercontent.com/assets/26053423/23349838/d941c204-fd01-11e6-8bdd-05a40a5f3c9f.png)
[install.txt](https://github.com/danmunn/redmine_dmsf/files/802722/install.txt)
install.txt contains all the commands that I ran
![2017-02-27 15_36_14-brisrdp - remote desktop connection](https://cloud.githubusercontent.com/assets/26053423/23349932/a132e4d2-fd02-11e6-90eb-985ea5cfe6ce.png)

and Redmine server info is 
![2017-02-27 15_37_41-information](https://cloud.githubusercontent.com/assets/26053423/23349951/c37a2b54-fd02-11e6-891f-edfdc7a7159b.png)

**Comment by picman** [comment]
What has happened? How have you fixed it?
