### ISSUE TITLE
Responsive view

### ISSUE THREAD

**Issue by imorales** [danmunn/redmine_dmsf#682]
Hi, 

first of all, thank for this great plugin, very useful for document management.

I raise a possible improvement ... what about visualization on mobile devices, responsive design?

Kin regards

**Comment by picman** [comment]
Maybe is not perfect, but Redmine has got some tuning for mobile devices. See a screen-shot from my phone:

![img_4233](https://cloud.githubusercontent.com/assets/779003/23500393/279cbc26-ff30-11e6-8f21-c71641c8ca24.PNG)

**Comment by imorales** [comment]
Hi Picman,

thank you for your reply. 
As you can see in the screenshot, the columns "Autor", "Workflow" and "Actions", the last one is the most important, doesn´t apper.
Is dificult to display html tables in a responsive desgin, so I think it coul´d be a very good improve, show all the columns developing and adaptative design.

Thanks again.

**Comment by picman** [comment]
Looks better now:
![screenshot-2018-2-9 dms - c1 - kdp 3 7 webrick](https://user-images.githubusercontent.com/779003/36029728-b7ba5cea-0da4-11e8-9e7a-43c3c831344c.png)
