### ISSUE TITLE
approval reminder problem

### ISSUE THREAD

**Issue by dskibarko** [danmunn/redmine_dmsf#683]
Upgrade to 1.5.9 DMSF secessfuly and then try to use alert approval firstly. 
Unfortunelly an issue appear and log with issue (screenshot) attached. 
This on Redmine 3.3.0 reproduced.
![dmsf_reminder_log](https://cloud.githubusercontent.com/assets/20500604/23587682/c336293a-01c2-11e7-842e-e1f4ca33309b.jpg)

**Comment by picman** [comment]
Fixed. Thank your for reporting this bug.

**Comment by dskibarko** [comment]
Try testing... No progress. 
Was changed file dmsf_alert_approvals.rake to new version (DMSF v1.5.9 based) and Redmine restarted.
Same issue reproduced. Have you any idea?

**Comment by picman** [comment]
Check the following commit for reference: 89d6ee7.

If you have checked out the master branch, it should be enough to run:

git pull
service apache2 restart

**Comment by eurodba** [comment]
Does it means, everyone who have installed **1.5.9-master**, should also download recent changes on top of it (**git pull**)?

**Comment by picman** [comment]
Yes.

**Comment by dskibarko** [comment]
May be start testing version 1.6.0-dev?

**Comment by picman** [comment]
No.

**Comment by dskibarko** [comment]
A new issue after fix update on screenshot
![capture_001_06032017_192614](https://cloud.githubusercontent.com/assets/20500604/23619319/58c0c7a8-02a4-11e7-85b3-a87a80e9d300.jpg)

**Comment by picman** [comment]
The problem is very probably in NULL values in the new columns of dmsf_workflow table. Please update your database as follows (MySQL version):

```sql
UPDATE dmsf_workflows SET created_on = now(), updated_on = now(), author_id = (SELECT id FROM users WHERE admin LIMIT 1) WHERE created_on IS NULL;
```

**Comment by dskibarko** [comment]
Ok! Fine working now! Thanks
