### ISSUE TITLE
Long response time on Editing an Issue

### ISSUE THREAD

**Issue by therequest** [danmunn/redmine_dmsf#684]
After i've upgaded to 1.5.9 i am getting long response times, when i am editing or creating an new issue.
I can't find any interesting entry at the logging, but i've only upgraded the dmsf and could reproduce this on some other instances.
It would be nice to check this...

**Comment by therequest** [comment]
I am using redmine 3.3.1 and a postgres db

**Comment by picman** [comment]
Hm, that's strange. There are some hooks implemented in DMSF which might cause it. Could you provide a log where we can see how long do requests take? 

E.g.

INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_files/_links.html.erb (**0.1ms**)
INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (**1.5ms**)
INFO -- :   Rendered issues/_form.html.erb (198.6ms)
INFO -- :   Rendered attachments/_form.html.erb (1.8ms)
INFO -- :   Rendered issues/_edit.html.erb (208.8ms)
INFO -- :   Rendered issues/_sidebar.html.erb (1.9ms)
INFO -- :   Rendered watchers/_watchers.html.erb (2.6ms)

**Comment by eurodba** [comment]
Or try to use a bit more complex approach, which maybe will help you in the future too or with more complex cases - install plugin **RM+ Devtools**: http://rmplus.pro/en/redmine/plugins/rmplus_devtools. According to description, it provides, between other features, possibility to monitor and catch duration of each request or render time. I have not tested it, so, all mentioned above - from plugin's description.

**Comment by therequest** [comment]
hmm okay, stange ...
i raised the logging to debug and could resolve the problem -> some notification plugin cause the timeouts.
DMSF is fine.

i hate mondays -.-
