### ISSUE TITLE
Problem deleting plugin

### ISSUE THREAD

**Issue by imorales** [danmunn/redmine_dmsf#685]
With Redmine 3.3.0, i installed Plugin v1.5.8, works correct.
After install v1.5.9 of the plugin a problem occurs, and then trying to uninstall the plugin the exception is:

sistemas@gesproyec:/usr/local/redmine/plugins$ bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf VERSION=0 RAILS_ENV=production
(in /usr/local/redmine-3.3.0)
Migrating redmine_dmsf (DMSF)...
== 20141013102501 RemoveProjectFromRevision: reverting ========================
-- add_column(:dmsf_file_revisions, :project_id, :integer, {:null=>true})
   -> 0.0013s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `project_id' for #<DmsfFile:0x00000004951d58>
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:433:in `method_missing'
/usr/local/redmine-3.3.0/plugins/redmine_dmsf/db/migrate/20141013102501_remove_project_from_revision.rb:31:in `block in down'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/relation/batches.rb:51:in `each'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/relation/batches.rb:51:in `block in find_each'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/relation/batches.rb:50:in `find_each'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/querying.rb:9:in `find_each'
/usr/local/redmine-3.3.0/plugins/redmine_dmsf/db/migrate/20141013102501_remove_project_from_revision.rb:29:in `down'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:611:in `exec_migration'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:591:in `block in migrate'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:590:in `migrate'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:768:in `migrate'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:1044:in `ddl_transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:959:in `block in migrate'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:955:in `each'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:955:in `migrate'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:830:in `down'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:805:in `migrate'
/usr/local/redmine-3.3.0/lib/redmine/plugin.rb:481:in `migrate_plugin'
/usr/local/redmine-3.3.0/lib/redmine/plugin.rb:453:in `migrate'
/usr/local/redmine-3.3.0/lib/redmine/plugin.rb:464:in `migrate'
/usr/local/redmine-3.3.0/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by imorales** [comment]
Trying to install again and updating:

sistemas@gesproyec:/usr/local/redmine/plugins$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /usr/local/redmine-3.3.0)
Migrating redmine_cas (Redmine CAS)...
Migrating redmine_dmsf (DMSF)...
== 20141015132701 RemoveFolderFromRevision: migrating =========================
-- remove_column(:dmsf_file_revisions, :dmsf_folder_id)
   -> 0.0014s
== 20141015132701 RemoveFolderFromRevision: migrated (0.0017s) ================

== 20141205143001 RemoveUniquenessFromWf: migrating ===========================
-- index_exists?(:dmsf_workflows, :name)
   -> 0.0023s
== 20141205143001 RemoveUniquenessFromWf: migrated (0.0025s) ==================

== 20150120152101 NotificationsNullable: migrating ============================
-- change_column(:projects, :dmsf_notification, :boolean, {:default=>false, :null=>true})
   -> 0.0040s
-- change_column(:dmsf_folders, :notification, :boolean, {:default=>false, :null=>true})
   -> 0.0026s
-- change_column(:dmsf_files, :notification, :boolean, {:default=>false, :null=>true})
   -> 0.0027s
== 20150120152101 NotificationsNullable: migrated (0.0098s) ===================

== 20150130052716 AddExternal: migrating ======================================
-- change_column(:dmsf_links, :target_id, :integer, {:null=>true})
   -> 0.0010s
-- add_column(:dmsf_links, :external_url, :string, {:null=>true})
   -> 0.0007s
== 20150130052716 AddExternal: migrated (0.0021s) =============================

== 20150202010301 AddUserToLinks: migrating ===================================
-- add_column(:dmsf_links, :user_id, :integer)
   -> 0.0008s
== 20150202010301 AddUserToLinks: migrated (0.0011s) ==========================

== 20151020141801 LargeFiles: migrating =======================================
-- change_column(:dmsf_file_revisions, :size, :bigint, {:null=>true})
   -> 0.0288s
== 20151020141801 LargeFiles: migrated (0.0290s) ==============================

== 20151209100001 TitleFormat: migrating ======================================
-- add_column(:members, :title_format, :text, {:null=>true, :limit=>100})
   -> 0.0010s
== 20151209100001 TitleFormat: migrated (0.0013s) =============================

== 20160215125801 ApprovalWorkflowStatus: migrating ===========================
-- add_column(:dmsf_workflows, :status, :integer, {:null=>false, :default=>1})
   -> 0.0174s
== 20160215125801 ApprovalWorkflowStatus: migrated (0.0367s) ==================

== 20160217133001 StatusDeleted: migrating ====================================
-- change_column(:dmsf_folders, :deleted, :boolean, {:default=>nil})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DatatypeMismatch: ERROR:  column "deleted" cannot be cast automatically to type boolean
HINT:  You might need to specify "USING deleted::boolean".
: ALTER TABLE "dmsf_folders" ALTER COLUMN "deleted" TYPE boolean
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/schema_statements.rb:448:in `change_column'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:665:in `block in method_missing'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:634:in `block in say_with_time'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:634:in `say_with_time'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:654:in `method_missing'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:416:in `method_missing'
/usr/local/redmine-3.3.0/plugins/redmine_dmsf/db/migrate/20160217133001_status_deleted.rb:33:in `up'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:571:in `up'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:611:in `exec_migration'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:591:in `block in migrate'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:590:in `migrate'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:768:in `migrate'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:1044:in `ddl_transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:959:in `block in migrate'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:955:in `each'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:955:in `migrate'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:823:in `up'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/activerecord-4.2.6/lib/active_record/migration.rb:801:in `migrate'
/usr/local/redmine-3.3.0/lib/redmine/plugin.rb:481:in `migrate_plugin'
/usr/local/redmine-3.3.0/lib/redmine/plugin.rb:453:in `migrate'
/usr/local/redmine-3.3.0/lib/redmine/plugin.rb:467:in `block in migrate'
/usr/local/redmine-3.3.0/lib/redmine/plugin.rb:466:in `each'
/usr/local/redmine-3.3.0/lib/redmine/plugin.rb:466:in `migrate'
/usr/local/redmine-3.3.0/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
/home/sistemas/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate

**Comment by picman** [comment]
Fixed.

**Comment by imorales** [comment]
Thanks Picma.

How can I probe it? I have to wait untill 1.6.0 ?

**Comment by picman** [comment]
No, it's been committed to the master branch. So either _git pull_ or download zip version

**Comment by imorales** [comment]
Hi Picman, 

I installed the master branch, and everything is OK, the problema is when trying to access, the error occurs whit the gem dalli: 

[ 2017-03-07 10:22:35.1700 5882/7f647862a700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-4] Cannot checkout session because a spawning error occurred. The identifier of the error is 0b943bec. Please see earlier logs for details about the error.
App 6334 stdout:
App 6334 stdout:
[ 2017-03-07 10:22:41.1689 5882/7f6477628700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /usr/local/redmine: An error occurred while starting up the preloader.
  Error ID: cd2bb19c
  Error details saved to: /tmp/passenger-error-ncIudC.html
  Message from application: <p>It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:</p>

  <pre class="commands">bundle install</pre>

<p>If that didn't work, then the problem is probably caused by your application being run under a different environment than it's supposed to. Please check the following:</p>

<ol>
  <li>Is this app supposed to be run as the <code>sistemas</code> user?</li>
  <li>Is this app being run on the correct Ruby interpreter? Below you will
      see which Ruby interpreter Phusion Passenger attempted to use.</li>
  <li>Please check whether the correct RVM gemset is being used.</li>
  <li>Sometimes, RVM gemsets may be broken.
      <a href="https://github.com/phusion/passenger/wiki/Resetting-RVM-gemsets">Try resetting them.</a></li>
</ol>

<p>-------- The exception is as follows: -------</p>
Your bundle is locked to dalli (2.7.6), but that version could not be found in any of the sources listed in your Gemfile. If you haven&#39;t changed sources, that means the author of dalli (2.7.6) has removed it. You&#39;ll need to update your bundle to a different version of dalli (2.7.6) that hasn&#39;t been removed in order to install. (Bundler::GemNotFound)
<pre>  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `&lt;top (required)&gt;&#39;
  /home/sistemas/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require&#39;
  /home/sistemas/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:297:in `block in run_load_path_setup_code&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:435:in `running_bundler&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:296:in `run_load_path_setup_code&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:100:in `preload_app&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:156:in `&lt;module:App&gt;&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:30:in `&lt;module:PhusionPassenger&gt;&#39;
  /home/sistemas/.rvm/gems/ruby-2.3.0/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:29:in `&lt;main&gt;&#39;</pre>


[ 2017-03-07 10:22:41.1738 5882/7f647862a700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-5] Cannot checkout session because a spawning error occurred. The identifier of the error is cd2bb19c. Please see earlier logs for details about the error.


My list gem is:
*** LOCAL GEMS ***

actionmailer (4.2.6)
actionpack (4.2.6)
actionpack-action_caching (1.1.1)
actionpack-xml_parser (1.0.2)
actionview (4.2.6)
activejob (4.2.6)
activemodel (4.2.6)
activerecord (4.2.6)
activesupport (4.2.6)
addressable (2.5.0, 2.4.0)
arel (6.0.3)
bigdecimal (1.2.0)
builder (3.2.2)
bundler (1.13.6)
bundler-unload (1.0.2)
coderay (1.1.1)
concurrent-ruby (1.0.2)
css_parser (1.4.6, 1.3.7)
dalli (2.7.6)
dav4rack (0.3.0)
erubis (2.7.0)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
globalid (0.3.7)
htmlentities (4.3.1)
i18n (0.7.0)
io-console (0.4.2)
jquery-rails (3.1.4)
json (1.8.3, 1.7.7)
loofah (2.0.3)
mail (2.6.4)
mime-types (3.1, 2.99.3)
mime-types-data (3.2016.0521)
mimemagic (0.3.2)
mini_portile2 (2.1.0)
minitest (5.9.1, 5.9.0, 4.3.2)
net-ldap (0.12.1)
nokogiri (1.6.8.1, 1.6.8)
pg (0.18.4)
pkg-config (1.1.7)
protected_attributes (1.1.3)
psych (2.0.0)
public_suffix (2.0.4)
rack (1.6.5, 1.6.4)
rack-openid (1.4.2)
rack-test (0.6.3)
rails (4.2.6)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.3)
railties (4.2.6)
rake (11.3.0, 11.2.2, 0.9.6)
rbpdf (1.19.0)
rbpdf-font (1.19.0)
rdoc (4.0.0)
redcarpet (3.3.4)
request_store (1.0.5)
rmagick (2.16.0)
roadie (3.2.0, 3.1.1)
roadie-rails (1.1.1)
ruby-openid (2.3.0)
rubycas-client (2.3.10.rc1)
rubygems-bundler (1.4.4)
rubyzip (1.2.0)
rvm (1.11.3.9)
simple_enum (2.3.0)
sprockets (3.7.0)
sprockets-rails (3.2.0)
test-unit (2.0.0.0)
thor (0.19.1)
thread_safe (0.3.5)
tzinfo (1.2.2)
uuidtools (2.1.5)
xapian-full-alaveteli (1.2.21.1)
zip-zip (0.3)

**Comment by picman** [comment]
> Your bundle is locked to dalli (2.7.6), but that version could not be found in any of the sources listed in your Gemfile.

I see no relation to DMSF, I'm afraid.

**Comment by imorales** [comment]
Thanks again for your response. 

But, when i move the plugin directory (plugins/redmine_dmsf) to anotherone or I delete it, the problem not occurs and the Redmine is working fine.

**Comment by picman** [comment]
Oops, I see it now. Somebody has added Dalli to the DMSF dependencies.

Try to remove Gemfile.lock file and then run _bundle install_ again.

**Comment by picman** [comment]
No feedback for more than one month => closing.
