### ISSUE TITLE
Not sorting correctly by the column title

### ISSUE THREAD

**Issue by imorales** [danmunn/redmine_dmsf#687]
Hi Picman,

as you can see in the image the plugin is not sorting by title column correctly.

Can you check it? Thank you.
![title_sort](https://cloud.githubusercontent.com/assets/2647291/23741674/9537f23e-04a1-11e7-8edd-222cc2608412.png)

**Comment by picman** [comment]
I can't reproduce your problem, I'm afraid. What version of DMSF do you use? Can you test it a little further in order to find a possible cause of the problem? E.g. Switch your user interface to English and back to Spain (I guess) or to change the sort direction, another column sort,...

![image](https://cloud.githubusercontent.com/assets/779003/23787901/8500a5cc-0574-11e7-9129-ce2685191741.png)

**Comment by imorales** [comment]
OK, i will test better.

**Comment by imorales** [comment]
We are using v1.5.9, we changed to english interface ant still not sorting correctly, we changed the sort direction and same ... I atach you and screencapture.
![sort_problem](https://cloud.githubusercontent.com/assets/2647291/24501855/36b5d160-1543-11e7-97a1-2b4dedbf60ee.png)

**Comment by Rodrigosalasv** [comment]
Hello,
I have the same issue with the version1.5.9.
Same tests, language modification and sort and still the same issue.

Thak you

![error](https://cloud.githubusercontent.com/assets/27017278/24807551/f04293e0-1bb8-11e7-91e5-e9678cf3f8ce.png)

**Comment by Brigithubert** [comment]
Same problem here. My list of folders used to be in correct order until I created some subfolders within one of them.

Before:
100 Level 1
200 Level 2
300 Level 3
400 Level 4

After:
100 Level 1
300 Level 3
400 Level 4
200 Level 2

**Comment by Rodrigosalasv** [comment]
Hello,

We noticed today that the sorting of the name in DMSF works well when we use IE or Edge.
But it's still not working with Chrome or Firefox.
Do you have any idea?

**Comment by darksoul42** [comment]
Hello,

We actually also hit this bug (on DMSF 1.5.9), and found out that the sorting function in JavaScript seems to mess up when there is a newline in the Description field. That's probably why it works differently based on the browser.

**Comment by Brigithubert** [comment]
Respect -- that seems to solve the problem!

**Comment by Rodrigosalasv** [comment]
I don't think that the problem is solved.
I need description on my folders and users use different browsers.
But it's true, on Firefox and Chrome the sorting is done by the number of lines in description.
I checked that today

**Comment by xJom** [comment]
This seem to be a bug in Firefox and Chrome, so you should file the bug there instead. There is a competition between browsers for sorting, and there seems to be suboptimizations in Firefox and Chrome to be as fast as possible in those tests, which make them fail at sorting numbers in strings.
https://stackoverflow.com/questions/15084070/is-this-a-bug-in-array-sort

**Comment by Rodrigosalasv** [comment]
Hello,

I noticed that in my redmine, this bug did not come from DMSF but from the theme I use. (Circle)
With other themes this bug does not exist.
By checking the box "**Navigate folders in a tree**" in **My account**, the display is corrected

![capture](https://user-images.githubusercontent.com/27017278/33546986-da84925a-d8e2-11e7-8ffd-73fbfcba1def.PNG)

**Comment by picman** [comment]
I've just upgraded DataTables library responsible for sorting. Please try v1.6.1. I will reopen it if the problem persists.

**Comment by picman** [comment]
The problem is caused by folder descriptions and is still there.

**Comment by picman** [comment]
Fixed.
