### ISSUE TITLE
Enabling project names when already using webdav cache cause faulty folders

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#688]
Enabling the project names for the webdav project folders when the webdav cache already is enabled and have been running can cause the webdav to show faulty folder lists.
Problems that I have noticed is that a folder lists itself as a subfolder and not all folders and files are visible.

The quick fix is to just clear the cache after enabling project names.

**Comment by picman** [comment]
I don't understand. So if anybody enables the project names for WebDAV, they should ran the rake task?

**Comment by picman** [comment]
Wouldn't it be better to override SettingsController::plugin? E.g.:
```ruby
def plugin_with_clear_cache
  if @plugin == dmsf && project_names_has_just_been_enabled && cache_enabled
    cache.clear
  end
  plugin_without_cache
end
```

BTW, If you're adding a new file, put your name in the copyright section. It's your work :-)

**Comment by carlolars** [comment]
> Wouldn't it be better to override SettingsController::plugin?
Yes it would, if it is always required.
But it should not be required to clear the cache, there must be something that I've missed but I don't have the time to investigate right now. So the quickest fix for us to be able to use it was to clear the cache, and it seems to have done the trick since no one has complained. Yet...

So if you accept the merge request at least there is a way for others to use the cache along with project names until a proper solution has been found.

**Comment by picman** [comment]
Okay
