### ISSUE TITLE
Handeling files that contains #

### ISSUE THREAD

**Issue by therequest** [danmunn/redmine_dmsf#690]
Hmm okay, now i've found an new problem: the dmsf is unable to handle files, that contains a # in the name.

Bug or Feature?

**Comment by picman** [comment]
It's a feature. Here is a list of invalid characters:

```ruby
INVALID_CHARACTERS = /\A[^\/\\\?":<>#%\*]*\z/.freeze
```

**Comment by therequest** [comment]
Well, thx, i've to add them to my sync script and everything is fine
