### ISSUE TITLE
redmine:dmsf_convert_documents 

### ISSUE THREAD

**Issue by yurix1975** [danmunn/redmine_dmsf#693]
hi guys,
a disturbing problem,after installed the plugin , i 've tried to migrate my document using the task
but i got this error.  here with dmsf 1.5.9 + redmine 3.3.1

 rake --trace redmine:dmsf_convert_documents project=395 dry=false RAILS_ENV="production"
** Invoke redmine:dmsf_convert_documents (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:dmsf_convert_documents
Processing project: XXXXXXXXXXXXXXXXXXXXXXXXX
Processing document: XXXXXXXXXXXXXXXXXXXXXXXXX
Created folder: XXXXXXXXXXXXXXXXXXXXXXXXX
Creating file: SIS_XXXXXXXXXXXXXXXXXXXXXXXXX_1.0.doc failed
undefined method `project=' for #<DmsfFile:0x007fba6f4fe698>
Processing document: XXXXXXXXXXXXXXXXXXXXXXXXX
rake aborted!
NameError: uninitialized constant DmsfConvertDocuments::Users
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:75:in `block (2 levels) in convert'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:65:in `block in convert'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:57:in `each'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:57:in `convert'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:205:in `block (2 levels) in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/rake:23:in `load'
/opt/bitnami/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine:dmsf_convert_documents

**Comment by picman** [comment]
Fixed. Just git pull the master branch.

**Comment by lonestonewy** [comment]
[root@iZ23gyg9np7Z pro.bjhacf.org]# rake redmine:dmsf_convert_documents project=qa dry=true RAILS_ENV="production" --trace
/usr/local/lib/ruby/gems/2.2.0/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
** Invoke redmine:dmsf_convert_documents (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:dmsf_convert_documents
Processing project: QA报告
Processing document: QA报告
rake aborted!
NameError: uninitialized constant DmsfConvertDocuments::Users
/alidata1/wwwroot/pro.bjhacf.org/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:75:in `block (2 levels) in convert'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/alidata1/wwwroot/pro.bjhacf.org/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:65:in `block in convert'
/alidata1/wwwroot/pro.bjhacf.org/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:57:in `each'
/alidata1/wwwroot/pro.bjhacf.org/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:57:in `convert'
/alidata1/wwwroot/pro.bjhacf.org/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:205:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:dmsf_convert_documents

**Comment by picman** [comment]
Yeah, that's a bug. Fixed. Thank you for reporting that.
