### ISSUE TITLE
redmine:dmsf_convert_documents 

### ISSUE THREAD

**Issue by yurix1975** [danmunn/redmine_dmsf#694]
thanks for the previuos fix. 
this error remains.....i bet it's my fault:

rake --trace redmine:dmsf_convert_documents project=395 dry=false RAILS_ENV="production"
** Invoke redmine:dmsf_convert_documents (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:dmsf_convert_documents
Processing project: XXXXXXXXXXXXXXXXXXXXXXXXX
Processing document: XXXXXXXXXXXXXXXXXXXXXXXXX
Created folder: XXXXXXXXXXXXXXXXXXXXXXXXX
Created file: XXXXXXXXXXXXXXXXXXXXXXXXX_1.0.doc
Processing document: XXXXXXXXXXXXXXXXXXXXXXXXX
rake aborted!
NameError: uninitialized constant DmsfConvertDocuments::Users
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:75:in `block (2 levels) in convert'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:65:in `block in convert'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:57:in `each'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:57:in `convert'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:205:in `block (2 levels) in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/rake:23:in `load'
/opt/bitnami/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine:dmsf_convert_documents

**Comment by picman** [comment]
Hm, something wrong with your installation probably. Do you run the rake task from the Redmine folder? How about *bundle exec rake redmine:dmsf_convert_documents...*?
