### ISSUE TITLE
Move dmsf documents

### ISSUE THREAD

**Issue by imorales** [danmunn/redmine_dmsf#696]
The plugin allow using "dmsf_convert_documents" to migrate documents from the Documents module to the DMSF module, but it would be interesting if the script allows you to specify the destination DMSF module (different project) and even the current folder within a project.

Example:

`rake redmine:dmsf_convert_documents project=test destination_project=ID destinatio_folder=ROUTE RAILS_ENV="production"`

Would it be possible?

**Comment by picman** [comment]
The purpose of the rake task is to reorganize files to the new disk folder structure. The disk folder structure has been changed from one common folder to more folders reflecting projects.  Their project and folder database structure remain unchanged. It's and old rake task which should have been used during a single DMSF upgrade in the past and shouldn't be used any more.
