### ISSUE TITLE
install error: LoadError: cannot load such file -- addressable/uri 

### ISSUE THREAD

**Issue by u2mike** [danmunn/redmine_dmsf#698]
hello 

my current redmine stack is 3.1.1 and i wanted to update to current redmine_dmsf version 1.5.9
(from 1.5.3 i think)
now i get an error during migration job:  bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
LoadError: cannot load such file -- addressable/uri

is there a change to upgrade or is it needed to upgrade to 3.3.x before?
OR how can i download the <old> version of redmine?
thanks in advance
michael

**Comment by picman** [comment]
Redmine 3.3 is required. So please upgrade Redmine first.

**Comment by u2mike** [comment]
last question ... because lack of time ... is it possible to download version 1.5.3?

**Comment by picman** [comment]
https://github.com/danmunn/redmine_dmsf/releases

**Comment by u2mike** [comment]
thanks!
