### ISSUE TITLE
'Save as' from Excel does not work when using project names

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#700]
Using 'Save as' in ~~MsOffice~~ Excel (tested with Excel 2016) and trying to save a document to the WebDAV does not work when using project names since Excel does not like '[' or ']' in the path.
Office shows the following error message:
![image](https://cloud.githubusercontent.com/assets/13761538/23993097/8d120344-0a3f-11e7-8a0a-ceebf417abc1.png)

Using 'Save as' in Notepad++ does work, and saving with Word or Publisher also works.

The problem is not only related to using project names since both '[' and ']' are valid characters in foldernames and filenames:
[`INVALID_CHARACTERS = /\A[^\/\\\?":<>#%\*]*\z/.freeze`](https://github.com/danmunn/redmine_dmsf/blob/master/app/models/dmsf_folder.rb#L46)

**Comment by carlolars** [comment]
Solution:
1. Add '[' and ']' to invalid characters for folders.
2. When using project names, don't append `[<project-id>]` to the project name, use `-<project-id>` instead.

**Comment by picman** [comment]
Fixed.

**Comment by carlolars** [comment]
Hi
Using `DmsfFolder::INVALID_CHARACTERS` in the gsub does not work, that is why I created a new INVALID_CHARACTERS regex in project_resource.rb.

We decided to go for appending `-<project-id>-` as it looked better and made the project id number distinctive from the project name.

Shouldn't this also be fixed in the master branch? Anyways I made a PR to master with fixed tests.

**Comment by picman** [comment]
> DmsfFolder::INVALID_CHARACTERS in the gsub does not work

There must be a reason why it doesn't work. To have two the same constants is not a good approach.

**Comment by carlolars** [comment]
> There must be a reason why it doesn't work. To have two the same constants is not a good approach.

The set in DmsfFolder::INVALID_CHARACTERS is actually an expression for valid characters despite the name, while the expression used in the gsub is used to match invalid characters.

Another thing is that the DmsfFolder::INVALID_CHARACTERS expression starts with '\A' and ends with '\z' that are used to match start and end of a string in `validates_format_of`, while they will match the characters 'A' and 'z' in gsub.

Create a proper INVALID_CHARACTERS string and from that one create the expressions for  `validates_format_of` and `gsub`.

I consider this issue resolved.
