### ISSUE TITLE
How tagging with multiple values works?

### ISSUE THREAD

**Issue by tluu04** [danmunn/redmine_dmsf#701]
Not sure if this is a bug.
I define a Tag custom field named Tag as a list with Multiple Values checked and selected as checkboxes.  When in project, the check boxes show in dsmf but without description, and whenever you check a box, the frame go wider,...  
Perhaps i am not sure exactly how this work.  Needs help.  
We'd like to use the multiple values to allow filtering based on different categories.

Thong

**Comment by picman** [comment]
It's a bug. I've fixed it in 1.6.0-devel. It should be working now.

![0 0 0 0_2017-04-13_13-27-57](https://cloud.githubusercontent.com/assets/779003/25003021/a4fce568-204d-11e7-8b30-b6dc639f8759.png)
