### ISSUE TITLE
Now it is impossible to paste image with redmine_image_clipboard_paste

### ISSUE THREAD

**Issue by fabricerobin** [danmunn/redmine_dmsf#702]
Hi,

Since commit "Linking Issues and DMSF Documents #48", the image paste feature of the plugin https://github.com/thorin/redmine_image_clipboard_paste does not work anymore.

I had to rollback DMSF plugin to 94fad6275b2af1f38f3b28f764b24b337314f09a

Regards,
Fabrice

**Comment by picman** [comment]
Could you provide some details, log etc. To see whether it's image_clipboard_paste plugin's problem or dmsf plugin's problem?

**Comment by dhoyer** [comment]
same errror. Chrome Console says:Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (attachments.js:70)
    at j (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
    at x (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4)
    at XMLHttpRequest.b (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4)

**Comment by fabricerobin** [comment]
I tried to analyze quickly the problem.

When the issue is submitted, the image is uploaded via DMSF.
The image file is present on the Redmine host into the Redmine file folder /var/www/redmine/files/2017/03/170323153341_screenshot_1_1490279622.png

But when the Issue page is refreshed, the attached image file is not showed.
There is a 404 error on "https://redmine.xxxx.com/issues/screenshot_1_1490279622.png"

If I rollback the redmine_dmsf to commit 94fad6275b2af1f38f3b28f764b24b337314f09a , there is no more error.

The problem occurs with the following commit 65820f97f3beaf31258b99da15a9e88f54d7c87b

**Comment by picman** [comment]
Related to #703

**Comment by picman** [comment]
Update your master branch by calling _git pull_. there is a new plugin option **Act as attachable** and keep it off. That should help.

**Comment by dhoyer** [comment]
Yes, that helps. Thank, you!

**Comment by fabricerobin** [comment]
It is ok now. Thanks !
