### ISSUE TITLE
tree view

### ISSUE THREAD

**Issue by paul-leroy** [danmunn/redmine_dmsf#704]
Hi all,
First of all, thanks for your job on dmsf which gives to Redmine one important feature it is missing!
I would like to know whether it is possible to configure dmsf to see a tree view of the directory structure instead of the default view?
Thanks in advance.

**Comment by picman** [comment]
Check your user's profile and select **Navigate folders in a tree**:

![tree](https://cloud.githubusercontent.com/assets/779003/24291018/8114e2b6-1087-11e7-890b-2a42516f0e07.png)

**Comment by paul-leroy** [comment]
Excellent! Thanks.
