### ISSUE TITLE
Update from 1.4.8 to 1.5.9

### ISSUE THREAD

**Issue by ipcross** [danmunn/redmine_dmsf#705]
Hi.
Updated from 1.4.8 to 1.5.9. The plugin works fine, but does not see old files and folders.
Help.

**Comment by picman** [comment]
What does the production.log say?

**Comment by ipcross** [comment]
`Started GET "/projects/instr/dmsf" for x.x.x.x at 2017-03-28 16:09:56 +0300
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"instr"}
  Current user: admin (id=1)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (7.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (2.2ms)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (0.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (24.3ms)
  Rendered plugins/customize_view_unico/app/views/create_wiki_page/_init_create_wiki_page.erb (0.0ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.0ms)
Completed 200 OK in 111ms (Views: 23.5ms | ActiveRecord: 78.8ms)`

List of files is empty. "No matching records found"

File storage directory is true and have files.

**Comment by picman** [comment]
The files should by physically located in dmsf/p_instr. They are organized by projects. However, in the user interface of DMSF can be seen only those files with a corresponding record in dmsf_folders, dmsf_files and dmsf_file_revisions tables. Please check them. I suppose that the original files and folders are missing there.

**Comment by ipcross** [comment]
irb(main):002:0> DmsfFile
REDMAIN_XAPIAN ERROR: No Ruby bindings for Xapian installed !!. PLEASE install Xapian search engine interface for Ruby.
=> DmsfFile(id: integer, project_id: integer, dmsf_folder_id: integer, name: string, notification: boolean, deleted: boolean, deleted_by_user_id: integer, created_at: datetime, updated_at: datetime)
irb(main):003:0> DmsfFile.all
=> #<ActiveRecord::Relation [#<DmsfFile id: 1, project_id: 23, dmsf_folder_id: 2, name: "56718.pdf", notification: false, deleted: false, deleted_by_user_id: nil, created_at: "2014-05-14 05:11:36", updated_at: "2014-05-14 05:11:36">, #<DmsfFile id: 2, project_id: 23, dmsf_folder_id: 2, name: "ИС_ОГРН295.pdf", notification: false, deleted: false, deleted_by_user_id: nil, created_at: "2014-05-14 05:12:21", updated_at: "2014-05-14 05:12:21">,...]>
irb(main):004:0> DmsfFile.all.count
=> 506
irb(main):005:0> DmsfFolder
=> DmsfFolder(id: integer, project_id: integer, dmsf_folder_id: integer, title: string, description: text, notification: boolean, user_id: integer, created_at: datetime, updated_at: datetime)
irb(main):006:0> DmsfFolder.all
=> #<ActiveRecord::Relation [#<DmsfFolder id: 14, project_id: 23, dmsf_folder_id: nil, title: "Отдел программирования и телефонии", description: "", notification: false, user_id: 3, created_at: "2014-05-27 10:40:20", updated_at: "2014-06-18 09:27:42">...]>
irb(main):007:0> DmsfFolder.all.count
=> 67
irb(main):008:0> DmsfFileRevision
=> DmsfFileRevision(id: integer, dmsf_file_id: integer, source_dmsf_file_revision_id: integer, name: string, dmsf_folder_id: integer, disk_filename: string, size: integer, mime_type: string, title: string, description: text, workflow: integer, major_version: integer, minor_version: integer, comment: text, deleted: boolean, deleted_by_user_id: integer, user_id: integer, created_at: datetime, updated_at: datetime, project_id: integer, dmsf_workflow_id: integer, dmsf_workflow_assigned_by: integer, dmsf_workflow_assigned_at: datetime, dmsf_workflow_started_by: integer, dmsf_workflow_started_at: datetime)
irb(main):009:0> DmsfFileRevision.all
=> #<ActiveRecord::Relation [#<DmsfFileRevision id: 1, dmsf_file_id: 1, source_dmsf_file_revision_id: nil, name: "56718.pdf", dmsf_folder_id: 2, disk_filename: "140514091136_1_56718.pdf", size: 3967064, mime_type: "application/pdf", title: "56718", description: "ПД полная, закончилась", workflow: nil, major_version: 0, minor_version: 1, comment: "", deleted: false, deleted_by_user_id: nil, user_id: 3, created_at: "2014-05-14 05:11:36", updated_at: "2014-05-14 05:11:36", project_id: 23, dmsf_workflow_id: nil, dmsf_workflow_assigned_by: nil, dmsf_workflow_assigned_at: nil, dmsf_workflow_started_by: nil, dmsf_workflow_started_at: nil>, ....]>
irb(main):010:0> DmsfFileRevision.all.count
=> 755

**Comment by ipcross** [comment]
I upgraded from 1.4.8 to 1.5.9
My migrate is:
Migrating redmine_dmsf (DMSF)...
== 20140519133201 TrashBin: migrating =========================================
-- add_column(:dmsf_folders, :deleted, :boolean, {:default=>false, :null=>false})
   -> 0.0580s
-- add_column(:dmsf_folders, :deleted_by_user_id, :integer)
   -> 0.0011s
== 20140519133201 TrashBin: migrated (0.1126s) ================================

== 20141013102501 RemoveProjectFromRevision: migrating ========================
-- remove_column(:dmsf_file_revisions, :project_id)
   -> 0.0014s
== 20141013102501 RemoveProjectFromRevision: migrated (0.0014s) ===============

== 20141015132701 RemoveFolderFromRevision: migrating =========================
-- remove_column(:dmsf_file_revisions, :dmsf_folder_id)
   -> 0.0007s
== 20141015132701 RemoveFolderFromRevision: migrated (0.0007s) ================

May be problem is here?

**Comment by ipcross** [comment]
I add file:
=> #<DmsfFile id: 728, container_id: 23, dmsf_folder_id: nil, name: "Rails 4 Test Prescriptions.pdf", notification: nil, deleted: 0, deleted_by_user_id: nil, created_at: "2017-03-29 06:49:55", updated_at: "2017-03-29 06:49:55", container_type: "Project">
I see it.

irb(main):002:0> DmsfFile.find(716)
=> #<DmsfFile id: 716, container_id: 23, dmsf_folder_id: nil, name: "Миссия.pdf", notification: false, deleted: 1, deleted_by_user_id: nil, created_at: "2017-01-19 07:06:15", updated_at: "2017-01-19 07:06:15", container_type: "Project">
This no see, but on 1.4.8 yes. Why fieid deleted = 1, if:

Migrating redmine_dmsf (DMSF)...
== 20140519133201 TrashBin: migrating =========================================
-- add_column(:dmsf_folders, :deleted, :boolean, {:default=>false, :null=>false})
-> 0.0580s
-- add_column(:dmsf_folders, :deleted_by_user_id, :integer)
-> 0.0011s
== 20140519133201 TrashBin: migrated (0.1126s) ================================

and

== 20160217133001 StatusDeleted: migrating ====================================
-- execute("ALTER TABLE dmsf_folders ALTER deleted DROP DEFAULT;")
   -> 0.0011s
-- change_column(:dmsf_folders, :deleted, "INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END", {:null=>false, :default=>0})
   -> 0.0495s
-- execute("ALTER TABLE dmsf_files ALTER deleted DROP DEFAULT;")
   -> 0.0010s
-- change_column(:dmsf_files, :deleted, "INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END", {:null=>false, :default=>0})
   -> 0.0541s
-- execute("ALTER TABLE dmsf_file_revisions ALTER deleted DROP DEFAULT;")
   -> 0.0008s
-- change_column(:dmsf_file_revisions, :deleted, "INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END", {:null=>false, :default=>0})
   -> 0.1643s
-- execute("ALTER TABLE dmsf_links ALTER deleted DROP DEFAULT;")
   -> 0.0006s
-- change_column(:dmsf_links, :deleted, "INTEGER USING CASE WHEN TRUE THEN 1 ELSE 0 END", {:null=>false, :default=>0})
   -> 0.0393s
== 20160217133001 StatusDeleted: migrated (0.3450s) ===========================

**Comment by picman** [comment]
Thank you for trying to find the origin of the problem. I've looked into the migration but I haven't found any bug causing deleted = 1 by existing files.
As a workaround I suggest you updating your database manually, e.g.:

```sql
UPDATE dmsf_files SET deleted = 0;
UPDATE dmsf_files SET deleted = 0;
```

**Comment by picman** [comment]
BTW, which database do you use?

**Comment by ipcross** [comment]
Postgresql 9.4

**Comment by ipcross** [comment]
irb(main):003:0> DmsfFile.update_all(deleted: 0)
=> 506
irb(main):004:0> DmsfFolder.update_all(deleted: 0)
=> 67

**Comment by ipcross** [comment]
Folders - true
Count of files - true
Files no see.

<a target="_blank" href="http://radikal.ru"><img src="http://s019.radikal.ru/i601/1703/04/533f2089f494.jpg" /></a>

**Comment by picman** [comment]
>DmsfFileRevision.update_all(deleted:0)

**Comment by ipcross** [comment]
Work. Thanks.
