### ISSUE TITLE
The full text search does not work

### ISSUE THREAD

**Issue by fabricerobin** [danmunn/redmine_dmsf#714]
Hi,

We are unable to get the full text search working.

The files are well indexed by omindex and manual search with the quest command are ok.

When launching a search from Redmine, the following log occurred :
WARN -- : REDMAIN_XAPIAN ERROR: Xapian database is not properly set, initiated or it's corrupted.
WARN -- : DatabaseOpeningError: Couldn't detect type of database

The index folder :
[root@redmine english]# pwd
/var/www/redmine-files/dmsf_index/english

-rw-r--r-- 1 apache apache  1064960 21 avril 17:36 docdata.glass
-rw-r--r-- 1 apache apache        0 21 avril 17:30 flintlock
-rw-r--r-- 1 apache apache      123 21 avril 17:36 iamglass
-rw-r--r-- 1 apache apache 85565440 21 avril 17:36 position.glass
-rw-r--r-- 1 apache apache 41058304 21 avril 17:36 postlist.glass
-rw-r--r-- 1 apache apache 13025280 21 avril 17:36 termlist.glass

The plugin settings :
![image](https://cloud.githubusercontent.com/assets/7325235/25286012/8b26e8b2-26bc-11e7-9d72-05253731fa89.png)

We are using xapian 1.4.3, with Redmine 3.3.1 and DMSF plugin 1.5.9

Regards,
Fabrice

**Comment by acosonic** [comment]
Are you on postgresql?

**Comment by acosonic** [comment]
I can confirm it's not working on postgresql 1.5.9 and it's working on mysql 1.5.8 version...

If I type bo on postgresql I get nothing, but I should get document containing bobo

which works on mysql version...

**Comment by picman** [comment]
> REDMAIN_XAPIAN ERROR: Xapian database is not properly set, initiated or it's corrupted.

The full-text search has nothing to do with the Redmine database.

**Comment by acosonic** [comment]
Yeah, but if I search for bobo123 I do get result, and if I search for bobo I get nothing. Bobo123 is what's written in file.

**Comment by acosonic** [comment]
There is screenshot:

![screenshot at apr 27 16-08-31](https://cloud.githubusercontent.com/assets/862015/25487213/d3766ede-2b63-11e7-8b96-6e7306f7675b.png)

Same thing works on mysql.

**Comment by picman** [comment]
That's strange, because as I said the texts are indexed in the Xapian database independent on the database used by Redmine. Moreover, results of searching for Bobo123 X Bobo should depend on stemming option in the plugin settings.

**Comment by fabricerobin** [comment]
We are using Mysql for Redmine. But that is not the problem as the Xapian "database" is on the filesystem (In our case into /var/www/redmine-files/dmsf_index/english folder).

**Comment by acosonic** [comment]
Sorry I can confirm it's not working on mysql as well.

![screenshot at apr 27 16-55-35](https://cloud.githubusercontent.com/assets/862015/25489521/5bb2a44c-2b6a-11e7-9b86-f2641ded61f3.png)

I can give you mysql version's ssh access to test if you want/need...

Server is under passenger/apache so it's easy to restart via touch tmp/restart.txt

**Comment by picman** [comment]
Select **Stem some** as the stem strategy, then it should find _Bobo_ and _Bobo123_ as well.

**Comment by acosonic** [comment]
I did, and run update, but no change. 

bobo returns nothing, while bobo123 does find proper document.

**Comment by picman** [comment]
Try to re-index the database.

**Comment by acosonic** [comment]
I don't see reset command in list of xapian_indexer.rb.

What I did is deleting database then re-indexing.

Still same result.

If you have time I can provide SSH/web access to my test instance.

**Comment by fabricerobin** [comment]
Hi,
We found a solution.
We had to replace xapian 1.4.3 with xapian 1.2.21 on the machine, and to reindex the files.
Now the full-text search is working.

Maybe redmine_dmsf documentation should list the required dependencies for Xapian ?

**Comment by acosonic** [comment]
My version is 1.2.22 

I'll try removing it and installing 1.2.21 and will get back here also.

**Comment by acosonic** [comment]
Tried, same thing. bobo123 finds it, bobo does not find it... Re-created db..

```
 usr/bin/omindex -s english --db /home/redmine/files/dmsf_index/english /home/redmine/files/dmsf --url / --depth-limit=0 -v --overwrite
[Entering directory ""]
[Entering directory "p_upiti/"]
Indexing "p_upiti/170427145940_7_Em.docx" as application/vnd.openxmlformats-officedocument.wordprocessingml.document ... added
Indexing "p_upiti/170427142542_7_Em.docx" as application/vnd.openxmlformats-officedocument.wordprocessingml.document ... added
Indexing "p_upiti/170427142142_7_New_Microsoft_Word_Document.docx" as application/vnd.openxmlformats-officedocument.wordprocessingml.document ... added
Indexing "p_upiti/170427145159_7_Em.docx" as application/vnd.openxmlformats-officedocument.wordprocessingml.document ... added
Indexing "p_upiti/170427102153_6_New_Microsoft_Word_Document.docx" as application/vnd.openxmlformats-officedocument.wordprocessingml.document ... Skipping - Zero-sized file
```
xapian is now xapian-config - xapian-core 1.2.21

**Comment by acosonic** [comment]
Hm, obviously this bobo123 thing is xapian's stemming / search algorithm problem...

**Comment by picman** [comment]
Another problem is that the gem used in the plugin: xapian-full-alavateli is frozen on v1.2.21.1 for two years and the question is whether and when will it be updated.

**Comment by acosonic** [comment]
Hmm, you are right, and there is no recently updated forks... Let's monitor this, in the future I might have some budget and have somebody work on it if required. Plus I got snowball stemming algorithms for Serbian language...
