### ISSUE TITLE
open document from url 

### ISSUE THREAD

**Issue by vsirvent** [danmunn/redmine_dmsf#715]
Hi,

We are just testing new 1.6.0 version and when opening a document directly from the url the plugin now redirects to the last uploaded file by date and not by version as it was done before, this is a problem for us because if we forget to upload an intermediate version and we upload it later it's the one downloaded instead of the last version. Is this a wanted behaviour or a bug?

Regards,

Vicente

**Comment by picman** [comment]
This part hasn't been changed, I believe. The last revision is defined as follows:

```ruby
def last_revision
  unless defined?(@last_revision)
    @last_revision = self.deleted? ? self.dmsf_file_revisions.first : self.dmsf_file_revisions.visible.first
  end
  @last_revision
end
```

It means that the revision with the biggest id is returned. The last uploaded in other words.

If you want to create a revision older than the last one, you must delete the newer revisions first and create them again. Versions have no influence on the revisions order.

**Comment by vsirvent** [comment]
I've checked that piece of code and it's the same, but I can guarantee that when clicking a doc it showed the lastest version by version number...

We were using v1.5.2

**Comment by picman** [comment]
I'm pretty sure that it is not true.
