### ISSUE TITLE
Enhacement: Xapian parse eml and msg files in same way as word, excel...

### ISSUE THREAD

**Issue by acosonic** [danmunn/redmine_dmsf#717]
Some users are putting msg and eml files in Redmine I believe it's not too much work to make them parsable and searchable by Xapian.

**Comment by picman** [comment]
Do not forget to install _libemail-outlook-message-perl_ package.

**Comment by acosonic** [comment]
Ok, don't forget to update plugin description github page as well. (Readme.md) with ibemail-outlook-message-perl
