### ISSUE TITLE
Dalli is in conflict with redmine gemfile

### ISSUE THREAD

**Issue by sho-suzuki** [danmunn/redmine_dmsf#719]
Hi I'm using redmine 3.3.2-1.
when I execute `git clone` and `bundle install`, I got a error message.

Could you remove dalli in Gemfile or add to the installation note that you need to delete dallli before running `bundle install`.

Shall I send you a PR with deleted dalli gem dependency?

thanks.

**Comment by picman** [comment]
Yes, to devel-1.6.0, please.

**Comment by picman** [comment]
But, the plugin depends on dalli. It's used in WebDAV to access a memcached server. We can't remove the dependency. What is the error you get?

**Comment by sho-suzuki** [comment]
@picman  I got  this error.

```rb
root# bundle install

[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: dalli (>= 0) and dalli (~> 2.7.0). Bundler cannot continue.

 #  from /home/redmine/redmine/Gemfile:121
 #  -------------------------------------------
 #  gem "unicorn"
 >  gem "dalli", "~> 2.7.0"
 #  -------------------------------------------
```

**Comment by picman** [comment]
If I check the Redmine's Gemfile I see neither unicorn nor dalli there.
http://www.redmine.org/projects/redmine/repository/entry/trunk/Gemfile
Where have you got this file?

**Comment by sho-suzuki** [comment]
I am sorry. That's right.
I am using docker image of sameersbn / redmine.

I checked github (https://github.com/sameersbn/docker-redmine) and confirmed that unicorn and dalli were added to original gemfile.
If the dalli version specification is unnecessary, is it OK to change it?

```
Gem "dalli", "~> 2.7.0"
```

**Comment by picman** [comment]
I'd prefer to keep 'gem dalli'. There is no reason to require the version > 2.7.0. Later on they will modify the dependency to e.g. 2.7.1 and we will have to modify our Gemfile too.
Comment out dalli dependency in your Gemfile. No changes in DMSF needed, I think.

**Comment by sho-suzuki** [comment]
It is not a problem with official redmine but a problem with customized redmine so i comment it out.
Thank you very much.

**Comment by psi-4ward** [comment]
Same Problem here, using docker image `sameersbn/redmine:3.3.0-4`

**Comment by psi-4ward** [comment]
still present
