### ISSUE TITLE
Connection to WebDAV with WinSCP is not working

### ISSUE THREAD

**Issue by picman** [danmunn/redmine_dmsf#721]
There is a problem that WinSCP append the port number to the URL, e.g. localhost:3000/dmsf/webdav/c1:443. No project with th identifier c1:443 is found then.

**Comment by carlolars** [comment]
Works for me.
In hostname write just the root url, in your case '_localhost_', and in Advanced->Environment->Directories, put '_/dmsf/webdav_' in Remote directory (or '_/dmsf/webdav/c1_' if you want the c1 project).

**Comment by picman** [comment]
That works. Thank you.
