### ISSUE TITLE
Delete revision removed file from disk when it should not

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#722]
Hi
I have a Ms-Word file with a lot of revisions, and some of those revisions might have the same physical file.
Delete files physically were configured to enabled in DMSF, version 1.5.9.

When I deleted a few revisions from a file the file were suddenly not available anymore.
The file was visible in both the WebGUI and WebDAV, but trying to open the file caused "_RoutingError (No route matches [GET] "/dmsf/webdav/.../myfile.docx"_" from WebDAV and "_ERROR: Cannot read file /home/redmine/redmine/files/dmsf/.../170502143352_4_myfile.docx_" from the WebGUI.
I tried to download specific revisions from the files details and the most recent revision failed but the revision before that was successful, probably because that revision used a file on disk that existed.

I have mainly used WebDAV to update the file.

I have unfortunately not the time right now to investigate this further, and have disabled physically deleting files now.

**Comment by picman** [comment]
I've just tested it a little but haven't faced such problem yet.
If I check the source code, there is just one place where files are physically deleted and the condition before the deletion is quite strong. A file is deleted if only there is no other revision referencing the file.

```ruby
if Setting.plugin_redmine_dmsf['dmsf_really_delete_files']
   dependencies = DmsfFileRevision.where(:disk_filename => self.disk_filename).count
   File.delete(self.disk_file) if dependencies <= 1 && File.exist?(self.disk_file)
end
```

Please investigate it further to find circumstances when it happens.

**Comment by picman** [comment]
No feedback => closing.
