### ISSUE TITLE
Automate Linking a Project's DMSF to other existing projects

### ISSUE THREAD

**Issue by shaneavelino** [danmunn/redmine_dmsf#723]
Would there be a way to automatically set a project's DMSF to other existing project's DMSF without manually having to 'Link from' said project?  Normally, you can 'Link from' in a project's DMSF UI and copy from the Source project, Source folder, Source file, and the Link name.   

Our organization would like a way to automate this process since we have about 50-75 projects that we would have to manually copy DMSF folders/files to.

**Example**: Project 1 has all template documents in DMSF.  Projects 10-35 will use the same existing template folders/files in DMSF from Project 1.  Would like to select Projects 10-35 and copy Project 1's DMSF folders/files and apply it to Projects 10-35.

**Comment by picman** [comment]
Why not to do that this way:

1. Create a template project with a defined folder/file structure in DMS module.
2. Create each new project as a copy of the template project.
