### ISSUE TITLE
Can't upload file. There will arise ERR_EMPTY_RESPONSE when commit 

### ISSUE THREAD

**Issue by ThinkingHeart** [danmunn/redmine_dmsf#724]
when I want to upload file through DMSF, and after clicked 'start upload' ,there show a commit page. But there were not response when I clicked 'commit'.
The log is show that
`    47 at 2017-05-23 16:57:56 +0800
Processing by DmsfController#notify_activate as HTML
  Parameters: {"id"=>"test1"}
  Current user: qinhao (id=7)
Redirected to http://222.25.175.7:8080/redmine/projects/test1/dmsf
Completed 302 Found in 613ms (ActiveRecord: 599.8ms)
Started GET "/redmine/projects/test1/dmsf" for 10.170.24.47 at 2017-05-23 16:57:57 +0800
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (4.9ms)
/home/qin/Bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/jquery.dataTables/zh.json not found
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.6ms)
/home/qin/Bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/plupload/js/i18n/zh.js not found
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (3.3ms)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (1.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (21.3ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (2.1ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (1.4ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.3ms)
Completed 200 OK in 116ms (Views: 47.5ms | ActiveRecord: 55.3ms)
Started GET "/redmine/projects/test1/dmsf/trash" for 10.170.24.47 at 2017-05-23 16:57:59 +0800
Processing by DmsfController#trash as HTML
  Parameters: {"id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir_trash.html.erb (28.1ms)
/home/qin/Bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/jquery.dataTables/zh.json not found
  Rendered plugins/redmine_dmsf/app/views/dmsf/trash.html.erb within layouts/base (60.2ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.5ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (1.5ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.4ms)
Completed 200 OK in 1493ms (Views: 85.7ms | ActiveRecord: 1398.3ms)
Started GET "/redmine/projects/test1/dmsf/delete?commit=yes&folder_id=1" for 10.170.24.47 at 2017-05-23 16:58:04 +0800
Processing by DmsfController#delete as HTML
  Parameters: {"commit"=>"yes", "folder_id"=>"1", "id"=>"test1"}
  Current user: qinhao (id=7)
Webdav::Cache: Cache disabled!
Redirected to http://222.25.175.7:8080/redmine/projects/test1/dmsf/trash
Completed 302 Found in 290ms (ActiveRecord: 260.7ms)
Started GET "/redmine/projects/test1/dmsf/trash" for 10.170.24.47 at 2017-05-23 16:58:04 +0800
Processing by DmsfController#trash as HTML
  Parameters: {"id"=>"test1"}
  Current user: qinhao (id=7)
/home/qin/Bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/jquery.dataTables/zh.json not found
  Rendered plugins/redmine_dmsf/app/views/dmsf/trash.html.erb within layouts/base (12.1ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.3ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (1.5ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.6ms)
Completed 200 OK in 95ms (Views: 38.9ms | ActiveRecord: 48.3ms)
Started GET "/redmine/projects/test1/dmsf" for 10.170.24.47 at 2017-05-23 16:58:06 +0800
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (3.4ms)
/home/qin/Bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/jquery.dataTables/zh.json not found
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.8ms)
/home/qin/Bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/plupload/js/i18n/zh.js not found
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (3.8ms)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (1.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (21.9ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.4ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (1.4ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.4ms)
Completed 200 OK in 113ms (Views: 47.4ms | ActiveRecord: 50.5ms)
Started GET "/redmine/projects/test1/dmsf/edit/root" for 10.170.24.47 at 2017-05-23 16:58:08 +0800
Processing by DmsfController#edit_root as HTML
  Parameters: {"id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/edit_root.html.erb within layouts/base (5.5ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.4ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (1.3ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.3ms)
Completed 200 OK in 83ms (Views: 35.7ms | ActiveRecord: 40.6ms)
Started GET "/redmine/projects/test1/dmsf" for 10.170.24.47 at 2017-05-23 16:58:12 +0800
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (3.3ms)
/home/qin/Bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/jquery.dataTables/zh.json not found
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.8ms)
/home/qin/Bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/plupload/js/i18n/zh.js not found
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (4.3ms)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (1.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (21.3ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.4ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (1.4ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.5ms)
Completed 200 OK in 298ms (Views: 47.2ms | ActiveRecord: 236.7ms)
Started POST "/redmine/projects/test1/dmsf/upload/file" for 10.170.24.47 at 2017-05-23 16:58:23 +0800
Processing by DmsfUploadController#upload_file as */*
  Parameters: {"name"=>"Deep Face Recognition.pdf", "authenticity_token"=>"UAJAje7x1DMIUOZFu4EmRr0xSaUiJrqQ3OOZh3hB8ZnODwEG9ywEYweCVAI0fuVajs2rY2i7m2dqo1I/EGh/4Q==", "file"=>#<ActionDispatch::Http::UploadedFile:0x007ff14afce980 @tempfile=#<Tempfile:/tmp/RackMultipart20170523-18038-1pfpln3.pdf>, @original_filename="Deep Face Recognition.pdf", @content_type="application/pdf", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"Deep Face Recognition.pdf\"\r\nContent-Type: application/pdf\r\n">, "id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_file.html.erb (0.1ms)
Completed 200 OK in 944ms (Views: 0.7ms | ActiveRecord: 936.0ms)
Started POST "/redmine/projects/test1/dmsf/upload/files" for 10.170.24.47 at 2017-05-23 16:58:24 +0800
Processing by DmsfUploadController#upload_files as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"SIVWsZOuoCDT1Pk4zCpqGNSvAKJ1JW8lr224g+qBwP3WiBc6inNwcNwGS39D1akE51PiZD+4TtIZLXM7gqhOhQ==", "view_mode_o_1bgq8e5tc1ehocs4bggs6t1gc01"=>"on", "o_1bgq8e5tc1ehocs4bggs6t1gc01_count"=>"0", "uploaded"=>{"1"=>{"disk_filename"=>"170523165824_Deep_Face_Recognition.pdf", "content_type"=>"application/pdf", "original_filename"=>"Deep Face Recognition.pdf"}}, "id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_upload_file.html.erb (7.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_files.html.erb within layouts/base (9.3ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.4ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (1.3ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.4ms)
Completed 200 OK in 96ms (Views: 37.9ms | ActiveRecord: 48.2ms)
Started GET "/redmine" for 10.170.24.47 at 2017-05-23 17:27:02 +0800
Processing by WelcomeController#index as HTML
  Current user: qinhao (id=7)
  Rendered welcome/index.html.erb within layouts/base (11.5ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.0ms)
  Rendered inline template (0.5ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (0.0ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.1ms)
Completed 200 OK in 87ms (Views: 21.5ms | ActiveRecord: 61.0ms)
Started GET "/redmine/projects/test1" for 10.170.24.47 at 2017-05-23 17:27:05 +0800
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_urls.html.haml (6.3ms)
  Rendered plugins/redmine_git_hosting/app/views/projects/_git_urls.html.haml (11.4ms)
  Rendered projects/_members_box.html.erb (1.3ms)
  Rendered projects/_sidebar.html.erb (0.9ms)
  Rendered projects/show.html.erb within layouts/base (21.9ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.3ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (0.1ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.3ms)
Completed 200 OK in 157ms (Views: 79.9ms | ActiveRecord: 55.5ms)
Started GET "/redmine/projects/test1/dmsf" for 10.170.24.47 at 2017-05-23 17:27:08 +0800
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (3.3ms)
/home/qin/Bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/jquery.dataTables/zh.json not found
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.7ms)
/home/qin/Bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/plupload/js/i18n/zh.js not found
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (3.7ms)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (1.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (21.6ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.4ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (3.3ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.3ms)
Completed 200 OK in 145ms (Views: 57.3ms | ActiveRecord: 73.0ms)
Started POST "/redmine/projects/test1/dmsf/upload/file" for 10.170.24.47 at 2017-05-23 17:27:16 +0800
Processing by DmsfUploadController#upload_file as */*
  Parameters: {"name"=>"A Unified Embedding for Face Recognition and Clustering.pdf", "authenticity_token"=>"JfUG8SuEFpWjuGQyeiNPOrjl/8VP9zzLXz2T7K2Dc3+7+Ed6MlnGxaxq1nX13IwmixkdAwVqHTzpfVhUxar9Bw==", "file"=>#<ActionDispatch::Http::UploadedFile:0x007ff14ba097d8 @tempfile=#<Tempfile:/tmp/RackMultipart20170523-18038-f61eg5.pdf>, @original_filename="A Unified Embedding for Face Recognition and Clustering.pdf", @content_type="application/pdf", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"A Unified Embedding for Face Recognition and Clustering.pdf\"\r\nContent-Type: application/pdf\r\n">, "id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_file.html.erb (0.1ms)
Completed 200 OK in 77ms (Views: 1.1ms | ActiveRecord: 66.4ms)
Started POST "/redmine/projects/test1/dmsf/upload/files" for 10.170.24.47 at 2017-05-23 17:27:16 +0800
Processing by DmsfUploadController#upload_files as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"wmV+jCZFovfBHvgqLMl2sHX52WqbtpTmbffvpbcOBfJcaD8HP5hyp87MSm2jNrWsRgU7rNErtRHbtyQd3yeLig==", "view_mode_o_1bgqa34t51bnliei2j19d61esv1"=>"on", "o_1bgqa34t51bnliei2j19d61esv1_count"=>"0", "uploaded"=>{"1"=>{"disk_filename"=>"170523172716_A_Unified_Embedding_for_Face_Recognition_and_Clustering.pdf", "content_type"=>"application/pdf", "original_filename"=>"A Unified Embedding for Face Recognition and Clustering.pdf"}}, "id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_upload_file.html.erb (6.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_files.html.erb within layouts/base (8.4ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.6ms)
  Rendered inline template (0.7ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (1.8ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.3ms)
Completed 200 OK in 92ms (Views: 36.5ms | ActiveRecord: 43.8ms)
Started GET "/redmine/projects/test1/dmsf" for 10.170.24.47 at 2017-05-23 17:30:12 +0800
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (4.3ms)
/home/qin/Bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/jquery.dataTables/zh.json not found
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.5ms)
/home/qin/Bitnami/apps/redmine/htdocs/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/plupload/js/i18n/zh.js not found
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (3.2ms)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (1.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (20.2ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (2.2ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (1.3ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.3ms)
Completed 200 OK in 123ms (Views: 44.8ms | ActiveRecord: 63.8ms)
Started GET "/redmine/admin" for 10.170.24.47 at 2017-05-23 17:30:26 +0800
Processing by AdminController#index as HTML
  Current user: qinhao (id=7)
  Rendered admin/_menu.html.erb (4.8ms)
  Rendered admin/index.html.erb within layouts/admin (9.4ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.0ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (0.0ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.0ms)
  Rendered layouts/base.html.erb (12.8ms)
Completed 200 OK in 104ms (Views: 33.0ms | ActiveRecord: 64.1ms)
Started GET "/redmine/logs/index" for 10.170.24.47 at 2017-05-23 17:30:31 +0800
Processing by LogsController#index as HTML
  Current user: qinhao (id=7)
  Rendered plugins/redmine_logs/app/views/logs/index.html.erb within layouts/admin (6.2ms)
  Rendered admin/_menu.html.erb (4.1ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.1ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (0.0ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.0ms)
  Rendered layouts/base.html.erb (11.3ms)
Completed 200 OK in 91ms (Views: 27.7ms | ActiveRecord: 59.2ms)
Started POST "/redmine/logs/show" for 10.170.24.47 at 2017-05-23 17:30:33 +0800
Processing by LogsController#show as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"ZY4Mr2dth60Qol9VaDzQImGpfL26fPfBZ7Zwn7NbaMP7g00kfrBX/R9w7RLnwxM+UlWee/Dh1jbR9rsn23Lmuw==", "path"=>"/home/qin/Bitnami/apps/redmine/htdocs/log/production.log"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_logs/app/views/logs/show.html.erb within layouts/admin (3.0ms)
  Rendered admin/_menu.html.erb (4.9ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.0ms)
  Rendered inline template (0.5ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (0.0ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.0ms)
  Rendered layouts/base.html.erb (11.0ms)
Completed 200 OK in 71ms (Views: 20.4ms | ActiveRecord: 47.2ms)
Started POST "/redmine/projects/test1/dmsf/upload/file" for 10.170.24.47 at 2017-05-23 17:30:52 +0800
Processing by DmsfUploadController#upload_file as */*
  Parameters: {"name"=>"1409.1556.pdf", "authenticity_token"=>"wmV+jCZFovfBHvgqLMl2sHX52WqbtpTmbffvpbcOBfJcaD8HP5hyp87MSm2jNrWsRgU7rNErtRHbtyQd3yeLig==", "file"=>#<ActionDispatch::Http::UploadedFile:0x007ff149fb18b8 @tempfile=#<Tempfile:/tmp/RackMultipart20170523-18038-xtbljg.pdf>, @original_filename="1409.1556.pdf", @content_type="application/pdf", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"1409.1556.pdf\"\r\nContent-Type: application/pdf\r\n">, "id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_file.html.erb (0.1ms)
Completed 200 OK in 512ms (Views: 0.6ms | ActiveRecord: 503.4ms)
Started POST "/redmine/projects/test1/dmsf/upload/files" for 10.170.24.47 at 2017-05-23 17:30:52 +0800
Processing by DmsfUploadController#upload_files as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"ceo3q4xQGBQHmKHfRdGIO4/7TBfnR1xSLhJROKkRWTzv53YglY3IRAhKE5jKLksnvAeu0a3afaWYUpqAwTjXRA==", "view_mode_o_1bgqa8ohe14kv176m1tls159tejp1"=>"on", "o_1bgqa8ohe14kv176m1tls159tejp1_count"=>"0", "uploaded"=>{"1"=>{"disk_filename"=>"170523173052_1409.1556.pdf", "content_type"=>"application/pdf", "original_filename"=>"1409.1556.pdf"}}, "id"=>"test1"}
  Current user: qinhao (id=7)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_upload_file.html.erb (7.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_files.html.erb within layouts/base (9.7ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.3ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_repobrowser/app/views/repobrowser/_toolbarmod.erb (1.3ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.3ms)
Completed 200 OK in 96ms (Views: 37.2ms | ActiveRecord: 48.7ms)
Started POST "/redmine/logs/show" for 10.170.24.47 at 2017-05-23 17:31:05 +0800
Processing by LogsController#show as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"ZY4Mr2dth60Qol9VaDzQImGpfL26fPfBZ7Zwn7NbaMP7g00kfrBX/R9w7RLnwxM+UlWee/Dh1jbR9rsn23Lmuw==", "path"=>"/home/qin/Bitnami/apps/redmine/htdocs/log/production.log"}
  Current user: qinhao (id=7)
`

**Comment by picman** [comment]
ERR_EMPTY_RESPONSE is a client problem. Please check on the Internet.

**Comment by ThinkingHeart** [comment]
It could upload file and enter commit page, but when i clicked 'commit' button, there would  a  ERR_EMPTY_RESPONSE.

**Comment by picman** [comment]
I know. try to google ERR_EMPTY_RESPONSE.

**Comment by ThinkingHeart** [comment]
This problem appear other client. And the uploaded file  could't appear in Documents.I have installed many plugin in redmine. It my be a compatibility problem, it can't be repaired when I reinstalled.
