### ISSUE TITLE
Can't uninstall redmine dmsf in Bitnami

### ISSUE THREAD

**Issue by ThinkingHeart** [danmunn/redmine_dmsf#725]
when I executed 'rake redmine:plugins:migrate NAME=redmine_dmsf VERSION=0 RAILS_ENV=production'. there would throw a error： ‘StandardError: An error has occurred, all later migrations canceled:

No such column: dmsf_file_revisions.boolean
’

**Comment by picman** [comment]
It has been already fixed. Either pull devel-1.6.0 or apply the change done in the following commit manually.

9d4c57ab7a19e890e3ada59285c0ad7e315d273
