### ISSUE TITLE
Keep the modification date of the file

### ISSUE THREAD

**Issue by i-and** [danmunn/redmine_dmsf#726]
Good day! Is it possible to preserve the modification date of the file when it is downloading in a zip archive, a separate file or using Webdav? Now the file's modification date matches the date of the downloading, which is not very convenient in the process of further analysis of files.

**Comment by picman** [comment]
1. I think, that it is a standard behaviour. If you download a file from the Internet the modification date is set to the time of downloading.
2. Ruby zip library doesn't serve an option to keep modification dates of the zipped files.

**Comment by i-and** [comment]
However, the archiver (e.g. 7-zip) preserve the modification date of the archive files. And I think this is a logical behavior. In this regard, I have a few suggestions: 
1) add to library "Ruby zip" option to preserve the modification dates of files (may be to initiate a change request to the library authors?); 
2) to Implement in DMSF following capability: automatic packaging into a zip archive files that are added to the database DMSF. The specified files must conform to the mask (set in the plugin settings). The proposed approach will allow to implement the idea of the immutability included in the archive file with any download method. Also the size of the database DMSF will be reduced because the files will be stored on the server in the form of zip-archives.

**Comment by graywolf** [comment]
@picman 

> 1.

if you add files to zip and pretty common to preserve their mtime

> 2.

while not exactly straightforward, it very possible to do so

    Zip::File.open('a.zip', Zip::File::CREATE) do |zf|
      zf.add('a', 'a')
      zf.get_entry('a').instance_eval { @time = Zip::DOSTime.new(2001, 12, 1, 1, 1, 1, 0) }
    end

you can just fill the `Zip::DOSTime.new` with data acquired from `File.mtime`...

**Comment by picman** [comment]
I've set the modification date for files and folders to the value displayed in the column **Modified** in UI.
