### ISSUE TITLE
Ability to disable document upload in issues

### ISSUE THREAD

**Issue by hameno** [danmunn/redmine_dmsf#727]
I was very surprised to see, that a new documents upload is now visible in all ticket forms. I cannot find any option to disable this, even disabling the module for the project does not work. How can I disable this?

**Comment by hameno** [comment]
I should add, that this also breaks the normal drag and drop upload. The files won't be uploaded to the issue.

**Comment by picman** [comment]
Just disable "Act as attachable" option in the plugin options.

**Comment by hameno** [comment]
I'm using 1.5.9 and cannot see any option like that.

**Comment by picman** [comment]
Pull the master branch again.

**Comment by hameno** [comment]
I'm on tag v1.5.9, I will test that later this evening

**Comment by hameno** [comment]
Thanks, that worked
