### ISSUE TITLE
Add users for new step in Worflow Dialogue

### ISSUE THREAD

**Issue by mrazek** [danmunn/redmine_dmsf#731]
![firefox_2017-06-01_11-27-42](https://cloud.githubusercontent.com/assets/12605987/26673651/f3c6dfaa-46bd-11e7-9a01-94520ff4ef7c.png)

It is impossible to assign users from different pages to one step of workflow. If I search for them, only users chosen in last page will be added to workflow. There are only 10 users per page. Either setting of count of users per page or any other mode to select users for one step would be great.

**Comment by picman** [comment]
You're right. I've extended the limit from 10 to 100. Maybe it would make sense to create such an issue in Redmine project because a selection disappear in their dialogues after changing tab too.
