### ISSUE TITLE
DMSF uploader seems to override built in uploader.

### ISSUE THREAD

**Issue by errodr** [danmunn/redmine_dmsf#734]
My configuration:

```
  Redmine version                3.3.3.stable
  Ruby version                   2.2.7-p470 (2017-03-28) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
  ---
  redmine_dmsf                   1.5.9
```

When a user tries to upload a file against an issue by dragging and dropping a file onto the **edit** form the DMSF plugin appears to override the default drag and drop uploader. The file **is** uploaded but it is **not** associated with the issue (it is unreachable). Using the non drag and drop upload method works correctly.

I verified the behavior by deleting the `dmsf_uploader` div from the page and was then able to upload via drag and drop a file and have it linked to the issue.

Any idea on a workaround or a setting I missed?

**Comment by picman** [comment]
Could you test it in v1.6.0-devel? This feature has been completely re-written.

**Comment by picman** [comment]
No feedback => closing.
