### ISSUE TITLE
v1.5.8 -> 1.6.0 upgrade procedure

### ISSUE THREAD

**Issue by dinya** [danmunn/redmine_dmsf#735]
I use DMSF v1.5.8 and I want to try DMSF v1.6.0.

Should I first upgrade 1.5.8 -> 1.5.9 and then 1.5.9 -> 1.6.0? Or just enough 1.5.8 -> 1.6.0 ?

**Comment by picman** [comment]
You can upgrade directly to 1.6.0. Please keep in mind that 1.6.0 is a development version, not yet released.
