### ISSUE TITLE
Setting tmp folder path via ENV 

### ISSUE THREAD

**Issue by caleno** [danmunn/redmine_dmsf#736]
Hi, 

This more a question and a feature request. 

Is it possible to set the tmp folder for DMSF only? 
Would it be possible and/or convenient to be able to set the path using a env variable like DMSF_TMP.

Or implement a logic like this: if ENV set then use that else use system/default. 

The problem I'm facing is that I'm using a proxy to multiple servers and uploading a file throws an error since the file is uploaded to server A but the move operation is carried out on serve B. => error 500. 

Br,
Lennart

**Comment by caleno** [comment]
I managed to find a workaround, I shall see if I can find a better and more dynamic solution. 
And I'm not sure if this changes the tmp for the whole application. (?)

I put this in the bottom of init.rb

```
class Dir
  def self.tmpdir
    "/var/www/redmine/files/.dmsf_tmp"
  end
end
```

**Comment by caleno** [comment]
`# Set DMSF tmp folder
def Dir::tmpdir
  if $SAFE > 0
    tmp = @@systmpdir
  else
    tmp = nil
    for dir in [ENV['DMSF_TMPDIR'], '/var/www/redmine/files/.dmsf_tmp', ENV['TMP'], ENV['TEMP'], '/tmp', './files/tmp', './files']
      next if !dir
      dir = File.expand_path(dir)
      if stat = File.stat(dir) and stat.directory? and stat.writable? and
          (!stat.world_writable? or stat.sticky?)
        tmp = dir
        break
      end rescue nil
    end
    raise ArgumentError, "could not find a temporary directory" if !tmp
    tmp
  end
end`

**Comment by picman** [comment]
Wouldn't be easier to add it to the plugin settings?

**Comment by caleno** [comment]
Absolutely, that would be much easier and better.

**Comment by picman** [comment]
Temporary files folder is now an option in the plugin's settings.

**Comment by picman** [comment]
Originally, I used OS's temp folder, e.g. /tmp. If I replace that with Redmine's temp folder, it would be a solution for your problem too, right? If you have multiple servers, the Redmine's temp folder must be shared among all the servers. So, I'm removing the DMSF' temp folder with Redmine's temp folder and removing this option from the plugin's settings.
