### ISSUE TITLE
Upload failure

### ISSUE THREAD

**Issue by flybyray** [danmunn/redmine_dmsf#738]
`

> `Permission denied @ sys_fail2 - (C:/Users/admin/AppData/Local/Temp/RackMultipart20170622-2240-10z3037.zip, C:/dev/src/service/redmine/files/dmsf/2017/06/170622001752_6_UnlimitedJCEPolicyJDK7.zip)`

Tried to execute line 99: `FileUtils.mv commited_file[:tempfile_path], new_revision.disk_file`
from https://github.com/danmunn/redmine_dmsf/blob/devel-1.6.0/app/helpers/dmsf_upload_helper.rb#L99

The file `C:/Users/admin/AppData/Local/Temp/RackMultipart20170622-2240-10z3037.zip` exists.

A newfile record is saved but the file is not moved.

Are there any problems with windows and file management abstraction in FileUtils?

**Comment by flybyray** [comment]
maybe the file at `commited_file[:tempfile_path]` is not closed, therefore the `FileUtils.mv` crashes on windows.
I tested that with IRB
https://gist.github.com/flybyray/7f1a5a1278974f2c2f302e0c546121eb

**Comment by picman** [comment]
It seems to be a Windows related problem. Fortunately, I have no access to a Windows computer. Could you test the following workaround?
```ruby
f = File.new(commited_file[:tempfile_path])
f.close
if f.closed?
  FileUtils.mv commited_file[:tempfile_path], new_revision.disk_file
else
  FileUtils.cp_r commited_file[:tempfile_path], new_revision.disk_file
end
```

**Comment by flybyray** [comment]
sorry but this does not help. a new_file_revision is created without having a file attached. therefore i can try to upload a new version and the same error on other source code location happen.
https://github.com/danmunn/redmine_dmsf/blob/devel-1.6.0/app/controllers/dmsf_files_controller.rb#L152

I think it should have a more general approach to fix that bug

maybe somewhat related to Good practice of using ruby tempfile:
https://docs.ruby-lang.org/en/2.2.0/Tempfile.html#class-Tempfile-label-Explicit+close

**Comment by flybyray** [comment]
https://gist.github.com/flybyray/59f2ee5170e3a785f44f92a53a11012a

This works for the initial upload.
But if i create a new version it uses the attachment way to create a dmsf file.
very strange two different uploads procedures for same plugin. will that change someday?
  - if not we must check what is going on here

```
Errno::ENOENT (No such file or directory @ sys_fail2 - (C:/Users/admin/AppData/Local/Temp/170626165647_LICENSE, C:/dev/src/service.synapplix.de/realis/redmine/files/dmsf/2017/06/170626165647_26_LICENSE)):
  plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:152:in `create_revision'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


  Rendered C:/dev/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (1.0ms)
  Rendered C:/dev/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (12.0ms)
  Rendered C:/dev/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (3.0ms)
  Rendered C:/dev/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (460.3ms)

```

As you can see it searches the file within temp folder but the file is uploaded to redmine attachment dir
`redmine\files\2017\06\170626165625_LICENSE`

**Comment by flybyray** [comment]
`disk_file` is a method which generates some path with tmpdir as prefix.
https://github.com/danmunn/redmine_dmsf/blob/bf282ff2808005a58746c594621d40fee00b0435/app/models/dmsf_upload.rb#L39

called from here:
https://github.com/danmunn/redmine_dmsf/blob/bf282ff2808005a58746c594621d40fee00b0435/app/controllers/dmsf_files_controller.rb#L152

in case of an attackment upload it should be `@tempfile_path`
https://github.com/danmunn/redmine_dmsf/blob/bf282ff2808005a58746c594621d40fee00b0435/app/models/dmsf_upload.rb#L50

**Comment by flybyray** [comment]
here a patch that will work (but md5 and mime-type are not correct)
https://gist.github.com/flybyray/29023576da39ef14e514dc7a3b67bbdc

[video](https://drive.google.com/file/d/0B6SQaK_sFvnaMHdCaHBCWE9iaGs/view?usp=sharing)

**Comment by picman** [comment]
There are two ways of uploading:
1. The Redmine way via attachments. Used in the main view if you switch the upload control to the classic one and in an existing documents details to upload a new content.
2. DMSF way used as default in the main view. The main view can be used for new documents upload but also for existing documents updating. If you upload a document of the same file name as an existing one, a new revison of the document is created.

Do you have problems with both ways of document uploading or just with the Redmine way?

This problem seems to be Related to MS Windows only. I've no such environment to test it. So I appreciate your help here.

**Comment by flybyray** [comment]
With both:

1. was solved with Line 13 https://gist.github.com/flybyray/29023576da39ef14e514dc7a3b67bbdc#file-some_patch_for_danmunn_redmine_dmsf_issues_738__not_complete____md5_hash_and_mime_type_is_-patch-L13

2. was solved with Line 44 https://gist.github.com/flybyray/29023576da39ef14e514dc7a3b67bbdc#file-some_patch_for_danmunn_redmine_dmsf_issues_738__not_complete____md5_hash_and_mime_type_is_-patch-L44

I encountered first the second fixed it than used the "existing documents details to upload a new content" and I needed to change the tempfile

I have no virtual vm of my windows environment (perhaps i find sometime to setup one).
Please let me know if there is anything I should check.

**Comment by picman** [comment]
Source codes modified accordingly. Please re-test in your environment.

**Comment by flybyray** [comment]
test: ok
thanks for correcting the digest calculation too
