### ISSUE TITLE
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by Shaiken** [danmunn/redmine_dmsf#741]
when set 
Run $ bundle install

![image](https://user-images.githubusercontent.com/30071132/28060276-44bb6d62-6659-11e7-9ec7-85d5fd2aadfe.png)

**Comment by picman** [comment]
The problem that you can't build xapian-full-alaveteli gem is related to your environment not DMSF plugin, I'm afraid. Either find the reason why it can't be built or run the installation without xapian:
```bash
bundle install --without xapian
```
