### ISSUE TITLE
WebDAV PROPSTATS and PROPFIND caching change

### ISSUE THREAD

**Issue by picman** [danmunn/redmine_dmsf#742]
I'd like to switch the WebDAV caching to _Rails.cache_ instead of our own implementation currently present in the plugin.
=>
1. _Rails.cache_ is directly used instead of _@@WebDAVCache_ in  _redmine_dmsf/lib/redmine_dmsf/webdav/cache.rb_.
2. There are no more option to set _memcached_ servers or to disable caching in the plugin's settings.
3. The common _Rails.cache_ is used. It can be initialized in _config/additional_environment.rb_, e.g. _config.cache_store = :mem_cache_store_ (:_file_store is default_)

Is there any drawback?

Related to #614.

**Comment by picman** [comment]
Implemented, tested, everything seems to be Okay.

**Comment by carlolars** [comment]
> Is there any drawback?
Only potential drawback I can see is that the dmsf-webdav will now compete with the rest of Redmine for the available cache memory.
I have no idea on how much caching the redmine application and all other plugins do so I played it safe and just created a dedicated cache.

**Comment by picman** [comment]
Hm, it shouldn't be problem, I think. Moreover, it is logical that one application uses one common cache.
The reason why I needed to change your original implementation was to get rid of all @@variables as they cause problems when multiple instances of Redmine are run on the same machine.
