### ISSUE TITLE
Full stops within filename lead to false extensions

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#744]
If full stops are used within filenames the file extension shows the wrong value.

Example:
Filename: The.Big.Bang.Theory.S05E12.mkv
Shows this extension: Big.Bang.Theory.S05E12.mkv
Correct extension: mkv

![grafik](https://user-images.githubusercontent.com/7224922/28908313-3bf1fc74-7823-11e7-939d-4500dba52af1.png)

**Comment by picman** [comment]
Fixed. Thank you for the bug report.
