### ISSUE TITLE
Thumbnail macro: size paramter not respected

### ISSUE THREAD

**Issue by tofi86** [danmunn/redmine_dmsf#746]
When inserting a DMSF thumbnail in a wiki page, the thumbnail size is not set. The Thumbnail always shows as 200px.

```
{{dmsftn(1, size=300)}}
```

results in:

```html
<a target="_blank" title="" data-downloadurl="image/png:screenshot.png:/dmsf/files/1/view" href="/dmsf/files/1/view">
  <img alt="screenshot" src="/dmsf/files/1/view" width="auto" height="200">
</a>
```

**Comment by tofi86** [comment]
This happens at least with Redmine 3.4.2, I haven't tried other versions.

**Comment by picman** [comment]
Fixed. Thank you for the bug report.
