### ISSUE TITLE
Background icon repeating in admin panel (Redmine 3.4.2)

### ISSUE THREAD

**Issue by jmfarina** [danmunn/redmine_dmsf#747]
Seems related to #548, but in a different place: in admin panel (/admin), the approval workflows button's icon is repeating itself with Redmine's default themes (and others as well, though I've seen at least one that works out of the box).
Adding the "icon" class to the a element fixes the problem:

`<li><a class="icon dmsf-approvalworkflows" href="/dmsf_workflows">Approval workflows</a></li>`

**Comment by picman** [comment]
It has been already fixed in v1.6.0. v1.5.9 is older than Redmine 3.4.x and therefore not compatible.
