### ISSUE TITLE
REST API - List of documents in folder fails when using folder_title.

### ISSUE THREAD

**Issue by owbmoore** [danmunn/redmine_dmsf#749]
Trying to follow the API documentation and found this problem:

The first commands, from the API documentation work just fine.
GET /projects/12/dmsf.xml (the root folder)
GET /projects/12/dmsf.xml?folder_id=51 (a sub-folder)

Truncated output of the first list is this:
```
<dmsf>
<dmsf_folders total_count="2" type="array">
<folder>
<id>1</id>
<title>mine</title>
</folder>
<folder>
<id>2</id>
<title>rest_api</title>
</folder>
</dmsf_folders>
```

But when moving to the next section, folder_id worked but folder_title did not.

GET //projects/12/dmsf.xml?folder_title=folder1 (by folder name)
GET //projects/12/dmsf.xml?folder_id=1 (by folder_id)

Tried these with folder_id=1 which was successful
And with folder_title=mine which returns 404

Any Idea what I could be doing wrong?

**Comment by picman** [comment]
It seems to be working on my computer. The only problem I have found is if you use project's identifier instead of id. Can't it be your case?

```bash
curl -v -H "Content-Type: application/json" -X GET -u ***:*** http://localhost:3000/projects/1995/dmsf.json?folder_title=f1
>> HTTP/1.1 200 OK
```
```bash
curl -v -H "Content-Type: application/json" -X GET -u ***:*** http://localhost:3000/projects/c1/dmsf.json?folder_title=f1
>> HTTP/1.1 404 Not Found
```

Also be careful with folder's title format, e.g. spaces, _my title_ must be entered as _Updated%20title_.

Don't forget to check the production.log file.

**Comment by owbmoore** [comment]
Using the project id instead of the identifier in the url did fix it.   Threw me off because using the project identifier when creating folders and several other API calls worked just fine.

**Comment by picman** [comment]
I've modified the code in order to accept id and identifier as well.
