### ISSUE TITLE
How are files uploaded using the REST API?

### ISSUE THREAD

**Issue by owbmoore** [danmunn/redmine_dmsf#753]
Question:
  I have been unsuccessful in uploading a file using the following commands.

1.  curl -v -H "Content-Type: application/xml" -X POST --data-binary "@PV.pdf" -u xxxx:xxxx http://x.x.x.x:3000/projects/1/dmsf/upload.xml?filename=PV.pdf
  Results in:  HTTP/1.1 400 Bad Request

Production.log output
```
ActionDispatch::ParamsParser::ParseError (#<ArgumentError: invalid byte sequence in UTF-8>...
```

2. curl -v -H "Content-Type: application/xml" -X POST --data-binary "@x.xml" -u xxxx:xxxx http://x.x.x.x:3000/projects/1/dmsf/upload.xml?filename=x.xml

Content of x.xml 
```
<tag>it</tag>
```

Production.log output
```
Started POST "/projects/1/dmsf/upload.xml?filename=x.xml" for x.x.x.x at 2017-08-22 17:04:49 +0000
Processing by DmsfUploadController#upload as XML
  Parameters: {"tag"=>"it", "filename"=>"x.xml", "id"=>"1"}
  Current user: admin (id=1)
  Rendered text template (0.0ms)
Completed 406 Not Acceptable in 8ms (Views: 0.2ms | ActiveRecord: 5.2ms)
```   

3. curl -v -H "Content-Type: application/xml" -X POST --data-binary "@file.xml" -u xxxx:xxxx http://x.x.x.x:3000/projects/1/dmsf/upload.xml?filename=file.xml

```
<?xml version="1.0" encoding="utf-8" ?>
<attachments>
  <folder_id/>
  <uploaded_file>
    <disk_filename>PV.pdf</disk_filename>
    <name>PV.pdf</name>
    <title>PV</title>
    <description>REST API TEST</description>
    <comment>From API Documentation</comment>
    <version/>
  </uploaded_file>
</attachments>
```

Production.log output
```
Started POST "/projects/1/dmsf/upload.xml?filename=file.xml" for x.x.x.x at 2017-08-22 17:13:56 +0000
Processing by DmsfUploadController#upload as XML
  Parameters: {"attachments"=>{"folder_id"=>nil, "uploaded_file"=>{"disk_filename"=>"PV.pdf", "name"=>"PV.pdf", "title"=>"PV", "description"=>"REST API TEST", "comment"=>"From API Documentation", "version"=>nil}}, "filename"=>"file.xml", "id"=>"1"}
  Current user: admin (id=1)
  Rendered text template (0.0ms)
Completed 406 Not Acceptable in 4ms (Views: 0.2ms | ActiveRecord: 1.6ms)
```

 What is the correct way to upload a file?

**Comment by picman** [comment]
See extra/api/api_client.sh:

```bash
# 4. Upload a document into a given folder or the root folder
curl --data-binary "@cat.gif" -H "Content-Type: application/octet-stream" -X POST -u ${1}:${2} http://localhost:3000/projects/12/dmsf/upload.xml?filename=cat.gif
curl -v -H "Content-Type: application/xml" -X POST --data "@file.xml" -u ${1}:${2} http://localhost:3000/projects/12/dmsf/commit.xml
```

The upload is split into two steps. First you get a token an then using this token you commit the uploaded file.

See the following wiki page: https://github.com/danmunn/redmine_dmsf/wiki/REST-API#upload-a-document-into-a-given-folder-or-the-root-folder

**Comment by owbmoore** [comment]
Thanks, your comments and api_client.sh provided everything I needed to get this right.  Wish I had seen the script earlier!
