### ISSUE TITLE
How to set the document version on upload using REST API.

### ISSUE THREAD

**Issue by owbmoore** [danmunn/redmine_dmsf#757]
Several subquestions here.

1.  How can the version number be set to 1.0 when a new document is uploaded using the REST API?

2.  How is incrementing of the version number supposed to happen on subsequent uploads?  Setting the version tag in the commit xml does not behave as expected.

Example version number updates..

| Current Version   |  Commit XML     |  Result Version | Note|
|----------|:-------------:|------:|-------:|
| none |  1.0 | 0.0 | failed to honor setting
| 0.0 | 0.0 | 0.0 | no change
| 0.0 | 0.1 | 0.0 | no change
| 1.1 |  1.1 | 1.2 |   auto incremented
| 1.2 |  1.2 | 1.3 |  auto incremented
| 1.9 |  1.9 | 1.10 | auto incremented
| 1.10 |  2.0 | 2.0 |  increased major, minor to 0
| 2.0 | 2.0 | 2.0  |  failed to auto increment
| 2.0 | 2.1 | 3.0  |  major increased instead of minor
| 2.0 | 3.0 |  0.0 |  ???
| 2.1 | 3.0 |  0.0 |  ???

How exactly is the version number supposed to be controlled using the REST API?

**Comment by picman** [comment]
I thing that a custom version of an uploaded document should be specified as follows:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<attachments>
  <folder_id/>
  <uploaded_file>
    <disk_filename>cat.gif</disk_filename>
    <name>cat.gif</name>
    <title>cat.gif</title>
    <description>REST API</description>
    <comment>From API</comment>
    <version>3</version> <!-- It must be 3 (Custom version) -->
    <custom_version_major>2</custom_version_major> <!-- Major version -->
    <custom_version_minor>4</custom_version_minor> <!-- Minor version -->
    <token>15817.c49f68ff81b552d315927df2e27df506</token>
  </uploaded_file>
</attachments>
```

Please try it.

**Comment by owbmoore** [comment]
The above xml with version set to 3, and specifying the major/minor version does set the version as expected.  Thanks!

**Comment by picman** [comment]
I've updated the wiki accordingly.

https://github.com/danmunn/redmine_dmsf/wiki/REST-API
