### ISSUE TITLE
Error in template when retrieving details of a file in a subfolder

### ISSUE THREAD

**Issue by owbmoore** [danmunn/redmine_dmsf#758]
ActionView::Template::Error (undefined method `folder' for #<DmsfFile:0x007fc23ee96990>):  

Caused by this line when getting file details of a file that is in a subfolder of a project.  

```api.dmsf_folder_id @file.folder if @file.dmsf_folder_id```

in file ./app/views/dmsf_files/show.api.rsb

Changing the line to the following resolves the problem.  

 ```api.dmsf_folder_id @file.dmsf_folder_id if @file.dmsf_folder_id ```

**Comment by picman** [comment]
Fixed according your suggestion. Thank you for the bug report.
