### ISSUE TITLE
Hard links

### ISSUE THREAD

**Issue by dinya** [danmunn/redmine_dmsf#761]
If I'm not mistaken the current links are something like *nix symbolic links.

Is it possible to add "hard links"?

**Comment by picman** [comment]
Could you provide a specification how the "hard links" should behave?

**Comment by dinya** [comment]
@picman Dear Karel, are you still interested in my view on implementation after [your comment in #1105](https://github.com/danmunn/redmine_dmsf/issues/1105#issuecomment-1670700905)?

**Comment by picman** [comment]
No more support for Russians.
