### ISSUE TITLE
NoMethodError when migrating plugins

### ISSUE THREAD

**Issue by afaonline** [danmunn/redmine_dmsf#766]
Hello!

I am trying to install 1.6.0-master to Redmine 3.3.3, and after starting `bundle exec rake redmine:plugins:migrate RAILS_ENV="production"` I see the following error message:

```
NoMethodError: undefined method `safe_attributes' for #<Class:0x00000004ee0e90>
Did you mean?  cache_attributes
               scope_attributes
               cached_attributes
               scope_attributes?
               cache_attribute?
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/opt/redmine-3.3.3-0/apps/redmine/htdocs/plugins/redmine_dmsf/lib/redmine_dmsf/patches/user_preference_patch.rb:28:in `block in included'
/opt/redmine-3.3.3-0/apps/redmine/htdocs/plugins/redmine_dmsf/lib/redmine_dmsf/patches/user_preference_patch.rb:27:in `class_eval'
/opt/redmine-3.3.3-0/apps/redmine/htdocs/plugins/redmine_dmsf/lib/redmine_dmsf/patches/user_preference_patch.rb:27:in `included'
...
```

**Comment by picman** [comment]
Hmm :-( `include Redmine::SafeAttributes` is missing in the class UserPreferences. So DMSF 1.6.0 requires Redmine >= 3.4. I will change requirements of DMSF accordingly.
Either upgrade your Redmine to 3.4 or as a workaround you can comment out the lines 28 - 30 in _lib/redmine_dmsf/patches/user_preference_patch.rb_

```ruby
module RedmineDmsf
  module Patches
    module UserPreference

      def self.included(base)
        base.send(:include, InstanceMethods)
        base.class_eval do
          #safe_attributes 'dmsf_tree_view',
          #                'dmsf_attachments_upload_choice'
          #end
      end

      module InstanceMethods
```

**Comment by afaonline** [comment]
Thank you!

It seems that there's no need to comment out line 30, so one has to change the code this way (for Redmine 3.3.3):

```ruby
module RedmineDmsf
  module Patches
    module UserPreference

      def self.included(base)
        base.send(:include, InstanceMethods)
        base.class_eval do
          #safe_attributes 'dmsf_tree_view',
          #                'dmsf_attachments_upload_choice'
          end
      end

      module InstanceMethods
```

Plugin migration completes successfully after that change, but Redmine doesn't start anyway, Apache error log contains the following error:
```
Could not find dalli-2.7.6 in any of the sources (Bundler::GemNotFound)
<pre>  /opt/redmine-3.3.3-0/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/spec_set.rb:87:in `block in materialize&#39;
  /opt/redmine-3.3.3-0/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/spec_set.rb:80:in `map!&#39;
...
```

I think I should try to upgrade Redmine to 3.4

**Comment by picman** [comment]
You're right, I will modify my comment.
Have you run `bundle install`? gem dalli installed?

**Comment by afaonline** [comment]
Looks like I've messed up something with permissions last time, running `bundle install` under the wrong user. Now I have dalli gem installed, Redmine starts, DMSF settings page works fine.

Thank you!
