### ISSUE TITLE
The new directory structure was not applied when migrating to DMS 1.6.0

### ISSUE THREAD

**Issue by Atmis** [danmunn/redmine_dmsf#767]
Hello,

I am using Redmine 3.4 with DMSF, and despite there was no error during the plugin migration from 1.5.9 to 1.6.0, the file directory structure was not migrated.

We are on Windows

```
Environment:
Redmine version                3.4.2.stable
Ruby version                   2.3.3-p222 (2016-11-21) [x64-mingw32]
Rails version                  4.2.8
Environment                    production
Database adapter               Mysql2
```

Here is a PowerShell Script that manually update the directory structure of DMSF :

```
$sourceDir = 'c:\dmsf'
$targetDir = 'c:\dmsf'
Get-ChildItem -Path $sourceDir -file -recurse | foreach {
    If( -not $_.PSIsContainer)
    {
        $topath = $targetDir + "\20" + $_.Name.substring(0, 2)  + "\" + $_.Name.substring(2,2)  
        if(-not (Test-Path $topath))
        {
            mkdir $topath
        }   
        move $_.FullName $topath 
    }  
}
```

Hope this helps

**Comment by picman** [comment]
Hmm, this is bad (using Windows too ;-))

The document migration is implemented in _db/migrate/20170418104901_migrate_documents.rb_. There is quite a lot of messages and everything which might goes wrong is reported.

Really there were no messages during the migration?
Does _schema_migrations_ table contain a row _20170418104901-redmine_dmsf_?

**Comment by Atmis** [comment]
I know using Windows is bad, but I am not ready to change yet (My Redmine instance works flawlessly for 5 years now :-))

I checked in the database and I confirm that the row 20170418104901-redmine_dmsf exists in the schema_migrations table.
 
There were messages during the migration, but I didn't consider them as error messages (now that I see them in 20170418104901_migrate_documents.rb, I understand it was errors), and I haven't kept an output of those message. Unfortunately, I can't remember what these messages were exactly.

My production.log is also (it is setup to only log error messages).

**Comment by PedroTeixido** [comment]
I had the same problem on a linux machine.
I have migrated the windows powershell script to linux. Here it is in case it helps to anyone with the same issue.

sourceDir='/opt/bitnami/apps/redmine/htdocs/files/dmsf'
targetDir='/opt/bitnami/apps/redmine/htdocs/files/dmsf'

for targetFile in $(find $sourceDir -type f) ; do

  topath=$(echo "$targetDir/20$(echo $targetFile | xargs -n 1 basename | cut -c1-2)/$(echo $targetFile | xargs -n 1 basename | cut -c3-4)/")

  if [ ! -d "$topath" ]; then
    mkdir -p $topath
  fi

  mv $targetFile $topath
done

**Comment by picman** [comment]
Thank you for the script. Have you noticed any messages during the migration?

**Comment by PedroTeixido** [comment]
Hello Karel,

Sorry for the delay. I had to rolback the redmine to a backup I had before
installing the dmsf in order to re-execute it and save the logs.

My original redmine is a 2.6.2 and the new one is 3.4.2
I dediced to start with a fresh installation instead of updating it. So, I
started with a bitnami image
(https://bitnami.com/stack/redmine/virtual-machine)
and I have migrated the redmine DB and the files over to the new machine,
and them install dmsf. That means it's not really an upgrade, and this
maybe the reason to find this issue.

Anyway, I have attached the logs here.

I hope this helps,

   Pedro

**Comment by picman** [comment]
I think, I found the origin of problems with the document migration. I've swapped migrations _dmsf_file_container_rollback.rb_ and _migrate_documents.rb_.

**Comment by Hofei90** [comment]
Hello again,
wanted to let you know briefly, the migration of the files has now worked with the help of the linked script. An automatic migration, however, did not work. If there is a bug here or not I can't judge, so I just wanted to give feedback again.

https://github.com/danmunn/redmine_dmsf/issues/767#issuecomment-329832080

**Comment by carterb23** [comment]
Hi, 
I'm still struggling with the migration. I executed the script mentioned in the post and the folder structure is okay now. I still get 404 error when accessing files. What do I have to do, to re-migrate the database?

**Comment by carterb23** [comment]
Hi again,

in the end the above mentioned script worked for me. I just had to change the file owner and permission to www-data again. Furthermore to migrate the plugin/db I used "rake redmine:plugins:migrate RAILS_ENV=production". This is my working setup:

Environment:
Redmine version: 4.0.0.stable
Ruby version: 2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
Rails version: 5.2.2           
Redmine plugins:
redmine_dmsf: 2.0.1 (devel)

Thanks for the support!

**Comment by rteitge** [comment]
> I had the same problem on a linux machine. I have migrated the windows powershell script to linux. Here it is in case it helps to anyone with the same issue.
> 
> sourceDir='/opt/bitnami/apps/redmine/htdocs/files/dmsf' targetDir='/opt/bitnami/apps/redmine/htdocs/files/dmsf'
> 
> for targetFile in $(find $sourceDir -type f) ; do
> 
> topath=$(echo "$targetDir/20$(echo targetFile|xargs−n1basename|cut−c1−2)/(echo $targetFile | xargs -n 1 basename | cut -c3-4)/")
> 
> if [ ! -d "$topath" ]; then mkdir -p $topath fi
> 
> mv $targetFile $topath done

Github's formating this code little bit strange, that's why here's the code again :)

```sh
sourceDir='/usr/src/redmine/files/dmsf'
targetDir='/usr/src/redmine/files/dmsf'

for targetFile in $(find $sourceDir -type f) ; do

topath=$(echo "$targetDir/20$(echo $targetFile | xargs -n 1 basename | cut -c1-2)/$(echo $targetFile | xargs -n 1 basename | cut -c3-4)/")

if [ ! -d "$topath" ]; then
mkdir -p $topath
fi

mv $targetFile $topath
done
```
