### ISSUE TITLE
REST API document download not working

### ISSUE THREAD

**Issue by activatekillswitch** [danmunn/redmine_dmsf#768]
Redmine 3.4.2
DMSF 1.6.0

Using the REST API.

`redmine/dmsf/files/xyz.xml` returns the expected XML file with the correct information.

``` XML
<dmsf_file>
<id>xyz</id>
<name>abc.docx</name>
<project_id>xy</project_id>
<version>0.1</version>
<mime_type>
application/vnd.openxmlformats-officedocument.wordprocessingml.document
</mime_type>
<digest>ef74fd2d8eef313c2d0a82631dd18540</digest>
<size>1001774</size>
<description/>
<content_url>/dmsf/files/xyz/download</content_url>
</dmsf_file>
```
`/dmsf/files/xyz/download` returns the HTML page instead of the document as expected.

**Comment by picman** [comment]
The document download was not working. I've fixed it. Pull the master branch again. BTW, you can't use the returned URL use for a direct download. You must use it in another API call to get the document. The right procedure is as follows:

Get the document's URL first:
```bash
curl -v -H "Content-Type: application/octet-stream" -X GET -u ***:*** http://localhost:3000/dmsf/files/120520.xml
```
You get:
```xml
...
<content_url>http://localhost:3000/dmsf/files/120520/download</content_url>
```
And, then:
```bash
curl -v -H "Content-Type: application/octet-stream" -X GET -u ***:*** http://localhost:3000/dmsf/files/120520/download > file.txt
```

**Comment by activatekillswitch** [comment]
Works perfectly now thanks.
