### ISSUE TITLE
Xapian

### ISSUE THREAD

**Issue by elmaogullari** [danmunn/redmine_dmsf#769]
I am trying to install dmsf with xapian. (On bitnami stack) 
Bitnami uses its ruby. 
Everything seems fine while installation. Dmsf plugin configuration page says xapian not available. 
It says xapian-alavetelli replaced by xapian-ruby but it is not in gemfile.

**Comment by picman** [comment]
No it's not. It's a software package. So, e.g.: `aptitude install ruby-xapian`.

**Comment by elmaogullari** [comment]
Hi,

Issue is not directly related with dmsf itself. I don't know well how ruby works so i don't want to say anyhting wrong. Previous method (alavetelli gem installation) was working with Bitnami stacks.
As you know bitnami use its ruby. Installing ruby-xapian is for built-in ruby. OS itself does not know bitnami ruby . 
Seems there are three options ; 
1. Not using Bitnami stack .
2. Not using xapian
3. Compiling binding of xapian from source with bitnami ruby .

Thanks,
Ersen

**Comment by picman** [comment]
I'm not familiar with Bitnami. However, to be able to index files you must use `omindex` utility coming from `xapian-omega` package. So, if you can install `xapian-omega`, why you can't install `ruby-xapian`?

Thy reason why I replaced `xapian-full-alaveteli` gem was that this gem is maintained not anymore. Moreover, is not compatible with the latest Xapian. (The gem supports Xapian 1.2.22, while the last release is 1.4.4). Alternative gems are not maintained too.

**Comment by albozo** [comment]
Hello,
Upgraded from 1.5.9, got this issue too on Ubuntu 16.04 with ruby installed via RVM.
Installing `ruby-xapian` didn't help - xapian is still not available.

**Comment by picman** [comment]
Hmm, very probably it's necessary to have `ruby` package from the system and not via RVM or Bitnami, so the packages `ruby` and `ruby-xapian`.

**Comment by albozo** [comment]
Ok, solved this issue by compiling ruby bindings from source manually.

**Comment by picman** [comment]
Did you use xapian-full-alaveteli + Xapian 1.2.22?

**Comment by albozo** [comment]
For DMSF 1.5.9 - yes. For 1.6.0 I use latest `Xapian 1.4.4` package (installed from backports repo) and Xapian ruby bindings compiled from source - and it works just fine.

**Comment by picman** [comment]
Not just user friendly, but a good solution. Thank you.
