### ISSUE TITLE
Upload fails when using modern interface

### ISSUE THREAD

**Issue by matthewfu** [danmunn/redmine_dmsf#770]
Hello there,

here is the error message I've got:

> Started POST "/projects/redmine_test/dmsf/upload/file" for 118.169.70.147 at 2017-09-18 00:10:17 +0800
> Processing by DmsfUploadController#upload_file as */*
>   Parameters: {"name"=>"vod_numbers3ministry.jpg", "authenticity_token"=>"alivFOirHmgmlVyes9j5SEg++DsGZQdOk/A4F6Kdi/xRizsWiGjAXXe0RXVA6CTWzosPDjvEJm4yyz6wvP8ijw==", "file"=>#<ActionDispatch::Http::UploadedFile:0xececc4c @tempfile=#<Tempfile:/tmp/RackMultipart20170918-5771-7448rd.jpg>, @original_filename="vod_numbers3ministry.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"vod_numbers3ministry.jpg\"\r\nContent-Type: image/jpeg\r\n">, "id"=>"redmine_test"}
> 
>   
>   Current user: matthewfu.tw (id=8)
>   Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload_file.html.erb (1.5ms)
> Completed 200 OK in 179ms (Views: 122.1ms | ActiveRecord: 42.0ms)
> Started POST "/projects/redmine_test/dmsf/upload/files?folder_id=1" for 118.169.70.147 at 2017-09-18 00:10:17 +0800
> Processing by DmsfUploadController#upload_files as HTML
>   Parameters: {"utf8"=>"✓", "authenticity_token"=>"alivFOirHmgmlVyes9j5SEg++DsGZQdOk/A4F6Kdi/xRizsWiGjAXXe0RXVA6CTWzosPDjvEJm4yyz6wvP8ijw==", "view_mode_o_1bq89lntb1np59i4mo31beg1j2cf"=>"on", "o_1bq89lntb1np59i4mo31beg1j2cf_count"=>"0", "uploaded"=>{"1"=>{"disk_filename"=>"170918001017_vod_numbers3ministry.jpg", "content_type"=>"image/jpeg", "original_filename"=>"vod_numbers3ministry.jpg", "tempfile_path"=>"/tmp/RackMultipart20170918-5771-7448rd.jpg"}}, "folder_id"=>"1", "id"=>"redmine_test"}
>   Current user: matthewfu.tw (id=8)
> Completed 500 Internal Server Error in 129ms (ActiveRecord: 111.1ms)
> 
> Errno::ENOENT (No such file or directory @ rb_file_s_size - /tmp/RackMultipart20170918-5771-7448rd.jpg):
>   plugins/redmine_dmsf/app/models/dmsf_upload.rb:70:in `size'
>   plugins/redmine_dmsf/app/models/dmsf_upload.rb:70:in `initialize'
>   plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:57:in `new'
>   plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:57:in `block in upload_files'
>   plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:56:in `each_value'
>   plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:56:in `upload_files'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

No error when using classic UI. No error on development only happens on production.

Please help.

Here is my settings:

Redmine:   3.4.2.stable
DMSF: 1.6.0
Ruby: ruby-2.3.3

**Comment by picman** [comment]
Related to #774.
