### ISSUE TITLE
CAST(title as DECIMAL) is syntax error for numeric in postgresql 9.6.5

### ISSUE THREAD

**Issue by VVD** [danmunn/redmine_dmsf#775]
Redmine 3.4.2, dmsf 1.6.0, postgresql 9.6.5, ruby 2.4.2, FreeBSD 11.1 amd64.

If "Act as attachable" is on and project have issues with attached files via dmsf, then redmine show http error 500 for any issue.
log/production.log say something like: ERROR: CAST(title as DECIMAL) is syntax error for type numeric: "8939 - test"

This patch for file lib/redmine_dmsf/patches/issue_patch.rb fixed this error:
```
- folder = DmsfFolder.system.where(['project_id = ? AND dmsf_folder_id = ? AND CAST(title AS DECIMAL) = ?',
+ folder = DmsfFolder.system.where(['project_id = ? AND dmsf_folder_id = ? AND CAST(SPLIT_PART(title, \' \', 1) AS DECIMAL) = ?',
```

**Comment by picman** [comment]
I'm afraid that `SPLIT_PART` doesn't exist in MySQL. We'd need a patch compatible with other databases(MySQL, SQLite).

**Comment by picman** [comment]
How about the following a bit more general solution independent on the database engine:

```ruby
folder = DmsfFolder.system.where(['project_id = ? AND dmsf_folder_id = ? AND title LIKE "#{self.id} - %", self.project_id, parent.id]).first
```

**Comment by VVD** [comment]
Ye, my patch is a dirty hack for explain bug only.
Your fix is better!

**Comment by VVD** [comment]
Your patch have errors:
1) quotes after LIKE must be ', but not "
2) you lose symbol ' in end of SQL statement
3) it just don't work after fix 1) and 2) :-D

This patch work for me:
```
folder = DmsfFolder.system.where(['project_id = ? AND dmsf_folder_id = ? AND title LIKE \'? - %\'', self.project_id, parent.id, self.id]).first
```

**Comment by picman** [comment]
Fixed.
