### ISSUE TITLE
Directory moving between projects

### ISSUE THREAD

**Issue by dinya** [danmunn/redmine_dmsf#776]
Is it possible to move directory between projects?

I can't find such tool in web interface (per project only).

When I copy directory with files from one to another project DMSF 1.5.9 creates new (new id) directory with the same name, but moves files correctly (the same name and id)

I use DMSF 1.5.9, Redmine 3.3.

**Comment by picman** [comment]
There is no such possibility, I'm afraid. You must copy the folder and then delete it.

**Comment by picman** [comment]
Implemented when you click on **Copy/Move**.
