### ISSUE TITLE
environment.rb cannot be loaded

### ISSUE THREAD

**Issue by itadminatitgroup** [danmunn/redmine_dmsf#779]
Hi, 

i have a Problem with the DMSF Plugin for Redmine and need help.

It says that the location of the environment.rb cannot be loaded.

but the path should be correct.

I created some screenshots of the config file and the paths.

![dmsf_config](https://user-images.githubusercontent.com/32698930/31429996-e0fa4fa0-ae6f-11e7-995e-2311d6db9a15.png)
![environment rb_not_loaded](https://user-images.githubusercontent.com/32698930/31429997-e118f608-ae6f-11e7-9105-adb9798038fc.png)
![path_to_environment rb](https://user-images.githubusercontent.com/32698930/31429998-e134d79c-ae6f-11e7-9e52-f2433ea6a53b.png)

thanks in advance for any help.

**Comment by picman** [comment]
I personally see no problem in your screen-shots and have no idea what is wrong. Do Redmine and the plugin work?

**Comment by itadminatitgroup** [comment]
Redmine is working fine and the Plugin is shown in the Administration section in Redmine and is working.
![dmsf](https://user-images.githubusercontent.com/32698930/31498558-850a3072-af62-11e7-90a2-137438ce6ec6.png)
Only Xapian for the Full-text Search isn't working

**Comment by picman** [comment]
As a workaround you can use directly the command `omindex` instead of `xapian_indexer.rb` which is a wrapper of the command only. E.g.:
```
omindex -s english --db /_daten1/bitnami_redmine/apps/redmine/htdocs/dmsf-index /_daten1/bitnami_redmine/apps/redmine/htdocs/files/dmsf --url / --depth-limit=0 -v
```

**Comment by itadminatitgroup** [comment]
thanks for your help and sorry for my late response.
i tried the command and it runs successfully it indexed the files but when i try to search inside Redmine
it's not showing any results.

**Comment by picman** [comment]
**Search titles only** unchecked and **DMS files** checked?

**Comment by itadminatitgroup** [comment]
search titles only is unchecked.
where can i check the DMS files? couldn't find the option

**Comment by picman** [comment]
There should be two new options added by the plugin at the end of the check box list, **Documents** and **Folders**.

**Comment by itadminatitgroup** [comment]
yes the two new options are checked.
i made two screenshots one is showing the search results and the other is showing the files inside the files/dmsf Folder. 
![dmfs_file](https://user-images.githubusercontent.com/32698930/31879847-f916b416-b7de-11e7-92a5-e795a6c1df91.PNG)
![search](https://user-images.githubusercontent.com/32698930/31879849-f9329794-b7de-11e7-9410-f3e71706ee9f.png)

**Comment by picman** [comment]
Something wrong with your documents. If you upload a document via DMSF plugin, it should be stored in a path which looks like `dmsf/2017/10/Test.txt` and not `dmsf/Test.txt`.

**Comment by itadminatitgroup** [comment]
okay i can now upload files with DMS but when i upload it shows me this error.
Permission denied @ rb_sysopen - /_daten1/bitnami_redmine/apps/redmine/htdocs/files/dmsf/2017/10/171023111331_2_ps_Script.txt
Some Files couldn't be committed validation error: ps_Script.txt

**Comment by picman** [comment]
The error message says that the web server user is not allowed to write to _/_daten1/bitnami_redmine/apps/redmine/htdocs/files/dmsf/2017/10/_. E.g. if your web server user is _www-data_, _www-data_ must be permitted to write and read _/_daten1/bitnami_redmine/apps/redmine/htdocs/files/dmsf/_.

**Comment by itadminatitgroup** [comment]
Hi,
i changed the Permissions but the problem still exists.
it shows me the same error

**Comment by picman** [comment]
`chown -R www-data:www-data files/dmsf` ?
Upload via the classic interface is working? (there is a option to change the upload controll).
Please post a bugger chunk of the production.log related to the issue.

**Comment by itadminatitgroup** [comment]
i tried the modern and the classic interface both not working.
here is the log file: 
![log](https://user-images.githubusercontent.com/32698930/31988418-4ee23618-b96f-11e7-8428-c15b41648666.png)

**Comment by itadminatitgroup** [comment]
i get to diffrent errors. if i try to upload with the modern option it says  this:
Permission denied @ rb_sysopen - /_daten1/bitnami_redmine/apps/redmine/htdocs/files/dmsf/2017/10/171023111331_2_ps_Script.txt
if i try to upload with classic it says this:
Permission denied @ rb_file_s_rename - (/_daten1/bitnami_redmine/apps/redmine/htdocs/files/2017/10/171025101952_ps_Script.txt, /_daten1/bitnami_redmine/apps/redmine/htdocs/files/dmsf/2017/10/171025103844_2_ps_Script.txt)

**Comment by itadminatitgroup** [comment]
okay i fixed the error i can now upload the files. 
but i have an other problem. i want to search the text inside a file but it's not working.
any idea what is wrong? or any option i have to turn on? 
thanks a lot for the help so far :)

**Comment by picman** [comment]
1. Post you searching options.
2. Post the production.log.

**Comment by itadminatitgroup** [comment]
here is the file i want to search:
![searchfile](https://user-images.githubusercontent.com/32698930/31998381-f59bd19c-b98f-11e7-95d1-0479f3228034.png)
and here is the log:
![logfile](https://user-images.githubusercontent.com/32698930/31998389-ff526d2c-b98f-11e7-9b54-fac845ff20d4.png)

**Comment by picman** [comment]
Hm, nothing wrong in the screen-shots. Recommended steps:

1. See the output of the `omindex` command whether the file is indexed.
2. For the beginning would be better to search plain text without special characters such as `$` which might be misinterpreted as wildcard search characters.
3. Switch the log level to debug a check the `production.log` again. (`config.log_level = :info` in `config/additional_environment.rb`)

**Comment by picman** [comment]
No feedback => closing.
