### ISSUE TITLE
Control DMSF via REST API

### ISSUE THREAD

**Issue by mcondarelli** [danmunn/redmine_dmsf#78]
It would be very useful (to us, at least) if we could control DMSF via REST API (or some equivalent method).

The required actions would be:
* List Documents
* Download a Document (zipped?)
* Download s Directory (zipped)
* Upload a Document (new)
* Upload a Document (new version)
* Upload a (zipped) directory.

Is there some way to automatize the above operations?
How difficult would be to add REST compatibility?

**Comment by picman** [comment]
Done.
