### ISSUE TITLE
I can't upload the file!!!

### ISSUE THREAD

**Issue by Aryan15** [danmunn/redmine_dmsf#786]
Hi, 
Whenever upload the file, I get the following message : 

![image](https://user-images.githubusercontent.com/31335377/31649378-8afda948-b34d-11e7-8af1-851024946cf7.png)

I can click on the file name but get the following message, too : 

![image](https://user-images.githubusercontent.com/31335377/31649383-9707f964-b34d-11e7-97d8-0cf91b996ca7.png)

What should I do??? 

Here is my information for redmine : 

Environment:
  Redmine version                3.4.2.stable
  Ruby version                      2.3.3-p222 (2016-11-21) [i386-mingw32]
  Rails version                       4.2.8
  Environment                       production
  Database adapter               Mysql2

Redmine plugins:
  redmine_dmsf                     1.6.0

**Comment by picman** [comment]
Duplicates #774. Update your master branch.

**Comment by Aryan15** [comment]
Thank you for your response but I don't know how to update master branch....
Actually I'm so beginner...

**Comment by picman** [comment]
```
cd redmine/plugins/redmine_dmsf
git pull
service apache2 restart
```

**Comment by Atmis** [comment]
Hi Karel,

On my side, I have the same issue which appeared right after I upgraded to the latest master sunday evening (October 15th). I was already using 1.6.0 since its release.
I double checked the folder authorizations, but I can't fix the issue. Is there any other change regarding upload between original 1.6.0 and current master release ?

Thank you

![screenshot 2017-10-18 22_13_08 pma](https://user-images.githubusercontent.com/5329747/31740415-97017378-b451-11e7-8e63-08d99e2d99b1.png)

**Comment by Atmis** [comment]
I tried to change the temp folder by changing the TMPDIR variable, and moved it inside the redmine installation, but the error is still there.
![screenshot 2017-10-18 22_30_23 pma](https://user-images.githubusercontent.com/5329747/31741401-673c063c-b454-11e7-9353-be7f716c918b.png)
Here the tmpdir content :
![screenshot 2017-10-18 22_38_22 pma](https://user-images.githubusercontent.com/5329747/31741604-1f88b44c-b455-11e7-9f08-96c3fbe95b1a.png)

**Comment by picman** [comment]
No familiar with Windows, sorry. The present master branch has replaced the original movement, and as I've seen in the rails code renaming is called in fact, with copying. So I wonder who and where can call renaming on /tmp/RackMultipart..... That's really strange.
1. Ensure that you use the latest code. (git checkout master && git pull)
2. Post a part of production log related to an upload.

**Comment by picman** [comment]
As I've described in #774, the procedure of uploading is as follows. So no renaming of the original rack file.

1.  Rails creates a temporary file, e.g. tmp/RackMultipart20170928-8186-1ni6cmd.sh.
2.  DMSF creates an extra copy of this file, e.g. tmp/171006092835_cmd.sh.
3.  A user makes a commit and DMSF moves this extra copy into a new document, e.g. 2017/10/171006092835_1356_cmd.sh.

**Comment by picman** [comment]
All in all the webserver user must be permitted to manipulate with files in the temp folder. Please check.

**Comment by Atmis** [comment]
Ok, what I did :
- I pulled the current DMSF master
- Triple checked the folder authorization, which is correct and aligned with other folders that are written by redmine

Unfortunately, the error is still there.

Here is the log part regarding the upload (anonymized) :
```
Started POST "/projects/test/dmsf/upload/commit" for xxx.xxx.xxx.xx:xx at 2017-10-19 10:31:11 +0200
Processing by DmsfUploadController#commit_files as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"azertyuiop", "commited_files"=>{"0"=>{"disk_filename"=>"171019103107_test_file.pdf", "tempfile_path"=>"C:/inetpub/redmine/tmpdir/RackMultipart20171019-1512-11b8z0y.pdf", "size"=>"335215", "mime_type"=>"application/pdf", "title"=>"test file", "name"=>"test_file.pdf", "description"=>"", "version"=>"1", "custom_version_major"=>"2", "custom_version_minor"=>"1", "comment"=>""}}, "name"=>"327 ko", "commit"=>"Appliquer", "id"=>"test"}
  Current user: username (id=4)
Permission denied @ rb_file_s_rename - (C:/inetpub/redmine/tmpdir/RackMultipart20171019-1512-11b8z0y.pdf, C:/inetpub/redmine/files/dmsf/2017/10/171019103111_826_test_file.pdf)
Redirected to https://redmine.xxxxxxx.com/projects/test/dmsf
Completed 302 Found in 156ms (ActiveRecord: 78.4ms)
```

**Comment by picman** [comment]
I see the problem now. What a terrible bug! Please pull it test again.

**Comment by Atmis** [comment]
It works now ! This was effectively a terrible bug, this is not always a Windows issue :-)

As always, thank you for your reactivity, you may now close that issue I guess

Pierre
