### ISSUE TITLE
problem config directory

### ISSUE THREAD

**Issue by gustavalentin** [danmunn/redmine_dmsf#787]
I installed the the pluggin but I must have done something wrong as after restarting the apache service, and going to the admin pane on Redmine there is
![image](https://user-images.githubusercontent.com/4275242/31688202-0749aace-b362-11e7-830d-7ca35a6b4f7f.png)
and the plugin 
![image](https://user-images.githubusercontent.com/4275242/31688238-258e4684-b362-11e7-83b1-11ded37571ea.png)
![image](https://user-images.githubusercontent.com/4275242/31688258-368311a4-b362-11e7-8261-8df65cf30a6f.png)

The redmine info is
![image](https://user-images.githubusercontent.com/4275242/31688301-57929e32-b362-11e7-83b2-0972489d2899.png)

the history are
cd /opt/redmine
bundle install
bundle exec rake redmine:plugins:migrate RAILS_ENV="production"

thanks !!

**Comment by picman** [comment]
The plugin's sub-foder got the right ownership? Eg. `chown -R www-data:www-data plugins/redmine_dmsf`.

**Comment by gustavalentin** [comment]
Hi Picman, the subfolder can be this 
/opt/redmine/plugins/redmine_dmsf-master???

Thanks

**Comment by picman** [comment]
I think it should be `/opt/redmine/plugins/redmine_dmsf`.

**Comment by gustavalentin** [comment]
ok. the folder have the rigth ownership

**Comment by picman** [comment]
And?
Something in the production.log?

**Comment by gustavalentin** [comment]
Hi.
This is the log in production when I want to access the configuration
`
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dmsf/javascripts/attachments_dmsf.js"):
  actionpack (4.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.8) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.8) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.8) lib/rack/content_length.rb:15:in `call'
  rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.8) lib/rails/engine.rb:518:in `call'
  railties (4.2.8) lib/rails/application.rb:165:in `call'
  railties (4.2.8) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.8) lib/rails/railtie.rb:194:in `method_missing'
  passenger (5.0.8) lib/phusion_passenger/rack/thread_handler_extension.rb:89:in `process_request'
  passenger (5.0.8) lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
  passenger (5.0.8) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  passenger (5.0.8) lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
  passenger (5.0.8) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
`

**Comment by picman** [comment]
There must be something wrong with your installation, I'd recommend reinstalling the plugin. E.g:
```
rm -rf plugins/redmine_dmsf
cd plugins
git pull https://github.com/danmunn/redmine_dmsf.git
chown -R www-data:www-data redmine_dmsf
cd ..
bundle install
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
bundle exec rake tmp:cache:clear tmp:sessions:clear RAILS_ENV=production
service apache2 restart
```

P.S. Do not forget to backup existing documents if any uploaded in dmsf sub-folder prior the installation.
