### ISSUE TITLE
Mail Notifications changed/incorrect

### ISSUE THREAD

**Issue by flybyray** [danmunn/redmine_dmsf#788]
maybe by this change 

https://github.com/danmunn/redmine_dmsf/commit/21ba4bef9930d61b3198d1419bc7deb61eae3807

the listing of changed files is missing as you can see here:
![image](https://user-images.githubusercontent.com/804661/31710074-3cec25ac-b3f4-11e7-952e-405507418d3c.png)

**Comment by picman** [comment]
Please describe the problem in more details. I don't see the point. As you can see in the diff the indentation was wrong and fixed by that commit. I wonder how it can have an influence on email notification functionality.
On the second link I see only: "Invalid upstream response (403)".

**Comment by flybyray** [comment]
sorry fixed the picture.

please see that the indentation on that particular place has different semantic.

I just reverted to the indentation version before and now i receive notifications about deleted files. before i do not get them (no email).

i updated deployment with the 1.6.0 merged into master version, and now i am missing the file list when files have updates and i am involved.

sorry the screenshot show "german" messages.

it means similar like: "user admin has updated the following documents in folder test"

after that message there are no files listed. but i updated files.

**Comment by picman** [comment]
What do you mean with a "different semantic". The code has just been moved one tab to the left. Nothing more. The indentation has no influence on the code functionality. Ruby is not Python.
I've just tested notifications in case of documents uploading and deleting. I both cases I received correct notification email.
Could you check your production log whether there are some errors/warning related to notifications.

**Comment by picman** [comment]
Also permissions come to my mind. Have got the user receiving the empty email permissions to see updated documents?

**Comment by flybyray** [comment]
ok thx i need to elaborate the exact settings of thoses users.
it is a test deployment with real users from a production system. maybe there are some other settings.

sorry with that indentation thing
