### ISSUE TITLE
Mail Notification for deletion missing

### ISSUE THREAD

**Issue by flybyray** [danmunn/redmine_dmsf#789]
The DMSF Plugin allows the deletion over the file browser.
Here the action is invoked about the route:

config/routes.rb:40 : `post '/projects/:id/dmsf/entries/delete', :controller => 'dmsf', :action => 'delete_entries', :as => 'delete_entries'`

another way to delete files is through the details page, where you can delete revisions or the whole file:
config/routes.rb:87 : `delete '/dmsf/files/:id', :controller => 'dmsf_files', :action => 'delete'`

The latter case does not deliver any mail message.
I do not think that this is expected and in older versions that worked.

**Comment by picman** [comment]
Yes, you are right. It is not consistent. But, what is correct?

A) Deleting of files by selecting check boxes and pressing the delete button
1. Files are moved into the trash bin. Notifications are sent.
2. Files are deleted from the trash bin. Notifications are sent again.

B) Deleting a file using the trash icon next to the file either in the document list or the document's details.
1. The file is moved into the trash bin. Notifications are NOT sent.
2. The file is deleted from the trash bin. Notifications are sent.

From my point of view I'd prefer to send notifications only in the case of delete from the trash bin. So in the case of real deletion of files from the system.

What do you think?

**Comment by picman** [comment]
Okay, no feedback so far, let's fix B1.
