### ISSUE TITLE
redmine not administrator account can not download the dmsf doctuments,it shows Internal error.

### ISSUE THREAD

**Issue by flashliao** [danmunn/redmine_dmsf#791]
I use the bitnami setup the redmine.
Environment is show like this:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  redmine_ckeditor               1.1.5
  redmine_dmsf                   1.6.0
  redmine_xlsx_format_issue_exporter 0.1.5

When I use the redmine administrator account,the Internal error not happen.
But when I use the not administrator redmine  account,and give the this acount with role full  function。when I want download the doctuments in redmine Issues  the error show like this.
-------------------------------------------------------------------------------------------
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.
----------------------------------------------------------------------------------------------------------------

I'm chinaese,I want use the redmine web application with redmine_dmsf for my company.

**Comment by flashliao** [comment]
I can't upload the picture because my network is not good.
I want to say,if the issues just happen to me,So the issues is the questions.
if the issues happen all of them,I think the issues is the bug.
the issues is important for me,solve the problem give me a lot advantage.
if can't understand my issues,just say to me .I will try so hard to updoad the picture.

**Comment by picman** [comment]
Post a part of your production.log related to the issue, please.

**Comment by flashliao** [comment]
@picman  I don't konw where production.log

**Comment by picman** [comment]
log/production.log

**Comment by flashliao** [comment]
Started HEAD "/redmine" for 127.0.0.1 at 2017-10-24 14:37:15 +0800
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendered welcome/index.html.erb within layouts/base (121.2ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (4.7ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (23.7ms)
Completed 200 OK in 905ms (Views: 635.1ms | ActiveRecord: 20.7ms)
Started GET "/redmine/" for 163.163.0.121 at 2017-10-24 14:38:02 +0800
Processing by WelcomeController#index as HTML
  Current user: 08622 (id=20)
  Rendered welcome/index.html.erb within layouts/base (30.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.6ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (10.7ms)
Completed 200 OK in 231ms (Views: 144.9ms | ActiveRecord: 16.1ms)
Started GET "/redmine/projects" for 163.163.0.121 at 2017-10-24 14:38:04 +0800
Processing by ProjectsController#index as HTML
  Current user: 08622 (id=20)
  Rendered projects/index.html.erb within layouts/base (43.3ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.6ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (10.3ms)
Completed 200 OK in 158ms (Views: 114.4ms | ActiveRecord: 11.6ms)
Started GET "/redmine/projects/capp24" for 163.163.0.121 at 2017-10-24 14:38:06 +0800
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"capp24"}
  Current user: 08622 (id=20)
  Rendered projects/_members_box.html.erb (5.1ms)
  Rendered projects/show.html.erb within layouts/base (64.6ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.6ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (10.7ms)
Completed 200 OK in 455ms (Views: 174.9ms | ActiveRecord: 39.9ms)
Started GET "/redmine/projects/capp24/issues?set_filter=1&tracker_id=4" for 163.163.0.121 at 2017-10-24 14:38:09 +0800
Processing by IssuesController#index as HTML
  Parameters: {"set_filter"=>"1", "tracker_id"=>"4", "project_id"=>"capp24"}
  Current user: 08622 (id=20)
  Rendered queries/_filters.html.erb (67.0ms)
  Rendered queries/_columns.html.erb (10.9ms)
  Rendered queries/_query_form.html.erb (107.3ms)
  Rendered issues/_list.html.erb (33.6ms)
  Rendered issues/_sidebar.html.erb (18.4ms)
  Rendered issues/index.html.erb within layouts/base (228.9ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.6ms)
  Rendered plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_insert_xlsx_link_for_dialog.erb (3.9ms)
  Rendered plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_xlsx_export_dialog_on_issues_index.erb (20.5ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (11.9ms)
Completed 200 OK in 969ms (Views: 516.5ms | ActiveRecord: 43.1ms)
Started GET "/redmine/issues/36" for 163.163.0.121 at 2017-10-24 14:38:12 +0800
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"36"}
  Current user: 08622 (id=20)
  Rendered issues/_action_menu.html.erb (26.0ms)
No Xapian search engine interface for Ruby installed => Full-text search won't be available.
                      Install a ruby-xapian package or an alternative Xapian binding (https://xapian.org).
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (20.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_link.html.erb (215.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_thumbnails.html.erb (4.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_links.html.erb (228.9ms)
  Rendered issue_relations/_form.html.erb (16.0ms)
  Rendered issues/_relations.html.erb (31.8ms)
  Rendered issues/_history.html.erb (13.7ms)
  Rendered issues/_action_menu.html.erb (12.5ms)
  Rendered issues/_form_custom_fields.html.erb (3.3ms)
  Rendered issues/_attributes.html.erb (75.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (24.5ms)
  Rendered issues/_form.html.erb (214.0ms)
  Rendered attachments/_form.html.erb (18.7ms)
  Rendered issues/_edit.html.erb (365.5ms)
  Rendered issues/_sidebar.html.erb (13.0ms)
  Rendered watchers/_watchers.html.erb (25.6ms)
  Rendered issues/show.html.erb within layouts/base (1281.1ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.1ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (13.6ms)
Completed 200 OK in 1885ms (Views: 1329.1ms | ActiveRecord: 94.8ms)
Started GET "/redmine/dmsf/files/76/view" for 163.163.0.121 at 2017-10-24 14:38:16 +0800
Processing by DmsfFilesController#view as HTML
  Parameters: {"id"=>"76"}
  Current user: 08622 (id=20)
Completed 500 Internal Server Error in 114ms (ActiveRecord: 7.9ms)

NoMethodError (undefined method `issue' for #<Class:0x00007fbfb90edc80>):
  plugins/redmine_dmsf/app/models/dmsf_folder.rb:114:in `permissions?'
  plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:41:in `permissions'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by picman** [comment]
Fixed. Thank you for reporting the bug. Update your code and restart your web server. E.g.
```
cd plugins/redmine_dmsf
git checkout master
git pull
service apache2 restart
```

**Comment by flashliao** [comment]
@picman So quickly fix the bug，it works useful.I almost think this is my prolem,thanks.If I'm in your country,I will  contribute the money for you.
