### ISSUE TITLE
Upload of Word 2016 documents not possible

### ISSUE THREAD

**Issue by broszies** [danmunn/redmine_dmsf#792]
Hi,
since our company migrated to Office 2016 its no longer possible to upload the new word documents into the DMSF. The Error Message is "Upload-URL wrong or nonexistant".
Replication: 
1. Open new Word document
2. Write "Test"
3. Save
4. Attempt upload.

This seems to be related to the upgrade insofar as when I save the same document as .doc (Word 97-2003), the upload is possible without any problems.

Please advise

**Comment by picman** [comment]
My advise is to migrate to LibreOffice.

**Comment by broszies** [comment]
Thanks, nice Idea, but not helpful, since I am only in charge of the DMS, not in Charge of my companys IT ^^

**Comment by picman** [comment]
I've just upgrade `dav4rack` library. But still not having an opportunity to test Office2016. Could you switch to the branch devel-1.6.1 and try it in your environment, please? If there is still a problem, please post production.log.

**Comment by picman** [comment]
I've just tested it with MS Office 2016 and can't reproduce your problem. Please try v1.6.1.
