### ISSUE TITLE
Installation on bitnami - rake aborted NameError: uninitialized constant

### ISSUE THREAD

**Issue by steveweree** [danmunn/redmine_dmsf#797]
Running bitnami redmine stack on 1and1. Disabled services, uploaded redmine_dmsf-1.6.0 and ran bundle install. But the bundle exec rake aborts with NameError: uninitialized constant ActionDispatch::ParamsParser

![rakeabort](https://user-images.githubusercontent.com/33436667/32469845-82e7aee0-c322-11e7-877c-d201cdaa3794.JPG)

I don't know where to start to fix this. Any help is appreciated. Thank you.

**Comment by picman** [comment]
The only usage of `ParamsParser` class I see in `config/application.rb`:
```ruby
# XML parameter parser removed from core in Rails 4.0
# and extracted to actionpack-xml_parser gem
config.middleware.insert_after ActionDispatch::ParamsParser, ActionDispatch::XmlParamsParser
```
I'd check whether `actionpack-xml_parser_ gem` is installed.

**Comment by steveweree** [comment]
Thank you for the quick response and suggestion. 

You were right, `actionpack-xml_parser` was not installed, so added to gemfile and ran bundle install. 
gem list now shows it:  
![gemlist](https://user-images.githubusercontent.com/33436667/32493147-d8f544ec-c38a-11e7-807d-de4aee9d6238.JPG)

But still get same rake aborted message: 
![rakeabort2](https://user-images.githubusercontent.com/33436667/32493272-416dcc7e-c38b-11e7-95a7-09844d9264cc.JPG)
Do you have another suggestion?  Thank you in advance.

**Comment by picman** [comment]
1. `bundle install` and `bundle exec rake redmine:plugin:migrate` run from within redmine root directory? 
2. Location of DMSF plugin is `plugins/redmine_dmsf`?

**Comment by steveweree** [comment]
1. I am running `bundle install` and the `bundle exec rake redmine:plugin:migrate` from the plugin folder
`/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf-1.6.0`

2. This is the location of the DMSF plugin (same as 1): 
`/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dmsf-1.6.0`

Thank you.

**Comment by picman** [comment]
That's wrong. `bundle install` and `bundle exec rake redmine:plugin:migrate` must be run from the redmine root folder. The plugin sub-folder must be named `redmine_dmsf`.

**Comment by steveweree** [comment]
With your help, DMSF is now working.  It was not clear to me from the install instructions as to how to do this. Thank you for your patience with a Ruby on Rails novice.
