### ISSUE TITLE
Possibility of Obsolete an Approved Version of a Document

### ISSUE THREAD

**Issue by PedroTeixido** [danmunn/redmine_dmsf#798]
Once a version of a document has been approved. It can not be obsolete if for whatever reason the content of the document is not longer valid.

It would be nice to be able to reassign an obsolete workflow and be able to approve its obsolescence
A simpler version could be that one of the reviewers who approved the version could just obsolete it latter on.

Thanks you very much!

**Comment by picman** [comment]
https://github.com/danmunn/redmine_dmsf/pull/877/commits/a50af4b041689ee798672ee6b29c87f8aa651a47

**Comment by picman** [comment]
https://github.com/danmunn/redmine_dmsf/blob/devel-1.6.2/assets/images/obsolete.png has got 0b. Please upload again.

**Comment by picman** [comment]
```NoMethodError (undefined method `log_activity' for #<DmsfFilesController:0x00005613c0b3c7f0>):
  plugins/redmine_dmsf/app/controllers/dmsf_files_controller.rb:251:in `obsolete_revision'```

Have you tested it?

**Comment by PedroTeixido** [comment]
I'm using it in our redmine with DMFS v1.6.0 and is working very well for
me.
I'm going to have a look now to see if I find out the issue, and I'll test
it tomorrow on release v1.6.1 sorry for that.

**Comment by PedroTeixido** [comment]
Ok, I have seen that between 1.6.0 and 1.6.1 all calls to log_activity were
removed because of issue #802
Sorry for not testing it on last release. My mistake.

I have uploaded the image file again, removed the log_activity call and
created another pull request.

Thanks Karel
