### ISSUE TITLE
'Create folder' takes a very long time

### ISSUE THREAD

**Issue by picman** [danmunn/redmine_dmsf#803]
E.g. In a project with 7406 folders and 54829 files it takes minutes:
```
INFO -- : Started GET "/projects/release/dmsf/new" for 127.0.0.1 at 2017-11-10 14:12:39 +0100
INFO -- : Processing by DmsfController#new as HTML
INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (1.2ms)
INFO -- :   Rendered plugins/redmine_dmsf/app/views/dmsf/edit.html.erb within layouts/base (214144.8ms)
INFO -- :   Rendered plugins/redmine_kontron/app/views/hooks/_view_base_head.html.erb (0.3ms)
INFO -- : Completed 200 OK in 214360ms (Views: 47355.6ms | ActiveRecord: 166893.2ms)
```

**Comment by picman** [comment]
Related SQLs have been optimized for speed. They're about 20 times faster now.

**Comment by mrazek** [comment]
I have still problem with extremely long time to "Create Folder" page.
`Rendered plugins/redmine_dmsf/app/views/dmsf/edit.html.erb within layouts/base (115635.3ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (1.1ms)
  Rendered plugins/redmine_contacts/app/views/contacts_issues/_additional_assets.html.erb (0.3ms)
  Rendered plugins/under_construction/app/views/hooks/under_construction/_view_layouts_base_body_top.html.erb (0.7ms)
  Rendered plugins/redmine_contacts/app/views/common/_contacts_select2_data.html.erb (0.2ms)
Completed 200 OK in 115713ms (Views: 97869.7ms | ActiveRecord: 17831.9ms)`

I'm using redmine 3.4.5, dmsf 1.6.2-devel, postgresql...
Is this patch in devel tree already implemented?

**Comment by picman** [comment]
Yes, it is. The problem is in the new/edit folder form, where a user can select the parent folder. If there is a lot of folders in the project, generating of a possible parent folder tree is quite time consuming. I've tried to optimize the code, but if there are plenty of folders, it's not enough.

A next step might be removing the parent folder control from the form:

- In case of new folder form it's quite logical that you must enter the parent folder first and then create a child folder.
- In case of moving folder, you can use the Copy/Move function instead of editing.

![untitled](https://user-images.githubusercontent.com/779003/41096156-086e881c-6a54-11e8-9dfc-f8be18407168.png)

**Comment by mrazek** [comment]
Yes, I understand, that we have to specify, in which parent folder we want to create child folder. For us, it would work fine, if the parent folder is always that folder, where we hit "Create Folder" button. We have one project where all user doc for our product is stored and this is why we have so many folders (each product at least two folders) and it will grow. Main product folders we create through REST API and we have no problems with this, but if we need to add a specific folder manually, this issue arises.

Many thanks for re-opening issue and for any advice for workaround!

**Comment by picman** [comment]
Okay. The parent folder selection removed. Now it's fast.

**Comment by mrazek** [comment]
unfortunately this patch creates folder in root "Documents" folder only, not in the folder, where I hit the "Create Folder" button.

**Comment by picman** [comment]
Fixed.

**Comment by mrazek** [comment]
Excellent. Many, many thanks! Unfortunately, we have similar problem with "Create link" command, but this is not that trivial as DMS needs to read the list of projects, folders and files to create the link. So maybe just a short question... Is it possible to create links through REST API?

**Comment by picman** [comment]
Concerning links. There is a new option in the project's setting "Fast links" in DMS 1.6.2. If set you can enter a document's ID directly without selecting project/folder/document.

![image](https://user-images.githubusercontent.com/779003/47432402-5a9f6400-d79e-11e8-803e-5694180dc0ad.png)
