### ISSUE TITLE
Cannot change document description

### ISSUE THREAD

**Issue by roman6334** [danmunn/redmine_dmsf#806]
If I added a file in documents tree and was mistaken in the description, I cannot edit this description again. I have to do new revisions with new description!

**Comment by picman** [comment]
That's a feature. Each document change is a new document's revision.

**Comment by roman6334** [comment]
Yes. But I dont change document., i only change description

**Comment by picman** [comment]
Yes, a document's property => new revision. You can see then the history of the document's description changes.
![image](https://user-images.githubusercontent.com/779003/32883330-5ee08cf0-cab7-11e7-958e-6348644f8cf6.png)

**Comment by roman6334** [comment]
Thank you.
