### ISSUE TITLE
Documents not found after upgrade from DMSF v1.4.8 to v1.6.0

### ISSUE THREAD

**Issue by j-avdeev** [danmunn/redmine_dmsf#811]
I have upgraded Redmine (2.5.1 > 3.4.3) through backup/rewert:
I use bitnami redmine, so I used mysqldump to export database from old redmine and to import it in new redmine. Also I copied /dmsf fodder with all files.

Now I have Redmine 3.4.3 with new 1.6.0 dmsf plugin. All my projects and names of files in DMSF-tab are on correct places, but when I click to download some of dmsf-file I get error:
"404 Not Found"

My production.log contatin following lines about it:

```
2017-12-06 18:16:01 admin@192.168.1.1/: downloaded dmsf://testproject/145/32592
Sent file /opt/bitnami/apps/redmine/htdocs/files/dmsf/2014/07/140731061318_145_logo.gif (0.4ms)
Cannot read file /opt/bitnami/apps/redmine/htdocs/files/dmsf/2014/07/140731061318_145_logo.gif
  Rendered common/error.html.erb within layouts/base (0.3ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_sidebar.html.erb (0.1ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_recent_projects.html.erb (3.6ms)
Completed 404 Not Found in 102ms (Views: 45.8ms | ActiveRecord: 23.5ms)
```

I checked the presence of this file (140731061318_145_logo.gif) in this path (/opt/bitnami/apps/redmine/htdocs/files/dmsf/2014/07/140731061318_145_logo.gif) and it is not there. 

This file is in 
/opt/bitnami/apps/redmine/htdocs/files/dmsf/p_testproject/140731061318_145_logo.gif

Also I tried to download this file from old redmine and upload it to new redmine's - and it works, dmsf creates folder like
 /opt/bitnami/apps/redmine/htdocs/files/dmsf/2017/12/
(actually because it is December 2017 now) and puts uploaded "140731061318_145_logo.gif" there,
 but why it is not put it to
/opt/bitnami/apps/redmine/htdocs/files/dmsf/p_testproject/
?

Looks like new dmsf-plugin has different file-storage-organization logic?
If so - how can I "translate" old file paths to new?
I have a couple of thousands files, so I really do not want to do this through manual downloading-uploading.

**Comment by picman** [comment]
#799
