### ISSUE TITLE
I can't upload file from Windows but I can do it from Linux

### ISSUE THREAD

**Issue by aivorra** [danmunn/redmine_dmsf#814]
Hi, I'm working with DMSF 1.4.9 on Redmine 2.5.3 since a long time... 
Now I see that if I try to upload a file (it doesn't matter the size, 1kB, 10kB or 1MB) with Chrome on Windows 10, when I press "Upload" the process begin but I never see the next page to do the commit. If the file is less than 100kB the progress bar get 100%, but if the file is bigger the bar never arrive to 100%.
If I do the same act on Chrome Linux (Ubuntu) it's work perfect, like always.

My doubt is if you have seen this situation before.

Best regards.

**Comment by picman** [comment]
The versions you use are pretty old. I suppose that your browser is not as old and stricter politics there prevent the old upload control from functioning properly. It's time to upgrade Redmine and DMSF plugin as well, I think.

**Comment by aivorra** [comment]
I'II install the last version of Redmine and DMSF, and check it out.

Thanks!
