### ISSUE TITLE
Move directory to root

### ISSUE THREAD

**Issue by dinya** [danmunn/redmine_dmsf#815]
How to move directory from ``/a/b`` to ``/b`` with web interface (no root element at ``dmsf/edit?folder_id=XXX``)?

With WebDAV directories are recreated on moving, but contained files are "truly" moved.

dmsf v1.5.9, redmine  3.3.1.stable

**Comment by dinya** [comment]
No root element

![no_root_element](https://user-images.githubusercontent.com/2182222/34399357-8b6584d0-eba8-11e7-9799-6e223cbf7e3a.png)

**Comment by dinya** [comment]
@picman 

Which element is the root?

**Comment by picman** [comment]
Hm, that's strange. I see there "Documents" which stands for the root folder. It might be a bug. Have you tested the last released version 1.6.0?

![image](https://user-images.githubusercontent.com/779003/34515594-0e717c8e-f073-11e7-8055-7451082a6b53.png)

**Comment by picman** [comment]
No feedback => closing.
