### ISSUE TITLE
 the check for approval is not displayed

### ISSUE THREAD

**Issue by schildg** [danmunn/redmine_dmsf#817]
Hi, update DMFS from 1.5.9 to 1.6.0 in redmine 3.4.3, and the approval check is not displayed, where a workflow is assigned

**Comment by picman** [comment]
Could you post here an explaining screen shot, please? There has been made a change related to the icons. If an approval workflow is finished, no icon is displayed and the state of approval is indicated in the column **Workflow** with a text _Rejected_ or _Approved_.

.

**Comment by schildg** [comment]
Hello, this is the screenshot before making the migration, where the approval checks are seen.

![dmsf](https://user-images.githubusercontent.com/29732357/34519694-024d4a82-f064-11e7-860a-33d3d61d5314.png)

 
After update 1.5.9 to 1.6.0 DMSF disappear check
 ![dms](https://user-images.githubusercontent.com/29732357/34519693-021dd914-f064-11e7-9638-6008ffd52003.png)
maybe I'm mistaking the update steps or I'm missing some

**Comment by picman** [comment]
There is also another change. And this is your case, I think. If a document is locked for you, command icons are not visible.

**Comment by picman** [comment]
In summary: with the standard graphical interface the flow assignment icon is standard, but if I use the Purple2 graphic interface the icons change with the easy_redmine styles. which I'm not using.
---
Gerardo

**Comment by schildg** [comment]
Hi, I think this problem is due to the fact that I'm using a graphical interface different from the redmine standart, since with the standart interface it looks like the image.
![image](https://user-images.githubusercontent.com/29732357/35565028-c89c44e0-059a-11e8-8def-b13b56aeaa8c.png)

but with the Purple2 graphic interface as seen in the previous screenshots, it shows up the different icons, it shows the icons for EasyRedmine

**Comment by picman** [comment]
Where I can get and how to install Purple2 graphic interface?

**Comment by schildg** [comment]
​from here https://github.com/mrliptontea/PurpleMine2

Thank you​

2018-01-30 8:53 GMT-03:00 Karel Picman <notifications@github.com>:

**Comment by picman** [comment]
Fixed:
![screenshot-2018-2-2 dms - c1 - kdp 3 7 webrick](https://user-images.githubusercontent.com/779003/35739849-4329bedc-0833-11e8-9de0-64c4b51f5124.png)
