### ISSUE TITLE
Cyrillic symbols

### ISSUE THREAD

**Issue by TarasVus** [danmunn/redmine_dmsf#820]
Hello, 
We installed your plugin redmine_dmsf.
Tried to config it. But have some problems with Cyrillic symbols 
1. in the names of files
2. When we try to write some words in the description 
![screenshot-2018-1-9 dms -01](https://user-images.githubusercontent.com/18629877/34767111-facd9766-f5ff-11e7-999f-53b897781e10.png)
![screenshot-2018-1-9 dms - 02](https://user-images.githubusercontent.com/18629877/34767106-f8dd4708-f5ff-11e7-8e2d-d2a1bec24881.png)
![screenshot-2018-1-9 03](https://user-images.githubusercontent.com/18629877/34767094-f4f80812-f5ff-11e7-9c15-6ccc853327fc.png)

Please help us .

Thank You

**Comment by picman** [comment]
Could you post your _log/production.log_ related to the error above, please?

**Comment by TarasVus** [comment]
[production.log](https://github.com/danmunn/redmine_dmsf/files/1618550/production.log)

**Comment by TarasVus** [comment]
Hope, You'll help us

**Comment by picman** [comment]
I think here are error related to the issue:
```
ActiveRecord::StatementInvalid (Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=': SELECT  `dmsf_files`.* FROM `dmsf_files` WHERE `dmsf_files`.`project_id` = 10 AND `dmsf_files`.`dmsf_folder_id` = 1 AND `dmsf_files`.`name` = 'візуальна схема кодифікації.png' AND `dmsf_files`.`deleted` = 0  ORDER BY `dmsf_files`.`id` ASC LIMIT 1):
```
```
ActiveRecord::StatementInvalid (Mysql2::Error: Incorrect string value: '\xD0\xBE\xD1\x81\xD1\x82...' for column 'comment' at row 1: INSERT INTO `dmsf_file_revisions` (`title`, `name`, `description`, `comment`, `dmsf_file_id`, `source_dmsf_file_revision_id`, `user_id`, `major_version`, `minor_version`, `size`, `disk_filename`, `mime_type`, `digest`, `created_at`, `updated_at`) VALUES ('redmine logo', 'redmine_logo.png', '', 'остання картинка з 3х запропонованих мені подобається, бо там написано, що таке цей редмайн. \r\nдумаю, для розуміння, що це саме платформа для управління проектами (редмайн) саме для карітасу - потрібно поєднати цю інфо (чи символами, чи текстом)', 6, 6, 9, 0, 1, 3835, '180105160720_6_redmine_logo.png', 'image/png', 'd702b4df0ed563e567e16e4c449a69d7', '2018-01-09 12:07:08', '2018-01-09 12:07:08')):
```
The problem seems to be on the database's side. You have wrong collation. Check the following statements in your database:

```
mysql> show create table dmsf_file_revisions;
...
DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

**Comment by TarasVus** [comment]
Thank You for your answer. 
But I cannot open tables. :(
Could You help me please.

Maybe with teamviewer.com.

**Comment by picman** [comment]
You are logged in a wrong database. mysql is a system database. I assume that your Redmine uses a different one. Check your config/database.yml file. Default is remine, so:
```mysql -u redmine -p redmine```

**Comment by TarasVus** [comment]
I found this one:
![mysql1](https://user-images.githubusercontent.com/18629877/34826515-844e1c74-f6df-11e7-9ecf-8dc48ee58ef6.jpg)

**Comment by TarasVus** [comment]
could You tell me a command how I can change this?

**Comment by picman** [comment]
So I was right. You database encoding is wrong. You can't set _UTF8_ in your application and _latin1_ in the database. You haven't probably followed the Redmine installation instruction:
```CREATE DATABASE redmine CHARACTER SET utf8;```
To update your database is not an easy task. If you are in a testing environment I'd recommend you creating a new database. If this is not possible try the following:
```
mysql -u your_user -p your_password redmine_production -B -N -e "SHOW TABLES" | awk '{print "SET foreign_key_checks = 0; ALTER TABLE", $1, "CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci; SET foreign_key_checks = 1; "}' | mysql -u your_user -p your_password redmine_production

mysql -u your_user -p your_password redmine_production
mysql> ALTER DATABASE redmine_production CHARACTER SET utf8 COLLATE utf8_general_ci;
```

**Comment by TarasVus** [comment]
I changed this parameter
![mysqlutf8](https://user-images.githubusercontent.com/18629877/34829515-9aa6efc8-f6e9-11e7-9b7d-53acb04c1670.jpg)
. but problem is now too.

**Comment by picman** [comment]
config/database.yml
```production:
  adapter: mysql2
  database: ***
  host: ***
  username: *** 
  password: ***
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
```
```
mysql> SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME
    -> FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'redmine';
+----------------------------+------------------------+
| DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME |
+----------------------------+------------------------+
| utf8mb4                    | utf8mb4_general_ci     |
+----------------------------+------------------------+
```
mysql> show create dmsf_file_revisions;
...DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```
Right?

**Comment by TarasVus** [comment]
some screens:
![database](https://user-images.githubusercontent.com/18629877/34831221-fe7cf1b4-f6ee-11e7-8c5b-66f96136a1e5.jpg)
![redmine](https://user-images.githubusercontent.com/18629877/34831222-fe996448-f6ee-11e7-9d73-c17f8498d3a7.jpg)

**Comment by picman** [comment]
Alter your database as recommended here: https://github.com/danmunn/redmine_dmsf/issues/820#issuecomment-356943057

**Comment by picman** [comment]
Moreover, according to your _database.yml_ the database is _redmine_production_ not _redmine_!

**Comment by TarasVus** [comment]
thank You for your help. 
Now I can write descriptions and comments on the Cyrillic symbols.

But problem with Cyrillic names of the files left.
Could You help me? 
Thank You

**Comment by picman** [comment]
And what is the problem with filenames? Please describe it.

**Comment by TarasVus** [comment]
Please look to screenshots
![file1](https://user-images.githubusercontent.com/18629877/34872602-33ef63ee-f79a-11e7-92d0-cebc312f8261.jpg)
![file2](https://user-images.githubusercontent.com/18629877/34872603-340da3d6-f79a-11e7-89b9-3ea569f5be1e.jpg)
when I want to start upload we see second page

**Comment by picman** [comment]
Again, I'd need your production.log. It is enough a chunk related to the error.

**Comment by TarasVus** [comment]
[production.log](https://github.com/danmunn/redmine_dmsf/files/1625980/production.log)

**Comment by picman** [comment]
The same problem but now in dmsf_files table:
```
ActiveRecord::StatementInvalid (Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_unicode_ci,COERCIBLE) for operation '=': SELECT  `dmsf_files`.* FROM `dmsf_files` WHERE `dmsf_files`.`project_id` = 10 AND `dmsf_files`.`name` = 'сканирование.pdf' AND `dmsf_files`.`dmsf_folder_id` IS NULL AND `dmsf_files`.`deleted` = 0  ORDER BY `dmsf_files`.`id` ASC LIMIT 1):
```
If you have set encoding: _utf8mb4_ and collation: _utf8mb4_unicode_ci_ in your _database.yml_, all your tables must reflect it!

Have run the script from https://github.com/danmunn/redmine_dmsf/issues/820#issuecomment-356943057 ?

**Comment by TarasVus** [comment]
Thanks a lot. 
I changed encoding in this table too and files become to work.
Could You help me if I'll have another problems? :)
Good luck

**Comment by TarasVus** [comment]
Ok, I'll do it soon :)
