### ISSUE TITLE
Office URI Scheme for direct editing of MS Office files

### ISSUE THREAD

**Issue by AThomsen** [danmunn/redmine_dmsf#823]
It would be nice if links to MS Office file would point directly to the wevdav-url, using the [Office URL Schema](https://msdn.microsoft.com/en-us/library/office/dn906146.aspx) , to allow editing of files without mapping webdav-share to a drive. 

This is the way Sharepoint works.

**Comment by picman** [comment]
I've added a context menu with Edit item:

![image](https://user-images.githubusercontent.com/779003/36154035-6e59e41a-10d0-11e8-9ab3-9dc259842cd4.png)

providing an Office URL, e.g.:
```
ms-word:ofe|u|http://localhost:3000/dmsf/webdav/c1/Formular%20Mitarbeitergespr%C3%A4ch%20Karel.docx
```

A problem is that having neither Windows nor MS Office I don't know how to test it. Could you switch your testing environment to _context_menu_ branch,try it and provide me a feedback, please?

```
cd plugins/redmine_dmsf
git fetch
git checkout context_menu
cd ..
cd ..
bundle install
service apache2 restart
```

**Comment by picman** [comment]
I've just tested it using MS Office 2016 and it works! So DMSF 1.6.1 will bring a new feature of direct editing of documents.

**Comment by picman** [comment]
Done.

**Comment by bluekyg** [comment]
when dmsf settings page,  Use project name for project folder checked and direct editing not open
when unchecked, open working.

**Comment by bluekyg** [comment]
and folder exist, not open office.
"/" missing front file_name .

i'm edit(andd one line) on app/views/dmsf_context_menus/dmsf.html.erb
      <% if @file.last_revision && @file.last_revision.protocol %>
        <% url = "#{@file.last_revision.protocol}:ofe|u|#{Setting.protocol.strip}://#{Setting.host_name.strip}/dmsf/webdav/#{Addressable::URI.escape(@file.project.identifier)}/" %>
        <% if @file.dmsf_folder %>
          <% url << @file.dmsf_folder.dmsf_path_str %>
          **<% url << "/" %>**
        <% end %>
        <% url << @file.name %>
      <% end %>

**Comment by picman** [comment]
Fixed.
