### ISSUE TITLE
DMSF Large File Upload Error 

### ISSUE THREAD

**Issue by RedmineUsr** [danmunn/redmine_dmsf#825]
Hi,

Trying to upload large files (>~1.5 MB) within DMSF and receive the following error:
"HTTP Error. Upload URL might be wrong or doesn't exist."

I am currently running the following on a Ubuntu 16.04 VM through VirtualBox with Nginx webserver:
Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.4.0-p0 (2016-12-24) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.6.0

New to this, so would appreciate any help or guidance anyone can provide.  Thanks!

**Comment by picman** [comment]
Check the production.log. There might be an error.

**Comment by RedmineUsr** [comment]
Apparently this issue was being caused by the Nginx webserver configuration file. The client max body size needed to uncommented.

Default config file located: /etc/nginx/sites-available

# Default server configuration
#
server {
    #root /data/redmine/redmine/public;
    #passenger_enabled on;
    **client_max_body_size 2000m;**
