### ISSUE TITLE
Xapian not indexing

### ISSUE THREAD

**Issue by ilovetacos** [danmunn/redmine_dmsf#826]
Hi,
I hope I can get some help here. I'm working with an old system (ubuntu 14.04, redmine 2.5, dmsf 1.4.8). This system was setup a few years ago and now somebody wants to use the full-text-search. So I  installed xapian as described in the dmsf 1.4.8 README.
Indexing with 

`omindex -s german2 --url / --db /home/redmine/redmine-2.5/files/dmsf_index /home/redmine/redmine-2.5/files/dmsf`

seems to work fine (although there is a bunch of error messages):

`/bin/sh: 1: pdftotext: not found
p_workshops-seminare-und-infoveranstaltungen/150710171335_292_150707-FET_Open_Webinar_Versandversion-1.pdf: Skipping - Filter for "application/pdf" not installed
p_redmine-support/141124120654_58___dmine_basics.docx: Skipping - "unzip -p '/home/redmine/redmine-2.5/files/dmsf/p_redmine-support/141124120654_58___dmine_basics.docx' word/document.xml word/header\*.xml word/footer\*.xml 2>/dev/null||test $? = 11" failed
p_redmine-support/141126135555_72_config-mitglieder.JPG: Skipping - unknown MIME type 'image/jpeg'
p_redmine-support/141124141048_67_config-module.JPG: Skipping - unknown MIME type 'image/jpeg'
[/home/redmine/redmine-2.5/files/dmsf/p_redmine-support/141117155003_53___android_apps.xlsx]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.`

but when I add a new document and either wait for the cronjob or try to index manually, the only file changed is `flintlock` (with 0 B) and the new document is not searchable.
Is this a problem with the old versions? The missing pdftotext doesn't sound right either.

**Comment by picman** [comment]
1) Run indexing manually.
2) Index a TXT file first to see whether it's working.
3) Check the stemming language. It must be set to the same value by `omindex` and in the plugin settings too.
4) Install required tools for converting different document formats to text according to Xapian's docs (https://xapian.org/docs/omega/overview.html)
5) `pdftotext /home/redmine/redmine-2.5/files/dmsf/p_workshops-seminare-und-infoveranstaltungen/150710171335_292_150707-FET_Open_Webinar_Versandversion-1.pdf` output.txt is working?

**Comment by ilovetacos** [comment]
First of all: I installed pdftotext (poppler-utils), now the error messages look different (obviously now it finds pdftotext, which is good); converting pdf to txt is working too.
Indexing a .txt file is working.
Stemming language is german2 in both locations (btw what is the difference between german and german2?).
Indexing of pdfs seem to be working now, too. 
Thank you!
Do you know what about this error? 
`p_redmine-deployment/141201115501_188___dmine_Aufgaben.docx: Skipping - "unzip -p '/home/redmine/redmine-2.5/files/dmsf/p_redmine-deployment/141201115501_188___dmine_Aufgaben.docx' word/document.xml word/header\*.xml word/footer\*.xml 2>/dev/null||test $? = 11" failed`

**Comment by picman** [comment]
I don't know, I'm afraid. Please look into _xapian.org_ documentation. From my experience, some MS documents, probably with some advance formating, are simply not readable by non-MS tools.

**Comment by ilovetacos** [comment]
Thank you for your time to answer and for this really useful piece of software!
