### ISSUE TITLE
500 when trying to access trash bin

### ISSUE THREAD

**Issue by quimicefa** [danmunn/redmine_dmsf#828]
Hello,
using redmine 3.4.4 + dmsf 1.6.0 in a testing env. and we're getting a 500 error when clicking in the trash bin icon. 
Logs are showing this msg, but i can't figure if this is a configuration issue or a bug:

`Completed 500 Internal Server Error in 235ms (ActiveRecord: 72.7ms)

ActionView::Template::Error (undefined method `id' for nil:NilClass):
    23: <td class="dmsf_checkbox"><%= check_box_tag(name, id, false,
    24:   :title => l(:title_check_for_restore_or_delete), :id => "subfolder_#{id}") %></td>
    25: <% if DmsfFolder.is_column_on?('id') %>
    26:     <td class="id"><%= link_to(subfolder.id, edit_dmsf_path(:id => project, :folder_id => subfolder)) %></td>
    27: <% end %>
    28: <% if DmsfFolder.is_column_on?('title') %>
    29:   <td class="dmsf_title">
  plugins/redmine_dmsf/app/views/dmsf/_dir_trash.html.erb:26:in `_plugins_redmine_dmsf_app_views_dmsf__dir_trash_html_erb___3991504299329967712_70279256541860'
  plugins/redmine_dmsf/app/views/dmsf/trash.html.erb:105:in `block (2 levels) in _plugins_redmine_dmsf_app_views_dmsf_trash_html_erb__3539456328459996933_70279263669720'
  plugins/redmine_dmsf/app/views/dmsf/trash.html.erb:103:in `block in _plugins_redmine_dmsf_app_views_dmsf_trash_html_erb__3539456328459996933_70279263669720'
  plugins/redmine_dmsf/app/views/dmsf/trash.html.erb:35:in `_plugins_redmine_dmsf_app_views_dmsf_trash_html_erb__3539456328459996933_70279263669720'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Started GET "/" for 172.24.2.3 at 2018-02-13 10:31:38 +0100
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendered welcome/index.html.erb within layouts/base `(2.2ms)```

![image](https://user-images.githubusercontent.com/5465238/36143278-f546c52c-10aa-11e8-9e3a-2efec1eb59fe.png)

**Comment by picman** [comment]
Do you work with links? Can't it be an orphan? I mean a deleted folder links pointing to a directory which had been deleted.

**Comment by picman** [comment]
No feedback => Closing.
