### ISSUE TITLE
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'dmsf_file_revisions' doesn't exist

### ISSUE THREAD

**Issue by FSCgithub** [danmunn/redmine_dmsf#830]
Hi,
when installing the plugin's version 1.6.0 I expierence following error:

`# bundle exec rake db:migrate RAILS_ENV=production`
`Loading Rails environment for Resque`
`rake aborted!`
`ActiveRecord::StatementInvalid: Mysql2::Error: Table 'redminedb.dmsf_file_revisions' doesn't exist: SHOW FULL FIELDS FROM dmsf_file_revisions`

Do you have any hints?

-Thanks in advance!!

My environment:

Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux] (CentOS 7.3.1611)
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  additionals                    2.0.3
  clipboard_image_paste          1.12
  redmine_agile                  1.4.5
  redmine_banner                 0.1.2
  redmine_checklists             3.1.9
  redmine_default_assign         0.6
  redmine_elasticsearch          0.2.0
  redmine_issue_templates        0.1.8
  redmine_resque                 0.1.4
  redmine_theme_changer          0.3.1

**Comment by picman** [comment]
Hm, that's strange. Is there something in the production.log? Why do you run `db:migrate` rake task when installing a plugin? You should run `redmine:plugins:migrate` instead.

**Comment by FSCgithub** [comment]
I get the **same error** if I run
`# bundle exec rake redmine:plugins:migrate RAILS_ENV="production"`

**Comment by FSCgithub** [comment]
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'redminedb.dmsf_file_revisions' doesn't exist: SHOW FULL FIELDS FROM `dmsf_file_revisions`
/usr/local/rvm/gems/ruby-2.2.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `_query'
/usr/local/rvm/gems/ruby-2.2.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `block in query'
/usr/local/rvm/gems/ruby-2.2.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.2.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `query'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:316:in `execute_and_free'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:463:in `columns'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/attributes.rb:93:in `columns'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/attributes.rb:98:in `columns_hash'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:969:in `block in create_binds'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:967:in `each'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:967:in `partition'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:967:in `create_binds'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:954:in `build_where'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:584:in `where!'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:574:in `where'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/querying.rb:10:in `where'
/opt/redmine-3.4.2/plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:38:in `block in <class:DmsfFileRevision>'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/scoping/named.rb:155:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/scoping/named.rb:155:in `block (2 levels) in scope'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation.rb:302:in `scoping'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/scoping/named.rb:155:in `block in scope'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:94:in `public_send'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:94:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation.rb:302:in `scoping'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:94:in `method_missing'
/opt/redmine-3.4.2/plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:53:in `<class:DmsfFileRevision>'
/opt/redmine-3.4.2/plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:24:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/redmine-3.4.2/plugins/redmine_dmsf/app/models/dmsf_file.rb:82:in `<class:DmsfFile>'
/opt/redmine-3.4.2/plugins/redmine_dmsf/app/models/dmsf_file.rb:31:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:261:in `const_get'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `each'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `inject'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `constantize'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch.rb:13:in `type2class'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:43:in `include_search_methods'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:37:in `block in update_search_methods'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:37:in `each'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:37:in `update_search_methods'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:24:in `block in prepended'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:8:in `class_eval'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:8:in `prepended'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch.rb:24:in `prepend'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch.rb:24:in `block in apply_patch'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch.rb:22:in `each'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch.rb:22:in `apply_patch'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch.rb:63:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/opt/redmine-3.4.2/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Mysql2::Error: Table 'redminedb.dmsf_file_revisions' doesn't exist
/usr/local/rvm/gems/ruby-2.2.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `_query'
/usr/local/rvm/gems/ruby-2.2.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `block in query'
/usr/local/rvm/gems/ruby-2.2.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.2.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `query'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:316:in `execute_and_free'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:463:in `columns'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/attributes.rb:93:in `columns'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/attributes.rb:98:in `columns_hash'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:969:in `block in create_binds'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:967:in `each'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:967:in `partition'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:967:in `create_binds'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:954:in `build_where'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:584:in `where!'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/query_methods.rb:574:in `where'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/querying.rb:10:in `where'
/opt/redmine-3.4.2/plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:38:in `block in <class:DmsfFileRevision>'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/scoping/named.rb:155:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/scoping/named.rb:155:in `block (2 levels) in scope'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation.rb:302:in `scoping'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/scoping/named.rb:155:in `block in scope'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:94:in `public_send'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:94:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation.rb:302:in `scoping'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:94:in `method_missing'
/opt/redmine-3.4.2/plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:53:in `<class:DmsfFileRevision>'
/opt/redmine-3.4.2/plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:24:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/redmine-3.4.2/plugins/redmine_dmsf/app/models/dmsf_file.rb:82:in `<class:DmsfFile>'
/opt/redmine-3.4.2/plugins/redmine_dmsf/app/models/dmsf_file.rb:31:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:261:in `const_get'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `each'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `inject'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `constantize'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch.rb:13:in `type2class'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:43:in `include_search_methods'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:37:in `block in update_search_methods'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:37:in `each'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:37:in `update_search_methods'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:24:in `block in prepended'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:8:in `class_eval'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/patches/redmine_search_patch.rb:8:in `prepended'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch.rb:24:in `prepend'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch.rb:24:in `block in apply_patch'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch.rb:22:in `each'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch.rb:22:in `apply_patch'
/opt/redmine-3.4.2/plugins/redmine_elasticsearch/lib/redmine_elasticsearch.rb:63:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/opt/redmine-3.4.2/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
Loading Rails environment for Resque

**Comment by FSCgithub** [comment]
**production.log**:
...
W, [2018-02-21T15:46:57.878401 #14148]  WARN -- : No Xapian search engine interface for Ruby installed => Full-text search won't be available.
                      Install a ruby-xapian package or an alternative Xapian binding (https://xapian.org).

**Comment by FSCgithub** [comment]
`...No Xapian search engine interface for Ruby installed ...`

This is because until now I did not find a `xapian-omega` package for CentOS 7.

**Comment by picman** [comment]
It's not the problem. The problem seems to be in _redmine_elasticsearch_. Could you remove it temporarily and re-run the migration task?

**Comment by picman** [comment]
Concerning the problem above, install `xapian-bindings` package on CentOS.

**Comment by FSCgithub** [comment]
Hi Karel,
thanks for your reply!!

You were right: There was some kind of a collision between `redmine_elasticsearch` and `redmine_dmsf`. Removing `redmine_elasticsearch` temporarily before installing `redmine_dmsf` worked!

-Thanks for this hint!!

**Comment by FSCgithub** [comment]
> Concerning the problem above, install xapian-bindings package on CentOS.

I tried 
`# yum install xapian*`
That installed:

- xapian-bindings.x86_64  ( 1.2.22-1.el7                 @epel )
- xapian-bindings-python.x86_64     (1.2.22-1.el7                 @epel     )
- xapian-bindings-ruby.x86_64         (1.2.22-1.el7                 @epel     )
- xapian-core.x86_64                      (1.2.22-1.el7                  @epel     )
- xapian-core-devel.x86_64            ( 1.2.22-1.el7                  @epel     )
- xapian-core-libs.x86_64                (1.2.22-1.el7                   @epel     )

But unfortunately the DMSF plugin says `Xapian not available`

**Comment by picman** [comment]
`xapian-bindings-ruby` and `xapian-core` seem to be the required packages on CentOS. Have you restarted Redmine?

**Comment by FSCgithub** [comment]
Neither web server restart `systemctl restart nginx.service` nor system `reboot` made `Xapian` available. :-|

**Comment by FSCgithub** [comment]
Using manual compile and install for Xapian from `tar.xz`-archives seems to work.

https://xapian.org/docs/install.html

**Comment by FSCgithub** [comment]
> Using manual compile and install for Xapian 1.4.5 from tar.xz-archives seems to work.

> Btw. is the full text search field the same as for issues/news etc.?

By compiling and installing Xapian 1.4.5 manually from tar.xz sources I got `xapian-omega`, too, but there was no index database file generated (using default path `$$REDMINE_HGOME/files/dmsf_index)`.

The default full text search field on issues/news etc. level, is used for the ElasticSearch full text search. If there is no other search field for docs I think there will be some kind of "functional collision"...

**Comment by FSCgithub** [comment]
But however, the plugin is **great** (even if we cannot use the full text search ;-) )!

Thank you for your support!!

**Comment by picman** [comment]
1) You must generate the index database manually. See **Full-text search** chapter in README.md.
2) The search field is the same. You should see there two new options _DMS Files_ and _DMS Folders_.

**Comment by FSCgithub** [comment]
Ah, ok!
