### ISSUE TITLE
title_format or dmsf_title_format?

### ISSUE THREAD

**Issue by rkd77** [danmunn/redmine_dmsf#832]
In app/views/dmsf_state/_user_pref.html.erb there is fragment:
 <% member = @project.members.where(:user_id => User.current.id).first %>
 <% if member %>
   <% mail_notification = member.dmsf_mail_notification %>
   <% title_format = member.title_format %>
 <% end %>

But in database there is members.dmsf_title_format .
Is it a bug in code or misconfiguration at my side?

**Comment by picman** [comment]
Run `bundle exec rake redmine:plugins:migrate RAILS_ENV=production`.
