### ISSUE TITLE
Issue attachment problem with DMSF

### ISSUE THREAD

**Issue by asimko** [danmunn/redmine_dmsf#835]
Hello,

this is our environment:
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2

If I install DMSF and want to upload a file (as attachment) in issue, I cannot do it with drag and drop, and other thing is, that after activating DMSF (but not enabling as a module), I have there two options to upload, one is called Files and the other is Documents. If I upload a file in both of them by clicking on upload a file, it works, but one of them is attached as a attachment and the other is dmsf file. Attachment file is ok, I can work with it as ussually, but dmsf file is not ok, because I cannot remove it, or do anything else with it, becasue DMSF module is not enabled. After enabling DMSF as a module, now I can work with that file.
So I have these questions:
- is there a possibility to disable issue attachments and work only with DMSF?
- or can I have the "Documents" file upload have disabled and work in issues with files as attachments as regularly and switch this only if I enable DMSF as a module?
- or am I doing something wrong that I have this disfunctionality?

Thank you for any answer.

**Comment by picman** [comment]
Unfortunately you haven't mentioned the version of DMSF you use. If I try it in 1.6.1, it works fine. If DMS module is disabled, documents attaching is not available. If yes, you can choose either documents and attachments or attachments only or documents only in the project's setting, tab DMS.

**Comment by picman** [comment]
No feedback => closing.
