### ISSUE TITLE
Migrate from DMSF 1.5.5 to 1.6, i can not view files in Redmine

### ISSUE THREAD

**Issue by tobyve** [danmunn/redmine_dmsf#837]
Hello,

I migrate from DMSF 1.5.5 to 1.6, the migration run without errors, but i can not view the files in Redmine, the files it's ok in file system (directory, files permissions , etc).

In the file dmsf.txt, a extract of migration process 

[dmsf.txt](https://github.com/danmunn/redmine_dmsf/files/1807590/dmsf.txt)

thanks a lot.

**Comment by picman** [comment]
Check Roles & Permissions.
--
Karel Pičman

On 13 Mar 2018, at 16:42, tobyve <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I migrate from DMSF 1.5.5 to 1.6, the migration run without errors, but i can not view the files in Redmine, the files it's ok in file system (directory, files permissions , etc).

In the file dmsf.txt, a extract of migration process

dmsf.txt<https://github.com/danmunn/redmine_dmsf/files/1807590/dmsf.txt>

thanks a lot.

**Comment by picman** [comment]
Hm, that's strange. It might be a problem in the migration. It has been quite a big step from 1.5 to 1.6. Could check you database whether your files contain correct project IDs? The project_id should correspond to the project where the documents should be visible.

```
mysql> select id, project_id, name from dmsf_files limit 3;
+----+------------+--------------------+
| id | project_id | name               |
+----+------------+--------------------+
|  1 |          9 | 320497.pdf         |
|  2 |          9 | Test_Cases_2.0.ods |
|  3 |          9 | 10010SRS_1.0.doc   |
+----+------------+--------------------+
```

**Comment by tobyve** [comment]
Yes, project_id is in the table dmsf_files

**Comment by picman** [comment]
Are there any errors or warnings in the `production.log` if you open DMS view with some missing documents?

**Comment by tobyve** [comment]
Nothing.

What do you think to migrate release to release ? (1.5.5 to 1.5.6, 1.5.6 to 1.5.7, 1.5.7 to 1.5.8.....)

<img width="755" alt="screen shot 2018-03-14 at 1 18 31 pm" src="https://user-images.githubusercontent.com/22240175/37419298-885ab2d8-278a-11e8-8b1a-ac75bf4db6da.png">

**Comment by picman** [comment]
It probably makes no sense.

Please check the deleted flag too:

```sql
mysql> select id, project_id, name, deleted from dmsf_files limit 3;
+----+------------+--------------------+---------+
| id | project_id | name               | deleted |
+----+------------+--------------------+---------+
|  1 |          9 | 320497.pdf         |       0 |
|  2 |          9 | Test_Cases_2.0.ods |       0 |
|  3 |          9 | 10010SRS_1.0.doc   |       0 |
+----+------------+--------------------+---------+
```

**Comment by tobyve** [comment]
All the the old files are marked as deleted, the directories too.

I change the flag for files and folders, i can see the folders right now and totals files by folders, but not the files yet.

<img width="477" alt="screen shot 2018-03-15 at 11 42 35 am" src="https://user-images.githubusercontent.com/22240175/37474146-0d11442c-2846-11e8-9f94-245a7d46bd8e.png">
<img width="553" alt="screen shot 2018-03-15 at 11 42 06 am" src="https://user-images.githubusercontent.com/22240175/37474148-0d3fe2f0-2846-11e8-929d-b30b20e902e2.png">

<img width="611" alt="screen shot 2018-03-15 at 11 45 16 am" src="https://user-images.githubusercontent.com/22240175/37474317-77ca61b8-2846-11e8-9b01-d30f7de62c8d.png">

**Comment by picman** [comment]
Probably the same problem in `dmsf_file_revisions` table.

**Comment by tobyve** [comment]
Now works.

Thank you for you support.
