### ISSUE TITLE
webdav not working

### ISSUE THREAD

**Issue by srntm** [danmunn/redmine_dmsf#839]
Hi there,

unfortunately I'm not able to get access to DMSF via WebDAV, opening the URL in a Webbrowser works fine!

> dav:!> open http://192.168.78.10/software/dmsf/webdav/test
> Authentication required for Locked content on server 192.168.78.10:
> Username: testuser
> Password:
> Could not access /software/dmsf/webdav/test/ (not WebDAV-enabled?):
> 405 Method Not Allowed
> Connection to `192.168.78.10' closed.

production.log says:

> Started OPTIONS "/software/dmsf/webdav/test/" for 1.2.3.4 at 2018-03-15 14:20:55 +0100
> Processing WebDAV request: /software/dmsf/webdav/test (for 1.2.3.4 at 2018-03-15 14:20:55 +0100) [OPTIONS]
> Completed in: 0 ms | 401 [http://192.168.78.10/software/dmsf/webdav/test]
> Started OPTIONS "/software/dmsf/webdav/test/" for 1.2.3.4 at 2018-03-15 14:21:00 +0100
> Processing WebDAV request: /software/dmsf/webdav/test (for 1.2.3.4 at 2018-03-15 14:21:00 +0100) [OPTIONS]
> Completed in: 6 ms | 200 [http://192.168.78.10/software/dmsf/webdav/test]
> Started PROPFIND "/software/dmsf/webdav/test/" for 1.2.3.4 at 2018-03-15 14:21:00 +0100
> Processing WebDAV request: /software/dmsf/webdav/test (for 1.2.3.4 at 2018-03-15 14:21:00 +0100) [PROPFIND]
> Completed in: 3 ms | 405 [http://192.168.78.10/software/dmsf/webdav/test]

Apache access log:

> 1.2.3.4 - - [15/Mar/2018:14:23:19 +0100] "OPTIONS /software/dmsf/webdav/test/ HTTP/1.1" 200 434 "-" "cadaver/0.23.3 neon/0.30.1"
> 1.2.3.4 - - [15/Mar/2018:14:23:19 +0100] "PROPFIND /software/dmsf/webdav/test/ HTTP/1.1" 405 291 "-" "cadaver/0.23.3 neon/0.30.1"

Redmine Environment:
  > Redmine version                3.4.4.stable
  Ruby version                   2.3.6-p384 (2017-12-14) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.6.0
> 

running on Ubuntu 14.04 LTS

Do you guys have any clue? :-)

**Comment by picman** [comment]
A few thoughts:
1. WebDAV enabled in the plugin's settings?
2. Try to disable caching in the code and restart the application.
lib/redmine_dmsf/webdav/cache.rb
```ruby
24     class Cache
25       def self.read(name, options = nil)
26   ++    return nil
27         Rails.cache.read(name, options)
28       end
```
3. I've never tested the plugin in sub-uri (/software)

**Comment by srntm** [comment]
Thanks for the short reply.

1. WebDAV is enabled in the plugin's settings
2. I just tried that, but it didn't help -> same result
3. Now I'm quite sure that it has to do with the sub-uri. I have another VM (with exactly the same environment) running at / and it works fine:

> dav:!> open https://redmine.test-server.eu/dmsf/webdav/test
> Authentication required for Locked content on server redmine.test-server.eu:
> Username: testuser
> Password: 
> dav:/dmsf/webdav/test/> ls
> Listing collection `/dmsf/webdav/test/': succeeded.

**Comment by picman** [comment]
Could you test it with the branch devel-1.6.1, please?

**Comment by srntm** [comment]
Yesss! After upgrading to 1.6.1-devel WebDAV is working as expected.

Thanks alot!

**Comment by picman** [comment]
Thank you for the test. v1.6.1 will be released soon.

**Comment by salmanmp** [comment]
> Thank you for the test. v1.6.1 will be released soon.

Hi
Same issue on v2.4.11

**Comment by picman** [comment]
> Hi Same issue on v2.4.11

Create a new issue and provide some details otherwise you cannot expect any solution.
