### ISSUE TITLE
problems with dockerized Redmine instance

### ISSUE THREAD

**Issue by prohde** [danmunn/redmine_dmsf#840]
I am running Redmine 3.4.4 in a Docker container. If I want to use the DMSF plugin I can not upload files. The settings page of the plugin states

> File storage directory doesn't exist and can't be created

But the directory exists. All directories in my <redmine>/files directory have the same access rights and other plugins as well as Redmine itself can upload files. How can I solve this problem?

**Comment by picman** [comment]
1. Post the error from production.log.
2. Try manually access the DMSF folder set in the plugin's settings with the user under whom is run the web application using e.g. `sudo`.

**Comment by prohde** [comment]
1. I can not find any error message in production.log.
2. I can access the folder manually.

Using the relative path instead of the absolute path worked. But I don't know why. I always used the absolute path on my old server where Redmine did not run in a Docker container.
