### ISSUE TITLE
 error in the configuration of projects

### ISSUE THREAD

**Issue by schildg** [danmunn/redmine_dmsf#846]
Hello, I have an error accessing the configuration of a particular project: for example **attention_audio_recording** whose route is
`http: // redminehost / projects / attention_audio_recording / settings`

I get the following error:
![image](https://user-images.githubusercontent.com/29732357/38756702-c465fb7a-3f40-11e8-98c2-eedfc1d4b6f3.png)

console log:
![image](https://user-images.githubusercontent.com/29732357/38756727-d5cc383e-3f40-11e8-9cb6-9e7197b7d713.png)

Redmine Information:
![image](https://user-images.githubusercontent.com/29732357/38756806-196fdfaa-3f41-11e8-9be0-6aefb12a9e52.png)

any ideas? I express your comments

regards

**Comment by picman** [comment]
BTW, the second error differs from the first one and is related to _redmine_ldap_sync_ plugin.
