### ISSUE TITLE
REST API and delete Folder/document

### ISSUE THREAD

**Issue by x-techarts** [danmunn/redmine_dmsf#847]
Is it possible using DMSF API to delete a folder previoulsy created, or to delete a document previously uploaded?

**Comment by picman** [comment]
No, it's not, I'm afraid. But, we can put it on the feature list.

https://github.com/danmunn/redmine_dmsf/wiki/REST-API

**Comment by picman** [comment]
Done.

**Comment by x-techarts** [comment]
Thank you Karel.
Do you have an idea when version 1.6.2 will be available?

**Comment by picman** [comment]
September

**Comment by x-techarts** [comment]
Ok, thanks a lot.
