### ISSUE TITLE
DMSF install to Redmine 3.3.6-0051 on Synology NAS problem

### ISSUE THREAD

**Issue by luckygg** [danmunn/redmine_dmsf#848]
Hi all.

First, I'm so sorry my English.

I want to install redmine_dmsf to redmine 3.3.6-0051 on Synology NAS.

> Environment:
  Redmine version                3.3.6.stable
  Ruby version                   2.3.6-p384 (2017-12-14) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.16.1
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  progressive_projects_list      3.0.1
  redmine_custom_reports         0.1.5
  redmine_issue_checklist        2.1.0
  redmine_issues_tree            0.0.11
  redmine_lightbox2              0.3.5
  redmine_local_avatars          1.0.3
  redmine_monitoring_controlling 0.1.1
  redmine_startpage              0.1.0
  redmine_tags                   3.2.2

If I run the following procedure, an error occurs.
1. Download redmine_dmsf-1.5.2e.
2. Copy to 'redmine's plugins folder'.
3. run 'bundle install.
4. Get error messages.

[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: nokogiri (~> 1.7.2) and nokogiri (>= 1.5.10). Bundler cannot continue.

group :production do
    gem 'nokogiri', '>= 1.5.10'
end

5. So, I modified from 'gem 'nokogiri', '>= 1.5.10' to '# gem 'nokogiri', '>= 1.5.10' on redmine_dmsf/Gemfile.
6. run 'bundle install', and 'bundle exec rake redmine:plugins:migrate RAILS_ENV=production'.
7. I can get a message that the installation was successful.
8. Run redmine page.
9. The page show '502 Bad Gateway'

So.. How can I solve this problem?

Please help me...

Thank you.

**Comment by picman** [comment]
1. For Redmine 3.3.6 use DMSF 1.5.9.
2. You can comment out gems in the Gemfile in case of a conflict.
3. Check _log/production.log_ for the reason of 502 Bad Gateway.

**Comment by luckygg** [comment]
@picman 
Thank you for your reply!

I solved it with DMSF 1.5.5.

But, when I use with DMSF 1.5.8, the 'Internal Error' occurred. (also DMSF 1.5.9)

NoMethodError (undefined method `digest=' for #<DmsfFileRevision:0x0000000006c4f198>):
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:192:in `block in commit_files_internal'
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:140:in `each_value'
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:140:in `commit_files_internal'
  plugins/redmine_dmsf/app/controllers/dmsf_upload_controller.rb:116:in `commit_files'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

So, I can't use with DMSF 1.5.8 but can use with DMSF 1.5.5.

How can I solve that error message?

Thank you.

**Comment by picman** [comment]
It seems that a DB migration failed. There should be `digest` column in the `dmsf_file_revisions table`. Have you run it? You can try to add it manually.

```
mysql> alter table dmsf_file_revisions add column digest varchar(64) not null default '';
```

```
mysql> desc dmsf_file_revisions;
+------------------------------+--------------+------+-----+---------+----------------+
| Field                        | Type         | Null | Key | Default | Extra          |
+------------------------------+--------------+------+-----+---------+----------------+
| id                           | int(11)      | NO   | PRI | NULL    | auto_increment |
| dmsf_file_id                 | int(11)      | NO   | MUL | NULL    |                |
| source_dmsf_file_revision_id | int(11)      | YES  |     | NULL    |                |
| name                         | varchar(255) | NO   |     | NULL    |                |
| disk_filename                | varchar(255) | NO   |     | NULL    |                |
| size                         | bigint(20)   | YES  |     | NULL    |                |
| mime_type                    | varchar(255) | YES  |     | NULL    |                |
| title                        | varchar(255) | NO   |     | NULL    |                |
| description                  | mediumtext   | YES  |     | NULL    |                |
| workflow                     | int(11)      | YES  |     | NULL    |                |
| major_version                | int(11)      | NO   |     | NULL    |                |
| minor_version                | int(11)      | NO   |     | NULL    |                |
| comment                      | mediumtext   | YES  |     | NULL    |                |
| deleted                      | int(11)      | NO   |     | 0       |                |
| deleted_by_user_id           | int(11)      | YES  |     | NULL    |                |
| user_id                      | int(11)      | NO   |     | NULL    |                |
| created_at                   | datetime     | YES  |     | NULL    |                |
| updated_at                   | datetime     | YES  |     | NULL    |                |
| dmsf_workflow_id             | int(11)      | YES  |     | NULL    |                |
| dmsf_workflow_assigned_by    | int(11)      | YES  |     | NULL    |                |
| dmsf_workflow_assigned_at    | datetime     | YES  |     | NULL    |                |
| dmsf_workflow_started_by     | int(11)      | YES  |     | NULL    |                |
| dmsf_workflow_started_at     | datetime     | YES  |     | NULL    |                |
| digest                       | varchar(64)  | NO   |     |         |                |
+------------------------------+--------------+------+-----+---------+----------------+
24 rows in set (0,00 sec)
```

**Comment by luckygg** [comment]
@picman 
Thank you for your reply!

There was a problem with the DB as you said.
But after add 'digest', other error occurred :(

ActionView::Template::Error (Mysql2::Error: Unknown column 'dmsf_workflows.status' in 'where clause': SELECT COUNT(*) FROM `dmsf_workflows` WHERE `dmsf_workflows`.`status` = 1 AND `dmsf_workflows`.`project_id` = 3):
    39:   &nbsp;
    40: <% end %>  
    41: 
    42: <% if @workflows.any? %>  
    43:   <table class="list">
    44:     <thead><tr>
    45:       <th><%=l(:field_name)%></th>    
  plugins/redmine_dmsf/app/views/dmsf_workflows/_main.html.erb:42:in `_plugins_redmine_dmsf_app_views_dmsf_workflows__main_html_erb___1305383888598716936_92501480'
  app/views/common/_tabs.html.erb:17:in `block in _app_views_common__tabs_html_erb__1342017397813054551_75099980'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_app_views_common__tabs_html_erb__1342017397813054551_75099980'
  app/helpers/application_helper.rb:326:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__4250782171130359867_74409860'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

How can solve it? ;;

Thank you.

**Comment by picman** [comment]
Obviously, your database is in a very bad state.... Next step:

```sql
mysql> alter table dmsf_workflows add column status1 int not null default 1;
```

**Comment by luckygg** [comment]
@picman
Hi picman!

I still have problems...

ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'dmsf_files.container_id' in 'where clause': SELECT COUNT(*) FROM `dmsf_files` WHERE `dmsf_files`.`deleted` = 1 AND `dmsf_files`.`container_id` = 3 AND `dmsf_files`.`container_type` = 'Project'):
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:698:in `get_display_params'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:51:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

I uninstalled MariaDB, Redmine on Synology, and reinstalled but still have problems.

Is there a solution?

Thank you. T_T

**Comment by picman** [comment]
1. Install DMSF 1.6.0.
2. Run the plugin migration task.
3. Fix migrations problems if any by manual updates in the database.

**Comment by luckygg** [comment]
@picman
Hi picman!

1. Install DMSF 1.6.0
-> Redmine::PluginRequirementError: redmine_dmsf plugin requires Redmine 3.4.0 or higher but current is 3.3.6.stable

So, I commented out the redmine version check.

2. Run the plugin migration task.
-> bundle exec rake redmine:plugins:migrate RAILS_ENV=production

3. Update DB
-> alter table dmsf_workflows add column status int not null default 1;

Above result, I can upload the files!
But, the new issue occurred...

When I clicked the 'create folder', the error messages occurred.

ActionView::Template::Error (Mysql2::Error: Unknown column 'dmsf_folders.system' in 'where clause': SELECT DISTINCT `dmsf_folders`.* FROM `dmsf_folders` INNER JOIN `projects` ON `projects`.`id` = `dmsf_folders`.`project_id` LEFT JOIN dmsf_folder_permissions ON dmsf_folders.id = dmsf_folder_permissions.dmsf_folder_id WHERE `dmsf_folders`.`project_id` = 3 AND `dmsf_folders`.`dmsf_folder_id` IS NULL AND `dmsf_folders`.`system` = 0 AND `dmsf_folders`.`deleted` = 0 AND (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='dmsf'))  ORDER BY `dmsf_folders`.`title` ASC):
    73:     </p>  
    74:     <p>      
    75:       <%= f.select(:dmsf_folder_id, 
    76:         options_for_select(DmsfFolder.directory_tree(@project, @folder), 	
    77:         :selected => @parent? @parent.id : (@pathfolder.id if @pathfolder)),
    78:       :label => l(:field_folder))                           
    79:       %>				
  plugins/redmine_dmsf/app/models/dmsf_folder.rb:228:in `directory_tree'
  plugins/redmine_dmsf/app/views/dmsf/edit.html.erb:76:in `block in _plugins_redmine_dmsf_app_views_dmsf_edit_html_erb___1673523442276304566_72525880'
  app/helpers/application_helper.rb:1052:in `labelled_form_for'
  plugins/redmine_dmsf/app/views/dmsf/edit.html.erb:67:in `_plugins_redmine_dmsf_app_views_dmsf_edit_html_erb___1673523442276304566_72525880'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:185:in `new'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Does this messages also problem with the DB?

Thank you.

**Comment by picman** [comment]
Yes, try:
```sql
mysql> alter table dmsf_folders add column system tinyint(1) not null default 0;
```

**Comment by luckygg** [comment]
@picman
Hi picman!

Thank you for your support!

Finally, I can use it!

Upload, Download, Create Folder, Delete... are no problem!

Thank you very much!

**Comment by picman** [comment]
Great!
