### ISSUE TITLE
install err :You specified: dalli (>= 0) and dalli (~> 2.7.0). Bundler cannot continue

### ISSUE THREAD

**Issue by kevinzu007** [danmunn/redmine_dmsf#849]
under  docker-compose 
redmine 3.4.
dmsf Version 1.6.1

# docker logs  8aac96b91654
Initializing logdir...
Initializing datadir...
Symlinking dotfiles...
Installing configuration templates...
SSL keys and certificates were not found.
Assuming that the container is running behind a HTTPS enabled load balancer.
Configuring redmine...
Configuring redmine::database...
Configuring redmine::memcached...
Configuring redmine::unicorn...
Configuring redmine::secret_token...
Configuring redmine::max_concurrent_ajax_uploads...
Configuring redmine::sudo_mode...
Configuring redmine::autologin_cookie...
Configuring redmine::email_delivery...
Configuring redmine::backups...
Configuring redmine::backups::schedule...
Configuring nginx...
Configuring nginx::redmine...
Configuring nginx::redmine::hsts...
Installing plugins...
Installing gems required by plugins...

[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: dalli (>= 0) and dalli (~> 2.7.0). Bundler cannot continue.

 #  from /home/redmine/redmine/Gemfile:116
 #  -------------------------------------------
 #  gem "unicorn"
 >  gem "dalli", "~> 2.7.0"
 #  -------------------------------------------

**Comment by picman** [comment]
Redmine itself doesn't require "dalli". DMSF requires "dalli" >= 0. It's not problem of DMSF that someone else requires "dalli" >= 2.7. As a workaround you can comment out "dalli" in plugins/redmine/dmsf/Gemfile as follows:

``` ruby
27 - gem 'dalli'
27 + #gem 'dalli'

```
