### ISSUE TITLE
REST API and pagination on collection resources

### ISSUE THREAD

**Issue by x-techarts** [danmunn/redmine_dmsf#850]
Using standard redmine REST API, it's possible to manage pagination on collection by adding "offset" and "limit" parameter in the GET URL query string (cf. http://www.redmine.org/projects/redmine/wiki/Rest_api - "collection resources and pagination" paragraph).
Is there a such mechanism in DMSF REST API while requesting on a collection resources, or all the objects available in the dataset are returned in this case?
I did not found anything about that in the DMSF REST API doucmentation.

**Comment by picman** [comment]
No, this is not available. Let's put it on the feature list.

**Comment by picman** [comment]
You can specify _limit_ and _offset_ parameters in your REST API query.

e.g. ```curl -v -H "Content-Type: application/xml" -X GET -u ***:*** "http://localhost:3000/dmsf/files/17216.xml?limit=1&offset=1```
