### ISSUE TITLE
WebDAV 1.6.1 seems broken with "Use project name for project folder" and spaces in names

### ISSUE THREAD

**Issue by mikitex70** [danmunn/redmine_dmsf#851]
The WebDAV interface in DMSF 1.6.1 gives me strange results when the `Use project name for project folder` option is set and there are projects with spaces in their names.
Going to `http://my-redmine-url/dmsg/webdav` the page shows the same project names repeated many times (it seems they are choosen randomly) but the links seems to point to the correct projects.
Navigating to the project documents seems to give random results: sometimes the documents are shown, sometimes not.
If the `Use project name for project folder` is unchecked, the WebDAV is working fine.

Tested with:
* Redmine 3.4.4 stable
* DMSF 1.6.1
* Redmine_Drawio v0.8.2 (develop branch)

**Comment by picman** [comment]
Fixed in the master branch. Can you update your branch and test it, please?

**Comment by mikitex70** [comment]
All fine, thank you for your great work.
