### ISSUE TITLE
Workflow notification missing

### ISSUE THREAD

**Issue by mrazek** [danmunn/redmine_dmsf#855]
Users are notified about being part of workflow only when they have "For any event ..." option set in their redmine profile. If they set "Only for things I watch or I'm invilved in", no notification is sent.

configuration
redmine 3.3.1.stable
ruby 2.3.0-p0 (2015-12-25) [x86_64-linux]
dmsf 1.5.9

**Comment by picman** [comment]
Fixed.

**Comment by mrazek** [comment]
After approval process was finished I got this error... Do you have any idea, what went wrong?

Completed 500 Internal Server Error in 80ms (ActiveRecord: 38.5ms)
NoMethodError (undefined method `assignee?' for #<DmsfFile:0x005585824a3dc0>
Did you mean?  assigned?):
  plugins/redmine_dmsf/app/models/dmsf_mailer.rb:109:in `block (2 levels) in get_notify_users'
  plugins/redmine_dmsf/app/models/dmsf_mailer.rb:108:in `each'
  plugins/redmine_dmsf/app/models/dmsf_mailer.rb:108:in `block in get_notify_users'
  plugins/redmine_dmsf/app/models/dmsf_mailer.rb:95:in `get_notify_users'
  plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb:75:in `new_action'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'

Many thanks,
Jan

**Comment by picman** [comment]
A typing mistake. Sorry. Fixed.
