### ISSUE TITLE
Mysql2::Error: Table 'redmine.easy_settings'

### ISSUE THREAD

**Issue by luckygg** [danmunn/redmine_dmsf#856]
Hi all.
The internal error is occurred when I delete the project.

Environment :
Environment:
  Redmine version                3.3.6.stable
  Ruby version                   2.3.6-p384 (2017-12-14) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.16.1
  Filesystem                     
Redmine plugins:
  redmine_ckeditor               1.1.5
  redmine_dmsf                   1.6.0
  redmine_highlightjs            1.0.3

Error Message :
ActiveRecord::StatementInvalid (Mysql2::Error: Table 'redmine.easy_settings' doesn't exist: SHOW FULL FIELDS FROM `easy_settings`):
  app/controllers/projects_controller.rb:225:in `destroy'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

If I delete the DMSF plugin, there is no error.

Please advise me...

Thank you!

**Comment by picman** [comment]
The table is created by _redmine_extensions_ gem which is required in the _Gemfile_. So verify that _redmine_extensions_ gem is installed and your redmine database contains _easy_settings_ table. If not, intstall/reinstall _redmine_extensions_ gem.

**Comment by luckygg** [comment]
Thank you @picman 

Strangely, I reinstalled redmine and plugin so it is solved...

Thank you for your help.

**Comment by acosonic** [comment]
Above error is caused by failed install of some of **_easy plugins._** 

They require **rake db:migrate RAILS_ENV=production** step!
