### ISSUE TITLE
Xapian not indexing repository if project configuration is blank

### ISSUE THREAD

**Issue by schildg** [danmunn/redmine_dmsf#857]
Hi, I believe that there should be a way to index all the repositories that are created automatically, without the need to manually add them from a single one, so that the indexing by crontab is carried out.

as requested for: https: //github.com/xelkano/redmine_xapian/issues/91

another issue install from scratch redmine_dmsf and I get an error in indexing repositories because the Indexinglog table is missing, so I had to install redmine_xapian, which is no longer necessary.

**Comment by picman** [comment]
Indexing of repositories doesn't belong to Redmine DMS plugin => Removed.
