### ISSUE TITLE
Render error after update to Ruby 2.5.1

### ISSUE THREAD

**Issue by rtestaverde** [danmunn/redmine_dmsf#860]
Hi all, having an error after update to Ruby 2.5.1 

ActionView::Template::Error in Dmsf#show
wrong number of arguments (given 0, expected 1..2)
near this block of code:

```
       def context_menu_with_easy_extensions(url, container='table.list')
        javascript_tag("EASY.contextMenu.addContextMenuFor( '#{ url_for(url) }', '#{container}' )") if url
      end
```
**Application trace:**

plugins/easyproject/easy_plugins/easy_extensions/lib/easy_patch/redmine/helpers/application_helper_patch.rb:2497:in `context_menu_with_easy_extensions'
plugins/redmine_dmsf/app/views/dmsf/show.html.erb:125:in `_plugins_redmine_dmsf_app_views_dmsf_show_html_erb__536451992077343389_96215640'
plugins/easyproject/easy_helpers/before_render/lib/before_render/before_render_instance.rb:12:in `block in render_with_before_render_filter'
plugins/easyproject/easy_helpers/before_render/lib/before_render/before_render_instance.rb:11:in `render_with_before_render_filter'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:65:in `block (2 levels) in show'
plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:63:in `show'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'

**Request parameters**

  Params                         {"controller"=>"dmsf", "action"=>"show", "id"=>"ceoe-pcae-suite-de-prl"}
  URL                            https://redmine.DOMAIN.TLD/projects/PROJECT_ID/dmsf
  Remote IP                      80.28.245.247

**Environment**

  Redmine version                3.4.4.stable
  Brand version                  2018.1.1
  Platform version               2018.02.07
  Last commit SHA                
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
  Rails root                     /opt/redmine/redmine-3.4.4
  Gem root                       /opt/redmine/.rvm/gems/ruby-2.5.1
  Hostname                       UbuntuSrv14

**Easy Redmine with plugins:**

  before_render                  
  ckeditor                       
  clipboard_image_paste          1.9
  sanitize                       
  easy_extensions                2018
  easy_agile_board               2018
  easy_alerts                    2018
  easy_budgetsheet               2018
  easy_buttons                   2018
  easy_calculation               2018
  easy_calendar                  2018
  easy_data_templates            2018
  easy_helpdesk                  2018
  easy_money                     2018
  easy_outlook                   1.1
  easy_printable_templates       2018
  easy_project_attachments       2018
  easy_quick_project_planner     2018
  easy_redmine                   
  easy_to_do_list                2018
  easy_xml_helper                2018
  easy_baseline                  1.3
  easy_checklist                 2018
  easy_gantt                     1.9
  easy_gantt_pro                 1.9
  easy_gantt_resources           1.6
  easy_instant_messages          2016
  easy_job                       1.1
  easy_mindmup                   1.0
  easy_wbs                       1.5
  easy_zoom                      2018
  redmine_bootstrap_kit          0.2.5
  redmine_dmsf                   1.6.1
  redmine_test_cases             2016

**Comment by picman** [comment]
I think that the problem is related to a different plugin:
```plugins/easyproject/easy_plugins/easy_extensions/lib/easy_patch/redmine/helpers/application_helper_patch.rb:2497```

**Comment by picman** [comment]
There is used Redmine's function 'context_menu' in DMSF plugin. EasyRedmine plugin has extended this method and has given it two more parameters. While the original Redmine's method is without any parameters. That's the problem. If a plugin overrides a method, it's called instead of the original one even from other plugins. You should contact EasyRedmine instead. As a workaround you can replace 
``` <% context_menu %>``` with ``` <% context_menu_without_easy_extensions %>``` in DMSF plugin's code.

**Comment by rtestaverde** [comment]
Thankyou again.
I'll close this issue
