### ISSUE TITLE
Slow issue when move the directory.

### ISSUE THREAD

**Issue by luckygg** [danmunn/redmine_dmsf#861]
Hi all.

I have a slow issue when move the directory.
(I am using the redmine on Synology NAS.)

Environment:
  Redmine version                3.3.6.stable
  Ruby version                   2.3.6-p384 (2017-12-14) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
Redmine plugins:
redmine_dmsf                   1.6.0

Log :
Started GET "/projects/tech/dmsf?folder_id=1" for 127.0.0.1 at 2018-05-18 04:26:09 +0000
Processing by DmsfController#show as HTML
  Parameters: {"folder_id"=>"1", "id"=>"tech"}
  Current user: MyTest (id=5)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (54.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (49.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (53.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (170.2ms)
/home/redmine/redmine/plugins/redmine_dmsf/app/helpers/../../assets/javascripts/jquery.dataTables/ko.json not found
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (4.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (9.2ms)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (3.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (231.0ms)
redmine_highlightjs2: supported browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.4ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_sidebar.html.erb (0.1ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_recent_projects.html.erb (3.8ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (8.4ms)
Completed 200 OK in **1244ms** (Views: 657.4ms | ActiveRecord: 154.5ms)

Why is so slow?
How can I speed up?

Thank you :)

**Comment by picman** [comment]
Could you add a little more information. In the chunk of your log I see just SHOW method - displaying of a folder content. How many files and folders is in the folder in the current view and how many of them altogether? What's the relation to the MOVE operation?

**Comment by luckygg** [comment]
Please tell me which log you need.

I have only a few folders and a few files. (not even 10)

I mean 'MOVE' is just 'mouse click'.
If directory is defined as following
'Documents > Folder1 > Folder2 > Folder3' on DMS.
I just clicked 'Folder1' and 'Folder2'. 
(change directory.)

**Comment by picman** [comment]
And the server's parameters? 1,2s is not so slow if you consider the graphics and a lot of SQL queries behind. The weakest point can be the database.

**Comment by luckygg** [comment]
Where are the server's parameters?
So, there is no way to speed up?

And I tested with the redmine on Windows, back up all files from Synology redmine to Widnows redmine.
The DMSF on Windows redmine is very fast.

What is the difference?

**Comment by picman** [comment]
- Operationg system
- RAM
- disk type
- SQL server local/remote, database

Recommended:

- Linux
- As much as possible
- SSD disk
- MySQL on localhost

**Comment by luckygg** [comment]
OS : Synology (maybe.. based on linux?)
RAM : 16GB
SSD 250GB
SQL Server : MariaDB 10 (Synology Package)

Can it be slowed down by other plugins installed?
I installed so many plugins...

Environment:
  Redmine version                3.3.6.stable
  Ruby version                   2.3.6-p384 (2017-12-14) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.16.1
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  progressive_projects_list      3.0.1
  redmine_ckeditor               1.1.5
  redmine_custom_reports         0.1.5
  redmine_dmsf                   1.6.0
  redmine_highlightjs            1.0.3
  redmine_issue_checklist        2.1.0
  redmine_issue_templates        0.1.9
  redmine_lightbox2              0.3.5
  redmine_local_avatars          1.0.3
  redmine_monitoring_controlling 0.1.1
  redmine_questions              0.0.7
  redmine_startpage              0.1.0

**Comment by picman** [comment]
I don't know. This is really not related to DMSF development. Sorry.
