### ISSUE TITLE
No route matches [GET] "/javascripts/redmine_extensions/dynamic_loading.js"

### ISSUE THREAD

**Issue by snw1968** [danmunn/redmine_dmsf#864]
Centos 7.4
Redmine version 3.4.5 stable
Ruby 2.4.1

Having installed redmine_dmsf from master download - I now have the error detailed below.
Uninstalling redmine_dmsf - the error goes away.

Started GET "/redmine/" for 999.999.999.999 at 2018-05-28 16:05:32 +0100
Processing by WelcomeController#index as HTML
  Current user: myuser@somewhere.com (id=5)
  Rendered welcome/index.html.erb within layouts/base (3.6ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (2.9ms)
  Rendered plugins/usability/app/views/hooks/usability/_html_head.html.erb (1.7ms)
  Rendered plugins/usability/app/views/hooks/usability/_body_bottom.html.erb (0.2ms)
Completed 200 OK in 65ms (Views: 25.1ms | ActiveRecord: 33.1ms)
**Started GET "/redmine/javascripts/redmine_extensions/dynamic_loading.js" for 999.999.999.999 at 2018-05-28 16:05:32 +0100**

**ActionController::RoutingError (No route matches [GET] "/javascripts/redmine_extensions/dynamic_loading.js"):**
  actionpack (4.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.10) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.10) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.8) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.10) lib/rack/content_length.rb:15:in `call'
  rack (1.6.10) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.8) lib/rails/engine.rb:518:in `call'
  railties (4.2.8) lib/rails/application.rb:165:in `call'
  railties (4.2.8) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.8) lib/rails/railtie.rb:194:in `method_missing'
  passenger (5.2.3) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  passenger (5.2.3) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  passenger (5.2.3) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  passenger (5.2.3) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  passenger (5.2.3) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

Processing by UsErrorsController#error_404 as */*
  Current user: myuser@somewhere.com (id=5)
  Rendered plugins/usability/app/views/errors/error_status.html.erb (4.5ms)
Completed 404 Not Found in 11ms (Views: 4.6ms | ActiveRecord: 1.6ms)
Started GET "/redmine/javascripts/redmine_extensions/dynamic_loading.js" for 999.999.999.999 at 2018-05-28 16:05:32 +0100

**Comment by picman** [comment]
> Maybe in lib/redmine_extensions/hooks.rb
Right. But, this's Redmine DMSF plugin project, not Redmine Extensions.

**Comment by flybyray** [comment]
https://github.com/easyredmine/redmine_extensions/issues/4
