### ISSUE TITLE
Deleting projects cause internal error

### ISSUE THREAD

**Issue by acosonic** [danmunn/redmine_dmsf#870]
due to redmine_extensions gem, error is following:

`Started DELETE "/projects/proba" for 188.2.64.3 at 2018-06-07 05:58:00 +0200
Processing by ProjectsController#destroy as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"H27zgxH0EpmEo/IFh1vJz+I+UOY2XpTTQoxAs4HQ6qs1ceJdWfNAAr1tgL1D8UcvnH74QYYrk2HdXuPfbJwCXQ==", "confirm"=>"1", "commit"=>"Izbriši", "id"=>"proba"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 85ms (ActiveRecord: 25.5ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'impex.easy_settings' doesn't exist: SHOW FULL FIELDS FROM `easy_settings`):
  app/controllers/projects_controller.rb:241:in `destroy'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'

impex@host1:~/redmine-3.4$ cd plugins/
impex@host1:~/redmine-3.4/plugins$ grep -R "easy_settings" .
impex@host1:~/redmine-3.4/plugins$ grep -R "redmine_extensions" .
./redmine_dmsf/Gemfile:  gem 'redmine_extensions', '~>`

**Comment by picman** [comment]
It duplicates #856.

You can add the missing tables manually too, e.g.:

```sql
CREATE TABLE `easy_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `value` text COLLATE utf8mb4_unicode_ci,
  `project_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_easy_settings_on_project_id` (`project_id`),
  CONSTRAINT `fk_rails_31c4b01147` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `easy_entity_assignments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entity_from_id` int(11) DEFAULT NULL,
  `entity_from_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `entity_to_id` int(11) DEFAULT NULL,
  `entity_to_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by ahorek** [comment]
please run **bundle exec rake db:migrate RAILS_ENV=production**

**Comment by KevinB87** [comment]
ahorek , so much thank you for your solution.
i resolved my problem. 
thanks.
