### ISSUE TITLE
500 Internal Server Error  when opening project settings

### ISSUE THREAD

**Issue by carodrigues** [danmunn/redmine_dmsf#873]
500 Internal Server Error when opening project settings after installing latest DSMF update: 

Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"crm"}
  Current user: crodrigues (id=121)
  Rendered projects/settings.html.erb within layouts/base (440.4ms)
Completed 500 Internal Server Error in 458ms (ActiveRecord: 6.8ms)

ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x9738948>:0xd68d230>
Did you mean?  project_settings_tabs_with_contacts):
    1: <h2><%=l(:label_settings)%></h2>
    2: 
    3: <%= render_tabs project_settings_tabs %>
    4: 
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  plugins/redmine_issue_templates/lib/issue_templates/projects_helper_patch.rb:16:in `project_settings_tabs_with_issue_templates'
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  app/views/projects/settings.html.erb:3:in `_f52613c8a0d7706bc4863f60a7d12048'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'

**Comment by picman** [comment]
It duplicates #845. Have you read CHANGELOG.md?
