### ISSUE TITLE
Full-Text-Search not working

### ISSUE THREAD

**Issue by itadminatitgroup** [danmunn/redmine_dmsf#875]
Hi,
i have a Problem with the Full-Text-Search feature in DMSF Plugin.

I tried it with `omindex --url / --db /_daten1/bitnami_redmine/apps/redmine/htdocs/files/dmsf_index/german/ /_daten1/bitnami_redmine/apps/redmine/htdocs/files/dmsf`

and also with `ruby redmine_dmsf/extra/xapian_indexer.rb -vf`

here are my configurations
Xapian Config File:
![xapian_config](https://user-images.githubusercontent.com/32698930/41394080-ef18b2b6-6fa8-11e8-90a4-eb049cacc569.png)

DMSF Plugin Configuration:
![dmsf_plugin](https://user-images.githubusercontent.com/32698930/41394091-fe171618-6fa8-11e8-80eb-1baaed36ce33.png)

do you have an idea what the problem could be? 

thanks in advance,
Andy

**Comment by picman** [comment]
No, because you have omitted to describe the problem you had got. `ruby redmine_dmsf/extra/xapian_indexer.rb -vf` is corect. Also `xapian_indexer.rb` looks good.

Please specify the problem and also post output from indexing and a screenshot from searching. `production.log` might content some useful information too.

**Comment by itadminatitgroup** [comment]
Thanks for the fast answer.

Here is the Output when i ran omindex and xapian_indexer.rb
![omindex](https://user-images.githubusercontent.com/32698930/41399265-220e4daa-6fba-11e8-9a6e-ff0a86a87bce.png)

now here is the weird part...

if i use the search bar from Redmine directly it does a full text search but only for .txt files.
Filename: Plugintest.txt 
![redmine_search](https://user-images.githubusercontent.com/32698930/41399470-b9e9633a-6fba-11e8-856f-cb620d306f43.png)

if i use the search bar for DMS it finds the files correctly but if i try to search inside the files it returns no results.
![dms_search1](https://user-images.githubusercontent.com/32698930/41399629-17442fce-6fbb-11e8-91d0-088af69a35fa.png)

Here i'm searching for "dokumente" and it finds the file.
![dms_search3](https://user-images.githubusercontent.com/32698930/41399677-38e1004e-6fbb-11e8-88ce-9c2746e55ea6.png)

And here i'm searching a word inside the Plugintest.txt and it shows no result.
![dms_search2](https://user-images.githubusercontent.com/32698930/41399718-5caa7b40-6fbb-11e8-9aa2-5b7d9a2f8a2c.png)

Here the production.log output:
![production_log](https://user-images.githubusercontent.com/32698930/41399742-6cb08dea-6fbb-11e8-86d2-367b38d4e94f.png)

it outputs only the searching results from the redmine search bar if i'm using the DMS Search bar nothing will be logged.

**Comment by picman** [comment]
The DMS search box works as a filter only. If used, only files and folders with the given text in file/folder's name are displayed. It should be called _Filter_ not _Search_, but the text _Search_ comes from the used PlUpload control. If you want to use full-text search you must use Redmine's search box.

**Comment by itadminatitgroup** [comment]
I see. Thanks for explaining. 
Unfortunatly if i use the Redmine Search it also only finds **.txt** files as full-text-search if i'm searching words inside **.odt** file type. It's not showing any results. Any idea what could be the problem?

**Comment by picman** [comment]
From the Xapian indexer I see that some ODT files were successfully indexed. In the Search view you are searching for 'firefox'. Is the word 'firefox' inside an ODT file?

**Comment by itadminatitgroup** [comment]
I found the Problem. I was searching the header part inside the .odt file i think it's not possible to be searching the header part? If i'm searching the body part the full-text-search is working.
So the Problem is solved :) thanks again!

**Comment by picman** [comment]
You're right. Xapian uses `unzip` for ODT files. Then indexes the text from `content.xml` file. But, header and footer's contents are in `styles.xml`, which is not indexed.
```
$ unzip test.odt 
Archive:  test.odt
 extracting: mimetype                
 extracting: Thumbnails/thumbnail.png  
   creating: Configurations2/accelerator/
   creating: Configurations2/popupmenu/
   creating: Configurations2/toolpanel/
   creating: Configurations2/menubar/
   creating: Configurations2/images/Bitmaps/
   creating: Configurations2/toolbar/
   creating: Configurations2/floater/
   creating: Configurations2/statusbar/
   creating: Configurations2/progressbar/
  inflating: content.xml             
  inflating: meta.xml                
  inflating: manifest.rdf            
  inflating: settings.xml            
  inflating: styles.xml              
  inflating: META-INF/manifest.xml   
```
