### ISSUE TITLE
DMSF - WebDav Question

### ISSUE THREAD

**Issue by itadminatitgroup** [danmunn/redmine_dmsf#876]
Hello,

i have a question regarding DMSF.

I'm using WebDav to upload Folders with Files.

If for example i'm accidentally deleting a File or Folder from WebDav is it possible to restore the File/Folder?

Or are the Files/Folder permanently deleted?

thanks in advance,
Andy

**Comment by picman** [comment]
Yes, if you go back to the DMS web interface your can restore them from the trash bin,

**Comment by itadminatitgroup** [comment]
Ahh great! Did saw the trash bin on the right side. Works like a charm.
thanks again for your help!
