### ISSUE TITLE
Enlarge "Link To" form fields

### ISSUE THREAD

**Issue by davidepozzi** [danmunn/redmine_dmsf#878]
Hello.

Is it possible to enlarge the "Link from" form fileds? I see them very narrow and it is sometimes very difficult to select the correct path, for example.

Thank you.

Davide

**Comment by picman** [comment]
Please post a screen-shot and mark there which control you refer to.

**Comment by davidepozzi** [comment]
Hello.

This is the most annoying problem:

![image](https://user-images.githubusercontent.com/35496129/41535170-a3df86c4-7301-11e8-9c79-5a1c9fd1a777.png)

This field could be enlarged as well:

![image](https://user-images.githubusercontent.com/35496129/41535220-d4034c1e-7301-11e8-923f-b2d9ec8ee4ae.png)


Thanks for helping!


Davide

**Comment by picman** [comment]
I've set a minimal with for the select control. It should be better now. Concerning the height of the drop-down area I don't know how to do that, sorry.

**Comment by davidepozzi** [comment]
Great! Will this modification be included in the next release?

Thank you!

**Comment by picman** [comment]
Yes, the milestone is set to 1.6.2.
