### ISSUE TITLE
Removing steps of approval_workflows causes data corruption

### ISSUE THREAD

**Issue by PedroTeixido** [danmunn/redmine_dmsf#880]
We had a employee who left the company. And so, he was removed from the approval_workflow, and the new employee was added.

The effect is that all the approved/rejected actions he had done had been lost. Any approved/rejected revision, when you try to see the approval_workflow history and reasons for it to be rejected or approved, the records are broken at the step of the employee who left the company.

Also, I don't fully understand this yet, but some dates are been corrupted as a consequence of this approval_workflow change. We currently have files approved earlier than created!!! And so, I think some created dates were changed to the date of the change in the approval_workflow.

This is a critical issue for us, as we may fail audits because our records could be corrupted at any point we change anyone involved in the approval_workflow.

**Comment by picman** [comment]
Understood. I recommend keeping the following rules when an employee leaving the company:
1. Don't remove the user, just lock it.
2. Don't change the existing approval workflow. Just lock it as well and create a new one with the former employee replaced with a substitute.
Then all documents and assigned workflows kept untouched.

Concerning the dates I will check it.

**Comment by picman** [comment]
I've just tested it and haven't found anything odd. This is an approval workflow log after removing a user.

![image](https://user-images.githubusercontent.com/779003/41653329-04e54ff0-7486-11e8-97a7-2f70ed536079.png)

If I remove the approval step 1, the last line from the log simply disappear.
Dates in both cases remain unchanged.

Maybe test it again and provide some screen-shots of your case.

**Comment by PedroTeixido** [comment]
Good,

This is a good workaround :-)
The one we were using it is less practical

Thank you

**Comment by PedroTeixido** [comment]
I'm not sure the steps my colleague did. So, I'm not sure I could reproduce
it, but I'll have a go and let you know.

**Comment by PedroTeixido** [comment]
I have just review the what you said, and it is exactly this "If I remove the approval step 1, the last line from the log simply disappears" but in my case is the line corresponding to the one of the users of one of the steps.

And this causes the information to be broken, all approved or rejected files loose the comments of the user that has been removed. I have check in the data base, and they are also removed from it. So, there is no way to recover them unless you have a backup of the DB before removing the user.
Also, if any open approval is waiting on the user you remove, the approval process can not be recovered. But this will be a minor problem, as the file can be re-upload and the approval workflow re-launched.

In the other hand, we have been using the workaround you told me, but it gets really hard to identify all open approvals associated to a particular approval workflow. And in order to use the workaround we have to make sure there are no open approvals before locking the workflow. Is there any way to see this in the current version? Are you planning to do it?

Thanks!

**Comment by picman** [comment]
Add 1)
That's right. If you remove an approval step, all the corresponding records are removed.

Add 2)
Just a note that if you want to restart an approval workflow by a document, there is no need to upload the file again. Just create a new revision in the document's details.

Add 3)
Unfortunately, there is no such plan. You can merely see open approvals for a particular user on "My Page".

**Comment by picman** [comment]
Approval workflows in use can be no more edited or deleted. Project approval workflows can be locked instead now. So, if we need to update an approval workflow, which has been already assigned to document, we should lock it and create a new one.
