### ISSUE TITLE
DMSF access for anonymous users

### ISSUE THREAD

**Issue by mrazek** [danmunn/redmine_dmsf#881]
Is it possible to grant read/only access for anonymous users to DMS, so they can see folders and browse them, but no deletions, edits etc...?
I did the project public, I granted role to Anonymous user, I added Anonymous users into project as reporter, however, I can't see any folder (although I added anonymous user to folder permissions).

Please, do you have any clue how to grant such public read-only access?

**Comment by mrazek** [comment]
Just s small remark... If i put direct link into the web browser, file is for anonymous user available. But folders are not visible.

**Comment by AndyLicht** [comment]
Hi, thanks for this great plugin. But it would nice to fix this bug.

**Comment by picman** [comment]
Fixed.
