### ISSUE TITLE
DMSF install to Redmine 3.4 , Project setting tab is not working

### ISSUE THREAD

**Issue by sucharithag** [danmunn/redmine_dmsf#884]
I have installed DMSF1.6.1 in redmine 3,4 it is working fine but project settings tab is returing "Internal Error" 
with below message.

"Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back".

Production Log:

Started GET "/projects/tpe-050-hallmarkchannel-universalsweept/settings" for 103.248.209.130 at 2018-07-10 07:52:04 +0000
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"tpe-050-hallmarkchannel-universalsweept"}
  Current user: pvvvvvvv@cccc.com (id=417)
  Rendered projects/settings.html.erb within layouts/base (171.7ms)
Completed 500 Internal Server Error in 191ms (ActiveRecord: 5.3ms)

ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x00007fafab9878a0>:0x00007fafaa765b68>
Did you mean?  project_issues_path):
    1: <h2><%=l(:label_settings)%></h2>
    2:
    3: <%= render_tabs project_settings_tabs %>
    4:
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  plugins/redmine_custom_workflows/lib/redmine_custom_workflows/projects_helper_patch.rb:13:in `project_settings_tabs_with_custom_workflows'
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__2743346403283165172_70196237469560'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'

Please let me know how we can address this issue.

**Comment by picman** [comment]
It duplicates #845. Have you read CHANGELOG.md?
