### ISSUE TITLE
Can't access to DMSF using a none standard role

### ISSUE THREAD

**Issue by x-techarts** [danmunn/redmine_dmsf#886]
I created a new Redmine role, and i assigned to this role only 2 DMSF permissions :

* Browse documents
* View documents

After that, is created a user, and i assigned this user to a Redmine project with this new customized role.
This project contains DMSF files, but when i sign in with this new user on this project, i can't see the DMSF files linked to this project.

These 2 role permissions seem to be not sufficient to browse DMSF files. 
What are the mandatories permissions to add to a customized role to be able to browse DMSF Files?

Thank you.

**Comment by picman** [comment]
**Browse documents** permission is enough to see DMS tab and files and folders on this tab. Check again your settings, especially project's members and modules.
