### ISSUE TITLE
The page you were trying to access doesn't exist or has been removed.

### ISSUE THREAD

**Issue by neocosmic2** [danmunn/redmine_dmsf#891]
I found our the link of file is different from previous version that after upgrading.

Past: based on project P_xxxx
Now: dmsf\2018\03\

here is the log:
Sent file C:\Bitnami\redmine-3.4.6-0\apps\redmine\htdocs\files\dmsf**/2018/03/**180307123929_311_Sample_TITO_Tickets_-_Version_8.05b.pdf (0.0ms)
Cannot read file C:\Bitnami\redmine-3.4.6-0\apps\redmine\htdocs\files\dmsf/2018/03/180307123929_311_Sample_TITO_Tickets_-_Version_8.05b.pdf
  Rendered common/error.html.erb within layouts/base (0.0ms)
  Rendered inline template (0.0ms)
  Rendered plugins/ttm/app/views/ttm/_stylesheets.html.erb (0.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.0ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_attendance_widget.html.erb (0.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (0.0ms)
Completed 404 Not Found in 281ms (Views: 144.1ms | ActiveRecord: 62.4ms)

**Comment by sposs** [comment]
I have the same issue. No file can be downloaded after migrating from 1.5.8 to 2.0.

**Comment by picman** [comment]
There were very probably errors during the migration which you ignored. Please see #799 and #767 for a solution.
