### ISSUE TITLE
Upload for some filenames is not working

### ISSUE THREAD

**Issue by flybyray** [danmunn/redmine_dmsf#894]
```
"Das\ höchste\ Gut\ und\ Uebel"\ Cicero.docx
Das_höchste_Gut_und_Uebel_Cicero.docx
```
The first file cannot be saved. But the content is exactly the same as in the second file.

**Comment by picman** [comment]
The back slash and double apostrophes are not allowed in file names.
```INVALID_CHARACTERS = '\[\]\/\\\?":<>#%\*'```

**Comment by flybyray** [comment]
sorry those are just escape sequences from the `ls -lb` output the filename has just allowed characters.
to make it more clear:
```bash
robert@robert-debian:~/Documents$ ls -lb *Cicer*
-rw-r--r-- 1 robert robert 28454 Aug  7 09:35 "Das\ höchste\ Gut\ und\ Uebel"\ Cicero.docx
-rw-r--r-- 1 robert robert 28454 Aug  7 09:35 Das_höchste_Gut_und_Uebel_Cicero.docx
robert@robert-debian:~/Documents$ ls -l *Cicer*
-rw-r--r-- 1 robert robert 28454 Aug  7 09:35 "Das höchste Gut und Uebel" Cicero.docx
-rw-r--r-- 1 robert robert 28454 Aug  7 09:35 Das_höchste_Gut_und_Uebel_Cicero.docx
```

**Comment by flybyray** [comment]
The `ls -lb` output is ideal to create exactly those files
`touch "Das\ höchste\ Gut\ und\ Uebel"\ Cicero.docx`

**Comment by picman** [comment]
Again, double apostrophes are not allowed in filenames.
