### ISSUE TITLE
Gem ox  installation failed

### ISSUE THREAD

**Issue by asrmarco13** [danmunn/redmine_dmsf#901]
Hello,
I have a Redmine Docker Container (https://hub.docker.com/_/redmine/) and I trying to install DMFS plugin.
When I try to launch command `bundle install --without development test` I receive an error and the installation failed. My stack trace:
> bundle install --without development test
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.3.1
Using i18n 0.7.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 4.2.8
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.3.0
Using nokogiri 1.8.4
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.9
Using crass 1.0.4
Using loofah 2.2.2
Using rails-html-sanitizer 1.0.4
Using actionview 4.2.8
Using rack 1.6.10
Using rack-test 0.6.3
Using actionpack 4.2.8
Using globalid 0.4.1
Using activejob 4.2.8
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using mail 2.6.6
Using actionmailer 4.2.8
Using actionpack-xml_parser 1.0.2
Using activemodel 4.2.8
Using arel 6.0.4
Using activerecord 4.2.8
Using acts-as-taggable-on 4.0.0
Using public_suffix 3.0.2
Using addressable 2.5.2
Using bundler 1.16.3
Using coderay 1.1.2
Using concurrent-ruby 1.0.5
Using css_parser 1.6.0
Using dalli 2.7.8
Using htmlentities 4.3.4
Using thor 0.20.0
Using railties 4.2.8
Using jquery-rails 3.1.5
Using mimemagic 0.3.2
Using mysql2 0.4.10
Using net-ldap 0.12.1
Fetching ox 2.9.4
Installing ox 2.9.4 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    current directory: /usr/local/bundle/gems/ox-2.9.4/ext/ox
/usr/local/bin/ruby -r ./siteconf20180813-5527-1hxd0il.rb extconf.rb
>>>>> Creating Makefile for ruby version 2.4.4 on x86_64-linux <<<<<
creating Makefile
extconf.rb:67:in ``': No such file or directory - make (Errno::ENOENT)
        from extconf.rb:67:in `<main>'
extconf failed, exit code 1
Gem files will remain installed in /usr/local/bundle/gems/ox-2.9.4 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.4.0/ox-2.9.4/gem_make.out
An error occurred while installing ox (2.9.4), and Bundler cannot continue.
Make sure that `gem install ox -v '2.9.4' --source 'https://rubygems.org/'` succeeds before bundling.
In Gemfile:
  ox

OX installation failed and I don't know how to solve this mistake. Can you help me?

My Redmine info:
![screenshot](https://user-images.githubusercontent.com/17269293/44026012-f79da004-9ef1-11e8-9562-1bd336af6507.png)

Thanks in advance

**Comment by flybyray** [comment]
i use dmsf plugin within docker. but as I understand you do not create an docker image from a Dockerfile as a first step. You run the install from inside of the running docker container from docekr image redmine. That will never work if you do not have the build dependencies. The official image removes them to keep the final image small.
https://github.com/docker-library/redmine/blob/69082edc899cdbc69a00c4dd30d01f83fb59048f/3.4/Dockerfile#L117

but to make thinks clear you should provide the out put from `/usr/local/bundle/extensions/x86_64-linux/2.4.0/ox-2.9.4/gem_make.out` .

**Comment by asrmarco13** [comment]
@flybyray thanks for the reply. I use this image for internal test and I didn't pay attention to the Dockerfile. I will create a new Dockerfile with all necessary dependencies.

Anyhow, here it is the output from `/usr/local/bundle/extensions/x86_64-linux/2.4.0/ox-2.9.4/gem_make.out` :
> current directory: /usr/local/bundle/gems/ox-2.9.4/ext/ox
/usr/local/bin/ruby -r ./siteconf20180813-5527-1hxd0il.rb extconf.rb
>>>>> Creating Makefile for ruby version 2.4.4 on x86_64-linux <<<<<
creating Makefile
extconf.rb:67:in ``': No such file or directory - make (Errno::ENOENT)
        from extconf.rb:67:in `<main>'
extconf failed, exit code 1

**Comment by flybyray** [comment]
As you can see it is even missing the make command.
https://github.com/ohler55/ox/blob/6a2442a35a4a77ed3136ebb569377683c8c34dcd/ext/ox/extconf.rb#L67

**Comment by lterekhov** [comment]
I have a similar problem. Tell me, what do I need to do?

**Comment by flybyray** [comment]
@lterekhov reading and studying the references and links. Do you understand what the referenced Dockerfile above is doing? Some hint https://github.com/docker-library/redmine/blob/69082edc899cdbc69a00c4dd30d01f83fb59048f/3.4/Dockerfile#L77 .

**Comment by lterekhov** [comment]
Oh thanks you! Now I realized what I had to do.
Added the following packages to the Dockerfile and everything assemble:
```
RUN apt-get update && apt-get install -y \
make \
gcc
```
