### ISSUE TITLE
Little bug in PDF image export (Redmine 3.4.6)

### ISSUE THREAD

**Issue by bor8** [danmunn/redmine_dmsf#903]
When using `{{dmsf_image(<ID>)}}` with PDF export, no picture is shown in PDF. Instead it is replaced by the text "view". Can someone tell me if I'm right here or if this is more of a Redmine bug?

**Comment by picman** [comment]
I think that it's a missing functionality on DMSF side. I've had a look at it and haven't seen any easy solution.

**Comment by bor8** [comment]
Thank you for examining the problem. I'm not getting around to supporting it right now. My employer may be able to hire a company to fix the problem. Can you provide some more information, so it might be faster?

**Comment by picman** [comment]
Look at _Redmine:Export:PDF:ITCPDF::get_image_filename(attrname)_. The method expect a picture filename as the parameter, e.g. _picture.png_ but it gets _/dmsf/files/nnnn/view/_ from DMSF macro.
My first attempt was to add the file name to the URL so the parameter was _/dmsf/files/nnnn/view/picture.png_ then. But still it expect just _picture.png_.

**Comment by M0d3rn15t** [comment]
This may be redmine as there is a pdf rendering issue with the draw.io plug in.

https://github.com/mikitex70/redmine_drawio/issues/55

**Comment by picman** [comment]
Fixed.
