### ISSUE TITLE
Custom Fields of type 'url' are displayed "as plain text" in document listing.

### ISSUE THREAD

**Issue by alvarocombo** [danmunn/redmine_dmsf#905]
HI,
I'm using DMSF V1.6.1 and I have defined the following two Custom fields:

1. List Type, with an 'URL' to values: This is used to link a document to a redmine project.
2. Link Type: Used (as expected) to create a link to an 'url'.

These two Fields were added as columns in 'Document Management'
Both features work  fine except the two following nagging aspects:

- Both links appear on Document List as plane text (they don't have the link to be followed). It is necessary to go to 'edit' document to see the proper linking (on both Custom fields). 
-  In the 'Link Type' Custom field, an URL is presented (as expected), but a since it can be quite long, the possibility of using an alias would greatly improve usability and readability. 

Thank you very much for your attention. 
Great Work on this plugin.

**Comment by picman** [comment]
Link type fixed. Concerning the List type it won't be implemented. Nor Redmine supports it.
