### ISSUE TITLE
Wrapping problem in Issue view

### ISSUE THREAD

**Issue by vchryssos** [danmunn/redmine_dmsf#908]
In the Issue view there is the DMS sector, where you can view your related documents. On the right hand side you have 6 icons for the respective actions (edit, delete, etc).
When the title of the document is too long, the wrapping of these icons is not correct, resulting to a confusing view (see attached).
Maybe a solution would be to hide the excessive document title (or the document description) and ad three dots (...) as an indicator. When the user clicks on the dots the hidden phrase is revealed.
  Redmine version            3.4.6.stable
  Ruby version                   2.4.4-p296 (2018-03-28) [x86_64-linux]
  Rails version                   4.2.8
![screen](https://user-images.githubusercontent.com/3367469/45146219-1db9e680-b1cb-11e8-8a00-0d495232b6cd.png)

**Comment by picman** [comment]
It seems to be fine now (Redmine 4.1, DMSF 2.4.2, Firefox 71.0)

![image](https://user-images.githubusercontent.com/779003/71714334-b9825380-2e0d-11ea-8e9b-474a92a211f7.png)
