### ISSUE TITLE
Redirect the plugin home to the revisions page of the first document of the project

### ISSUE THREAD

**Issue by dnyamy** [danmunn/redmine_dmsf#909]
Hello all,
I have recently forked redmine_dmsf plugin and I am trying to customize it so that it perfectly fits our usecases, while being more user friendly.

I would really appreciate if someone can give me a nudge for the change explained below : 

Currently, when user clicks on DMSF tab, it shows the documents page of the project. I guess this is what I see in after_init.rb
Redmine::MenuManager.map :project_menu do |menu|
    menu.push :dmsf, { :controller => 'dmsf', :action => 'show' }, :caption => :menu_dmsf, :before => :documents, :param => :id
end

I would like to show directly the revisions page of the first document (if any) of the project, for my projects almost always have only one document. And I want to keep the possibility to go from there up up to the documents page.

Thank in advance,
And regards
Dorice

**Comment by picman** [comment]
i'd leave the menu item as it is but modify DmsfController::show method instead. In the show method you should find a document to display, e.g. _file = DmsfFiles.where(:project_id => xxx).first_ and than call method _show()_ from _DmsfFiles_ controller.
``` ruby
render :controller => 'DmsfFilesController', :action => :show, :params
=> { :id => file.id }
```

**Comment by dnyamy** [comment]
Thanks a lot for interest,
I have tried this, but not working.
I am able to get first file for I can render it.
These are my instructions 
```
file = DmsfFile.where(:project_id => @project.id).first
    render :controller => 'DmsfFilesController', :action => :show, :params => { :id => file.id }
```
But I am still landing on the documents page of the project, with no trace in the logs

**Comment by picman** [comment]
If you add _return_ on the next line after _render_?

**Comment by dnyamy** [comment]
I have finally managed with a redirection, instead of just rendering the file controller.
`redirect_to :controller => 'dmsf_files', :action => :show,  :id => file.id
`
But I have created a new action in the dmsf_controller, as I needed to show the initial home page again (I won't be able to add a document otherwise) from other links.

Thanks a lot for help
