### ISSUE TITLE
Automatically assign project validation flows on file upload

### ISSUE THREAD

**Issue by dnyamy** [danmunn/redmine_dmsf#911]
Hello all,

Currently, users need to explicitly assign validation flows each time they add new revisions. I would like to automatically assigne project validation flows each time a new revision is added to a document. Is it possible to consider such a functionallity ?

Or at least could someone give me a nudge to add it myself. I have cloned th e project and started customizations my association need.

Thank in advance,
And regards
Dorice.

**Comment by picman** [comment]
Look at _DmsfUploadHelper::commit_files_internal_, line 118 _# Approvalworkflow_. If you set _commited_file[:workflow_id]_, the approval workflow will be assigned.

**Comment by dnyamy** [comment]
I must be missing something, as I am new to Rails.
I wanted to log some info in order to get what to assign.
But I am suprised, logging seems not to be working within helpers ?
As you said, 118 # Approvalworkflow, event a simple string won't appear in the logs

`        # Approval workflow
        Rails.logger.info '========================================================================='
        if commited_file[:workflow_id].present?
`

Please what am I missing ?
Thanks

**Comment by picman** [comment]
```ruby
Rails.logger.info 'xxx'
```
must be working.

**Comment by dnyamy** [comment]
As I would have expected.
Even a log from the begining of the helper function won't show.
May be there is a log silencer mechanism I am not aware of within helpers.
I have not problem logging from controllers

**Comment by dnyamy** [comment]
I have finally debugged from erb file. 
And now I am pretty sure I am not updating at the right place.
I have created a workflow whose id is 7
and a simple instruction as 
`commited_file[:workflow_id] = 7`
Won't do anything
May be am mislidden, but please, any idea ?
Thanks

**Comment by picman** [comment]
Post a chunk of your code to see whether you put it onto the right place.

**Comment by dnyamy** [comment]
I am in 
app/helpers/dmsf_upload_helper.rb
Line 118
`       # Approval workflow
        commited_file[:workflow_id] = 7
        if commited_file[:workflow_id].present?
          wf = DmsfWorkflow.find_by_id commited_file[:workflow_id]
          if wf
            # Assign the workflow
            new_revision.set_workflow(wf.id, 'assign')
            new_revision.assign_workflow(wf.id)
            # Start the workflow
            new_revision.set_workflow(wf.id, 'start')
            if new_revision.save
              wf.notify_users(project, new_revision, controller)
              begin
                file.lock!
              rescue DmsfLockError => e
                Rails.logger.warn e.message
              end
            else
              Rails.logger.error l(:error_workflow_assign)
            end
          end  `
Thanks

**Comment by picman** [comment]
Hm, it's strange. I tried exactly the same and it worked:

```ruby
# Approval workflow
commited_file[:workflow_id] = 240
if commited_file[:workflow_id].present?
  wf = DmsfWorkflow.find_by_id commited_file[:workflow_id]
  ...
```

**Comment by dnyamy** [comment]
My helper code is not refreshed, I think
```
# Approval workflow
commited_file[:workflow_id] = djh jhdj jsdj jsdfsndbfnbsdf ssdbfhsbvdbfhvsdf bs sdf
  ...
```
causes no error.
I restart the application by touching the tmp/restart.txt file. It worked for all the updates I did till now.

**Comment by picman** [comment]
Yes, if you modify the code, you must restart the application, e.g. `service apache2 restart`.
