### ISSUE TITLE
NoMethodError (undefined method `[]' for nil:NilClass):

### ISSUE THREAD

**Issue by Max11mus** [danmunn/redmine_dmsf#912]
Redmine server information:
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  easy_instant_messages          2016
  redmine_ckeditor               1.1.5
  redmine_dmsf                   1.6.1
  redmine_drawio                 0.8.2
  redmine_lightbox2              0.4.3
  redmine_preview_office         1.0.3

Log :
Completed 200 OK in 441ms (Views: 364.9ms | ActiveRecord: 32.6ms)
Started GET "/easy_instant_messages.json?key=5c9b0c62274d69c7e8842beb80bce74187f4bbb1" for 77.122.225.85 at 2018-09-16 03:31:57 +0300
Processing by EasyInstantMessagesController#index as JSON
  Parameters: {"key"=>"5c9b0c62274d69c7e8842beb80bce74187f4bbb1"}
  Current user: admin (id=1)
  Rendered plugins/easy_instant_messages/app/views/easy_instant_messages/index.api.rsb (1.7ms)
Completed 200 OK in 19ms (Views: 2.2ms | ActiveRecord: 4.8ms)
Started GET "/projects/project_000011/dmsf.csv?folder_id=19" for 77.122.225.85 at 2018-09-16 03:31:58 +0300
Processing by DmsfController#show as CSV
  Parameters: {"folder_id"=>"19", "id"=>"project_000011"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 50ms (ActiveRecord: 8.1ms)

NoMethodError (undefined method `[]' for nil:NilClass):
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:72:in `block (2 levels) in show'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:63:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'

**Comment by Max11mus** [comment]
> It seems to be related to the chat plugin - https://www.easyredmine.com/redmine-chat. Could you describe a little in which situation the error occurs?
> 
> From DMSF plugin point of view CSV format of data is requested but params[:settings][:dmsf_columns] is missing in the parameters of the request. It's expected to be present an information which columns should be present in the requested CSV.
> Maybe I can modify the functionality in order to suppose all columns if not specified.

When i click on DMS tab in any project.

![image](https://user-images.githubusercontent.com/43306019/45610971-8411f500-ba66-11e8-9071-226abeb46513.png)

**Comment by picman** [comment]
That's strange. I see in your log file: `Started GET "/projects/project_000011/dmsf.csv?folder_id=19`
If you clik on DMS tab, the URL should looks like: `/projects/project_000011/dmsf`
Who calls `GET "/projects/project_000011/dmsf.csv?folder_id=19`?

**Comment by Max11mus** [comment]
> That's strange. I see in your log file: `Started GET "/projects/project_000011/dmsf.csv?folder_id=19`
> If you clik on DMS tab, the URL should looks like: `/projects/project_000011/dmsf`
> Who calls `GET "/projects/project_000011/dmsf.csv?folder_id=19`?

Started GET "/projects/project_000013/dmsf" for 146.185.157.51 at 2018-09-17 19:03:53 +0300
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"project_000013"}
  Current user: admin (id=1)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (37.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (446.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (30.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (419.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (50.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (88.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (1260.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (65.7ms)
/var/www/redmine/public/plugin_assets/redmine_dmsf/javascripts/plupload/js/i18n/uk.js not found
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (85.1ms)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (24.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (1969.6ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.9ms)
  Rendered plugins/redmine_drawio/app/views/redmine_drawio/_macro_dialog.html.erb (6.9ms)
  Rendered plugins/easy_instant_messages/app/views/easy_instant_messages/_audio_tag.html.erb (0.4ms)
  Rendered plugins/easy_instant_messages/app/views/easy_instant_messages/_render_easy_instant_messages_box.html.erb (13.2ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (110.1ms)
Completed 200 OK in 2765ms (Views: 2010.8ms | ActiveRecord: 283.5ms)
Started GET "/easy_instant_messages.json?key=5c9b0c62274d69c7e8842beb80bce74187f4bbb1" for 146.185.157.51 at 2018-09-17 19:03:57 +0300
Processing by EasyInstantMessagesController#index as JSON
  Parameters: {"key"=>"5c9b0c62274d69c7e8842beb80bce74187f4bbb1"}
  Current user: admin (id=1)
  Rendered plugins/easy_instant_messages/app/views/easy_instant_messages/index.api.rsb (1.9ms)
Completed 200 OK in 33ms (Views: 2.7ms | ActiveRecord: 4.0ms)
Started GET "/projects/project_000013/dmsf.csv" for 146.185.157.51 at 2018-09-17 19:03:57 +0300
Processing by DmsfController#show as CSV
  Parameters: {"id"=>"project_000013"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 189ms (ActiveRecord: 11.0ms)

NoMethodError (undefined method `[]' for nil:NilClass):
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:72:in `block (2 levels) in show'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:63:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'

**Comment by picman** [comment]
You must find who is responsible for **Started GET "/projects/project_000013/dmsf.csv"**. I'd start with disabling all other plugins. Try it just with Redmine + DMSF only.

**Comment by Max11mus** [comment]
> You must find who is responsible for **Started GET "/projects/project_000013/dmsf.csv"**. I'd start with disabling all other plugins. Try it just with Redmine + DMSF only.

Uninstall all plugins:

Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.6.1

Log:
Started GET "/projects/project_000013/dmsf" for 192.168.1.101 at 2018-09-18 20:53:16 +0300
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"project_000013"}
  Current user: admin (id=1)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (30.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (10.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (11.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (10.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (75.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (2.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (4.5ms)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (1.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (99.6ms)
Completed 200 OK in 189ms (Views: 130.8ms | ActiveRecord: 35.1ms)
Started GET "/projects/project_000013/dmsf.csv" for 192.168.1.101 at 2018-09-18 20:53:17 +0300
Processing by DmsfController#show as CSV
  Parameters: {"id"=>"project_000013"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 47ms (ActiveRecord: 6.9ms)

NoMethodError (undefined method `[]' for nil:NilClass):
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:72:in `block (2 levels) in show'
  plugins/redmine_dmsf/app/controllers/dmsf_controller.rb:63:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'

Nothing changes.

**Comment by picman** [comment]
The correct behaviour is in Firefox. The log when using Chrome indicates that a browser extension tries download links present on the page. Because there is just a link "Available as CSV". Moreover, three is Javascript call only. The problem is definitely related to your browser not the application.
