### ISSUE TITLE
ActionController::RoutingError (No route matches [PROPFIND] "/"):

### ISSUE THREAD

**Issue by Max11mus** [danmunn/redmine_dmsf#913]
I mount WebDAV folder in windows then PROPFIND requests are sent for the paths "/"  which results in a FATAL log entry "ActionController::RoutingError (No route matches [PROPFIND] "/"):"

Server Information:
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  easy_instant_messages          2016
  redmine_ckeditor               1.1.5
  redmine_dmsf                   1.6.1
  redmine_drawio                 0.8.2
  redmine_lightbox2              0.4.3
  redmine_preview_office         1.0.3

Log:

Started PROPFIND "/" for 77.122.225.85 at 2018-09-16 11:51:03 +0300

ActionController::RoutingError (No route matches [PROPFIND] "/"):
  actionpack (4.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.10) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.10) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.8) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.10) lib/rack/content_length.rb:15:in `call'
  rack (1.6.10) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.8) lib/rails/engine.rb:518:in `call'
  railties (4.2.8) lib/rails/application.rb:165:in `call'
  railties (4.2.8) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.8) lib/rails/railtie.rb:194:in `method_missing'
  passenger (5.3.3) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  passenger (5.3.3) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
  passenger (5.3.3) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  passenger (5.3.3) src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
  passenger (5.3.3) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by picman** [comment]
Maybe ask Microsoft why they do such fool things...

**Comment by picman** [comment]
I've made a workaround but it would be nice if somebody tests it in different environment with different clients.
