### ISSUE TITLE
dav4rack xml namespace changed in case

### ISSUE THREAD

**Issue by flybyray** [danmunn/redmine_dmsf#915]
https://github.com/danmunn/redmine_dmsf/blob/b9e5222c2f1c51b395e5d74a1106e5b8e669d95f/lib/dav4rack/xml_elements.rb#L6-L8

Would be great if the original behaviour would even the case sensitivity would be the same:
https://github.com/chrisroberts/dav4rack/blob/master/lib/dav4rack/controller.rb#L465
I think the first implementation was based on one of the first examples: https://tools.ietf.org/html/rfc2518#section-8.1.1

dmsf is generating valid xml, that is all fine, but in practice there are implementors which do not follow exact rfc documentation and fail badly. For those implementors it is the best if reimplementations follow the prior path of implementation if it was not wrong.

I just found some customer clients which integrated against an webdav based on a redmine dmsf with dav4rack. their implementation is now broken because of an updated system. ;-)

**Comment by picman** [comment]
Please explain it in other words, a simpler way. I don't see your point. BTW dav4rack library is just copied from here: https://github.com/planio-gmbh/dav4rack. I can certainly override some functionality in DMSF and I do that. But better to change dav4rack library, if it make sense.
Ideally come with a patch solving your problem.

**Comment by picman** [comment]
No feedback => closing
