### ISSUE TITLE
Is there an easy way to share a parent's documents (folder structure included) with subprojects?

### ISSUE THREAD

**Issue by M0d3rn15t** [danmunn/redmine_dmsf#916]
We often create subprojects which reference and update the documents of the parent project (or projects).

Is there a way to inherit the DMS folder structure from a parent (all ancestors)? This would reduce duplication and make document management easier.

**Comment by picman** [comment]
No such feature, so far.

**Comment by picman** [comment]
Will be implemented in scope of #1207. You can test it in devel-2.4.6 branch.

**Comment by CubaLibre84** [comment]
Please correct me if I'm wrong, but the integration of top project folders in a sub-project's DMS view is not implemented in v2.4.6.  In the new main DMS view (great work b.t.w.) I do see all projects and their sub-projects as [...] and all the DMS folders by using the small ">" symbol left beside the folder.

But if I now click on a sub-project I do NOT SEE the folders of the parent project. Is this intended?
