### ISSUE TITLE
possibility to block specific files to other users of a project

### ISSUE THREAD

**Issue by p-leroy** [danmunn/redmine_dmsf#917]
Hi All,
Thank you for the good job on the DMSF plugin, hope it will become the default documents manager of Redmine in the future!
I would like to know whether we could have a specific permission added to the 12 existing ones for the DMSF plugin.
Description of the permission: the right to view / modify only the files to have created. You can browse all other files but not see/modify them.
Use case: one project manager wants to launch a call for projects. Each participant has the right to put a proposition in the directory, modify it, create new revisions, etc. But he has not the right to read / edit others propositions, only reviewers can do that.
This could be a permission similar to "View documents" but only for the users own documents. It could also be a parameter of the file itself, allowing it to be accessible either to all the users either to its creator.
What do you think about that?
Best regards.

**Comment by picman** [comment]
I think, that you can achieve required functionality using permissions for folders. If you edit a folder you can define who or which role has access to the directory.

**Comment by p-leroy** [comment]
Thank you for the reply!
