### ISSUE TITLE
Some local json file doesn't load

### ISSUE THREAD

**Issue by liaham** [danmunn/redmine_dmsf#918]
Hi,
I observed that some of the json files such that de.json, and no.json are not loading in webrick when the default languages of Redmine changes accordingly. There might be more. Moreover, it seems to depend on the application server. Using Apache there are much more files which are not loading.  With de.js it is the same problem with Apache.

There is no other plugin installed.

I have no idea how to fix this. Is there anybody having a solution?

Regards,
liaham
----
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.4.4-p296 (2018-03-28) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    development
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.6.1

**Comment by picman** [comment]
I've just tested German language in Webrick and Apache too and haven't noticed any problems. Have you looked into the log file? Are there any warnings related to .json/.js files, eg. `de.json not found`?

**Comment by liaham** [comment]
Thanks for your fast reply. 

Here is a short summary of what I have tried:

1. Checked Redmine development.log: Both de.js and de.json could not be found.
1. Checked to open the files by myself: Successful.
1. Checked file permissions: 755 -> should be sufficient.
1. Checked apache2 error.log: phusion_passenger.rb could not be loaded. -> Fixed it.
1. Restarted apache and passenger.
1. Observed that the problem is still alive.

Again I have no idea how to solve the problem. 

How about you, picman? 

Regards,
liaham

P.S. I have found some other bugs and their solutions. Two of them refer to database rollbacks and another one causes a Redmine core test to fail. However, right now I have no time to set up a workflow for pull requests (I use SVN). The fixings are very small. Is it possible to use just an issue to explain the problems and the solutions to you for integrating them by yourself? 

__________________________________________
1. Here is an excerpt of the log file:

```
Rendered` plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (2.9ms)
  [1m[35mCustomField Load (0.2ms)[0m  SELECT `custom_fields`.* FROM `custom_fields` WHERE `custom_fields`.`type` = 'DmsfFileRevisionCustomField'
  [1m[36mCACHE (0.0ms)[0m  [1mSELECT `custom_fields`.* FROM `custom_fields` WHERE `custom_fields`.`type` = 'DmsfFileRevisionCustomField'[0m  [["type", "DmsfFileRevisionCustomField"]]
  [1m[35mCACHE (0.0ms)[0m  SELECT `custom_fields`.* FROM `custom_fields` WHERE `custom_fields`.`type` = 'DmsfFileRevisionCustomField'  [["type", "DmsfFileRevisionCustomField"]]
  [1m[36mCACHE (0.0ms)[0m  [1mSELECT `custom_fields`.* FROM `custom_fields` WHERE `custom_fields`.`type` = 'DmsfFileRevisionCustomField'[0m  [["type", "DmsfFileRevisionCustomField"]]
  [1m[35mCACHE (0.0ms)[0m  SELECT `custom_fields`.* FROM `custom_fields` WHERE `custom_fields`.`type` = 'DmsfFileRevisionCustomField'  [["type", "DmsfFileRevisionCustomField"]]
  [1m[36mCACHE (0.0ms)[0m  [1mSELECT `custom_fields`.* FROM `custom_fields` WHERE `custom_fields`.`type` = 'DmsfFileRevisionCustomField'[0m  [["type", "DmsfFileRevisionCustomField"]]
  [1m[35mCACHE (0.0ms)[0m  SELECT `custom_fields`.* FROM `custom_fields` WHERE `custom_fields`.`type` = 'DmsfFileRevisionCustomField'  [["type", "DmsfFileRevisionCustomField"]]
/var/www/htdocs/web1/files/rm346/releases/20180918130859/public/rm346/plugin_assets/redmine_dmsf/javascripts/jquery.dataTables/locales/de.json not found
  [1m[36m (0.4ms)[0m  [1mSELECT COUNT(*) FROM `dmsf_links` WHERE `dmsf_links`.`dmsf_folder_id` = 10 AND `dmsf_links`.`target_type` = 'DmsfFolder' AND `dmsf_links`.`deleted` = 0[0m
  [1m[35m (0.1ms)[0m  SELECT COUNT(*) FROM `dmsf_files` WHERE `dmsf_files`.`dmsf_folder_id` = 10 AND `dmsf_files`.`deleted` = 0
  [1m[36m (0.1ms)[0m  [1mSELECT COUNT(*) FROM `dmsf_links` WHERE `dmsf_links`.`dmsf_folder_id` = 10 AND `dmsf_links`.`target_type` = 'DmsfFile' AND `dmsf_links`.`deleted` = 0[0m
  [1m[35m (0.1ms)[0m  SELECT COUNT(*) FROM `dmsf_links` WHERE `dmsf_links`.`dmsf_folder_id` = 10 AND `dmsf_links`.`target_type` = 'DmsfUrl' AND `dmsf_links`.`deleted` = 0
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.3ms)
/var/www/htdocs/web1/files/rm346/releases/20180918130859/public/rm346/plugin_assets/redmine_dmsf/javascripts/plupload/js/i18n/de.js not found
```
2. In addition, I checked whether I am able to open the files by myself. It is no problem. 

3. Permissions are set to 775.

4.  In the Apache2 error.log I found:

```
App 9550 stdout: 
[ 2018-10-09 11:02:29.2228 4274/7ff6affff700 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 9550, application /var/www/htdocs/web1/files/rm346/current (development)
App 9870 stdout: 
App 9870 stderr: /usr/bin/passenger-config:27:in `require': cannot load such file -- phusion_passenger (LoadError)
App 9870 stderr: 	from /usr/bin/passenger-config:27:in `<main>'
App 9908 stdout: 
```
Line 27 in passenger-config is: `require 'phusion_passenger'`.  I changed the path to '/usr/lib/ruby/vendor_ruby/phusion_passenger'. The loading problem is solved.

5. Restarted the web and application server (apache, passenger).

6. However, the language files are still not loading.

**Comment by liaham** [comment]
**Addition:**
When I patch the underlying ruby functions json_url and js_url in dmsf_helper.rb by setting german as fallback language then it works for de.js but not for de.json.

Maybe this helps by getting an idea...

**Comment by picman** [comment]
It might be related to #1010. Please check it.
