### ISSUE TITLE
Search for Document #

### ISSUE THREAD

**Issue by mmundi72** [danmunn/redmine_dmsf#919]
I tried to search for a specific document based on the "Document #" I have (as I can search for tickets just using the ticket/issue number). This doesn't seem to work. 

It would be great if we could also search for a document for which we just know the corresponding number (#) - overall projects. The filtering function within specific project on the DMSF page does also not help, as this only finds documents within the current folder.

**Comment by picman** [comment]
Such a functionality is there but you must install [redmine_xapian](https://github.com/xelkano/redmine_xapian) plugin. Then D123 works, similar to #123 for issues.

**Comment by mmundi72** [comment]
Xapian is installed:
![grafik](https://user-images.githubusercontent.com/7224922/46849399-9bd36380-cdef-11e8-9bae-c40fc090bb03.png)

I tried to search for this document:
![grafik](https://user-images.githubusercontent.com/7224922/46849465-e2c15900-cdef-11e8-93de-85d6ebc1a2a8.png)

Searching for title: works
Searching for content within document: works  (full text seems to work)
Search for document #:  doesn't work (I tried 8145, D8145, #8145) -> no result

**Comment by mmundi72** [comment]
I am using redmine 3.4.6 and DMSF 1.6.1

**Comment by picman** [comment]
Hm, that's strange. If you enter D8145 into either the search filed in the top right corner (next to the project pick list) or the search field on the search page you should be redirected to the document's details form.
You should investigate why _SearchControllerPatch_ from Xapian plugin is not called.

**Comment by mmundi72** [comment]
It's finally working. Xapian was not properly activated....
