### ISSUE TITLE
Office 2016

### ISSUE THREAD

**Issue by ToniIltanen** [danmunn/redmine_dmsf#922]
When saving a file through webdav (mounted drive, open -> modifiy -> save), the next happens:

*Word 2016*:
A loop of temporary folders start to appear and word itself remains on pending state. after the loop (approx 5min), the folders remain and the original file is removed.

*Excel 2016*
File is saved, but not versioned. A temporary folder appears (which is removed after save), but no new versions are visible on the saved file (each save is the first revision of the file)

**Comment by picman** [comment]
1. Can check what is in the production.log during saving and post it here?
2. Can you test a direct editing in MS Office from the main view of DMS(right click on the document's row and edit from the context menu)?

**Comment by ToniIltanen** [comment]
When opening an office file, an error is returned. 

```
Cannot open file.
Log in with an accout, which has permissions to open the file.
```
Our redmine uses our own openid connect provider for auth (but i suppose this has nothing to do with this, because no webdav login prompt was shown on which account to even use when opening an office file.

**Comment by picman** [comment]
Base authentication is required.
