### ISSUE TITLE
DMS plugin only visible for administrators

### ISSUE THREAD

**Issue by stefanomattia** [danmunn/redmine_dmsf#923]
I'm quite new to the whole Redmine/DMS ecosystem, so please bear with me if the question is trivial.
So far everything has been quite smooth except for the DMS plugin not being "visible" for users other than administrators.
If users are not an administrator, no matter what's their roles are, the DMS plugin won't show up in the modules bar, even if the module itself is enabled by the user in the project configuration.
Links to documents in the DMS in the wiki pages for such users are replaced with "Error executing the dmsf macro (You are not authorized to access this page.)" messages.

There seems to be some sort of permission problem, but I can't find any setting anywhere to enable use of DMS for "normal" users.

Am I doing anything wrong?

I'm using the following versions:

`Environment:
  Redmine version                3.4.6.stable.17593
  Ruby version                   2.4.4-p296 (2018-03-28) [x86_64-linux]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.6.1`

**Comment by picman** [comment]
Check Administration/Roles and Permissions. I suppose you haven't checked anything there...

![image](https://user-images.githubusercontent.com/779003/47556121-dcfa6600-d90d-11e8-935d-0ede07e3ccbd.png)

**Comment by stefanomattia** [comment]
Thanks! That solved my problem! I didn't even know you could click on the roles and access that huge amount of permissions! 
Really appreciated your help.
I'll close this issue.
