### ISSUE TITLE
Problems in revision history

### ISSUE THREAD

**Issue by lpereira98** [danmunn/redmine_dmsf#929]
I've just updated to DMSF 1.6.1.
What i need is to make a baseline of the dmsf files in a given date.
But a file can have many revisions and i want to have access to the file until a given date.
And the problem is that i can only get the last revision.
When i do:
GET "/redmine/dmsf/files/9325.json
i get something like this:
![aa](https://user-images.githubusercontent.com/44083899/49443732-16ec4100-f7c5-11e8-9e04-a3d5736f9899.PNG)
What i want is to have the full revision history, for example:
![bb](https://user-images.githubusercontent.com/44083899/49443759-28354d80-f7c5-11e8-8ed3-60f1fe2e2095.PNG)
Where i have a file with multiple revisions.

**Comment by lpereira98** [comment]
Hello again, i think i've solved this enhancement myself.
I noticed that in html i can see what i want (full revision history)
![capturar](https://user-images.githubusercontent.com/44083899/49860650-22a5bc00-fdf2-11e8-9f59-faded9096edb.PNG)

But throught the API we could only see the last revision

![capturar2](https://user-images.githubusercontent.com/44083899/49861058-ef176180-fdf2-11e8-9bfc-2ed6f6146436.PNG)

So, **i took a loot at the code** in the files "show.api.rsb" and "show.html.erb", and noticed that in the html one, we have a different file parameter that sends me to what i want:

`@file.dmsf_file_revisions.visible[@revision_pages.offset, @revision_pages.per_page].each`
So i've just tried to change "show.api.rsb" and it worked out:

![capturar3](https://user-images.githubusercontent.com/44083899/49861315-795fc580-fdf3-11e8-9316-0d2d22b08e1c.PNG)

Now i can see full file revision history:
![capturar4](https://user-images.githubusercontent.com/44083899/49861538-f9862b00-fdf3-11e8-9354-52e0e82eb304.PNG)

Now i just dont need the last_revision parameter.
I dont know if it is the best way to do this, but if works, works :)
Best regards

**Comment by picman** [comment]
I've thought that your change might be a part of a next release. Couldn't you create a pull request?

**Comment by picman** [comment]
Implemented in #948

**Comment by picman** [comment]
If I run tests I see:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<dmsf_file>
	<id>1</id>
	<title>Test File</title>
	<name>test.txt</name>
	<project_id>1</project_id>
	<content_url>http://www.example.com/dmsf/files/1/download</content_url>
	<revisions>#&lt;Enumerator:0x000055a531fc7cf0&gt;</revisions>
</dmsf_file>
```

**Comment by picman** [comment]
The output is slightly different now:

```xml
  <?xml version="1.0" encoding="UTF-8"?>
     <dmsf_file>
       <id>1</id>
       <title>Test File</title>
       <name>test.txt</name>
       <project_id>1</project_id>
       <content_url>http://www.example.com/dmsf/files/1/download</content_url>
      <dmsf_file_revisions type="array">
         <dmsf_file_revision>
           <id>5</id>
           <source_dmsf_file_revision_id/>
           <name>test5.txt</name>
           <content_url>http://www.example.com/dmsf/files/1/view?download=5</content_url>
           <size>4</size>
           <mime_type>text/plain</mime_type>
           <title>Test File</title>
           <description/>
           <workflow>1</workflow>
           <version>1.0</version>
           <comment/>
           <user_id>1</user_id>
           <created_at>2017-04-18T12:52:28Z</created_at>
           <updated_at>2019-01-15T15:56:15Z</updated_at>
           <dmsf_workflow_id/>
           <dmsf_workflow_assigned_by/>
           <dmsf_workflow_assigned_at/>
           <dmsf_workflow_started_by/>
           <dmsf_workflow_started_at/>
           <digest></digest>
         </dmsf_file_revision>
         <dmsf_file_revision>
           <id>1</id>
           <source_dmsf_file_revision_id/>
           <name>test.txt</name>
           <content_url>http://www.example.com/dmsf/files/1/view?download=1</content_url>
           <size>4</size>
           <mime_type>text/plain</mime_type>
           <title>Test File</title>
           <description>Some file :-)</description>
           <workflow>1</workflow>
           <version>1.0</version>
           <comment/>
           <user_id>1</user_id>
           <created_at>2017-04-18T12:52:27Z</created_at>
           <updated_at>2019-01-15T15:56:15Z</updated_at>
           <dmsf_workflow_id/>
           <dmsf_workflow_assigned_by>1</dmsf_workflow_assigned_by>
           <dmsf_workflow_assigned_at/>
           <dmsf_workflow_started_by>1</dmsf_workflow_started_by>
           <dmsf_workflow_started_at/>
           <digest>81dc9bdb52d04dc20036dbd8313ed055</digest>
         </dmsf_file_revision>
       </dmsf_file_revisions>
     </dmsf_file>
```

**Comment by lpereira98** [comment]
I tested it and you are right, in xml format we get:
`<revisions>#&lt;Enumerator:0x000055a531fc7cf0&gt;</revisions>`
But in json format we get the information, it's strange. I have not noticed before cause I always use in json format.
