### ISSUE TITLE
změny v xapian_indexer

### ISSUE THREAD

**Issue by PavelBaco** [danmunn/redmine_dmsf#933]
Ahoj,

upgradoval jsem na verzi 1.6.2 a došlo ke změnám ve zmíněném souboru. Jednak zmizel parametr f, který je zmíněn v dokumentaci, ale řekl bych že se soubory (strojově čitelná pdf) nezaindexují(respektive jejich obsah). Ve verzi 1.6.1 jsem měl zaindexované všechny soubory a stačilo zadat slovo a soubory to vyhledalo, nyní to nefunguje tak jako předtím. Podle některých slov to vyhledá a podle některých ne, i když ve verzi 1.6.1 to vyhledávalo.

**Comment by picman** [comment]
Sorry for English, but the most of readers probably don't understand Czech. And now to your points:

1) Yes, _-f_ parameter has been removed. I've forgotten to update README.md. I will do that.
2) Post here a sample PDF file with words which are not found. I will try it.
