### ISSUE TITLE
problem to get reversion error

### ISSUE THREAD

**Issue by netmeeting** [danmunn/redmine_dmsf#934]
Hi,gentlement：
I've just updated to DMSF 1.6.2
when i get the history version of file by  {{dmsf(1503,file,0.2)}}
Error shows "Error executing the dmsf macro (Couldn't find DmsfFileRevision with 'id'=0.2)"
but  by {{dmsfversion(1503)}},can get the right version.
others, when I run ：bundle exec rake redmine:dmsf_create_digests RAILS_ENV="production"
the log shows as follow:
(in /opt/redmine-3.4.0-1/apps/redmine/htdocs)
rake aborted!
NoMethodError: undefined method `dmsf_file_revisions' for nil:NilClass
/opt/redmine-3.4.0-1/apps/redmine/htdocs/plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:180:in `disk_file'
/opt/redmine-3.4.0-1/apps/redmine/htdocs/plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:328:in `create_digest'
/opt/redmine-3.4.0-1/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_create_digests.rake:54:in `block in create_digests'
/opt/redmine-3.4.0-1/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_create_digests.rake:53:in `create_digests'
/opt/redmine-3.4.0-1/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_create_digests.rake:38:in `block (2 levels) in <top (required)>'
/opt/redmine-3.4.0-1/ruby/bin/bundle:23:in `load'
/opt/redmine-3.4.0-1/ruby/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:dmsf_create_digests
(See full trace by running task with --trace)
what shall I do?

**Comment by picman** [comment]
` {{dmsf(1503,file,0.2)}}`
The revision's ID is expected here, not the version.

![revision](https://user-images.githubusercontent.com/779003/50275221-2911e480-043f-11e9-9af2-f684bb83a0ef.png)
