### ISSUE TITLE
Then go to configuration an internal error #500  appear

### ISSUE THREAD

**Issue by dskibarko** [danmunn/redmine_dmsf#936]
Issue after upgrade DMSF from 1.6.1 to 1.6.2 appear.
Reproduced for Administrator configuration page only. 
Redmine log is below:

Started GET "/redmine/settings/plugin/redmine_dmsf" for 127.0.0.1 at 2018-12-27 15:13:52 +0300
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_dmsf"}
  Current user: skibarko (id=1)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_settings.html.erb (156.0ms)
  Rendered settings/plugin.html.erb within layouts/admin (171.6ms)
Completed 500 Internal Server Error in 187ms (ActiveRecord: 15.6ms)

ActionView::Template::Error (Permission denied @ unlink_internal - D:/dmsf_data/test.test):
    83:   <% rescue %>
    84:     <p class="warning"><%= l(:error_file_can_not_be_created) %></p>
    85:   <%	ensure %>
    86:     <% File.delete(testfilename) if File.exist?(testfilename) %>
    87:   <% end %>
    88: <% end %>
    89: 
  plugins/redmine_dmsf/app/views/settings/_dmsf_settings.html.erb:86:in `delete'
  plugins/redmine_dmsf/app/views/settings/_dmsf_settings.html.erb:86:in `_b11822ee9b77a1b6f1163101151132b6'
  app/views/settings/plugin.html.erb:6:in `block in _2cf743301a91bf557f913a198c211c89'
  app/views/settings/plugin.html.erb:4:in `_2cf743301a91bf557f913a198c211c89'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'

**Comment by picman** [comment]
It seems to be related to MS Windows only. You can manually fix it according to this commit https://github.com/danmunn/redmine_dmsf/commit/4a2f512186bb59fed37442013235dc81418d7715.

**Comment by ahorek** [comment]
@picman this isn't correct. File.open without a block leaks the file descriptor. Unlike other systems Windows won't allow you to delete a file that is still open / used. A good practice is to close a file by calling File#close in an ensure block or even better add a block to File.open itself that calls File#close automatically under the hood.

**Comment by picman** [comment]
Okay.

**Comment by dskibarko** [comment]
Hi. 
Then plans appear 2.0.0 release ? 
Thank you

**Comment by picman** [comment]
1-2 months.
