### ISSUE TITLE
To simplify Email notification settings 

### ISSUE THREAD

**Issue by bellatriks** [danmunn/redmine_dmsf#947]
As far as I understand there are two kind of Email notification settings exist: 
1. Redmine's user settings that can be configured in My Account tab
2. Plugin's Email notification settings (DMS tab, Project setting tab, Administrator setting tab)

Using both of the setting in the plugin leads to confusion and unexpected behavior. 

For example: if user sets the notification to "Only for things I watch or I'm involved in" and the Email notification is set to default in  DMS project preferences tab, there is no any way to select the documents to watch. 

Another example is the default Notification setting.  If the plugin's notification is enabled globally in Admin tab (Administration->Plugins->DMSF), it does not take any effect, because the Email notification in the Project's DMS tab is "Default" (means use Redmine's user settings ) by default %) 

From my point of view, plugin should behave as Wiki's "watch/unwatch" scheme. If user wants to watch for some documents, he just simply select folder/file to watch. What do you think ?

My Env:
Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
  Xitolite                       2.1.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.5
  redmine_dmsf                   1.6.0
  redmine_git_hosting            1.2.3
  redmine_theme_changer          0.3.1

**Comment by picman** [comment]
You're right, the notifications configuration is cumbersome. A side effect of changes you suggest is that the users used to the present configuration might be confused and will have to update their settings.
All in all I'd like to change it too.

**Comment by bellatriks** [comment]
True, it might be painful for some users.

**Comment by mmundi72** [comment]
Same as #557
Would be great if that feature could be implemented.

**Comment by picman** [comment]
Duplicated #557.
