### ISSUE TITLE
The page you were trying to access doesn't exist or has been remove (configuring plugin)

### ISSUE THREAD

**Issue by abeamud** [danmunn/redmine_dmsf#949]
Environment:
  Redmine version                3.4.7.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.11
  Environment                    production
  Database adapter               PostgreSQL
Redmine plugins:
  redmine_dmsf                   1.6.2
All seems ok, but trying to configure the plugin, gives me the title message "The page you were trying to access doesn't exist or has been remove "
The same message appears trying to create a new project or a new issue.

**Comment by picman** [comment]
> The same message appears trying to create a new project or a new issue.

So very probably the problem is not related to the plugin. Look into the _production.log_ what is wrong.

**Comment by picman** [comment]
Remove the link and rename _plugins/redmine-1.6.2_ to _plugins/redmine_dmsf_.

**Comment by abeamud** [comment]
Ahhh, ok now the rest of redmine seems to work ok, but trying to configure dmsf, gives me a 500 error, and the production.log:

 Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_settings.html.erb (41.3ms)
  Rendered settings/plugin.html.erb within layouts/admin (102.9ms)
Completed 500 Internal Server Error in 237ms (ActiveRecord: 35.5ms)

`ActionView::Template::Error (PG::UndefinedTable: ERROR:  no existe la relación «dmsf_file_revisions»
LINE 5:                WHERE a.attrelid = '"dmsf_file_revisions"'::r...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"dmsf_file_revisions"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):
    69:     <%= l(:label_default) %>: dmsf
    70:   </em>
    71: </p>
    72: <% unless File.exist?(DmsfFile.storage_path) %>
    73:   <% begin %>
    74:      <% FileUtils.mkdir_p DmsfFile.storage_path %>
    75:   <% rescue %>
  plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:51:in `block in <class:DmsfFileRevision>'
  plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:66:in `<class:DmsfFileRevision>'
  plugins/redmine_dmsf/app/models/dmsf_file_revision.rb:24:in `<top (required)>'
  plugins/redmine_dmsf/app/models/dmsf_file.rb:76:in `<class:DmsfFile>'
  plugins/redmine_dmsf/app/models/dmsf_file.rb:32:in `<top (required)>'
  plugins/redmine_dmsf/app/views/settings/_dmsf_settings.html.erb:72:in `_plugins_redmine_dmsf_app_views_settings__dmsf_settings_html_erb___1226014462075659948_46915384255100'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__2888810440290227231_46915376789280'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__2888810440290227231_46915376789280'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'
`

**Comment by abeamud** [comment]
Ok, solved. The problem was executing the: 
`bundle exec rake redmine:plugins:migrate RAILS_ENV="production"`
as root. I've changed the owner user and launch the command with that user and all have worked like a charm.
A lot of thanks
