### ISSUE TITLE
when run "ruby redmine_dmsf/extra/xapian_indexer.rb -vf" it echo errors.

### ISSUE THREAD

**Issue by yaocanwei** [danmunn/redmine_dmsf#953]
![image](https://user-images.githubusercontent.com/4312268/51373104-31db0080-1b3a-11e9-842b-15ef9b1a9b85.png)

**Comment by picman** [comment]
Duplicates #933

Remove _-f_ options from your command. It's no more supported.

**Comment by yaocanwei** [comment]
Ok. Thanks for replying.
