### ISSUE TITLE
Permission "User preferences" clarification

### ISSUE THREAD

**Issue by mrak0s** [danmunn/redmine_dmsf#955]
As settings are located /settings/dmsf, no sense to have checkbox for non members and anonymous. Because section /settings is unreachable for above described users.
And permission "File approval" seems mean "Assign approval workflow", so can be renamed. 
Thank you in advance.
![capture](https://user-images.githubusercontent.com/26814959/51544806-f5244780-1e60-11e9-85bb-00e3965798cd.PNG)

**Comment by picman** [comment]
1) The check boxes of User preferences for Non member and Anonymous removed.
2) File approval permissions is not only for assignment but also for start and approval.
