### ISSUE TITLE
Notifications not working if file is edited via webdav

### ISSUE THREAD

**Issue by acosonic** [danmunn/redmine_dmsf#957]
If it's edited and version updated thru Redmine, notification is sent.

If it's edited and version updated via webdav, notification is not sent.

Also folder notifications, don't work...

redmine_dmsf                   1.5.9

**Comment by acosonic** [comment]
Shouldn't there be some trigger for notifications, or cron job...?

**Comment by acosonic** [comment]
I guess notification should be added in put, here https://github.com/danmunn/redmine_dmsf/blob/cb1601f783c8ec0be5835cd75aa929469c6d22dc/lib/dav4rack/controller.rb#L133

**Comment by picman** [comment]
Duplicates #697. Upgrade to 1.6.0.
