### ISSUE TITLE
tag column missing in the dms_file_revision_table

### ISSUE THREAD

**Issue by speedytom** [danmunn/redmine_dmsf#965]
![create-tag-01](https://user-images.githubusercontent.com/43999405/52217185-3b819980-2898-11e9-8ead-a029ae881178.png)
![create-tag-02](https://user-images.githubusercontent.com/43999405/52217189-3fadb700-2898-11e9-87ed-f8b24aca2a4c.png)
![create-tag-03](https://user-images.githubusercontent.com/43999405/52217382-9c10d680-2898-11e9-9ad1-991c0cf16c7a.png)

I don't see any data for tag field. Thanks for your help in advance

**Comment by speedytom** [comment]
We see this problem for DMSF 1.6.2 and redmine 3.4.2.

**Comment by speedytom** [comment]
No, I don't see any warnings or errors:
Started POST "/dmsf/files/33/revision/create" for 10.10.39.100 at 2019-02-04 15:22:33 +0100
Processing by DmsfFilesController#create_revision as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"adLdNdxYYHZwBLdVJSrg43Imhfc+viYvsgYTP6EsZDPOZlYEP5uhC1OqD9P/CoPUbmsWm23ZxCbcFEQDKRsVWw==", "dmsf_file_revision"=>{"title"=>"rozlozeni portu - zvlastni segmenty pro NBI - minimalni komora - v0.1.2", "name"=>"2018.08.08-09
-2_days_videoconference-draft_programme_v2.xlsx", "description"=>"bla bla bla", "custom_field_values"=>{"1"=>"Drawing"}, "comment"=>"tagged as drawing"}, "version"=>"3", "custom_version_major"=>"5", "custom_version_minor"=>"2", "commit"=>"Create", "id"=>"33"}
  Current user: admin (id=1)
Redirected to http://redmine-new.tok.ipp.cas.cz/dmsf/files/33
Completed 302 Found in 89ms (ActiveRecord: 57.6ms)
Started GET "/dmsf/files/33" for 10.10.39.100 at 2019-02-04 15:22:33 +0100
Processing by DmsfFilesController#show as HTML
  Parameters: {"id"=>"33"}
  Current user: admin (id=1)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_file_new_revision.html.erb (13.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (1.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (2.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (0.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (2.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (2.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (2.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (2.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb within layouts/base (114.2ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (1.0ms)
  Rendered plugins/single_auth/app/views/hooks/single_auth/_html_head.html.erb (0.6ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.5ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.1ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (2.5ms)
Completed 200 OK in 163ms (Views: 128.5ms | ActiveRecord: 26.7ms)
Started GET "/projects/redmine-u/dmsf" for 10.10.39.100 at 2019-02-04 15:23:10 +0100
Processing by DmsfController#show as HTML
  Parameters: {"id"=>"redmine-u"}
  Current user: admin (id=1)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (13.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (16.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_dir.html.erb (14.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (10.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (8.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (3.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (17.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (9.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_approval_workflow_button.html.erb (0.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_file.html.erb (8.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_url.html.erb (1.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_list_view.erb (114.4ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_multi_upload.html.erb (3.0ms)
  Rendered plugins/redmine_dmsf/app/views/settings/_dmsf_columns.html.erb (1.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/show.html.erb within layouts/base (144.5ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (0.9ms)
  Rendered plugins/single_auth/app/views/hooks/single_auth/_html_head.html.erb (0.6ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.4ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.1ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (2.4ms)
Completed 200 OK in 194ms (Views: 139.4ms | ActiveRecord: 43.4ms)

**Comment by speedytom** [comment]
Do you have any idea where is root case of our problem?

I dig in it more. I see this output:
select type, name from custom_fields
DmsfFileRevisionCustomField, Tag

Thanks in advance.

**Comment by picman** [comment]
Concerning the issue's title. The Tag is a DMS custom field which definition is stored in _custom_fields_ and it's values are in _custom_values_ tables.

Take a look at app/controllers/dmsf_files_controller.rb around line 140 at the following code related to storing custom fields from the new revision's form.

```ruby
# Custom fields
if params[:dmsf_file_revision][:custom_field_values].present?
  params[:dmsf_file_revision][:custom_field_values].each_with_index do |v, i|
    revision.custom_field_values[i].value = v[1]
  end
end
```

Try to add there some log messages, restart the application, add a new revision and check the production.log then.

e.g.:

```ruby
# Custom fields
Rails.logger.info '>>> Custom fields start'
if params[:dmsf_file_revision][:custom_field_values].present?
  Rails.logger.info '>>> Custom fields present'
  params[:dmsf_file_revision][:custom_field_values].each_with_index do |v, i|    
    revision.custom_field_values[i].value = v[1]
    Rails.logger.info ">>> Custom value #{i} set to #{v[1]}"
  end
end
```

**Comment by speedytom** [comment]
1. modified dmsf_files_controller.rb
root@redmine-new:/usr/local/share/redmine-3.4.2/plugins/redmine_dmsf# diff -u ./app/controllers/dmsf_files_controller.rb.190212 ./app/controllers/dmsf_files_controller.rb                                                                                                     
--- ./app/controllers/dmsf_files_controller.rb.190212   2019-02-12 08:34:07.092589632 +0100                                                                                                                                                                                    
+++ ./app/controllers/dmsf_files_controller.rb  2019-02-12 08:35:23.046880866 +0100                                                                                                                                                                                            
@@ -138,9 +138,12 @@                                                                                                                                                                                                                                                           
         end                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                               
         # Cu@@ -357,4 +360,4 @@                                                                                                                                                                                                                                                            
     @tree_view = (User.current.pref[:dmsf_tree_view] == '1') && (!%w(atom xml json).include?(params[:format])) && !tag                                                                                                                                                        
   end                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                               
-end                                                                                                                                                                                                                                                                           
\ No newlinstom fields                                                                                                                                                                                                                                                       
+        Rails.logger.info '>>> Custom fields start'                                                                                                                                                                                                                           
         if params[:dmsf_file_revision][:custom_field_values].present?                                                                                                                                                                                                         
+          Rails.logger.info '>>> Custom fields present'                                                                                                                                                                                                                       
           params[:dmsf_file_revision][:custom_field_values].each_with_index do |v, i|                                                                                                                                                                                         
             revision.custom_field_values[i].value = v[1]                                                                                                                                                                                                                      
+            Rails.logger.info ">>> Custom value #{i} set to #{v[1]}"                                                                                                                                                                                                          
           end                                                                                                                                                                                                                                                                 
         end                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                               
2. restarted apache
root@redmine-new:~# /etc/init.d/apache2 restart                                    
[ ok ] Restarting apache2 (via systemctl): apache2.service.
                                                             

3. created a new revision 
There is output from log.

Started POST "/dmsf/files/39/revision/create" for 10.10.39.100 at 2019-02-12 08:38:41 +0100
Processing by DmsfFilesController#create_revision as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"9/+EjWWp4AUWpO9XOz8MRODfGmaj0uQKSuF5wGj7PHnzSeqZGdjKtnzv0gP96D1QwtbGUsBgU+0PGpxoIOcTEw==", "dmsf_file_revision"=>{"title"=>"COMPASS-U", "name"=>"COMPASS-U.png", "description"=>"", "custom_field_values"=>{"5"=>"CDR"}, "comment"=>""}, "version"=>"1", "custom_version_major"=>"6", "custom_version_minor"=>"8", "commit"=>"Create", "id"=>"39"}
  Current user: admin (id=1)
>>> Custom fields start
>>> Custom fields present
>>> Custom value 0 set to CDR
Redirected to http://redmine-new.tok.ipp.cas.cz/dmsf/files/39
Completed 302 Found in 65ms (ActiveRecord: 28.0ms)
Started GET "/dmsf/files/39" for 10.10.39.100 at 2019-02-12 08:38:41 +0100
Processing by DmsfFilesController#show as HTML
  Parameters: {"id"=>"39"}
  Current user: admin (id=1)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_path.html.erb (0.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb (1.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_file_new_revision.html.erb (14.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (1.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (1.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (4.2ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (1.1ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (1.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.8ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (2.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (2.3ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (0.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.6ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (0.9ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf/_custom_fields.html.erb (3.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb (1.0ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_files/show.html.erb within layouts/base (128.0ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (0.9ms)
  Rendered plugins/single_auth/app/views/hooks/single_auth/_html_head.html.erb (0.6ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.4ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.1ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (2.5ms)
Completed 200 OK in 174ms (Views: 137.8ms | ActiveRecord: 28.7ms)

It means that TAG is set to CDR. I don't still see any TAG in DMS=>Documents.

**Comment by picman** [comment]
If you check the database is the value there?
```sql
select f.name, v.value from custom_values v join custom_fields f on f.id = v.customized_id where f.type='DmsfFileRevisionCustomField' order by v.id desc limit 1;
```

**Comment by speedytom** [comment]
No, I don't have any related values:
<pre>
mysql> select f.name, v.value from custom_values v join custom_fields f on f.id = v.customized_id where f.type='DmsfFileRevisionCustomField' order by v.id desc limit 1;
Empty set (0.00 sec)
</pre>
But I have already defined TAGs values:
![custom-tag_final](https://user-images.githubusercontent.com/43999405/52621248-16e47d80-2ea7-11e9-804c-d164618ad862.png)

**Comment by speedytom** [comment]
<pre>
mysql> select id, type, name, field_format, possible_values from custom_fields;
+----+-----------------------------+------+--------------+----------------------------+
| id | type                        | name | field_format | possible_values            |
+----+-----------------------------+------+--------------+----------------------------+
|  5 | DmsfFileRevisionCustomField | Tag  | list         | ---
- Drawing
- CDR
- FDR
 |
+----+-----------------------------+------+--------------+----------------------------+
1 row in set (0.00 sec)
</pre>

**Comment by picman** [comment]
So, the custom field is not saved. I've no idea why. Sorry.
Maybe switch on DEBUG mode and try to figure out from the log what went wrong.
(```config.log_level = :debug``` in _config/additional_environment.rb_)

```ruby
# Custom fields
if params[:dmsf_file_revision][:custom_field_values].present?
  params[:dmsf_file_revision][:custom_field_values].each_with_index do |v, i|
    revision.custom_field_values[i].value = v[1]
  end
end

@file.name = revision.name

if revision.save
  # If this's Okay, I realy don't know why custom fields are not saved.
 ...
````
```

**Comment by speedytom** [comment]
<pre>
mysql> select * from custom_values;
+----+------------------+---------------+-----------------+-------+
| id | customized_type  | customized_id | custom_field_id | value |
+----+------------------+---------------+-----------------+-------+
| 32 | DmsfFileRevision |            67 |               5 |       |
| 33 | DmsfFileRevision |            68 |               5 |       |
| 34 | DmsfFileRevision |            69 |               5 |       |
| 35 | DmsfFileRevision |            70 |               5 |       |
+----+------------------+---------------+-----------------+-------+
4 rows in set (0.00 sec)
</pre>

**Comment by speedytom** [comment]
[production.log.tag-bug.log](https://github.com/danmunn/redmine_dmsf/files/2854938/production.log.tag-bug.log)

**Comment by speedytom** [comment]
As I understand, our application insert a new empty value. 

Details are here:
<pre>
mysql> select  f.name, v.value, v.customized_id  from custom_fields f , custom_values v where f.id = v.custom_field_id;
+------+-------+---------------+
| name | value | customized_id |
+------+-------+---------------+
| Tag  |       |            67 |
| Tag  |       |            68 |
| Tag  |       |            69 |
| Tag  |       |            70 |
| Tag  |       |            71 |
+------+-------+---------------+
5 rows in set (0.00 sec)

  ^[[1m^[[36mSQL (0.2ms)^[[0m  ^[[1mINSERT INTO `custom_values` (`customized_id`, `customized_type`, `custom_field_id`, `value`) VALUES (71, 'DmsfFileRevision', 5, '')^[[0m
</pre>

**Comment by speedytom** [comment]
If I manually update custom_fields. It works well. I see my TAG.
<pre> 
mysql> update custom_values set value='FDR' where id = 36;
Query OK, 1 row affected (0.05 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from custom_values;
+----+------------------+---------------+-----------------+-------+
| id | customized_type  | customized_id | custom_field_id | value |
+----+------------------+---------------+-----------------+-------+
| 32 | DmsfFileRevision |            67 |               5 |       |
| 33 | DmsfFileRevision |            68 |               5 |       |
| 34 | DmsfFileRevision |            69 |               5 |       |
| 35 | DmsfFileRevision |            70 |               5 |       |
| 36 | DmsfFileRevision |            71 |               5 | FDR   |
+----+------------------+---------------+-----------------+-------+
5 rows in set (0.00 sec)
</pre>

It seems like problem with LIST format:
<pre>
mysql> select possible_values from custom_fields;
+----------------------------+
| possible_values            |
+----------------------------+
| ---
- Drawing
- CDR
- FDR
 |
+----------------------------+
1 row in set (0.00 sec)
</pre>

**Comment by speedytom** [comment]
It is problem with default value for custom_field(in my case TAG). I changed default value for custom field several times. Each time I saved default value.
<pre>
  SQL (0.1ms)  INSERT INTO `custom_values` (`customized_id`, `customized_type`, `custom_field_id`, `value`) VALUES (78, 'DmsfFileRevision', 5, '')
  SQL (0.2ms)  INSERT INTO `custom_values` (`customized_id`, `customized_type`, `custom_field_id`, `value`) VALUES (79, 'DmsfFileRevision', 5, 'Drawing')
  SQL (0.2ms)  INSERT INTO `custom_values` (`customized_id`, `customized_type`, `custom_field_id`, `value`) VALUES (80, 'DmsfFileRevision', 5, 'Drawing')
  SQL (0.2ms)  INSERT INTO `custom_values` (`customized_id`, `customized_type`, `custom_field_id`, `value`) VALUES (81, 'DmsfFileRevision', 5, 'FDR')
  SQL (0.2ms)  INSERT INTO `custom_values` (`customized_id`, `customized_type`, `custom_field_id`, `value`) VALUES (82, 'DmsfFileRevision', 5, 'FDR')
</pre>

**Comment by picman** [comment]
I don't understand. So even if you try to insert a new custom value directly by a SQL command, the default value is inserted instead of the value you wanted to insert?

**Comment by speedytom** [comment]
No, previous comment was just log output from my testing procedure. I didn't insert values manually.

**Comment by speedytom** [comment]
It seems like "A common libraries" plugin change TAG value to default value from this list.

I tried uninstall this plugin. Unfortunately it didn't work. 

Is it possible run this plugin on REDMINE 4?

**Comment by speedytom** [comment]
Is it DMSF ready for REDMINE 4?

**Comment by picman** [comment]
1. How have you uninstalled it? You have to remove its directory completely to stop it functioning.
2. Not yet, but you can try devel-2.0.0 branch witch is compatible with Redmine 4 and will be released at the beginning of March.

**Comment by speedytom** [comment]
Thanks for point 2.

Yes. I removed completely. After that action Redmine was unavailable. Do you have any hint about plugin uninstallation?

**Comment by picman** [comment]
No, just revert the Db migration and remove the plugin. That's all.

**Comment by speedytom** [comment]
Thanks for your support.
