### ISSUE TITLE
About the DMSF folder search logic

### ISSUE THREAD

**Issue by HIROORIH** [danmunn/redmine_dmsf#969]
Hello

I am in trouble with the environment using 1.6.1.
There is circumstance, so in 1.6.2 I can not try it now.

The problem is with search function.
Filenames can be searched for characters other than English.
The folder name can be searched only in English. I can not hit anything other than English.

I want to check why this problem occurs with the 1.6.1 source, but I do not know where the source making the search function is.

I'm sorry, could you tell me which file contains the logic used in the search?

"After_init.rb" is displayed only ...?

**Comment by HIROORIH** [comment]
Supplement.
Search is Redmine's standard search.
Search attached to DMSF has no problem.

**Comment by picman** [comment]
Can you post an example of a folder's name which can't be searched?

**Comment by HIROORIH** [comment]
No.1
ABC Project
There is a folder called "1月度".
Search by "月度", you can search.

No. 2
HJI Project
There is a folder called "赤青黄".
If you search by "赤", you can not search.

No. 3
HJI Project
There is a folder called "APPLE".
Search by "APPLE", you can search.

I am worried why I can not search by No.2.

**Comment by picman** [comment]
The issue is very probably related to Redmine itself (I just call a Redmine's function to search for folders). If you try the same with issues they are not searchable too. A positive piece of news is that if I try it in Redmine 4.0 + DMSF 2.0 it works.

**Comment by HIROORIH** [comment]
Thank you for contacting me.

It's just calling a function. Thank you for teaching me.
It also seems to work with [Redmine 4.0 + DMSF 2.0].
I was relieved when I next upgraded it seems okay.

After that, I verified with members and found out something.
Redmine "3.4.6" + DMSF "1.6.1" is used.
With this combination, it seems that you can not search by one character.
Whether in English or any other language.

For now, I will search with more than one letter.

Thank you always for your early reply. It saved me.

**Comment by picman** [comment]
No problem.
