### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by akil4u001** [danmunn/redmine_dmsf#970]
Hey I am getting error while installing the DMSF, Please help...

Attached below
`[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: redmine_extensions (>= 0) and redmine_extensions (~> 0.2.5). Bundler cannot continue.

 #  from /opt/redmine/redmine-3.4.5/plugins/redmine_dmsf/Gemfile:33
 #  -------------------------------------------
 #  unless %w(easyproject easy_gantt).any? { |plugin| Dir.exist?(File.expand_path("../../#{plugin}", __FILE__)) }
 >    gem 'redmine_extensions', '~> 0.2.5'
 #  end
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /opt/redmine/redmine-3.4.5/Gemfile:113
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------
`

**Comment by picman** [comment]
Very probably you have got another plugin with the same dependency. Just comment out the line requesting redmine_extension in the _Gemfile_.

```ruby
# Redmine extensions
unless %w(easyproject easy_gantt).any? { |plugin| Dir.exist?(File.expand_path("../../#{plugin}", __FILE__)) }
--  gem 'redmine_extensions', '~> 0.2.5'
++  #gem 'redmine_extensions', '~> 0.2.5'
end
```
