### ISSUE TITLE
LoadError: No such file to load -- ../validators/dmsf_file_name_validator.rb

### ISSUE THREAD

**Issue by ausghostdog** [danmunn/redmine_dmsf#971]
EDIT: Just notied that 4.0 is only supported in devel-2.0.0 at present 

EDIT 2 Devel is giving the same error 

Environment:
  Redmine version                4.0.1.stable.17851
  Ruby version                   2.4.5-p335 (2018-10-18) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_custom_css             0.1.7
  redmine_custom_js              0.1.1

/opt/redmine/current/plugins$ bundle exec rake redmine:plugins:migrate RAILS_ENV="production" --trace
(in /opt/redmine/current)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
LoadError: No such file to load -- ../validators/dmsf_file_name_validator.rb

:/opt/redmine/current/plugins/redmine_dmsf-1.6.2/app/validators$ ls
dmsf_file_name_validator.rb  dmsf_url_validator.rb  dmsf_workflow_name_validator.rb

**Comment by picman** [comment]
Rename _redmine_dmsf-1.6.2_ folder to _redmine_dmsf_.

**Comment by ausghostdog** [comment]
:/opt/redmine/current$ bundle exec rake redmine:plugins:migrate RAILS_ENV="production" --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
Thanks for getting back to me

** Execute environment
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Reloader:Class
/opt/redmine/current/plugins/redmine_dmsf/after_init.rb:103:in `<top (required)>'
/opt/redmine/current/plugins/redmine_dmsf/init.rb:70:in `require_relative'
/opt/redmine/current/plugins/redmine_dmsf/init.rb:70:in `<top (required)>'

I also tried the deval version as well
:/opt/redmine/current/plugins$ bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.3.2
Using concurrent-ruby 1.1.4
Using i18n 0.7.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.2
Using builder 3.2.3
Using erubi 1.8.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.1
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using actionview 5.2.2
Using rack 2.0.6
Using rack-test 1.1.0
Using actionpack 5.2.2
Using nio4r 2.3.1
Using websocket-extensions 0.1.3
Using websocket-driver 0.7.0
Using actioncable 5.2.2
Using globalid 0.4.2
Using activejob 5.2.2
Using mini_mime 1.0.1
Using mail 2.7.1
Using actionmailer 5.2.2
Using method_source 0.9.2
Using thor 0.20.3
Using railties 5.2.2
Using actionpack-xml_parser 2.0.1
Using activemodel 5.2.2
Using arel 9.0.0
Using activerecord 5.2.2
Using mimemagic 0.3.3
Using marcel 0.3.3
Using activestorage 5.2.2
Using public_suffix 3.0.3
Using addressable 2.6.0
Using bundler 1.17.3
Using css_parser 1.6.0
Using csv 3.0.4
Using dalli 2.7.9
Using htmlentities 4.3.4
Using mysql2 0.5.2
Using net-ldap 0.16.1
Using ox 2.10.0
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 5.2.2
Using rbpdf-font 1.19.1
Using rbpdf 1.19.8
Using redcarpet 3.4.0
Using redmine_extensions 0.2.14
Using request_store 1.0.5
Using rmagick 2.16.0
Using roadie 3.4.0
Using roadie-rails 1.3.0
Using rouge 3.3.0
Using rubyzip 1.2.2
Using simple_enum 2.3.2
Using uuidtools 2.1.5
Using zip-zip 0.3
Bundle complete! 35 Gemfile dependencies, 66 gems now installed.
Gems in the groups development and test were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
You have new mail in /var/mail/
@-virtual-machine:/opt/redmine/current/plugins$ bundle exec rake redmine:plugins:migrate RAILS_ENV="production" --trace
(in /opt/redmine/current)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:migrate
== 20170323131231 DmsfDescriptionLimit: migrating =============================
-- adapter_name()
   -> 0.0000s
-- change_column(:projects, :dmsf_description, :text, {:null=>true, :limit=>65535})
   -> 0.0137s
-- adapter_name()
   -> 0.0000s
-- change_column(:dmsf_folders, :description, :text, {:null=>true, :limit=>65535})
   -> 0.0063s
== 20170323131231 DmsfDescriptionLimit: migrated (0.0217s) ====================

== 20170330131901 CreateDmsfFolderPermissions: migrating ======================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:dmsf_folder_permissions, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.0079s
-- add_index(:dmsf_folder_permissions, :dmsf_folder_id)
   -> 0.0763s
== 20170330131901 CreateDmsfFolderPermissions: migrated (0.0845s) =============

== 20170421101901 DmsfFileContainerRollback: migrating ========================
-- add_column(:dmsf_folders, :system, :boolean, {:null=>false, :default=>false})
   -> 0.0380s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Validation failed: Title contains invalid character(s)
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/validations.rb:80:in `raise_validation_error'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/validations.rb:52:in `save!'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/transactions.rb:315:in `block in save!'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home//.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/transactions.rb:315:in `save!'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/suppressor.rb:48:in `save!'
/opt/redmine/current/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:52:in `block in up'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `each'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `block in find_each'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:222:in `loop'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:222:in `in_batches'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:69:in `find_each'
/opt/redmine/current/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:29:in `up'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:817:in `exec_migration'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home//.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:797:in `block in migrate'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:796:in `migrate'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:in `migrate'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1345:in `ddl_transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `each'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `block in migrate'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `migrate'
/opt/redmine/current/lib/redmine/plugin.rb:498:in `up'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:in `migrate'
/opt/redmine/current/lib/redmine/plugin.rb:530:in `migrate_plugin'
/opt/redmine/current/lib/redmine/plugin.rb:471:in `migrate'
/opt/redmine/current/lib/redmine/plugin.rb:485:in `block in migrate'
/opt/redmine/current/lib/redmine/plugin.rb:484:in `each'
/opt/redmine/current/lib/redmine/plugin.rb:484:in `migrate'
/opt/redmine/current/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/home//.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home//.rvm/gems/ruby-2.4.5/bin/rake:23:in `load'
/home//.rvm/gems/ruby-2.4.5/bin/rake:23:in `<main>'
/home//.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:15:in `eval'
/home//.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
ActiveRecord::RecordInvalid: Validation failed: Title contains invalid character(s)
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/validations.rb:80:in `raise_validation_error'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/validations.rb:52:in `save!'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/transactions.rb:315:in `block in save!'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home//.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/transactions.rb:315:in `save!'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/suppressor.rb:48:in `save!'
/opt/redmine/current/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:52:in `block in up'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `each'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `block in find_each'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:222:in `loop'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:222:in `in_batches'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:69:in `find_each'
/opt/redmine/current/plugins/redmine_dmsf/db/migrate/20170421101901_dmsf_file_container_rollback.rb:29:in `up'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:817:in `exec_migration'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home//.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:797:in `block in migrate'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:796:in `migrate'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:in `migrate'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1345:in `ddl_transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `each'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `block in migrate'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `migrate'
/opt/redmine/current/lib/redmine/plugin.rb:498:in `up'
/home//.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:in `migrate'
/opt/redmine/current/lib/redmine/plugin.rb:530:in `migrate_plugin'
/opt/redmine/current/lib/redmine/plugin.rb:471:in `migrate'
/opt/redmine/current/lib/redmine/plugin.rb:485:in `block in migrate'
/opt/redmine/current/lib/redmine/plugin.rb:484:in `each'
/opt/redmine/current/lib/redmine/plugin.rb:484:in `migrate'
/opt/redmine/current/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/home//.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/home//.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home//.rvm/gems/ruby-2.4.5/bin/rake:23:in `load'
/home//.rvm/gems/ruby-2.4.5/bin/rake:23:in `<main>'
/home//.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:15:in `eval'
/home//.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
@-virtual-machine:/opt/redmine/current/plugins$

**Comment by picman** [comment]
> Validation failed: Title contains invalid character(s)

It seems that some of your folders' titles contain invalid characters in your database. As a workaround just comment out the validation in _app/validatores/dmsf_file_name_validator.rb_ before the migration as follows:
```ruby
class DmsfFileNameValidator  < ActiveModel::EachValidator

  def validate_each(record, attribute, value)
    unless /\A[^#{DmsfFolder::INVALID_CHARACTERS}]*\z/.match?(value)
      #record.errors.add attribute, :error_contains_invalid_character
    end
  end

end
```

**Comment by ausghostdog** [comment]
Think I found the issue, I cloned our main server to do the update to 4.0, instead of reading the uninstall process of I just rm -rfed the plugin file. Which seems to have lead to this issue.  As now even after commenting out the line, MYSQL is throwing an error for the process

(in /opt/redmine/current)
== 20170421101901 DmsfFileContainerRollback: migrating ========================
-- add_column(:dmsf_folders, :system, :boolean, {:null=>false, :default=>false})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Duplicate column name 'system': ALTER TABLE `dmsf_folders` ADD `system` tinyint(1) DEFAULT FALSE NOT NULL

Will redo the test server and remove the pluggin correctly this time and it should work.

**Comment by picman** [comment]
Be aware that the plugin v1.6.2 is not compatible with Redmine 4.0.It will be v2.0.0
