### ISSUE TITLE
Failing to upload document via API

### ISSUE THREAD

**Issue by dnyamy** [danmunn/redmine_dmsf#972]
Hello,

I have been trying for days, to upload a file via the API.

The first step, upload seems Ok, I receive a token I then use to commit
The commit also seems Ok, as I receive a 200 OK.
But yet, there is no file in my redmine project.

Here are my upload and commit logs
`* Rebuilt URL to: POST/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Could not resolve host: POST
* Closing connection 0
curl: (6) Could not resolve host: POST
*   Trying 137.74.119.29...
* Connected to redmine.cphlabs.net (137.74.119.29) port 80 (#1)
* Server auth using Basic with user 'dnyamy'
> POST /projects/dans-le-creuset-en-vue-du-service/dmsf/upload.json?filename=test.docx HTTP/1.1
> Host: redmine.cphlabs.net
> Authorization: Basic xxxxxxxxxxxxxxcccccx==
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/octet-stream
> Content-Length: 36490
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
} [16384 bytes data]
* We are completely uploaded and fine
< HTTP/1.1 201 Created
< Date: Mon, 11 Feb 2019 12:56:14 GMT
< Server: Apache
< Cache-Control: max-age=0, private, must-revalidate
< X-XSS-Protection: 1; mode=block
< X-Request-Id: e51abb03-13eb-4a4e-ab7a-65b02549b573
< X-Frame-Options: SAMEORIGIN
< X-Runtime: 0.087160
< X-Content-Type-Options: nosniff
< X-Powered-By: Phusion Passenger 5.1.8
< ETag: W/"ed8a5ec1cdc7241f239156755acb9cd5"
< Status: 201 Created
< Transfer-Encoding: chunked
< Content-Type: application/json; charset=utf-8
< 
{ [103 bytes data]
100 36582    0    92  100 36490    620   240k --:--:-- --:--:-- --:--:--  240k
* Connection #1 to host xxxxxxxxxxxxxxxxxxx left intact
* Rebuilt URL to: POST/
* Could not resolve host: POST
* Closing connection 0
curl: (6) Could not resolve host: POST
*   Trying 137.74.119.29...
* Connected to xxxxxxxxxxxxxxx (137.74.119.29) port 80 (#1)
* Server auth using Basic with user 'dnyamy'
> POST /projects/dans-le-creuset-en-vue-du-service/dmsf/commit.xml HTTP/1.1
> Host: xxxxxxxxxxxx
> Authorization : xxxxxxxx.  
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/xml
> Content-Length: 200
> 
* upload completely sent off: 200 out of 200 bytes
< HTTP/1.1 200 OK
< Date: Mon, 11 Feb 2019 12:56:14 GMT
< Server: Apache
< Cache-Control: max-age=0, private, must-revalidate
< X-XSS-Protection: 1; mode=block
< X-Request-Id: 2530a903-6567-4092-8647-7c38826b29f7
< X-Frame-Options: SAMEORIGIN
< X-Runtime: 0.048100
< X-Content-Type-Options: nosniff
< X-Powered-By: Phusion Passenger 5.1.8
< ETag: W/"b8ab1aaa88580e04d1d1bd28dfdafbc7"
< Status: 200 OK
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< Content-Type: application/xml; charset=utf-8
< 
* Connection #1 to host xxxxxxxxxxxxxxx left intact
<?xml version="1.0" encoding="UTF-8"?><dmsf_files total_count="0" type="array"></dmsf_files>`

And here is an example xml file params for the commit step
`<file>
  <token>2540.5f28358206ffa1e73cbb4ae140d3ab302814f0c11c6921ffdd05625cb93b0300</token>
  <filename>test.docx</filename>
  <comment></comment>
  <description>Document vide</description>
</file>`

Please a little help would be much appreciated
Regards

**Comment by picman** [comment]
What does say the _production.log_ after a successful commit?

**Comment by dnyamy** [comment]
Logs for both steps : 
`Started POST "/projects/dans-le-creuset-en-vue-du-service/dmsf/upload.json?filename=test.docx" for 137.74.119.29 at 2019-02-12 01:47:08 +0100
Processing by DmsfUploadController#upload as JSON
  Parameters: {"filename"=>"test.docx", "id"=>"dans-le-creuset-en-vue-du-service"}
  Current user: dnyamy (id=5)
Saving attachment '/usr/share/redmine/files/2019/02/190212014708_test.docx' (36490 bytes)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/upload.api.rsb (0.4ms)
Completed 201 Created in 66ms (Views: 1.3ms | ActiveRecord: 39.9ms)
Started POST "/projects/dans-le-creuset-en-vue-du-service/dmsf/commit.xml" for 137.74.119.29 at 2019-02-12 01:47:09 +0100
Processing by DmsfUploadController#commit as XML
  Parameters: {"file"=>{"token"=>"2541.5f28358206ffa1e73cbb4ae140d3ab302814f0c11c6921ffdd05625cb93b0300", "filename"=>"test.docx", "comment"=>nil, "description"=>"Document vide"}, "id"=>"dans-le-creuset-en-vue-du-service"}
  Current user: dnyamy (id=5)
  Rendered plugins/redmine_dmsf/app/views/dmsf_upload/commit.api.rsb (0.4ms)
Completed 200 OK in 25ms (Views: 0.9ms | ActiveRecord: 12.4ms)`

**Comment by picman** [comment]
Hm, that's a mystery. Everything seems to be all right. If you check your database, tables dmsf_files and dmsf_file_revisions, are just created file and it's revision there?

**Comment by dnyamy** [comment]
I have rerun the test, and checked the database
No created file in dmsf_file_revisions nor dmsf_files tables

**Comment by picman** [comment]
I think that your xml file for the commit has got a wrong format. Check the [wiki](https://github.com/danmunn/redmine_dmsf/wiki/REST-API). It should look like follows:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<attachments>
  <folder_id/>
  <uploaded_file>
    <name>test.txt</name>
    <title>test.txt</title>
    <description>REST API</description>
    <comment>From API</comment>
    <version/>
    <token>45205.181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b</token>
  </uploaded_file>
</attachments>
```

**Comment by dnyamy** [comment]
Indeed, my xml was not well formatted
Thank you very much
Working nice
