### ISSUE TITLE
Subrpojects as folders

### ISSUE THREAD

**Issue by acosonic** [danmunn/redmine_dmsf#974]
Sanity check for feature request...

If 1 project like "parent project", has DMSF turned on, and it's sub-projects also.

Can web-dav of parent project display subprojects like folders?

Could this be optional feature like in settings "enable sub-projects as folders"

This way 1 user will have only 1 mapped drive in windows, for example with all documents from all sub-projects...

**Comment by picman** [comment]
Duplicates #460.

**Comment by acosonic** [comment]
So, as far as sanity check, it's sane :+1:

**Comment by acosonic** [comment]
> Duplicates #460.

I've made comment there
[](https://github.com/danmunn/redmine_dmsf/issues/460#issuecomment-465915991)
