### ISSUE TITLE
Can't link document to issue with column in subject

### ISSUE THREAD

**Issue by danaivehr** [danmunn/redmine_dmsf#976]
If issue has column in its subject, i can't link document to it.

To reproduce:

* Create Issue with subject "Foo: bar"
* Create any document in DMSF, Foo.docx for example
* Edit issue "Foo: bar" - add a link to Foo.docx
* Save issue

Expected result: Foo.docx is linked to "Foo: bar" issue and shown on its page

Actual result: No Foo.docx link on "Foo bar" issue page
Additional details:
* There is no system folder "/.Issues/1234 - Foo: bar" created as usual, seems like ":" is not acceptable here
* Thus link to file is dropped in "/" of projects dmsf

I have dmsf 1.6.1 installed on redmine 3.4
Ubuntu with PostgreSQL

**Comment by picman** [comment]
Already fixed in 2.0.0.

**Comment by picman** [comment]
It's very probably fixed in the master branch too. So if you cloned the repository, you can just update the master branch. But be careful, I'm merging devel-2.0.0 into the master branch tomorrow.

**Comment by danaivehr** [comment]
Thanks! Updated to 1.6.2 and confirming it works now.
