### ISSUE TITLE
Can not access files after upgrade to devel-2.0.0

### ISSUE THREAD

**Issue by carterb23** [danmunn/redmine_dmsf#977]
Hi all -

I recently moved to redmine 4.0 on my ubuntu 18.04. After upgrading dmsf, I faced the issue of not being able to access files anymore. Even though they are displayed on the folder list, I get following error message when trying to open them:

404 The page you were trying to access doesn't exist or has been removed.

What I recognized: Whenever I click on a file, folders in the format files/dmsf/YEAR/MONTH are created on the hard disk. The original files are placed in files/dmsf/p_project_name.

Cheers,
 Oliver

**Comment by picman** [comment]
Have you run the plugin's migration? Files should be moved from _dmsf/p_identifier_ to _dmsf/YYYY/MM_ during the migration.

**Comment by carterb23** [comment]
Hi, I used

bundle exec rake redmine:plugins:migrate RAILS_ENV="production"

without any change. Can I provide more information?

Regards,
 Oliver

**Comment by picman** [comment]
There were very probably errors during the migration which you ignored. Please see #799 and #767 for a solution.
