### ISSUE TITLE
Copy of root folder to subfolder causes web crash

### ISSUE THREAD

**Issue by BagginsHasIt** [danmunn/redmine_dmsf#980]
We are preparing to update the DMSF plugin on our Redmine server from version 1.5.8 to 1.6.2, and while testing the new build I encountered an issue in the “Copy/Move” folder feature.  I have a “Test Folder” in the root DMS Documents, and inside the test folder is a “Subfolder” with a couple word documents.  When trying to copy/move the Test Folder, it allowed me to copy it into its own Subfolder in the destination dropdown options.   This caused a recursive copy of both folders.  I am unable to delete the first Test Folder because the Subfolder contained files, and cannot find the end of the folder tree.  I am also unable to perform any further copy/move folder actions within this Redmine project, as the folder tree never fully loads.  Has this issue been reported previously?  Is there a way to prevent copying a folder into its own subfolder, to protect the server from user errors?

**Comment by picman** [comment]
Fixed by commit 98938d8f2baa3874589367dfb17fc727c481bd78.
