### ISSUE TITLE
Graphical file previews?

### ISSUE THREAD

**Issue by mrPsycho** [danmunn/redmine_dmsf#981]
Hello! 

thanks for a great plugin, very helpful. 
and question: is it possible to add preview for graphical stuff? png,jpg,cdr,whatever? )

**Comment by phqsh** [comment]
If it is like some thumbnail on mouse over on file in the list it will save us millions of time! 
Or at least make it compatible with lightbox plugin for example.
We store some vector projects for machining and right now we have to either store additional images with same name and open them or store thumbnails in file description, which is also accessible only from file properties.

**Comment by dinya** [comment]
@mrPsycho,

Try https://github.com/paginagmbh/redmine_lightbox2

It works for issue graph attachments and ``{{dmsftn()}}``

**Comment by mrPsycho** [comment]
@dinya yep, i know for this... but, i mean preview on https://redmine.example.ru/projects/pdm_sch/dmsf
cause browsing going in that place... and to use it in wiki or kasks - yes, very helpful feature.

**Comment by dinya** [comment]
@mrPsycho 

Try https://github.com/paginagmbh/redmine_lightbox2/issues/64

**Comment by picman** [comment]
I think that we can close it here as there exists another solution using an external plugin.
