### ISSUE TITLE
No such column: projects.dmsf_description DMSF 2.0

### ISSUE THREAD

**Issue by ausghostdog** [danmunn/redmine_dmsf#982]
Hi,
Have recently upgraded to redmine 4.0, prior to the server was running 1.5.9, following advice from https://github.com/danmunn/redmine_dmsf/issues/975 
I dropped all tables and removed columns 
![image](https://user-images.githubusercontent.com/7588602/53932242-67d14580-40e4-11e9-876e-50050e62b2e1.png)
![image](https://user-images.githubusercontent.com/7588602/53932248-6bfd6300-40e4-11e9-87b3-4cdf8e583816.png)
![image](https://user-images.githubusercontent.com/7588602/53932252-6ef85380-40e4-11e9-808b-744fcd1fe05e.png)

Shows all tables and columns removed, Apache was restarted after and server was tested to make sure Redmine still worked. 

The following commands were then run 
 2001  cd /opt/redmine/current/plugins/
 2002  sudo cp /home//redmine_dmsf-2.0.0.tar.gz /opt/redmine/current/plugins/
 2003  ls
 2004  sudo tar -xzvf redmine_dmsf-2.0.0.tar.gz
 2005  clear
 2006  ls
 2007  sudo mv redmine_dmsf-2.0.0 redmine_dmsf
 2008  sudo chown -R www-data:www-data redmine_dmsf
 2009  cd ../
 2010  bundle install
 2011  bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf RAILS_ENV="production"
 2012  bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf RAILS_ENV="production" --trace

The following error is produced when trying to run the rake command 
redmine@redmine-virtual-machine:/opt/redmine/current$ bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf RAILS_ENV="production" --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:migrate
== 20170323131231 DmsfDescriptionLimit: migrating =============================
-- adapter_name()
   -> 0.0000s
-- change_column(:projects, :dmsf_description, :text, {:null=>true, :limit=>65535})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

No such column: projects.dmsf_description
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `column_for'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:668:in `change_column_for_alter'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:371:in `change_column'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:871:in `block in method_missing'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:840:in `block in say_with_time'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:840:in `say_with_time'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:860:in `method_missing'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration/compatibility.rb:28:in `change_column'
/opt/redmine/current/plugins/redmine_dmsf/db/migrate/20170323131231_dmsf_description_limit.rb:24:in `up'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:817:in `exec_migration'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:797:in `block in migrate'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:796:in `migrate'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:in `migrate'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1345:in `ddl_transaction'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `each'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `block in migrate'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `migrate'
/opt/redmine/current/lib/redmine/plugin.rb:498:in `up'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:in `migrate'
/opt/redmine/current/lib/redmine/plugin.rb:530:in `migrate_plugin'
/opt/redmine/current/lib/redmine/plugin.rb:471:in `migrate'
/opt/redmine/current/lib/redmine/plugin.rb:482:in `migrate'
/opt/redmine/current/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.5.3/bin/rake:23:in `load'
/home/redmine/.rvm/gems/ruby-2.5.3/bin/rake:23:in `<top (required)>'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:463:in `exec'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.5.3/bin/bundle:23:in `load'
/home/redmine/.rvm/gems/ruby-2.5.3/bin/bundle:23:in `<main>'

Caused by:
ActiveRecord::ActiveRecordError: No such column: projects.dmsf_description
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `column_for'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:668:in `change_column_for_alter'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:371:in `change_column'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:871:in `block in method_missing'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:840:in `block in say_with_time'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:840:in `say_with_time'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:860:in `method_missing'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration/compatibility.rb:28:in `change_column'
/opt/redmine/current/plugins/redmine_dmsf/db/migrate/20170323131231_dmsf_description_limit.rb:24:in `up'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:817:in `exec_migration'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:797:in `block in migrate'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:796:in `migrate'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:in `migrate'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1345:in `ddl_transaction'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `each'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `block in migrate'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `migrate'
/opt/redmine/current/lib/redmine/plugin.rb:498:in `up'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:in `migrate'
/opt/redmine/current/lib/redmine/plugin.rb:530:in `migrate_plugin'
/opt/redmine/current/lib/redmine/plugin.rb:471:in `migrate'
/opt/redmine/current/lib/redmine/plugin.rb:482:in `migrate'
/opt/redmine/current/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/home/redmine/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.5.3/bin/rake:23:in `load'
/home/redmine/.rvm/gems/ruby-2.5.3/bin/rake:23:in `<top (required)>'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:463:in `exec'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/home/redmine/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.5.3/bin/bundle:23:in `load'
/home/redmine/.rvm/gems/ruby-2.5.3/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate

It is trying to get to column No such column: projects.dmsf_description yet I removed that one and have since rebooted the server.

I tried editing the table adding the column alter table projects add dmsf_description text

running the command now returns
Mysql2::Error: Table 'redmine.dmsf_folders' doesn't exist: SHOW FULL FIELDS FROM `dmsf_folders`

Is there something else that needs to happen after the tables and columns are removed other than a restart of the apache server?

**Comment by picman** [comment]
Duplicates #975. I've updated #975.
