### ISSUE TITLE
uninitialized constant Redmine::IntegrationTest NameError

### ISSUE THREAD

**Issue by geraldodinukwe80** [danmunn/redmine_dmsf#984]
Hi all, i am trying to install redmine dmsf 2.0 plugin on redmine 4.0 but redmine can´t load after the installation. I checked the nginx error.log file and found the following error.

" Could not spawn process for application /var/data/redmine: The application encountered the following error: uninitialized constant Redmine::IntegrationTest (NameError)"

 Please kindly assist

App 4538 output:     /usr/local/rvm/gems/ruby-2.4.5/gems/passenger-6.0.2/src/hel                                                                             per-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 4538 output:     /usr/local/rvm/gems/ruby-2.4.5/gems/passenger-6.0.2/src/rub                                                                             y_supportlib/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_re                                                                             cord_step_progress'
App 4538 output:     /usr/local/rvm/gems/ruby-2.4.5/gems/passenger-6.0.2/src/hel                                                                             per-scripts/rack-preloader.rb:188:in `<module:App>'
App 4538 output:     /usr/local/rvm/gems/ruby-2.4.5/gems/passenger-6.0.2/src/hel                                                                             per-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 4538 output:     /usr/local/rvm/gems/ruby-2.4.5/gems/passenger-6.0.2/src/hel                                                                             per-scripts/rack-preloader.rb:29:in `<main>'
[ E 2019-03-16 22:31:46.1849 4516/Tc age/Cor/App/Implementation.cpp:221 ]: Could                                                                              not spawn process for application /var/data/redmine: The application encountere                                                                             d the following error: uninitialized constant Redmine::IntegrationTest (NameErro                                                                             r)
  Error ID: ee98900d
  Error details saved to: /tmp/passenger-error-V5LjXS.html

[ E 2019-03-16 22:31:46.1910 4516/T5 age/Cor/Con/CheckoutSession.cpp:276 ]: [Cli                                                                             ent 1-1] Cannot checkout session because a spawning error occurred. The identifi                                                                             er of the error is ee98900d. Please see earlier logs for details about the error

**Comment by picman** [comment]
Could you post what is in log/production.log?

**Comment by nikosfrangakis** [comment]
Hi,
i have a similar problem.

This is the output:

uninitialized constant Redmine::IntegrationTest (NameError)
  /home/i-sense/public_html/sites/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/test/integration_test.rb:24:in `<module:Test>'
  /home/i-sense/public_html/sites/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/test/integration_test.rb:23:in `<module:RedmineDmsf>'
  /home/i-sense/public_html/sites/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/test/integration_test.rb:22:in `<top (required)>'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in `each'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in `block in eager_load!'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in `each'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in `eager_load!'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:356:in `eager_load!'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in `each'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/2.6.0/tsort.rb:347:in `each'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/2.6.0/tsort.rb:347:in `call'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
  /home/i-sense/public_html/sites/redmine/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

**Comment by aanderse** [comment]
I have a similar error: `NameError: uninitialized constant RedmineExtensions`

Unfortunately my production.log only had this:
```
# Logfile created on 2019-04-05 10:56:25 -0400 by logger.rb/v1.2.7
W, [2019-04-05T10:56:32.325284 #9679]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system
```

Using redmine 4.0.2 and dmsf 2.0.0.

Note: I tried to produce more verbose output in production.log by adding the following to additional_environment.rb: `config.logger = Logger.new("/var/lib/redmine/log/production.log", 14, 1048576)`

**Comment by picman** [comment]
@aanderse 
1) Gem redmine_extensions installed?
```
$ gem list | grep redmine_extensions
redmine_extensions (0.2.14, 0.2.8)
```
2)
```ruby
config.logger = Logger.new("#{Rails.root}/log/#{Rails.env}.log", 'daily')
config.log_level = :info # :warn :debug
```

**Comment by picman** [comment]
I'm sorry but I have no clue where is the problem. ```Redmine::IntegrationTest``` is a normal class defined in Redmine. Moreover it's used in tests only and shouldn't be required for the normal run of the application.
During the installation, have you used ```--without test``` option?
```
bundle install --without test
```

**Comment by picman** [comment]
Fixed.

**Comment by betavr** [comment]
@picman Merge this please.
