### ISSUE TITLE
I can not send file by mail

### ISSUE THREAD

**Issue by milenkocvijic** [danmunn/redmine_dmsf#986]
[ActiveJob] [ActionMailer::DeliveryJob] [94c6a336-c74f-4e3a-9bce-198f5c0624d0] Error performing ActionMailer::DeliveryJob (Job ID: 94c6a336-c74f-4e3a-9bce-198f5c0624d0) from Async(mailers) in 1.61ms: Errno::ENOENT (No such file or directory @ rb_sysopen - /tmp/190322082802_dmsf_email_sent_documents.zip):

There is 190322082801_dmsf_zip.zip file in /tmp directory

Thank you

**Comment by picman** [comment]
A big error. Thank you for pointing that out. Fixed also in the _master_ branch, so just call `git pull`.
