### ISSUE TITLE
WARNING: Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by cforce** [danmunn/redmine_dmsf#99]
I can't create any file in the folder via webdav. It look slike the authenication fails althought correct credentails and fallsbacks to anonymous user.

INFO  WEBrick::HTTPServer#start: pid=10530 port=3000
Started PROPFIND "/dmsf/webdav" for 172.25.252.98 at 2013-02-26 14:52:35 +0100
Started PROPFIND "/dmsf/webdav" for 172.25.252.98 at 2013-02-26 14:52:36 +0100
Started OPTIONS "/" for 172.25.252.98 at 2013-02-26 14:52:47 +0100
Processing by WelcomeController#index as HTML
WARNING: Can't verify CSRF token authenticity
  Current user: anonymous
Redirected to http://dev-redmine.domain.loc:3000/login?back_url=http%3A%2F%2Fdev-redmine.domain.loc%3A3000%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 42ms (ActiveRecord: 4.2ms)
Started OPTIONS "/login?back_url=http://dev-redmine.domain.loc:3000/" for 172.25.252.98 at 2013-02-26 14:52:47 +0100
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://dev-redmine.domain.loc:3000/"}
WARNING: Can't verify CSRF token authenticity
  Current user: anonymous
Failed login for '' from 172.25.252.98 at 2013-02-26 13:52:47 UTC
DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in #<Module:0xc8925b8> instead. (called from realtime at /home/sidfunktion/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/benchmark.rb:295)
  Rendered account/login.html.erb within layouts/base (100.2ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.8ms)
  Rendered inline template (0.6ms)
)
Completed 200 OK in 1290ms (Views: 928.8ms | ActiveRecord: 20.2ms)
Started OPTIONS "/dmsf/webdav" for 172.25.252.98 at 2013-02-26 14:52:48 +0100
Started PROPFIND "/dmsf/webdav" for 172.25.252.98 at 2013-02-26 14:52:49 +0100
Started PROPFIND "/dmsf/webdav/spielwiese" for 172.25.252.98 at 2013-02-26 14:52:57 +0100

**Comment by picman** [comment]
Please try again with the latest version.
