### ISSUE TITLE
Cannot preview my doc 

### ISSUE THREAD

**Issue by dny0419** [danmunn/redmine_dmsf#990]
Want to preview Microsoft Office Documents in DMSF

**Comment by picman** [comment]
Why have you closed it? No more interested in such a feature?

**Comment by dny0419** [comment]
> Why have you closed it? No more interested in such a feature?

sry i just fixed it with another plugin. Thanks.

**Comment by chengpeng321** [comment]
可以说一下你使用了什么插件解决了这个问题吗？
