### ISSUE TITLE
 No such file to load -- mime/types.rb (LoadError)

### ISSUE THREAD

**Issue by elmaogullari** [danmunn/redmine_dmsf#992]
Hi, 

I am trying a fresh install of dmsf plugin. 
My environment is (Ubuntu16.04.06 - Ruby 2.6 - Redmine 4.0 Stable SVN)
Everything seems fine while installation but when i restart Apache, I am getting error below.  
I tried both master and development releases.

Thank you. 
---
/usr/lib/ruby/2.6.0/fileutils/version.rb:4: warning: already initialized constant FileUtils::VERSION
/var/lib/gems/2.6.0/gems/fileutils-1.2.0/lib/fileutils/version.rb:4: warning: previous definition of VERSION was here
/usr/lib/ruby/2.6.0/fileutils.rb:1267: warning: already initialized constant FileUtils::Entry_::S_IF_DOOR
/var/lib/gems/2.6.0/gems/fileutils-1.2.0/lib/fileutils.rb:1267: warning: previous definition of S_IF_DOOR was here
/usr/lib/ruby/2.6.0/fileutils.rb:1540: warning: already initialized constant FileUtils::Entry_::DIRECTORY_TERM
/var/lib/gems/2.6.0/gems/fileutils-1.2.0/lib/fileutils.rb:1547: warning: previous definition of DIRECTORY_TERM was here
/usr/lib/ruby/2.6.0/fileutils.rb:1542: warning: already initialized constant FileUtils::Entry_::SYSCASE
/var/lib/gems/2.6.0/gems/fileutils-1.2.0/lib/fileutils.rb:1549: warning: previous definition of SYSCASE was here
/usr/lib/ruby/2.6.0/fileutils.rb:1595: warning: already initialized constant FileUtils::OPT_TABLE
/var/lib/gems/2.6.0/gems/fileutils-1.2.0/lib/fileutils.rb:1602: warning: previous definition of OPT_TABLE was here
/usr/lib/ruby/2.6.0/fileutils.rb:1649: warning: already initialized constant FileUtils::LOW_METHODS
/var/lib/gems/2.6.0/gems/fileutils-1.2.0/lib/fileutils.rb:1656: warning: previous definition of LOW_METHODS was here
/usr/lib/ruby/2.6.0/fileutils.rb:1656: warning: already initialized constant FileUtils::METHODS
/var/lib/gems/2.6.0/gems/fileutils-1.2.0/lib/fileutils.rb:1663: warning: previous definition of METHODS was here
Error: The application encountered the following error: No such file to load -- mime/types.rb (LoadError)
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
    /data/redmine/redmine-4.0/plugins/redmine_dmsf/lib/dav4rack/resources/mongo_resource.rb:4:in `<top (required)>'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:378:in `block in require_or_load'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in `load_interlock'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:356:in `require_or_load'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:334:in `depend_on'
    /var/lib/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:246:in `require_dependency'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in `each'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in `block in eager_load!'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in `each'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in `eager_load!'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:356:in `eager_load!'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in `each'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
    /usr/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
    /usr/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    /usr/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
    /usr/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
    /usr/lib/ruby/2.6.0/tsort.rb:347:in `each'
    /usr/lib/ruby/2.6.0/tsort.rb:347:in `call'
    /usr/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
    /usr/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
    /usr/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
    /var/lib/gems/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
    /data/redmine/redmine-4.0/config/environment.rb:14:in `<top (required)>'
    config.ru:3:in `require'
    config.ru:3:in `block in <main>'
    /var/lib/gems/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
    /var/lib/gems/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
    config.ru:1:in `new'
    config.ru:1:in `<main>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

**Comment by goodnewz** [comment]
I am having exactly the same issues. However I  am on redmine 4.0.3. No issues with 4.0.2. The issue seem related to the gem activesupport above version 5.2.2 (e.g. 5.2.2.1 and higher). Consistent with the gentleman who initiate the post.

**Comment by elmaogullari** [comment]
It was a good catch. I tried all variations for ruby and dmsf. but redmine 4.0.3 .  Result was same.
Just tried with 4.0.2 and it works. 
I don't understand deeply ruby and gems but when i look at activesupport change log ;

Issue must be something about this.

Fix String#safe_constantize throwing a LoadError for incorrectly cased constant references.

**Comment by ahorek** [comment]
hi @elmaogullari, good catch, here's an explanation:
1/ mime_types were removed and replaced by mini_mime in redmine 4.0.0 http://www.redmine.org/issues/29359
2/ there was a change in redmine 4.0.3 http://www.redmine.org/issues/30753 basically all libraries in eager_load paths are preloaded in production

ping @picman does dms even use mongo? this file explicitely requires mongo and mime/types, but these gems aren't part of the Gemfile.
https://github.com/danmunn/redmine_dmsf/blob/master/lib/dav4rack/resources/mongo_resource.rb#L4
https://github.com/danmunn/redmine_dmsf/blob/master/lib/dav4rack/resources/mongo_resource.rb#L259

**Comment by picman** [comment]
So either

a) add gem _mime_type_ and _mongo_ into the _Gemfile_
or
b) remove lib/dav4rack/resources/mongo_resource.rb (It's not use in DMSF)

I'd vote for the solution _a)_ as dav4rack is copied as a package and it doesn't make sense to make there local changes. What do you think?

**Comment by ahorek** [comment]
the intention was to get rid of mime_types, see http://www.redmine.org/issues/29359 or https://github.com/mikel/mail/pull/1059 .
I know dav4rack is just a fork of a fork but adding a dependencies that won't be used anyway doesn't seem right to me. I would vote for b/

btw dms tests are passing, because eager_load is disabled in tests https://github.com/redmine/redmine/blob/master/config/environments/test.rb#L15

**Comment by elmaogullari** [comment]
I will try it again.  But as far as i remember adding mongo and mime_types did not work while installation.

**Comment by picman** [comment]
@elmaogullari Could you test the branch devel-2.0.1? If it works, I'd fix the master branch too.

**Comment by elmaogullari** [comment]
It was a very dirty/quick test but if i did not make any mistake  ; 

Error: The application encountered the following error: uninitialized constant Redmine::IntegrationTest (NameError)
    /data/redmine/redmine-4.0/plugins/redmine_dmsf/lib/redmine_dmsf/test/integration_test.rb:24:in `<module:Test>'
    /data/redmine/redmine-4.0/plugins/redmine_dmsf/lib/redmine_dmsf/test/integration_test.rb:23:in `<module:RedmineDmsf>'
    /data/redmine/redmine-4.0/plugins/redmine_dmsf/lib/redmine_dmsf/test/integration_test.rb:22:in `<top (required)>'
    /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'

**Comment by picman** [comment]
Fixed.

**Comment by tainewoo** [comment]
Hi Picman,

sorry just a question, when will this fix be merged to master?
i tested the tip code on master and still meets this issue.
And after i modified the file according to https://github.com/danmunn/redmine_dmsf/pull/998/commits/8c430bec6ace934412f71a2c2269deaa96778d34
the fails stills.
After i deleted the lib/dav4rack/resources/mongo_resource.rb , it works for me.
Tested on Redmine-4.0.3

**Comment by picman** [comment]
Probably September.

**Comment by p1xelshader** [comment]
Hi Picman.  Thanks for working on this plugin, just wanted to say that I encountered the same problem as others while trying to migrate to Redmine 4.0.4 and cannot currently move past Redmine 4.0.2 as we rely on the DMSF plugin.  Do you have any update on the next master please?  I'm happy to test if you need feedback.  Cheers dude!

**Comment by picman** [comment]
I'm in the testing phase now. Two more weeks needed.
