### ISSUE TITLE
Missing gems mime-types and mongo

### ISSUE THREAD

**Issue by lutra** [danmunn/redmine_dmsf#994]
I've installed the last version [v2.0.0](https://github.com/danmunn/redmine_dmsf/releases/tag/v2.0.0) directly from git. But had to install some additional gems:
- mime-types
  This may be related to #992. But after inserting into `Gemfile.local` everything worked fine.
- mongo
  This gem is required by file `lib/dav4rack/resources/mongo_resource.rb`

**Comment by picman** [comment]
Duplicates #992
