### ISSUE TITLE
DMSF path directory changing 

### ISSUE THREAD

**Issue by wbeji** [danmunn/redmine_dmsf#999]
Dear community,
i have an issue with my attachment  after changing of the default file directory path.
the space of the old  location is still decreasing and the new files are not uploaded due to the space limitation.
Could please support me to resolve this issue?
Please let me know if you need any further infomartion.

Thanks in advance

![production_rb](https://user-images.githubusercontent.com/3382286/56472431-b05b7d00-645e-11e9-968c-00164e5684f0.PNG)
![space](https://user-images.githubusercontent.com/3382286/56472436-b6e9f480-645e-11e9-90e2-0fdbad5232dd.PNG)
![plugin](https://user-images.githubusercontent.com/3382286/56472440-bb161200-645e-11e9-9a3e-64cde96143a0.PNG)

![dmsf](https://user-images.githubusercontent.com/3382286/56472469-10522380-645f-11e9-9fbe-55f31d83d8ed.PNG)

**Comment by picman** [comment]
1. Have you reestarted the application after the settings change?
2. Check the production.log when you download an uploaded document from where are the files taken.

**Comment by wbeji** [comment]
Hello Picman,

thanks for your reply!
I restarted the application  many time.
I uploaded a file and i downloaded it in order to check the log file, please see the attachment of the last records in the production log file.
![image](https://user-images.githubusercontent.com/3382286/56575500-2af2dc80-65c6-11e9-936a-9c16e499bc76.png)

**Comment by picman** [comment]
As I can see in the log file, a file was successfully downloaded from /var/files. So where is the problem? Maybe there is insufficient space in */tmp* dir. Check the log file in case of an unsuccessful upload.

**Comment by wbeji** [comment]
do you mean the tmp file witch stetted in the plugin settings below or is there any tmp file which i'm not aware about it?

![image](https://user-images.githubusercontent.com/3382286/56579956-be7dda80-65d1-11e9-821c-743e41f91ba8.png)

**Comment by picman** [comment]
No I mean the system */tmp* folder. Rails uses the system *tmp* independently of the DMSF settings. But you will see it in the *production.log*.

**Comment by kmmizouri** [comment]
@picman you are actually right. The /tmp file is under the <ROOT_PATH> and we couldn't change it to for example /home/tmp because the / is only 19GB and it's already full. 
We tried to change the tmp of the whole ENV by adding 
A config to the Initialization of the redmine but it crushes.
